### ISSUE TITLE
Validate use of streaming gRPC calls

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#10133]
As reported in https://github.com/grpc/grpc-dotnet/issues/2086, streaming gRPC calls can cause a memory leak if the original gRPC call isn't disposed of *and* we don't read to the end of the response stream. (And if we dispose of the call without reading to the end of the response stream, that will abort the request which probably isn't ideal.)

We should check our hand-written code for uses of bidi/server-streaming calls (I'm thinking particularly of Firestore and Spanner, but there may be more) to check that we're disposing of everything correctly. (Separately, our wrapper types should implement IDisposable.)

**Comment by meredithslota** [comment]
Probably also Pub/Sub but I'm not clear on the scope of handwritten code there.

**Comment by Rishabh-V** [comment]
Right @meredithslota. We have already identified the code changes needed in BigTable, Firestore, PubSub and Spanner. Jon has already implemented the `IDisposable` on the bidi/server streams in GAX. Once the GAX changes are in, we can make the relevant changes in these libraries. Thanks.
