### ISSUE TITLE
Unable to publish message to GCP PubSub from .NET app behind a proxy

### ISSUE THREAD

**Issue by nhakimia** [googleapis/google-cloud-dotnet#10195]
Unable to publish message to GCP PubSub from .NET app behind a proxy

Environment details
OS: 
Windows Enterprise 2010
.NET version:
6.0
Package name and version:
Google.Cloud.PubSub.V1 3.4.0
Steps to reproduce
Close the internet on a server and allow only to pass via a proxy
Try to publish a message using this code:
var projectId = "your project id"; 
            var topicId = "your topic id";
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", "path to your key");
            var topicName = new TopicName(projectId, topicId);
            PublisherClient publisher = PublisherClient.Create(topicName);

            // Create a message
            var message = new PubsubMessage()
            {
                Data = ByteString.CopyFromUtf8("hello world")
            };
            
            // Publish it
            Console.WriteLine("Publishing...");
            var response = publisher.PublishAsync(message).Result;

**Error received:**
Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.

Thanks!

@jskeet

**Comment by amanda-tarafa** [comment]
This looks more like your proxy does not support HTTP/2 wich is required for gRPC.

Can you find about your proxy configuration etc. from your system admins?

**Comment by nhakimia** [comment]
My problem is solved. The issue was that the pubsub.googleapis.com certificat was not trusted by our firewall. Our firewall team add the url to the groupe nodecrypt.
Thank you for your help!

**Comment by jskeet** [comment]
Glad it's sorted.
