### ISSUE TITLE
CloudFunctions V2 Create Operation Returns Error 

### ISSUE THREAD

**Issue by JohnnyWombwell** [googleapis/google-cloud-dotnet#10243]
Hi

I'm attempting to update an application from `Google.Apis.CloudFunctions.v1` to `v2`.

While the application works fine with the v1 libraries and I can successfully deploy gen2 functions via gcloud CLI, when executing the following call:

```csharp
var createOperation = cloudFunctionService
    .Projects
    .Locations
    .Functions
    .Create(function, $"projects/my-project/locations/us-east1");
```
I receive the following response:

```
HttpStatusCode is BadRequest.
Google.Apis.Requests.RequestError
Malformed name: 'projects/my-project/locations/us-east1/functions/' [400]
Errors [
        Message[Malformed name: 'projects/my-project/locations/us-east1/functions/'] Location[ - ] Reason[badRequest] Domain[global]
]
```
The content of the function object does not appear to make a difference. I incrementally removed properties even a completely empty object produces the same result.

Am I missing something?

Any help would be appreciated.

**Comment by jskeet** [comment]
Firstly, for future issues around packages starting `Google.Apis`, please file issues in https://github.com/googleapis/google-api-dotnet-client as that's the repo that those packages live in.

But fundamentally, it sounds like this probably isn't a client library issue so much as one about what is required in the create request - and that's something that the maintainers of the client libraries don't have experience of.

Looking at the [documentation](https://cloud.google.com/functions/docs/reference/rest/v2/projects.locations.functions/create), it does look like you're currently missing the query parameter for the ID of the new function.

So I suspect you want:

```csharp
var createOperation = cloudFunctionService
    .Projects
    .Locations
    .Functions
    .Create(function, $"projects/my-project/locations/us-east1");
createOperation.FunctionId = "my-function-id";
```

If that doesn't help, I would suggest using the "Try This Method" part of [the Functions reference documentation](https://cloud.google.com/functions/docs/reference/rest/v2/projects.locations.functions/create) - once you've got an API request that succeeds, hopefully you'll be able to translate that into C# code. If you have trouble with that C# code, please file a new issue (in https://github.com/googleapis/google-api-dotnet-client) showing what API call you're trying to make, the C# code you've tried, and the result.

**Comment by JohnnyWombwell** [comment]
Wow, thanks for taking the time to respond to this so quickly.

And best of all, your suggested worked!

Many thanks!
