### ISSUE TITLE
Clients created by `SubscriberClient` and `PublisherClient` are not disposed

### ISSUE THREAD

**Issue by jeffijoe** [googleapis/google-cloud-dotnet#10304]
I have observed that none of the underlying gRPC channels are disposed when disposing any of the clients.

We use a lot of Pub/Sub topics and subscriptions in our application (>60 topics + at least one subscription per topic). I am running into the operating system's max open files limit `Too many open files` when running our integration test suite which spins up our application with real connections to the PubSub emulator.

We also manually construct clients via `PublisherServiceApiClientBuilder` and `SubscriberServiceApiClientBuilder` in order to set up topics and subscriptions.

I have been digging into the library source, and doing the following seems to dispose channels created by `PublisherServiceApiClientBuilder` and `SubscriberServiceApiClientBuilder`:

```csharp
var builder = new SubscriberServiceApiClientBuilder
{
    // .. options omitted for brevity
};
var subscriberService = await builder.BuildAsync();

// Later..
if (builder.LastCreatedChannel is IDisposable disposable)
{
    disposable.Dispose();
}
```

However, I was not so lucky with `PublisherClient` and `SubscriberClient`. Looking at the source, I see that shutdown sequences are configured like so:

https://github.com/googleapis/google-cloud-dotnet/blob/d4e696b126046a162870fabb092118fa58ed3b86/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherClientBuilder.cs#L129

I then went to check out the `GrpcChannel` implementation of `ChannelBase` in `grpc-dotnet`, and it appears that the virtual `ShutdownAsync` method is not implemented, so it therefore no-ops. The proper way to dispose the channel is with [`Dispose`](https://github.com/grpc/grpc-dotnet/blob/9427a740a468e10c1daa2443061d2d1609bf1777/src/Grpc.Net.Client/GrpcChannel.cs#L730-L734), which isn't being called by this library.

Ideally, `grpc-dotnet` would just implement `ShutdownAsync` and call `Dispose` there, so I am not sure if this is the right place to report this or if I should report it over there?

#### Environment details

  - OS: macOS Ventura
  - .NET version: 7
  - Package name and version: Google.Cloud.PubSub.V1 @ 3.5.0

#### Steps to reproduce

  1. Create a `SubscriberClient` and `StartAsync`, then later `StopAsync`.
  2. Before terminating the host process, observe that there are still open connections to PubSub using `lsof`

**Comment by jskeet** [comment]
I think it's fine for us to call Dispose in `shutdowns`, although the sync/async disparity is unfortunate. Thanks for reporting this - we'll look into it soon.

(The aspect of the clients *generally* not implementing IDisposable itself is complex - by default, all clients will share the same channel, so you don't want to dispose of that when disposing a single client. But if you're constructing a client in a way that doesn't allow the use of a channel pool, it *would* be good to make it disposable. There's a little more detail in the [client lifecycle help page](https://cloud.google.com/dotnet/docs/reference/help/client-lifecycle#clean-up).)

**Comment by jeffijoe** [comment]
How about making the builders themselves disposable? If they detect that `CanUseChannelPool` is `false`, then dispose any channels that they created?

**Comment by jskeet** [comment]
No, I don't think that the builder should be disposable - because normally by the time you're done with a client, the builder is *long* gone. In the future it's likely that the builder will signal to the client how it *should* handle disposal though. Then there's just the sync/async clean-up impedance mismatch to deal with.
(That's not likely to be any time soon though - it'll be at the next major version of GAX and all client libraries.)

**Comment by jeffijoe** [comment]
That makes sense.

> That's not likely to be any time soon though

But will there be some sort of fix available soon for the issue at hand? At least some way that I can manually dispose of a client when it is no longer needed and have the channels dispose with it? Right now I am only able to dispose the `*ServiceApiClient`s that I create for topic/subscription management, but not the publisher and subscriber high-level clients.

**Comment by jskeet** [comment]
> But will there be some sort of fix available soon for the issue at hand?

Yes, we should be able to do that much sooner. (I'm not going to give a guaranteed timeline right now, but it's definitely not "wait for a major release" territory by any means.)

**Comment by jeffijoe** [comment]
Looks like there is an [issue in `grpc-net` regarding `ShutdownAsync`](https://github.com/grpc/grpc-dotnet/issues/1712).

**Comment by Rishabh-V** [comment]
Fixed via #10307. The fix will be available in the next release.

**Comment by jskeet** [comment]
Version 3.5.1 is now published - please give it a try.

**Comment by jeffijoe** [comment]
It works, thank you so much for shipping this so fast! 🙌
