### ISSUE TITLE
Incorrect documentation for FlowControlSettings.maxOutstandingElementCount?

### ISSUE THREAD

**Issue by vilmacs** [googleapis/google-cloud-dotnet#10358]
Each client pulls maxOutstandingElementCount messages (which is fine i guess) but this will lead to clientCount*maxOutstandingElementCount    outstanding elements, yet we also use maxOutstandingElementCount to limit processing of messages across all clients so it's more accurantly named "maxProcessingMessages" .  I think two independent fields would have been better.

The documentation claims that setting FlowControlSettings.maxOutstandingElementCount will limit the number of outstanding messages.

https://github.com/googleapis/gax-dotnet/blob/main/Google.Api.Gax/FlowControlSettings.cs

"The maximum number of elements that can be outstanding before data flow is restricted"

Consider when there are multiple clients (ClientCount is greater then 1)  which will happen by default on any multi-processor machine.  We'll supply maxOutstandingElementCount as the PullRequest.maxMessages  for EACH client: 

https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClientImpl.SingleChannel.cs#L313

Yet the same Flow object is used for all clients which mean over all clients only maxOustandingElementCount messages are processed: https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClientImpl.cs#L135

So with a client count of 10,   there will be 10 times the number of "oustanding messsages" then are concurrently being processed. 

Just seems odd to me that we use the same field for both, and the documentation doesn't match my understanding of what an "outstanding" message is in a pub/sub subscriber context. 

Perhaps two independent fields for this would be better. 
thanks

**Comment by amanda-tarafa** [comment]
Assigning to @jskeet as he will have better context than I.

I think it all depends on whether [StreamingPullRequest.max_outstanding_messages](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#streamingpullrequest) is in relation to the subscription as a whole or to the individual streaming clients. From docs (link above) it seems to be the latter in which case, as far as I can see you are right that we are pulling client count times more messages than we are prepared to handle concurrently.

**Comment by jskeet** [comment]
I'll reassign this to @Rishabh-V who has been in closer contact with the PubSub team - even though FlowControlSettings and BatchingSettings are in GAX (as we incorrectly anticipated using them more widely), they're only used by PubSub, and I'm sure we're following the PubSub team's guidelines for how to apply them.

We can definitely tweak the documentation in GAX, but as it's a "general" class (at the moment; we should consider moving it into just PubSub at the next major version; I'll note that in internal docs) it's quite hard to be definitive.

**Comment by Rishabh-V** [comment]
Closed via #10366 and https://github.com/googleapis/gax-dotnet/pull/694
Updated documentation will be available in the library with the next release.
