### ISSUE TITLE
Question: how does streaming-pull flow control work?

### ISSUE THREAD

**Issue by jeffijoe** [googleapis/google-cloud-dotnet#10390]
> This issue is not a problem report, just a question out of curiosity as to how flow control works.

I have been digging into the codebase as I was investigating the issues I posted recently, and one thing I noticed was that flow control is configured on the streaming pull request here:

https://github.com/googleapis/google-cloud-dotnet/blob/d509ccddfa2c09b7846a2fd5027e3c0454e7c51f/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClientImpl.SingleChannel.cs#L313-L315

However:
* The `Flow` structure is still being used to manage flow control on the client-side when `_useLegacyFlowControl` is `false`.
* The `StreamingPull` call is not being used for sending ACKs and deadline modifications; the RPC calls are used instead.

When looking at the `pubsub.proto` definitions, I see the [following documentation](https://github.com/googleapis/googleapis/blob/53a0be29c4a95a1d3b4c0d3a7a2ac8b52af2a3c0/google/pubsub/v1/pubsub.proto#L1315-L1335) for the flow control settings:

```
  // Flow control settings for the maximum number of outstanding messages. When
  // there are `max_outstanding_messages` or more currently sent to the
  // streaming pull client that have not yet been acked or nacked, the server
  // stops sending more messages. The sending of messages resumes once the
  // number of outstanding messages is less than this value. If the value is
  // <= 0, there is no limit to the number of outstanding messages. This
  // property can only be set on the initial StreamingPullRequest. If it is set
  // on a subsequent request, the stream will be aborted with status
  // `INVALID_ARGUMENT`.
  int64 max_outstanding_messages = 7;
```

Specifically, the `currently sent to the streaming pull client` is what caught my eye. This, to me, sounds like that in order for the server-side flow control settings to work, the client must also be sending the requests for ACK/deadline extensions through the same stream? If I am understanding the rest of the code correctly, the RPC requests may be sent from any of the spawned clients, all of which may potentially be connected to different [subscribing forwarders](https://cloud.google.com/pubsub/architecture#:~:text=Subscribers%20receive%20messages%20by%20connecting%20to%20subscribing%20forwarders%2C)?

Obviously, the client-side implementation will enable natural backpressure propagation, but I figured that server-side flow control would eliminate the need for it on the client.

Feel free to close this issue right away as it's just a question. 😄

**Comment by jskeet** [comment]
I've assigned this to @Rishabh-V as he knows the most about Pub/Sub in our team. However, I believe he's now finished working for the day and won't be back until Tuesday, so it may be a while before he's able to answer.

**Comment by Rishabh-V** [comment]
Hi @jeffijoe, I am checking internally. I will update this thread when I have more details. Thanks.

**Comment by Rishabh-V** [comment]
Hi @jeffijoe, The library is working as expected. Please see [this documentation](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#streamingpullrequest:~:text=(received%20on%20this%20stream%20or%20a%20different%20stream)) which states that ack_ids can be the previously received messages (received on this stream or a different stream), so there is no need to send the Ack/modify ack requests on the same stream. The [flow control settings in the initial request](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#streamingpullrequest:~:text=of%20outstanding%20messages.-,This%20property%20can%20only%20be%20set%20on%20the%20initial%20StreamingPullRequest.,-If%20it%20is) is enough for server side flow control. Thanks.

I hope this answers your question.

**Comment by kamalaboulhosn** [comment]
@jeffijoe The questions about how the server tracks outstanding messages is really internal details that we don't want to get into and aren't really necessary to understand. The use of ack/modack as they are (not on the stream) is intentional.

The history of flow control that in the beginning, only client-side flow control existed and then server-side flow control was added later. The decision was made to pass the flow control settings per stream rather than dividing the values among the number of streams. As a result, client-side flow control was kept in place to deal with the case of having multiple streams in a single client. 

If you were to have three clients then yes, the flow control limit would be 3000 if each one were set to a max message count of 1000.

`client_id` does not need to be set necessarily, so it should have no impact on flow control.

**Comment by kamalaboulhosn** [comment]
Either will work, but for the lowest latency at the highest throughput, it can be best to reserve the stream strictly for the delivery of messages.

**Comment by jeffijoe** [comment]
Thank you @kamalaboulhosn and @Rishabh-V !
