### ISSUE TITLE
Can't find any minimal working example of logging

### ISSUE THREAD

**Issue by charring** [googleapis/google-cloud-dotnet#10438]
I made this example based upon reading the docs and issues. The app below works in Cloud Run but on see no logs in the Logs Explorer. I've done some googling but have not found a single complete example of using Google.Cloud.Diagnostics.AspNetCore3 for logging. Below is my attempt at a complete example. Using .NET 7.

    using Google.Cloud.Diagnostics.Common;
    using Google.Cloud.Diagnostics.AspNetCore3;

    var builder = WebApplication.CreateBuilder(args);
    var config = builder.Configuration;

    builder.Logging.ClearProviders();

    builder.Services.AddGoogleDiagnosticsForAspNetCore(
        loggingOptions: new LoggingServiceOptions
        {
             Options = LoggingOptions.Create(logLevel: LogLevel.Debug)
        }
    );

    var port = Environment.GetEnvironmentVariable("PORT") ?? "8080";
    var url = $"http://0.0.0.0:{port}";
    builder.WebHost.UseUrls(url);

    var app = builder.Build();

    app.MapGet("/", (ILogger<Program> logger) => {
        logger.LogInformation("In root endpoint");
        return Results.Ok("Hello World");
    });

    app.Run();

**Comment by amanda-tarafa** [comment]
Please take a look at the note in the [Google.Cloud.Diagnostics.AspNetCore3 documentation](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Diagnostics.AspNetCore3/latest):

> Some environments limit or disable CPU usage for background activities, while some others allow you to configure CPU allocation for request processing only. When running on environments with limited CPU for background activities, take care not to use the timed buffer options for any of Logging, Tracing or Error Reporting. Take into account that the timed buffer is used for the Logging and Tracing components by default so you will need to explicitly configure the buffers by using the Google.Cloud.Diagnostics.Common.LoggerOptions and Google.Cloud.Diagnostics.Common.TraceOptions classes. The Error Reporting component does not buffer entries by default. See the Google.Cloud.Diagnostics.Common documentation for more information on buffers. Here you can read more about CPU allocation in Google Cloud Run.

There are examples on the documentation on how to configure the components, etc.

But, do consider using [Google.Cloud.Logging.Console](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Logging.Console/latest) instead. It will write structure log entries to stdout, which are picked up by logging agents present in Google Cloud Environments, like Cloud Run, AppEngine Flex, etc.

**Comment by charring** [comment]
That is the guide that was the basis of my minimal test program. But again I see nothing in the log. Most libraries show in their documentation a minimal "hello world" type of sample, and that's what I am looking for. What is the minimal configuration needed to achieve logging in Cloud Run?

You mentioned Google.Cloud.Logging.Console. Another question I have is what benefit/capability does Google.Cloud.Diagnostics.AspNetCore3 give a developer? That isn't mentioned anywhere that I have found.

**Comment by charring** [comment]
I made this minimal example using Google.Cloud.Logging.Console. 

    using Google.Cloud.Diagnostics.Common;
    using Google.Cloud.Logging.Console;

    var builder = WebApplication.CreateBuilder(args);
    var isDevelopment = builder.Environment.IsDevelopment();
    var config = builder.Configuration;

    builder.Logging.AddGoogleCloudConsole(options => {
        options.IncludeScopes = true;
        options.TraceGoogleCloudProjectId = config["GCP:ID"];
    });

    var port = Environment.GetEnvironmentVariable("PORT") ?? "8080";
    var url = $"http://0.0.0.0:{port}";
    builder.WebHost.UseUrls(url);

    var app = builder.Build();

    app.MapGet("/", (ILogger<Program> logger) => {
        logger.LogInformation("In root endpoint");
        return Results.Ok("Hello World!");
    });

    app.Run();

As it also wasn't logging, I had a closer look at my Log Explorer window, and noticed that by default it had launched with a particular revision in the query. Removing the revision resulted in my seeing the logs. I also see the logs from the previous test using Google.Cloud.Diagnostics.AspNetCore3.

Now I'm hoping that someone can chime in on the pros and cons of these two libraries.
