### ISSUE TITLE
Google.Cloud.Firestore: Backoff on FirestoreDb.RunTransactionAsync retry

### ISSUE THREAD

**Issue by kasperhhk** [googleapis/google-cloud-dotnet#10513]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Regarding [RunTransactionAsync](https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/FirestoreDb.cs#L389) on the FirestoreDb class in the Google.Cloud.Firestore package.

When we call it with `MaxAttempts > 1` option, then we would like to have some sort of backoff policy, in our case for data contention, so that it does not spam the document when it is already in contention.
(note there is a `backoff` variable that is unused in the source code, not really relevant to the solution proposed below though)

 **Describe the solution you'd like**
Either a backoff policy similar to what we see in the `_batchGetCallSettings` field or being able to pass an optional backoff policy to the method / client.
There's the issue of backwards compatibility, so maybe it does need to configurable by the user, defaulting to current behavior (no backoff).

 **Describe alternatives you've considered**
Currently we're implementing our own backoff policy, wrapping around the firestoredb, but since you already have a backoff concept, it seemed reasonable to add it here as well.

 **Additional context**
I admit that I'm a bit unsure if there's some internal backoff policy inside the lower internal functions that I haven't been able to divine, but from what I could see there's nothing obvious going on, so please correct me if there's anything I've misunderstood.

**Comment by jskeet** [comment]
This sounds entirely reasonable, but we'll need to talk with the Firestore SDK team - we'll want to make sure that we're consistent with other languages.

**Comment by jskeet** [comment]
I've talked with the Firestore team, and they're going to write an internal document to design how this can be achieved consistently across languages. Thanks for bringing it up.

**Comment by jskeet** [comment]
Just to avoid leaving you *completely* in the dark - this is still bubbling along. I'm hoping we'll get somewhere "soonish" but I can't make any promises about a timeline. We haven't forgotten about it though.

**Comment by jskeet** [comment]
@kasperhhk: Thinking about this in terms of what I'm doing for #11322, would a FirestoreDb-wide setting for retry configuration work for you? I can imagine some times when you might want per-call settings, but if we were to expose a `FirestoreDbBuilder.RunTransactionRetrySettings` property, would that at least get most of the way there?

**Comment by jskeet** [comment]
Actually, I now wonder whether we should just have a RetrySettings in TransactionOptions, given that that's got MaxAttempts already. (We'd probably need some sort of precedence - if the RetrySettings is specified, that overrides MaxAttempts, given that a RetrySettings effectively includes max attempts already.)

**Comment by jskeet** [comment]
@kasperhhk: If you could have a look at #11564 and add any thoughts about the API, that would be much appreciated. If you're happy with it, I'll write appropriate tests and check whether the Firestore team is okay with it too.
