### ISSUE TITLE
Google.Analytics.Data.V1Beta 2.0.0-beta03 Version mismatches

### ISSUE THREAD

**Issue by pjninnis** [googleapis/google-cloud-dotnet#10532]
#### Environment details

  - OS: Windows
  - .NET version: NetFramework v4.8
  - Package name and version: Google.Analytics.Data.V1Beta 2.0.0-beta03 

#### Steps to reproduce

I'm having an issue with the Google.Analytics.Data.V1Beta 2.0.0-beta03 Nuget in a simple NetFramework v4.8 Project.
Installing the Nuget, and it pulls in numerous Google and Grpc packages, in particular Google.Apis.Auth 1.58.0
but at runtime, it seems to be explicitly accessing 1.46.0 of this library, resulting is the following error:
"Could not load file or assembly 'Google.Apis.Auth, Version=1.46.0.0"

I am not using any other Google Nugets, onlyfor Google.Analytics.Data.V1Beta
I can't downgrade the Google.Apis.Auth to the lower version, because 1.58.0 is the defined minimum version.
I also tried adding Redirect Bindings in the app.config to specify using the 1.58.0 version, but to no avail.

My code is very simple and I just need to retrieve Report Data from GA4, namely:

var client = await new BetaAnalyticsDataClientBuilder
{
    JsonCredentials = credentials,
    GrpcAdapter = RestGrpcAdapter.Default,
}.BuildAsync();

... RunReportRequest setup ...

var response = await client.RunReportAsync(request);

**Comment by jskeet** [comment]
Please post your project file - it would be *really* odd for anything to depend on Google.Apis.Auth 1.46.0, which was from 2020. Are you sure it's not Grpc.Auth?

Here's a sample console app that doesn't "work" (because the request is invalid) but runs without any dependency issues:

As an aside, is there any particular reason you're using the RestGrpcAdapter? I'd normally encourage you to use the default adapter unless you have specific reasons for avoiding HTTP/2.0.

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Analytics.Data.V1Beta" Version="2.0.0-beta03" />
  </ItemGroup>

</Project>
```

Code:

```csharp
using Google.Analytics.Data.V1Beta;
using System;
using System.Threading.Tasks;

class Program
{
    static async Task Main()
    {
        var client = await BetaAnalyticsDataClient.CreateAsync();
        var request = new RunReportRequest();
        var response = await client.RunReportAsync(request);
        Console.WriteLine(response);
    }
}
```

Result:

```text
Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode="PermissionDenied", ...)
```

(The failure is expected as I haven't enabled the API in my project.)

**Comment by pjninnis** [comment]
Thanks for the very quick response, jskeet.

Project file is:
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>10</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="10.1.1" />
        <PackageReference Include="Google.Analytics.Data.V1Beta" Version="2.0.0-beta03" />
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="6.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.0.3" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
        <PackageReference Include="System.Buffers" Version="4.4.0" />
        <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.5.1" />
        <PackageReference Include="System.Memory" Version="4.5.3" />
        <PackageReference Include="System.Numerics.Vectors" Version="4.4.0" />
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.3" />
        <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
        <PackageReference Include="System.ValueTuple" Version="4.5.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NoQV2.BusinessModel\NoQV2.BusinessModel.csproj" />
        <ProjectReference Include="..\NoQV2.Common\NoQV2.Common.csproj" />
        <ProjectReference Include="..\NoQV2.Providers.Storage\NoQV2.Providers.Storage.csproj" />
        <ProjectReference Include="..\NoQV2.Services\NoQV2.Services.csproj" />
    </ItemGroup>
</Project>
```

Only the Google.Analytics.Data.V1Beta is explicitly included, but the package manager says that the following are Implicitly Installed in the project because of it:
```
Google.Api.CommonProtos (2.7.0)
Google.Api.Gax (4.3.0)
Google.Api.Gax.Grpc (4.3.0)
Google.Apis (1.58.0)
Google.Apis.Auth (1.58.0)
Google.Apis.Core (1.58.0)
Google.Protobuf (3.21.0)
Grpc.Auth (2.51.0)
Grpc.Core (2.46.5)
Grpc.Core.Api (2.51.0)
Grpc.Net.Client (2.51.0)
Grpc.Net.Common (2.51.0)

```

**Comment by jskeet** [comment]
You've got dependencies on a lot of other projects there... are you able to reproduce this in a standalone project? (Until we can reproduce this, it's going to be hard to help you.)

The other NuGet packages being included implicitly is fine.

I've just tried running my sample code with your list of NuGet packages, and that's working as before.

**Comment by pjninnis** [comment]
Ok, even more strangely...
I've created a standalone Unit Test project that calls the project to get the data and it is working!
BUT calling to project to get the data as part of the larger program is still failing. Both the Test project and the program project caller are also NetFramework v4.8

Tracing through the error, and the exception is getting thrown when creating the client

```
       try
        {
            client = await new BetaAnalyticsDataClientBuilder
            {
                JsonCredentials = credentials
            }.BuildAsync();
        }
        catch (Exception e)
        {
            logger.Error("Unable to create Google Analytics Data Client", e);
            throw;
        }
```
Stacktrace is:

```
System.IO.FileLoadException: Could not load file or assembly 'Google.Apis.Auth, Version=1.46.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Google.Apis.Auth, Version=1.46.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab'
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.<GetChannelCredentialsAsync>d__80.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.GetChannelCredentialsAsync(CancellationToken cancellationToken)
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.<CreateCallInvokerAsync>d__78.MoveNext() in /_/Google.Api.Gax.Grpc/ClientBuilderBase.cs:line 399
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Analytics.Data.V1Beta.BetaAnalyticsDataClientBuilder.<BuildAsyncImpl>d__10.MoveNext() in /_/apis/Google.Analytics.Data.V1Beta/Google.Analytics.Data.V1Beta/BetaAnalyticsDataClient.g.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NoQV2.Services.Google.Impl.GoogleAnalytics.GoogleAnalyticsService.<GetGA4ReportDataAsync>d__7`1.MoveNext() in C:\dev\noqv2\NoQV2.Services.Google.Impl\GoogleAnalytics\GoogleAnalyticsService.cs:line 62

=== Pre-bind state information ===
LOG: DisplayName = Google.Apis.Auth, Version=1.46.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab
 (Fully-specified)
LOG: Appbase = file:///C:/dev/noqv2/NoQV2.Web.Api/
LOG: Initial PrivatePath = C:\dev\noqv2\NoQV2.Web.Api\bin
Calling assembly : Grpc.Auth, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\dev\noqv2\NoQV2.Web.Api\web.config
LOG: Using host configuration file: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Google.Apis.Auth, Version=1.46.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/noqv2.web.api/32d6be55/eca39545/Google.Apis.Auth.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/noqv2.web.api/32d6be55/eca39545/Google.Apis.Auth/Google.Apis.Auth.DLL.
LOG: Attempting download of new URL file:///C:/dev/noqv2/NoQV2.Web.Api/bin/Google.Apis.Auth.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

```

**Comment by jskeet** [comment]
My guess is that the problem is due to dependencies in one of those other projects - but we can't really tell where the problem is without seeing them.

Do you have any assembly binding redirects being generated? I'd suggest looking through that file carefully.

**Comment by pjninnis** [comment]
Stripped the project right down to just the single package, but I still get the same version error.
    _<ItemGroup>
        <PackageReference Include="Google.Analytics.Data.V1Beta" Version="2.0.0-beta03" />
    </ItemGroup>_

Tried with and without a binding redirect for Google.Apis.Auth versions, and tried with and without Auto Binding Redirects on, but always the same error.

The error is occurring when calling the module via our existing ASP.NET WebApi controller, however, plugging the same module into a ASP.Net Core project and the error disappears. I'm not sure what else I can look at, but it seems that the Google.Api.Gax.Grpc.ClientBuilderBase component is choosing a particular version of Google.Apis.Auth package based on something I can't see.

**Comment by jskeet** [comment]
> Stripped the project right down to just the single package, but I still get the same version error.

Okay, that's progress...

> The error is occurring when calling the module via our existing ASP.NET WebApi controller

What exactly do you mean by this? What do you mean by "call the module"? It would be *really* helpful if you could provide (either as a zip file here, or just a branch in a GitHub repo) a complete example that I can copy, build, compile and run to see the error. Until I can reproduce the problem, I'm unlikely to be able to help.

The example doesn't need to have *any* of your "real" business logic (and indeed it shouldn't do, as I would assume that's proprietary). It just needs to be a minimal example that fails in the same way.

> it seems that the Google.Api.Gax.Grpc.ClientBuilderBase component is choosing a particular version of Google.Apis.Auth package based on something I can't see

No, the version of Google.Api.Gax.Grpc you're using depends on a *much* more recent version of Google.Apis.Auth. The class doesn't "choose" a particular version at all - the build process and runtime do, which is why it's really important to get a complete example to reproduce it.

**Comment by pjninnis** [comment]
Here's a very very simple cutdown of a ASP.Net WebApi controller program calling the project and it failing with the error.
You can run the GA4App directly in IISExpress and call http://localhost:5000/swagger/ui/index#!/GA4/GA4_GetDataAsync to try it and see the failure.

[GA4App.zip](https://github.com/googleapis/google-cloud-dotnet/files/11785840/GA4App.zip)

**Comment by pjninnis** [comment]
Thanks for the help jskeet.
I had incorrectly attempted adding that binding redirect to the Google Project (App.config) rather than the Web Project (Web.config). Adding as per your suggestion and it is now working in our ASP.NET program.
Still not sure why the Grpc.Auth pulled into the project with Google.Analytics.Data.V1Beta is looking for a specific version of the Google.Api.Auth - thought that it all dependancies would be compatible out of the box.

Anyway, we are currently transitioning for ASP.NET/NET Framework to ASP.NET Core/NET6 (with SDK project files), but it's a big, big job for a mature large product.

Thanks again.

**Comment by jskeet** [comment]
> Still not sure why the Grpc.Auth pulled into the project with Google.Analytics.Data.V1Beta is looking for a specific version of the Google.Api.Auth - thought that it all dependancies would be compatible out of the box.

The dependencies are *compatible* (in that it's fine for Grpc.Auth to depend on Google.Apis.Auth 1.46.0 when other libraries depend on 1.58.0) - it's just the version resolution algorithm for .NET Framework that seems to be causing the problem here. Hopefully when you've updated to ASP.NET Core you won't run into that any more - and until then, the binding redirect should keep things in check :)
