### ISSUE TITLE
Unable to get data from fire store after an hour.

### ISSUE THREAD

**Issue by OsamaNasir** [googleapis/google-cloud-dotnet#10702]
I use a SignInWithCustom Token method and successfully get data from firestore, but after an hour I unable to get the data because of token expiration time. I found there's   a Get IDToken() method to refresh a FirebaseDB object to access data, but unfortunately there's no such method in C# Library, So I decided to handle this case manully, Now I searching for token expiration property in FirebaseDB object, So I can initialize the object before It's expiration.
Is there any solution?

**Comment by jskeet** [comment]
Please clarify which library you're using, and where the `SignInWithCustomToken` method comes from. The Google.Cloud.Firestore library is expected to be used server-side, typically with a service account credential or similar. We have very little context for what you're trying to do here.

**Comment by OsamaNasir** [comment]
`private async Task<FirestoreDb> GetFirestoreDb(IConnectionStringProvider connectionStringProvider)
        {
            var builder = new FirestoreDbBuilder();
            builder.ProjectId = ConnectionStringProvider.ProjectId;
            
            var customToken = await ConnectionStringProvider.GetCustomTokenAsync();
            var oauthToken = await SignInWithCustomToken(customToken, ConnectionStringProvider.APIKey);
            ITokenAccess credential = GoogleCredential.FromAccessToken(oauthToken);
            builder.TokenAccessMethod = credential.GetAccessTokenForRequestAsync;
            
            return builder.Build();
        }`
        `private async Task<string> SignInWithCustomToken(string customToken, string apiKey)
        {
            var requestBuilder = new RequestBuilder
            {
                Method = HttpConsts.Post,
                BaseUri = new Uri(_BASE_URL),
                Path = "accounts:signInWithCustomToken"
            };
            requestBuilder.AddParameter(RequestParameterType.Query, "key", apiKey);
            var request = requestBuilder.CreateRequest();
            var jsonSerializer = Google.Apis.Json.NewtonsoftJsonSerializer.Instance;
            var payload = jsonSerializer.Serialize(new
            {
                token = customToken,
                returnSecureToken = true,
            });
            request.Content = new StringContent(payload, Encoding.UTF8, "application/json");
            using (var client = new HttpClient())
            {
                var response = await client.SendAsync(request);
                response.EnsureSuccessStatusCode();
                var json = await response.Content.ReadAsStringAsync();
                var parsed = jsonSerializer.Deserialize<dynamic>(json);
                return parsed.idToken;
            }
        }`
        
        
        Sign In with custom Token is my method. I create  a Firestore DB object from Firestore DB builder using custom Token as I retrieved from my backend.I successfully getted data from this method but after an our I get an exception In valid Credentials.means Firestore DB object is expire. How Can I handle this case?
        Note : I use Firestore in my client side application not server side.

**Comment by jskeet** [comment]
> I use Firestore in my client side application not server side.

In that case the Google.Cloud.Firestore library really isn't particularly design for your use case.

You can probably make it work by implementing `ITokenAccess` directly, so that it can fetch a new access token periodically (delegating to a new `GoogleCredential.FromAccessToken` after that). You might want to look at the [TokenRefreshManager](https://github.com/googleapis/google-api-dotnet-client/blob/main/Src/Support/Google.Apis.Auth/OAuth2/TokenRefreshManager.cs) code for how we handle that with our own credentials.

But basically if you provide the library with credentials that expire after an hour, you shouldn't be surprised that it stops working at that point. You either need to provide credentials that auto-refresh, or auto-refresh your `FirestoreDb` instead.

I don't think there's anything more the Firestore library can really do for you here - but it shouldn't be too hard to implement the refresh-behind-the-scenes, assuming your token refresh can happen without user interaction.

**Comment by jskeet** [comment]
> Now I searching for token expiration property in FirebaseDB object

FirebaseDb itself knows nothing about the token expiration. *All* it knows is how to retrieve a token to add to the request - that's all that `TokenAccessMethod` is about.

**Comment by OsamaNasir** [comment]
So, your suggestion is I didn't get the Token Expiration Property in my case.I handled manually to refresh FirestoreDB object and Assume that It expire after an hour. But in future development may be It expire in 30 minutes so what can I do in that case If I hard coded the one hour model

**Comment by jskeet** [comment]
I'm saying that *I don't know how you're getting the token*. I don't know whether that provides you an expiry time or not - but you should know that, as it's your code. You'll need to perform the token refresh in your code, either way.

**Comment by OsamaNasir** [comment]
I say that I Initialize the FirestoreDB object, This object expire after an hour. I debug this case and identify the issue. Now my question is as that FirestoreDB object is expire in one hour how can I know that object expiration time property from your c# library. It's not about my code, FirestoreDb is your Library part.

**Comment by jskeet** [comment]
It's not that the FirestoreDb object itself has expired. On each request that it makes, it will ask the access token method you've provided for an access token. If that access token has expired, the request will fail. If instead you return a *new* access token when the old one is close to expiry (as our own credential implementations do, for service accounts etc), the single FirestoreDb object will continue to work.

> It's not about my code, FirestoreDb is your Library part.

Yes, but FirestoreDb isn't responsible for obtaining an access token - your code is. FirestoreDb *just* applies the access token you provide to the request. It has no knowledge of what's in that access token, or when/if it expires. That's not its job.

**Comment by jskeet** [comment]
I'll close this issue now as I've explained what changes would be required in your code, and how this isn't something that FirestoreDb can do anything about. Please add another comment if you need further assistance.
