### ISSUE TITLE
Can Firestore SDK used on Web Assembly

### ISSUE THREAD

**Issue by AathifMahir** [googleapis/google-cloud-dotnet#10892]
Can we use current Firestore Library on Blazor Web Assembly App Model, I mostly guess it's not safe to use it on web Assembly since we are exposing service.json and API keys here. I'm Just double checking whether we can use it on Client Scenerios

**Comment by jskeet** [comment]
We certainly don't test using Blazor and WASM, no. It's possible that it would technically work, but as you say you'd want to think about how you manage authentication. Assuming you've already got a server involved, you could make that server return access tokens used by the Blazor code, with a suitable refresh mechanism. Again though, I really don't know whether this would actually work - I don't know what the Blazor/WASM support for HTTP/2.0 and gRPC is like. It *might* just work out of the box, but it's not a scenario we can actively support, I'm afraid.

**Comment by jskeet** [comment]
Closing as I believe I've answered the question - but please don't regard this as trying to shut down the conversation. I'm happy to reopen it if you'd like.

**Comment by AathifMahir** [comment]
> We certainly don't test using Blazor and WASM, no. It's possible that it would technically work, but as you say you'd want to think about how you manage authentication. Assuming you've already got a server involved, you could make that server return access tokens used by the Blazor code, with a suitable refresh mechanism. Again though, I really don't know whether this would actually work - I don't know what the Blazor/WASM support for HTTP/2.0 and gRPC is like. It *might* just work out of the box, but it's not a scenario we can actively support, I'm afraid.

I guess I didn't provided enough context on this issue.

What I was asking is, is it safe to expose the service account json that used to connect to firestore. As far as web Assembly we are exposing it to client that anyone access it. Just like JavaScript Firestore Client SDK which exposes the API key and etc.. to access the firestore. In this case we are exposing service account json. By the way I'm not sure what are the properties that used to init the connection to firestore on this SDK. Is it the same as Js client SDK

**Comment by jskeet** [comment]
> What I was asking is, is it safe to expose the service account json that used to connect to firestore.

No, that's not safe. A service account is *much* more powerful than a single API key. That's why I was suggesting only providing an access token from your server. That can be scoped for just Firestore, will naturally be expire etc. (That's safer than exposing an API key, too...)

> By the way I'm not sure what are the properties that used to init the connection to firestore on this SDK. Is it the same as Js client SDK

I doubt it, but I've never used the JavaScript client SDK.

Rather than conflating "getting started" and the Blazor aspect, I suggest you start with a simple console application, following either https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Firestore/latest or the guides at https://cloud.google.com/firestore/docs/create-database-server-client-library#c - if you have difficulties with that, please file a separate issue.

**Comment by AathifMahir** [comment]
> > What I was asking is, is it safe to expose the service account json that used to connect to firestore.
> 
> No, that's not safe. A service account is *much* more powerful than a single API key. That's why I was suggesting only providing an access token from your server. That can be scoped for just Firestore, will naturally be expire etc. (That's safer than exposing an API key, too...)
> 
> You could *potentially* create a service account which only has access to Firestore, but that still exposes things like your project ID and other information you probably don't want clients seeing.
> 
> > By the way I'm not sure what are the properties that used to init the connection to firestore on this SDK. Is it the same as Js client SDK
> 
> I doubt it, but I've never used the JavaScript client SDK.
> 
> Rather than conflating "getting started" and the Blazor aspect, I suggest you start with a simple console application, following either https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Firestore/latest or the guides at https://cloud.google.com/firestore/docs/create-database-server-client-library#c - if you have difficulties with that, please file a separate issue.

Thanks for confirmation on this. Actually I'm building a Firebase SDK based on the JavaScript Client SDK by using a JavaScript interop on Blazor. I guess for now that's the ideal solution. When it comes to using the solution that your recommendation can be viable for Blazor Only workloads but Having Blazor Hybrid workloads defeats the purpose. For now the only solution is going with JavaScript Interop on Blazor. Therefore we can have all the advantages of the client only SDK. Until we interrate that SDK with new builds and completely remove the JavaScript interop in future.
