### ISSUE TITLE
Error CS0117: 'AnnotateAssessmentRequest' does not contain a definition for 'Assessment' (CS0117) (RecaptchaEnterprise)

### ISSUE THREAD

**Issue by CarlosNetAcad** [googleapis/google-cloud-dotnet#10935]
I am integrating the Recaptcha enterprise and trying to create an assessment in a Xamarin Native iOS using the documentation in: 

https://cloud.google.com/recaptcha-enterprise/docs/create-assessment#c

```cs
public async Task<bool> VerifyRecaptchaAsync(string responseToken)
        {
            var client = await RecaptchaEnterpriseServiceClient.CreateAsync();

            var recaptchaRequest = new AnnotateAssessmentRequest
            {
                Assessment = new Assessment
                {
                    Event = new Event
                    {
                        SiteKey = RecaptchaSecretKey,
                        Token = responseToken
                    }
                }
            };

            try
            {
                var recaptchaResponse = await client.AnnotateAssessmentAsync(recaptchaRequest);
                return recaptchaResponse.Annotation == Annotation.Valid;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error verifying reCAPTCHA: {ex.Message}");
                return false;
            }
        }
```

I have installed the NuGet packages  mentioned in the example, but I'm having the error CS01103.

 - Error CS0117: 'AnnotateAssessmentRequest' does not contain a definition for 'Assessment' (CS0117) (RecaptchaEnterprise)

-  Error CS1061: 'AnnotateAssessmentResponse' does not contain a definition for 'Annotation' and no accessible extension method 'Annotation' accepting a first argument of type 'AnnotateAssessmentResponse' could be found (are you missing a using directive or an assembly reference?) (CS1061) (RecaptchaEnterprise)

- Error CS0103: The name 'Annotation' does not exist in the current context (CS0103) (RecaptchaEnterprise)

Do I need to add more packages or what is missing?

I am using the latest version of the package.

**Comment by jskeet** [comment]
Please specify exactly which NuGet package you've installed, including the version. Next, please be aware that we don't support Xamarin with these libraries - if they work for you, that's great, but we won't be able to support any gRPC issues etc.

I'd expect any samples to compile though - we'll need to dig into this.  On vacation until Tuesday, but another member of the team should be able to check out the sample.

**Comment by jskeet** [comment]
Hang on - you've mixed up two samples there. The sample you've linked to is about CreateAssessment, not AnnotateAssesment.

CreateAssessmentRequest does have an Assessment property, but AnnotateAssessmentRequest doesn't.

**Comment by amanda-tarafa** [comment]
As @jskeet mentioned, the `AnnotateAssesmentRequest` does not contain an Assesment property and [note](https://cloud.google.com/recaptcha-enterprise/docs/reference/rpc/google.cloud.recaptchaenterprise.v1#annotateassessmentrequest) that it doesn't do so at the API level, and libraries are just an idiomatic reflection of the APIs. The error you are seeing is expected.

I'll close this issue now as I believe there's nothing to do from our side, but do leave a comment if you believe otherwise.
