### ISSUE TITLE
await collection.GetSnapshotAsync() line is not returning to next line in .Net MAUI project

### ISSUE THREAD

**Issue by shubhgupta4u** [googleapis/google-cloud-dotnet#10934]
Hi,

While using Firebase.Cloud.Firestore library in .Net MAUI project, i have faced issue in below line, where my code execution stuck at this line indefinitely and did not return to next line:

    var snapshot = await collection.GetSnapshotAsync();

#### Environment details

  - OS: Android device Emulator
  - .NET version: 7.0
  - Package name and version:

Below workaround worked for me where I re-write the code and used ContinueWith() instead of await:

            Task task = collection.GetSnapshotAsync().ContinueWith((t) =>
                {
                    if (t.IsCompletedSuccessfully)
                    {
                        QuerySnapshot snapshot = t.Result;
                        result = snapshot.Documents.Select((x) => {
                                T obj = x.ConvertTo<T>();
                                obj.Id = x.Id;
                                return obj;
                            }).ToList();
                    }
                });

task.Wait();

Thanks!

**Comment by jskeet** [comment]
I will try to reproduce this when I'm back from vacation next Tuesday.

**Comment by amanda-tarafa** [comment]
Can you please clarify which library you are using and which version? You mentioned `Firebase.Cloud.Firestore library` but we don't maintain any such library in this repo. Which Nuget package exactly?

Also, can you confirm that the method that contains the line `var snapshot = await collection.GetSnapshotAsync();` is an `async` method?

With that info I might be able to look before Tuesday.

**Comment by shubhgupta4u** [comment]
Hi,

Kindly see the attached snapshot for the request library and version:

![image](https://github.com/googleapis/google-cloud-dotnet/assets/24973600/95bf3d41-1e1a-44a3-bfae-c4250449408b)
![image](https://github.com/googleapis/google-cloud-dotnet/assets/24973600/1187d794-a202-450e-a890-1b928c162e86)

Thanks

**Comment by amanda-tarafa** [comment]
Thanks, yes we do maintain `Google.Cloud.Firestore`.

If you could share more about the context where you are exeucting this line of code `var snapshot = await collection.GetSnapshotAsync();` that'd be helpful as well to attempt reproduction. The reason I'm asking is because in MAUI code that needs to access user interface elements [needs to be executed on the UI or main thread](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/main-thread), else it could lead to blocking.

Ideally you could share a small but complete MAUI application that reproduces the problem and we can take it from there. Basically there are many ways in which you could be executing `var snapshot = await collection.GetSnapshotAsync();` and it'd be hard for us to try and guess which you are using.

**Comment by jskeet** [comment]
Okay, I've just tried to reproduce this, and experienced everything behaving as expected. Steps I took:

- Create a new solution
- Create a new MAUI app within the solution - I used .NET 7.0
- Remove iOS from the build (as it's not relevant to this reported issue)
- Add `await Task.Delay(2000);` in `MainPageOnCountClicked()` just after `count++`, as well as making it async
- Run the app in the emulator - it takes a couple of seconds to respond to the button, as expected
- Test breakpoints: stepping over the `await Task.Delay(2000)` behaves as expected
- Add Google.Cloud.Firestore dependency (3.3.0)
- Hard-code a service account credential (**not** recommended for production code, of course) and project ID as constants in MainPage
- Create a document called "test" in a collection "issue10934", with a field "x" which has a string value
- Change code in `MainPage` to this:

```csharp
public partial class MainPage : ContentPage
{
    // Adjust as appropriate, of course
    private const string ServiceAccountJson = "...";
    private const string ProjectId = "...";

    private FirestoreDb db;

    public MainPage()
    {
        InitializeComponent();
        db = new FirestoreDbBuilder
        {
            ProjectId = "jonskeet-personal",
            Credential = GoogleCredential.FromJson(ServiceAccountJson)
        }.Build();
    }

    private async void OnCounterClicked(object sender, EventArgs e)
    {
        var docRef = db.Document("issue10934/testdoc");
        var doc = await docRef.GetSnapshotAsync();

        CounterBtn.Text = $"Value: {doc.GetValue<string>("x")}";
    }
}

I then tested the app in the Android Emulator, and it behaves as expected:

- Running without any breakpoints, it updates the UI
- With a breakpoint on `GetSnapshotAsync`, it breaks at the breakpoint, then "step over" cedes control of the IDE while it's fetching, then goes back into the debugger at the `CounterBtn.Txt` assignment statement

So everything looks okay to me - it seems most likely that there's something else going on to do with how you're calling `GetSnapshotAsync` with respect to the threading in MAUI - so we'd need more information to help further.

I would say, however, that we don't really support the Google Cloud Client Libraries on mobile platforms. It looks like it works from this brief test, but there could be all kinds of problems (not least around auth) which we won't be able to help with.

**Comment by jskeet** [comment]
Closing as everything looks fine as far as we can see, and we don't have any extra information to try to reproduce this. We can reopen the issue if more information is provided that suggests it's a problem in the library.
