### ISSUE TITLE
Readonly PhraseSet.Phrases in AdaptationPhraseSet of Google.Cloud.Speech.V2 API.

### ISSUE THREAD

**Issue by gusarovrb** [googleapis/google-cloud-dotnet#10993]
Hi there!

I am trying to migrate from `Google.Cloud.Speech.V1` to `V2` and can't find an info on how-to set speech adaptation phrases within `StreamingRecognizeRequest` in .NET SDK, version `1.0.0-beta06`.

The code I came up with so far:
```
StreamingRecognitionConfig config = new StreamingRecognitionConfig()
{
    StreamingFeatures = new StreamingRecognitionFeatures()
    {
        InterimResults = configuration.InterimResults,
    },
    Config = new RecognitionConfig()
    {
        ExplicitDecodingConfig = new ExplicitDecodingConfig()
        {
            AudioChannelCount = 1,
            Encoding = ExplicitDecodingConfig.Types.AudioEncoding.Linear16,
            SampleRateHertz = configuration.SampleRate
        }
    }
}; 
foreach (var srcContext in configuration.SpeechContexts)
{
    var phrases = new List<PhraseSet.Types.Phrase>();
    foreach (var srcPhrase in srcContext.Phrases)
    {
        var phrase = new PhraseSet.Types.Phrase()
        {
            Value = srcPhrase,
            Boost = srcContext.Boost
        };
        phrases.Add(phrase);
    }
    var phraseSet = new SpeechAdaptation.Types.AdaptationPhraseSet()
    {
        InlinePhraseSet = new PhraseSet()
        {
            Phrases = phrases
        }
    };
    config.Config.Adaptation.PhraseSets.Add(phraseSet);
}
```

The issue is that `PhraseSet.Phrases` is readonly, there is no setter defined. So is there another option to set speech adaptation phrases dynamically within each `StreamingRecognizeRequest`?

I saw in Python SDK is possible to set phrases in phraseSet ([example](https://cloud.google.com/speech-to-text/v2/docs/adaptation-model?hl=en#improve_transcription_using_a_phraseset)), so though that something similar should be doable in C# SDK.

**Comment by amanda-tarafa** [comment]
Protobuf repeated fields and maps are generated as readonly but they can be populated using collection initializers or by adding elements to the collection. Please refer to https://cloud.google.com/dotnet/docs/reference/help/protobuf#repeated-fields-and-maps for more information.

**Comment by jskeet** [comment]
There's no setter, but the property is a repeated field, so you can call `Add` on it. `RepeatedField<T>` has overloads for adding a single or multiple items, so you can just use a collection initializer:

```csharp
var phraseSet = new SpeechAdaptation.Types.AdaptationPhraseSet
{
      InlinePhraseSet = new PhraseSet
      {
          Phrases = { phrases }
      }
};
```

Or do the whole thing in a single LINQ expression:

```
var phraseSet = new SpeechAdaptation.Types.AdaptationPhraseSet
{
      InlinePhraseSet = new PhraseSet
      {
          Phrases = { srcContext.Phrases.Select(p => new PhraseSet.Types.Phrase { Value = p, Boost = p.Boost }) }
      }
};
```

**Comment by gusarovrb** [comment]
@jskeet Thank you for such prompt response! Collection initializer works.
