### ISSUE TITLE
Storage: Add support for Autoclass v2.1

### ISSUE THREAD

**Issue by cojenco** [googleapis/google-cloud-dotnet#11037]
Feature request to add support for new AutoclassConfig metadata fields. Full details are available in this [internal doc](http://goto.google.com/ac2-1-sdk-request).

Please wait for approval from myself before merging/releasing so we can [coordinate](http://goto.google.com/gcs-sdk-ac2-1) around release dates.

**Comment by amanda-tarafa** [comment]
This is one of the Storage features that only requires sample work for the .NET library as we expose all the underlying Discovery library types. Testing is done through samples.

@cojenco I'll be closing this one here, can you please recreate it in https://github.com/GoogleCloudPlatform/dotnet-docs-samples (issues cannot be moved to repos in different organizations) .

Thanks.

**Comment by cojenco** [comment]
Filed https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/2341, thanks
