### ISSUE TITLE
Google.Cloud.Logging.Console : getting / setting the traceId manually ?

### ISSUE THREAD

**Issue by christopheblin** [googleapis/google-cloud-dotnet#11042]
After #9948, the result is that using a simple stdout logger allows to correlate all logs of the same HTTP request because they have the same "trace"

Which allows a nice view like this where you can fold/unfold logs of the same trace

![image](https://github.com/googleapis/google-cloud-dotnet/assets/11044877/3fbecd37-bf20-4644-935c-b4225afeb8e9)

My question : is there a way to manually get / set the id of the trace ?

**Comment by jskeet** [comment]
I'll assign this to Amanda in case I've missed something, but I believe the trace ID is just `Activity.Current.TraceId.ToHexString()`.
(I don't know enough about the Activity API to know whether you can set the trace ID yourself.)

**Comment by amanda-tarafa** [comment]
Getting the Trace ID is as @jskeet said, you just use `Activity.Current.TraceId`.

Setting the Trace ID and it having an effect in the exported data, depends.

This is briefly described in Google.Cloud.Loggin.Console [documentation](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Logging.Console/latest#log-trace-correlation). In particular:

For initializing or modifying the Activity ID:

> When writing a server application, the current .NET [Activity](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity) needs to be initialized with the trace context included in the current request. ASP.NET Core does this for you automatically based on HTTP headers. Alternatively, if your application is starting traces itself (for example, if it's responding to Pub/Sub messages instead of HTTP requests), it needs to initialize the current Activity explicitly, as described in the [Distributed Tracing guide](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing).

But, you'd need to make sure that those "custom" traces are exported, i.e. you'd need to write explicit code to export them.

> Your application needs to be exporting traces to Google Cloud Trace. This could be performed automatically by the runtime, or via explicit code or instrumentation. Google Cloud runtimes export some traces automatically. (For example, Cloud Run will [export traces for received requests](https://cloud.google.com/run/docs/trace) by default, but you would need to export traces for any additional information.) Please refer to the documentation for the runtime you're using for more details.

**Comment by jskeet** [comment]
@christopheblin: Does that answer everything you need?

**Comment by christopheblin** [comment]
Hi ,

Thanks to the pointers given by Amanda, I found out that to set the traceId of the Activity.CUrrent, you need to do
```
var traceId = ...
var spanId = ...
Activity.Current.SetParentId(ActivityTraceId.CreateFromString(traceId), ActivitySpanId.CreateFromString(spanId));
```

To find traceId and spanId, I read https://cloud.google.com/run/docs/trace

So I am currently trying to make it work with "traceparent".
It works locally butit does not seem to work with cloud run which seems to override this header with its own :(

I think I can close this issue because my question is answered

**Comment by christopheblin** [comment]
For the record, the problem is not that cloud run override the header on its own BUT you must start a new activity in order for it to work in Cloud run (no idea why, I do not see how it makes a difference...)

        var activity = new Activity(httpContext.Request.Method + " " + httpContext.Request.Path)
            .SetParentId(traceId, spanId)
            .Start();
        try
        {
            await _next(httpContext);
        }
        finally
        {
            activity.Stop();
        }

instead of the more simpler version that only works locally

        Activity.Current.SetParentId(traceId, spanId);
        await _next(httpContext);

**Comment by christopheblin** [comment]
OK I now understand why we need to start a new activity in Cloud run : Activity.Current.Parent is already populated (I do not know by who or how) and so it is ignored

To see why it is ignored, look at https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L574

Basically, 

            if (Parent != null)
            {
                NotifyError(new InvalidOperationException(SR.SetParentIdOnActivityWithParent));
            }

The `NotifyError ` simply throws and immediately catches the exception, which mean that we never have a chance to see it ...

In .NET 7+, the restriction is even more hard because the SetParentId can only be called before .Start()  

            if (_id != null || _spanId != null)
            {
                // Cannot set the parent on already started Activity.
                NotifyError(new InvalidOperationException(SR.ActivitySetParentAlreadyStarted));
            } 

so in the end, I'm glad to have the bug before .NET 8 :)
