### ISSUE TITLE
Private service connect with PublisherClientBuilder

### ISSUE THREAD

**Issue by christopheblin** [googleapis/google-cloud-dotnet#11106]
I configured a private service connect for PubSub on my own endpoint pubsub.mycompany.io

How can I use this PSC with the PublisherClientBuilder ?

I try to read https://cloud.google.com/dotnet/docs/reference/Google.Cloud.PubSub.V1/latest but I cannot find anything about PSC

**Comment by jskeet** [comment]
@amanda-tarafa Could you have a look at this please? If you don't have time, I'll try to look tomorrow.

**Comment by amanda-tarafa** [comment]
I'm looking at it. I'll come back here when I know more.

**Comment by amanda-tarafa** [comment]
Client builders all inherit from [Google.Api.Gax.Grpc.ClientBuilderBase](https://github.com/googleapis/gax-dotnet/blob/main/Google.Api.Gax.Grpc/ClientBuilderBase.cs) which has an Endpoint property. You can set that property to your PSC endpoint and things should work from there. So your code would look something like:

```csharp
var builder = new PublisherClientBuilder
{
    Endpoint = "pubsub.mycompany.io"
};
var publisherClient = builder.Build(); // await builder.BuildAsync();
```

And this is the same for all Google.Cloud client libraries. The documentation for cross-library features like this is not included on each library documentation, instead it's on the [Client library help](https://cloud.google.com/dotnet/docs/reference/help/getting-started) section of the documentation at the top of the Table of Contents. In particular we have the [Endpoint](https://cloud.google.com/dotnet/docs/reference/help/client-configuration#endpoint) section. I'll update this section to mention PSC and link to the [PSC documentation](https://cloud.google.com/vpc/docs/configure-private-service-connect-apis#configure-p-dns). I'll also update the PSC documentation to include .NET on the list of supported languages (alongside with Pythong and Go).

Let me know.

**Comment by amanda-tarafa** [comment]
OK, let us know if it all works, and we can close this issue.

(I've also updated the [PSC docs](https://cloud.google.com/vpc/docs/configure-private-service-connect-apis#configure-p-dns) to include .NET libraries there, but that change may take longer to go through).

**Comment by christopheblin** [comment]
Here is the console program I use

```
using Google.Api.Gax;
using Google.Apis.Auth.OAuth2;
using Google.Cloud.PubSub.V1;
using Google.Protobuf;
using System.Diagnostics;
using System.Net;
using System.Text.Json;

var endpoint = "redacted:443";
var projectId = "redacted";
var topicId = "redacted";
var creds = GoogleCredential.FromFile("./sa-key.json");
var credsSa = (ServiceAccountCredential)creds.UnderlyingCredential;
var msg = JsonSerializer.Serialize(new { dummy = "test" });
var messageType = "FakeMessage";
var source = "ConsoleApp";

Console.WriteLine("Trying to publish message {0} on {1}/{2} with service account {3} for {4}", 
    msg, projectId, topicId, credsSa.Id, endpoint);

var _publisherClient = new PublisherClientBuilder()
{
    Endpoint = endpoint,
    Credential = creds,
    TopicName = TopicName.FromProjectTopic(projectId, topicId),
    Settings = new PublisherClient.Settings
    {
        EnableMessageOrdering = true
    },
    EmulatorDetection = EmulatorDetection.None,
}.Build();

var m = new PubsubMessage
{
    Data = ByteString.CopyFromUtf8(msg),
    Attributes =
            {
                { "MessageType", messageType },
                { "Source", source }
            }
};
var perfTimer = Stopwatch.StartNew();
var msgId = await _publisherClient.PublishAsync(m); //failing here
Console.WriteLine("Published message {0} in {1}ms with id={2}", msg, perfTimer.ElapsedMilliseconds, msgId);
```

**Comment by amanda-tarafa** [comment]
These are gRPC calls over HTTP/2 so you cannot use `curl` to reproduce them. Postman [does seem to support gRPC](https://learning.postman.com/docs/sending-requests/grpc/grpc-request-interface/). And this error does seem like gRPC is not supported in some part of the pipeline.

Can you try overriding the endpoint but with Pub/Sub's default endpoint (`"pubsub.googleapis.com:443"`) and see what happens? And not overriding the endpoint at all?

Can you confirm you are using .NET 6 or above for this test? It seems so from the top level statements in Program.cs but just want to make sure.

See the [How can I trace gRPC issues? ](https://cloud.google.com/dotnet/docs/reference/help/troubleshooting) docs for information on how to enable logging. Note that how to do so will depend on the transport you are using (Grpc.Net.Client or Grpc.Core). If you are indeed targetting .NET 6 or above, then you are [most likely using Grpc.Net.Client](https://cloud.google.com/dotnet/docs/reference/help/transports#default-selection), and so you should follow [Transport logging with Grpc.Net.Client](https://cloud.google.com/dotnet/docs/reference/help/troubleshooting#transport-logging-with-grpcnetclient).

Let me know what you get from this.

**Comment by christopheblin** [comment]
Hi @amanda-tarafa and @jskeet 

I fixed the error  Detail="No grpc-status found on response.") by forcing the backend to use HTTP/2 protocol

However, still using the same code, I now see the following error
```
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Unauthenticated", Detail="Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.")
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
```

As you can see, I did set the Credential on the PublisherClientBuilder thanks to a service account key so I do not understand what I need to do instead

If I follow the link, it directs me to using auth as a user (not as a service account), which does not seem relevant here ...

I also tried `Credential = credsSa` to really force the usage of the service account, same result ...

Do you have any pointers ?

**Comment by christopheblin** [comment]
Ah I did find the answer here : https://cloud.google.com/dotnet/docs/reference/help/client-configuration#credentialspath-jsoncredentials-or-googlecredential

I must use `GoogleCredential `instead of `Credential `if I want to use a service account JSON key
