### ISSUE TITLE
real time 

### ISSUE THREAD

**Issue by MTEV** [googleapis/google-cloud-dotnet#11117]
hi 
how i can  read data from  real time 
by c# 
i can    retrieve data  from firestore database 
but  real time i can't  
and i can't find  any  answer 

thanks for  any help

**Comment by jskeet** [comment]
Please add *much* more information to this issue. We don't know what you've tried, which package you're using, what goes wrong with what you've tried, what version of .NET you're using, where you're running it etc. (When you started to file an issue, you should have been presented with a template asking you all of this information. Please don't just ignore such templates.)

**Comment by jskeet** [comment]
Closing due to lack of information.
