### ISSUE TITLE
"Failed to get document because the client is offline" error in Xamarin.Forms project

### ISSUE THREAD

**Issue by CostasAthan** [googleapis/google-cloud-dotnet#11120]
Here is my code of the App.xaml.cs file of a Xamarin.Forms project:

```
public partial class App : Application
    {
            public App()
            {
                CrossFirebaseCrashlytics.Current.HandleUncaughtException();
    
                InitializeComponent();
    
                MainPage = new Page();
    
                MainThread.BeginInvokeOnMainThread(async () => await Loader());
            }
    
            
            private async Task Loader()
            {
                var firebaseDocExists = false;
    
                var firebaseDoc = await CrossCloudFirestore.Current
                                                           .Instance
                                                           .Collection("myCollection")
                                                           .Document("docId")
                                                           .GetAsync();
    
                firebaseDocExists = firebaseDoc.Exists;
    
                if (firebaseDocExists == false) MainPage = new MyPage();
                else MainPage = new NavigationPage(new MainPage());
            }
    }
```

At the launch of the Android app **on physical devices (API levels 29 & 31), not on the emulator, I get the following error**:

***crc64[alphanumeric_string].CrashlyticsException: Plugin.CloudFirestore.CloudFirestoreException: Failed to get document because the client is offline.
at MyApp.App.Loader ()(<unkown>:0)
at MyApp.App.<.ctor>b__0_0 ()(<unkown>:0)***

Before the first Firestore reference in my initial code, I added this new line of code:

`await CrossCloudFirestore.Current.Instance.EnableNetworkAsync();`

No difference at all.

**I also should add that running the app on the emulator does not produce the error, regardless which API level I use.**

#### Environment details

  - OS: Android API levels 29 & 31
  - .NET version: .NET Standard 2.0
  - Package name and version: Google.Cloud.Firestore 3.3.0

**Comment by jskeet** [comment]
I'm afraid we don't support Xamarin. (See our [supported platforms page](https://cloud.google.com/dotnet/docs/reference/help/platforms).) If it happens to work, that's great - but we're not in a position to investigate any problems with it. `CrossCloudFirestore` isn't part of any package published from this repository, either. My *guess* is that the gRPC stack isn't working, but again we're not really in a position to look into that. (It's not even clear to me whether it's using the Grpc.Net.Client or Grpc.Core stack.)

It looks to me like you should probably ask on https://github.com/f-miyu/Plugin.CloudFirestore - I'll close this issue now, as there's nothing we can do in this repository to help, I'm afraid.
