### ISSUE TITLE
Support DatabaseId on FirestoreDb

### ISSUE THREAD

**Issue by hach-que** [googleapis/google-cloud-dotnet#11163]
Google Cloud Firestore now supports multiple database, but FirestoreDb still hides the parameter in an internal method: https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/FirestoreDb.cs#L134

The `databaseId` parameter should be exposed to developers.

**Comment by jskeet** [comment]
The feature is still in preview. We will make it public when the feature is GA.

**Comment by TulyOpt** [comment]
Hello @jskeet ,

is it the same for DatastoreDb[Builder]. I have : 
![image](https://github.com/googleapis/google-cloud-dotnet/assets/7174515/04b90a74-8b56-4a85-bbb7-93c2ae2a84aa)

i am trying to write to the orders db ( in datastore mode) but it still writes to (default). Can I change the db I am writing to ? or should I wait for the GA. If it's the case, the multi db is unusable for the moment.

**Comment by jskeet** [comment]
No, Datastore support for multiple databases is GA (I believe) - but we haven't implemented it yet in the client library. It's literally being worked on at the moment.

**Comment by hach-que** [comment]
If anyone needs to instantiate a FirestoreDb for the non-default database, you can do it with this bit of reflection code:

```csharp
var firestoreClient = await new FirestoreClientBuilder().BuildAsync();
var create = typeof(FirestoreDb).GetMethod(
    "Create",
    BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public,
    new Type[]
    {
        typeof(string),
        typeof(string),
        typeof(FirestoreClient),
        typeof(Action<string>),
        typeof(ConverterRegistry)
    });
var db = (FirestoreDb)create!.Invoke(
    null,
    new object[]
    {
        Platform.Instance().ProjectId,
        "REPLACE_WITH_YOUR_DATABASE_ID_HERE",
        firestoreClient,
        null!,
        null!,
    })!;
```

**Comment by jskeet** [comment]
Correction to my previous statement: I'm afraid Datastore multi-db support is *also* in preview at the moment. We'll look at options for release beta versions of the libraries to expose the features, but we definitely won't release GA libraries with this in until the feature goes GA.

**Comment by jskeet** [comment]
The 3.5.0-beta01 release for Firestore is now in progress. I hope we'll be able to release 3.5.0 early in 2024.
