### ISSUE TITLE
Slow file upload and download problem

### ISSUE THREAD

**Issue by suleymanbyzt** [googleapis/google-cloud-dotnet#11229]
Hello everyone,
I have completed integrations using your library but I am having problems with download and upload. 

On my machine on Google Kubernetes, the upload and download times using your library are taking too long.

For example, downloading a 1GB ZIP file takes 195 seconds and uploading takes 166 seconds.

```
Oct 27, 2023 @ 19:02:17.804 Upload process took 166182ms

Oct 27, 2023 @ 18:59:31.620 Download and zip process took 195215ms
```

When I do the same with gsutil on the same machine, the downloads take under 10 seconds. I can't find what is causing this slowness. 

```csharp

    public async Task UploadFile(string uploadPath, string filePath)
    {
        using var fileStream = File.OpenRead(filePath);
        await _storageClient.UploadObjectAsync(_bucketName, uploadPath, contentType: null, fileStream);
    }


public async Task<Object> Download(string path, Stream stream)
    {
        Object media = null;

        try
        {
            media = await _storageClient.GetObjectAsync(_bucketName, path);

            if (media != null)
            {
                await _storageClient.DownloadObjectAsync(media, stream);
                stream.Position = 0;
            }
        }
        catch (GoogleApiException e) when(e.HttpStatusCode == HttpStatusCode.NotFound)
        {
            // ignored
        }

        return media;
    }
```

My code example is like this. What is the reason why the download is taking so long? I am waiting for your support on the subject thanks!

**Comment by jskeet** [comment]
That's really unusual. I'll test it tomorrow myself, but I'm sure I've been seeing uploads of about 10-20 seconds for a gigabyte. I don't expect it to be quite as fast as gsutil due to some of the fine-tuning there, but I certainly wouldn't expect *that* level of slowness.

In the download case, what is the stream in question? If you're easily able to test uploading and downloading from/to a MemoryStream, that would be interesting - if you copy the file content to a MemoryStream and upload that, for example, timing each part, are you able to see which part is the slow bit? (I'd certainly *expect* it to be the network rather than file access, but I've learned not to assume...)

**Comment by suleymanbyzt** [comment]
Thank you for your help. I use filestream instead of memorystream. When I use memorystream I get an out of memory error for large files, so I have to use filestream. If you have a different suggestion other than memorystream, I can try it too. If you have a chance to test using filestream that would be great. Thanks again for your support

**Comment by jskeet** [comment]
I'll definitely try with FileStream, yes. If you could try a smaller file with MemoryStream (say 100MB) that would be handy.

Could you let me know what your node sizes are, by the way? I know that the machine type affects the IO available.

**Comment by suleymanbyzt** [comment]
Hello again,
I did my tests like you said, but the result is the same.  I used 2 different methods. Method 1 uses filestream while method 2 uses memoryStream.

**Note: File type ZIP and size 40 mb**

```csharp
        stopwatch.Restart();
        await _cloudStorage.UploadFile(uploadPath, zipFilePath);
        _logger.LogInformation($"Upload file with UploadFile method took {stopwatch.ElapsedMilliseconds}ms");

        stopwatch.Restart();
        await _cloudStorage.UploadFileWithMemoryStream(uploadPath, zipFilePath);
        _logger.LogInformation($"Upload file with UploadFileWithMemoryStream method took {stopwatch.ElapsedMilliseconds}ms");
```

```csharp
    private readonly StorageClient _storageClient;
    private readonly string _bucketName;

    public GoogleCloudStorage()
    {
        GoogleCredential credential = GoogleCredential.FromFile(CloudItems.Credential);
        _storageClient = StorageClient.Create(credential);
        _bucketName = CloudItems.Bucket;
    }

    public async Task UploadFile(string uploadPath, string filePath)
    {
        await using (FileStream fileStream = File.OpenRead(filePath))
        {
            await _storageClient.UploadObjectAsync(_bucketName, uploadPath, null, fileStream);
        }
    }
    
    public async Task UploadFileWithMemoryStream(string uploadPath, string filePath)
    {
        byte[] fileBytes = await File.ReadAllBytesAsync(filePath);
        MemoryStream memoryStream = new MemoryStream(fileBytes);
        await _storageClient.UploadObjectAsync(_bucketName, uploadPath, null, memoryStream);
        memoryStream.DisposeAsync();
    }
```

and my outputs are as follows
![image](https://github.com/googleapis/google-cloud-dotnet/assets/58400764/46bcb2c7-b659-457f-9906-4ca1639a363e)

```
        resources:
          requests:
            memory: "100Mi"
            cpu: "10m"
          limits:
            memory: "512Mi"
            cpu: "400m"
```
Since it is in dev environment, its resources are a bit low, but as I said, when I connect to this machine with port forward and use gsutil, I have no problem for upload or download. maybe I'm missing something. If you have another suggestion, I can try again.

**Comment by jskeet** [comment]
Another thing to check: if you connect to the machine and run a .NET console app (rather than doing it in a service), what performance do you see? I wonder whether the "overall machine" has a lot more I/O bandwidth than the individual service, precisely because you've set a very low set of resources for the service. (I assume that the YAML snippet you provided was for the service - it's not entirely clear.)

Another thing to try would be increasing the requests and/or limits, just for testing purposes.

**Comment by amanda-tarafa** [comment]
Just as an update, I've been trying to reproduce this but haven't quite gotten there yet.

I must say I'm consitently getting a 1GB file to download in ~20 seconds. I'm looking at uploads next.

**Comment by amanda-tarafa** [comment]
@suleymanbyzt I can't reproduce this with the cluster/nodes/services configurations I'm using. Can you please share yours so I can try with that?

Alternatively, run the test that @jskeet suggested on https://github.com/googleapis/google-cloud-dotnet/issues/11229#issuecomment-1784685882, that is, to connect to the machine and run your code in a .NET console app instead of a service, to check that is not the service's configuration that's making a difference here.

**Comment by suleymanbyzt** [comment]
First of all, thank you very much for your support, you are great @amanda-tarafa @jskeet  <3 You are helping in the best way you can and that makes me happy.

I will be available on the weekend and I can share the information you want then, but there are some things I want to share with you.

We wanted to test using your Google Cloud REST API as an alternative. We got very good results from our tests. 

For example, we get the following speed values for downloading a 100Mb ZIP file.

**Google.Cloud.Storage.V1 4.7.0** =>48 Mbps
**Google Cloud REST API** => 228Mbps

Even though we increased resources by about 4x, we continued to see the same speeds. I will share our cluster/nodes/services information with you over the weekend. Maybe this will help you understand the problem better.

**Comment by jskeet** [comment]
Google.Cloud.Storage.V1 uses the REST API under the hood.

Please tell us *exactly* what you mean by "using your Google Cloud REST API" - can you show the code you were using?
(Note that Google.Cloud.Storage.V1 uses Google.Cloud.Apis.Storage.v1, which uses the common ResumableUpload support... but I wouldn't expect resumable uploads to be significantly slower than a direct one-shot upload.)

**Comment by suleymanbyzt** [comment]
The code example is as follow.

```csharp
            GoogleCredential credential;
            await using (FileStream fileStream = new FileStream(CloudItems.Credential, FileMode.Open, FileAccess.Read))
            {
                credential = GoogleCredential.FromStream(fileStream)
                    .CreateScoped(StorageService.Scope.DevstorageReadWrite);
            }

            ITokenAccess tokenAccess = credential;
            string authUri = "https://accounts.google.com/o/oauth2/auth";
            string token = await tokenAccess.GetAccessTokenForRequestAsync(authUri, CancellationToken.None);

            string googleStorageUrl = $"https://storage.googleapis.com/my-bucket/{path}";

            using (HttpClient httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {token}");

                HttpResponseMessage response = await httpClient.GetAsync(googleStorageUrl);

                if (response.IsSuccessStatusCode)
                {
                    string downloadPath= Path.Combine(Path.GetTempPath(), "Download");
                    if (!Directory.Exists(downloadPath))
                    {
                        Directory.CreateDirectory(downloadPath);
                    }

                    string zipFilePath = Path.Combine(downloadPath, $"{Guid.NewGuid().ToString("N")}.zip");
                    
                    await using (FileStream stream = new FileStream(zipFilePath, FileMode.Create))
                    {
                        await response.Content.CopyToAsync(stream);
                    }
                    
                    File.Delete(zipFilePath);
                }
            }
```

I get very good performance when I send the request this way.

**Comment by suleymanbyzt** [comment]
I think I understand the problem better now. The size of the files I download is very small. For example, I have 500 files, 300 of them are 5 kb and it takes a long time to download them. It is faster to download large files

Thank you for your help.
