### ISSUE TITLE
Ability to enforce handling of all shipments

### ISSUE THREAD

**Issue by UnBayleefable** [googleapis/google-cloud-dotnet#11253]
would like to enable validation constraints to return a validation error if the optimizer is unable to handle all shipments.  

library in use: Cloud Optimization v1 API

my current use case is as follows:

- we are transitioning our current courier route system to go from manual static routes (always the same) to pooled route distrobution and are looking to integrate Cloud Optimization that handles generating the routes and assigning vehicles to them.

- im currently attempting to input our previous static route in order to get a comparable response to the new routes that are generated in order to analyse the performance increase/cost reduction but given the size of the shipment collection every test request i send ends up eating a chunk of my monthly budget.

i am currently integrating the Cloud Optimization v1 API library and and have setup a system for submitting OptimizeTourRequests and have successfully received responses but i would like to be able to enforce that it handles all visits that are supplied or return a validation error if its unable to as im in the process of tweaking the constraint parameters to refine the quality of the routes that are generated but have spent the majority of my monthly budget generating routes that would be deemed as unsatisfactory.

**Comment by amanda-tarafa** [comment]
There are over 100 client libraries on this repo. It's impossible to know which you are trying to use and how,

You'll need to provide way more information than what you have just provided for us to be able to help you.

**Comment by UnBayleefable** [comment]
woops that was my bad i had thought i was linked to the repo directly related to the library i was using.

library in use: Cloud Optimization v1 API 

my current use case is as follows:
- we are transitioning our current courier route system to go from manual static routes (always the same) to pooled route distrobution and are looking to integrate Cloud Optimization that handles generating the routes and assigning vehicles to them.
- im currently attempting to input our previous static route in order to get a comparable response to the new routes that are generated in order to analyse the performance increase/cost reduction but given the size of the shipment collection every test request i send ends up eating a chunk of my monthly budget.

i am currently integrating the Cloud Optimization v1 API library and and have setup a system for submitting OptimizeTourRequests and have successfully received responses but i would like to be able to enforce that it handles all visits that are supplied or return a validation error if its unable to as im in the process of tweaking the constraint parameters to refine the quality of the routes that are generated but have spent the majority of my monthly budget generating routes that would be deemed as unsatisfactory.

**Comment by jskeet** [comment]
Thanks for raising this issue. Unfortunately this sounds like it's really a question about the Optimization API itself rather than about the .NET client library. The maintainers of this repository aren't experts in all the different Google APIs that are available - only how the .NET client libraries can be used to make requests to those APIs. (We can help customers who know what their API call should look like but are having trouble with how to make that request using C#, but not with figuring out the request to start with.) I recommend you follow one of the support routes on the [Optimization API support page](https://cloud.google.com/optimization/docs/getting-support) which will hopefully resolve the issue for you.
