### ISSUE TITLE
Unauthenticated Error at .Net Maui

### ISSUE THREAD

**Issue by shinnthant-lab** [googleapis/google-cloud-dotnet#11261]
#### Environment details

  - OS: Android 13.0
  - .NET version: 8.0.100-rc.2.23502.2
  - Package name and version: Google.Maps.Routing.V2

#### Steps to reproduce

  1. Create a .net maui project and install Google.Maps.Routing.V2 prerelease via nuget and follow the guide at https://googleapis.dev/dotnet/Google.Maps.Routing.V2/latest/index.html
  2. Add the following snippet to OnAppearing of main page and try run.
`
var localPath = Path.Combine(FileSystem.CacheDirectory, "credentials.json");

using var json = await FileSystem.OpenAppPackageFileAsync("credentials.json");
using var dest = File.Create(localPath);
await json.CopyToAsync(dest);
Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", localPath);

dest.Close();

var file = File.ReadAllText(localPath);hannelCredentials();

var client = new RoutesClientBuilder
{
    //ChannelCredentials = channelCredentials,
    //JsonCredentials = file,
    GrpcAdapter = RestGrpcAdapter.Default
}.Build();

CallSettings callSettings = CallSettings.FromHeader("X-Goog-FieldMask", "*");
ComputeRoutesRequest request = new ComputeRoutesRequest
{
    Origin = new Waypoint
    {
        Location = new Google.Maps.Routing.V2.Location { LatLng = new LatLng { Latitude = 37.419734, Longitude = -122.0827784 } }
    },
    Destination = new Waypoint
    {
        Location = new Google.Maps.Routing.V2.Location { LatLng = new LatLng { Latitude = 37.417670, Longitude = -122.079595 } }
    },
    TravelMode = RouteTravelMode.Drive,
    RoutingPreference = RoutingPreference.TrafficAware
};
ComputeRoutesResponse response = client.ComputeRoutes(request, callSettings);
`
  4. Will crash with the following error
  
![image](https://github.com/googleapis/google-cloud-dotnet/assets/54578974/0e67608d-a7ba-4fed-b617-ba4a1c7d90e2)

Thanks!

**Comment by amanda-tarafa** [comment]
In general we don't support mobile platforms. You can read more about that in the [Mobile Platform Support](https://cloud.google.com/dotnet/docs/reference/help/platforms#mobile-platform-support) of the Google Cloud .NET Client libraries documentation. 

That said, it seems like you are trying to use a service account credential from a client side application? What's the content of your `credentials.json` file? Please make sure to obfuscate any value that may seem sensitive, but do share the structure of it.

**Comment by jskeet** [comment]
One thing to check - have you definitely enabled the Maps Routing API for the project? I believe I received an error like this while originally trying it when the API was in private preview, so this *may* be the error you get if the API isn't enabled.

I'd strongly recommend trying a simple console app with the same credential, so that you can get everything working on a simple and supported platform first. (And as Amanda says, we don't support mobile platforms at the moment.)

**Comment by shinnthant-lab** [comment]
> In general we don't support mobile platforms. You can read more about that in the [Mobile Platform Support](https://cloud.google.com/dotnet/docs/reference/help/platforms#mobile-platform-support) of the Google Cloud .NET Client libraries documentation.
> 
> That said, it seems like you are trying to use a service account credential from a client side application? What's the content of your `credentials.json` file? Please make sure to obfuscate any value that may seem sensitive, but do share the structure of it.

Dear Amanda,

Here is the credentials edited for your reference.
[credentials.json](https://github.com/googleapis/google-cloud-dotnet/files/13226849/credentials.json)

**Comment by shinnthant-lab** [comment]
also @jskeet , I tested with console app and still facing the same issue.
Please see the screenshot for your reference.

![image](https://github.com/googleapis/google-cloud-dotnet/assets/54578974/70b491d7-c305-4f48-95a5-afea7611ec25)

**Comment by jskeet** [comment]
I believe this is the problem:

```csharp
GrpcAdapter = RestGrpcAdapter.Default
```

I've just run a smoke test on this myself, and it works for gRPC but not for REST. It's *possible* that you need to use an API key for REST for this API - I'm not sure.

Please run your console app test without specifying a gRPC adapter, to see if that addresses the problem, and I can then ask internally about expectations.

**Comment by amanda-tarafa** [comment]
And a note in parallel:

> Here is the credentials edited for your reference.
[credentials.json](https://github.com/googleapis/google-cloud-dotnet/files/13226849/credentials.json)

That does indeed look like a service account credential. I'm not certain that using a service account credential from Maui will work, we don't test in mobile infrastructures and that's precisely why we don't claim to support them. Regardless, it's uncommon to share a service account credential with your Android app users. That means that all users will be authenticating as the identity represented by the service account credential, i.e. the service account. It also means that a private key for your service account is stored in possibly many devices, from which it may be obtained and used by a bad actor.

If this is your intention and you plan to guard your service account credential against bad actors, then that's fine. But usually, when building apps for devices, you [Authenticate application users](https://cloud.google.com/docs/authentication/use-cases#app-users).

**Comment by shinnthant-lab** [comment]
> I believe this is the problem:
> 
> ```cs
> GrpcAdapter = RestGrpcAdapter.Default
> ```
> 
> I've just run a smoke test on this myself, and it works for gRPC but not for REST. It's _possible_ that you need to use an API key for REST for this API - I'm not sure.
> 
> Please run your console app test without specifying a gRPC adapter, to see if that addresses the problem, and I can then ask internally about expectations.

@jskeet it's work with grpc fine confirmed, somehow REST service bug.

**Comment by shinnthant-lab** [comment]
> And a note in parallel:
> 
> > Here is the credentials edited for your reference.
> > [credentials.json](https://github.com/googleapis/google-cloud-dotnet/files/13226849/credentials.json)
> 
> That does indeed look like a service account credential. I'm not certain that using a service account credential from Maui will work, we don't test in mobile infrastructures and that's precisely why we don't claim to support them. Regardless, it's uncommon to share a service account credential with your Android app users. That means that all users will be authenticating as the identity represented by the service account credential, i.e. the service account. It also means that a private key for your service account is stored in possibly many devices, from which it may be obtained and used by a bad actor.
> 
> If this is your intention and you plan to guard your service account credential against bad actors, then that's fine. But usually, when building apps for devices, you [Authenticate application users](https://cloud.google.com/docs/authentication/use-cases#app-users).

thanks for the information @amanda-tarafa , will try to follow the flow for the application users

**Comment by jskeet** [comment]
I have an update... it looks like it needs scopes in the auth token, and there are no default scopes.

I'll work on getting this fixed in a future update, but if you build your client as:

```csharp
var client = new RoutesClientBuilder
{
    Scopes = new[] { "https://www.googleapis.com/auth/cloud-platform" },
    GrpcAdapter = RestGrpcAdapter.Default
}.Build();
```

... then I believe it should work.

**Comment by shinnthant-lab** [comment]
> I have an update... it looks like it needs scopes in the auth token, and there are no default scopes.
> 
> I'll work on getting this fixed in a future update, but if you build your client as:
> 
> ```cs
> var client = new RoutesClientBuilder
> {
>     Scopes = new[] { "https://www.googleapis.com/auth/cloud-platform" },
>     GrpcAdapter = RestGrpcAdapter.Default
> }.Build();
> ```
> 
> ... then I believe it should work.

Thanks @jskeet for the update bro. Will try on that also.

**Comment by jskeet** [comment]
Note to myself: filed b/308895602.

**Comment by amanda-tarafa** [comment]
@shinnthant-lab I'm closing this issue now because there's not much else we can do client library side. There's an internal issue for the API team to add the missing scopes, and we'll update here once they have done so, but for the time being you can use @jskeet 's workaround from [this comment](https://github.com/googleapis/google-cloud-dotnet/issues/11261#issuecomment-1790189446).

Do leave a new comment here or create new issues if you run into other problems.
