### ISSUE TITLE
storage: Support custom endpoints for SignURLs

### ISSUE THREAD

**Issue by BrennaEpp** [googleapis/google-cloud-dotnet#11313]
When a custom endpoint is set on the client, Sign URLs and Post Policies should automatically use that domain.

Optional: allow users to set a custom hostname for Sign URL and Post policy methods.

See the following for more information and fill out language section: go/signurl-custom-endpoint-gcs
Please add a comment or ping me if you have any questions.

**Comment by jskeet** [comment]
> When a custom endpoint is set on the client, Sign URLs and Post Policies should automatically use that domain.

Our URL signer isn't created in the context of any client - see https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Storage.V1/latest#signed-urls for sample code. In other words, this will take a bit of a redesign.

We'll probably want to add a `CreateUrlSigner` method on `StorageClient`, or something similar. But it's definitely not just a matter of changing some implementation.

**Comment by BrennaEpp** [comment]
> Our URL signer isn't created in the context of any client - see https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Storage.V1/latest#signed-urls for sample code. In other words, this will take a bit of a redesign.

This was the same case for our Go client as well. We ended up adding a URL signer at the bucket level that calls the original URL signer. Other languages have the URL Signer on the object (Node, Python) or on the Client; any of these is fine.

Adding a URL signer under the client/bucket/object allows not only supporting the same custom endpoint automatically, it also enables automatic signing (which is a highly requested feature across languages) with the client's credentials.
