### ISSUE TITLE
Better way for setting operation timeout and retries in Firestore SDK

### ISSUE THREAD

**Issue by alex-namely** [googleapis/google-cloud-dotnet#11322]
Hello,

I'm looking for a convenient way of setting timeouts and optionally retries for basic Firestore operations.

As an example, I have a read document operation that in some _weird_ cases may be running for more than a minute:
```
firestoreDb.Collection(collectionName).Document(key).GetSnapshotAsync()
```

I am aware that there is a way to provide a cancellation token to some of methods but in my opinion, it is not a clean way to set timeout moreover using `CreateLinkedTokenSource` adds additional overhead and requires advanced technics (like pooling and disposing) to be used.

Naive example:
```
 var timeoutCts = new CancellationTokenSource();
 timeoutCts.CancelAfter(timeSpan);
 var combinedCts = CancellationTokenSource.CreateLinkedTokenSource(timeoutCts.Token, cancellationToken);
 return combinedCts.Token;
```

I can be wrong but I'm under impression that in .NET SDK timeouts and retries were hard-coded.
https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/FirestoreDb.cs#L78-L86

As a suggestion I would like to highlight Python SDK where setting timeouts and retries requires no effort.

https://cloud.google.com/python/docs/reference/firestore/latest/query
```
retry ([google.api_core.retry.Retry](https://googleapis.dev/python/google-api-core/latest/retry.html#google.api_core.retry.Retry)) – Designation of what errors, if any, should be retried. Defaults to a system-specified policy.
timeout ([float](https://python.readthedocs.io/en/latest/library/functions.html#float)) – The timeout for this request. Defaults to a system-specified value.
```

JFYI: There was an old issue https://github.com/googleapis/google-cloud-dotnet/issues/2471 but I think it is different.

**Comment by jskeet** [comment]
I'll try to have a look at this on Monday.

**Comment by jskeet** [comment]
Right. Having had a look now, I'm not sure why we're not using the `FirestoreSettings.BatchGetDocumentsSettings` instead of constructing separate ones. If we used that, users would at least be able to set it on a per-client basis. Not great in terms of flexibility (e.g. a different deadline for each call), but it'd be something.

In our "normal" generated libraries (including in Google.Cloud.Firestore.V1) you can pass a CallSettings in every operation - but Google.Cloud.Firestore is generally a more high-level with a little less flexibility.

I'll consult with colleagues about how this is handled in other languages. (Adding a CallSettings parameter *everywhere* in the handwritten layer would feel awkward...)

**Comment by alex-namely** [comment]
Hi @jskeet, have you had a chance to consult with your colleagues regarding this issue?

**Comment by jskeet** [comment]
@alex-namely: I did raise it, but I'm afraid I don't have a resolution. Right now we're in the middle of multiple urgent projects so I don't expect a resolution *soon* - but I'll definitely come back to it. Apologies for this taking a long time.

**Comment by jskeet** [comment]
Out of interest, if we were to honor `FirestoreSettings.BatchGetDocumentsSettings` (which would be somewhat awkward to set up, at the moment at least) would that client-wide setting be useful to you, or do you really need to be able to set it on every call?

(It's worth noting that under the hood, we do convert timeouts to a cancellation token - while also applying retry etc. But obviously we manage the disposal etc in that case.)

**Comment by alex-namely** [comment]
> Out of interest, if we were to honor `FirestoreSettings.BatchGetDocumentsSettings` (which would be somewhat awkward to set up, at the moment at least) would that client-wide setting be useful to you, or do you really need to be able to set it on every call?
> 
> (It's worth noting that under the hood, we do convert timeouts to a cancellation token - while also applying retry etc. But obviously we manage the disposal etc in that case.)

Yeah, I think this can be a good start!

**Comment by jskeet** [comment]
Notes to self... the current BatchGetDocumentsSettings are:

Hardcoded in FirestoreDb:

```csharp
            var batchGetRetry = RetrySettings.FromExponentialBackoff(
                maxAttempts: 5,
                initialBackoff: TimeSpan.FromMilliseconds(100),
                maxBackoff: TimeSpan.FromSeconds(60),
                backoffMultiplier: 1.3,
                retryFilter: RetrySettings.FilterForStatusCodes(StatusCode.Unavailable, StatusCode.Internal,             
          _batchGetCallSettings = CallSettings.FromRetry(batchGetRetry).WithTimeout(TimeSpan.FromMinutes(10));
StatusCode.DeadlineExceeded));
```

From FirestoreClient (generated):

```csharp
public gaxgrpc::CallSettings BatchGetDocumentsSettings { get; set; } = gaxgrpc::CallSettings.FromExpiration(gax::Expiration.FromTimeout(sys::TimeSpan.FromMilliseconds(300000)));
```

Interestingly, the FirestoreDb code claims that the retry settings are from the service config - but there's no retry specified in the generated code. It looks to me like there *should* be retries, given the [service config](https://github.com/googleapis/googleapis/blob/master/google/firestore/v1/firestore_grpc_service_config.json) so I need to look into what's going on there.

But aside from anything else, there's the "5 minute vs 10 minute" timeout difference. We'll need to work out how to do this without breaking folks.

-

**Comment by jskeet** [comment]
Ah, we don't generate a retry configuration because this is a server-streaming call - we don't retry automatically for any streaming calls in general.

However, we also have custom retry code within FirestoreDb, with this comment:

```csharp
            // This is the function that we'll retry. We can't use the built-in retry functionality, because it's not a unary gRPC call.
            // (We could potentially simulate a unary call, but it would be a little odd to do so.)
            // Note that we perform a "whole request" retry. In theory we could collect some documents, then see an error, and only
            // request the remaining documents. Given how rarely we retry anyway in practice, that's probably not worth doing.
```

The retry settings in this call aren't observed by GAX - we're really just using CallSettings to keep them in one place. It's easy to separate that out.

**Comment by jskeet** [comment]
I've been reviewing some internal documentation, and I think our timeout of 10 minutes is an outlier - changing it to the default of 5 minutes should be okay (and realistically, I'd be surprised if that ever caused a problem).

There's a bit of an oddity: setting a retry on FirestoreSettings.BatchGetDocumentsSettings etc would (without intervention) cause the client creation to fail, as GAX validates that there are no retries on client creation. However, we could allow a user-specified `FirestoreSettings` to contain retries, that we strip out in `FirestoreDbBuilder`, and retain for use in `GetDocumentSnapshots` etc.
This does come with a bit of a drawback though: if someone just creates a `new FirestoreSettings()` then they won't have any retry information at all, so if they just wanted to tweak *one* small aspect (for an entirely unrelated RPC) then that would mess things up.

I think a simpler approach will be to add a separate `FirestoreDbBuilder.BatchGetDocumentsRetrySettings` property (and explain where it's used).

**Comment by jskeet** [comment]
This is now merged (with `FirestoreDbBuilder.BatchGetDocumentsRetrySettings`) and will be in the next release, which I *expect* to be some time next week.
