### ISSUE TITLE
Google.Cloud.Datastore.V1  : How to specify databaseid 

### ISSUE THREAD

**Issue by yashhema** [googleapis/google-cloud-dotnet#11343]
Hello,
We want to move to multiple database in one project , when trying to use the c# client - we are unable to specify database id (but able to do so in go)

Any help will be appreciated

**Comment by jskeet** [comment]
Multiple databases are currently only in preview, so aren't supported in our GA libraries. We have been considering releasing beta libraries supporting multiple databases, but we expect the feature will go to GA soon enough that it's not worth doing that.

**Comment by yashhema** [comment]
Hello, 
Do you have a time frame for client library release, is it going to happen somewhere in next year jan or see it beyond it.
We have existing code , for firebase (native) we are able to use reflection , but unable to understand the same for datastore , is there a way for us to set database id (till the time official release of library happens)

**Comment by jskeet** [comment]
I would *expect* it to be early next year - if it looks like it'll be later than that, we're more likely to release an interim beta.

The code to suppose multiple databases for Firestore isn't merged yet, so there's no direct workaround like using reflection.

**Comment by yashhema** [comment]
For firestore we are able to do (its from one of the post ) using reflection , but for datastore we are unable to do
For firestore , its like
``
public static async Task<FirestoreDb>  CreateFireStoreDbForParticularDBId(string projectid,string dbid,ChannelCredentials cc)
        {
            var fcb =  new FirestoreClientBuilder();

            if(cc !=null)
            {
                fcb.ChannelCredentials = cc;    
            }
            FirestoreClient firestoreClient = fcb.Build();
            var create = typeof(FirestoreDb).GetMethod(
                "Create",
                BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public,
                new Type[]
                {
        typeof(string),
        typeof(string),
        typeof(FirestoreClient),
        typeof(Action<string>),
        typeof(ConverterRegistry)
                });
            var newdb = (FirestoreDb)create!.Invoke(
                null,
                new object[]
                {
        projectid,
        dbid,
        firestoreClient,
        null!,
        null!,
                })!;

            return newdb;
        }

`'

**Comment by jskeet** [comment]
Yes, I'm aware of what you'd do in Firestore (although I still discourage it, to be honest - and if the reflection code breaks in a later version, that's definitely not something we'd consider a "breaking change" in the normal way). But as I said before, the code simply hasn't been merged for Datastore yet. (See #11220.)

We're discussing potentially releasing betas for the Firestore and Datastore libraries in early December (once our current release freeze is over) but there's really not point in adding additional code snippets into this issue.

**Comment by yashhema** [comment]
If its early december , we are good. Thanks a lot

**Comment by jskeet** [comment]
This has now been released in Google.Cloud.Datastore.V1 4.7.0.
