### ISSUE TITLE
 Google.Cloud.Firestore Document.UpdateAsync Precondition.MustExist cannot be explicitly set as argument

### ISSUE THREAD

**Issue by SteGaff7** [googleapis/google-cloud-dotnet#11361]
#### Environment details

  - OS: MacOS Sonoma V14.0
  - .NET version: 7.0
  - Package name and version: Google.Cloud.Firestore 3.4.0

#### Steps to reproduce

  1. If you explicitly set the precondition parameter to Precondition.MustExist in the UpdateAsync method:
```            
await db
        .Collection("path")
        .Document("id")
        .UpdateAsync("field", value, Precondition.MustExist, cancellationToken);
``` 

an exception is thrown

```
Cannot specify a must-exist precondition for update (Parameter 'precondition')
      System.ArgumentException: Cannot specify a must-exist precondition for update (Parameter 'precondition')
         at Google.Api.Gax.GaxPreconditions.CheckArgument(Boolean condition, String paramName, String message)
         at Google.Cloud.Firestore.WriteBatch.Update(DocumentReference documentReference, IDictionary`2 updates, Precondition precondition)
         at Google.Cloud.Firestore.DocumentReference.UpdateAsync(IDictionary`2 updates, Precondition precondition, CancellationToken cancellationToken)
```

However if you leave this as null which is equivalent to Must Exist ("May be null, which is equivalent to MustExist.") it works as expected.

**Comment by jskeet** [comment]
I'll have a look at this on Monday.

**Comment by jskeet** [comment]
(Marking as "external" not because it's a service bug, but because it requires wider Google scrutiny - we can't act unilaterally here.)

**Comment by SteGaff7** [comment]
Hi Jon, thanks for the reply and explanation!

**Comment by jskeet** [comment]
Sorry for the delay getting back to this, but I'm intending to update the conformance test and the code to allow the precondition to be specified explicitly.

**Comment by jskeet** [comment]
Thanks for your patience here. This will go out in the next Firestore release, which I *hope* will be next week.
