### ISSUE TITLE
.NET8 vs Cloud run : a mismatch somewhere ?

### ISSUE THREAD

**Issue by glb-cblin** [googleapis/google-cloud-dotnet#11404]
This is not a bug report for the library, but because the Google support are not .NET experts, I'm trying to have an answer here ...

Since we upgraded to .NET8, we are seeing our containers crashing regularly with 100% RAM consumption

However, the number of incoming requests is not so high and we did not have this issue with .NET6 containers for the same amount of RAM and incoming requests (and even with more incoming requests)

For reference, we have 1 CPU / 512Mo RAM.

Here is a screenshot for .NET8 (highlithed with crashes in red) 
![image](https://github.com/googleapis/google-cloud-dotnet/assets/140622709/1abead1e-dd01-4126-90d8-fb447eee60b3)

And the "same" screenshot for .NET6
![image](https://github.com/googleapis/google-cloud-dotnet/assets/140622709/449faecb-2207-4c14-a813-d3e00a6ee180)

You can see in .NET6 that RAM was always around 50% whereas in .NET8 it's more 80% (which makes for 150Mo more in .NET8)

My intuition is that either .NET8 consumes more memory OR the GC behavior has changed in .NET7 or .NET8 : are you aware of something like this ?

Are you aware of setttings to configure the GC to behave more like .NET6 (which looks like "free the memory more often") ?

I had a look into https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector but I cannot find something relevant here
The only thing that triggers me is https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc#workstation-gc 
> Workstation garbage collection is always used on a computer that has only one logical CPU, regardless of the configuration setting

This does seem true for .NET6 but not for .NET8 (because RAM is never freed before reaching 75%)

Do you have an idea to repro on my machine (i.e my machine has i7 and 32Go RAM so I do not have this memory issue and CPU throtling issue... )

**Comment by Rishabh-V** [comment]
I will research and check internally with the team and try to provide an update when I know more about it. Thanks for your patience.
(Currently, I am going through this [blog](https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-8/#gc))

**Comment by glb-cblin** [comment]
Thanks @Rishabh-V 

Based on your blog post + the doc at https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector + the doc at https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc

I'm going to try 
```
ENV DOTNET_gcServer=0
ENV DOTNET_gcConcurrent=0
```
This should allow the GC to work "on the fly" (i.e not being throtlled by Cloud run with a bakground thread)

Then I'll try what is described in the blog if that does not work (hope I do not need to do that ... :) )
```
ENV DOTNET_GCName=libclrgc.so
```

**Comment by jskeet** [comment]
@glb-cblin: Any updates? I'd like to close this if there's not further action to take in this repo.

**Comment by glb-cblin** [comment]
for the moment, seems to work with ENV DOTNET_gcServer=0 + ENV DOTNET_gcConcurrent=0

**Comment by mnebes** [comment]
Hi everyone,

I found this issue while investigating strange memory spikes on our .NET 8 deployments in Cloud Run. We have a bunch of stuff running on .NET in Cloud Run, mostly F# projects. In our case, since migrating from .NET 7 to .NET 8 we started noticing strange peaks in memory usage. Our setup was pretty similar: 1000 mCPUs, 0.5 or 1 GB of RAM. We've added some periodic GC logs to see what's happening and one thing stood out: dotnet runtime reported that it had 2 CPUs. I suspect this made the Garbage Collector assume it can use concurrent GC and sometimes it meant the GC was never triggered until the instance was killed by Cloud Run for exceeding the memory limit.

Fortunately, since .NET 6 one can override the CPU count by setting `DOTNET_PROCESSOR_COUNT` env var and when we set it to `1` the memory consumption stabilized. Here is how it looked like before and after:
![image](https://github.com/googleapis/google-cloud-dotnet/assets/16987208/fa5d31f7-f88a-4ffa-913e-9e41b91d73c6)

Do you think this something to be reported to the dotnet runtime team or is it something Cloud Run specific? (I'm not sure how the dotnet runtime infers the number of CPUs available and how Cloud Run exposes this information.)

For now, setting the processor count stabilized our deployments, so I hope this may help anyone who stumbles upon it. Let me know if I can provide any more information.

**Comment by jskeet** [comment]
> Do you think this something to be reported to the dotnet runtime team or is it something Cloud Run specific?

I think I'd suggest reporting it to the dotnet runtime team first, asking that if they believe it's Cloud Run specific, they suggest details of how the Cloud Run team should investigate.

**Comment by glb-cblin** [comment]
@mnebes please see https://github.com/dotnet/docs/issues/38634

**Comment by mnebes** [comment]
> > Do you think this something to be reported to the dotnet runtime team or is it something Cloud Run specific?
> 
> I think I'd suggest reporting it to the dotnet runtime team first, asking that if they believe it's Cloud Run specific, they suggest details of how the Cloud Run team should investigate.

Thanks! I'll see where I can report that.

**Comment by glb-cblin** [comment]
Sorry, I now understand what you mean by
>  dotnet runtime reported that it had 2 CPUs.

So, because it did not happen with .NET 6 (or .NET 7 for you), you suspect there was a change in .NET to detect the number of CPUs

However, we are also having the same problem on .NET6 applications since we published new revisions
And the same fix is working (i.e setting DOTNET_gcServer=0 + DOTNET_gcConcurrent=0, I was not aware of DOTNET_PROCESSOR_COUNT )

So, I've look at .NET6 doc for ProcessorCount and I now have an hypothesis/intuition that Cloud run has a temporary startup CPU boost which confuses .NET

See https://learn.microsoft.com/en-us/dotnet/api/system.environment.processorcount?view=net-6.0#remarks
![image](https://github.com/googleapis/google-cloud-dotnet/assets/140622709/39731453-85c8-4ec3-b0f2-b565e1b43f51)

WDYT ?

**Comment by mnebes** [comment]
Oh I didn't think about the boost. There might be something to it. I tried a minimal repro with a Hello World project and CPU boost switched off, but it still I get 2 Processors returned by `Environment.ProcessorCount`.

I even tried to call the underlying private `GetProcessorCount` method to get around the [static property](https://github.com/dotnet/runtime/blob/d7d3c6bcee82b306d509748f90f35e113ee9ec29/src/libraries/System.Private.CoreLib/src/System/Environment.cs#L14) to see if the value changes but unless it is also cached somewhere in the native code, it consistently reads 2 CPUs.

Here's the code I tried:

```csharp
using System.Reflection;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

var port = Environment.GetEnvironmentVariable("PORT") ?? "8080";
var url = $"http://0.0.0.0:{port}";

var method = typeof(Environment).GetMethod("GetProcessorCount", BindingFlags.Static | BindingFlags.NonPublic);
var getProcessorCount = () => method.Invoke(obj: null, parameters: []);

app.MapGet("/", () => "Hello World!");
app.MapGet("/processors", () => $"Processors: {getProcessorCount()}");

app.Logger.Log(LogLevel.Information, "Processor count: {ProcessorCount}", Environment.ProcessorCount);

app.Run(url);
```

**Comment by glb-cblin** [comment]
Maybe linked to https://stackoverflow.com/q/67164850/1545567 ?

**Comment by mnebes** [comment]
> Maybe linked to [stackoverflow.com/q/67164850/1545567](https://stackoverflow.com/q/67164850/1545567) ?

Might be indirectly, but that's an older issue and we only started experiencing it now, so my guess is something must've changed in the runtime 🤷 

I opened an issue in the dotnet/runtime repo: https://github.com/dotnet/runtime/issues/99046

**Comment by glb-cblin** [comment]
Ah you're absolutely right !

I'll subscribe to the issue

Good luck

**Comment by mnebes** [comment]
@jskeet according to https://github.com/dotnet/runtime/issues/99046#issuecomment-1971835003 I should also reach out to a GCP team, could you point me in the right direction?

**Comment by jskeet** [comment]
@mnebes: At this point I'll need to reach out internally even to work out who can be contacted publicly. I'm on vacation today, but I'll look into it on Monday.

**Comment by mnebes** [comment]
@jskeet thank you so much and sorry to disturb your vacation! This can definitely wait, especially since there are workarounds, so no worries. Enjoy the rest of your vacation!

**Comment by mnebes** [comment]
@jskeet FYI there is a fix in the runtime for this but it [might only be coming with .NET 9](https://github.com/dotnet/runtime/issues/99046#issuecomment-1992946251). If that'll be the case, maybe some guidance for Cloud Run .NET 8 users would be useful?

**Comment by jskeet** [comment]
@mnebes: There's an internal bug where this is being discussed - it'll really be up to the Cloud Run team to decide what to do. (I'm not on the Cloud Run team.)

**Comment by AustinWise** [comment]
The fix on the Cloud Run side should be rolled out now. I tested using [my test application](https://github.com/AustinWise/TestCpuCount) and `Environment.ProcessorCount` now returns 1 when running in a gen 1 execution environment configured with a single CPU.
