### ISSUE TITLE
[Google.Cloud.Logging.NLog] Support for NLog 5

### ISSUE THREAD

**Issue by SeanFeldman** [googleapis/google-cloud-dotnet#11465]
The [current version](https://www.nuget.org/packages/Google.Cloud.Logging.NLog) of the adapter is 4.0.0, targeting `NLog` version 4.7.15 and higher.
Should the package be updated to target version [5.x](https://www.nuget.org/packages/NLog/#versions-body-tab) and versioned as 5.0.0?

**Comment by jskeet** [comment]
Yes, that would make sense. I don't know when we'll get to it, but hopefully within a couple of weeks.

**Comment by jskeet** [comment]
We've now released Google.Cloud.Logging.NLog version 5.0.0-beta01 (it'll take a little while to be indexed). Please give it a try, and we'll release a GA version after it's had time to bake (just in case anyone runs into problems).
