### ISSUE TITLE
Google.Cloud.Storage.V1 - create folder

### ISSUE THREAD

**Issue by mvdgun** [googleapis/google-cloud-dotnet#11484]
**Is your feature request related to a problem? Please describe.**

I am working on integrating a Google Cloud Storage adapter into my [FileSystem](https://github.com/SharpGrip/FileSystem) project. While I can successfully create a directory using the cloud portal,  I cannot seem to do so through the Google.Cloud.Storage.V1 .NET library.

 **Describe the solution you'd like**

I would like to have an API method (or some other official way) to create a folder in a GCP storage bucket via the Google.Cloud.Storage.V1 .NET library.

 **Describe alternatives you've considered**

I have tried to create a folder like so;

```
await client.UploadObjectAsync("bucket", "folderName", null, new MemoryStream(), cancellationToken: cancellationToken);
```

But that just creates a 0B file with an empty "Type" in the portal/bucket.

I also found the following resource but I would like to use an official SDK method instead of going through the API directly.

https://www.googlecloudcommunity.com/gc/Developer-Tools/How-to-create-a-Folder-in-the-GCP-Bucket-using-API/m-p/507047

**Comment by mvdgun** [comment]
I managed to create a folder via the library:

```
await client.UploadObjectAsync("bucketName", "folderName/", null, Stream.Null, cancellationToken: cancellationToken);
```

The important part is the trailing forward slash in the object name. Is this how we are supposed to create folders?

**Comment by amanda-tarafa** [comment]
In Google Cloud Storage, there are no folders. For convenience there are a couple of ways in which folders may be simulated. One such way is to use the forward slash as a "folder" delimiter. See [About Cloud Storage Objects - Object Namespaces](https://cloud.google.com/storage/docs/objects#namespace) for more information.
