### ISSUE TITLE
Unable to get response from RouteMatrix: Request contains an invalid argument.","grpc_status":3

### ISSUE THREAD

**Issue by David52920** [googleapis/google-cloud-dotnet#11480]
#### Environment details

  - OS: Windows 11
  - .NET version: 4.8
  - Package name and version: [Google.Maps.Routing.V2] 1.0.0-beta10

Issue:
I am trying to use the RouteAPI to get distances from location to locations (1 to many) however I am getting an error when trying to run the code below, am I missing something?

It seems to crash only when using the ComputeRouteMatrix method. It works fine individually with ComputeRoute method.

Error message:

> CoreErrorDetailException: {"created":"@1704378883.638000000","description":"Error received from peer ipv4:","file":"..\..\..\src\core\lib\surface\call.cc","file_line":953,"grpc_message":"Request contains an invalid argument.","grpc_status":3}

Async ComputeRouteMatrix Method
```
            RoutesClient client = await RoutesClient.CreateAsync();

            CallSettings callSettings = CallSettings.FromHeader("X-Goog-FieldMask", "routes.legs.distanceMeters");

            var origin = new Waypoint{ Location = new Location { LatLng = new LatLng { Latitude = 41.7682, Longitude = -83.5797 } }};
            var dest = new Waypoint { Location = new Location { LatLng = new LatLng { Latitude = 40.8154, Longitude = -73.0451 } } };

            ComputeRouteMatrixRequest request = new ComputeRouteMatrixRequest
            {
                Origins = { new RouteMatrixOrigin { Waypoint = origin }, },
                Destinations = { new RouteMatrixDestination { Waypoint = dest }, },
                TravelMode = RouteTravelMode.Drive,
                RoutingPreference = RoutingPreference.Unspecified,
            };
            using (RoutesClient.ComputeRouteMatrixStream response = client.ComputeRouteMatrix(request, callSettings))
            {
                AsyncResponseStream<RouteMatrixElement> responseStream = response.GetResponseStream();

                while (await responseStream.MoveNextAsync()) //<- fails here
                {
                    RouteMatrixElement responseItem = responseStream.Current;
                    Console.WriteLine(responseItem.ToString());
                }
            }
```

**Comment by jskeet** [comment]
I'm afraid this sounds like something you'll need to take up with Google Maps support. I strongly suspect that the .NET library itself is fine, but there's something about your request which is invalid. I can't tell what it is by just inspection, but the maintainers of this repository aren't able to provide API-specific support other than for a few APIs where we maintain hand-written clients.

Please follow one of the support options on https://developers.google.com/maps/documentation/routes/support

You might also want to *try* specifying a field mask of just "*" in case it's the field mask that's causing the problem.

**Comment by David52920** [comment]
You are correct, it was the field mask. I changed it to distanceMeters instead and it worked. Thank you!
