### ISSUE TITLE
Add the ability to override the default firestore db when creating a FirestoreDb instance

### ISSUE THREAD

**Issue by mostafa-abdalla** [googleapis/google-cloud-dotnet#11562]
We need to connect to other databases other the the `(default)` database and at the moment its not possible to pass the databse id to [FirestoreDb.Create](https://github.com/googleapis/google-cloud-dotnet/blob/138e5674072b2bee3a1d9a3a8f0de8cd23493938/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/FirestoreDb.cs#L102)
 
A solution can be to allow passing the databaseId.

The alternative at the moment it to keep using the (default) database.

**Comment by jskeet** [comment]
This is already available in the latest beta release using `FirestoreDbBuilder.DatabaseId`. (We're not expanding the set of overloads of `FirestoreDb.Create`, as that could get very messy as extra options are added. The `Create` method was introduced before we started using the builder pattern; in future, all options will be supported via `FirestoreDbBuilder` instead.)

We expect to publish a non-beta version with this functionality in the next week or two.
