### ISSUE TITLE
Add support for Gemini model in Vertex AI for .NET

### ISSUE THREAD

**Issue by vandana2015** [googleapis/google-cloud-dotnet#11576]
**Is your feature request related to a problem? Please describe.**
I want to connect to Gemini LLM model using this nuget - https://www.nuget.org/packages/Google.Cloud.AIPlatform.V1 . I tried to connect via the PredictionServiceClient. However I am not able to use it. 
Currently I get following message if I access ia the Predict api. - 
`StatusCode=\"FailedPrecondition\", Detail=\"Gemini cannot be accessed through Vertex Predict/RawPredict API. Please follow https://cloud.google.com/vertex-ai/docs/generative-ai/start/quickstarts/quickstart-multimodal for Gemini usage.\"`

 **Describe the solution you'd like**
I can connect via REST calls, but I would like to have access via client library sdk, like support is provided for JAVA and other languages.

**Comment by vandana2015** [comment]
Hi, 
is there any ETA on this?
Thanks.

**Comment by amanda-tarafa** [comment]
Thanks for your request. We are working with the Vertex API team to enable Google.Cloud.AIPlatform.V1 for Gemini models.
We'll update this issue as we move along, but know that currently we have no ETA.

**Comment by jskeet** [comment]
Marking this as fixed, as with the new library version you should have access to the RPC you need.
