### ISSUE TITLE
Firestore collection name customization

### ISSUE THREAD

**Issue by SeanFeldman** [googleapis/google-cloud-dotnet#11596]
**Is your feature request related to a problem? Please describe.**
When working with a collection that does not follow the .NET class naming convention, there seems to be no way to use a convention to specify the collection name, and developers are forced to provide a string whenever a collection is involved in the code. This is inconvenient and inconsistent with a model properties approach taken by the SDK, where a property name override can be provided with the `FirestoreProperty` attribute.

 **Describe the solution you'd like**
Provide a consistent convention to override a collection name by introducing a `FirestoreCollection` attribute that takes a `Name` property to be used instead of the C# class name.

**Comment by jskeet** [comment]
I'm confused as to exactly what you're doing - as collection names aren't part of the serialization anyway, are they? (We only serialize to documents, not to collections.) If you could provide an example, that would really help.

**Comment by SeanFeldman** [comment]
Here's an example of what I commonly see in the code base working on.

```c#
public override async Task<T> AddOrUpdate(T entity, CancellationToken ct)
{
	var collectionReference = firestoreDb.Collection(typeof(T));

	var doc = string.IsNullOrWhiteSpace(entity.Id)
		? collectionReference.Document()
		: collectionReference.Document(entity.Id);
	var documentReference = GetDocument(entity);

	await documentReference.SetAsync(entity, cancellationToken: ct);

	entity.Id = documentReference.Id;

	return entity;
}
```

The emphasis is on `var collectionReference = firestoreDb.Collection(typeof(T));` line.
If the type is `DeviceCode`, the collection will be named `DeviceCode`. Let's say the collection already exists, and it's called `device_codes`. To work with the given collection, today, the only option is to set a constant to a value of `device_codes` and use the constant whenever a collection access is required. 

```c#
public const string CollectionName = "device_codes";

public override async Task<T> AddOrUpdate(T entity, CancellationToken ct)
{
	var collectionReference = firestoreDb.Collection(CollectionName);
        ...
}

public override async Task<T?> Get(string id, CancellationToken ct)
{
	var collectionReference = firestoreDb.Collection(CollectionName);
        ...
}
```

This could be avoided if an attribute similar to `FirestoreProperty` would allow customizing the name. It would remove the need to have a constant and would consolidate the code associated with the definition of the model with the collection name in one place - the C# class used to work with the documents of that model.

Example:

```c#
[FirestoreCollection(Name="device_codes")]
public class DeviceCode {}

public override async Task<T> AddOrUpdate(T entity, CancellationToken ct)
{
	var collectionReference = firestoreDb.CollectionForType(entity.GetType());
        ...
}

public override async Task<T?> Get(string id, CancellationToken ct)
{
	var collectionReference = firestoreDb.CollectionForType(typeof(T));
        ...
}
```

**Comment by SeanFeldman** [comment]
I thought about an extension method, but the problem is that an extension method with frequent invocation would not be able to cache the name to be used with every model. In my custom solution, I built a registry with a concurrent dictionary as a cache for the once-resolved names. This is happening on a hot path, and I don't want to constantly look up an override for every Web API call that's made. That's why I've raised the issue to see if the .NET SDK could A) provide an option to define a collection custom name and B) encapsulate the logic of keeping the names resolved once and not for every call.

I don't have insights into other language SDKs and whether a similar request has been made, but that's a fair approach. Thank you.

**Comment by jskeet** [comment]
Any reason not to use a static concurrent dictionary for caching? It's not like it would be change for any given type, regardless of which FirestoreDb you called it on.

**Comment by SeanFeldman** [comment]
Statics are hard to test. The registry is registered as a singleton and acts as a "static". But that's another dependency to take on, whereas, with the SDK, it would be more natural. This approach also requires a custom attribute to be maintained that's not a part of the GCP SDK for Firestore. A property needed to discover a collection name override. Arguably, the mapping could be done w/o a custom attribute and directly within the registry, but then it goes against what I mentioned earlier, the mental modal where the C# document model is the source of the information about how the document is serialized and where.

**Comment by jskeet** [comment]
Okay, well I'll ask the other language teams - but as I say, I don't expect to be implementing this any time soon, given that it really is quite a departure (as *everything* else in terms of attributes is within a document rather than about collections).

**Comment by jskeet** [comment]
Okay, I've consulted the team, and I'm afraid I'm going to close this issue - for now. In the discussion, some alternative API surface options (that were discussed at the start of the project and rejected at the time) were raised - having `CollectionReference<T>` and `DocumentReference<T>` effectively. That sort of thing is currently not in place, and really feels like it's the way we'd want to approach this. Adding the attribute alone wouldn't do anything - we'd already need extra methods such as the `CollectionForType` that you mentioned, and having that just in non-generic terms would feel hacky to be honest. I'd rather wait and *potentially* do the complete job later on.

For the moment, I'd urge you to reconsider the extension method approach. While global state isn't easily testable, it would be pretty easy to implement this in a way that is *almost entirely* testable, e.g. having a testable `TypeToCollectionCache` type, and have single-line extension methods which use a singleton instance of that. (It's not like the attributes on a type can change over time. They're already global state, effectively.) Yes, you'd be taking on more code to maintain yourself - but as the only customer who's expressed an interest in this way of using Firestore, that feels reasonable to me at the moment.

Certainly if we ever add a more directly model-based generic set of types, I'll look at having the collection name optionally be derived from an attribute - but for the moment I'll close this. I know that's not the outcome you were hoping for, but please don't let it discourage you from further feature requests. (I still want to implement #11454 when the other aspects are in place, for example.)
