### ISSUE TITLE
Document sending PubSub messages unwrapped when using `PublisherServiceApiClient`

### ISSUE THREAD

**Issue by atrauzzi** [googleapis/google-cloud-dotnet#11594]
_Originated from discussion over at https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/2450#issuecomment-1913307907_

I haven't been able to find any guidance yet in the .NET SDK around sending unwrapped messages through PubSub, hoping to get some pointers :slightly_smiling_face: 

```csharp
        // note: Somewhere in my app bootstrap....
        serviceCollection.AddPublisherServiceApiClient((builder) =>
        {
            // note: How can I use `builder` here to configure the client so that it sends unwrapped?
        });
```

Then, elsewhere in my application, when I want to publish, I use `PublisherServiceApiClient cloudPubSubClient`:

```csharp
        await cloudPubSubClient.PublishAsync(
            pubSubTopicName,
            new PubsubMessage[]
            {
                new()
                {
                    Data = ByteString.CopyFrom(myData.ToDiscriminatedJsonByteArray()),
                },
            }
        );
```

:crossed_fingers: I'm hoping that I'm following [the docs](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.PubSub.V1/latest#getting-started) correctly so far.  There's advice on the pages that talks about using `PublisherServiceApiClient` over `PublisherClient`.

![image](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/assets/115199/327a2a1c-0453-472b-a800-9122a409accb)

**Comment by jskeet** [comment]
As I understand it, unwrapped sending is a feature of the push subscription, not the publisher. (The same topic can have a mixture of subscriptions.)
