### ISSUE TITLE
Support for parameters like temperature, TopP for mutimodels like Gemini in .NET

### ISSUE THREAD

**Issue by vandana2015** [googleapis/google-cloud-dotnet#11655]
**Is your feature request related to a problem? Please describe.**
I want to connect to Gemini LLM model using this nuget - https://www.nuget.org/packages/Google.Cloud.AIPlatform.V1 (version - 2.21). I am able to connect to Gemini using Prediction Service client method `StreamGenerateContent`- . However I am not able to set the parameters like temperature, topP etc. This is supported in methods like PredictAsync in the same PredictionServiceClient. 

 **Describe the solution you'd like**
Please add support to set parameters like temperature, topP etc for Gemini.

**Comment by jskeet** [comment]
This isn't something for the .NET client libraries team, I'm afraid. We just publish libraries based on the API definitions here: https://github.com/googleapis/googleapis/tree/master/google/cloud/aiplatform/v1

Having said that, `StreamGenerateContent` accepts `GenerateContentRequest`, which includes a [`GenerationConfig`](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.AIPlatform.V1/latest/Google.Cloud.AIPlatform.V1.GenerationConfig) field - that includes `Temperature`, `TopP` etc. Does that not do what you want?

**Comment by vandana2015** [comment]
Thanks, it is working.
