### ISSUE TITLE
Add GenerateContent method in PredictionServiceClient in Vertex AI in .NET

### ISSUE THREAD

**Issue by vandana2015** [googleapis/google-cloud-dotnet#11691]
**Is your feature request related to a problem? Please describe.**
Please add support for `GenerateContent `in `PredictionServiceClient `in .NET Vertex AI as defined here - https://github.com/googleapis/googleapis/blob/master/google/cloud/aiplatform/v1/prediction_service.proto#L167.

 **Describe the solution you'd like**
Support for GenerateContent in PredictionServiceClient.

 **Describe alternatives you've considered**
I am able to use StreamGenerateContent (https://github.com/googleapis/google-cloud-dotnet/issues/11576), which works same but returns response as stream.

 **Additional context**

**Comment by jskeet** [comment]
This is in the v2.22.0 release, which was released about half an hour ago. (It'll take a little while longer for documentation to be published.)
