### ISSUE TITLE
Support for retry settings for streaming calls in PredictionServiceClient

### ISSUE THREAD

**Issue by vandana2015** [googleapis/google-cloud-dotnet#11690]
**Is your feature request related to a problem? Please describe.**

I want to implement Retry logic in my application when using Google Cloud AI Platform's `PredictionServiceClient `. I want to use the same retry and timeout properties for all calls using the PredictionServiceClient. Earlier In same application, I have used azure openai nuget (https://www.nuget.org/packages/Azure.AI.OpenAI/) where I was able to provide the retry properties in the client creation phase like below -

   
```
OpenAIClientOptions opts = new OpenAIClientOptions();
    opts.Retry.MaxRetries = 2;
    opts.Retry.Delay = TimeSpan.FromSeconds(60);
    opts.Retry.NetworkTimeout = TimeSpan.FromSeconds(100);
    opts.Retry.Mode = (RetryMode)connDetails.AzureOpenAIRetryMode.Value;
client = new OpenAIClient(new Uri("sampleUrl"),new AzureKeyCredential("sampleKey"), opts);
```

I am using the Google Cloud AI Platform's PredictionServiceClient to stream content generation like below -

`Google.Cloud.AIPlatform.V1.PredictionServiceClient.StreamGenerateContentStream response = myPredictionServiceClient.StreamGenerateContent(generateContentRequest);`

**Describe the solution you'd like -**
To have ability to provide retry configuration when creating the PredictionServiceClient. Ability to apply same retry properties for all service calls like Predict, StreamGenerateContent etc. called using this client.

**Describe alternatives you've considered**
Below is the code I wrote for retry -

        PredictionServiceSettings settings = new PredictionServiceSettings
        {
            CallSettings = CallSettings.FromRetry(RetrySettings.FromExponentialBackoff(
                                            maxAttempts: 2,
                                            initialBackoff: TimeSpan.FromSeconds(1),
                                            maxBackoff: TimeSpan.FromSeconds(10),
                                            backoffMultiplier: 2,
                                            retryFilter: RetrySettings.FilterForStatusCodes(StatusCode.Unavailable)
                                            )).WithTimeout(TimeSpan.FromSeconds(100))
        };

        bardClient = await new PredictionServiceClientBuilder
        {
            Settings = settings,
            Endpoint = connDetails.AzureOpenAIResourceUrl
        }.BuildAsync();

An error is thrown at the StreamGenerateContent method call when using above code to create the client. The Google **API does not permit retries for this type of operation.** Below is the error message -
```
  HResult=0x80131509
  Message=Retry not permitted for this operation type
  Source=Google.Api.Gax.Grpc
  StackTrace:
   at Google.Api.Gax.Grpc.CallSettingsExtensions.ValidateNoRetry(CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiServerStreamingCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
   at Google.Cloud.AIPlatform.V1.PredictionServiceClientImpl.StreamGenerateContent(GenerateContentRequest request, CallSettings callSettings) in Google.Cloud.AIPlatform.V1\PredictionServiceClientImpl.cs:line 250

```
It originates from this method in the google API code - https://github.dev/googleapis/gax-dotnet/blob/ee799ad91309ef3102dee60f1baa67d7ec772548/Google.Api.Gax.Grpc/CallSettingsExtensions.cs#L192

**Comment by vandana2015** [comment]
Looking at below snippet of google API code, it looks like it is not allowed for non streaming calls as well -
```
 /// <summary>
 /// <see cref="gaxgrpc::CallSettings"/> for synchronous and asynchronous calls to
 /// <c>PredictionServiceClient.DirectPredict</c> and <c>PredictionServiceClient.DirectPredictAsync</c>.
 /// </summary>
 /// <remarks>
 /// <list type="bullet">
 /// <item><description>This call will not be retried.</description></item>
 /// <item><description>No timeout is applied.</description></item>
 /// </list>
 /// </remarks>
 public gaxgrpc::CallSettings DirectPredictSettings { get; set; } = gaxgrpc::CallSettings.FromExpiration(gax::Expiration.None);

```
Will try it out.

**Comment by jskeet** [comment]
> Looking at below snippet of google API code, it looks like it is not allowed for non streaming calls as well

That doesn't show that it's not allowed. It shows that it doesn't retry *by default* - that's a very big difference.

**Comment by jskeet** [comment]
I'm closing this now, as in other issues it looks like you've been looking at getting the unary call working.

Fundamentally, if you want to perform retry for a streaming RPC, at the moment you'll need to do it at the application level.
