### ISSUE TITLE
Allow setting custom time when uploading an object (Google.Cloud.Storage.V1)

### ISSUE THREAD

**Issue by provegard** [googleapis/google-cloud-dotnet#11753]
**Is your feature request related to a problem? Please describe.**

To upload an object and set its current time, I currently have to execute two operations:

1. `UploadObjectAsync`
2. `PatchObjectAsync` with `Object.CustomTimeDateTimeOffset` set

It would be nice to be able to upload an object and set the custom time as a single operation.

 **Describe the solution you'd like**

Unless I'm mistaken, the [underlying API](https://cloud.google.com/storage/docs/json_api/v1/objects/insert) has support for setting a custom time when uploading/inserting an object.

I'd like for some way to set a custom time on upload, e.g. in `UploadObjectOptions`.

 **Describe alternatives you've considered**

I tried to use `CreateObjectUploader`. However, my test that verifies that an object cannot be overwritten by default started to fail, presumably because I'd have to replicate the code in `StorageClientImpl.UploadHelper` and `Crc32c` (since they are private/internal).

 **Additional context**

I'm using version 4.8.0 of Google.Cloud.Storage.V1.

**Comment by jskeet** [comment]
We don't use `object.insert` ("single request upload") to upload data - we only ever use the resumable upload support, which I don't *think* has the ability to specify metadata.

I do feel your pain on this (and have similar issues for some personal projects) but I don't think we can support single request upload in any easy way at the moment (with the rest of the infrastructure for REST APIs). I'm hopeful that when we support the Storage v2 API (as a new client library; timeline is not set yet) we'll be able to address this at the same time.

**Comment by provegard** [comment]
I have zero experience with working directly with the Google APIs, but [this section](https://cloud.google.com/storage/docs/json_api/v1/objects/insert#request-body) of the `object.insert` documentation mentions that properties including `customTime` can be included when initiating a resumable upload.

> When performing a [multipart upload](https://cloud.google.com/storage/docs/uploading-objects) or when initiating a [resumable upload](https://cloud.google.com/storage/docs/resumable-uploads), both of which allow you to include object metadata as part of the request, supply the following properties.

Actually, looking at the code, `ResumableUpload<TRequest>.CreateInitializeRequest` uses `Body` as request content, and for `InsertMediaUpload` and its subclasses, that's `Object`. So it looks like just setting the custom time on `Object` prior to initiating the resumable upload session _should_ do the trick.

I can give it a try by copying the needed (internal/private) code and see what happens.

**Comment by jskeet** [comment]
Ah, well spotted. I'll try to have a look over the next few days - although as well as feasibility in terms of the HTTP requests we make, we'll also need to consider the API surface to expose. I don't expect we'll have a release including this *soon*, even if it's feasible.

**Comment by jskeet** [comment]
Ah, hang on - we already have a method of `UploadObject(Object, Stream, UploadObjectOptions, IProgress<...>)`. Does that not work already? Will write a quick test...

**Comment by jskeet** [comment]
Yes, it works - see #11761 for a sample which sets `customTime` in the initial upload.
Apologies for not remembering that overload before.

**Comment by provegard** [comment]
Huh, no idea how I managed to overlook that, so clearly my bad! 🤦 

It works great! Thank you!
