### ISSUE TITLE
Logs from cloud run job shows up as gce in logs

### ISSUE THREAD

**Issue by HannesRydberg** [googleapis/google-cloud-dotnet#11792]
#### Environment details

  - OS: Linux (Cloud Run Job)
  - .NET version: 6
  - Package name and version: Google.Cloud.Diagnostics.AspNetCore3

#### Steps to reproduce

  1. Create a .net console app that logs something with an ILogger
  2. Register the Google Diagnostics logging provider as such: `builder.Services.AddGoogleDiagnosticsForAspNetCore(loggingOptions: LoggingOptions.Create());`
  3. Deploy this app to a Cloud Run Job and run it.
  4. Look at logs in the Logs Explorer (and the absence of logs in the job itself)

We have a .net 6 application that was previously run as a GCP Cloud Run Service as an API. We've now converted much of it to run as a console app in a GCP Cloud Run Job. However, the logs does not show up as part of the Cloud Run Job, but rather as the underlying GCE instance. When ran as a service everything was shown under the Service logs.

We are using `Google.Cloud.Diagnostics.AspNetCore3` for the logs, and the logging provider is added with `builder.Services.AddGoogleDiagnosticsForAspNetCore(loggingOptions: LoggingOptions.Create());` in both projects. Is there any additional configuration required to get the logs to show up as part of the Cloud Run Job?

Also, logging to console (by registering `builder.Logging.AddConsole()` ) works and it shows up as part of the Job logs, but there logs are not structured, and searchable in the same manner that we previously had when the application ran as a Cloud Run Service. We have also tried logging with `builder.Logging.AddGoogle();` from `Google.Cloud.Diagnostics.Common` but that seems to give the same results as the other logging provider with logs not being tagged as part of the Cloud Run Job.

**Comment by jskeet** [comment]
@amanda-tarafa can comment more on the `AddGoogleDiagnosticsForAspNetCore` behavior, but as an interim solution I'd suggest that instead of using the default console formatting with `builder.Logging.AddConsole()`, you can use the Google.Cloud.Logging.Console package as described here: https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Logging.Console/latest

- Add Google.Cloud.Logging.Console as a package
- Use `builder.Logging.AddGoogleCloudConsole()`

You should then get structured logs.

**Comment by HannesRydberg** [comment]
Thank you @jskeet !

Logging is working as intended with the Google.Cloud.Logging.Console package.
As you mentioned we did only use the diagnostics package for logging, so this package is more suited for our needs.
