### ISSUE TITLE
IFirestoreConverter<T> do not support type with generic arguments

### ISSUE THREAD

**Issue by Skinz3** [googleapis/google-cloud-dotnet#12007]
Hello,

Im trying to use IFirestoreConverter passing a type that has generic arguments 
 ```
public class CarConverter<T> : IFirestoreConverter<Car<T>> where T : Engine
    {
        public Car<T> FromFirestore(object value)
        {
            return new Car<T>(value.ToString());
        }

        public object ToFirestore(Car<T> car)
        {
            return car.ToString();
        }
    }
```
Unfortunaly at runtime, it dosent work because even if my Reference object at runtime respect the generic constrainct, the convert should match the exact type of Car<T> because of this line :  
https://github.com/googleapis/google-cloud-dotnet/blob/6d221407548492df4051a256f48beb3beff496e7/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Converters/CustomConverter.cs#L41

i think if this exception wasnt thrown, Activator.CreateInstance would still work.

Is this exception relevant ?

**Comment by jskeet** [comment]
Looking at this again, I'll definitely need a complete example showing how you're using this - I'd really be guessing otherwise.

**Comment by jskeet** [comment]
Please add more information, or I'll have to just close this issue (around the end of the week). That doesn't stop you from adding more information later, but we try to avoid having lots of issues open in a state where we can't actually do anything with them.

**Comment by jskeet** [comment]
Closing for the moment due to lack of information.
