### ISSUE TITLE
Can't set AddressLines in PostalAddress using Google.Maps.AddressValidation.V1

### ISSUE THREAD

**Issue by wadeamaral** [googleapis/google-cloud-dotnet#12030]
Here is a link to the example: https://developers.google.com/maps/documentation/address-validation/client_libraries

There is no public setter in AddressLines so I am unable to set the value to initiate a request.

**Comment by jskeet** [comment]
There's no setter, but the returned collection is mutable. See https://cloud.google.com/dotnet/docs/reference/help/protobuf for more details.

**Comment by wadeamaral** [comment]
I'm sorry, I feel terrible for opening this. I see you can just add values to the AddressLines. I was going to remove this but you were too fast in responding. Thank you for the help.

**Comment by jskeet** [comment]
No problem, glad it all worked out.
