### ISSUE TITLE
Add CacheHit flag from GetQueryResultsResponse to BigQueryResults class

### ISSUE THREAD

**Issue by rcaisse2722** [googleapis/google-cloud-dotnet#12081]
**Is your feature request related to a problem? Please describe.**
The raw BigQuery API response GetQueryResultsResponse returns a flag CacheHit that specifies whether the results were retrieved from query cache or not:

```cs
//
// Summary:
//     Response object of GetQueryResults.
public class GetQueryResultsResponse : IDirectResponseSchema
{
    //
    // Summary:
    //     Whether the query result was fetched from the query cache.
    [JsonProperty("cacheHit")]
    public virtual bool? CacheHit { get; set; }
```

 **Describe the solution you'd like**
BigQueryResults should expose the value of the API response via the following property:

google-cloud-dotnet\apis\Google.Cloud.BigQuery.V2\Google.Cloud.BigQuery.V2\BigQueryResults.cs

```cs
        /// <summary>
        /// Whether the query result was fetched from the query cache.
        /// </summary>
        public bool? CacheHit => _response.CacheHit;
```

 **Describe alternatives you've considered**
N/A

 **Additional context**
N/A

**Comment by rcaisse2722** [comment]
Nope, no need from my end for it to be nullable. Defaulting to false when its null seems correct.

**Comment by jskeet** [comment]
The PR for this has been merged, but we haven't done a release yet. I'll ping this issue again when there's a NuGet package with the feature.
