### ISSUE TITLE
Google.Analytics.Data.V1Beta - 2.0.0-beta05 - RunReportAsync - Paging issue

### ISSUE THREAD

**Issue by johnhydemtm365** [googleapis/google-cloud-dotnet#12159]
**Nuget Package**: Google.Analytics.Data.V1Beta
**Version**: 2.0.0-beta05
**Service**: BetaAnalyticsDataClientBuilder
**Method**: RunReportAsync
**Codebase**: C# Dotnet core 8

**Issue**:
Getting GA4 data, there seems to be an issue with Paging. It works for the first page, but when I set the offset and limit to get the next page it times out with the error below:

**Error:**
Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: The connection timed out from inactivity. (analyticsdata.googleapis.com:443) QuicException: The connection timed out from inactivity.", DebugException="System.Net.Http.HttpRequestException: The connection timed out from inactivity. (analyticsdata.googleapis.com:443)")

**Request:**

{"Property":"properties/309199895","Dimensions":[{"Name":"isoYearIsoWeek","DimensionExpression":null},{"Name":"country","DimensionExpression":null},{"Name":"city","DimensionExpression":null}],"Metrics":[{"Name":"sessions","Expression":"","Invisible":false},{"Name":"totalUsers","Expression":"","Invisible":false},{"Name":"newUsers","Expression":"","Invisible":false},{"Name":"screenPageViews","Expression":"","Invisible":false},{"Name":"userEngagementDuration","Expression":"","Invisible":false},{"Name":"bounceRate","Expression":"","Invisible":false}],"DateRanges":[{"StartDate":"2023-01-01","EndDate":"2023-12-31","Name":""}],"DimensionFilter":null,"MetricFilter":null,"Offset":250000,"Limit":250000,"MetricAggregations":[],"OrderBys":[],"CurrencyCode":"","CohortSpec":null,"KeepEmptyRows":false,"ReturnPropertyQuota":false}

I am new to the GA analystics, so please shout if you need any more information.....

**Comment by jskeet** [comment]
Please could you provide the code you're using?

It feels unlikely to me that this is a client library issue, which is all we can really help with in this repository. I'll have a look at your code when you've provided it, but I strongly *suspect* that you'll need to follow one of the support routes in the [Analytics API help page](https://developers.google.com/analytics/devguides/help). (The maintainers of this repository know about how the client libraries are built, but don't know have detailed knowledge of all the APIs represented by the libraries.)

**Comment by johnhydemtm365** [comment]
sure please see below:

` var client = new GA4.BetaAnalyticsDataClientBuilder();

 client.JsonCredentials = clientConfig.GoogleAuthKey;
 var service = client.Build();
 var pageSize = 250000;
 var pageNo = 1;
 var totalRows = 0;
 var moreData = false;
 var offset = 0;

 do
 {
         request.Limit = pageSize;
         request.Offset = offset;    
         try
         {
             // Make the request
             var response = await service.RunReportAsync(request);

             //handle response and write the data out
             var jsonData = JsonConvert.SerializeObject(response);

             totalRows = totalRows + response.Rows.Count;
             if (totalRows < response.RowCount)
             {
                 moreData = true;
                 pageNo++;
                 offset += pageSize;
             }
         }
         catch(Exception ex)
         {
              _logger.LogError(ex);
             throw;
         }

     }
 }
 while (moreData);`

**Comment by johnhydemtm365** [comment]
as I mentioned the first request works fine, its only when there are more than 250,000 records does it fail.

**Comment by jskeet** [comment]
Okay, thanks. Could I suggest you try with a smaller page size, e.g. 10,000 or 25,000? If you could log the progress after each request, it would be interesting to see how far it gets.

Also, do you know how long it takes before timing out? (The timing for each request would be useful.)

I do suspect this is something we won't be able to handle in the client libraries though... *unless* it's a matter of specifying a keepalive to keep the connection open while it's taking a long time. Keepalive is slightly fiddly due to the different gRPC implementations involved, but we can look at that if it becomes relevant.

**Comment by johnhydemtm365** [comment]
Hi, yes tried that. My original code had it at 1000, which it started failing at weirdly.  although now I think about it, it was working agsinst one client but then started failing on another client.
Exhuasted my call limit now... but will try again laters.

**Comment by amanda-tarafa** [comment]
@johnhydemtm365 any new information you can share? We may close the issue because of inactivity. Thanks!

**Comment by jskeet** [comment]
I'll close this for now due to a lack of information. We can always open it again if we get more info.

**Comment by johnhydemtm365** [comment]
Hi, I had been off. We figured out iot was a credentials issue something to do with async beta client, which is not in the current c# package but is in a python package, so we just recreate the service everytime we want to query the data

**Comment by jskeet** [comment]
It's unclear to me exactly what you mean by that (I'm not sure why you'd get Python involved at all - just use the C# auth client) but it sounds like it's not a problem any more.
