### ISSUE TITLE
Alternative to PullRequest.ReturnImmediately

### ISSUE THREAD

**Issue by ronlhayes** [googleapis/google-cloud-dotnet#12161]
I am not finding a way to programmatically test for any messages in a subscription queue. Calling a synchronous Pull using ReturnImmediately works but is deprecated. I can see how this would causes performance issues in a tight loop however this is a call once every minute with an Task.Delay() in between and a cancellation token. Trying to use a CancellationToken with the CallSettings requires all the other settings to be set which I don't want.

Suggestions?

**Comment by jskeet** [comment]
We'll need to ask the Pub/Sub API team about this, in terms of best practice. We'll ask internally and get back to you when we can.

**Comment by jskeet** [comment]
I'll address this part though (which I hadn't spotted yesterday):

> Trying to use a CancellationToken with the CallSettings requires all the other settings to be set which I don't want.

No, it doesn't. If you pass a CallSettings with a CancellationToken in as an argument to an RPC, that gets merged with all the other call settings. You don't need to work out what else would have been in effect.

So if you'd be happy with just calling `PullAsync` and passing in a request with a cancellation token, that's the way to go. (You don't even have to construct a `CallSettings` yourself - there's an overload allowing you to just pass in a `CancellationToken` directly.)

I'm still asking the Pub/Sub team about a good way of doing a point in time "are there any messages" check though, in case the above doesn't fit your use case.

**Comment by kamalaboulhosn** [comment]
Actually, making a Pull call with return immediately is not a way to programmatically check for messages. In fact, with return immediately set to true, it would be very likely that it would return an empty response even if there were messages in the backlog. As noted in [the documentation](https://cloud.google.com/pubsub/docs/pull#pull_api), "When using the unary Pull API, a response with zero messages or with an error does not necessarily indicate that there are no messages available to receive." There is currently no programmatic way to make a call whose response guarantees an answer to the question, "are there messages to be consumed?" 

The way that is most likely to provide an answer that is close is to create a subscriber in the client library and leave it open for ~30 seconds or so. If no messages come back, then it is likely that there are no messages to consume, but even in this situation, it is not guaranteed.

**Comment by jskeet** [comment]
I'll close this issue now, as I believe we've answered the question as well as we can. Do feel free to add a comment if anything is unclear though.
