### ISSUE TITLE
feat: Add TopicName and SubsciptionName resolution from container as an extension point.

### ISSUE THREAD

**Issue by maw136** [googleapis/google-cloud-dotnet#12213]
I've created a PR: https://github.com/googleapis/google-cloud-dotnet/pull/12212
that resolved the issue of not being able to resolve TopicName/SubscriptionName from IoC container.
One such use-case for this new feature is:
Imagine a registration of IOptions<T> where T is the configuration for said pub/sub, there are validation options enabled at startup and maybe other dependencies for the configuration.
Current resolution requires one to create additional IServiceProvider instance inside Action<TBuilder>, alas there is perfectly good instance accessible inside virtual base.Configuration method of either Builder classes.

**Comment by amanda-tarafa** [comment]
I believe the best approach is to add overloads in [ServiceCollectionExtensions](https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/ServiceCollectionExtensions.cs) as follows:

`public static IServiceCollection AddSubscriberClient(this IServiceCollection services, Action<IServiceProvider, SubscriberClientBuilder> action)`

`public static IServiceCollection AddPublisherClient(this IServiceCollection services, Action<IServiceProvider,PublisherClientBuilder> action)`

This will allow you to resolve from DI not just the topic name but any other aspect, without us needing to add new "resolver" properties for each aspect in the builder that anyone wants to resolve from DI. Let me know if I'm missing something and this does not fully resolve your use case. Also @jskeet for thoughts.

**Comment by maw136** [comment]
Yes yours is more general solution and the better approach. 
I considered it and opted for the one in PR because of less intrusiveness, and possible breaking changes.
I am fully on board for either approach.

**Comment by amanda-tarafa** [comment]
I don't think there'd be breaking changes with my proposal, we'd be adding a couple of overloads? Can you clarify that? Also, what do you mean with intrusiveness? Again, I'm not certain if I'm missing something here.

I do strongly prefer my approach over yours, so if there's nothing else, I think we should go with that.

**Comment by maw136** [comment]
Just being pragmatic. I had to adjust existing unit tests to handle your approach. This is the only thing that got me thinking.
I prefer your approach myself too TBH.
Here is the implementation: https://github.com/googleapis/google-cloud-dotnet/pull/12215

**Comment by amanda-tarafa** [comment]
Perfect! I'll review as soon as I can, it'll be today or tomorrow. And also @jskeet should take a look before we merge.
Thanks a lot for this.

**Comment by amanda-tarafa** [comment]
Closed via #12215
