### ISSUE TITLE
Vertex AI Gemini APIs coming?

### ISSUE THREAD

**Issue by lukepuplett** [googleapis/google-cloud-dotnet#12226]
Hello! Just a quick question:

_Are you lovely folks working on .NET libraries for calling the Gemini LLM APIs (via Vertex, presumably)??_

The samples are REST and Python and I can't figure out how to get an API key to include as the Bearer. I can use other LLMs in the meantime. I've noticed each LLM is good at certain work, like people!

Thank you!

**Comment by jskeet** [comment]
I'm afraid I can't talk about anything upcoming, but I *can* say that we're aware of a desire for .NET libraries.

Until then, in terms of an API key, you can specify it either as a header (`x-goog-api-key`) or as a query parameter (`key`).

**Comment by lukepuplett** [comment]
Thank you. Between AI and SO I think I have found how to grab the OAuth token I need to stick in my HTTP request.

https://stackoverflow.com/questions/51156370/how-to-get-oauth-accesstoken-google-for-posting-a-job-to-google-hire-in-c
