### ISSUE TITLE
storage: Support Storage Control Quickstart

### ISSUE THREAD

**Issue by sydney-munro** [googleapis/google-cloud-dotnet#12514]
1. Please update Library Install Section to include install instructions for storage control, if applicable.
2. Please create sample with region tag storage_control_quickstart_sample that shows an example of initializing a storage control client and performing an call.
3. Please include me on reviews for tracking.

See [internal doc](http://goto.google.com/storage-control-quickstart) for further information.

**Comment by amanda-tarafa** [comment]
We'll track this internally.
