### ISSUE TITLE
Library for ComputeEngine metadata

### ISSUE THREAD

**Issue by glb-cblin** [googleapis/google-cloud-dotnet#12539]
Is there a lib that allows to query the metadata endpoints available on cloud run (or from any compute engine resource) ?

In java, this is described at https://cloud.google.com/appengine/docs/legacy/standard/java/accessing-instance-metadata#identifying_which_metadata_endpoint_to_use (but it seems there is no library)

To be more precise, my question would be : how to obtain the email of the current service account (http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email)

My other option would be to do it with the auth lib, but here also I cannot find the correct way (i.e `GoogleCredential.GetApplicationDefault().?????`)

**Comment by jskeet** [comment]
We *used* to have a Metadata library that was very much in alpha, but we removed it as we didn't want to commit to anything just for .NET.

If you're happy to assume you're on Compute, I *believe* you can use:

```csharp
var address = await new ComputeCredential().GetDefaultServiceAccountEmailAsync();
```

@amanda-tarafa may wish to provide more information on whether that's reasonable or not though.

**Comment by glb-cblin** [comment]
That is working fine under Cloud run, thank you very much for the very fast answer !

**Comment by amanda-tarafa** [comment]
> We _used_ to have a Metadata library that was very much in alpha, but we removed it as we didn't want to commit to anything just for .NET.
> 
> If you're happy to assume you're on Compute, I _believe_ you can use:
> 
> ```cs
> var address = await new ComputeCredential().GetDefaultServiceAccountEmailAsync();
> ```
> 
> @amanda-tarafa may wish to provide more information on whether that's reasonable or not though.

Just confirming this is right.
