### ISSUE TITLE
Support multiple SubscriberClient and PublisherClient instances in ServiceCollection by the notion of Keyed service

### ISSUE THREAD

**Issue by maw136** [googleapis/google-cloud-dotnet#12560]
Current `ServiceCollection` Extensions that assist with registering `SubscriberClinet` and `PublisherClient` does not support `Keyed` service registration that was introduced with `.NET 8.0`.
Having multiple singletons registered the consumer must iterate (taking a dependency of `IEnumerable<SubscriberClient>`/`IEnumerable<PublisherClient>`) through existing instances looking for the one that has the desired `SubscriptionName`/`TopicName`.
This is somewhat cumbersome and can be avoided using the newer registration mechanizm.

I propose multitargeting PubSub client to `.NET 8.0` and adding conditional compilation to add support for Keyed service registration in the `ServiceCollectionExtensions` class.

I can prepare this change if the community agrees in the value of said change.

**Comment by maw136** [comment]
Here are some good examples:
https://andrewlock.net/exploring-the-dotnet-8-preview-keyed-services-dependency-injection-support/

**Comment by jskeet** [comment]
Thanks, we'll have a look.

**Comment by jskeet** [comment]
Note that we *can't* do this just yet, as we're not building with the .NET 8 SDK yet, for internal CI reasons. We're hoping to resolve those, but it does mean this definitely won't happen *very* soon.

**Comment by maw136** [comment]
Sorry to hear that .NET 8 SDK cannot be used. The point is moot, so to speak, for now.

**Comment by amanda-tarafa** [comment]
We are tracking this internally. As per [#12561 (comment)](https://github.com/googleapis/google-cloud-dotnet/pull/12561#discussion_r1559830964) before we are able to do this, we need to:

- Be able to build in .NET 8, which we can't at the moment for internal reasons.
- Decide wether we want libraries to explicitly target .NET 8.

For now, I'm closing the feature request as we cannot support it. Once we remove blockers and made a decision on targetting .NET 8, we may reopen, but that will all be later in the year. Sorry this might no be want you want to hear.
