### ISSUE TITLE
Google.Cloud.Firestore can view any collection or document regardless of security rules

### ISSUE THREAD

**Issue by kur4mot0** [googleapis/google-cloud-dotnet#12623]
#### Environment details

  - OS: MAC OS Sonoma 14.4.1
  - .NET version: 8.0
  - Package name and version: Google.Cloud.Firestore - 3.6.0

#### Steps to reproduce

  1. Project on Firebase created, Firestore Database Created (On Test Mode).
  2. Used the Google.Cloud.Firestore to CRUD the data on it. and using the google.json credentials.
  3. I can't find the right way to use Firebase Authentication and Firestore together.
  4. In the approach of using the json credentials, the user has all the access to the Firestore. The rules don't apply to it.

Thanks!

**Comment by jskeet** [comment]
What do you mean by "the JSON credentials"? How were these credentials created?

Fundamentally, Google.Cloud.Firestore is not intended for *end users* (who would have Firebase credentials). It's intended to be used server-side, with credentials that authenticate that they're associated with your GCP project, not with a specific end-user.

**Comment by jskeet** [comment]
From the [documentation](https://firebase.google.com/docs/firestore/client/libraries):

> Unlike the Mobile and Web SDKs, the server client libraries create a privileged Firebase environment with full access to your database. In this environment, requests are not evaluated against your Firebase security rules. Privileged Firebase servers are secured using Identity and Access Management (IAM), see [Security for server client libraries](https://firebase.google.com/docs/firestore/security/iam).

So basically everything is working as documented...

**Comment by jskeet** [comment]
Right, so it's a service account credential. That is *absolutely not* intended for use by end users.

In terms of *end user* libraries, that's not something we support in this repository at all. For .NET users, there's a Unity SDK, but other than that I'd look at using the REST API. If you think there should be other .NET libraries available, I suggest you file a feature request at https://firebase.google.com/support/troubleshooter/report - but fundamentally the Google.Cloud.Firestore library is working as expected and as documented.

I'll close this issue now, as I don't expect any changes to occur in this repository.
