### ISSUE TITLE
Load large data using your API

### ISSUE THREAD

**Issue by francescomandruvs** [googleapis/google-cloud-dotnet#12652]
I'm trying to upload a large dataset into BigQuery. I have a dataset with more than 1M rows and 200 columns (1.2 GB). My current implementation basically splits this DataFrame into smaller batches, then I upload every batch inside a temporary Bucket and then I upload the .parquet files in the GCS bucket into the BigQuery table. Altough this approach works, it's very slow. I wonder if there is a smarter method to do this. Another idea that I have in mind is to save temporary the data in .parquet on my local machine into a tmp directory (which is pretty fast), and then use your client to upload the parquet into BigQuery. This is the function that I use:

```c#
public async Task UploadParquetToBigQueryAsync<T>(IEnumerable<T> records, string inputFilePath, 
        string datasetId, string tableId) where T : IWriteRecord
    {
        try
        {
            var parquetService = new ParquetService();
            await parquetService.WriteRecordsToParquetAsync(records, inputFilePath);

            using Stream inputStream = File.OpenRead(inputFilePath);
            var job = _client.UploadParquet(datasetId, tableId, inputStream);
            job.PollUntilCompleted().ThrowOnAnyError();
        }
        catch (IOException ex)
        {
            Console.WriteLine($"File operation failed: {ex.Message}");
            throw;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An unexpected error occurred: {ex.Message}");
            throw;
        }
```

However, when I try this method, I get this error:

> An unexpected error occurred: The service bigquery has thrown an exception. No HttpStatusCode was specified. Job xxxxx/xxxx/job_xxxx contained 2 error(s). First error message: Resources exceeded during query execution: The query could not be executed in the allotted memory. Peak usage: 105% of limit.
> Top memory consumer(s):
>   input table/file scan: 100%

Which is the correct approach? I don't find any documentation about this. Thank you! I found that the Python implementation seems tto do the second approach.

**Comment by jskeet** [comment]
Yes, splitting the data locally and using `UploadParquet` on each "chunk" sounds like it's probably the best approach.
I'm afraid the maintainers of this repository aren't in a position to give any more information about this specific (server-side) error - we maintain the client libraries, but we don't have specific expertise of all of the APIs. If you want someone with more BigQuery expertise to validate your idea, I'd suggest following one of the routes on the [BigQuery support page](https://cloud.google.com/bigquery/docs/getting-support). Sorry not to be more helpful - it's just not our area of expertise.

I'll close this issue now as I don't *think* we can help you further, but I do wish you luck in your endeavors.
