### ISSUE TITLE
build: Failed releases.

### ISSUE THREAD

**Issue by amanda-tarafa** [googleapis/google-cloud-dotnet#13015]
The following releases failed because of the docfx update.

* #13008
* #13009
* #13011
* #13007
* #13010

Because we had to downgrade docfx, these release PRs will never work, they continue to use the bad docfx version.
Alternatives that I can think of:

1. Delete the GitHub tags for these and rerun the whole release process again. New PRs will be created from main which will use the good docfx version, etc. Releases will happen with the same version they were intended to happen in the first place.
 
2. Run the whole release process again, bumping the minor version of the previously intended versions with a nore on version history clarifying that the intended version never got released because of release pipeline issues.

I prefer 1. @jskeet thoughts? Another alternative?

**Comment by jskeet** [comment]
Committish_override would probably work.

**Comment by amanda-tarafa** [comment]
> Committish_override would probably work.

Trying that...

**Comment by amanda-tarafa** [comment]
That failed, I'm trying something else now.

If it doesn't work, I'll go with option 1. But, I'll delete the tags today and remove the autorelease labels from the PRs. And early next week we can re-add the `autorelease:pending` label. I'll wait till next week for that in case there are pipeline failures. @jskeet let me know if you have objections to this.

**Comment by amanda-tarafa** [comment]
It failed again, I can't make it pick up the downgraded docfx version while using the earlier release PR/tag.

I won't do anything just yet, but I think we are stuck with options 1 or 2 from above.

**Comment by amanda-tarafa** [comment]
I'll try something else...

**Comment by amanda-tarafa** [comment]
OK, got it, doing the rest now.

**Comment by amanda-tarafa** [comment]
These were all released now.
