### ISSUE TITLE
Google.Cloud.Firestore.V1 is using grpc against the emulator but not when running in GKE

### ISSUE THREAD

**Issue by chrsin** [googleapis/google-cloud-dotnet#13033]
We have an application that is using firestore to store some data. When we run the application locally against the emulator we can see it is using GRPC to make calls to firestore. This gives pretty damn good performance with sub 1ms  to write a document and read it out. Pretty impressive!

But as far as we can tell our application is using the Rest API (Post http requests to for an example: "https://firestore.googleapis.com/google.firestore.v1.Firestore/Commit" when running our application on GKE.
At first this meant requests that were around 75ms. At that point we were using come credentials json to configure authentication of the client library. My suspicion was that this was inefficient because of the credentials so I looked into configuring using default application credentials. So we got our application setup using Workload Identity and configured the client library using default application credentials. This dropped our requests to around 50ms. But it still looks like it is using the http rest API. :(

How do I configure the client library to use GRPC against firestore to increase performance?

Our application is temporarily configured to run against 2 instances of firestore (one in the US and one in EU)
That means we are creating 2 FirestoreDb as singletons. 
They are configured like so:
```
var builder = new FirestoreDbBuilder();
builder.ProjectId = instance.ProjectId;
builder.Build();
```

#### Environment details

  - OS: Linux
  - .NET version: dotnet 8.0
  - Package name and version: Google.Cloud.Firestore.V1 - 3.6.0

#### Steps to reproduce

1. Run an application with open telemetry and observe your application make calls to:
https://firestore.googleapis.com/google.firestore.v1.Firestore/Commit.

**Comment by jskeet** [comment]
> But as far as we can tell our application is using the Rest API (Post http requests to for an example: "https://firestore.googleapis.com/google.firestore.v1.Firestore/Commit" when running our application on GKE.

How have you determined that? That shouldn't be the case unless you specifically set the `GrpcAdapter` property to `RestGrpcAdapter`.

I would be very *very* surprised to find that the client library is using REST without you explicitly specifying that somewhere. I can't currently imagine any path that would do that.

(I wouldn't expect the credentials to have any significant effect beyond the first request, other than very occasionally refreshing the access token - I'd expect about once per hour.)

**Comment by chrsin** [comment]
We have open telemetry setup to make spans for http requests and I can see that everytime we write to firestore a request is logged to: https://firestore.googleapis.com/google.firestore.v1.Firestore/Commit and it takes around 50ms.

Configuration of our Singleton FirestoreDb instance is literally just:
```
var builder = new FirestoreDbBuilder();
builder.ProjectId = <projectId>
var firestoreDb = builder.Build();
```

I would assume I would have to mess around with the GrpcAdapter or GrpcChannelOptions in order to mess this up? :)

An example of code that results in the commit http request:
```
var documentRef = firestoreDb.Document(documentPath);
var values =
                new Dictionary<string, object>()
                {
                    { FirestoreConnectorFields.STATUS, status.ToString("G") }
                };
await documentRef.SetAsync(values, SetOptions.MergeAll, cancellationToken);
```

**Comment by jskeet** [comment]
> I can see that everytime we write to firestore a request is logged to: https://firestore.googleapis.com/google.firestore.v1.Firestore/Commit and it takes around 50ms.

That's a gRPC request. If it were an HTTP/1.1 request, it would be to `https://firestore.googleapis.com/v1/projects/abc/databases/xyz/documents:commit`.

Bear in mind that gRPC is still using HTTP - and Grpc.Net.Client uses `HttpClient`, so I'm not surprised you're seeing HTTP requests.

So I believe the gRPC aspect is entirely a red herring here.

I don't know whether 50ms for a commit is typical or not I'm afraid. What latency do you see for reads? Is your GKE cluster in the same region as your Firestore database? You say your application is temporarily configured to run against 2 instances of firestore (one in the US and one in EU) - where is your GKE cluster?

For testing purposes, I'd personally take GKE out of the mix and just use Cloud Functions to test the performance. I'm happy to write a small function to test the commit and read performance if that would help - but as I say, I don't really know what a "normal" latency would look like.

**Comment by chrsin** [comment]
> That's a gRPC request. If it were an HTTP/1.1 request, it would be to https://firestore.googleapis.com/v1/projects/abc/databases/xyz/documents:commit.

Awesome! That clears a lot of the confusion for me. I'll try getting my benchmark application running in GKE and see what results I'm getting there. I'll also check the regions and see if there is anything to gain there.

Thanks a bundle for the clarification and so sorry for the inconvenience! :heart:

**Comment by jskeet** [comment]
I'll close this issue now as I doubt that there's anything in the client libraries that needs changing, but do feel free to add more comments.

**Comment by chrsin** [comment]
Yeah you can close this one.
I'm posting my findings here in case they give value to anyone else out there. :)

Our firestore instance is hosted in europe-west3 and our cluster is hosted in europe-west3
I executed my benchmark application in our cluster (in a docker container) with Worload identity and got the following results:
| Method                | Mean     | Error    | StdDev   |
|---------------------- |---------:|---------:|---------:|
| FirestoreWriteAndRead | 20.57 ms | 0.405 ms | 0.580 ms |

When running the benchmark locally against the emulator running on my machine I get:
| Method                | Mean     | Error    | StdDev   |
|---------------------- |---------:|---------:|---------:|
| FirestoreWriteAndRead | 573.3 us | 31.09 us | 91.17 us |

I've had a look at a lot more of the calls from our application and it looks like they are around 20-40ms. So it looks like they are around the same as the benchmark application.
