### ISSUE TITLE
Types declared outside the assembly will not deserialize unless decorated with attributes

### ISSUE THREAD

**Issue by FaridCTarin** [googleapis/google-cloud-dotnet#13060]
#### Environment details

  - OS: Mac
  - .NET version: 8.0
  - Package name and version:

#### Steps to reproduce

If a type is declared outside the assembly where the SDK is and the type is not decorated with `[FirestoreData]`, I get the following exception:

Unable to create converter for type...

However, if I move it into the assembly then all works fine and the data is deserialized for the class and all its properties.

Is that a limitation on purpose?

Thanks!

**Comment by jskeet** [comment]
Just moving the type shouldn't have any effect. Applying the attribute would.

Please provide a concrete example of what does and doesn't work for you, and I'll look on Monday.

**Comment by FaridCTarin** [comment]
1. Create an ASP.NET API project, it may replicate for a library too but I have an API project.
2. Create a wrapper around `FirestoreDb`.
3. Create a console app and reference the project in step 1.
4. Create a class like this in the console application: `public class User { public string Email { get; set; } }`
5. Access the user like: `var biz = await db.Get<User>("users", "IdOfUser");`

You will get an exception.

Now move the type into the API project and it will work--even without attributes.

**Comment by jskeet** [comment]
Sorry, there's too much to interpret there. Please provide the example in code to reproduce this - otherwise it's almost certain that I'll do something different to you and get a different result.

**Comment by jskeet** [comment]
In general however, if you can't apply attributes to the type you want to serialize, you should use the converter registry:

https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Firestore/latest/datamodel#converter-registries

**Comment by FaridCTarin** [comment]
Your comment about custom converter helped point me in the correct direction. Within the API we have a custom converter and that converter looks fro types in `Assembly.GetExecutingAssembly()`. That explains why things work differently within the assembly.

Thanks for your help! I appreciate it and sorry for taking your time.
