### ISSUE TITLE
Add the ability of composing objects inside the google cloud storage

### ISSUE THREAD

**Issue by francescomandruvs** [googleapis/google-cloud-dotnet#13181]
Currently your API supports the wildcards in order to split large files from big query into smaller ones into GCS. However, your csharp API does not give the ability to compose the objects directly inside the GCS bucket, as for example in [Java](https://cloud.google.com/java/docs/reference/google-cloud-storage/latest/com.google.storage.v2.StorageClient#com_google_storage_v2_StorageClient_composeObject_com_google_storage_v2_ComposeObjectRequest_), at least from my understanding.

**Comment by amanda-tarafa** [comment]
We don't expose the `Compose` operation on the higher level `Google.Cloud.Storage.V1.StorageClient` type.

But you can use the `Google.Cloud.Storage.V1.StorageClient.Service` property to access the lower level service client which does expose the `Compose` operation. Roughly, your code should look like:

```
StorageClient storageClient = ...;
var composeRequest = storageClient.Service.Objects.Compose(...);
var composedObject = await composeRequest.ExecuteAsync();
```

Note this means we are not retrying by default, etc. so you will have to handle that on your own.

I'll let @JesseLovelace talk about whether Compose should be surfaced on the higher level client or not and a possible ETA.

**Comment by francescomandruvs** [comment]
Thanks @amanda-tarafa for your answer! I have built a method which uses your piece of code, however I'm facing a new challenge now and I don't find any documentation about it. Basically I'm extracting data from big query into smaller objects using as a destination source file type `parquet`, however when the object is composed, it seems to be corrupted, for example reading the composed parquet from python I get:

`OSError: Unexpected end of stream: Page was smaller (1125) than expected (2228)`

. Is there any specific format that I'm forced to use when I compose objects?

**Comment by amanda-tarafa** [comment]
I'm not familiar with the specifics of the Storage Compose operation, (we maintain client libraries for hundreds of APIs so we are not familiar with specifics for most). @JesseLovelace can help here.

From just reading at the [Compose operation documentation](https://cloud.google.com/storage/docs/composite-objects) though I don't thing what you are attempting to do is a supported use case. Compose will simply "concatenate" the content of each smaller object into a bigger one. Formats like parquet which usually define a header, footer, etc. sections cannot be simply concatenated expecting the format to be maintained. Maybe try with a headerless CSV for instance? Again, these are my conclusions from reading at the docs, but I may well be mistaken.

**Comment by francescomandruvs** [comment]
I managed to merge every single parquet file locally. It should be the best available solution

**Comment by amanda-tarafa** [comment]
> I managed to merge every single parquet file locally. It should be the best available solution

How? Did you concatenated the whole content of each file together and obtained a new parquet formatted file? If that's the case I agree it should work with the Storage Compose operation.

But if you used a tool that understandas parquet, or similar, it's likely that tool unpacked each of the individual parquet files, extracted the data content and packed it back again in a parquet format. Compose _could_ do that, maybe, if it understood parquet and all other possible formats, but from [documentation](https://cloud.google.com/storage/docs/composite-objects)  it looks like it doesn't, it just concatenates objects together without understanding anything about those objects:

> This page describes composite objects, which you create from existing objects without transferring additional object data. Composite objects are useful for making [appends to an existing object](https://cloud.google.com/storage/docs/composite-objects#appends), as well as for recreating objects that you [uploaded as multiple components in parallel](https://cloud.google.com/storage/docs/parallel-composite-uploads).

Regardless, this is now a request for the API team, nothing we can do client library side. You can file a feature request for the API team on their [public issue tracker](https://issuetracker.google.com/issues?q=status:open%20componentid:187243&s=created_time:desc).

**Comment by francescomandruvs** [comment]
I'm basically reading each single parquet file generated using a wildcard (`parquet0001`, `parquet0002` etc.. etc..) inside my csharp application, where I have a parquet service reader which extracts every single raw from the parquet file, I'm appending these extracted rows into a list and then I sort my list. This was exactly what I was doing with a single parquet before. 
I was trying to compose the parquet files before my parquet service but as you highlighted, the compose operator does not understand parquet files. Indeed, your compose operator is just able to compose txt files as far as I understand, which does not make it very useful in my opinion. But maybe I misunderstood it's functionality.

**Comment by jskeet** [comment]
> Indeed, your compose operator is just able to compose txt files as far as I understand

It's not a matter of being able to compose text files - it's a matter of composing a single file from the concatenation of all the contents of multiple files. There are plenty of reasons to do that which may have nothing to do with text files - for example, you might want to upload a single large file *regardless* of its format, and choose to do so in multiple chunks and then compose them together afterwards (as opposed to using a resumable upload).

There are plenty of file formats where composing multiple individually-valid files doesn't work - you can't just concatenate multiple XML documents together and get a new valid XML document, for example, because it would have multiple root elements (and potentially multiple XML declarations). That doesn't mean that the compose operation is "not very useful" - it's just not appropriate *for that specific task*.

**Comment by francescomandruvs** [comment]
> There are plenty of reasons to do that which may have nothing to do with text files
Thank you for you answer. My limited knowledge made me think that there are not plenty of cases where the compose operator works without any "specific file type processing". by the way I agree with the fact that there are also plenty of cases to manage if the compose operator have to deal with all the file types. Thank you.

**Comment by jskeet** [comment]
Okay, I think we've reached agreement here - I'm going to close this issue as I don't think there's anything more to be done at the library level. Feel free to comment again if you disagree, including what you'd expect the next step to be.
