### ISSUE TITLE
Google.Cloud.Logging.NLog enable parameter

### ISSUE THREAD

**Issue by neotrow** [googleapis/google-cloud-dotnet#13196]
**Is your feature request related to a problem? Please describe.**
We use `appsettings.{environment}.json` to configure NLog. In the root `appsettings.json` we have a configured the `GoogleStackdriver` target. In the `appsettings.{environment}.json` we have configured the rules for NLog to write the logs to the correct places. In `appsettings.Development.json` we don't want to write to gcp stackdriver. But our code now throws an exception because there were no credentials configured during the initialisation phase. 

 **Describe the solution you'd like**
We would appreciate an `enable` parameter that would skip the whole initialzion and maybe throw an exception if you try to write to gcp stack driver if this is set to false. Or alternativley have a `skipCredentials` parameter.

 **Describe alternatives you've considered**
Our alternative is to move the gcp stack driver target to the `appsettings.{environment}.json` instead of the root `appsettings.json` but this means we have it duplicated.

**Comment by amanda-tarafa** [comment]
NLog supports referencing configuration defined elsewhere, i.e. not as part of NLog configuration itself. See https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer#configuration-syntax.

I think with this you can still configure the GoogleStackdriver target on `appsettings.json`, but as a standalone object, not as part of NLog configuration. Then on each of the `appsettings.{environment}.json` that you want to use GoogleStackdriver you configure NLog targets referencing the object defined in `appsettings.json`.

**Comment by amanda-tarafa** [comment]
@neotrow were you able to try my approach from the previous comment?

**Comment by amanda-tarafa** [comment]
@neotrow I'm closing this one as I believe I've provided an alternative approach to your request. If you don't believe so, please feel free to leave a comment explaning why and we'll reconsider. Thanks.
