### ISSUE TITLE
VertexAISearch throwing 'Request contains an invalid argument'

### ISSUE THREAD

**Issue by Martin-Molinero** [googleapis/google-cloud-dotnet#13275]
#### Environment details

  - OS: Windows10
  - .NET version: net6.0
  - Package name and version: Google.Cloud.AIPlatform.V1" Version="3.4.0

#### Steps to reproduce

```csharp
    public string Error(string query)
    {
        string publisher = "google";
        string model = "gemini-1.5-pro-001";
        var generateContentRequest = new GenerateContentRequest
        {
            Model = $"projects/{_googleProject}/locations/{_googleLocation}/publishers/{publisher}/models/{model}",
            Tools =
            {
                new Tool
                {   
                    Retrieval = new Retrieval
                    {
                        VertexAiSearch = new VertexAISearch
                        {
                            Datastore = $"projects/{_googleProject}/locations/{_dataStoreLocation}/collections/default_collection/dataStores/{_dataStoreId}",
                        }
                    },
                }
            },
            Contents =
            {
                new Content
                {
                    Role = "USER",
                    Parts =
                    {
                        new Part
                        {
                            Text = query,
                        },
                    }
                }
            },
        };

        return new PredictionServiceClientBuilder
        {
            Endpoint = $"{_googleLocation}-aiplatform.googleapis.com",
        }.Build().GenerateContent(generateContentRequest).Candidates[0].Content.Parts[0].Text;
    }
```
Throws:

`{"Status(StatusCode=\"InvalidArgument\", Detail=\"Request contains an invalid argument.\")"}`

- Commenting out `VertexAISearch` tool makes it work
- Tested with `GoogleSearchRetrieval` and that works

Not sure what/how to test/debug this, specified a logger but the only thing I see is `Starting asynchronous API call to GenerateContent.` and boom, no other information
Any tips on what the issue can be or how to add more logs/debug information? 🙏

**Comment by Martin-Molinero** [comment]
Also tested creating data stores in multiple locations or even creating a search app but don't think that's required?

**Comment by jskeet** [comment]
Thanks for raising this issue. Unfortunately this sounds like it's really a question about the AI Platform API itself rather than about the .NET client library. The maintainers of this repository aren't experts in all the different Google APIs that are available - only how the .NET client libraries can be used to make requests to those APIs. (We can help customers who know what their API call should look like but are having trouble with how to make that request using C#, but not with figuring out the request to start with.) I've assigned this issue to another engineer who *may* be able to help you, but otherwise the language-neutral [AI Platform support routes](https://cloud.google.com/vertex-ai/docs/support/getting-support) are probably your best bet.

One thing you *could* do to see if there's more information is to check the exception for more status details:

```csharp
catch (RpcException ex)
{
    foreach (var detail in ex.GetRpcStatus()?.UnpackDetailMessages() ?? Enumerable.Empty<IMessage>())
    {
        // Or whatever logging you have
        Console.WriteLine($"{detail.Descriptor.Name}: {detail}");
    }
}
```

**Comment by meteatamel** [comment]
Hi @Martin-Molinero, we have a VertexAiSearch sample here: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/main/aiplatform/api/AIPlatform.Samples/GroundingVertexAiSearchSample.cs

I just tested with with a datastore and it worked fine for me.

Could you please give it a try and let us know?

**Comment by Martin-Molinero** [comment]
Hi!
Thank you for the help, looking at the exception was able to find more information about the error, not sure how to solve it yet

> Status(StatusCode="InvalidArgument", Detail="`max_extractive_answer_count` must be not specified when the datastore is using 'chunking config'")

**Comment by meteatamel** [comment]
Maybe it's how you crate the datastore? This is how I create it: https://github.com/meteatamel/genai-beyond-basics/tree/main/samples/grounding/vertexai-search

**Comment by Martin-Molinero** [comment]
Hey @meteatamel! Thank you
Yes I was enabling chunk documents when creating the data store, which seemed nice to have, that was causing the issue I had. Not sure how to change `max_extractive_answer_count` on request, seems internal configuration, any ideas?
Closing the issue!

**Comment by meteatamel** [comment]
I'm not sure how to change `max_extractive_answer_count` but glad you got it working now
