### ISSUE TITLE
Add support for feature vector data insertion

### ISSUE THREAD

**Issue by abbottdev** [googleapis/google-cloud-dotnet#13278]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 I would like to be able to add/edit/query vector data using the `Google.Cloud.Firestore` library. I'm unable to upload anything using the dotnet client libraries- only support for NodeJS/Python exists: https://firebase.google.com/docs/firestore/vector-search?_gl=1*1riqzj8*_up*MQ..*_ga*NjkxMjIwMjkwLjE3MjEwNTg2MTM.*_ga_CW55HF8NVT*MTcyMTA1ODYxMy4xLjAuMTcyMTA1ODYxMy4wLjAuMA..#node.js
 

 **Describe the solution you'd like**
 - Add the relevant `FieldValue.vector([1.0 , 2.0, 3.0])` types.
 - Add `kNN`/embedding search support to `Google.Cloud.Firestore`. (Currently only exists in `Google.Cloud.Firestore.v1`)

**Comment by jskeet** [comment]
This feature is only in public preview at the moment; we don't currently provide support for preview features in our Firestore library.

**Comment by jskeet** [comment]
I'll close this issue now as we don't intend to make changes for it; when the feature comes out of preview we will look at the degree of support we can provide. (This is largely driven by prioritization by the Firestore team.)
