### ISSUE TITLE
Pub/Sub sample codes doesn't work on local Windows Environment

### ISSUE THREAD

**Issue by Rr7716** [googleapis/google-cloud-dotnet#13427]
```c#
// First create a topic.
PublisherServiceApiClient publisherService = await PublisherServiceApiClient.CreateAsync();
TopicName topicName = new TopicName(projectId, topicId);
publisherService.CreateTopic(topicName);

// Subscribe to the topic.
SubscriberServiceApiClient subscriberService = await SubscriberServiceApiClient.CreateAsync();
SubscriptionName subscriptionName = new SubscriptionName(projectId, subscriptionId);
subscriberService.CreateSubscription(subscriptionName, topicName, pushConfig: null, ackDeadlineSeconds: 60);

// Publish a message to the topic using PublisherClient.
PublisherClient publisher = await PublisherClient.CreateAsync(topicName);
// PublishAsync() has various overloads. Here we're using the string overload.
string messageId = await publisher.PublishAsync("Hello, Pubsub");
// PublisherClient instance should be shutdown after use.
// The TimeSpan specifies for how long to attempt to publish locally queued messages.
await publisher.ShutdownAsync(TimeSpan.FromSeconds(15));

// Pull messages from the subscription using SubscriberClient.
SubscriberClient subscriber = await SubscriberClient.CreateAsync(subscriptionName);
List<PubsubMessage> receivedMessages = new List<PubsubMessage>();
// Start the subscriber listening for messages.
await subscriber.StartAsync((msg, cancellationToken) =>
{
    receivedMessages.Add(msg);
    Console.WriteLine($"Received message {msg.MessageId} published at {msg.PublishTime.ToDateTime()}");
    Console.WriteLine($"Text: '{msg.Data.ToStringUtf8()}'");
    // Stop this subscriber after one message is received.
    // This is non-blocking, and the returned Task may be awaited.
    subscriber.StopAsync(TimeSpan.FromSeconds(15));
    // Return Reply.Ack to indicate this message has been handled.
    return Task.FromResult(SubscriberClient.Reply.Ack);
});

// Tidy up by deleting the subscription and the topic.
subscriberService.DeleteSubscription(subscriptionName);
publisherService.DeleteTopic(topicName);
```

Exception has occurred: CLR/Grpc.Core.RpcException
An exception of type 'Grpc.Core.RpcException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Status(StatusCode="DeadlineExceeded", Detail="")'
   at Grpc.Net.Client.Internal.GrpcCall`2.<GetResponseHeadersCoreAsync>d__72.MoveNext()
   at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass12_0.<WithCallSettingsOverlay>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Cloud.PubSub.V1.PublisherServiceApiClientImpl.CreateTopic(Topic request, CallSettings callSettings)
   at Google.Cloud.PubSub.V1.PublisherServiceApiClient.CreateTopic(TopicName name, CallSettings callSettings)

I already execute command `gcloud auth application-default login` to set up Application Default Credentials. I also used service account impersonation to create a local ADC file. But It still doesn't work.

#### Environment details

  - OS: Windows10
  - .NET version: .net8.0
  - Package name and version: Google.Cloud.PubSub.V1  3.16.0

Thanks!

**Comment by jskeet** [comment]
This sounds like a network issue to me - this code definitely *does* work in Windows (our integration tests cover far more than this, and they run nightly on Windows as well as Linux) so we need to work out why the call is timing out.

If you're able to test the same code in a different network environment, that would help as a starting point. Beyond that, please tell us more about the network in which this code is running. Are you behind a proxy server, for example?

One issue we've seen in some cases is that HTTP/3 (QUIC) can cause problems. One way of testing that would be to try the same code but using .NET 6.0 instead of .NET 8.0, as .NET 6 doesn't support QUIC. Are you happy to give that a try? If the code works with .NET 6, we can provide a workaround for disabling QUIC in .NET 8.

**Comment by jskeet** [comment]
@Rr7716 Have you been able to investigate this any further as per my comment?

We'll close this issue in a few days if we don't hear back, but you'll still be able to add more information in a comment and we can reopen if necessary.

**Comment by jskeet** [comment]
FYI: Google.Cloud.Pubsub v3.18.0 was released last week, using Grpc.Net.Client v2.66.0 which uses HTTP/2.0 by default, so the workaround isn't required any more.
