### ISSUE TITLE
[Feature Request] Add option to allow gRPC sub-channel reuse

### ISSUE THREAD

**Issue by jeffijoe** [googleapis/google-cloud-dotnet#13655]
**Is your feature request related to a problem? Please describe.**
We run a lot of integration tests against a PubSub emulator, and the service we are testing is both sending and receiving PubSub messages. We have more than 30 topics, and probably around ~100 subscriptions, all running in a single application. On its own this is not a problem, but since we run integration tests concurrently, we'll be spawning many instances of the application, which results in opening a ton of TCP connections to the emulator for both publishing and subscribing.

 **Describe the solution you'd like**
Having dug into the code, I noticed the library intentionally avoids subchannel reuse, which of course makes sense for high-performance scenarios.

https://github.com/googleapis/google-cloud-dotnet/blob/86e0b08262bd101b4c79a287da12ecae5b063b69/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClientBuilder.cs#L120-L122

For local development though, and for low throughput scenarios, I believe having an option to reuse subchannels would be beneficial to avoid spawning a ton of connections. On macOS, the default ephemeral port range is much smaller than that of Linux, so I run out of file descriptors rather quickly.

 **Describe alternatives you've considered**
I have already set `ClientCount = 1` everywhere.

**Comment by amanda-tarafa** [comment]
Thanks, I'm looking at this.
