### ISSUE TITLE
How to use HMAC credentials to download a file using the StorageClient?

### ISSUE THREAD

**Issue by 64J0** [googleapis/google-cloud-dotnet#13700]
## Description

Hello, hope you're good. I'm searching through the docs how to use the [HMAC credentials](https://cloud.google.com/storage/docs/authentication/hmackeys) with the **StorageClient**, but didn't find any example. How should I use it?

I'd like to use the methods from this class like `GetObjectAsync` to make my life easier, instead of making a common request using an HttpClient and parse the result.

If this is not the right place to ask this question, please let me know.

---

Update:

I found [this StackOverflow thread](https://stackoverflow.com/questions/65495865/upload-file-to-google-cloud-storage-using-hmac-key-in-c-sharp), where the accepted answer tells us to use the AWS SDK instead of GCP. Is this still valid, or has GCP SDK caught up already?

**Comment by amanda-tarafa** [comment]
Authentication via HMAC credentials is [only supported by the XML Storage API](https://cloud.google.com/storage/docs/authentication/hmackeys), and the Google.Cloud.Storage.V1 library is for the JSON API. So if you want to use HMAC credentials for different Storage operations, you cannot use the Google.Cloud.Storage.V1 library.

That said, it seems you are only interested in using HMAC keys for downloading a objects. For that, you can create [HMAC signed URLs](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Storage.V1/latest#hmac-signed-urls) using Google.Cloud.Storage.V1.

**Comment by 64J0** [comment]
Got it, thanks for the information.
