### ISSUE TITLE
Release new version of Google.Cloud.Logging.Console with updated dependency

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#13824]
Currently we depend on Microsoft.Extensions.Logging.Console 6.0.0 which has a vulnerable transitive dependency on System.Text.Json.
We should bump to 6.0.1 (at least) and release a patch version.

**Comment by amanda-tarafa** [comment]
Closing, this has been released: https://www.nuget.org/packages/Google.Cloud.Logging.Console/1.3.1
