### ISSUE TITLE
Google.Cloud.Firestore not uploading base class properties to Firestore document

### ISSUE THREAD

**Issue by tigerepic77** [googleapis/google-cloud-dotnet#13968]
OS: Windows 11

.NET version: 9.0 (Tested in 8.0 as well)

Package name and version: Google.Cloud.Firestore 3.9.0

Hello!

I just wanted to bring up an issue I am encountering lately. I have provided a simplified version of my code below.

I am able to upload the derived class to the Firestore document but the base class properties just don't appear on the server.

This was working a few days ago and I have made some changes to my application regarding these classes, but I have been racking my brain and cannot find any issue of my own that would cause this.

If someone could have a look I'd really appreciate it.

Thanks.

```
[FirestoreData]
public class OverallClass
{
    [FirestoreData]
    public class BaseClass
    {
        [FirestoreProperty] string base_property { get; set; } = "";
        public string BaseProperty { get { return base_property; } set { base_property = value; } }
    }

    [FirestoreProperty] public DerivedClass Derived { get; set; } = new DerivedClass();

    [FirestoreData]
    public class DerivedClass : BaseClass
    {
        [FirestoreProperty] string derived_property { get; set; } = "";
        public string DerivedProperty { get { return derived_property; } set { derived_property = value; } }
    }
}

DocumentSnapshot Snapshot = await FirestoreDocument.GetSnapshotAsync();

if (Snapshot.Exists == false)
{
    OverallClass Overall = new OverallClass();

    await FirestoreDocument.CreateAsync(Overall);
}
```

**Comment by jskeet** [comment]
It looks like we *do* serialize private properties of the specific type being serialized, but not private properties in the base class.
(I'm surprised we serialize private properties at all, to be honest, but obviously it would be a breaking change to change that now, and it's tested, so presumably it's deliberate.)

The simplest fix to this is to avoid having those two separate properties per class, which are confusing apart from anything else - just have one public property per class:

```csharp
[FirestoreData]
public class OverallClass
{
    [FirestoreData]
    public class BaseClass
    {
        [FirestoreProperty] public string BaseProperty { get; set; } = "";
    }

    [FirestoreProperty] public DerivedClass Derived { get; set; } = new DerivedClass();

    [FirestoreData]
    public class DerivedClass : BaseClass
    {
        [FirestoreProperty] public string DerivedProperty { get; set; } = "";
    }
}
```
If you want to use snake case for the name in Firestore, you can specify that:

```csharp
[FirestoreData]
public class OverallClass
{
    [FirestoreData]
    public class BaseClass
    {
        [FirestoreProperty("base_property")]
        public string BaseProperty { get; set; } = "";
    }

    [FirestoreProperty] public DerivedClass Derived { get; set; } = new DerivedClass();

    [FirestoreData]
    public class DerivedClass : BaseClass
    {
        [FirestoreProperty("derived_property")]
        public string DerivedProperty { get; set; } = "";
    }
}
```

We could *consider* serializing private inherited (attributed) properties in the future, but again, that would be a breaking change so I'd prefer not to. I can add a note to the documentation though.

**Comment by jskeet** [comment]
I'm going to close this issue now as I believe I've addressed your concern. Please add a comment if you have further questions.

**Comment by tigerepic77** [comment]
Sorry for the late reply, many thanks for your help!
