### ISSUE TITLE
Google.Cloud.BigQuery.V2 - GetTableAsync does not work for .NET 9.0

### ISSUE THREAD

**Issue by dhanjel** [googleapis/google-cloud-dotnet#13975]
#### Description

The `Google.Cloud.BigQuery.V2.BigQueryClient::GetTableAsync` throws an exception when invoked with `projectId`, `datasetId` and `tableId`. This only happens in .NET 9.0, if I downgrade my sample application to .NET 8.0 keeping the same nuget package version, it works just fine. _(Tested older versions as well without any luck.)_

For both framework version tests, the parameters are hard coded in the class as private read only variables and does not change between tests.

```json
{"ServiceName":"bigquery","Error":null,"HttpStatusCode":0,"Message":"Parameter validation failed for \"tableId\" : The parameter value must be a non-empty string","Data":{},"InnerException":null,"HelpLink":null,"Source":"Google.Apis","HResult":-2146233088,"StackTrace":" at Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)\r\n at Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()\r\n at Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)\r\n at Google.Apis.Requests.ClientServiceRequest`1.ExecuteUnparsedAsync(CancellationToken cancellationToken)\r\n at Google.Apis.Requests.ClientServiceRequest`1.ExecuteAsync(CancellationToken cancellationToken)\r\n at Google.Cloud.BigQuery.V2.BigQueryClientImpl.GetTableAsync(TableReference tableReference, GetTableOptions options, CancellationToken cancellationToken)\r\n at GoogleBigQueryService.GetRowCountAsync() in c:\\...\\GoogleBigQueryService.cs:line 43"}
```

#### Environment details

  - OS:
  - .NET version: 9.0
  - Package name and version: Google.Cloud.BigQuery.V2, 3.10.0

#### Steps to reproduce

```
var credentials = GoogleCredential.FromJson(_jsonCredentials);
var client = BigQueryClient.Create(_projectId, credentials);
var table = await _client.GetTableAsync(_projectId, _datasetId, _tableId);
```
 The line `var table = await _client.GetTableAsync(_projectId, _datasetId, _tableId)` throws an exception when targeting .NET 9, but not when targeting .NET 8.

Project file for reference:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.BigQuery.V2" Version="3.10.0" />
  </ItemGroup>

</Project>
```

**Comment by jskeet** [comment]
This is due to a .NET 9.0 JIT bug. See https://github.com/googleapis/google-api-dotnet-client/issues/2897 for another report of this with Google libraries, and https://github.com/dotnet/runtime/issues/108969 for the core runtime issue.

**Comment by dhanjel** [comment]
Ah I see, so while waiting for MS to resolve and release a fix for the issue in the framework (https://github.com/dotnet/runtime/issues/108969), we should set the env-variable then (`DOTNET_JitEnablePhysicalPromotion=0`)? 

That seems to resolve the issue locally at least so I assume it will work in Azure as well since others has had success there.

**Comment by jskeet** [comment]
Yes, I think that would be the best way forward.

**Comment by jskeet** [comment]
(Closing this issue now.)
