### ISSUE TITLE
Fix Bigtable admin pagination workarounds before GA

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#1776]
The Bigtable admin API doesn't fully support pagination, but we've got workarounds in the library to allow PagedEnumerable (etc) to be implemented, so long as users never set a page size.

We should almost certainly not go to GA with those in place.

**Comment by jskeet** [comment]
Reassigned to Mike as he's keeping better tabs on this than I am.

**Comment by jskeet** [comment]
(The bulk of the work for this will be internal, hence the lack of discussion here. This issue is mostly a placeholder to help make sure we don't forget about it.)

**Comment by jskeet** [comment]
The partial class can (and must) now be removed, but I need to check exactly how far it's really implemented.

**Comment by sduskis** [comment]
@jskeet, what's your take on this?

Also, can you please remove the "p2" label?

**Comment by jskeet** [comment]
I think it's best to continue the discussion via the internal mail thread. (I won't be terribly active on that right now as I'm travelling, but it seemed to have stalled anyway.)

 I can't remove the P2 label as otherwise it'll come up as untriaged - any particular reason it's causing a problem?

**Comment by sduskis** [comment]
@jskeet, oh sorry.  I didn't realize that "type: cleanup" also required a "priority: *" label.

**Comment by jskeet** [comment]
@sduskis: I *believe* it does, but I could be wrong. Will kill that label (the alert one) - I can always reapply it if it comes back saying it needs triage :)

**Comment by jskeet** [comment]
We removed ListSnapshots recently, and ListAppProfiles is now paginated appropriately server-side. ListInstances and ListClusters are not paginated either server-side or client-side. Closing as I believe we're done here.
