### ISSUE TITLE
Integrate OpenCensus with Google implementation

### ISSUE THREAD

**Issue by iantalarico** [googleapis/google-cloud-dotnet#1894]
This will involve work for both HTTP and gRPC libraries.

For HTTP libraries we need to ensure they can easily accept a HttpMessageHandler (This already works but is complicated). 

For gRPC we need to work with the gRPC team to see how we can hook into the native lib.

cc: @jskeet @chrisdunelm

**Comment by jskeet** [comment]
For gRPC, we are likely to expose an interceptor property into client settings. This can be used for logging as well as other use cases. Do we think that would handle everything we'd need?

**Comment by jskeet** [comment]
(Actually, presumably this isn't something the user should set up. Ian and Amanda, let's talk about this some time soon.)

**Comment by iantalarico** [comment]
Agreed the only set up that the user should be doing is to add the propagating handler to the http/grpc client and then to the library.

**Comment by amanda-tarafa** [comment]
Still blocked on OpenCensus .NET integration. Renamed issue.

**Comment by jskeet** [comment]
I'm going to close this as an issue for now. OpenCensus work is well underway, but won't be ready for us to integrate with for quite a while, and I don't think we'll miss the fact that we should integrate with it when we can.
