### ISSUE TITLE
Create a Timed and Sized buffer combination for the Google.Cloud.Diagnostics.* libraries

### ISSUE THREAD

**Issue by iantalarico** [googleapis/google-cloud-dotnet#2163]
We should create a timed and sized buffer for the Google.Cloud.Diagnostics.* libraries.  This would allow for a combination of the best of both.  We will always flush after some time so entries aren't miss and won't ever hold on to too many entries waiting for a flush.

**Comment by jskeet** [comment]
Closing for the moment as customers haven't mentioned a need for this.
