### ISSUE TITLE
Add integration tests for the ErrorReportingExceptionFilter

### ISSUE THREAD

**Issue by iantalarico** [googleapis/google-cloud-dotnet#2168]

**Comment by amanda-tarafa** [comment]
Blocked by #2297

**Comment by amanda-tarafa** [comment]
Closing this for now as we are reevaluating our Google.Cloud.Diagnostics.* library strategy.
See:

- [Google.Cloud.Diagnostics.AspNet version history](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNet/history.html).
- [Google.Cloud.Diagnostics.AspNetCore version history](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNetCore/history.html)
