### ISSUE TITLE
Log or write exceptions thrown in the TimedBuffer

### ISSUE THREAD

**Issue by iantalarico** [googleapis/google-cloud-dotnet#2182]
See https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/TimedBufferingConsumer.cs#L53

**Comment by amanda-tarafa** [comment]
Moving to the backlog as we don't have a good solution for where to log these.
