### ISSUE TITLE
Diagnostics.AspNet: Add integration tests against an IIS hosted application (Web Api and MVC)

### ISSUE THREAD

**Issue by amanda-tarafa** [googleapis/google-cloud-dotnet#2297]
There are differences between self hosted and IIS hosted ASP.Net applications that impact the Diagnostics library ( see #2292 and #2294). We are adding integration tests against self hosted applications but we should also add test applications against IIS hosted applications, since this is probably the most common use case for ASP.Net development. (We can probably set up an IIS Express on the jenkins machine an have a simple ASP.Net application hosted there to test against).

This is way less important for ASP.Net Core because ASP.Net Core is supposed to run the same "everywhere", so it is more OK if we assume the same behavior from ASP.Net Core applications regardless of how they are being hosted. And we already have integrations tests for ASP.Net Core.

**Comment by amanda-tarafa** [comment]
For integration testing of the Diagnostics library from within an Asp.Net MVC application this seems to be the only option, that is, to have an IIS hosted MVC application.

**Comment by jskeet** [comment]
This is work that Amanda will probably come back to when back from leave.

**Comment by amanda-tarafa** [comment]
Closing this for now as we are reevaluating our Google.Cloud.Diagnostics.* library strategy.
See:

- [Google.Cloud.Diagnostics.AspNet version history](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNet/history.html).
- [Google.Cloud.Diagnostics.AspNetCore version history](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNetCore/history.html)
