### ISSUE TITLE
Spanner resource handling still broken

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#2313]
I merged #2299, but the integration tests are flaky. I'm 99% sure there are still some leakages going on. Must fix!

**Comment by jskeet** [comment]
I've spent a lot of time looking at this, and I believe it can't be fixed in the current approach - I'll need to create a bigger design change for this. Will write up a document first, then implement it.

**Comment by jskeet** [comment]
(This work is still ongoing. I've made big strides, but we're not there yet.)

**Comment by JustinBeckwith** [comment]
👋 just wanted to check in here.  This one is starting to show up on a few dashboards.  Is this a customer impacting P1?  Anything we can do to help it along?

**Comment by jskeet** [comment]
The code is nearly finished, with more unit tests required. It will then take pretty careful review - this is a big deal.

It'll be easier to start getting code in once the Spanner DML branch has been merged, but there's nothing holding it up that can be helped.

We haven't heard about this directly as a customer issue, although there's one issue that *might* be resolved by this.

**Comment by JustinBeckwith** [comment]
Hah, no rush at all :) I just wanted to check in and make sure this is rockin and rollin, which it appears to be.  Thanks Jon!

**Comment by jskeet** [comment]
Lowering this to P2 as we haven't heard anything from customers about it impacting them, even though I suspect it may do so. We're getting close to being able to merge the fix though...

**Comment by jskeet** [comment]
This is now effectively fixed - hooray! There's a little tidying up to do (e.g. a migration guide) but we're basically there.
