### ISSUE TITLE
V2 Support for Browse Carousel Responses

### ISSUE THREAD

**Issue by timtye** [googleapis/google-cloud-dotnet#2377]
Browse Carousel responses can be configured via Dialogflow, but are not included in the MessageOneOfCase class and the responses are not included in the FulfillmentMessages list.

**Comment by jskeet** [comment]
Actually, scratch my previous comment - I'm now a bit confused. [MessageOneofCase](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Dialogflow.V2/api/Google.Cloud.Dialogflow.V2.Intent.Types.Message.MessageOneofCase.html) contains "CarouselSelect" and Message has a [CarouselSelect](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Dialogflow.V2/api/Google.Cloud.Dialogflow.V2.Intent.Types.Message.html#Google_Cloud_Dialogflow_V2_Intent_Types_Message_CarouselSelect) property.

Are you asking for something different to that?

(I should state that I don't know much about Dialogflow, and I've never used it myself - the library is purely autogenerated from the [proto description](https://github.com/googleapis/googleapis/tree/master/google/cloud/dialogflow/v2). It's entirely possible that hand-written libraries may have slightly different names, e.g. "browse carousel" vs "carousel selector" - is it possible that that's the source of confusion here?

**Comment by timtye** [comment]
No, browse carousel and select carousel are different and can both be set up in dialog flow. Select carousel let’s you pick an option and submit it in the chat window. Browse carousel lets you specify links that take you out of the app to whatever webpage is specified.

Sent from my iPhone

On Jul 27, 2018, at 5:54 AM, Jon Skeet <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, scratch my previous comment - I'm now a bit confused. MessageOneofCase<https://protect-us.mimecast.com/s/Z71xC9rpynikMvO2Foo2rR> contains "CarouselSelect" and Message has a CarouselSelect<https://protect-us.mimecast.com/s/SbOeC0R2m4iGMKymFDgp2Y> property.

Are you asking for something different to that?

(I should state that I don't know much about Dialogflow, and I've never used it myself - the library is purely autogenerated from the proto description<https://protect-us.mimecast.com/s/vWCLCgJxGviAmrBGF25CjV>. It's entirely possible that hand-written libraries may have slightly different names, e.g. "browse carousel" vs "carousel selector" - is it possible that that's the source of confusion here?

**Comment by jskeet** [comment]
Okay - in that case I don't see any support for it in those protos yet.

I'll ask internally, but until the protos have been published, I won't be able to do anything.

**Comment by timtye** [comment]
Here is an example from the DialogFlow UI:
<img width="537" alt="screen shot 2018-07-30 at 1 33 12 pm" src="https://user-images.githubusercontent.com/3943903/43416181-329523da-93fd-11e8-9b96-e5a7d4092bc6.png">

**Comment by jskeet** [comment]
I've reported this internally as a feature request - there's nothing I can do until it's exposed in the protos, I'm afraid. I'll update this issue when I hear something.

**Comment by jskeet** [comment]
Just to say, I'm still chasing this internally.

**Comment by jskeet** [comment]
This has now been added to V2 - hooray! I've released Google.Cloud.Dialogflow.V2 version 1.2.0-beta01 with this functionality.

**Comment by timtye** [comment]
Thank you so much Jon!
