### ISSUE TITLE
not an easy way or consistent way to use publisher client to post to Google Pub/Sub.

### ISSUE THREAD

**Issue by athrayee** [googleapis/google-cloud-dotnet#2436]
I am trying to use Pub/Sub from .NET client library. There is no easy and consistent way to create Publisher Client and pass Credential. The library is expecting to set environment variable only. You can find more details in the issue I have opened here in stackoverflow.

https://stackoverflow.com/questions/51801386/how-to-pass-google-credential-to-google-pub-sub/51813713?noredirect=1#comment90828782_51813713

**Comment by chrisdunelm** [comment]
Sorry for the delay in responding, Answered on stackoverflow.
