### ISSUE TITLE
Stringly-Typed Paths

### ISSUE THREAD

**Issue by bdhess** [googleapis/google-cloud-dotnet#2442]
Of the GAPIC-generated clients, .NET is the only environment where paths cannot be passed as strings.  This proves unwieldy in instances where multiple kinds of paths are accepted.  For example, in Cloud KMS, encrypt and decrypt cannot accept the same path object.

```
CryptoKeyName path1 = new CryptoKeyName(project, location, keyRing, cryptoKey);
CryptoKeyPathName path2 = CryptoKeyPathName.Parse(path1.ToString());

string textRaw = "The quick brown fox jumps over the lazy dog!";

EncryptResponse encRes = kms.Encrypt(path1, ByteString.CopyFromUtf8(textRaw));
DecryptResponse decRes = kms.Decrypt(path2, encRes.Ciphertext);
```

In contrast, the Java client accepts string overloads.  It would be ideal if the .NET clients did as well, to enable this style of invocation instead of the above example:

```
string path = new CryptoKeyName(project, location, keyRing, cryptoKey).ToString();

string textRaw = "The quick brown fox jumps over the lazy dog!";

EncryptResponse encRes = kms.Encrypt(path, ByteString.CopyFromUtf8(textRaw));
DecryptResponse decRes = kms.Decrypt(path, encRes.Ciphertext);
```

**Comment by jskeet** [comment]
I believe this is already planned, but I can't remember whether we're tracking it anywhere.

@chrisdunelm do you have an issue for this somewhere?

**Comment by bdhess** [comment]
I'm happy with no mixing.  An exponentially increasing number of overloads in autocomplete would be super unhelpful.

**Comment by chrisdunelm** [comment]
Thanks, yes, was is planned to be done.
We're currently working on a new code-gen implementation (soon to be in github), which will contain this feature. We don't have a firm release-date for this, but should be in the next couple of months.
