### ISSUE TITLE
Path Formatting Helpers

### ISSUE THREAD

**Issue by bdhess** [googleapis/google-cloud-dotnet#2443]
Assuming that we feel like #2442 is worth completing, then a further level of convenience would be provided by adding static formatting methods to the path types.

For example, instead of
```
string path = new CryptoKeyName(project, location, keyRing, cryptoKey).ToString();
```

A caller could do
```
string path = CryptoKeyName.Format(project, location, keyRing, cryptoKey);
```

The latter feels more canonical to a .NET programmer.

**Comment by bdhess** [comment]
Note that the equivalent already exists in Java; see e.g. https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-api-grpc/proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyName.java#L70

**Comment by bdhess** [comment]
Yeah, calling `static string Format` "more canonical" was probably the wrong way to characterize it.  I should've said something like "feels more right" (at least, to me).  In any case, I'd raise the following points in support of offering something other than `new Foo(bar, baz).ToString()`:

1. Relying on a `ToString` value will always requires a visit to the documentation, if for no other reason than to confirm that the default implementation has been overridden.  Along these lines, a developer looking for valid methods/properties in Intellisense will likely visit ToString only after excluding the other available options.

2. The discussion of `ToString` in the .NET Framework Design Guidelines book describes `ToString` as "intended to be used for general display and debugging purposes".  It then offers some anecdotes of how attempting to use a value returned by `ToString` has burned the annotators in the past, even when `ToString` seemed to provide the intended output on casual inspection (pp 271-273).  This may ultimately be in the same family as the point above, but I think just further emphasizes that it's a time sink for developers to confirm that `ToString` indeed does what they want.

3. Calling a static Format method avoids allocating a throwaway object.

**Comment by chrisdunelm** [comment]
Yes this looks like a helpful feature.
We're currently working on a new code-gen implementation (soon to be in github), in which we'll put this feature. We don't have a firm release-date for this, but should be in the next couple of months.

**Comment by jskeet** [comment]
@chrisdunelm: As you've been working on resources and resource names recently, is now a good time to implement this?

**Comment by chrisdunelm** [comment]
Thanks for the reminder. Yes, I'll implement these in the micro-generator.

**Comment by chrisdunelm** [comment]
This feature is now implemented in the micro-generator. So it won't appear in the generated code until we start using the micro-generator; which is not yet the case for any library.

**Comment by jskeet** [comment]
Given that there's no action left beyond "start using the microgenerator when we can" I'd propose closing this issue. @bdhess are you okay with that?

**Comment by chrisdunelm** [comment]
Closing as this is now present in both generators,

**Comment by jskeet** [comment]
Reopening but assigning to myself as I have a bit of work left to do - where we have resource name classes that aren't generated in the regular way.

**Comment by chrisdunelm** [comment]
Sorry, I was too enthusiastic ;)
