### ISSUE TITLE
Make serialization/deserialization without FirestoreData/FirestoreProperty attributes

### ISSUE THREAD

**Issue by enriko-riba** [googleapis/google-cloud-dotnet#2520]
Currently we have to either use property decoration or serialize via maps.

1st approach works for owned classes but not for classes in 3rd party assemblies as we can not decorate them. In addition mapping to enums or structs is also an issue.

2nd approach requires writing code to convert POCO instances to `Dictionary<string, object>` and vice versa. This is practical only for most simple classes without deep hierarchy. Unless one is willing to use reflection you are forced to write specific converters like:
```
public static class Extensions
{
        public static User ToUser(this Dictionary<string, object> map)
        {
            User user = new User()
            {
                Email =  (string)map["email"],
                IsActive= (bool)map["isActive"],               
                State = map["state"].ToUserState(), // <-- another map
            };
            return user;
        }
        public static UserState ToUserState(this object state)
        {
            var map = (Dictionary<string, object>) state;
            UserState userState = new UserState() {                
                NestedChild = map["anotherChildClass"].ToAnotherNestedObject(), // <-- deeper levels
            };
            return userState;
        }
```
For saving documents you also need the same conversions in opposite direction :-(

The serialization should be simple as if working with `JsonConvert.Serialize() Deserialize<T>()`. 
BTW why is working with JSON not supported?

**Comment by jskeet** [comment]
We're definitely *not* going to take a dependency on Json.NET. That approach leads to potentially harmful version mismatches which we've had experience of before.

You can serialize to and from a `Dictionary<string, Value>` to effectively retain the protobuf representation - and your application could even depend on Json.NET and have a way of using their annotations to perform the serialization and deserialization if necessary.

If you want to depend on actual JSON, just converting a `Value` to a string will render JSON directly, so if you don't mind the extra performance hit of then reparsing it, that's an option.

Fundamentally mapping like this is a huge minefield, and the purpose of the Firestore library isn't to provide an endlessly-customizable serialization/deserialization framework that happens to talk to Firestore. It's to provide easy access to the Firestore API that happens to have some useful serialization and deserialization options.

There's a balance to be struck, but I don't want the serialization process to get significantly more complex than it already is.

**Comment by enriko-riba** [comment]
You are actually rephrasing my statement that the serialization is impractical as it results in working with Dictionary objects instead with strongly typed objects. I understand serialization is low on your priority list but I am searching for guidelines how to accomplish this with maintainable code.

Am I missing an obvious way of converting those dictionaries into strongly typed objects? 
You mentioned protobuf - as I never used the lib before - I am wondering if it would be possible to do something in the lines of:
1. create message formats for our classes, 
2. compile the .proto files and 
3. feed the dictionary instances into the compiled .cs classes

If that's possible it deserves to be mentioned on the docs site.

**Comment by jskeet** [comment]
You'd still need to write conversions from the `Value` proto to your classes, yes. Doing so directly from `Value` would probably be better than going via the "default" deserialization/serialization to .NET types. There's no quick win there: it would involve writing code, either on a case-by-case basis or writing your own serialization framework.

In terms of protobuf, no, creating a protobuf message wouldn't help - the `Value` proto is from the Firestore API, and is the sort of "native" representation. Firestore doesn't handle arbitrary protobuf messages.

**Comment by jskeet** [comment]
Closing as we don't expect to act on this directly. With the proposal in #2534, you'd be able to potentially create a single wrapper class with the attribute specifying a serializer. That feature request is far from certain at the moment, but it's probably your best way forward here - I suggest you subscribe to that issue for updates.
