### ISSUE TITLE
Memory leak issue while publishing message

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/google-cloud-dotnet#2532]
Copied from https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/547

Hi,
The memory size is increasing and crashing the application at the below line.

publishTasks.Add(publisher.PublishAsync(text));

Any idea how to clear the memory after a message? We have to send 1000's of records in a minute and the memory is keep on increasing.

**Comment by jskeet** [comment]
Code causing a problem is [here](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/8aab65220c26cce1ed03edd3cfd4b23b907e6d76/pubsub/api/PubsubSample/Program.cs#L281)

**Comment by chrisdunelm** [comment]
OK... Then I guess I'll update the sample

**Comment by chrisdunelm** [comment]
@SurferJeffAtGoogle Created https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/645 adding a comment to the sample. Please can you review?
