### ISSUE TITLE
Firestore offline sync support for xamarin (dot net)

### ISSUE THREAD

**Issue by kabilan-ravi** [googleapis/google-cloud-dotnet#2537]
Firestore offline sync support for xamarin (dot net). When can we expect this to happen? Currently we are using couchbase. We are thinking of moving our entire data storage to firestore. Getting the offline sync support is the main blocker for us to proceed with firestore. Can anyone give me an update on this?

**Comment by jskeet** [comment]
I can't speak to this myself - it would be best to ask on the [Google Group](https://groups.google.com/forum/#!forum/firebase-talk). While I could ask a Firestore team member for comments, it's not productive for me to relay messages back and forth - and asking in the Google Group would also be better for visibility.

It won't be the same codebase as the library in this repo, so I'm going to close this issue now, as there won't be anything to do here. Please don't take this as an indication that I don't think it's important - it's just a matter of this not being the best place to have the discussion.
