### ISSUE TITLE
FirestoreChangeListener

### ISSUE THREAD

**Issue by sasog23** [googleapis/google-cloud-dotnet#2544]
is it possible to query/listen to the collection based on the last update time,
without adding additional field(last update time) to the document

CollectionReference collectionListen = firestoreDb.Collection("saso-test");
Timestamp _ts= new Timestamp();
Query queryListen = collectionListen.WhereGreaterThanOrEqualTo("timestamp", _ts);
FirestoreChangeListener listener = queryListen.Listen( callback: snapshot =>
            { ...

**Comment by jskeet** [comment]
No, I don't believe it is - you basically need to add it to your document, and use the server timestamp special value when you modify the document. That's certainly what I've been led to believe in conversations with the Firestore team before, when asking about #2250.

I'm going to close this issue now as it's not really about the .NET library - I suggest that if you want to talk more about it with the Firestore team, you post on the [Google Group](https://groups.google.com/forum/#!forum/firebase-talk).
