### ISSUE TITLE
Problem SensitiveCase Fulfillment response dialogflow

### ISSUE THREAD

**Issue by MRomeror** [googleapis/google-cloud-dotnet#2555]
Hello,
Have a project lambda .NET Core and main function return WebhookResponse, the name of the objects starts with a capital letter and forms the following JSON
`{
  "Payload": null,
  "Source": null,
  "FulfillmentText": "Hola Mundo",
  "OutputContexts": null
}`

When I call the intent I get the following status: `"Webhook call failed. Error: Failed to parse webhook JSON response: Cannot find field: FulfillmentText in message google.cloud.dialogflow.v2.WebhookResponse."`

I tried to create a class with the objects in lowercase and so if it worked for me.

Is there any way that this does not happen and can send it in lower case?

Thanks and I'm sorry for my English

**Comment by jskeet** [comment]
You need to use the Protocol Buffers library for JSON parsing and formatting.

We have an example at https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Dialogflow.V2/index.html which should help you.

**Comment by jskeet** [comment]
That's part of ASP.NET Core.

**Comment by MRomeror** [comment]
My project is lambda function and use .NET Core 2.1. Is there another solution?

**Comment by jskeet** [comment]
You need to find whatever you need to do to just send back a JSON string directly. I'm sure it's easy, but I haven't used lambda functions myself.

**Comment by MRomeror** [comment]
Ok, Thanks :)

**Comment by jskeet** [comment]
Closing as I assume this is now resolved. (If not, we need more information.)
