### ISSUE TITLE
SpannerConnectionStringBuilder: More settable properties.

### ISSUE THREAD

**Issue by ILMTitan** [googleapis/google-cloud-dotnet#2556]
SpannerConnetionStringBuilder properties Project, SpannerInstance and SpannderDatabase should all be settable.

I would like to be able to do 
```
new SpannerConnectionStringBuilder {
    Project = googleCloudProject,
    SpannerInstance = instanceName,
    SpannerDatabase = databaseName
};
```
instead of 
```
new SpannerConnectionStringBuilder {
     DataSource = $"projects/{googleCloudProject}/instances/{instanceName}/databases/{databaseName}"
};
```

**Comment by jskeet** [comment]
Hmm... will see what I can do in the rewrite. If the existing connection string can be parsed, it's fine - if we don't currently have a valid data source, "replacing" just the SpannerInstance may not make much sense.

**Comment by jskeet** [comment]
How would you feel about exposing the DatabaseName property (of type DatabaseName, which is a fully-qualified name with project and instance) instead? That way:

```csharp
new SpannerConnectionStringBuilder
{
    DatabaseName = new DatabaseName(googleCloudProject, instanceName, databaseName)
}
```

That way we don't need to worry about partially-populated builders with an instance but no project, for example.

**Comment by ILMTitan** [comment]
That looks like a good way to do it. It removes the format string, which was my biggest concern. The only downside is lower discoverability, but I think avoiding the partially-populated builders problem is worth it.

**Comment by jskeet** [comment]
Great! Will add that tomorrow - but we're still a little way off the next release with the new session pool...
