### ISSUE TITLE
Working with EntityTypesClient

### ISSUE THREAD

**Issue by sabiland** [googleapis/google-cloud-dotnet#2558]
I have started refactoring our company's backend from DialogFlow V1 to V2 gRPC API.

I have already many problems and am totally confused. Say I want to get ONLY one entity info.

1) I have created NEW agent, set-up Google IAM, credentials, etc.
2) I have imported our current V1 agent and converted it to API V2
...
3) EntityTypesClient
4) Among our entitites is one: **"program"**
5) When I call client.GetEntityTypeAsync 
6) EntityTypeName(Globals.GlobalMasterSettings.DialogFlowV2AgentProjectID, **"program"**)

I receive error: "program" **Entity Type ID is not valid.**
Is there NO way to retrieve (or batch update) entity by **"entity display name"** ?

Then I tried to create ONE new entity -> this worked, but then I saw in response some GUID (e.g. 752915fd-0091-4d25-92b1-a680db96908e) for new created entity as Entity Type ID. Now I am totally confused about this resource-id. Is there any way to retrieve resource-id for specific entity by **"entity display name"** ?

And further, is there no way to get ALL entities at once? I don't see any method in API which could do this.

**EDIT: I have found the way how to do it**

To get proper entity type id (GUID), first I have to call ListEntityTypes, then find appropriate entity by display name and then update it

```
var eett = client.ListEntityTypes(
                                new ListEntityTypesRequest()
                                {
                                    Parent = $"projects/{Globals.GlobalMasterSettings.DialogFlowV2AgentProjectID}/agent"

                                }
                                );

                            foreach (var et in eett.ToList())
                            {
                                Debug.WriteLine(et.DisplayName);
                                Debug.WriteLine(et.EntityTypeName.EntityTypeId);
                                Debug.WriteLine("---");
                            }
```

**Comment by jskeet** [comment]
I'm glad you've solved the problem - I'll close the issue.

I'm afraid we're *mostly* unable to help with API-specific detail in this repo; we're responsible for making sure the APIs can be accessed reliably from C#, but we don't know the details of all the APIs. (For some where we write significant wrapper code by hand, we're more likely to have an idea, but Dialogflow is purely generated.) For further Dialogflow questions that aren't C#-specific, I'd suggest asking on [the Dialogflow help forum](https://productforums.google.com/forum/#!forum/dialogflow)

**Comment by sabiland** [comment]
Thx for info Jon (I mean "The Jon Skeet" on StackOverflow ;)).

Yes, I have solved the issue.
Basically I needed 2 days to refactor from old V1 REST to new V2 gRPC. I have tested everything and V2 over gRPC works like a charm 👍 .

Ok, I'll ask possible further questions on Dialogflow forum. The only problem is there is so little happening on that forum :).
