### ISSUE TITLE
Support for Google Cloud Build

### ISSUE THREAD

**Issue by samuela** [googleapis/google-cloud-dotnet#2587]
There's currently no support for Google Cloud Build AFAICT. Can we haz pretty plz?

If not, how can we use this library in order to do the necessary auth for the available cloud build REST API?

**Comment by jskeet** [comment]
Thanks for the feature request.

For the moment you can use the [Google.Apis.CloudBuild.v1](https://www.nuget.org/packages/Google.Apis.CloudBuild.v1/) REST-based library, with the [normal authentication mechanisms](https://cloud.google.com/docs/authentication/getting-started) for our libraries.

Internal teams need to perform additional work for the gRPC-based library generation, and this hasn't been done yet. I expect it will happen in the future, but for the moment the REST-based library should do what you need.

I'll close this issue now as the maintainers of this repo don't drive which APIs have gRPC-based libraries built for them - but please don't take this as a sign that I disagree with the request!

**Comment by samuela** [comment]
@jskeet Thanks so much for pointing me to https://www.nuget.org/packages/Google.Apis.CloudBuild.v1/! I had no clue that such a library existed at all.

**Comment by jskeet** [comment]
No problem - in general, if you're looking for a library for Cloud API "FooBar", check here first (or on NuGet for Google.Cloud.FooBar) but if it doesn't exist, look for Google.Apis.FooBar or Google.Apis.CloudFooBar.

It's unfortunate (from a confusion perspective) that there are the two styles of library with two naming conventions... but it's good from the perspective of being able to provide better libraries over time, while keeping full API coverage with the old style.
