### ISSUE TITLE
Dialogflow.v2beta1 package with beta features

### ISSUE THREAD

**Issue by alec-anikin** [googleapis/google-cloud-dotnet#2613]
Hi!

There is no package for this reference
https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2beta1

I'd like to use Environments feature but in current Dialogflow.V2 package I have to manually build session urls. Not big deal but looks fragile.

**Comment by jskeet** [comment]
I've now heard back from the team, and they don't intend to publish the V2Beta1 library for C#. The features will be in V2 sooner or later. It sounds like you have some workarounds you can use for the moment. I realize this isn't ideal for you though.

**Comment by alec-anikin** [comment]
Thanks Jon.
My workaround, can be helpful for someone else.
```csharp
DetectIntentRequest request = ...;
if (string.IsNullOrWhiteSpace(_environment)) //Draft environment                
  request.SessionAsSessionName = new SessionName(_projectId, sessionId);
else
  request.Session = $"projects/{_projectId}/agent/environments/{_environment}/users/-/sessions/{sessionId}";
```
