### ISSUE TITLE
Unable to find source code to listen to Pub/Sub messages continuously 

### ISSUE THREAD

**Issue by gurnor28** [googleapis/google-cloud-dotnet#2621]
You suggested some source code in an answer on this question:
https://stackoverflow.com/questions/46790075/how-to-listen-for-pub-sub-messages-in-an-asp-net-core-app-continuously

Link to that Git is not working? Can you please share any source code you think that can be used at enterprise level to get messages out of Pub/Sub continuously? Preferably .Net code, thanks!

**Comment by jskeet** [comment]
The class was renamed to `SubscriberClient`. It's now [here](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClient.cs).

In terms of sharing source code, I'd suggest reading the [documentation here](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.PubSub.V1/index.html) and [here](https://cloud.google.com/pubsub/docs/).

**Comment by jskeet** [comment]
Closing this now as it's not clear that more information is required. (And if it is, it may well be that it should be in the PubSub site - we can pass that request on if necessary.)
