### ISSUE TITLE
Use of TraceHeaderPropagatingHandler in .NET Core 2.1

### ISSUE THREAD

**Issue by gabrielmus** [googleapis/google-cloud-dotnet#2629]
I am using Google.Cloud.Diagnostics.AspNetCore version 3.0.0-beta06.
Due to the [change of paradigm for creating HttpClient](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1), the [following code](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNetCore/index.html) for tracing outgoing http requests via Stackdriver Trace does not align well with .NET Core 2.1 any longer:

```csharp
/// <summary>
/// The <see cref="TraceHeaderPropagatingHandler"/> is populated by dependency injection.
/// </summary>
public async Task<HttpResponseMessage> TraceOutgoing(TraceHeaderPropagatingHandler traceHeaderHandler)
{
    // Add a handler to trace outgoing requests and to propagate the trace header.
    using (var httpClient = new HttpClient(traceHeaderHandler))
    {
        return await httpClient.GetAsync("https://weather.com/");
    }
}
```
Instead, the HttpClient instance must be created via an injected `IHttpClientFactory` (and "using" statement becomes unnecessary).  
More importantly, the registration and "chaining" of `HttpMessageHandler` into a handler pipeline is supposed to be configured at Startup.cs - ConfigureServices(), for example:
```csharp
services.AddHttpClient("weather").AddHttpMessageHandler<TraceHeaderPropagatingHandler>();
```
The HttpClient infrastructure takes care of chaining the `TraceHeaderPropagatingHandler` into the handler pipeline, but in return is asking that all handlers have a null `InnerHandler`, otherwise an exception is thrown.  
Unfortunately this is exactly what happens with `TraceHeaderPropagatingHandler`

```text
System.InvalidOperationException: The 'InnerHandler' property must be null. 'DelegatingHandler' instances provided to 'HttpMessageHandlerBuilder' must not be reused or cached.
Handler: 'Google.Cloud.Diagnostics.Common.TraceHeaderPropagatingHandler'
   at Microsoft.Extensions.Http.HttpMessageHandlerBuilder.CreateHandlerPipeline(HttpMessageHandler primaryHandler, IEnumerable`1 additionalHandlers)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.&lt;&gt;c__DisplayClass10_0`2.&lt;AddTypedClient&gt;b__0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
```

This is due to the fact that an `InnerHandler` is always created by the `TraceHeaderPropagatingHandler` constructor:
```csharp
public TempTraceHeaderPropagatingHandler(
    Func<IManagedTracer> managedTracerFactory, HttpMessageHandler innerHandler = null)
{
    _managedTracerFactory = GaxPreconditions.CheckNotNull(managedTracerFactory, nameof(managedTracerFactory));
    InnerHandler = innerHandler ?? new HttpClientHandler();
}
```
The implementation of the handler should be adjusted to support the new way of managing HttpClients in .NET Core.2.1.

**Comment by amanda-tarafa** [comment]
The introduction of `IHttpClientFactory` and its consumption patterns does not mean that directly creating `HttpClient` instances with custom `HttpMessageHandler` has stopped working. Hence, the sample code you referenced (as follows) still works as expected for AspNet Core 2.1.
```
/// <summary>
/// Add a handler to trace outgoing requests and to propagate the trace header.
/// The <see cref="TraceHeaderPropagatingHandler"/> is populated by dependency injection
/// thanks to the use of the <see cref="FromServicesAttribute"/> attribute.
/// </summary>
public async Task<HttpResponseMessage> TraceOutgoing([FromServices] TraceHeaderPropagatingHandler traceHeaderHandler)
{
    using (var httpClient = new HttpClient(traceHeaderHandler))
    {
        // Any code that makes outgoing requests.
        return await httpClient.GetAsync("https://weather.com/");
    }
}
```
It's true that as our Diagnostics.AspNetCore library stands, client code cannot take advantage of the features introduced with `IHttpClientFactory`, which I agree is desirable.
I will discuss internally with the team so we can prioritize properly, taking into account that we also want to keep supporting all other ApsNetCore versions.

**Comment by gabrielmus** [comment]
Thanks for looking into this.  
Yes, creating `HttpClient` the old way still works and the Diagnostics.AspNetCore library is fine in that context.  
Sorry for making it sound more critical than it probably is, it's just that our team moved to the new features introduced with `IHttpClientFactory` to avoid the known problems (e.g. [leaking sockets](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) and [DNS changes](https://github.com/dotnet/corefx/issues/11224)) so I am a bit selfish here. 

As a temporary solution I copied your `TraceHeaderPropagatingHandler` code and changed the constructor so we can still use the Stackdriver Trace (not sure whether I am violating any licence here)

Anyways, looking forward to your new library version.

**Comment by amanda-tarafa** [comment]
No worries, we defintely want to support the recommended way of doing things, and as soon as possible, so stay tuned. I will update here with any more info and PRs soon.

**Comment by amanda-tarafa** [comment]
Closing via #2661 and #2674 . Will be included on our next beta release.

**Comment by amanda-tarafa** [comment]
This is now released!
https://www.nuget.org/packages/Google.Cloud.Diagnostics.AspNetCore/3.0.0-beta07
