### ISSUE TITLE
It's hard for users to find their logs on console.cloud.google.com.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/google-cloud-dotnet#2634]
After collecting friction logs from many people, I've observed a common issue that users suffer is that it's difficult to find their logs in console.cloud.google.com.  If the app is running locally, then they appear under Global.  If the app is running on App Engine flex, then the logs appear under App Engine.

Admittedly, this client library is far removed from the user experience of console.cloud.google.com.  But I do see an opportunity to help users avoid this pain:  Write a log statement (which appears on stdout when the user runs in development mode) that tells them exactly how to see their logs.  Something like:
```
Logs are being written to Stackdriver and can be seen at https://console.cloud.google.com/logs/viewer?resource=global
```
Like https://github.com/googleapis/google-cloud-dotnet/issues/2630, it will take some cleverness to avoid infinite recursion.

**Comment by amanda-tarafa** [comment]
Shouldn't that information be part of normal user documentation instead? We can describe the different scenarios in which logs end up under one or another "environment label".

**Comment by SurferJeffAtGoogle** [comment]
Yes, it should and it is.  But it's just really hard for users to find the logs.  3 of the 5 of us who recorded friction logs had trouble finding our logs in console.cloud.google.com.

**Comment by jskeet** [comment]
Drive-by thought: suppose our *samples* had something that wrote the URL to the console. If we expose an easy way of getting it printed to the console, but without writing to the console by default, then users following the samples will see it, but then can easily remove it once they know where to look.

Does that work, or do you think people don't follow the samples closely enough?

**Comment by amanda-tarafa** [comment]
Hi @SurferJeffAtGoogle, I'm working on this now and we were thinking of adding some more data to the URL (apart from the monitored resource) so that users can truly land on the logs being logged. This data would include the project ID, the log level, the name of the log, etc. With this info included on the URL users would only need to change on the UI the time spans they want to see logs for. Are you OK with this?

**Comment by amanda-tarafa** [comment]
@SurferJeffAtGoogle I just created #2860. Take a look and leave comments, specially if you think the snippets are enough.

**Comment by JustinBeckwith** [comment]
@jskeet the flagging of this as a P2, even though it was a feature request, was causing it to go out of SLO.  I went ahead and removed that label - just wanted to make sure it's ok with you :)

**Comment by jskeet** [comment]
@JustinBeckwith: Fine by me. I thought everything had to have a priority :)

**Comment by jskeet** [comment]
I think this is now fixed as far as we want to; it's documented at
http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNetCore/#finding-out-the-url-where-logs-are-written

It does help that we've made diagnostics easier to get started with anyway.

**Comment by jskeet** [comment]
Closing as "this is as good as we're going to get".
