### ISSUE TITLE
Firestore: Serialization fails for classes with non-public parameterless constructors

### ISSUE THREAD

**Issue by pauloevpr** [googleapis/google-cloud-dotnet#2639]
Hi,

It seems `ValueDeserializer` uses` System.Activator.CreateInstance()` to build classes for deserialization. This causes `snapshot.ConvertTo<T>()` to fail when `T` does not have a public parameterless constructor.

Since Firestore-related classes are explicitly marked with the `[FirestoreDataAttribute]`, I don't see any compelling reason not to allow non-public parameterless constructors. 

This makes even more sense when taking into consideration that, as per the latest update (beta12), non-public properties marked with the `[FirestorePropertyAttribute]` have serialization support.

**Comment by jskeet** [comment]
Yes, the intention was to allow private constructors too. Will look into this next week.

**Comment by jskeet** [comment]
This is now available in version 1.0.0-beta13.

I haven't forgotten about #2534, although I didn't spot your comment a couple of days ago - will leave an update now.
