### ISSUE TITLE
Error: A model description could not be created. Duplicate model name 'Button' was found for types 'Google.Cloud.Dialogflow.V2.Intent

### ISSUE THREAD

**Issue by jnachman123** [googleapis/google-cloud-dotnet#2683]
Error when calling anything to do with nuget package, on web api .net 

 "A model description could not be created. Duplicate model name 'Button' was found for types 'Google.Cloud.Dialogflow.V2.Intent+Types+Message+Types+Card+Types+Button' and 'Google.Cloud.Dialogflow.V2.Intent+Types+Message+Types+BasicCard+Types+Button'. Use the [ModelName] attribute to change the model name for at least one of the types so that it has a unique name." | string

**Comment by jskeet** [comment]
That sounds like an error created by ASP.NET Web API, not be the library. Please could you give a lot more context for exactly what you're trying to achieve, and what code you're trying to use to do it?

Note that if you're trying to implement a web hook, you shouldn't use default JSON parsing to do it, but hook into the protobuf JSON parsing and formatting instead, as shown in the example at https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Dialogflow.V2/index.html

**Comment by jnachman123** [comment]
Replaced the package with json and error , reoccurred. 

Closing as not due to this package.
