### ISSUE TITLE
Update documentation around custom authentication

### ISSUE THREAD

**Issue by dansiegel** [googleapis/google-cloud-dotnet#2736]
# Description

According to the [Authentication Documentation](https://cloud.google.com/docs/authentication/production) I should be able to create my own credential object and pass that into whatever client I need. Unfortunately this doesn't appear to be supported or at least it's a round about way that isn't documented for this library.

## Expected

```cs
// Create the Google Credentials
var credential = GoogleCredential.FromAccessToken(Secrets.GoogleAccessToken);

// Create the Client with a specified credential
var client = ImageAnnotatorClient.Create(credential);

// Get authenticated response
var response = client.DetectLabels(image); 
```

## Actual

Credentials must be a service account and the json file must be exported to as an environment variable. Which means that you cannot use an Access Token and this couldn't be a resource that I locate in a custom manner.

**Comment by jskeet** [comment]
Unfortunately there are several sets of client libraries with different characteristics here. There are roughly three groups:

- The autogenerated REST API clients, where you'd specify your credential in the `HttpClientInitializer` property of the `BaseClientService.Initializer` passed to the service constructor
- Wrappers for those REST API clients, for Storage, BigQuery and Translate, where you can pass the credentials into the `Create` method exactly as per the documentation you specified
- gRPC-based client libraries such as the Image API you're using

This last one is indeed fiddly - but you don't *have* to use a JSON file. You can create a `Channel` based on your credentials and pass that into `ImageAnnotatorClient.Create`, along with the endpoint. There's a sample [here](https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis). It's definitely *not* as easy as we'd like it to be (see #1576) and I have some time allocated in the next couple of weeks to try to vastly improve this situation.

We clearly need to update the documentation you linked to, however. It'll be slightly tricky to do so in a consistent way, but I'll see what I can do. It *may* be worth waiting until I've  improved the way of providing alternative credentials before we update the documentation, to save churn.

**Comment by jskeet** [comment]
The ClientBuilder work is now rolling out - but at the same time, a lot of the documentation is moving around anyway, which makes all of this trickier.

I'm going to leave this issue open until I've got the ClientBuilder work documented *somewhere*, but at that point I'll close it as this repo probably isn't the right place for the "we should consolidate all auth docs" problem. (We're still definitely interested in getting it done though!)

**Comment by jskeet** [comment]
Closing for now - the documentation for client builders is at https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis
The larger question of consolidating our auth docs is ongoing - but there's a renewed focus on docs at the moment, so I'm hopeful we'll get there.

**Comment by jengstro2** [comment]
I do not want (cannot) to use env variable as "GOOGLE_APPLICATION_CREDENTIALS", as in the pubber you can have multiple credentials/endpoints inside same software. So, how actually I can feed programmaticly the credential.json information when building PublisherServiceApiClient?

**Comment by jskeet** [comment]
@jengstro2: See the link from the previous comment: https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis

**Comment by jengstro2** [comment]
In a relation to use with PublisherServiceApiClient.Create() ?

**Comment by jskeet** [comment]
Use `new PublisherServiceApiClientBuilder { ... }.Build()`.
