### ISSUE TITLE
Stackdriver Error Reporting should display the contents of Exception.Data.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/google-cloud-dotnet#2738]
**Describe the solution you'd like**

.NET exceptions have a Data dictionary, where I can add any tags I want.  For example:

```cs
            // Generate an error that Stackdriver should capture
            try {
                // [START error_reporting_setup_dotnetcore_force_error_controller]
                throw new Exception("Generic exception for testing Stackdriver Error Reporting");
                // [END error_reporting_setup_dotnetcore_force_error_controller]                
            } catch (Exception e) {
                e.Data.Add("flavor", "raspberry");
                throw;
            }
```

However, the Data dictionary is not visible in stackdriver error reporting:
![image](https://user-images.githubusercontent.com/11778530/49171664-dc316700-f2f3-11e8-809f-8bc6152465c2.png)

It would be useful to display the dictionary in Error Reporting, so I can effectively annotate exceptions.

**Comment by amanda-tarafa** [comment]
I think this is doable, I'll take a look.

**Comment by amanda-tarafa** [comment]
Hi @SurferJeffAtGoogle, in a few minutes I'll submit a PR that addresses this FR. Just wanted to add a few clarification notes.

The [ErrorEvent](https://cloud.google.com/error-reporting/reference/rest/v1beta1/ErrorEvent) resource does not define a property in which to include extra information similar to `System.Exception.Data` so you will never see this information on the Error Reporting section of the Cloud Console. This does not depend on us on the client side but on the API definition and the UI design.
Luckily, an ErrorEvent is a partial view of a [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) which defines a property `labels` more suited to store the data in `System.Exception.Data` in a more structured way that can be used for filtering etc.. So to see this information (once the PR is submitted and released) you can click on the View Logs link on the Error Reporting UI as shown below:
![image](https://user-images.githubusercontent.com/14878252/49877939-67dfe300-fe1e-11e8-86d6-1052190330fa.png)
 You then will se something like this:

![image](https://user-images.githubusercontent.com/14878252/49878057-ad9cab80-fe1e-11e8-80a8-66c93590d5c7.png)

**Comment by amanda-tarafa** [comment]
Blocked, waiting for [original requester](https://medium.com/@mikedube_/excellent-article-have-you-found-a-way-to-annote-error-trace-679727ec10fc) to give their opinion on the several options we have.

**Comment by amanda-tarafa** [comment]
Moving this issue to our backlog (#2822 ) given that the original requester hasn't confirmed what option better addresses their use case.
@SurferJeffAtGoogle we can reopen if the original requester gets back to us or if we get similar requests for this feature from other users.
