### ISSUE TITLE
Possibility to Copy one source file into multiple destinations using Google.Cloud.Storage.V1

### ISSUE THREAD

**Issue by SiarheiSurnin** [googleapis/google-cloud-dotnet#2747]
For .Net client library Google.Cloud.Storage.V1 even in 2.3.0-beta04 there is no way to perform multiple coping of files from one key to another key. I can perform only  single file copy operation.

public virtual Task<Apis.Storage.v1.Data.Object> CopyObjectAsync(string sourceBucket, string sourceObjectName, string destinationBucket = null, string destinationObjectName = null, CopyObjectOptions options = null, CancellationToken cancellationToken = default(CancellationToken));

I it will be good if instead of single string destinationObjectName, I can pass
IEnumerable<string> destinationObjectName , so I can copy 1 object into multiple locations with 1 request to .net library( actual requests will be packed into M so it will be more optimal from http side)

As a alternative way, you can open batch possibility for Rest API
https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch
(Currently it is disabled for upload and copy operation)

If you are afraid of malicious usage of api, you can provide milit for this operation - like 100 max copy destinations for example.

**Comment by jskeet** [comment]
I can't change what the API itself allows. Each copy request is cheap - it's not like it's physically copying the data to the client and back. I'd suggest just making multiple requests, in parallel if you want to.

**Comment by SiarheiSurnin** [comment]
The problem that we are performing copy > 100 items per 1 web request.
And even if I collect all items in Task<Object_From_Google_Storage_Api_Type> it took unacceptable long time to wait until all items were copied.

In general , during API development google should provide some flexibility level for api usage.
Allow only copy by 1 file, it is not farsightedly from google point of view. 
We should have possibility to perform batch operation using Google.Cloud.Storage.V1 client.

**Comment by jskeet** [comment]
I can certainly mention it, but I don't think "copying a single file to 100+ destinations and needing to do that in a very short space of time" is a common use case.

**Comment by jskeet** [comment]
I've asked internally. I'll close this now as there's no work to do in the client library unless the underlying API supports it.
