### ISSUE TITLE
Retry stream operations for Firestore

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#2760]
In issue #2721 it was noted that sometimes the server returns a status code of Unavailable when reading documents. We don't (currently) have transparent retry for streaming operations; this has been implemented over the top in Node, so we may wish to examine that implementation.

**Comment by pauloevpr** [comment]
I have seen this error in my ASP.NET Core 2.1 Web API running on Google Cloud App Engine Flexible. The application uses Firestore 1.0.0-beta13 with default authentication.

Stackdriver reports that my application has seen the following Firestore Unavailable errors:

- Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="The service is temporarily unavailable.")
- Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="OS Error")
- Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="The datastore operation timed out, or the data was temporarily unavailable.")

This seems to happen completely randomly when either reading or writing document(s).

**Comment by jskeet** [comment]
Thanks for the additional information. Related GAX issue: https://github.com/googleapis/gax-dotnet/issues/227

I'll need to work with @chrisdunelm on this - I'm afraid it won't be until January at this point.

**Comment by jskeet** [comment]
(I'm going to change it to a bug though, as I think it's reasonable to expect that we *would* retry this.)

**Comment by pauloevpr** [comment]
Great. Thank you.

**Comment by chrisdunelm** [comment]
Re-reading the gax bug (https://github.com/googleapis/gax-dotnet/issues/227), I'm not sure that this can be fixed in the gax layer. It's not clear to me if it's possible to detect a connection failure without reading some data, which (probably) cannot be done in the general case in gax.
This may need to do something similar to the node implementation.

**Comment by jskeet** [comment]
Right - I'll need to look into what Node does, and in which situations. (For example, it should be safe to retry for reads, but writes are harder to determine.)

**Comment by jskeet** [comment]
This is now released in 1.0.0-beta19 - @pauloevpr if you're able to see whether this fixes the problem for you, it would be appreciated.
Note that we do *not* retry write operations, as that wouldn't be safe. The change *only* affects reading documents, and only when reading them directly (not via queries).
