### ISSUE TITLE
Dialogflow gRPC incomplete responses with no details as to why 

### ISSUE THREAD

**Issue by HStuart18** [googleapis/google-cloud-dotnet#2780]
Using gRPC and the C# SDK for dialogflow streaming detect intent in an ASP.NET Core app, I occassionally have a situation where I do not receive a full query result. I have read a similar SO question with the same issue, but it was caused by an audio problem, I don't think that is my case since this issue only manifests every 50 or so calls. I can't easily replicate the issue in a Console Application because whenever I try, I never encounter the error. I have enabled logging in my application which has provided some help but I haven't received any API erros on the GCP console either.

NOTE: All my intents have a webhook enabled. However, for the requests with this error, Dialogflow History has no log of it, so obviously nor does my webhook backend. The part that confuses me the most, is that I do get a transcript result (so the transcription works), but I don't get an isFinal recognition result when I encounter this error.

Regular response:

    { \"recognitionResult\": { \"messageType\": \"TRANSCRIPT\", \"transcript\": \"yeah\" } }
    { \"recognitionResult\": { \"messageType\": \"TRANSCRIPT\", \"transcript\": \"yeah\" } }
    { \"recognitionResult\": { \"messageType\": \"END_OF_SINGLE_UTTERANCE\" } }
    { \"recognitionResult\": { \"messageType\": \"TRANSCRIPT\", \"transcript\": \"yeah\", \"isFinal\": true, \"confidence\": 0.891504765 } }
    { \"responseId\": \"...\", \"queryResult\": { \"queryText\": \"yeah\", \"parameters\": { }, \"allRequiredParamsPresent\": true, \"fulfillmentMessages\": [ { \"payload\": { ... } } ], \"intent\": { \"name\": \"...", \"displayName\": \"Yes_Intent\" }, \"intentDetectionConfidence\": 1, \"diagnosticInfo\": { \"webhook_latency_ms\": 100 }, \"languageCode\": \"en-au\" }, \"webhookStatus\": { \"message\": \"Webhook execution successful\" } }
Error causing response:

    { \"recognitionResult\": { \"messageType\": \"TRANSCRIPT\", \"transcript\": \"yeah\" } }
    { \"recognitionResult\": { \"messageType\": \"TRANSCRIPT\", \"transcript\": \"yeah\" } }
    { \"recognitionResult\": { \"messageType\": \"END_OF_SINGLE_UTTERANCE\" } }
    { \"queryResult\": { \"languageCode\": \"en-AU\" } }
Currently, the only details that make it to my log file is when there is a gRPC error. I need to be able to log the actual gRPC requests and responses (info and debug level, not only error level), not just the streamng detect intent responses. How can I log these details to further troubleshoot my problem? Is there anything I can use within the Client Library?

**Comment by jskeet** [comment]
It sounds like this is unlikely to be a client library issue - which means it's unlikely that I'll be able to help, unfortunately. (If there's something I've missed that suggests this *is* a client library issue, please let me know!)

I suspect you're more likely to get help at the [Dialogflow support forum](https://productforums.google.com/forum/#!forum/dialogflow) as the Dialogflow team will be monitoring that. (Maintainers of this repository only know details of the client library aspect.)

**Comment by HStuart18** [comment]
Okay, thanks for the advice, I will get in contact with them. Is there any verbose logging I can use throught this client library that might help?

**Comment by HStuart18** [comment]
Actually, this may be a related issue and could help solve the above one. I have the following code:

    StreamingDetectIntentRequest request = new StreamingDetectIntentRequest
    {
        Session = new SessionName("project", "session").ToString(),
        SingleUtterance = false,
        QueryInput = new QueryInput()
        {
            AudioConfig = new InputAudioConfig()
            {
                AudioEncoding = Google.Cloud.Dialogflow.V2.AudioEncoding.Linear16,
                SampleRateHertz = 16000,
                LanguageCode = "en-AU",
            },
        },
    };

    var streamingCall = sessionsClient.StreamingDetectIntent();
    await streamingCall.WriteAsync(request);
    Task responseHandler = Task.Run(async () =>
    {
        IAsyncEnumerator<StreamingDetectIntentResponse> responseStream = streamingCall.ResponseStream;
        while (await responseStream.MoveNext(default(CancellationToken)))
        {
            StreamingDetectIntentResponse response = responseStream.Current;
            _log.LogInformation("gRPC response: " + response.ToString());
        }
    });

    using (FileStream fileStream = new FileStream(@"C:\inetpub\wwwroot\wwwroot\maintenanceclip.wav", FileMode.Open))
    {
        var buffer = new byte[32 * 1024];
        int bytesRead;
        while ((bytesRead = await fileStream.ReadAsync(buffer, 0, buffer.Length)) > 0)
        {
            await streamingCall.WriteAsync(new StreamingDetectIntentRequest()
            {
                InputAudio = Google.Protobuf.ByteString
                    .CopyFrom(buffer, 0, bytesRead)
            });
            await Task.Delay(500);
            _log.LogInformation("sending audio data ");
        };
    }
    //This block here sends an HTTP request to a URL which creates a Dialogflow context and initialises some variables. It may be interfering with the above gRPC call I am not sure.
    using (var requestMessage = new HttpRequestMessage(HttpMethod.Get, "http://35.196.241.189/webhook/initial"))
    {
        requestMessage.Headers.Add("sessionId", "session");
        await Clients.httpClient.SendAsync(requestMessage);
    }

    await streamingCall.WriteCompleteAsync();
    await responseHandler;

This code is in the same project but is not the same code as the code that receives the incomplete query results. This code runs every hour or so in the background just to "make sure everything is working". However, around every 1 in 20 calls. It throws the error:

    "Grpc.Core.RpcException: Status(StatusCode=OutOfRange, Detail=\"While calling Cloud Speech API: Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time.\"

Maybe the Dialogflow team have some logs I can look into?

**Comment by HStuart18** [comment]
That's what was wrong. I needed the code to execute before my SessionsCLient was created. Thanks for the help. Now on to sifting through some log files!
