### ISSUE TITLE
PubSub: Consider updating Grpc dependency

### ISSUE THREAD

**Issue by lkts** [googleapis/google-cloud-dotnet#2781]
Hi, 

I am debugging my application which subscribes to PubSub. I see that sometimes if there is an exception `StartAsync` method of `SubscriberClient` never returns.

I think that i am hitting https://github.com/grpc/grpc/issues/14777 because stacktrace in one of threads looks like this:
```
- Monitor.Enter() (!)
- Grpc.Core.Internal.AsyncCallBase.Cancel() (!)
- CancellationTokenSource stuff
- SubscriberClientImpl.StopCompletionAsync()
```

This issue was fixed in version 1.15 of Grpc.Core (https://github.com/grpc/grpc/pull/16440) but PubSub package is still on 1.13.1.
https://github.com/googleapis/google-cloud-dotnet/blob/e8f43966e271490bfbb612c714589c2897a769a9/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.csproj#L28

#### Environment details

  - Linux
  - .NET Core 2.2
  - Google.Cloud.PubSub.V1 1.0.0

#### Steps to reproduce

  1. Call `SubscriberClient.StartAsync` multiple times in environment where it will result in exception.

Is it possible to update the dependency? 
Thanks.

**Comment by lkts** [comment]
Yes, I can do this, but i thought it is worth to create an issue.

**Comment by jskeet** [comment]
Yup, absolutely - it just means it's not quite as urgent :)
