### ISSUE TITLE
FirestoreData or FirestoreProperty support for value type tuples

### ISSUE THREAD

**Issue by gnpretorius** [googleapis/google-cloud-dotnet#2787]
## Problem
As part of your documents in Firestore, you will often have multiple nested objects. In most cases, these objects will be defined as classes within your solution, however in some cases these might simply be  container objects holding a subset of data to simplify queries. In this latter scenario, value type tuples are great as it avoids you cluttering your solution with tons of classes. an example: 

## Example
Using the old course and student nugget, you might have a sub collection within a course called "EnrolledStudents" which is a list of student id's. It would be handy to store the name, surname and major of each student so you don't have to link back to the main student object. This class could look as follows: 

```
    [FirestoreData]
    public class EnrolledStudent
    {
        [FirestoreProperty]
        public string StudentId { get; set; }
        [FirestoreProperty]
        public DateTime EnrollmentDate { get; set; }

        public (string Name, string Email, string Major) StudentInfo;
    }
```

Currently you cannot decorate the tuple with FirestoreProperty or FirestoreData. As you can see, this avoids you having to create the "StudentInfo" class which is essentially just a subset of the Student class. And in other cases you might only want Name & Email.

## Other options

You could just list the properties as part of the main object i.e. StudentName, StudentEmail, StudentMajor and will work as expected, however it's less tidy and concise. 

Let me know if unclear or more info is needed (or if this is in fact already possible) 

P.S. Great work on this library and Firestore in general.

**Comment by jskeet** [comment]
Hmm. One tricky aspect of this is that `ValueTuple` isn't available in the frameworks we target. We'd either need to add a dependency on it, or detect its use via reflection at execution time and know how to construct it with reflection too. The latter may well be a reasonable approach, in fact - although it's relatively tricky to get the names out of tuple types like this, and it would be particularly hard without having compile-time access to the attributes used to provide the names.

We *could* take a dependency on the `System.ValueTuple` NuGet package, but I've seen some issues with that in terms of versioning, and I'd *prefer* not to if possible.

I'll leave this open as a feature request, but I don't think we're likely to implement it *imminently*.

**Comment by gnpretorius** [comment]
Thanks for the feedback @jskeet 

It would appear the `System.ValueType` addition is already under consideration by yourself (taken from [here](https://jskeet.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore.Data/furtherwork.html))

> `Update(DocumentReference documentReference, params (string path, object value)[] updates)` Required users to be aware of C# 7 tuples, but then it's pretty nice. (It also adds a dependency on System.ValueTuple, but that shouldn't be a big deal.)

It's not an urgent requirement, more a nice to have. I'll take a look and see if it's something I can help contribute on (time permitting) 😄 

Cheers

**Comment by jskeet** [comment]
Yup, it's definitely an interesting option. I think I'll need to discuss any concerns about ValueTuple dependencies with the rest of my team - we probably want to work out a policy on this across all libraries.

**Comment by jskeet** [comment]
I've just been looking at this again, and I think to make it reasonable in terms of "bang-for-buck" we'd have to make it pretty limited:

- Only for attributed properties
- No maps or lists etc - just "a property that's a tuple"; we could probably handle nullable versions too.
- Possibly only support for up to 7 elements, at least to start with, as the naming gets tricky after that.

With those limitations, do you think it's worth the effort? I'd quite like to either get this done, or put it on our backlog of "we're not actively looking at this at the moment, but it's just possible we will in the future" features.

**Comment by gnpretorius** [comment]
Thanks for the update @jskeet 

Those constraints work well for our use cases. Anything more than that and it would make sense to have proper class representations of the property. 

As for effort vs. reward, difficult to answer. As mentioned, there are workarounds for this. However, with the capabilites that firestore provides and the nature of noSQL databases, this would be a handy "feature" and would make the code more concise and give some needed flexibility.

Hope that helps. 

Cheers
G

**Comment by jskeet** [comment]
Thanks for the quick response. I'll prototype it to see how neatly it falls out, then we can work out whether it's worth the complexity.

**Comment by jskeet** [comment]
I need to write some docs for this, then I'll create a release with all the new conversion code in it.
