### ISSUE TITLE
Using pubsub emulator with SubscriberClient

### ISSUE THREAD

**Issue by Eldar-Ahmadov** [googleapis/google-cloud-dotnet#2790]
Good day,

I was using "Google.Cloud.PubSub.V1 Api  Version="1.0.0-beta20" which allowed me  to switch between pubsub emulator and the “real” cloud pubsub as per code below:

                    var emulatorHostAndPort = Environment.GetEnvironmentVariable("PUBSUB_EMULATOR_HOST");

			var subscriberApiClient = string.IsNullOrEmpty(emulatorHostAndPort)
				? SubscriberServiceApiClient.Create(CreateChannelWithCredentials(credentialPath))
				: SubscriberServiceApiClient.Create(new Channel(emulatorHostAndPort, ChannelCredentials.Insecure));

			var subscriber = SubscriberClient.Create(subscription.SubscriptionName, new[] { subscriberApiClient });
In the code above I’m able to pass **subscriberApiClient** with the preconfigured Channel pointing to pubsub emulator  host/port to SubscriberClient.Create method, and then use SubscriberClient which allows for simpler api specifically StartAsync method which I use quite a lot throughout the codebase.

After upgrading to "Google.Cloud.PubSub.V1" Version="**1.0.0**" (not beta) I cannot find any corresponding way of being able to pass a preconfigured Channel which would allow me to make a switch similar to how I was doing it using older api; the SubscriberClient.Create method has been replaced with SubscriberClient.CreateAsync which takes SubscriberClient.ClientCreationSettings and SubscriberClient.Settings but I wasn’t able to identify which of those can be used to use pubsub emulator (using a Channel or otherwise).

Is there anything I may have missed? I’d greatly appreciate your response.

**Comment by Eldar-Ahmadov** [comment]
Thanks for your prompt response. 

Are there any plans to use an "PUBSUB_EMULATOR_HOST" environment variable to take care of it automatically, i.e. how it's done in Python api, where you only need to set the environment variable?

**Comment by chrisdunelm** [comment]
Closing. Please leave a further comment if you think it needs re-opening.

**Comment by chrisdunelm** [comment]
The `ServiceEndpoint` is the hostname and port of the service. So for the emulator I would expect the code to be something like: `new Google.Api.Gax.Grpc.ServiceEndpoint(uri.Host, uri.Port);`
