### ISSUE TITLE
Can't Install Google.Cloud.Language.V1 in Unity

### ISSUE THREAD

**Issue by bhylak** [googleapis/google-cloud-dotnet#2793]
Has this library ever been used with Unity? I am unable to install it.

#### Environment details

  - OS: macOS 10.14.2
  - .NET version: 4.X
  - Package name and version: Google.Cloud.Language.V1 

#### Steps to reproduce

  1. Install via Nuget
  2. Click Run

![image](https://user-images.githubusercontent.com/19956321/50861129-c472e700-1365-11e9-9de0-6df3741ce5fe.png)

**Comment by amanda-tarafa** [comment]
We don't support Unity at the moment and we don't have an ETA for it, you can read more about it in #2219.
I will close this issue now but feel free to add comments here or in #2219.
