### ISSUE TITLE
BigQuery: Add support for creating clustered tables

### ISSUE THREAD

**Issue by jaredhughes1012** [googleapis/google-cloud-dotnet#2823]
Problem:
The BigQuery library does not support creating tables with clustering enabled.

Solution:
There is already a class named Clustering that exists in various places in the library. It would be best if an instance of that class could be added as a property to CreateTableOptions as it is implemented for TimePartitioning.

Context:
Library version: Google.Cloud.BigQuery.V2 1.3.0-beta06

We are using central BigQuery tables as a template for creating new tables at runtime. We pull down these template tables and use their schemas to create a new table with a different project, dataset, and/or id. We'd like to extend our logic to copy time partitioning (which is already supported) and clustering.

This request appears to be similar to the feature request for time partitioning https://github.com/googleapis/google-cloud-dotnet/issues/692

**Comment by jskeet** [comment]
Thanks for the feature request - I'll take a look at this tomorrow.

**Comment by jskeet** [comment]
It looks like clustering is a beta feature, which could be changed in a backwardly-incompatible way. I'll need to consult with the BigQuery team about timing - I want to make sure we're not in a position where I want to release a GA version of this library, while it still depends on beta features. I believe the library change itself will be pretty straightforward.
