### ISSUE TITLE
Suggestion for additional Firestore sentinel attributes

### ISSUE THREAD

**Issue by codeaid** [googleapis/google-cloud-dotnet#2830]
I've been successfully using the Firestore library and so far most of the features have been a pleasure to use. One thing that I feel could be slightly improved is mapping of specialised document fields, such as `Id`, `CreateTime` and `UpdateTime`.

Currently the `FirestoreProperty` attribute allows us to specify which user properties should be stored in the document and which shouldn't, however, there is no way to automatically map the time document was created or its identifier.

The project where this library is used in is a rather standard web API with a plethora of CRUD endpoints. Because it returns models for use in an SPA I need them to include the ID, creation time and last updated time.

All my models implement an `IModel` interface that has the following signature:

```csharp
public interface IModel
{
    string Id { get; set; }
    DateTime? Created { get; set; }
    DateTime? Modified { get; set; }
}
```

I also have a custom `Store<T>` class that manages my Firestore data and has methods like the following ones (amongst others):

```csharp
public abstract class Store<T> : IStore<T> where T : class, IModel
{
    public virtual async Task<T> CreateAsync(T model, string documentId = null) { ... }
    public virtual async Task<T> UpdateAsync(T model) { ... }
    public virtual async Task<T> FindByIdAsync(string id) { ... }
}
```

Because there is no way to directly map specific `DocumentSnapshot` properties to the model, this is what I ended up doing in my `CreateAsync` method:

```csharp
var document = string.IsNullOrWhiteSpace(documentId)
    ? Collection.Document()
    : Collection.Document(documentId);

var writeResult = await document.CreateAsync(model, cancellationToken);
var dateTime = writeResult.UpdateTime.ToDateTime();

// Populate model fields from the newly created document.
model.Id = document.Id;
model.Created = dateTime;
model.Modified = dateTime;

return model;
```

This I suppose is not too bad as it allows me to avoid an extra read which is a priced operation. So instead all my properties on the model are mapped with `FirestoreProperty` and I populate `Id`, `Created` and `Modified` manually. One thing I'd like to have is a `CreateTime` on the `WriteResult` (at least when returned from `CreateAsync`). It doesn't make that much sense syntactically that I get an update time when creating a document. Or, if not, at least rename it to be operation-agnostic (e.g. `WriteTime`).

Similarly, I was updating `Modified` property in the `UpdateAsync` method until today, when I finally understood how the `ServerTimestamp` attribute works (more on that in P.S.) and realised I don't need to set it manually. That seems to work as expected so no complaints there.

For all read operations I have an extension method which does the following:

```csharp
public static T ToModel<T>(this DocumentSnapshot document) where T : class, IModel
{
    var model = document.ConvertTo<T>();

    model.Id = document.Id;
    model.Created = document.CreateTime?.ToDateTime();
    model.Modified = document.UpdateTime?.ToDateTime();

    return model;
}
```

Again, not ideal but it works.

What I would love to have, however, is a set of sentinel attributes that would be applied during `ConvertTo` and allow us to do something like this:

```csharp
public class MyCustomModel : IModel
{
    [FirestoreProperty, DocumentIdentifier]
    public string Id { get; set; }

    [FirestoreProperty, ServerTimestampCreated]
    public DateTime? Created { get; set; }

    [FirestoreProperty, ServerTimestamp]
    public DateTime? Modified { get; set; }
}
```

These attributes would then automatically map document properties to the relevant model properties.

I have a suspicion it might not always be possible to do this (I noticed that `WriteResult` for `CollectionReference.SetAsync` doesn't have time created, only `UpdateTime`) but as `Id` is always(?) present on the document after a create/update operation, it would be one thing less to maintain in the consumer code.

If my assumptions are correct and it's technically not possible to populate the time created, is there a way to pass a model I want to persist and a dictionary of overrides to apply? The reason I'm asking is if it was possible I could specify that my `Created` property is `FieldValue.ServerTimestamp`, e.g.:

```csharp
var writeResult = await document.CreateAsync(model, new {
    Created = FieldValue.ServerTimestamp,
}, cancellationToken);
```

_Is that even the way field value has to be used? This is one of the things that is not really clear from the documentation and all examples online are conveniently about the Firebase JS client._

P.S.
As promised a small remark about the documentation. It's taken me quite a long time to realise what this sentence means:

> Attribute indicating that a property value should be ignored on creation and modification operations, using the server time for the commit that modifies the document.

I'm not arguing that it's correct English but for someone like me, who's not a native English speaker it only makes sense when I understand how the attribute works. It would've made much more sense if it was something along the lines of

> Attribute indicating that a property value will be ignored during creation and modification operations, and will instead be automatically populated with the server time of the operation.

On a side note - I know this is not StackOverflow but I would very much be interested in hearing your thoughts about my approach with populating the properties. Am I doing something stupid? Is there something you'd change or avoid?

Thanks!

**Comment by jskeet** [comment]
Thanks for the detailed feature request.

Currently all the sentinel properties we have are dictated by the API itself - they're all applied server-side. I'd rather not start mixing and matching the logic for client-side vs server-side here, which means I'll need to pass this on as a feature request to the server team. I'd also suggest that the Firestore team would want to decide whether this functionality should be generally supported - it probably doesn't make sense for it *only* to work in C#. They *may* decide that it's okay to do the ID property on the client side. This does complicate all the serialization and deserialization quite significantly though - currently only the *values* provided by the API are involved in serialization, without the context of which document they came from. Would you also be suggesting that the ID property isn't part of the document snapshot data itself? It all gets a little tricky.

I'm not sure whether creation time is even tracked on the server side - that one may not be possible, as you mentioned.

I'll let the team know about the feature request, and see what they think - in particular, they have more experience of what other users have requested in other languages.

In terms of the documentation issue, I'll have a go at rewording them - although I *suspect* that what you've written with the hindsight of already understanding the feature at that point may not have made much more sense to you back when you didn't understand it. I suspect I need to make the whole comment longer. I'll create a PR and cc you in it.

**Comment by codeaid** [comment]
Thanks for the prompt and detailed reply!

> I'd rather not start mixing and matching the logic for client-side vs server-side here

Completely agree. Didn't know sentinel properties were applied on the server-side.

> it probably doesn't make sense for it _only_ to work in C#

Again, I agree. It would not make any sense to add it to just one language knowing that they are available in other languages too. 

> It all gets a little tricky.

I can see where you're coming from. Without knowing much about the internal workings of the library I obviously can't make any suggestions and, perhaps, leaving it as is is the cleanest solution when it comes to it, however, having a document identifier sentinel property would be nice.

I based my assumptions and suggestions on `DocumentSnapshot`, which has `Id`, `CreateTime` and `UpdateTime` properties, hence I thought that was data coming from the server and you simply populated the local snapshot with it. 
show 
> I'm not sure whether creation time is even tracked on the server side
Where it does it come from in that case? The `CreateTime` on the snapshot gets populated with the actual time of creation.

Other than that, what are your thoughts on supporting document property overrides during persistence? I know what I suggested is rather ugly but it was just to demonstrate the idea. Currently if the application is using models decorated with Firestore attributes (instead of using dictionaries) then it's very convenient that one can pass the model into methods like `CreateAsync` or `UpdateAsync` and it gets automatically serialised.

The problem I'm having at the moment is that if a property is decorated with the `ServerTimestamp` attribute then it _always_ gets updated with the latest value from the server, when the created time should obviously only be set once.

Maybe one way of doing it would be to support a constructor parameter in the `ServerTimestamp` attribute allowing users to specify the types of operations during which it should be invoked? E.g. `[ServerTimestamp(On = Operation.Update)]` or `[ServerTimestamp(On = Operation.Create)]` and it would default to e.g. `Operation.Always`.

Again, it's not really an issue and I've worked around it by setting my `Created` property value manually, however, the problem is that the time I set locally and server timestamp would/could be different depending on the local time of the server hosting the application. Solution of course is to never even use `ServerTimestamp` and set all dates locally but that means that I'm missing out on a rather handy feature.

**Comment by jskeet** [comment]
One issue with the conditional aspect is that we don't always know when a document is being created. If you call `DocumentReference.SetAsync`, that will either create or update. Basically all of this is best handled server-side. I think the ideas make sense, but I don't know how they'll be considered or prioritized by the Firestore team.

**Comment by codeaid** [comment]
I suspected that it might be a problem. Either way, I just wanted to get my ideas out there to see if any of what I wanted was possible. I guess time will tell if the server team even considers any of the suggestions so all we can do is wait. In the meantime - thanks for passing the ideas on to them!

**Comment by jskeet** [comment]
I've now merged support for document references via a new `FirestoreDocumentIdAttribute` type (which assigns to either a `string` or `DocumentReference` property. I'm asking about create/update times.

**Comment by jskeet** [comment]
Just as a heads-up, I've made another request for discussion of the created/last-updated bits with the team.

**Comment by jskeet** [comment]
(Blocked as in "waiting for team feedback")

**Comment by jskeet** [comment]
This suggestion has been approved by the Firestore team, so I'm going to try implementing it. We'll also support the read time, for completeness.

**Comment by jskeet** [comment]
Hi @codeaid,

Could you have a look at #3354 and see whether that looks like the kind of thing you'd expect from this request?
It dropped out fairly simply in the end, so I'm hopeful that if this does what you want, we can get it in and released quite soon.
