### ISSUE TITLE
C# SignedUrl not supporting Customer encryption key

### ISSUE THREAD

**Issue by Copyleaks** [googleapis/google-cloud-dotnet#2841]
I running c# NuGet SDK (latest) and doing two tasks. 

1) upload file to storage and encrypt it by customer key:
```
var key = EncryptionKey.Create(Convert.FromBase64String(base64Key));
StorageClient client = StorageClient.Create(ConfigurationManager.GoogleCredential);
var stream = File.OpenRead(@"test.txt");
client.UploadObject("mybucket", "test.txt", "text/plain", stream, new UploadObjectOptions
{
	EncryptionKey = key
});
```
This step is working without any problem and I can see my file from the GCP dashboard.

2) Make a signed url to give public access to this file. Here I'm stuck. It's looks like this scenario is not covered by the sdk.

Why it's not provided by the C# SDK? Seems like [possible](https://cloud.google.com/storage/docs/access-control/signing-urls-manually) via the bucket API.

**Comment by jskeet** [comment]
Apologies for the delay - somehow this had slipped past me.
I'll have a look at this tomorrow.

**Comment by jskeet** [comment]
Looking at this again, I don't *think* it's possible to generate a URL that means the user doesn't need to know the encryption key. If they *do* know the encryption key, they can specify the appropriate headers with their GET request later. From the documentation you linked to:

> However, do not specify the x-goog-encryption-key or x-goog-encryption-key-sha256 headers, even if the requests to access the associated object will use them.

You'd want to specify `x-goog-encryption-algorithm:AES256` as a header to be signed, and we could make that easier - but I don't think it meets the use case you described.

Fundamentally, my understanding is that when using a customer key, Google Cloud Storage doesn't "know" the content of the file itself at all at rest - it can only decrypt it when the key is given in another request. You wouldn't want that key to be encoded as part of the signed URL, as it's intended to be secret. You could distribute the signed URL publicly and the key in another fashion, but that's not the use case I think you're talking about.

Does that make sense?

**Comment by frankyn** [comment]
+1 to @jskeet, the client generates the signed URL, but you will need to provide the necessary signed header `x-goog-encryption-algorithm:AES256` for a customer supplied encryption keys  encrypted object. 

In the HTTP GET request that uses the signed URL the encryption key and hash headers are required.

Piecing this together into an example: 

```C#
// Generate a new encryption key
string key = EncryptionKey.Generate();

// Create a new HttpRequestMessage that will be used to make the subsequent GET request.
HttpRequestMessage request = new HttpRequestMessage { Method = HttpMethod.Get };

// Modify request to include the encryption key fields for CSEK headers:
// x-goog-encryption-key, x-goog-encryption-key-sha256, x-goog-encryption-algorithm
key.ModifyRequest(request);

// Create a signed URL for the following bucket/object.
// The Sign method will not sign headers: x-goog-encryption-key, x-goog-encryption-key-sha256
//  because the GCS service does not include these headers in the signature.
string bucketName = "bucket-name";
string objectName = "object-name";
signedUrl = signer.Sign(bucketName, objectName, TimeSpan.FromHours(1), HttpMethod.Get);

// Set the request URI to the signedUrl
request.RequestUri = new Uri(signedUrl);

// Execute request 
HttpResponseMessage response = httpClient.SendAsync(request);
string content = await response.Content.ReadAsByteArrayAsync();
```

**Comment by jskeet** [comment]
Closing as I believe we've explained why it's infeasible as requested, and there's been no further information.
