### ISSUE TITLE
the .net Firsestore sdk converts ENUM to Integer, but the Android SDK converts enums to String

### ISSUE THREAD

**Issue by alexdoan102** [googleapis/google-cloud-dotnet#2842]
the .net Firsestore sdk converts ENUM to Integer, but the Android SDK converts enums to String.

we need a way, on .net to store enum as string, to match the compatibility with our android app.
==> is there an custom attribute we an use to tell .net to store enums as string ?  (like android sdk)

**Comment by jskeet** [comment]
I'll need to talk with the Firestore team about this; I'll get into it on Monday.

At the moment you *could* do it with custom serialization, but it's probably worth us providing that as a "built-in custom serializer" that you can apply either on an individual property or on the type itself.

**Comment by jskeet** [comment]
#2853 shows how this can be done with a custom converter. It's very likely that we'll provide that ourselves over time, but we'll probably want to be careful about the API for it - we may want other attributes to allow custom names etc. For the moment, using a custom converter yourself (with 1.0.0-beta18 which is being built now) should unblock you.

**Comment by alexdoan102** [comment]
I added the custom converter and it works. Will this customer converter be part of the  main library?
 ==> I installed 1.0.0.-beta19, but I dont see the custom converter [FirestoreEnumNameConverter] in int.

**Comment by jskeet** [comment]
@alexdoan102: It's likely that we'll include it eventually, but I didn't want to commit to an API just yet, as we're approaching 1.0 GA. There are various things we may want to include, such as the ability to apply an attribute to enum values to control the naming, and potentially case insensitivity. The main thing I wanted to prove in #2853 was that we *could* go to GA without including this, without that requiring a breaking change later on.

**Comment by steveoh** [comment]
> such as the ability to apply an attribute to enum values to control the naming, and potentially case insensitivity

please please please allow for case insensitivity!

**Comment by jskeet** [comment]
> > such as the ability to apply an attribute to enum values to control the naming, and potentially case insensitivity
> 
> please please please allow for case insensitivity!

I don't anticipate making any changes to this at the moment - but there's nothing to stop you from creating your own very similar custom converter which is case insensitive; it's not like the converter has to be integrated deeply within the rest of the library.

**Comment by steveoh** [comment]
It's just a boolean value passed to enum.tryparse and it feels goofy to duplicate the built in to add `true, ` but ok.
