### ISSUE TITLE
BigQuery API: Getting value by name from BigQueryRow throws exception for NULLABLE fields

### ISSUE THREAD

**Issue by Zhenya-Ren** [googleapis/google-cloud-dotnet#2845]
#### Environment details

  - OS: Windows 10 64 bit
  - .NET version: .Net Framework 4.5
  - Package name and version:
Google.Cloud.BigQuery.V2.dll 1.2.0
Google.Api.Gax.Rest 2.5.0
Google.Apis.Bigquery.v2 1.36.1.1404
Google.Api.Gax  2.5.0
Google.Apis.Auth 1.36.1
Newtonsoft.Json 12.0.1.22727
Google.Apis 1.36.1
Google.Apis.Core 1.36.1

#### Steps to reproduce

  1. Here is the code snippet:

            BigQueryTable table = GetBigQueryTable();
            PagedEnumerable<TableDataList, BigQueryRow> result = table.ListRows();
            foreach (BigQueryRow row in result)
            {
                foreach (var columnName in this.columns)
                {
                    var value = row[columnName];
                    // do something
                }
            }

columnName is an existing field name, which is not null

  2. If the field is NULLABLE and has a value, the following exception is thrown at row[columnName]:

System.ArgumentNullException: Value cannot be null.
Parameter name: name
   at Google.Api.Gax.GaxPreconditions.CheckNotNull[T](T argument, String paramName)
   at Google.Cloud.BigQuery.V2.EnumMap`1.ToValue(String apiValue, String paramName)
   at Google.Cloud.BigQuery.V2.BigQueryRow.ConvertSingleValue(Object rawValue, TableFieldSchema field)

3. If the field is REQUIRED or NULLABLE and the value is null, then all works as expected.

4. Currently using the following workaround:

var value = row.RawRow.F[index].V; 

This gives the correct value, though we then need to convert it ourselves, as it is String for most datatypes. Also requires to resolve the index first, instead of using the name directly.

**Comment by jskeet** [comment]
I can't currently reproduce this. Here's what I've tried:

```csharp
using Google.Cloud.BigQuery.V2;
using System;
using System.Linq;

namespace Issue2845
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args.Length == 0)
            {
                Console.WriteLine("Please provide a project ID");
                return;
            }
            var client = BigQueryClient.Create(args[0]);
            var dataSetId = "Issue2845";
            var tableId = "DemoTable";

            var dataSet = client.GetOrCreateDataset(dataSetId);
            var schema = new TableSchemaBuilder
            {
                { "value", BigQueryDbType.Float64, BigQueryFieldMode.Nullable }
            }.Build();
            var table = dataSet.GetOrCreateTable(tableId, schema);

            table.InsertRow(new BigQueryInsertRow { ["value"] = 15.5 });

            var rows = table.ListRows().ToList();
            Console.WriteLine($"Row count: {rows.Count}");
            foreach (var row in rows)
            {
                Console.WriteLine(row["value"]);
            }
        }
    }
}
```

That reported the value with no problem.

From the stack trace, it looks like the problem would be if the response didn't have schema information in - it's happening before we get as far as the value itself.

Could you try the above program yourself, and see whether that works for you, or throws the same exception? We basically need to reproduce the issue, at which point it will probably be easy to fix.

If you could also try Google.Cloud.BigQuery.V2 version 1.3.0-beta07 just to see if something has changed (I don't think it has, but you never know) that would provide useful information.

**Comment by Zhenya-Ren** [comment]
I ran your program and yes, it gave no error. However, I managed to reproduce the issue once I created the table first in the WebUI, manually. Here are my steps to reproduce:

1. Go to Google BigQuery Web UI (beta).
2. Click on the dataset, click "Create table".
3. Choose "Empty table", click "Add field", type in name, leave STRING, NULLABLE, click Create table.
4. Run in the Web UI: insert zhenya.TestTableUI (`value`) values ("value");
5. Now, run the updated code:

class GoogleIssueTest
    {
        public static void Main(BigQueryClient client, string projectId)
        {
            var dataSetId = "zhenya";
            var tableId = "TestTableUI";
            var dataSet = client.GetOrCreateDataset(projectId, dataSetId);
            var table = dataSet.GetTable(tableId);

            var rows = table.ListRows().ToList();
            Console.WriteLine($"Row count: {rows.Count}");

            foreach (var row in rows)
            {
                Console.WriteLine(row["value"]); // Same error occurs here
            }
        }
    }

**Comment by jskeet** [comment]
It looks like it's a difference in how GetTable returns the schema:

Schema returned from table created with original UI (or in code):

```text
  "schema": {
    "fields": [
      {
        "name": "value",
        "type": "STRING",
        "mode": "NULLABLE"
      }
    ]
  },
```

Table created with beta UI:

```text
  "schema": {
    "fields": [
      {
        "name": "value",
        "type": "STRING"
      }
    ]
  },
```

I can *potentially* change the library code to default the mode, or it may be that the BigQuery team needs to fix this server-side (to avoid it breaking other clients).

**Comment by Zhenya-Ren** [comment]
Great! Thanks for looking into it!

**Comment by jskeet** [comment]
The fix is now merged - accidentally, in fact, as I meant to create a PR. (A colleague is going to review the commit directly.)

I'll then create a 1.3.0-beta08 release. Will that be okay for you, or do you need a GA release of the library to work with? (I don't know of any issues with the library at the moment, I just wasn't planning on releasing 1.3.0 imminently. I can do so if you have a policy against using betas, but I'll probably want to just let a beta 1.3.0 release "bake" for a few days before doing a GA release.)

**Comment by Zhenya-Ren** [comment]
Yes, we do need a GA release, few days would be great! Thanks!

**Comment by Zhenya-Ren** [comment]
One more question, perhaps not really related. I tested with NUMERIC and GEOGRAPHY values (required), which don't exist in BigQueryDbType. Trying to read like row["myNumeric"] I get the following exception: 

System.ArgumentException Value NUMERIC is undefined in BigQueryDbType

Same for GEOGRAPHY. 

Is this expected behavior?

**Comment by jskeet** [comment]
We don't support GEOGRAPHY yet. NUMERIC is supported in version 1.3 - if you try the same test with 1.3.0-beta07, I'd expect it to work.

**Comment by Zhenya-Ren** [comment]
Ok, thanks!

**Comment by jskeet** [comment]
Version 1.3.0 has now been released.
