### ISSUE TITLE
.NET Firestore SDK write c# Int property to to Firsestore as Int64, but on windows .net it default to Int32

### ISSUE THREAD

**Issue by alexdoan102** [googleapis/google-cloud-dotnet#2897]
.NET Firestore SDK write c# "Int" property to  Firsestore as Int64, but on windows .net it default to Int32.
When I do a select projection and just retrieve the INT property, i get an invalid cast exception

CollectionReference collectionRef = _firestoreDb.Collection("CategoryModel")
Query = Query.Select("FieldPath[position]")

When I convert the snapshot doc to  var xdictfirstdoc = firstdocument.ToDictionary();
 ==> and try to retrieve the field xdictfirstdoc["position"]
     ==> this field xdictfirstdoc["position"] is Int64  ==> TRUE

 it writes the INT as INT64 to firestore
 but when i do a select projection, and just get that field,  my windows .Net see it as INT32 not INT64,

**Comment by jskeet** [comment]
I'm finding it hard to understand your question at the moment. In particular:

> but when i do a select projection, and just get that field, my windows .Net see it as INT32 not INT64,

When you do a select projection of what, exactly? Could you provide a complete example? It's definitely expected that integers are serialized as `Int64` values in Firestore, as that's its only integer type. What's not clear is under what circumstances you're seeing an `Int32` - I *suspect* it's somewhere that Firestore isn't involved at all.

**Comment by jskeet** [comment]
Closed due to lack of feedback. Please add another comment with more information if you want this to be looked at again.
