### ISSUE TITLE
Flaky behavior of GZip download

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#2898]
In the Storage integration tests, `DownloadObjectTest.DownloadGzippedFile` is flaky. Most of the time it works, but sometimes we're seeing the download fail due to the hash being invalid:

```text
Incorrect hash: expected 'T1s5RQ==' (base64), was 'yZRlqg==' (base64)
```

I'm going to skip it in our integration tests for now, but we need more work to try to reproduce it and capture the requests. (I've tried, but failed so far.)

**Comment by weiming-myob** [comment]
A quick question, can you confirm this is not a flaky test, but actual bug in production, please?

**Comment by jskeet** [comment]
Well I can't reproduce it reliably, but I see no reason to believe it's a problem in the test code - it's *very* simple usage of the production code.
What's unclear at the moment is whether there's some weird situation which changes the headers sent by the client (which could provoke this) or whether it's a weird server-side issue.

**Comment by jskeet** [comment]
I'm not aware of seeing this problem since April, so I'll close the issue now.
