### ISSUE TITLE
UploadObjectAsync not working when async with Task.WhenAll on Ubuntu

### ISSUE THREAD

**Issue by khanghyxda** [googleapis/google-cloud-dotnet#2930]
#### Environment details

  - OS: Ubuntu 16.03
  - .NET version: NetCore 2.1
  - Package name and version: 2.3.0

#### Steps to reproduce

 I upload all files in folder to Storage. I try used UploadObjectAsync. Host Window work fine, but publish to Ubuntu 16.03 host, files not upload to Storage.
My Code
public async Task UploadFolder(string folder, string key)

    {
        string contentRootPath = _hostingEnvironment.ContentRootPath;
        var credential = GoogleCredential.FromJson(System.IO.File.ReadAllText(contentRootPath + "/Configs/storage.json"));
        StorageClient storageClient = StorageClient.Create(credential);
        var filePaths = Directory.GetFiles(folder, "*",
                                     SearchOption.AllDirectories);
        var tasks = new List<Task>();
        var listObjectName = new List<string>();
        var streams = new List<FileStream>();
        foreach (string path in filePaths)
        {
            var stream = new FileStream(path, FileMode.Open);
            string contentType;
            new FileExtensionContentTypeProvider().TryGetContentType(path, out contentType);
            var objectName = "design/" + key + path.Replace(folder, "").Replace("\\", "/");
            listObjectName.Add(objectName);
            tasks.Add(storageClient.UploadObjectAsync( // await here, ubuntu work ok
                bucket: CloudConfig.BUCKET,
                objectName: objectName,
                contentType: contentType,
                source: stream,
                options: new UploadObjectOptions { PredefinedAcl = PredefinedObjectAcl.PublicRead }
            ));
            streams.Add(stream);
        }
        await Task.WhenAll(tasks);
        streams.ForEach(stream =>
        {
            stream.Dispose();
        });
    }
![image](https://user-images.githubusercontent.com/5491573/54021370-5ca91300-41d3-11e9-9a58-a3efd2fadcfe.png)

Thanks!

**Comment by jskeet** [comment]
This was also raised as https://github.com/googleapis/google-api-dotnet-client/issues/1347, which is now closed. Closing this too.
