### ISSUE TITLE
Expose IncludeTrailingDelimiter or give access to api rest parameters

### ISSUE THREAD

**Issue by pepjo** [googleapis/google-cloud-dotnet#2941]
**Is your feature request related to a problem? Please describe.**
When making a request (for example: `ListObjects`) I'd like to set some parameters of the request that are currently not available in the options object (for example: `ListObjectsOptions`). In particular, I would like to access `IncludeTrailingDelimiter`.

 **Describe the solution you'd like**
I've seen in the documentation that this is a parameter of `ObjectsResource.ListRequest`. The best thing to do would be to expose it in `ListObjectsOptions`.

 **Describe alternatives you've considered**
If it's not possible it would be nice to have a method `SetRequestParameters` for this kind of options that are not implemented yet.

For example: `options.SetRequestParameter<T>(string parameter, T value)`

 **Additional context**
Using `Google.Cloud.Storage.V1` v `2.3.0`

**Comment by jskeet** [comment]
I'd definitely rather add a specific option than adding a general approach, as I can see things interacting badly when things get complex. I'll try to create a PR for this today.

**Comment by jskeet** [comment]
This is now merged into master. I expect I'll be doing a new beta Storage release over the next couple of weeks, so unless this is massively urgent for you, I'd prefer to wait until then to pick it up - is that okay?

**Comment by pepjo** [comment]
Can wait a couple of weeks. Thanks for addressing this so fast!

**Comment by jskeet** [comment]
This is in Google.Cloud.Storage.V1 version 2.4.0-beta01, which should be on nuget.org very soon.
