### ISSUE TITLE
Consider making Google.Cloud.Diagnostics.AspNetCore 3.0 only support ASP.NET Core 2.x

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#2959]
Currently Google.Cloud.Diagnostics.AspNetCore targets netstandard1.5, netstandard2.0 and net46. They have different dependencies, like this:

```xml
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.5' OR  '$(TargetFramework)' == 'net46' ">
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="1.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="1.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="1.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.2" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.0.1" />
  </ItemGroup>
```

This strikes me as confusing and potentially error-prone. It means that anyone using .NET desktop will end up with dependencies on ASP.NET Core 1.0, even if their application may target ASP.NET Core 2.x, for example. In reverse, it's *possible* that someone using .NET Core 2.0 may still actually be using ASP.NET Core 1.x, which this configuration would fail with.

Proposal: *just* have a target framework of netstandard2.0, and just use the existing ASP.NET Core 2.x dependencies (possibly updating them).

This is obviously a hugely breaking change - which is why it's important to make the decision *before* Google.Cloud.Diagnostics.AspNetCore hits 3.0 GA.

Cc users for comment:

- @SurferJeffAtGoogle
- @iantalarico 
- @henkmollema 
- @amanda-tarafa

**Comment by henkmollema** [comment]
I agree. This is confusing for library consumers as well as contributors. Targetting just `netstandard2.0` is fine by me.

**Comment by iantalarico** [comment]
+1

**Comment by amanda-tarafa** [comment]
Late to the party, but +1, I've always been confused by this as well.
