### ISSUE TITLE
run bash command

### ISSUE THREAD

**Issue by DenisGribanov** [googleapis/google-cloud-dotnet#2962]
how to use this library to run bash command on my instance ?

**Comment by jskeet** [comment]
Could you clarify which package you're talking about, and what kind of instance you're trying to run bash on? (This repository hosts the source code for a *lot* of packages.)

**Comment by DenisGribanov** [comment]
I created an instance virtual machine using Google.Apis.Compute.v1.Data.InstancesResource.InsertRequest. Can I connect to the created virtual machine and execute the bash command using Google.Apis.Compute?

**Comment by jskeet** [comment]
Okay, for future reference, Google.Apis.Compute.v1 is hosted in https://github.com/googleapis/google-api-dotnet-client - I appreciate it's not always obvious which repository is the relevant one.

I don't know the Compute API well - but I don't *think* there'd be anything to run a bash command. I suggest you look through the documentation at https://cloud.google.com/compute/docs/reference/rest/v1/ - which is what I'd basically be doing.
There are other APIs for scheduling tasks, if that's relevant - but I don't know of anything to run a bash command on an existing instance.
