### ISSUE TITLE
Log4Net StackdriverAppender: Use %property values in custom labels

### ISSUE THREAD

**Issue by rkalasky** [googleapis/google-cloud-dotnet#2983]
**Is your feature request related to a problem? Please describe.**
Attempting to use %property syntax on custom label values. It shows up in Stackdriver like this:

```
labels: {
  Key:  "%property{AccountID}"   
...
 }
```
I want the value inserted at runtime, similar to what I can do with the message:

`<conversionPattern value="%property{AccountID}` ...

 **Describe the solution you'd like**
I'd like to label my logs with some context from the application.

```
<customLabel>
      <key value="AccountID" />
      <value value="%property{AccountID}" />
</customLabel>
```

 **Describe alternatives you've considered**
Put the dynamic data into the log message directly.

 **Additional context**
- [I think this is where a replacement would happen.](https://github.com/googleapis/google-cloud-dotnet/blob/b36872c110349c3d73106d333396c9e24dc494e2/apis/Google.Cloud.Logging.Log4Net/Google.Cloud.Logging.Log4Net/GoogleStackdriverAppender.cs#L315)
- I saw that adding new labels dynamically was prevented completely in #1036. I would just be looking to change the values dynamically.

**Comment by jskeet** [comment]
Assigning to Chris to consider this.

**Comment by bryanroth** [comment]
@chrisdunelm Any updates on considering this feature request?

**Comment by chrisdunelm** [comment]
@rkalasky @bryanroth It isn't entirely obvious how to support this.
The patterns require parsing by `PatternLayout` (which is essentially a collection of `PatternConverter`s).
We cannot re-use any already-present `PatternLayout`, as there is no guarantee there will be one at all; and even if there is it is not possible to use multiple patterns within a single `PatternLayout` instance.
So we'd need to create a new `PatternLayout` instance for each label, which could be done, but I cannot see any simple way of allow this layout to be configured (beyond the pattern), so no custom converters would be possible.
The use of patterns within custom labels would be gated on a flag, something like `UsePatternWithinCustomLabels` - the default of `false` would preserve existing behaviour.

Please let me know your views on this, or whether you can see a better way to achieve this.

**Comment by rkalasky** [comment]
I would be totally fine with this behavior being gated behind a flag.

My understanding of the log4net internals is novice level, but I don't think custom converters are necessary. I would be happy with the built-in %property{...} (PropertyPatternConverter?) syntax.

We're putting this data into the log message directly today using the above syntax.

**Comment by nbelley** [comment]
Any news on this? It would be required for us to put the %property{log4net:HostName} in one label to filter our logs.

**Comment by bryanroth** [comment]
@chrisdunelm Any idea when this change will get published?

**Comment by chrisdunelm** [comment]
@bryanroth It's already in beta on nuget: https://www.nuget.org/packages/Google.Cloud.Logging.Log4Net/2.4.0-beta01

**Comment by bryanroth** [comment]
@chrisdunelm Brilliant. Thanks for letting me know. Is there a good way to see the release notes for updates to this nuget package?
