### ISSUE TITLE
Make it easier to init Firestore with GoogleCredentials

### ISSUE THREAD

**Issue by hiranya911** [googleapis/google-cloud-dotnet#2993]
Currently, the `FirestoreDb` class can only be initialized with application default credentials. If I want to specify a service account explicitly, I have to use a more low-level API:

```
using Google.Cloud.Firestore.V1;
using Google.Apis.Auth.OAuth2;
using Grpc.Auth;
using Grpc.Core;

// Load a service account explicitly
var serviceAcct = GoogleCredential.FromFile("path/to/serviceAcct.json");
Channel channel = new Channel(
           FirestoreClient.DefaultEndpoint.Host, FirestoreClient.DefaultEndpoint.Port,
           serviceAcct.ToChannelCredentials());
FirestoreClient client = FirestoreClient.Create(channel);

FirestoreDb db = FirestoreDb.Create(project, client);
```

Some other GCP clients provide an API that accepts both a project ID and a `GoogleCredential` to make this flow easier. See [BigQuery API](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.BigQuery.V2/api/Google.Cloud.BigQuery.V2.BigQueryClient#Google_Cloud_BigQuery_V2_BigQueryClient_Create_System_String_Google_Apis_Auth_OAuth2_GoogleCredential_) for example.

Following this pattern, please provide a `FirestoreDb.Create(string, GoogleCredential)` overload to make this type of initialization easier.

**Comment by sarensw** [comment]
As mentioned in #2349, it's now a lot easier to do this (just adding the info here because this is the first issue shown in Google when searching for C# Firestore Client auth). Check out https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis
