### ISSUE TITLE
Logs created with Stackdriver integration can't be exported to BigQuery

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#3011]
The logs we create have a struct called `format_parameters` with fields which have names that are just numbers, as well as `{OriginalFormat}`. These are passed to us by ASP.NET Core, but we could probably parse the strings if necessary.

Currently any field name that's *just* a digit is converted into `_` when exported to BigQuery, which leads to duplicate fields, so the entry can't be exported at all.

A couple of options:

- Add `_` as a prefix to the field name
- "Understand" the `{OriginalFormat}` and numbered fields, and handle them separately, e.g. as an array for the values and a separate field for the original format.

These would change the format of any existing logs, so I'll at least need to look at how long we've been formatting parameters like that.

cc @henkmollema who may have thoughts on this.

**Comment by jskeet** [comment]
Okay, so I've done a bit of digging, and:

- The parameters were added in 24473e16838d9e56d98b08d8cf8845c9cad89397 on April 3rd 2018 - so they've been in for about a year. (Release 3.0.0-beta01 was on April 16th 2018)
- This was *not* in 2.0, and 3.0 hasn't been released, so we at least wouldn't be breaking a GA release

I'm going to prototype at least one PR, maybe two, for the different options. I want to at least check that adding _ as a prefix would give us a valid export.

**Comment by henkmollema** [comment]
Extended support for parameters from logging scopes were added later: https://github.com/googleapis/google-cloud-dotnet/pull/2385.  I'm not sure where the fields with numbers come from. The structure of a log entry should look like this:

```
message: "message Corge"
scope: "first 42 => second Baz => "
format_parameters: 
  "Qux": "Corge"
  "{OriginalFormat}": "message {Qux}"
parent_scopes:
  [
    {
      "Bar": "Baz"
      "{OriginalFormat}": "second {Bar}"
    }
    {
      "Foo": "42"
      "{OriginalFormat}": "first {Foo}"
    }
  ]
```

Does the array `parent_scopes` result in fields with numbers?

**Comment by henkmollema** [comment]
Looking through the logs I do see the numbers appear:

![image](https://user-images.githubusercontent.com/1521207/55954114-1e819200-5c5e-11e9-97c5-a6a3e706bfd5.png)

**Comment by jskeet** [comment]
@henkmollema: Interesting - I haven't been looking at parent scopes at all. It was the format_parameters that I've seen as numbers, and that's presumably just because I've used them that way in my Noda Time logging. (I'd been treating the format string as a regular string.Format-style string.)
If that's the case, then a) I can fix Noda Time myself with the current version; b) it's less of a breaking change to add the underscore at the start for "just digits" keys, as it will affect fewer users.

The `parent_scopes` part should be okay, as that's a genuine array, rather than an object with numbers as keys.

**Comment by henkmollema** [comment]
I see, option B sounds good to me.  👍
