### ISSUE TITLE
Could not load file or assembly System.Interactive.Async

### ISSUE THREAD

**Issue by radmikulka** [googleapis/google-cloud-dotnet#3032]
I recently updated to newest version of firestore 1.0.0-beta20 (from version beta11) - everything runs ok on windows but when I upload my app (dotnet core 2.1 app) to linux with installed dotnet core 2.1 than I get following error

`
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Interactive.Async, Version=3.2.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Google.Cloud.Firestore.Query.GetSnapshotAsync(ByteString transactionId, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Google.Cloud.Firestore.Query.GetSnapshotAsync(ByteString transactionId, CancellationToken cancellationToken)
`

I also tryed to install nuget pacage System.Interactive.Async, but wit no success. (I tryed several versions)

**Comment by jskeet** [comment]
Please could you show me what your project file looks like so I can check all the dependencies? I'll try to reproduce this tomorrow.

**Comment by radmikulka** [comment]
Sorry it look that problem was on my side - Reinstalling of firestore nuget fixed it

**Comment by jskeet** [comment]
Hooray - my favourite kind of issue :)
