### ISSUE TITLE
FirestoreDataAttribute and FirestorePropertyAttribute are really useful, and would be even more useful with one an Id Attribute.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/google-cloud-dotnet#3042]
The class I'm storing in firestore looks like this:
```cs
    [FirestoreData]
    public class Book
    {
        [Key]
        [BindNever]
        public string Id { get; set; }

        [Required]
        [FirestoreProperty]
        public string Title { get; set; }

        [FirestoreProperty]
        public string Author { get; set; }

        [Display(Name = "Date Published")]
        [DataType(DataType.Date)]
        [FirestoreProperty]
        public DateTime? PublishedDate { get; set; }

        [FirestoreProperty]
        public string ImageUrl { get; set; }

        [DataType(DataType.MultilineText)]
        [FirestoreProperty]
        public string Description { get; set; }
    }
```

But I don't see a way to bind the `Id` field to Firestore's document Id, so I have to write code to propagate the id from the snapshot to my Book class.

For example:

```cs
            List<Book> bookList = new List<Book>();
            var snapshot = await _books.Offset(nextPageStart).Limit(pageSize)
                .GetSnapshotAsync();
            foreach (DocumentSnapshot docSnapshot in snapshot.Documents) 
            {
                var book = docSnapshot.ConvertTo<Book>();
                book.Id = docSnapshot.Id;
                bookList.Add(book);
            }
            return new BookList()
            {
                Books = bookList,
                NextPageToken = bookList.Count == pageSize ? 
                    (nextPageStart + pageSize).ToString() : null
            };
```

Instead, I wish I could write:
```cs
            List<Book> bookList = new List<Book>();
            var snapshot = await _books.Offset(nextPageStart).Limit(pageSize)
                .GetSnapshotAsync();
            return new BookList()
            {
                Books = snapshot.Documents.Select(doc => doc.ConvertTo<Book>()),
                NextPageToken = bookList.Count == pageSize ? 
                    (nextPageStart + pageSize).ToString() : null
            };
```

I imagine another property I could add to the Book class definition like:

```cs
    [FirestoreData]
    public class Book
    {
        [Key]
        [BindNever]
        [FirestoreId]
        public string Id { get; set; }
```

**Comment by jskeet** [comment]
So just to check that I understand this correctly:

- This would be one way, given that the document ID needs to be passed to Create etc methods already
- This would only be in `DocumentSnapshot.ConvertTo`, as it should only apply on a document basis, not arbitrary fields
- It would be reasonable to expect this to be a *top-level* field, and require it to be a string

I'll start prototyping that to see what the feasibility is like. We'll need to talk to the Firestore team as well - I think the C# annotations are somewhat more fully featured than those in other languages, and the team may be concerned about growing the disparity further. (To be clear, I completely see how this would be useful, and it's part of #2830 already.)

One other question is what the ID should look like. I can imagine three options here:

- The full document path, including the database it's part of (projects/foo/databases/bar/documents/col1/doc1/col2/doc2)
- The database-documents relative path (col1/doc1/col2/doc2)
- Just the final ID (doc2)

We could potentially support all of these, with an enum in the attribute - but I'm interested to know which of them you were expecting.
-

**Comment by jskeet** [comment]
Okay, if I've understood correctly, then #3045 is roughly how things would look. There are a few details to iron out, but it looks technically feasible.

@SurferJeffAtGoogle: Please confirm this is what you were looking for; if it is, the next step is to check with the Firestore team that they'd be happy for us to include it.

**Comment by SurferJeffAtGoogle** [comment]
Yes.  #3045 LGTM.  Thank you!

**Comment by jskeet** [comment]
Righto - will get in touch with the team. (The timing may be sensitive as we're hoping to get the GA of the Firestore library out - we'd need to work out whether this should get in before or after... but we'll see.)
