### ISSUE TITLE
TraceHeaderRegex does not match X-Cloud-Trace-Context header from HTTP(S) load balancer

### ISSUE THREAD

**Issue by steven-unity** [googleapis/google-cloud-dotnet#3055]
#### Environment details

  - OS: n/a
  - .NET version: netcoreapp2.2
  - Package name and version: Google.Cloud.Diagnostics.Common 3.0.0-beta12

#### Steps to reproduce

  1. Our AspNetCore web service is behind a GCP HTTP(S) load balancer
  2. Load balancer adds the X-Cloud-Trace-Context header with a value like f5526cbaa0faf6582ef3cbf0c6a2c7ff/7553744403246890094
  3. Notice the value is not terminated with a semi-colon or include o=TRACE_TRUE
  4. The TraceHeaderRegex in Google.Cloud.Diagnostics.Common (TraceHeaderContext.cs, lines 46 - 47) is @"^([A-Fa-f0-9]{32})/([0-9]+);(o=([0-3]))?$"
  5. Notice the regex requires the semi-colon (o=TRACE_TRUE is optional)
  6. So the regex does not match the header value and so the trace and spanId from the header is not used (TraceHeaderContext.cs, lines 79 - 83)
  7. Therefore, a new trace and spanId are generated within AspNetCore, losing the association with the load balancer trace.
  8. Fix is to make the semi-colon optional in the regex.

**Comment by jskeet** [comment]
Thanks for reporting the issue - will investigate it next week. (It'll be Tuesday, as Monday is a public holiday in the US.)

**Comment by jskeet** [comment]
Confirmed, I see a similar header value. I'll dig into where that regex came from, and work out exactly how we should handle it.

**Comment by jskeet** [comment]
I've merged the fix for this - thanks for doing so much of the diagnostic work for me beforehand :)
I'll start a release of all the Google.Cloud.Diagnostics packages, and ping this issue again when it's done.

**Comment by jskeet** [comment]
The new version is now released. Please let me know if this hasn't fixed the issue for some reason.
