### ISSUE TITLE
Can we push multiple folders into GCS using c#

### ISSUE THREAD

**Issue by Ganesh1991** [googleapis/google-cloud-dotnet#3066]
Can we push multiple folders into GCS using c#

**Comment by jskeet** [comment]
Do you mean in a single method call? No, we don't do anything recursively like that. You'd need to iterate over all the files you want to upload, calling `UploadObject` or `UploadObjectAsync` for each of them.

**Comment by Ganesh1991** [comment]
Thanks jsKeet.

**Comment by Ganesh1991** [comment]
Hi jskeet,
Using gsutil (below command) we can upload folder into the GCS.
gsutil -m cp -a public-read -R folder_big gs://bucket_name
Do we have a similar option in c# or node js?

**Comment by jskeet** [comment]
I don't know about Node.js, but there's definitely *not* an equivalent of that in C#. For Node, you could ask on https://github.com/googleapis/nodejs-storage - although I can't see anything in the sample file.

**Comment by Ganesh1991** [comment]
ok thanks
