### ISSUE TITLE
Implement Firestore numeric transforms

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#3077]

**Comment by tommed** [comment]
Sorry, as I'm new to this repo and it wasn't clear from PROCESS.md or travis.yml, but when will this appear in the nuget repo please? The packages haven't been updated in 2-months and I'm really hoping to use `Increment` in my .net project. M thanks.

**Comment by jskeet** [comment]
I've just received an email comment asking when this will appear in NuGet, but I can't see it here... not sure what's going on. I'll try to do a release next week.
