### ISSUE TITLE
Documentation for Dialogflow web hooks on ASP.NET

### ISSUE THREAD

**Issue by kobelinh24** [googleapis/google-cloud-dotnet#3096]
I'm currently having a problem of sending a comprehensible response from my webhook API to Actions on Google. Below is the code sample where I set up the webhook response: 
```
var response = new WebhookResponse
            {
                FulfillmentText = text,
                OutputContexts =
                {
                    new Context
                    {
                        Name = $"{request.Session}/contexts/action_selecting",
                        Parameters = parameters,
                        LifespanCount = 1
		    }
		}
	    }
	return response;
```
This works perfectly when I want to form a response to Dialogflow, but not Actions on Google. I also noticed that it can still work with Actions on Google if I remove the outputcontext from the response.
In the following image is the error I found on Actions on Google from the log:
![image](https://user-images.githubusercontent.com/17856738/58327456-f4f88080-7e2f-11e9-952b-ccec46a07bc8.png)

**Comment by jskeet** [comment]
Are you returning the response *directly* from your action? You need to use a specific formatter to convert it to JSON - see http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Dialogflow.V2/ for details on how to return a `WebhookResponse` from ASP.NET Core.
I *suspect* that's the issue.

**Comment by kobelinh24** [comment]
> Are you returning the response _directly_ from your action? You need to use a specific formatter to convert it to JSON - see http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Dialogflow.V2/ for details on how to return a `WebhookResponse` from ASP.NET Core.
> I _suspect_ that's the issue.

This is what I used for generating a response within the controller, which has been working quite well for any other circumstances:
```
[HttpPost]
        public async Task<JsonResult<WebhookResponse>> Post([FromBody] JObject json)
        {
            WebhookRequest webhookRequest = _jsonParser.Parse<WebhookRequest>(json.ToString());
            WebhookResponse response = null;
            string actionName = webhookRequest.QueryResult.Intent.DisplayName;
            if (actionName != null && _actions.ContainsKey(actionName))
            {
                var action = _actions[actionName]();
                response = await action.Execute(webhookRequest);
            }
            return this.Json(response, new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() });
        }
```

**Comment by jskeet** [comment]
While that will work for *some* messages, it won't work for all, due to the way that protobuf works. Please try using the code from that page instead.

**Comment by kobelinh24** [comment]
> While that will work for _some_ messages, it won't work for all, due to the way that protobuf works. Please try using the code from that page instead.

I am not working with .NET Core, therefore the code snippet did not work for me in this case. Already had a look on that previously though. Do you have any recommendation for this?

**Comment by jskeet** [comment]
You can use the same code to generate JSON, then just return it directly as a JSON result. The important part is that you use the Protobuf JSON serialization code rather than Json.NET.

**Comment by kobelinh24** [comment]
```
public async Task<string> Post([FromBody] JObject json)
        {
            WebhookRequest webhookRequest = _jsonParser.Parse<WebhookRequest>(json.ToString());
            WebhookResponse response = null;
            string actionName = webhookRequest.QueryResult.Intent.DisplayName;
            if (actionName != null && _actions.ContainsKey(actionName))
            {
                var action = _actions[actionName]();
                response = await action.Execute(webhookRequest);
            }

            var responseJson = response.ToString();
            return responseJson;
        }
```
This is what I have tried if I am understanding your reply correctly, and this did not work. Can I have a proper answer in this case?

**Comment by jskeet** [comment]
There are a few issues with that code:

- I would advise you to accept the string directly in the body, rather than accepting a `JObject` and then converting it back into JSON
- That could could easily throw a NullReferencException if there's no QueryResult, or no QueryResult.Intent
- If you don't find an action with the right name, it will also throw a NullReferenceException as `response` will be null.

Having seen your edit, it looks like Web API is taking the string response and formatting that *as JSON*. You need to stop it from doing that. I don't know "old school" Web API well enough to know what to recommend, but I *suspect* you could create an HttpResponseMessage with the right status code (200) and content, as well as a content type of "text/json".

It's worth being aware that the maintainers of this repository aren't experts on Actions on Google or Dialogflow - we aim to make sure that our client libraries can make appropriate requests to APIs, but there are too many APIs for us to be experts in all of them. If this ends up being very specific to Actions on Google, we may need to find somewhere with folks who are more knowledgeable about that. But first let's make sure we've got the right JSON back to the server...

**Comment by jskeet** [comment]
Some sample code for the response - untested, but I'd *hope* it would be okay...

```csharp
var response = new HttpResponseMessage(HttpStatusCode.OK)
{
    Content = new StringContent(Json)
    {
        Headers = { ContentType = new MediaTypeHeaderValue("text/json") }
    }
};
```
Then return that from your method.

**Comment by kobelinh24** [comment]
> There are a few issues with that code:
> 
> * I would advise you to accept the string directly in the body, rather than accepting a `JObject` and then converting it back into JSON


Regarding your comment, I understand that using JObject is not a proper workaround, however this was one of the trouble I had at the beginning:

- If I use the string directly in the body, like 
`public async Task<JsonResult<WebhookResponse>> Post([FromBody] string json)` , then the string would be empty
- If I use the WebhookRequest from the body, like 
`public async Task<JsonResult<WebhookResponse>> Post([FromBody] WebhookRequest request)` , then if the WebhookRequest from Dialogflow has parameter attribute, then the parameter would be empty

Only the JObject made a difference where I still get something from the request body and the parameter fields do not disappear.

**Comment by jskeet** [comment]
Okay, let's punt the `JObject` pararameter part for the moment. I understand why having `WebhookRequest` as the parameter fails, and I guess there may be special handling for a string parameter.

If you can get at the raw request within the controller, you could use the other part of the code from the link earlier:

```csharp
WebhookRequest request;
using (var reader = new StreamReader(Request.Body))
{
    request = jsonParser.Parse<WebhookRequest>(reader);
}
```

... you may need to change exactly how you obtain the request content stream, based on how you get the request.

But anyway, it sounds like the response is more problematic for now. We can always come back to the request part later.

**Comment by kobelinh24** [comment]
```
[HttpPost]
        public async Task<HttpResponseMessage> Post([FromBody] JObject json)
        {
            WebhookRequest webhookRequest = _jsonParser.Parse<WebhookRequest>(json.ToString());
            WebhookResponse webhookResponse = null;
            string actionName = webhookRequest.QueryResult.Intent.DisplayName;
            if (actionName != null && _actions.ContainsKey(actionName))
            {
                var action = _actions[actionName]();
                webhookResponse = await action.Execute(webhookRequest);
            }

            var response = new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(webhookResponse.ToString())
                {
                    Headers = {ContentType = new MediaTypeHeaderValue("text/json")}
                }
            };
            return response;
        }
```
Thanks to your recommendation, this works like a charm at the moment! Both for Dialogflow and Actions on Google. Now I believe the most problematic issue is solved.

**Comment by kobelinh24** [comment]
> Okay, let's punt the `JObject` pararameter part for the moment. I understand why having `WebhookRequest` as the parameter fails, and I guess there may be special handling for a string parameter.
> 
> If you can get at the raw request within the controller, you could use the other part of the code from the link earlier:
> 
> ```cs
> WebhookRequest request;
> using (var reader = new StreamReader(Request.Body))
> {
>     request = jsonParser.Parse<WebhookRequest>(reader);
> }
> ```
> 
> ... you may need to change exactly how you obtain the request content stream, based on how you get the request.

Put the response aside, I would kindly ask if we can somehow find a solution for the request as well, as I totally agree with you that using JObject is really consuming.

**Comment by jskeet** [comment]
Really glad to hear that it's working now :)

So can you get at the raw request content as a stream from Web API? That's all that `Request.Body` represents in the above. If you can do that - removing the method parameter entirely, btw - then the code above should work, I believe.

Browsing the Web API documentation, you *may* be able to use:

```csharp
WebhookRequest request;
using (var stream = await Request.Content.ReadAsStreamAsync())
{
    using (var reader = new StreamReader(stream))
    {
        request = jsonParser.Parse<WebhookRequest>(reader);
    }
}
```

That's at least worth trying.

**Comment by jskeet** [comment]
Any updates on this? If it's working now, I'd like to close the issue.

**Comment by kobelinh24** [comment]
```
[HttpPost]
        public async Task<HttpResponseMessage> Post()
        {
            WebhookRequest webhookRequest;
            using (var stream = await Request.Content.ReadAsStreamAsync())
            {
                using (var reader = new StreamReader(stream))
                {
                    webhookRequest = _jsonParser.Parse<WebhookRequest>(reader);
                }
            }
            WebhookResponse webhookResponse = //data to be returned
            var response = new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(webhookResponse.ToString())
                {
                    Headers = {ContentType = new MediaTypeHeaderValue("text/json")}
                }
            };

            return response;
        }
```
Sorry for the late reply since I was off for quite some time, but the results were definitely positive. Before closing the issue, I would like to suggest having this documented, similar to what you provided for the .NET Core version, as I believe these codes should be a standard one for people who work with .NET framework.

**Comment by jskeet** [comment]
Thanks, I'm glad it's working for you. I'll see if I can get this into the docs - there could be some issues on that due to the infrastructure for our snippets and this needing an ASP.NET dependency, but we'll see.

**Comment by jskeet** [comment]
(I've edited the title of the issue to reflect what ends up needing doing.)

**Comment by jskeet** [comment]
The new docs will be published when we next do a release for Dialogflow, which I expect to be next week. (We generally don't release on Fridays.)

**Comment by kobelinh24** [comment]
> The new docs will be published when we next do a release for Dialogflow, which I expect to be next week. (We generally don't release on Fridays.)

That's good to know, hope that this can somehow contribute to the development of Dialogflow and .NET 💃
