### ISSUE TITLE
Missing method exception

### ISSUE THREAD

**Issue by SamuelDebruyn** [googleapis/google-cloud-dotnet#3101]
#### Environment details

  - OS: macOS 10.14.5
  - .NET version: 2.2.100 - Azure Functions runtime v2
  - Package name and version: `<PackageReference Include="Google.Cloud.Firestore" Version="1.0.0-beta20"/>`

#### Steps to reproduce

1. Add the following code (and replace where needed) - `fireStore` is an instance of `FireStoreDb`
```
var collection = fireStore.Collection(Constants.FIRESTORE_COLLECTION);
var query = collection.WhereEqualTo("name", source.Title).WhereEqualTo("address", source.Address).Select("name").Limit(1);
var snapshot = await query.GetSnapshotAsync();
```
2. I get the MissingMethodException at the `GetSnapshotAsync` call

#### Stacktrace

```
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll: 'Method not found: 'Void Grpc.Core.CallOptions..ctor(Grpc.Core.Metadata, System.Nullable`1<System.DateTime>, System.Threading.CancellationToken, Grpc.Core.WriteOptions, Grpc.Core.ContextPropagationToken, Grpc.Core.CallCredentials)'.'
   at Google.Api.Gax.Grpc.CallSettingsExtensions.ToCallOptions(CallSettings callSettings, IClock clock)
   at Google.Api.Gax.Grpc.ApiServerStreamingCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Cloud.Firestore.V1.FirestoreClientImpl.RunQuery(RunQueryRequest request, CallSettings callSettings)
   at Google.Cloud.Firestore.Query.<>c__DisplayClass54_0.<StreamResponsesAsync>b__0()
   at System.Linq.AsyncEnumerable.<ForEachAsync_>d__174`1.MoveNext() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\ForEach.cs:line 147
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Firestore.Query.<GetSnapshotAsync>d__50.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

#### Background info

I'm using FireStore from within an Azure Function. I'm developing the function in VS Code on macOS and I get this during debugging. (Can this be any more non-conventional? ;) )

Thank you for your time.

**Comment by jskeet** [comment]
Hmm... it's possible that this is due to some recent changes in gRPC - some types have moved to Grpc.Core.Api. This should be handled automatically by the [forwarded types attributes](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/ForwardedTypes.cs), I believe... but maybe that's not working in your environment.

Are you able to reproduce the problem by writing a standalone console application? If we can try to get things like Azure Functions out of the equation, that'll make it a lot easier to work out what's going on.

**Comment by jskeet** [comment]
+jtattermusch in case he's seen this before as part of moving things to Grpc.Core.Api.

**Comment by SamuelDebruyn** [comment]
This works:

```
using System;
using System.IO;
using System.Threading.Tasks;
using Google.Apis.Auth.OAuth2;
using Google.Cloud.Firestore;
using Google.Cloud.Firestore.V1;
using Grpc.Auth;
using Grpc.Core;

namespace FireStoreTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var fileDirectory = Directory.GetCurrentDirectory();
            var credentialFile = Path.Combine(fileDirectory, "google.json");
            var credential = GoogleCredential.FromFile(credentialFile).CreateScoped(FirestoreClient.DefaultScopes);
            var channelCredentials = credential.ToChannelCredentials();
            var channel = new Channel(FirestoreClient.DefaultEndpoint.ToString(), channelCredentials);
            var client = FirestoreClient.Create(channel);
            var fireStore = await FirestoreDb.CreateAsync("my-project-id", client);
            var collection = fireStore.Collection("my-collection");
            var query = collection.WhereEqualTo("name", "nothing").WhereEqualTo("address", "nothing").Select("name").Limit(1);
            var snapshot = await query.GetSnapshotAsync();
            Console.WriteLine($"Found {snapshot.Count} documents");
        }
    }
}
```

Same runtime and same OS. But I have no clue why this works in a console app and not in an Azure Function. Any ideas where I should look?

**Comment by jskeet** [comment]
Hmm. I feared that might be the case :( It may well be the way that Azure Functions handles dependencies.

In your "broken" project, could you try adding a direct dependency to Grpc.Core (version 1.21.0 should be fine)? I know we've had problems before when there's a chain of dependencies before you get to Grpc.Core, although I wouldn't expect to see it manifest itself like this.

**Comment by SamuelDebruyn** [comment]
That didn't help, I got the same exception with the same stacktrace. Looks like Azure Functions doesn't support binding redirects, so I suspect that type forwarding doesn't work either...

**Comment by jskeet** [comment]
Hmm... I thought Azure Functions 2 *did* support binding redirects.

I have no experience with Azure Functions 2, but I'll try to reproduce this on my (Windows) machine. Unfortunately it probably won't be before the end of the week though, I'm afraid.

**Comment by jskeet** [comment]
Okay, so the good news is that I can reproduce this in VS 2019 on Windows - so the unusual environment *isn't* the problem. The bad news is I don't know the next step. I'll experiment and keep updating this bug.

```csharp
using Google.Cloud.Firestore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Threading.Tasks;

namespace FunctionApp1
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            FirestoreDb db = FirestoreDb.Create("irrelevant");
            var collections = await db.ListRootCollectionsAsync().ToList();

            return new OkObjectResult(string.Join(", ", collections.Select(coll => coll.Id)));
        }
    }
}
```

**Comment by jskeet** [comment]
I've recompiled a local copy of GAX against Grpc.Core 1.21.0, then used that in my functions project - that's moved the issue to:

```text
System.MissingMethodException: Method not found: 'Grpc.Core.ChannelCredentials Grpc.Core.ChannelCredentials.Create(Grpc.Core.ChannelCredentials, Grpc.Core.CallCredentials)'.
   at Grpc.Auth.GoogleGrpcCredentials.ToChannelCredentials(ITokenAccess googleCredential)
   at Google.Api.Gax.Grpc.ChannelPool.CreateChannelCredentialsUncached()
```

That's a method in Grpc.Auth, and all the versions are in sync there, which makes this even odder. Still checking...

**Comment by jskeet** [comment]
I've managed to reproduce this without the Google API libraries being involved at all - simple gRPC. I'll update your bug in Azure Functions to provide a minimal repro, and we can track it from there if that's okay.

**Comment by SamuelDebruyn** [comment]
Thank you for picking this up so quickly! @jskeet :)

**Comment by phw198** [comment]
@jskeet I think I have a similar problem when invoking `Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender`, though I posted it on the GRPC project site: https://github.com/grpc/grpc/issues/20230 - might you be able to take a quick look?

**Comment by jskeet** [comment]
That's failing to find a native method - I suspect it's a different issue.

**Comment by crazybert** [comment]
Seeing the same issue in Cloud Run with all the latest nuget versions

**Comment by jskeet** [comment]
@crazybert: If you could provide a complete example (project file, code, Dockerfile) that would really help. Although I won't be looking until Monday.

**Comment by crazybert** [comment]
@jskeet Oh thank you. I will get back to this on Monday and try to create standalone repro
