### ISSUE TITLE
[PubSub] Retry Count Number As Attribute

### ISSUE THREAD

**Issue by Talento90** [googleapis/google-cloud-dotnet#3110]
**Is your feature request related to a problem? Please describe.**
When we subscribe a subscription we are expecting to receive messages. Sometimes our subscribers may have a problem and it fails processing the message. It would be very helpful to have the retry count as an attribute.

 **Describe the solution you'd like**
The overall solution would be to inject an attribute `RetryCount` in the Attributes dictionary and increment in every retry.

 **Describe alternatives you've considered**
I am not aware of any alternative.

**Comment by jskeet** [comment]
Assigned to Chris as he knows more about this than I do - but could you clarify what this is the retry count for, specifically? In particular, if you have 5 subscribers, they might fail different numbers of times for the same message. What do you expect the retry count to be part of, and how would it work with multiple subscribers?

**Comment by Talento90** [comment]
First of all, thanks for the fast reply. For what I understand, the message will stay in the "queue" until  some subscriber acknowledge the message. I would like to ignore or push to a different topic like a DLX after X retries. But there is no way to know the number of times that message was processed. 

If we have the retry count as an attribute, I can read the value and do some logic based on the retry count.

**Comment by chrisdunelm** [comment]
You are correct that a message will be resent to a subscriber until it has been acknowledged. There is currently no feature for the service to send a retry count to the client(s), and it's not something we can support purely in our client-side code.

It looks like your situation is similar to this SO question: https://stackoverflow.com/questions/42436334/how-do-i-deal-with-poison-pill-messages-when-using-google-pub-sub
Where the current advice is to keep a retry count yourself on the client(s); although I realise this can be painful to do if you have multiple clients subscribed to the same topic, and/or if you need to handle persistence across client restarts.

I've asked internally if there are any updates, and will update this issue as and when I hear.

**Comment by Talento90** [comment]
Really sad to hear that :'(  For local tests I am using a ConcurrentDictionary to map the message.id and the retry counts but when we start to use multiple instances this workaround does not work... so we need to manage an external database like Redis... Pub/Sub is quite inferior comparing to SQS from AWS... no retry count or DLX :(

**Comment by chrisdunelm** [comment]
Having asked internally, the response is that a Dead Letter Queue feature is being worked on, but we don't have a timeline for when this will be released.

Sorry we can't be more help in the immediate term.
Closing this issue as there's nothing more we can do. Please leave another comment if you have any more questions.
