### ISSUE TITLE
Detecting language spoken (c# 1.1.0-beta03)

### ISSUE THREAD

**Issue by sabiland** [googleapis/google-cloud-dotnet#3113]
Is "Detecting language spoken" supported for **c# 1.1.0-beta03** client library?
I cannot find new property "alternativeLanguageCodes", when I update client library to version 1.1.0-beta03.

**Comment by jskeet** [comment]
I assume this is the Google.Cloud.Speech.V1 library? That field doesn't exist in the v1 API, but it's in the v1p1beta1 API. We haven't released a new version of Google.Cloud.Speech.V1P1Beta1 for a long time (it's likely we'll release an update today, as it happens), but [RecognitionConfig.AlternativeLanguageCodes](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Speech.V1P1Beta1/api/Google.Cloud.Speech.V1P1Beta1.RecognitionConfig.html#Google_Cloud_Speech_V1P1Beta1_RecognitionConfig_AlternativeLanguageCodes) is part of the API.

Could you try that package and close this issue if it works for you?

**Comment by sabiland** [comment]
Thx for info @jskeet, I'll try. Can I just ask one more question, is it ok to use v1p1beta1 on our production environment?

**Comment by jskeet** [comment]
It's permitted as far as Google is concerned, but:

- The API can still change (or even be removed) before features appear in the stable API
- I'd expect a lower SLO for beta APIs than for the stable API

**Comment by sabiland** [comment]
Ok. Should I rather wait for an update (as you said - maybe today) or can I start testing with:
V1P1Beta1 1.0.0-beta02
?
For production we use **Google.Cloud.Speech.V1 1.1.0**

**Comment by jskeet** [comment]
You can definitely start testing with 1.0.0-beta02. When we release today it'll add any changes since last August, but that obviously won't change what's happening at the server side, so I don't think you need to wait at all.

**Comment by sabiland** [comment]
@jskeet I just tried with 1.0.0-beta02, but I get **AlternativeLanguageCodes** is a read only property?

public RepeatedField<string> AlternativeLanguageCodes { get; }

**Comment by jskeet** [comment]
It's a repeated field - you add to it, typically in a collection initializer. This is the same with all repeated fields in C# proto3.

**Comment by sabiland** [comment]
Ohhhh ok damn thx, I understand :).

@jskeet sorry I have so many questions. Do you have maybe a sample of response for 3-4 language codes? On Google documentation is only this JSON sample below. I am not sure what kind (final/intermediate) of response (with all alternatives) will be returned for 3-4 different language codes?

`{
  "results": [
    {
      "alternatives": [
        {
          "transcript": "hi I'd like to buy a Chromecast I'm ..."
          "confidence": 0.9466864
        }
      ],
      "languageCode": "en-us"
    },
    {
      "alternatives": [
        {
          "transcript": " let's go with the black one",
          "confidence": 0.9829583
        }
      ],
      "languageCode": "en-us"
    },
  ]
}`

**Comment by jskeet** [comment]
I'm afraid I don't have deep experience with the APIs here - our job is to make the client library accurately (and easily) let you talk to the API; we don't generally have in-depth knowledge of specific use cases, particularly for beta APIs.

Is there anything stopping you just making the request yourself to see what the response would look like?

**Comment by sabiland** [comment]
Ok I'll test/check responses myself. Anyways thx for quick help today. Maybe I'll have some more questions these days when I'll refactor our code for automatic language detection.

**Comment by sabiland** [comment]
Just FYI, now I have tried:

- Primary language code: "sl-si"
- Alternative language codes: ["en-US", "de-DE"]

But always in response I get only results (intermediate and final) for primary language code, never for alternative language codes.

`[
  {
    "Alternatives": [
      {
        "Transcript": "slovenija van",
        "Confidence": 0.6814952,
        "Words": [
          
        ]
      },
      {
        "Transcript": "slovenija vojne",
        "Confidence": 0.5991966,
        "Words": [
          
        ]
      },
      {
        "Transcript": "slovenija v one",
        "Confidence": 0.444111,
        "Words": [
          
        ]
      },
      {
        "Transcript": "slovenija vane",
        "Confidence": 0.592139661,
        "Words": [
          
        ]
      },
      {
        "Transcript": "slovenia van",
        "Confidence": 0.401350826,
        "Words": [
          
        ]
      }
    ],
    "IsFinal": true,
    "Stability": 0.0,
    "ChannelTag": 0,
    "LanguageCode": "sl-si"
  }
]`

My RecognitionConfig:

`// CREATE FULL ENGINE
            // CREATE FULL ENGINE
            // CREATE FULL ENGINE
            ENGINE = SpeechClient.Create();
            ENGINE_CONFIG = new StreamingRecognitionConfig()
            {
                Config = new RecognitionConfig()
                {
                    Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                    SampleRateHertz = settings.ArchiveSampleRate,
                    LanguageCode = firstLanguageCode,
                    ProfanityFilter = false,
                    MaxAlternatives = Constants.MASTER_SETTINGS.SpeechRecognitionAlternatives  /*(optional, defaults to 1) indicates the number of alternative transcriptions to provide in the response. By default, the Speech API provides one primary transcription. If you wish to evaluate different alternatives, set maxAlternatives to a higher value. Note that the Speech API will only return alternatives if the recognizer determines alternatives to be of sufficient quality; in general, alternatives are more appropriate for real-time requests requiring user feedback (for example, voice commands) and therefore are more suited for streaming recognition requests.*/,
                    SpeechContexts = { new HintsManager(settings).GetHintsBasedOnContext(Contexts) }
                },
                InterimResults = Constants.MASTER_SETTINGS.RecognitionConfigSettings.InterimResultsReturned
            };

            // NOTE: 10062019 - ADD ALTERNATIVE LANGUAGE CODES HERE
            // NOTE: 10062019 - ADD ALTERNATIVE LANGUAGE CODES HERE
            // NOTE: 10062019 - ADD ALTERNATIVE LANGUAGE CODES HERE
            foreach (var alternativeCode in otherAlternativeLanguageCodes)
            {
                ENGINE_CONFIG.Config.AlternativeLanguageCodes.Add(alternativeCode);
            }`

Should I wait probably for update you were saying today?

**Comment by jskeet** [comment]
While the new release should be available in the next hour or two, I'd be very surprised if it changed what you're seeing. I strongly suspect this is a matter of either mismatched expectations, or something else API-specific.

I suggest you ask on the [cloud-speech-discuss](https://groups.google.com/forum/#!forum/cloud-speech-discuss) group and ask for more information about this specific feature.

**Comment by sabiland** [comment]
Ok I'll ask on [cloud-speech-discuss](https://groups.google.com/forum/#!forum/cloud-speech-discuss).

**Comment by sabiland** [comment]
Also with little testing right now I have noticed that detection is working OK for alternative language codes, just that the returned languageCode is always that setted as primary language code.

_Optional A list of up to 3 additional BCP-47 language tags, listing possible alternative languages of the supplied audio. See Language Support for a list of the currently supported language codes. If alternative languages are listed, recognition result will contain recognition in the most likely language detected including the main language_code. The recognition result will include the language tag of the language detected in the audio._ 

I think only this is not working ok:

The recognition result will include **the language tag** of the language detected in the audio.

**Comment by sabiland** [comment]
Ok FYI. I have updated today to **V1P1Beta1 1.0.0-beta03**, made some local code changes and it looks like everything is working ok now! Correct language code tag is returned when using automatic spoken language detection.

Though I noticed that **interim results** are almost never returned && everything works more **slowly**?

**Comment by jskeet** [comment]
Again, I'm afraid that's not really a client library aspect - you're best off asking on the Sperch-specific discussion group. It's entirely possible that the beta API endpoint has fewer resources. (Note my earlier comment about SLOs.)

**Comment by sabiland** [comment]
Very well, thx for info @jskeet .

**Comment by mjk6035** [comment]
Is this supported for LongRunningRecognize operations?

I am trying to use the 'AlternativeLanguageCode' code parameter with a audio file that has been uploaded to Google Storage.
But it never uses any of the language codes specified using the 'AlternativeLanguageCode' parameter even though the language spoken matches the language code specified in the 'AlternativeLanguageCodes' parameter
It always uses the primary  'LanguageCode' parameter below

My code

try {
            Speech = Google.Cloud.Speech.V1P1Beta1.SpeechClient.Create();            
            var RecogCfg = new Google.Cloud.Speech.V1P1Beta1.RecognitionConfig
            {

               // Encoding = EncodeType,
                //SampleRateHertz = Int32.Parse(SampleRate),                
                LanguageCode = "en-US",
               // EnableAutomaticPunctuation = true,
                //EnableWordTimeOffsets = true,
                MaxAlternatives = 5,
                Model= "default"
                
                



            };
            RecogCfg.AlternativeLanguageCodes.Add("ml-IN");            


            if (SpeechCtx != null && SpeechCtx.Phrases.Count() > 0) {
				RecogCfg.SpeechContexts.Add(SpeechCtx);
			}

           LongOperation = Speech.LongRunningRecognize(RecogCfg, Google.Cloud.Speech.V1P1Beta1.RecognitionAudio.FromStorageUri(storageUri));
           
			OperationName = LongOperation.Name;
			return "1";

**Comment by jskeet** [comment]
@mjk6035: I'm afraid that's more of an API question than a client library question - I don't know the details of what happens at the backend. I'd suggest asking in the [cloud-speech-discuss](https://groups.google.com/forum/#!forum/cloud-speech-discuss) group.

**Comment by mjk6035** [comment]
@jskeet Thanks for the quick response.
I have already posted my query  in the  cloud-speech-discuss group. But there is no response.
https://groups.google.com/forum/#!topic/cloud-speech-discuss/B2HqWGdKIeU

That's why I posted here.

Thanks and regards
Mathew

**Comment by jskeet** [comment]
@mjk6035: I'm sorry that I can't help more :( It's very possible that a lot of the speech team are on vacation (or just back and working through an email backlog). Hopefully you'll get an answer soon!
