### ISSUE TITLE
SetAgent Request header generation for Dialogflow needs to handle missing Agent

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#3131]
The SetAgent ApiCall is created like this:

```csharp
_callSetAgent = clientHelper.BuildApiCall<SetAgentRequest, Agent>(
    GrpcClient.SetAgentAsync, GrpcClient.SetAgent, effectiveSettings.SetAgentSettings)
    .WithCallSettingsOverlay(request => gaxgrpc::CallSettings.FromHeader("x-goog-request-params", $"agent.parent={request.Agent.Parent}"));
```

That will fail if `request.Agent` is null. I suspect in such cases it's okay to send "agent.parent=" but we shouldn't just throw a NullReferenceException.

(This is a generator issue, but it's first seen here... we can move it if necessary.)

**Comment by chrisdunelm** [comment]
Hmm, so it really needs to generate something like: `$"agent.parent={request.Agent?.Parent ?? ""}"`

**Comment by jskeet** [comment]
I don't think the `?? ""` is necessary, as a null reference would convert to an empty string anyway in formatting. Just `request.Agent?.Parent` should be fine.

**Comment by chrisdunelm** [comment]
Oh yes, you're right. OK, I'll see if I can figure out how to make the generator do this!
