### ISSUE TITLE
Inconsistency between google docs and nuget package

### ISSUE THREAD

**Issue by songjiahong** [googleapis/google-cloud-dotnet#3145]
Environment details:
  - OS: Windows 10
  - .NET version: .NET Core 2.1
  - Package name and version: Google.Cloud.PubSub.V1 V1.0.0

Steps to reproduce
  1. In google docs: [authentication](https://cloud.google.com/docs/authentication/production#obtaining_and_providing_service_account_credentials_manually) , there are some code like
```csharp
    var credential = GoogleCredential.FromFile(jsonPath)
        .CreateScoped(LanguageServiceClient.DefaultScopes);
    var channel = new Grpc.Core.Channel(
        LanguageServiceClient.DefaultEndpoint.ToString(),
        credential.ToChannelCredentials());
    var client = LanguageServiceClient.Create(channel);
```
And we create similar code like that:
```csharp
GoogleCredential cred = GoogleCredential.FromFile("/path/to/credentials.json").CreateScoped(SubscriberServiceApiClient.DefaultScopes);
Channel channel = new Channel(
    SubscriberServiceApiClient.DefaultEndpoint.Host, SubscriberServiceApiClient.DefaultEndpoint.Port, cred.ToChannelCredentials());
SubscriberServiceApiClient client = SubscriberServiceApiClient.Create(channel);
```
  2. How ever it cannot compile since `GoogleCredential` doesn't have the method `ToChannelCredentials`

**Comment by jskeet** [comment]
The `ToChannelCredentials` method is an extension method in the `Grpc.Auth` namespace - if you add `using Grpc.Auth;` at the top of your source file, it should be fine.

There's a simpler way now though, using client builders:

```csharp
var credential = GoogleCredential.FromFile(jsonPath).CreateScoped(LanguageServiceClient.DefaultScopes);
var client = new LanguageServiceClientBuilder { CredentialsPath = jsonPath }.Build();
```

This is very new - we're still updating the docs around authentication, and trying to consolidate them if possible.

I'll close this issue for now, as updating those docs is part of a wider effort - but hopefully this will have helped unblock you.

**Comment by songjiahong** [comment]
Thanks @jskeet , it works!
