### ISSUE TITLE
Scheduler HttpTarget doesn't support setting Headers

### ISSUE THREAD

**Issue by nicksav** [googleapis/google-cloud-dotnet#3152]
Hey there!

For some reason all docs saying that we can set a Headers in HttpTarget, However, the code state:
`
        //
        // Summary:
        //     The user can specify HTTP request headers to send with the job's HTTP request.
        //     This map contains the header field names and values. Repeated headers are not
        //     supported, but a header value can contain commas. These headers represent a subset
        //     of the headers that will accompany the job's HTTP request. Some HTTP request
        //     headers will be ignored or replaced. A partial list of headers that will be ignored
        //     or replaced is below: - Host: This will be computed by Cloud Scheduler and derived
        //     from [uri][google.cloud.scheduler.v1.HttpTarget.uri]. * `Content-Length`: This
        //     will be computed by Cloud Scheduler. * `User-Agent`: This will be set to `"Google-Cloud-Scheduler"`.
        //     * `X-Google-*`: Google internal use only. * `X-AppEngine-*`: Google internal
        //     use only. The total size of headers must be less than 80KB.

`
`
        public MapField<string, string> Headers { get; }
`

There is no set;
Please help!

**Comment by jskeet** [comment]
No, it's a read-only property - but `MapField` is mutable. The property value will never be null, so you just populate it.

For example:

```csharp
var target = new HttpTarget
{
    Uri = "some uri",
    Headers =
    {
        ["foo"] = "bar",
        ["x"] = "y"
    }
};
```

or using a collection initializer:

```csharp
var target = new HttpTarget
{
    Uri = "some uri",
    Headers =
    {
        { "foo", "bar" },
        { "x", "y" }
    }
};
```

Or after initialization:

```csharp
var target = new HttpTarget
{
    Uri = "some uri"
};
target.Headers["foo"] = "bar";
```

Closing as that should be enough to help you - please add another comment if some aspect is still confusing.

**Comment by nicksav** [comment]
Hey
Thank you so much for the answer. I am digging with scheduler and not really much info. 
Trying to update a job and can't figure out how to use FieldMask.

Any link where I can read or simple example please?
I really want to be able only update:
 Schedule and TimeZone fields.

Thanks in advance!

**Comment by jskeet** [comment]
You'd use code like this:

```csharp
var mask = new FieldMask { Paths = { "scheduler", "time_zone" } };
client.UpdateJob(job, mask);
```

If that isn't enough, please create a new issue, as the FieldMask part is entirely separate to headers.
