### ISSUE TITLE
Spanner: Adjust timeouts for CreateDatabase and retries for other methods

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-dotnet#3165]
As part of a recent change to GAPIC Configuration, timeouts and retries need to be updated. 

Ensure that the timeouts and retires specified in https://github.com/googleapis/googleapis/commit/cc233544aa39b8947c9b929819aeb08e2cb71feb#diff-4501db3e3507bcce8496c9aea2017d96 are reflected in this client library.

**Comment by jskeet** [comment]
Will regenerate on Monday; that will pick it up automatically.

**Comment by jskeet** [comment]
For some reason regenerating doesn't seem to be picking it up - but I want to push back on whether this is a reasonable new timeout anyway. This is intended to be an asynchronous RPC - it returns an operation. It really shouldn't take more than 30 seconds to *start* creating the database and return a long-running operation representing that. It feels to me like a timeout of 1 hour defeats the point of having a long-running operation in the first place. @crwilcox are you the best person to talk to the server team about this? (I'll continue looking into why regenerating the C# client didn't pick up the changes.)

**Comment by jskeet** [comment]
Ah - it looks like the problem is that there's a `retry_params_name: default`, and the generator doesn't use the `timeout_millis` to override that. I'll ask @chrisdunelm what his expectations would be here.

**Comment by jskeet** [comment]
It looks like the [Java code](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/DatabaseAdminStubSettings.java#L482) does the same thing too.

So it looks like we actually need a new retry config for this - once we've worked out what it *really* should be.

**Comment by crwilcox** [comment]
There is an issue in the Create Database RPC at this time where it can take an exceptional amount of time before returning an LRO. To avoid this breaking folks, we are raising this timeout.

**Comment by jskeet** [comment]
Okay. We may need to create a separate retry configuration for this, given that the method-specific timeout isn't overriding that.
