### ISSUE TITLE
Spanner: Ensure client backoff is implemented to respect client configuration.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-dotnet#3166]
There was an issue in the client library for python where requests to retry could occur without a proper retry object. In this case, rather than defaulting to an exponential backoff, we defaulted to immediate retry. Ensure that for this client library we respect the min, max, and multiplier as specified in the gapic configuration. 

Original Bug: https://github.com/googleapis/google-cloud-python/issues/7303

**Comment by jskeet** [comment]
I don't quite understand at the moment, but will have a look on Monday.

**Comment by jskeet** [comment]
We don't currently perform automatic retry ourselves for transactions, but we do have a retry in [SqlResultStream](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SqlResultStream.cs) when reading from a result stream. This does have exponential backoff, but it's not taken from the GAPIC config. It's not clear to me *which* backoff configuration should be used here. Any thoughts, @crwilcox?
