### ISSUE TITLE
No error reported by job when uploading an invalid Json file from local file

### ISSUE THREAD

**Issue by apautrot** [googleapis/google-cloud-dotnet#3169]
Hi

Using
* Google.Cloud.BigQuery.V2 v1.3.0.
* Visual Studio Community 5017 v15.9.12

A job which upload an invalid local Json file has an invalid state, which do not reflect the real state of it.

The state of the job which upload the file is invalid (looks non updated) after the upload completion method has returned (PollUntilCompleted). Note that creating a new job object, using the same Reference Id, gets a job with a valid state which indicates an error.

The following code reproduces the issue (change the projectId to yours) :

	var projectId = "...";
	var client = BigQueryClient.Create ( projectId, credentials );

	var datasets = client.ListDatasets();
	var dataset = datasets.FirstOrDefault ( d => d.Reference.DatasetId == "TestDataset" );
	if ( dataset == null )
		dataset = client.CreateDataset ( "TestDataset" );

	var tables = dataset.ListTables();
	var table = tables.FirstOrDefault ( t => t.Reference.TableId == "TestTable" );
	if ( table == null )
	{
		var builder = new TableSchemaBuilder();
		builder.Add ( "A", BigQueryDbType.String );
		builder.Add ( "B", BigQueryDbType.Int64 );
		builder.Add ( "C", BigQueryDbType.Float64 );

		var schema = builder.Build();
		table = dataset.CreateTable ( "TestTable", schema );
	}

	// this json has a missing new line delimiter
	var json = "{A=\"Hello\",B=5,C=0.42}\n{A=\"Hello\",B=5,C=0.42}{A=\"Hello\",B=5,C=0.42}\n{A=\"Hello\",B=5,C=0.42}";
	var bytes = Encoding.UTF8.GetBytes ( json );
	var memoryStream = new MemoryStream ( bytes );

	var uploadOptions = new UploadJsonOptions()
	{
		ProjectId = projectId,
		Autodetect = false
	};

	try
	{
		var job = client.UploadJson ( table.Reference, null, memoryStream, uploadOptions );
		Console.WriteLine ( $"Job id is {job.Resource.Id}" );
		job.PollUntilCompleted();

		Console.WriteLine ( $"Job should be completed, status is {job.Status.State}" );
		if ( job.Status.ErrorResult != null )
				Console.WriteLine ( $"Job has finished with error : {job.Status.ErrorResult.Message}" );
		else	Console.WriteLine ( $"Job has finished with no error" );

		job.ThrowOnAnyError();

		var jobBis = client.GetJob ( job.Reference );
		Console.WriteLine ( $"Job bis status is {jobBis.Status.State}" );
		if ( jobBis.Status.ErrorResult != null )
				Console.WriteLine ( $"Job bis has errors : {jobBis.Status.ErrorResult.Message}" );
		else	Console.WriteLine ( $"Job bis has no error" );

		Console.WriteLine ( $"Job status is still {job.Status.State}" );
		if ( job.Status.ErrorResult != null )
				Console.WriteLine ( $"Job still has error : {job.Status.ErrorResult.Message}" );
		else	Console.WriteLine ( $"Job still says it has no error" );
	}
	catch (Exception e)
	{
		Console.WriteLine ( e.Message );
	}

State of job is invalid : job.Status.State is "RUNNING".
State of jobBis is valid : jobBis.Statis.State is "DONE" and the state contains errors as expected.

Regards.

**Comment by jskeet** [comment]
I strongly suspect this is the problem:

```csharp
job.PollUntilCompleted();
```

That doesn't change the *current* `BigqueryJob` - it fetches a *new* `BigqueryJob`.

If you just change that to:

```csharp
job = job.PollUntilCompleted();
```

I suspect you'll find it behaves as expected.

**Comment by apautrot** [comment]
Oh !
I never suspected something like that.
I used the example code from https://cloud.google.com/bigquery/docs/loading-data-local as a base code... a base code that didn't mention anything like that.

May I propose to make this more clear by design ? having a PollUntilCompleted ( ref BigQueryJob ) so that the ref could be null if unused, or used to pass an updated object as well. It would make it clear that you can get an updated object in return of the method.
Or simply by renaming the method to include a Get somewhere. PollUntilCompletedAndGetJob() or GetJobOnceCompleted.

Thanks for the reply.
Regards.

**Comment by jskeet** [comment]
We can't change the method name or signature now - but I'll definitely get the samples changed; thanks for pointing that out.

**Comment by apautrot** [comment]
Changing the name no, but you could mark it as deprecated (using Obsolete attribute) and have a new method with a different name or design that would be recommended to use instead.

But anyway, having samples that highlight this would be probably enough.

**Comment by jskeet** [comment]
I'd rather not make it obsolete - particularly as it (deliberately) matches the `Operation<TResponse, TMetadata>` methods as well. I'll get the samples fixed and improve the XML documentation - I think that should be sufficient.
