### ISSUE TITLE
How to specify rotation period when creating a new KMS key?

### ISSUE THREAD

**Issue by omerlh** [googleapis/google-cloud-dotnet#3178]
I'm trying to enable [automate key rotation](https://cloud.google.com/kms/docs/rotating-keys#automatic_rotation_setting_the_rotation_period_for_a_key) using the SDK. This is what I tried so far:
```csharp
var key = new CryptoKey
{
    Purpose = "ENCRYPT_DECRYPT",
    VersionTemplate = new CryptoKeyVersionTemplate
    {
         ProtectionLevel = mProtectionLevel,
    },
    NextRotationTime = DateTime.UtcNow.Add(mRotationPeriod),
    RotationPeriod = Duration.FromTimeSpan(mRotationPeriod)
};

var request = cryptoKeys.Create(key, keyringId);
request.CryptoKeyId = safeId;
await request.ExecuteAsync();
```
The problem is with `RotationPeriod`, I can't figure what I should put there.
When I tried something that is not `Google.Protobuf.WellKnownTypes.Duration`, I got this exception:
```
Google.GoogleApiException : Google.Apis.Requests.RequestError
Invalid value at 'crypto_key.rotation_period' (type.googleapis.com/google.protobuf.Duration),  [400]
Errors [
	Message[Invalid value at 'crypto_key.rotation_period' (type.googleapis.com/google.protobuf.Duration), ] Location[ - ] Reason[badRequest] Domain[global]
]
```
When I tried using the duration I got this exception:
```
Google.GoogleApiException : Google.Apis.Requests.RequestError
Invalid JSON payload received. Unknown name "seconds" at 'crypto_key.rotation_period': Cannot find field.
Invalid JSON payload received. Unknown name "nanos" at 'crypto_key.rotation_period': Cannot find field. [400]
Errors [
	Message[Invalid JSON payload received. Unknown name "seconds" at 'crypto_key.rotation_period': Cannot find field.
Invalid JSON payload received. Unknown name "nanos" at 'crypto_key.rotation_period': Cannot find field.] Location[ - ] Reason[badRequest] Domain[global]
]
```

What am I missing? How can I specify the period?

**Comment by jskeet** [comment]
Apologies - somehow I missed seeing this before.

I'm not quite sure how you've got that code to compile - `NextRotationTime` should be a `Timestamp`, and there's no implicit conversion from `DateTime`. There also shouldn't be any JSON payload at all... could you clarify how you're calling this, exactly? If you can provide a short but complete program demonstrating the problem, that would be even better.

**Comment by jskeet** [comment]
(If you're using the Google.Apis.CloudKMS.v1 package, this would make a bit more sense - I'd recommend the Google.Cloud.Kms.V1 package instead.)

**Comment by jskeet** [comment]
This is what I'd expect the code to look like in Google.Cloud.Kms.V1:

```csharp
TimeSpan rotationPeriod = TimeSpan.FromDays(90);
var key = new CryptoKey
{
    Purpose = CryptoKey.Types.CryptoKeyPurpose.EncryptDecrypt,
    VersionTemplate = new CryptoKeyVersionTemplate
    {
        ProtectionLevel = ProtectionLevel.Software
    },
    NextRotationTime = (DateTime.UtcNow + rotationPeriod).ToTimestamp(),
    RotationPeriod = Duration.FromTimeSpan(rotationPeriod)
};
```

**Comment by omerlh** [comment]
Thanks, I just did a quick refactor and moved everything to the new package. Working as expected!
