### ISSUE TITLE
[Firestore] Question: Recommendations for FirestoreClient / FirestoreDb lifecycle management for backend services

### ISSUE THREAD

**Issue by pblachut** [googleapis/google-cloud-dotnet#3182]
Following @jskeet [suggestion](https://github.com/googleapis/google-cloud-dotnet/issues/2405#issuecomment-507629355) I have created separate issue.

Hi, I'm using Google.Cloud.Firestore package in version 1.0.0-beta22. What are current recommendations for lifecycle management of FirestoreDb / FirestoreClient especially for backend services?

I use Firestore in backend service to process telemetry data (intensive reads and writes are done there). Service is deployed in GCP GKE and I observe high latency there. I followed all [best practices](https://cloud.google.com/firestore/docs/best-practices) but still 99th percentile is over 200ms (for reads and writes). Such results were present when I had single FirestoreDb instance for each pod.

I achieved lower latency by using basic pool mechanism. Created specified number of FirestoreDbs and then fetch them in random way. All these FirebaseDbs are created using the same json credentials:

```
var client = new FirestoreClientBuilder { JsonCredentials = credentialsJson }.Build();
return FirestoreDb.Create(projectName, client);
```

Are there any other recommendations for backend services to achieve lower latency?

**Comment by jskeet** [comment]
I would generally still recommend using a single `FirestoreDb` instance, yes. As you're getting better latency with a pooling system, we should probably investigate that. That would *suggest* you're saturating the channel, but I'd expect that to be pretty hard to do. Could you give me more detail about what the code does? If you have any sort of benchmarking of it that you'd be able to share, that would definitely be appreciated.

**Comment by pblachut** [comment]
Basically the code loads the state of object from Firestore into memory (state build using events, each event in separate document), applies some logic on that state and in result creates one or several new events (all saved using batch write).

I got unambiguous results only for write operation. Results for reads are not so clear (missing metrics).

![image (2)](https://user-images.githubusercontent.com/12517339/60514584-13c51f00-9cda-11e9-8f55-ac144524867b.png)

Metric measures following batch write operation (it is not exact code but describes what exactly is doing):
```charp
       [FirestoreData]
        private class SomeEvent
        {
            [FirestoreProperty]
            public long Id { get; set; }
            [FirestoreProperty]
            // Property exemptioned from indexing
            public byte[] Data { get; set; }
        }


        private async Task Do(FirestoreDb db, List<SomeEvent> documents)
        {
            var numberOfItemsPerBatch = 500;

            for (var i = 0; i < documents.Count; i += numberOfItemsPerBatch)
            {
                var docsForOperation = documents.Skip(i).Take(numberOfItemsPerBatch).ToList();

                var batch = db.StartBatch();

                foreach (var eventToSave in docsForOperation)
                {
                    // in real code document is located lower in the hierarchy 
                    var eventReference = db.Collection("someCollection").Document();
                    
                    batch.Set(eventReference, eventToSave);
                }

                await batch.CommitAsync();
            }
        }
```

**Comment by jskeet** [comment]
Thanks for that. Is there any relevance to the second red line, after which the graph is flat?
Also, do you have figures for what the throughput is like, i.e. how many of these you're doing over what time period? Just to try to work out how congested we might expect the traffic to be.

I suspect I'll need to ask the Firestore server team for help on this, by the way - but I might try reproducing it with similar code myself.

**Comment by pblachut** [comment]
Thank you for your engagement. Second red line is only my mouse pointer during taking snapshot, I did not intend to show anything by that :)

We perform average 1000 writes per sec, but during the day we have spikes which rise up to 2500 writes per sec.

**Comment by jskeet** [comment]
That's 1000 writes per second in a single process? When modeling this, is it reasonable to make each document quite small? (You have an arbitrary byte array there, which I guess could be huge...)

I'll see if I can reproduce your results myself - first locally (which would make things simpler) and then deploying to GCP if necessary to see the same effect.

**Comment by pblachut** [comment]
No, not in single process, currently we receive that using 10 pods. We perform 1000 times per second write batch operation. In single write batch is one or several documents (currently less than 5). Above code shows operation which is invoked.

We are currently during spike. Based on it we must decide if we could use firestore in longer run based on pricing and thoughput for our use case.

**Comment by jskeet** [comment]
Okay, so if I model it as 100 batches per second on a single machine, with 5 documents per batch, that's a *reasonable* approximation to what you're doing. I can then see whether I get any difference with pooling.

**Comment by jskeet** [comment]
While I try to reproduce this, by the way, I can probably be more helpful by answering the question about lifecycle:

It's **absolutely fine** to create a pool of `FirestoreDb` objects and use them in order to take advantage of multiple network channels. It's worth noting that if you weren't using custom credentials, you wouldn't get separate channels (due to us reusing a channel where we know we can) - and I'm *slightly* surprised that the separate logical channels are (presumably) ending up as separate physical network connections anyway, given internal gRPC pooling.

So while there are still aspects I need to understand and ideally improve, you shouldn't worry about your current approach of creating a pool: the `FirestoreDb` object itself is effectively immutable, so you shouldn't see any behavioral differences between using one or using many.

Hope that helps while I (finally) get round to reproducing.

**Comment by jskeet** [comment]
Okay, I've now written the benchmark to help us diagnose the problem.
If you have the time, could you have a look at the code in https://github.com/googleapis/google-cloud-dotnet/tree/master/apis/Google.Cloud.Firestore/Google.Cloud.Firestore.IntegrationBenchmarks and see whether that looks like it should reproduce the issue? So far I haven't seen pooling `FirestoreDb` instances consistently helping...

**Comment by jskeet** [comment]
Hi @pblachut,

Have you had a chance to look at this at all? Or is the information that it's okay to create a pool of `FirestoreDb` objects sufficient for your needs?

**Comment by pblachut** [comment]
Sorry for delay. We abandoned the idea of using Firestore in final solution, we have chosen to use Bigtable. Really appreciate your help and I think you have already answered my question.

I looked into the code which you have prepared and in comparision to ours there few small differences. 1. we used different api to add to batch document:
- in our case: `batch.Set(documentRef, document);`
- in your repro: `batch.Create(documentRef, document);`
2. we measured time a little bit different (might not influence very much on results)
- in our case: we starts stopwatch in the beging `Task WriteBatchAsync()` method
- in your case: you measure only time needed for making request
https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Firestore/Google.Cloud.Firestore.IntegrationBenchmarks/Program.cs#L124
3. Our pool was much more simpler:
```EventHubClient GetEventHubClient()
        {
            var i = _rand.Next(0, _eventHubClients.Length);
            return _eventHubClients[i];
        }```
4. Each firestoredb was created differently in our case;
```FirestoreDb CreateFirestoreDb()
            {
                var client = new FirestoreClientBuilder { JsonCredentials = credentialsJson }.Build();

                return FirestoreDb.Create(projectName, client);
            }```

Please remember that we observed differences when the pooling was turned on. Higher latency was observed when we used single firestoredb.

**Comment by jskeet** [comment]
Thanks for the extra detail. I probably won't investigate this any further for now, but that will be useful if we ever come across this again.

Best of luck with your application, and I hope Bigtable works out well for you.
