### ISSUE TITLE
 SubscriberClient.Create does not exist from the 1.0.0-beta20

### ISSUE THREAD

**Issue by xav-stargate** [googleapis/google-cloud-dotnet#3241]
I want update my package : Google.Cloud.PubSub from 1.0.0-beta19 to 1.0.0.
But after this upgrade  SubscriberClient.Create doesn't exist anymore. What I can use instead in my code ?

```csharp
SubscriptionName subscriptionName = new SubscriptionName(projectId, subscriptionId);
SubscriberServiceApiClient subscriberClient = SubscriberServiceApiClient.Create(channel);
SubscriberClient subscriber = SubscriberClient.Create(subscriptionName, new[] { subscriberClient });
```

Do you have a link to a changelog?

#### Environment details

  - OS: Windows 10
  - .NET version: 2.1
  - Package name and version: Google.Cloud.PubSub 1.0.0

Thanks to everyone

**Comment by jskeet** [comment]
Chris can provide more details, but it looks like you want to use the [SubscriberClient.ClientCreationSettings] type to pass into `SubscriberClient.CreateAsync`.

**Comment by chrisdunelm** [comment]
You can call the constructor directly:
```C#
SubscriberClient subscriber = new SubscriberClientImpl(subscriptionName, new[] { subscriberClient }, new Settings(), null);
```

Or don't create a `SubscriberServiceApiClient` yourself; instead call `SubscriberClient.CreateAsync.CreateAsync(subscriptionName);`

**Comment by jskeet** [comment]
@xav-stargate: Have our comments resolved this? If not, please provide more information about what you're looking for.

**Comment by jskeet** [comment]
Closing as I believe we've addressed this - @xav-stargate please add another comment if you need more information.

**Comment by xav-stargate** [comment]
Yes @jskeet thank you =)
Sorry for the delay
