### ISSUE TITLE
support for UseGoogleDiagnostics with CreateHostBuilder

### ISSUE THREAD

**Issue by WellspringCS** [googleapis/google-cloud-dotnet#3259]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
as noted here https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio, `CreateHostBuilder` is the go-forward recommended approach in Program.cs, with `CreateWebHostBuilder` being deprecated.

I am disappointed to find what appears to be no way to call `UseGoogleDiagnostics` via `CreateHostBuilder`.

 **Describe the solution you'd like**
Support for ASP.NET Core 3.0 recommended design next week instead of next year. (Can't hurt for me to ask...)

 **Describe alternatives you've considered**
I thought about MS DOS 4.0 but cannot find the floppies.

 **Additional context**
I'll send cute emoticons when my dreams are granted to me by the Google fairies.

**Comment by jskeet** [comment]
"Next week" is asking a bit much, but I'll look into it. There are several more urgent aspects of the diagnostics library that I want to address first, but I'm all for supporting the 3.0 way of doing things - *as well as* the old way. (I don't see any reason to break code that's already working.)

**Comment by jskeet** [comment]
I prototyped this earlier today, and I suspect the production code will actually be trivial - but I got stuck on the testing part.
I'm going to have another go when all our other changes have landed, but it *may* be within a week after all...

**Comment by WellspringCS** [comment]
John, I'd read that most of the people benefiting from your help are relative newcomers (to Stack Exchange, admittedly). So either that makes me a noob or you're not living up to your billing! (My silly way of saying Thank You!)

Thank you, indeed.

In other news... I have not been idle. I decided to try to implement the API using the legacy `CreateWebHostBuilder`. (I really wasn't expecting you to turn around my request so quickly!)

Bad news is, I got weird errors.

So I went back a step and, using [http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNetCore/index.html](url) as guide, I was able to implement Stackdriver logging with netcoreapp2.2 -- happy and no errors on first swing. No exhaustive effort, not exhaustively tested, to be sure... but something rudimentary did work without errors.

However in my full 3.0 project (which includes GraphQL and IdentityServer4 authentication, etc. etc.) that same code produces errors.

Ironically, yesterday it was preview 6. The error there was: `MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest..ctor`

Then overnight preview 7 was introduced, so for grins I am working with it. The error did not go away, but it changed. Now it is: `System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest'`

Go figure? So... stay tuned. I will try to reproduce my problems in a greenfield project and if so will start a new thread. Wouldn't want you to be bored, since you're making fast work of my first request!

Thanks again! Much appreciated.

**Comment by jskeet** [comment]
@henkmollema is currently working on making the package work with ASP.NET Core 3.0. I'm not *entirely* surprised it doesn't work right now (although it's a pity it's so obscure - maybe it'll at least be clearer with the RTM). My initial goal will be to get the "preferred way of working in 3.0 but viable way of working in 2.1" working *in 2.1* with UseGoogleDiagnostics. Getting it working in 3.0 will be slightly separate. Does that make sense?

**Comment by WellspringCS** [comment]
@jskeet mostly it does, except I'm not sure that anything in 2.1 is not working. Do you mean to say you'll try to get `CreateHostBuilder` working in 2.1? I'm being lazy and not checking to see if that is even an option.

Or do you mean to say you'll be working on two things, both in 3.0 -- one for `CreateHostBuilder` and one for `CreateWebHostBuilder`? That would make perfect sense, since there will be users on both sides of that fence for quite some time to come.

**Comment by jskeet** [comment]
>  Do you mean to say you'll try to get CreateHostBuilder working in 2.1?

That's the hope, yes. I *believe* it should be fine. The interface is available, at least.

ASP.NET Core 3.0 support will go into a separate branch that we won't merge until that's gone RTM.

**Comment by jskeet** [comment]
Actually, let me qualify: we can do the `UseGoogleDiagnostics` bit when targeting ASP.NET Core 2.1... but I suspect `CreateHostBuilder` won't work in 2.1 itself... it might work in 2.2. I need to investigate that more closely. But having a consistent set of capabilities in the package is important for simplicity.

**Comment by henkmollema** [comment]
I will toy a bit around and see if I can get 3.0 working with the 2.1 packages.

**Comment by WellspringCS** [comment]
Supposing I find something not working in 3.0 preview 7, should I open an issue? Or just await the outcome of your efforts as described here?

**Comment by jskeet** [comment]
Best to wait for the moment, I think - maybe subscribe to #3215, and you could always fork that branch and try it that way?

**Comment by henkmollema** [comment]
I think we should be able to get this working on .NET Core 3.0 with a few non-breaking adjustments. The setup code for .NET Core 3.0 would look like this:

```cs
Host.CreateDefaultBuilder(args)
     .ConfigureWebHostDefaults(webBuilder =>
     {
         webBuilder.UseStartup<Startup>();
         webBuilder.UseGoogleCloudDiagnostics();
     });
```

**Comment by jskeet** [comment]
@henkmollema: Are you suggesting it's not worth writing an extension method on `IHostBuilder` itself? (I believe it can be done pretty simply.)

**Comment by henkmollema** [comment]
Yeah it will be pretty simple, the type `IHostBuilder` exists in 2.1. But to keep the changes minimum, we don't _have_ to add the extension on `IHostBuilder`. Secondly, I'm not sure if it makes sense to configure an ASP.NET Core based logger on the generic host. The `UseGoogleDiagnostics` extension won't work as-is for console/worker apps since it uses a startup filter to configure the error logging and tracing middleware. Though the logging might work, from the layering perspective I think configuring this on the generic host seems a bit odd. According to the MS docs `ConfigureWebHostDefaults` is the preferred way to configure web host specific services.

**Comment by jskeet** [comment]
@henkmollema: Thanks for that feedback - that's definitely good to know.

I suspect this is just something we'll want to document when ASP.NET Core 3.0 comes out then.

@WellspringCS: Does that work for you?

**Comment by henkmollema** [comment]
Got a PR up in #3318.

**Comment by WellspringCS** [comment]
> Secondly, I'm not sure if it makes sense to configure an ASP.NET Core based logger on the generic host. 

@henkmollema I asked myself the same question, but [the ASP.NET Core 3.0 docs](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio) indicate:

> `IWebHostBuilder` remains in 3.0 and is the type of the `webBuilder` seen in the preceding code sample. `WebHostBuilder` will be deprecated in a future release and replaced by `HostBuilder`.

This is why I was wondering before if it wouldn't make more sense for you to focus on 3.0 support for both `CreateWebHostBuilder` and `CreateHostBuilder`. I don't imagine many will be in a hurry to reverse engineer the generic host into existing 2.x projects, but the case for supporting generic hosts in 3.x seems clear: `UseGoogleCloudDiagnostics` needs to be an extension for the generic host as well as the web host which is itself being sunsetted.

Speaking for myself, I'll be gratefully for Stackdriver support of any sort in 3.0 because I'm desperate to get over this hurdle. But I'd prefer to build for the future.

**Comment by WellspringCS** [comment]
@henkmollema did you mean precisely the following?
```
Host.CreateDefaultBuilder(args)
     .ConfigureWebHostDefaults(webBuilder =>
     {
         webBuilder.UseStartup<Startup>();
         webBuilder.UseGoogleCloudDiagnostics();
     });
```
Not to beat a dead horse, but `Host` won't work with `ConfigureWebHostDefaults` which is another way of stating the problem I face. I'm hoping indeed for a `Host` solution, but if I understand your suggestion, wouldn't you mean to say `WebHost.CreateDefaultBuilder(args)` here?

**Comment by henkmollema** [comment]
Why wouldn't that work? `Host.ConfigureWebHostDefaults` is used in all the new 3.0 templates and is re-platted on top of the generic host. AFAICT it's the way forward to configure web-related services in stead of using `WebHost.CreateDefaultBuilder()`.

**Comment by WellspringCS** [comment]
Sorry, I misspoke. You're right. But `Host` is the generic host, is it not? Confused as to what you meant, having offered up code that supports the generic host but then words that indicated you didn't think that was necessary.

**Comment by henkmollema** [comment]
> But `Host` is the generic host, is it not?

Yes, it is. But a web hosting model still exists for hosting ASP.NET Core web applications. Where as on 2.x these were two separated hosting models, in 3.0 the web hosting model has been re-platted on the generic hosting model. So there is a generic host and the web host now builds on top of that as some sort of extension rather than a separate model.

> Confused as to what you meant, having offered up code that supports the generic host but then words that indicated you didn't think that was necessary

What I meant by that was that we don't necessarily need an extension method on `IHostBuilder` but instead keep leveraging the extension on `IWebHostBuilder` and call that from inside `ConfigureWebHostDefaults()`. I also think having an extension method on the generic `IHostBuilder` doesn't make a lot of sense for a logger which uses ASP.NET Core concepts and hooks into the HTTP pipeline like this library.

**Comment by WellspringCS** [comment]
@henkmollema thanks, I understand you clearly now. And I've also had the chance to follow the [PR 3318](https://github.com/googleapis/google-cloud-dotnet/pull/3318) link which reinforces the same.

Apologies for my earlier confusion, and I eagerly await the results!

**Comment by henkmollema** [comment]
No problem. Glad it's clear now, these hosting model changes keep being a source of confusion. 😄

**Comment by jskeet** [comment]
Okay, I *think* it's now okay to close this issue. Do let me know if you think it should be reopened!
