### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by elvogel** [googleapis/google-cloud-dotnet#3266]
I use a number of different products in this API stack for several different solutions. One thing I've come to anticipate is some level of chaos and confusion that comes from updating NuGet packages for each product with respect to things that are new, changed or even removed altogether. 

It would be **really** helpful to have some release notes for these updates. Ideally, these release notes would be in the API documentation site(s), which is where we all go to try and understand implementation details as we go along. It's especially relevant to have release notes for the SDK that are separate from the release notes of the product itself, as some of the changes I've experienced in the Nuget packages aren't necessarily correlated to anything new in the product. 

Thanks!

**Comment by jskeet** [comment]
I definitely hear the concern. I *try* to make sure that the commit that creates the release gives some details - but in the past that's not always been easy to sort out... and I appreciate that https://github.com/googleapis/google-cloud-dotnet/releases makes it hard to filter for a single API.

We have some work in the pipeline to make it easier for the product teams to communicate changes with the client library teams... but I think we'll need more than that.

Just to clarify what you mean by "the API documentation site" do you mean pages like https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/index.html? As a heads-up, this content will be moving to googleapis.dev over time - we're currently duplicating, but we'll redirect from GitHub Pages eventually. As an example, that documentation is also at https://googleapis.dev/dotnet/Google.Cloud.Firestore/1.0.0/index.html. It's only API documentation - none of the "guides" that are currently on GitHub pages; we're still deciding where those should go.

So, are those the pages you're using at the moment? If so, that's definitely the easiest place for us to add release notes to. If you wanted them in the product documentation, that could be trickier.

**Comment by elvogel** [comment]
> Just to clarify what you mean by "the API documentation site" do you mean pages like https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/index.html? 

Yes - those pages are my go-to for anything related to the packages. 

> As an example, that documentation is also at https://googleapis.dev/dotnet/Google.Cloud.Firestore/1.0.0/index.html. 

Just took a look - LOVE the pop-up in the corner letting you pick versions. That helps confirm that new features are new and you're not just losing your mind.

But yeah, https://googleapis.dev/dotnet/Google.Cloud.Firestore/1.0.0/index.html is my go-to for Firestore info. I honestly don't even look at the Releases page in here - I took a look at the link, and it confirmed what I thought it would - broad-level release info for each and every package. Still good to have, but some quick, developer-friendly release notes would be fantastic.

**Comment by jskeet** [comment]
Thanks for the quick response. I'll start working on a design for how to build release notes for each package - probably as an extra page within each package's API docs (so Google.Cloud.Firestore/releases.html or something similar). Then it's a matter of making sure there's clear content in there.

To set expectations, I wouldn't expect this to change *quickly* - but hopefully when it *is* sorted, it'll be much, much better :)

**Comment by elvogel** [comment]
Much appreciated!

**Comment by jskeet** [comment]
We now have release notes - of varying degrees of detail - for all libraries. Not all are published yet - those that aren't published yet will be included in the next release. Example: https://googleapis.dev/dotnet/Google.Cloud.Language.V1/latest/history.html
