### ISSUE TITLE
FulfillmentMessages property in DialogFlow WebhookResponse (V2) is ReadOnly

### ISSUE THREAD

**Issue by thinkcodellc** [googleapis/google-cloud-dotnet#3325]
The WebhookResponse object in DialogFlow has a FulfillmentMessages along with FulfillmentText. The FulfillmentMessages  messages struct is however readonly. Earlier discussion seem to indicate that it was meant to be send in rich response such as cards, suggestion chips etc. Is there a different means to send in rich responses?
`
return new WebhookResponse {
                FulfillmentText = responseText,
                FulfillmentMessages = WebhookResponse.Parser.ParseJson(richResponse)
            };
`

**Comment by jskeet** [comment]
All repeated fields in C# generated code from protos are read-only properties, but they're mutable collections - you just need to add to them, which you can do with a collection initializer. For example:

```csharp
return new WebhookResponse
{
    FulfillmentText = responseText,
    FulfillmentMessages = { WebhookResponse.Parser.ParseJson(richResponse) }
}
```

Note that you *must* use the Protobuf JSON parsing and serializing code, not Json.NET etc... so if that's attempting to return a result in a Web API, you probably want to return a string instead. See the [documentation](https://googleapis.dev/dotnet/Google.Cloud.Dialogflow.V2/latest/index.html) for sample code.

**Comment by jskeet** [comment]
I'm going to close this issue now as I expect this will have answered your question - but please add another comment if this hasn't resolved things for you.
