### ISSUE TITLE
[Google.Cloud.PubSub.V1] - Inconsistencies in documentation for .net

### ISSUE THREAD

**Issue by vsspt** [googleapis/google-cloud-dotnet#3348]
**Steps to reproduce**

The Documentation for PubSub is not consistent:

- On Google Cloud Documentation, available [here](https://cloud.google.com/pubsub/docs/pull), the examples use the old SubscriberClient / PublisherClient classes

- On Google.Cloud.PubSub.V1, available [here](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.PubSub.V1), it uses the new PublisherServiceApiClient / SubscriberServiceApiClient classes.

Unfortunately, the Google.Cloud.PubSub.V1 documentation, does not cover all scenarios, for example:
- Listening for Errors
- Message Flow Control

The documentation on Google Cloud, has an example for configuring flow control, but there is no example for the same  on the new classes.

This is the flow control code for the old classes:
````
SubscriberClient subscriber = await SubscriberClient.CreateAsync(
    subscriptionName,
    settings: new SubscriberClient.Settings()
    {
        AckExtensionWindow = TimeSpan.FromSeconds(4),
        Scheduler = Google.Api.Gax.SystemScheduler.Instance,
        AckDeadline = TimeSpan.FromSeconds(10),
        FlowControlSettings = new Google.Api.Gax
            .FlowControlSettings(
            maxOutstandingElementCount: 100,
            maxOutstandingByteCount: 10240)
    });
````

I couldn't find any example to define the flow settings for the new SubscriberServiceApiClient.
Would it be possible to update the API page with the proper example for this?

**Comment by jskeet** [comment]
`SubscriberClient and `PublisherClient` aren't the "old" classes - they're a higher level abstraction than the API client classes which are more "raw" access to the underlying API. Those classes don't have flow control configuration because that flow control is implemented by the higher-level abstraction.

Is there anything stopping you from using `SubscriberClient` and `PublisherClient`, or was it just the misunderstanding of "old vs new"?

**Comment by vsspt** [comment]
Thank you for the clarification, the mistake was mine.
I will look at the documentation in more detail.
