### ISSUE TITLE
Form issues for c#

### ISSUE THREAD

**Issue by kairanaquazi** [googleapis/google-cloud-dotnet#3367]
OS: Windows 10(x64 based)
.NET version: 4.0
Package name: Google.Cloud.speech.v1
Version: 1.2.0

## Reproduction
1. Open a C# .Net form
2. Make sure you have your credentials set :)
4. Use NuGet to install Google.Cloud.speech.v1
4. Add <code>using Google.Cloud.speech.v1</code>
5. Use it for something (IDK)
6. Build and run
7. You should get: " Cannot load *location to dependency*.dll or one of its dependencies.

If this works it might be an issue with the code I am using <a href = "../../../../intel/acat">ACAT</a>.
Thanks :)

**Comment by jskeet** [comment]
I wasn't aware of ACAT before this issue. It sounds like there's something wrong with how the NuGet packages (including transitive dependencies) are being deployed.

Which precise dependency was it complaining about? If it's the gRPC native DLL, it may well be fixable via some code to manually copy that file at execution time.

**Comment by jskeet** [comment]
(It's not quite clear to me what ACAT's role is here. Is it just a library you're using, or a whole new project type in Visual Studio? If it's the former, what kind of project type are you using?)

**Comment by kairanaquazi** [comment]
ACAT is a project that I maintain for Intel Labs' Anticipatory Computing Lab. It uses forms as it is a desktop app. It did not say what was missing, it just said that one of them is. I've attached 2 pages of my NuGet installed packages.
<img width="562" alt="page1 github error" src="https://user-images.githubusercontent.com/48654706/63109575-654e0400-bf3e-11e9-9896-fbb542a7079e.PNG">
<img width="578" alt="page2 github error" src="https://user-images.githubusercontent.com/48654706/63109586-697a2180-bf3e-11e9-913a-62e90198953e.png">

**Comment by jskeet** [comment]
> It uses forms as it is a desktop app.

Do you mean it's a WinForms app? In that case I'd normally expect it to work absolutely fine for supported platforms - but I see you're targeting .NET 4.0, which our libraries don't support. I'm surprised NuGet even allows you to install the package in that case, as we target net45 and netstandard1.5.

**Comment by kairanaquazi** [comment]
It works for a Console App I have, which is on .NET Standard 1.5. Do you have any other modules that would do the same thing?

**Comment by jskeet** [comment]
An *application* can't target .NET Standard 1.5 - that's what a *library* would target.

We don't support .NET 4.0 even for our REST-based client libraries now. Note that .NET 4.0 [reached end of life in January 2016](https://dotnet.microsoft.com/learn/dotnet/what-is-dotnet-framework). Is there any reason you can't use a more modern framework?

**Comment by kairanaquazi** [comment]
OK

**Comment by kairanaquazi** [comment]
If I transfer it to .NET 4.5 (which I did some time ago), would it work?

**Comment by jskeet** [comment]
Well I'd *expect* it to, but given that I wouldn't have expected it to build at all under .NET 4.0, I can't say for sure. You're in the best position to test that, to be honest.

**Comment by kairanaquazi** [comment]
I just did, it is giving me the original error.

**Comment by jskeet** [comment]
Okay, in that case could you walk me through reproducing this step by step, from "File > New Project"? (Your current instructions don't mention ACAT, for example...)

**Comment by kairanaquazi** [comment]
If you download ACAT source code (it is kinda big) at github.com/intel/acat, I can help you reproduce the problem

**Comment by kairanaquazi** [comment]
Just notify me :)

**Comment by jskeet** [comment]
I'll be doing this tomorrow, UK time. It would be really helpful if you'd provide the steps here rather than trying to do this interactively.

**Comment by kairanaquazi** [comment]
OK

**Comment by kairanaquazi** [comment]
After you download the source code, open it up in Visual Studio. Search for PhraseSpeakScanner, it is a form under PhraseSpeakAgent. Replace it with the one that I'm attaching. Make sure to install Google.Cloud.Speech.v1 from NuGet. Build and run. A form will pop up with different buttons, one of them will say "Phrase". Click on it and you will get the error.

**Comment by kairanaquazi** [comment]
If you have any questions, ask me (I'm 8 hrs. behind UK time)

**Comment by jskeet** [comment]
I'm finding it *very* difficult to understand your project structure. PhraseSpeakScanner is in a solution folder - not part of any project. Which project should I add the Speech dependency to? Which project should I run? Is there any reason the solution is organized in this rather unconventional way? I'll keep looking at what's going on, but I suspect that this structuring may be part of the problem.

**Comment by jskeet** [comment]
I've managed to get it to *build* by adding the dependency to Lib/Extension. Trying to run ACAT Phrase, I'm asked to select a color scheme then a camera - I'm then getting an exception of "External component has thrown an exception". (I haven't got as far as finding a "Phrase" button...)

**Comment by jskeet** [comment]
Running ACatApp instead, I get an error of "Fatal error. Error setting active word prediction engine". Ditto ACatTalk.

It would really help if you could cut this down to a *minimal* example to reproduce the problem, rather than me trying to navigate through all of these project-specific issues before I can get to the problem with the Speech library itself.
One thing you might want to try is installing the Google.Cloud.Speech.V1 NuGet package as a direct dependency of your *application* rather than just the class library you're using it from. My guess is that the way you're loading libraries stops it from finding the dependencies of those libraries.

**Comment by jskeet** [comment]
Okay, having disabled the camera initialization part of code, ACatPhrase starts - and then repeated captures focus, which makes it hard to switch between writing this feedback and testing - but there's no "Phrase" button.
I don't think I can make any more progress on this on my own, I'm afraid. Please give clearer instructions for how to reproduce this - ideally in a minimal environment which is less error-prone.

**Comment by kairanaquazi** [comment]
ok

**Comment by kairanaquazi** [comment]
I think I found a workaround using Sockets to communicate with the python ASR.

**Comment by kairanaquazi** [comment]
you also have to set ACATDashboard as startup, sorry, I forgot. It only works on Windows.

**Comment by kairanaquazi** [comment]
Thank you for your time

**Comment by jskeet** [comment]
Okay, well I thought I'd give it one last try - I set ACATDashboard as the startup project, and it starts - I clicked on "Phrase" and it opened the Phrase app with no problems.
If you decide you need to come back to this, please try to reproduce the problem in a much smaller sample, otherwise we won't get far. However, it sounds like you've got a solution for now.
