### ISSUE TITLE
Ignore Tracing Http Requests

### ISSUE THREAD

**Issue by Talento90** [googleapis/google-cloud-dotnet#3387]
There is any way to ignore some specific endpoints when using: `Google.Cloud.Diagnostics.AspNetCore` ? I would like to ignore `/health` or `/swagger/*`

**Comment by jskeet** [comment]
Yes, in `TraceServiceOptions` you can specify the `TraceFallbackPredicate` property of type `TraceDecisionPredicate`, which is used to determine whether or not to trace requests which don't explicitly have a trace header. You'd configure this in the `AddGoogleTrace` call (I don't believe it can be done in `UseGoogleDiagnostics` at the moment, although we could look at changing that):

```csharp
// The "true" is to ignore /_ah/health requests for AppEngine
services.AddGoogleTrace(options => options.TraceFallbackPredicate = new TraceDecisionPredicate(IgnoreSwaggerAndHealth, true));

...
bool? IgnoreSwaggerAndHealth(HttpRequest request) =>
    request.Path == "/health" || request.Path.StartsWith("/swagger/", StringComparison.Ordinal) ? false : null;
```

Note that the return type is `bool?` to indicate "definitely don't trace", "definitely trace", or "trace if other code thinks it should".
This predicate won't be called if the request already has a trace ID though - I hope that's not a problem for you.

Let me know if this works out for you.

**Comment by Talento90** [comment]
Thank you very much, I will give a try to see if it works as I expect :)

Another question: If I use `services.AddGoogleTrace` then I need to explicit trace my code by creating spans? Can I use `Google.Cloud.Diagnostics.AspNetCore` and `AddGoogleTrace`?

**Comment by jskeet** [comment]
Yes, `AddGoogleTrace` is part of `Google.Cloud.Diagnostics.AspNetCore`. You just need to configure the diagnostic services separately instead of in a single `UseGoogleDiagnostics` call. When I get a chance, I'll see if there's a way we could make `UseGoogleDiagnostics` flexible enough to handle this use case.

**Comment by Talento90** [comment]
Since, I am running my service in K8S, it would be useful to have an option to set the service name. Otherwise, I cannot filter in the UI by service name :( 

```
 bool? IgnoreSwaggerAndHealth(HttpRequest request) => request.Path == "/health" || request.Path.Value.StartsWith("/swagger", StringComparison.Ordinal) ? false : (bool?) null;
```

It's not showing any traces :/ Do I need to create a middleware to create spans?

**Comment by jskeet** [comment]
You shouldn't need to, no - but just those two lines of code aren't enough information for me to understand what's going on in terms of the lack of tracing.

For the "option to set the service name" - I'm not sure what you mean there, but it sounds like a separate feature request. Please file a separate issue so I can try to understand exactly what you're trying to do. (I *suspect* I know what you mean, and while we try to fetch the service name automatically to include in the monitored resource, we don't always have access.)

**Comment by jskeet** [comment]
One suggestion - if you want to trace *every* request, you can return `true` from your method instead of `null`. That might be okay for testing purposes, but would probably generate more traces than you want for production traffic.

**Comment by Talento90** [comment]
I had the wrong permissions in my Service Account 🤦‍♂ I was missing the `Cloud Trace Agent` permission.

Thank you very much for your help and tips!!  👍

**Comment by jskeet** [comment]
Hooray - I'm so glad it worked out in the end, and thanks for explaining what was wrong... it'll help me ask future customers to check their permissions :)
