### ISSUE TITLE
[Firestore] ListDocumentsAsync against emulator resulting in PermissionDenied

### ISSUE THREAD

**Issue by emmekappa** [googleapis/google-cloud-dotnet#3397]
I'm running Firestore emulator on MacOS 10.14.6 from gcloud sdk version 260.0.0.

And I'm using the following code to connect to the emulator:

`return FirestoreDb.Create("na",
                FirestoreClient.Create(new Channel("127.0.0.1", 8080, ChannelCredentials.Insecure)));`

Every `ListDocumentsAsync()` operations results in 

`Grpc.Core.RpcException : Status(StatusCode=PermissionDenied, Detail="Metadata operations require admin authentication.")`

Looks the same problem described in https://github.com/firebase/firebase-tools/issues/1363

**Comment by emmekappa** [comment]
Found a way to workaround the issue by expliciting the `FirestoreSettings` adding `Baerer owner` as `Authorization` header.

Here's now the code to create a `FirestoreDb` able to list documents:

```
var firestoreSettings = new FirestoreSettings()
{
   CallSettings = CallSettings.FromHeaderMutation(x => x.Add("Authorization", "Bearer owner"))
};
return FirestoreDb.Create("na",
   FirestoreClient.Create(new Channel("127.0.0.1", 8080, ChannelCredentials.Insecure), firestoreSettings));
```

**Comment by jskeet** [comment]
That's interesting, thanks. I'll treat this issue as a feature request to make that easier to do. We might even end up with a simple way of configuring `FirestoreDbBuilder` to use emulator in the same way that we do for DatastoreDb.

Thanks for filing and then following up!

**Comment by emmekappa** [comment]
Yes @jskeet, it would be great to have the same OOB emulator support already implemented in DatastoreDb.

**Comment by jskeet** [comment]
This is now implemented in Google.Cloud.Firestore version 1.1.0-beta02.
See http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/ for an example.
