### ISSUE TITLE
System.EntryPointNotFoundException at GetDocumentSnapshotsAsync

### ISSUE THREAD

**Issue by bjornbacklund** [googleapis/google-cloud-dotnet#3398]
#### Environment details

  - OS: Microsoft Windows NT 6.2.9200.0
  - .NET version: 4.0.30319.42000
  - Package name and version: Google.Cloud.Firestore 1.0.0

#### Steps to reproduce
A simple GetSnapshotAsync throws:

var credential = GoogleCredential.FromFile("mycreds.json");
    	var channel = new Channel(FirestoreClient.DefaultEndpoint.Host, FirestoreClient.DefaultEndpoint.Port, credential.ToChannelCredentials());
    	var client = FirestoreClient.Create(channel);

    	var db = FirestoreDb.Create("myprojectid", client);
	var coll = db.Collection("A");
    	var docRef = coll.Document("doc");

        // this throws System.EntryPointNotFoundException, see stack below
	var snapshot = docRef.GetSnapshotAsync().GetAwaiter().GetResult();
  
	
//////////////////////////////

OS Version: Microsoft Windows NT 6.2.9200.0
CLR Version: 4.0.30319.42000
ProcessorCount: 4
Error Type: System.EntryPointNotFoundException
Error Message: Entry point was not found.
Stack Trace:
   at System.IDisposable.Dispose()
   at Google.Cloud.Firestore.FirestoreDb.<<GetDocumentSnapshotsAsync>b__34_0>d.MoveNext() in T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Firestore\Google.Cloud.Firestore\FirestoreDb.cs:line 316
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

**Comment by jskeet** [comment]
Could you clarify which version of .NET you're targeting? You've shown the CLR version, but that doesn't tell me about the overall framework version. It would also be nice to know which style of project file you're using - the old-school one, or the newer "SDK" style one (as used by .NET Core, but also capable of supporting .NET).

Additionally, do you see this behaviour in a console application? It will be easier to reproduce if that's the case. Basically, the more information we have in order to reproduce this, the better.

**Comment by jskeet** [comment]
Okay, I had a hunch about what this was - I suspect I'll need to write a FAQ entry for it.

I suspect you've added a dependency to Grpc.Core 2.23.0, which is the latest version - but which is incompatible with Grpc.Core 1.x which our libraries currently depend on.

If you either remove the explicit dependency on Grpc.Core entirely, or downgrade it to 1.22.0, I believe you'll see the problem go away.

Here's my repro:

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="1.0.0" />
    <PackageReference Include="Grpc.Core" Version="2.23.0" />
  </ItemGroup>
</Project>
```

And C#:

```csharp
using Google.Cloud.Firestore;
using System.Threading.Tasks;

namespace Issue3398
{
    class Program
    {
        static async Task Main(string[] args)
        {
            // Assumes GOOGLE_APPLICATION_CREDENTIALS is set appropriately.
            var db = FirestoreDb.Create(args[0]);
            await db.Document("a/b").GetSnapshotAsync();
        }
    }
}
```

That will throw an exception, whereas changing the version of Grpc.Core to 1.22.0 fixes it.

**Comment by bjornbacklund** [comment]
Thank you for an amazingly quick response. 
Yes, reverting Grpc.Core (and Grpc.Auth) to 1.22 fixes the issue.
(I am targeting NET 4.7.2)
Any idea when you would be supporting the lastest version of Grpc.Core ?
Thanks!
---bjorn

**Comment by jskeet** [comment]
I'm *hoping* it'll be some time in Q4. Making a breaking change - thus requiring a new major version number - is pretty involved, as well as disruptive for customers... we want to try to make sure we get all the breaking changes we're likely to want in the near future into one release.
