### ISSUE TITLE
Cloud Translation GoogleApiException "The service is unavailable at this time. [503]"

### ISSUE THREAD

**Issue by chriskilpatrick** [googleapis/google-cloud-dotnet#3416]
- OS: Windows 10
  - .NET version: 4.8
  - Package name and version: Google.Cloud.Translation.V2 (1.2.0-beta02)

I'm trying to translate the attached japanese text to english using this code:
`_translationClient.TranslateHtmlAsync(text, "EN", "ZH");`

This results in following exception:

`The service translate has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
The service is unavailable at this time. [503]
Errors [
	Message[The service is unavailable at this time.] Location[ - ] Reason[backendError] Domain[global]
]`

The strange thing is that there are some texts, which work and some texts, which don't work. I can provide some other failing examples as well if it is needed.

[TranslationText.txt](https://github.com/googleapis/google-cloud-dotnet/files/3573780/TranslationText.txt)

**Comment by jskeet** [comment]
I strongly suspect this isn't a client library issue, but a Translation service issue, in which case it'll be best to follow one of the support routes listed in the [Translation support page](https://cloud.google.com/translate/docs/getting-support). But I'll try to a) reproduce it with client libraries; b) reproduce it in the API explorer, just to check.

**Comment by jskeet** [comment]
Hmm... I reproduced it once, but then while fiddling with the text to try to cut down the repro a bit, the error stopped. Could you retry and see if it's been fixed for you now? It could be that it was a temporary backend issue.

**Comment by chriskilpatrick** [comment]
Okay for this example it seems to work now. But I have another example, which still fails.
But you are right, this seems to be an error with the service and not with the library.

[TranslationText2.txt](https://github.com/googleapis/google-cloud-dotnet/files/3573992/TranslationText2.txt)

**Comment by jskeet** [comment]
Right - I'm afraid there's not a lot I (as a client library maintainer) can do at this point, in that case, so I'm going to close this issue. I suspect the best route is via the [google-translate-api](https://groups.google.com/forum/#!forum/google-translate-api) Google group, which is monitored by the Translation team themselves. If you link to the same problematic file there, hopefully they'll be able to work out what's going on.
