### ISSUE TITLE
Update MultiRegional and Regional to Standard

### ISSUE THREAD

**Issue by JesseLovelace** [googleapis/google-cloud-dotnet#3426]
(I don't have assign privileges in this repository but this should be assigned to @dopiera )

Previously, we implemented the concept of "Location Type" to move the concept of bucket location away from storage class. It is no longer considered correct to use "MultiRegional" or "Regional" as a storage class, instead those should be location types.

As such, we need to update every instance of the "MultiRegional" and "Regional" storage in samples, library documentation, and tests to use "Standard" instead--Standard is a correct storage class.

Note that "MultiRegional" and "Regional" should only be replaced with "Standard" in cases where they are used a storage class. If they're used as a location type, that's fine and doesn't need to be replaced.

https://github.com/googleapis/google-cloud-dotnet/blob/d2aba1aa0fbcb7b9cb8cc4f603ce038ceaeed81e/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/StorageClassTest.cs#L41
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/search?q=regional&unscoped_q=regional

**Comment by jskeet** [comment]
Assigned to @dopiera, but within this repo it's probably going to be simplest for me to put together a PR that they review.

**Comment by dopiera** [comment]
Hi,
are you sure I am the right person to do this? I've never worked in C#. I'm currently working on GCS and Bigtable in C++.

**Comment by jskeet** [comment]
No need for any C# experience really - just reviewing my changes, one in a test and the others in comments (that are then published in documentation).
