### ISSUE TITLE
BigQuery: expose CMEK functionality for ML models

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-dotnet#3509]
This request is to expose customer managed encryption key (CMEK) for BigQuery ML models.

It uses the same message (encryptionConfig) as is present on the rest interface
for managed tables, e.g. the expression of a related KMSKeyName.

ML models aren't instantiated via the API directly, but via CREATE MODEL sql query.
The CMEK functionality should be present in the API for other relevant mechanisms,
such as models.get and models.update.

For more information, contact @shollyman.

**Comment by jskeet** [comment]
Thanks - we'll need to work out how to prioritize that alongside our other work.

Note that customers using Google.Cloud.BigQuery.V2 can still fetch and update models via the underlying generated service - it'll just be less convenient than if we create dedicated methods.

**Comment by shollyman** [comment]
Going to close this one, as there's no custom methods, just surfacing new fields on existing resources.
