### ISSUE TITLE
[Code cleanup] Duplicate Tests: DocumentSnapshotTest.ConvertTo_CustomType() and GetField_ProtoValue()

### ISSUE THREAD

**Issue by mikelehen** [googleapis/google-cloud-dotnet#3520]
https://github.com/googleapis/google-cloud-dotnet/blob/c4439e0099d9e4c414afbe666f0d2bb28f95b297/apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/DocumentSnapshotTest.cs#L99 appears to be an exact duplicate of https://github.com/googleapis/google-cloud-dotnet/blob/c4439e0099d9e4c414afbe666f0d2bb28f95b297/apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Tests/DocumentSnapshotTest.cs#L74

Presumably it was meant to do something else.

**Comment by jskeet** [comment]
Thanks, will look tomorrow.

**Comment by mikelehen** [comment]
Thanks!  Though it's super low-pri, really. 😄
