### ISSUE TITLE
Google.Cloud.Language.V1.AnnotateTextResponse.ToString() throws exception

### ISSUE THREAD

**Issue by bjornbacklund** [googleapis/google-cloud-dotnet#3526]
#### Environment details

  - OS: Wndows 10
  - .NET version: 4.7.2
  - Package name and version: Google.Cloud.Language.V1 1.3.0

#### Steps to reproduce

   var doc = new Document()
    {
        Content = ""One dollar and eighty-seven cents. That was all. And sixty cents of it was in pennies. Pennies saved one and two at a time by bulldozing the grocer and the vegetable man and the butcher until one's cheeks burned with the silent imputation of parsimony that such close dealing implied. Three times Della counted it. One dollar and eighty-seven cents. And the next day would be Christmas.",
        Language = "en",
        Type = Document.Types.Type.PlainText
    };

    var features = new AnnotateTextRequest.Types.Features();
    features.ExtractDocumentSentiment = true;
    features.ExtractEntities = true;
    features.ExtractEntitySentiment = true;
    features.ExtractSyntax = true;
    features.ClassifyText = true;

    LanguageServiceClient client = ...// code to initialize client
    AnnotateTextResponse response = client.AnnotateText(doc, features);
   var str = response.ToString(); // THIS THROWS - DETAILS BELOW!

/*
'response.ToString()' threw an exception of type 'System.TypeInitializationException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233036
    HelpLink: null
    InnerException: {"The type initializer for 'Google.Api.AnnotationsReflection' threw an exception."}
    Message: "The type initializer for 'Google.Cloud.Language.V1.LanguageServiceReflection' threw an exception."
    Source: "Google.Cloud.Language.V1"
    StackTrace: "   at Google.Cloud.Language.V1.AnnotateTextResponse.get_Descriptor()\r\n   at Google.Cloud.Language.V1.AnnotateTextResponse.pb::Google.Protobuf.IMessage.get_Descriptor()\r\n   at Google.Protobuf.JsonFormatter.Format(IMessage message, TextWriter writer)\r\n   at Google.Protobuf.JsonFormatter.Format(IMessage message)\r\n   at Google.Protobuf.JsonFormatter.ToDiagnosticString(IMessage message)\r\n   at Google.Cloud.Language.V1.AnnotateTextResponse.ToString()"
    TargetSite: {Google.Protobuf.Reflection.MessageDescriptor get_Descriptor()}
    TypeName: "Google.Cloud.Language.V1.LanguageServiceReflection"*/

**Comment by jskeet** [comment]
I believe you've taken a dependency on Google.Protobuf version 3.9.1, which has a bug. Please remove the explicit dependency, or reduce it to 3.8.0, which doesn't have the bug. (Our client libraries don't depend on anything higher than 3.8.0.) Unfortunately I believe the fix for this bug has missed the cut for 3.10.0, so please wait until 3.11.0 is released before upgrading.

**Comment by jskeet** [comment]
(Please confirm in this issue when you've been able to test my hypothesis, so I can close the issue. Obviously if it *doesn't* fix the problem, we'll investigate further.)

**Comment by bjornbacklund** [comment]
Amazingly quick response! and yes, downgrading Google.Protobuf to 3.8.0 fixed it. Thanks!

**Comment by jskeet** [comment]
Cracking - glad it worked!
