### ISSUE TITLE
Google.Cloud.Dialogflow.V2 (C sharp) missing property enable_fuzzy_extraction

### ISSUE THREAD

**Issue by SafeCab** [googleapis/google-cloud-dotnet#3571]
Hi,

I am using Google.Cloud.Dialogflow.V2 from nuget and am unable to find the property enable_fuzzy_extraction on the EntityType object.  Please could you provide me an example of how to set it

Thanks

Steve

**Comment by jskeet** [comment]
Right, that property was added since we last did a release of Dialogflow. I'll try to sort out a new release to go out today.

**Comment by jskeet** [comment]
Google.Cloud.Dialogflow.V2 version 1.1.0, including EntityType.EnableFuzzyExtraction, is now available. Thanks!
