### ISSUE TITLE
Google Speech API Grpc.Core.RpcException StatusCode=Unavailable, Detail=Empty update

### ISSUE THREAD

**Issue by sabiland** [googleapis/google-cloud-dotnet#3576]
We use Google Speech API:

`<PackageReference Include="Google.Cloud.Speech.V1P1Beta1" Version="1.0.0-beta03" />`

Today I suddenly noticed quite random (not always) exceptions:

`Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail=Empty update)`

I cannot find anywhere what **Detail=Empty update** means?

EDIT: Exceptions happen quite rarely and randomly, but they do happen. Until today we haven't seen those kind of issues.

EDIT2: I have checked success/fail statistics and it seems we get cca 1 exception per 10 success API calls.

**Comment by jskeet** [comment]
I *believe* that's an [error from the gRPC library](https://github.com/grpc/grpc/blob/5911d2c7314ccce3b1a6d44d985d36e323317098/src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc#L452) if it receives an update list of subchannels which is empty. It looks like it's transient, and you should be able to retry it after a delay. (Although I wouldn't be surprised if it took a little while for things to recover in this case.)

**Comment by sabiland** [comment]
Exception happens already in first initial call:

```
try
            {
                ENGINE_STREAM = ENGINE.StreamingRecognize();

                // Write the initial request with the config.
                await ENGINE_STREAM.TryWriteAsync(
                    message: new StreamingRecognizeRequest() { StreamingConfig = ENGINE_CONFIG },
                    options: Helper.GetGrpcWriteOptions()
                 ).ConfigureAwait(false);

            }
            catch (Exception e)
            {
                Helper.LogException("LanguageSpeechRecognition::StartEngine", e, FinalAutomaticDetectedLanguageCode);
            }
```

**Comment by sabiland** [comment]
> I _believe_ that's an [error from the gRPC library](https://github.com/grpc/grpc/blob/5911d2c7314ccce3b1a6d44d985d36e323317098/src/core/ext/filters/client_channel/lb_policy/round_robin/round_robin.cc#L452) if it receives an update list of subchannels which is empty. It looks like it's transient, and you should be able to retry it after a delay. (Although I wouldn't be surprised if it took a little while for things to recover in this case.)

Jon, so is this issue somehow related between client library and server side communication?
I guess we can do nothing about it right?

**Comment by sabiland** [comment]
Jon I think we found the problem, though I am in the dark what was really wrong. We ran our service on 2 servers behind load balancer (c# console application, running as windows service as gRpc server ---> which forwards/streams everything to GoogleSpeechAPI). I found out the problem was only on 1 server, when we restarted service, everything was ok!

Jon maybe any idea how/why could this happen?

**Comment by jskeet** [comment]
That would explain why this isn't something I've seen before... I'm afraid I really can't explain it without doing more diagnostics on the failing systems. I wouldn't have *thought* updating to .NET Core 3.0 would be relevant, but I try not to rule anything out beforehand.

I'll close this issue now as I don't think there's anything for us to do in this repo - but we can reopen if it's useful later.

**Comment by sabiland** [comment]
Ok thx for info.
