### ISSUE TITLE
spanner: Session pool should hand out sessions in LIFO order

### ISSUE THREAD

**Issue by skuruppu** [googleapis/google-cloud-dotnet#3578]
**Is your feature request related to a problem? Please describe.**
Currently sessions are handed out from the session pool in FIFO order. Least recently used sessions are unlikely to be in backend caches, and the transactions associated with them are likely to aborted due to idleness.

 **Describe the solution you'd like**
The session pool should hand out sessions in LIFO order.

**Comment by amanda-tarafa** [comment]
Addressed by #3577

**Comment by amanda-tarafa** [comment]
Closing via #3577
