### ISSUE TITLE
dialogflow2 adding prompts to a parameter via the c sharp library 

### ISSUE THREAD

**Issue by SafeCab** [googleapis/google-cloud-dotnet#3582]
hi,

I am trying to set up a parameter for an intent and would like to set the prompts parameter but it seems it only has a Get and no Set

I am using C sharp and Google.Cloud.DialogFlow.V2 (version 1.1.0.0)

maybe I am missing something obvious but I am quite new to this.

Thanks

Steve

**Comment by jskeet** [comment]
It's a repeated field - you add to it. See https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-modify-repeated-fields-and-maps-in-protobuf-messages

**Comment by jskeet** [comment]
Sorry for the brief message yesterday - I was on a mobile. But you'd want something like:

```csharp
Parameter p = new Parameter
{
    Name = "my parameter",
    DisplayName = "Something visible",
    Prompts = { "First prompt", "Second prompt" }
};
```

I'll close this issue now as I expect this will have addressed it fully - please add a comment if you have further questions about it.
