### ISSUE TITLE
FieldValue.Increment not available

### ISSUE THREAD

**Issue by premy** [googleapis/google-cloud-dotnet#3583]
Though the docs  affirm it, I'm not able to set FieldValue.Increment. Only options that appear in intellisens (VS 2017, .NET 451) are: ArrayRemove, ArrayUnion, Delete and ServerTimeStamp
![fieldIncrement](https://user-images.githubusercontent.com/1387407/66281909-c08fd900-e893-11e9-9b36-9172b0068b75.jpg)

**Comment by jskeet** [comment]
Which version of the package are you using?

**Comment by jskeet** [comment]
(I'd expect `FieldValue.Increment` to be present from 1.0.0-beta21 onwards.)

**Comment by premy** [comment]
Was using 1.0.0 beta20, upgraded to latest version 1.1.0 beta01, which gives access to Increment, but throws an error while connecting to firestore:
The native method "grpcsharp_batch_context_recv_message_next_slice_peek" does not exist;
Googling for it, didn't come up with anything usable.

**Comment by jskeet** [comment]
That's very odd - that sounds like the Grpc.Core version is out of sync somewhere. Are you certain you haven't accidentally updated to Grpc.Core v2 somehow? If it's a .NET Core project, if you could post the project file, that would be really helpful.

**Comment by premy** [comment]
Well, it's a WebForms site, so no project file, but here is a snap of the packages file.
![packages](https://user-images.githubusercontent.com/1387407/66344347-fd0b1580-e923-11e9-8a03-7c476ff19e1c.JPG)

**Comment by jskeet** [comment]
Hmm... are you able to look at which binaries are actually deployed in your application? In particular, you'd want to look for `grpc_csharp_ext.dll` as that's the interop DLL. I strongly suspect there's a mismatch of dependencies somewhere - but I can't see anything there. Do you have any other dependencies?

Are you able to try this with a more recent version of .NET? I have no reason to believe that using 4.7.2 or similar would change this, but it's at least worth a try - and it's worth noting that as part of a major version bump later this year, we're *considering* dropping support for the desktop framework earlier than .NET 4.6.1.

**Comment by premy** [comment]
grpc_csharp_ext.dll is in the bin folder. Will try with a newr version of .NET and let you know, thank you.

**Comment by jskeet** [comment]
Right - the interesting thing to find out is what *version* of grpc_csharp_ext.dll it is (and likewise the version of Grpc.Core.dll).

Although grpc_csharp_ext.dll doesn't have a version handily baked in like Grpc.Core.dll, it does have a timestamp in the digital signature - if you right-click on it in Explorer and then select "Digital Signatures", there should be a signature from "Google LLC", with a timestamp. Could you let me know what that timestamp is?

Then for Grpc.Core.dll, just right-clicking in Explorer and looking at "Details" should show the full version in either "File version" or "Product version".

If you could let me know those, I can chase a bit further.

**Comment by premy** [comment]
![csahrpext](https://user-images.githubusercontent.com/1387407/66351701-7ad71d00-e934-11e9-898a-83b7de3504ae.JPG)
grpc_csharp_ext.dll does not expose a signatures tab, and Previous versions is empty.

![grpc](https://user-images.githubusercontent.com/1387407/66351814-b376f680-e934-11e9-84d2-6d6828d4195f.JPG)

**Comment by jskeet** [comment]
Okay, I believe that's a very old version of grpc_csharp_ext.x86.dll - possibly around 1.31.1. (That's certainly *a* version that's 2.36MB. In 1.22.0 it's just over 3MB.) That would definitely explain the error you're seeing.

I would suggest cleaning your solution as far as you possibly can - blow away the bin and obj directories entirely, and before you build, search for *every* occurrence of grpc_csharp_ext.x86.dll in your project directory, recursively. There may be a stray one lurking ready to cause problems...

**Comment by premy** [comment]
Now it gives:
"The type initializer for 'Google.Cloud.Firestore.Converters.ConverterCache' threw an exception.;"

**Comment by jskeet** [comment]
Okay, we're going to need to see the details of the exception in order to understand it. I expect it's a TypeInitializerException, with an InnerException that has the real details.

**Comment by premy** [comment]
Thing is I'm not being able to get to that innerException. Here's the code where the error's thrown:
`Try
            Dim dbase As FirestoreDb = ConnectDB()
            Dim collection As CollectionReference = dbase.Collection("Solicitados")
            Dim solicitadosQuery As Query = collection.WhereEqualTo("status", "novo").OrderBy("datum").OrderBy("paciente")
            Dim solicitadosQS As QuerySnapshot = Await solicitadosQuery.GetSnapshotAsync()
                      For Each doc As DocumentSnapshot In solicitadosQS.Documents
                Dim sol As Solicitados = doc.ConvertTo(Of Solicitados)
                //populate datatable dt                '    
            Next
            GridView1.DataSource = dt
            GridView1.DataBind()
        Catch ex As Exception
            ShowMessage(ex.Message)
        End Try`
dbase does not expose any exception methods or properties. And this is the ConnectDB class:
`Public Class fbdal
    Public Shared db As FirestoreDb
    Public Shared channel As Channel
    Public Shared Function InitDB() As FirestoreDb
        Dim credential As GoogleCredential = GoogleCredential.FromFile(System.Web.HttpContext.Current.Server.MapPath("~/chave_firestore.json"))
        Dim channelCredentials As ChannelCredentials = credential.ToChannelCredentials()
        channel = New Channel(FirestoreClient.DefaultEndpoint.ToString(), channelCredentials)

        Dim fsClient As FirestoreClient = FirestoreClient.Create(channel)

        Dim db As FirestoreDb = FirestoreDb.Create("forlifesaude-ec167", client:=fsClient)
        Return db
    End Function

    Public Shared Function ConnectDB() As FirestoreDb
        If db Is Nothing Then
            db = InitDB()

        End If
        Return db
    End Function
    Public Shared Async Function CloseDB() As Task

        Await (channel.ShutdownAsync())
    End Function

End Class`

**Comment by jskeet** [comment]
I'm afraid if you don't have the exception details, that leaves us completely in the dark. It also means that for anything *else* that goes wrong in your application you'd be in the dark too. It's really important to be able to get full exception details. What have you got that's reporting *just the message* of the exception?

**Comment by premy** [comment]
Update previous comment. Do you have a better picture now?

**Comment by jskeet** [comment]
Well this is the problem:

```vb
ShowMessage(ex.Message)
```

You should change that code to show `ex` instead of `ex.Message` - or at least *log* the whole thing. (It's not clear to me whether `ShowMessage` makes something user-visible, or just logs it.) Fundamentally, logging just an exception message is almost *never* useful compared with logging the complete exception including the stack trace and any inner exceptions.

**Comment by premy** [comment]
ShowMessage just shows the exception in the ui. I will try to see If I can get more details from ex.

**Comment by jskeet** [comment]
If by "the UI" you mean a web application that anyone is able to see, you probably *don't* want to display even the exception message. Log it, and then just tell the user that something went wrong. In some cases, showing an exception message can reveal a security vulnerability to a hostile user.

**Comment by premy** [comment]
In fact I do not show the exception itself in the ui, just tell the user something went wrong, as you're rightfully suggesting.
Well I guess I was too tired last night, for I didn't think about digging deeper into ex. Turns out it was due to an assembly mismatch (Google.Api.CommonProtos.dll). Fixed that, and now everything works, Yay!!!
Would expect for Nuget to take care of all that, but apparently...
But now I came across something else: 

![increment](https://user-images.githubusercontent.com/1387407/66413579-081a8000-e9ce-11e9-89e7-a3cde042d515.jpg)
Hovering over the .test property reveals it's an int, however, trying to commit, throws the following exception:
[InvalidCastException: Conversion of type 'SentinelValue' to type 'Integer' invalid.]
Tried as Long, Double and even String, all with the same result. Finally tried it with type Object, and guess what, it works! Seems odd though. Any ideas? Or can I close this issue?

**Comment by jskeet** [comment]
I would expect that to be a *compile-time* error, unless you're using `Option Strict = False`.

`FieldValue.Increment(1)` can't return an integer - it represents "the change to an integer value" which isn't the same as an integer. (If it were just an integer, how could anything tell the difference between that and "I want to set it to that integer"?)

This is absolutely working as intended. Usually `FieldValue.Increment` would be used not with a model object, but with an anonymous type.

I'll close the issue now, as I don't believe there's anything wrong now.
