### ISSUE TITLE
Endless Streaming - Google Cloud Speech2Text

### ISSUE THREAD

**Issue by Tiozi** [googleapis/google-cloud-dotnet#3621]
Hello everyone,

I'm trying to develop a Infinite Streaming service using .Net.

I did it last year.. Briefly cutting the audio stream and renew the session after 40 seconds.

Today i was taking a look trying to find more information about this and i found that has examples in other languages (Java, Python, NodeJS .. https://cloud.google.com/speech-to-text/docs/endless-streaming-tutorial) Can someone give me a tip how to make it in .Net ?

Thanks!

**Comment by jskeet** [comment]
We have some sample code here:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/speech/api/Recognize/InfiniteStreaming.cs

I'd expect it will eventually be listed in the page you showed before, but it needs review by the Speech team first. That said, I expect it should be fine - I tested it against a long video, comparing it with how the Python code did, and they gave the same results.

**Comment by Tiozi** [comment]
I just found this code few minutes ago. Sorry about that!

I'll test it, using a mic in the next days! 

I did it cutting the stream in a "silenced sample" after it renewing the screaming session .. It's working well, but i think that now has a newer solution to this issue.

I will do a comparison soon as possible!

Thanks for your help!

**Comment by jskeet** [comment]
Great - I'll close this issue now as unless I hear otherwise, I'll assume that it works :)
