### ISSUE TITLE
Calling firestore async methods, like SetAsync(), with "grpc.net.client" package dependency gets deadlock

### ISSUE THREAD

**Issue by li-rongcheng** [googleapis/google-cloud-dotnet#3673]
#### Environment details

  - **OS:** Windows 10
  - **.NET version:** .net core 2.2 and .net core 3.0
  - **Package name and version:**
    Google.Cloud.Firestore, 1.0.0-beta21 and 1.0.0

#### Steps to reproduce

  1. Set up a very basic forestore c# client project according to https://firebase.google.com/docs/firestore/quickstart , make a call to ```await docRef.SetAsync(user);``` . So far, everything works perfect!
  
  2. Add the following package to the project: ```<PackageReference Include="grpc.net.client" Version="2.24.0" />```, now execute the program, it will stop forever on the return of ```SetAsync(user)```

Need to mention that:
- the data has written successfully, the program just keeps waiting on the return
- there's no any "Wait()" call, everything is called using async/await:
  ``` c#
  static async Task Main(string[] args)
  {
     ...
     await docRef.SetAsync(user);
     ...
  }
  ```

**Comment by jskeet** [comment]
Unfortunately the Grpc.Net.Client dependency will have brought in Grpc.Core.Api 2.24.0, which isn't compatible with Grpc.Core and Grpc.Core.Api 1.x that the Firestore library depends on.

Basically, until we've updated the dependencies to Grpc.Core 2.x, this won't work, and there's no known workaround. (It's *possible* that cunning use of AssemblyLoadContext might help, but I don't know - and it's likely to be brittle.)

I suggest subscribing to #3519 which I'll update as we make progress on this. (It's rather more complex than it appears at first glance.) I'll close this issue now, as there are no separate actions to take for this issue vs that one.
