### ISSUE TITLE
Proposal: remove EF Core provider for Spanner

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#3675]
We currently have an alpha version of an Entity Framework Core provider for Spanner, along with a GA version of an ADO.NET provider.

The EF Core provider has not been reviewed and maintained as thoroughly as the ADO.NET provider, and probably needs significant effort to bring it from alpha to beta and then GA. At the moment, we have no plans to put in that effort.

Proposal:

- Delist the packages in NuGet
- Remove the source code from GitHub in a single commit (so we can easily revert it later if we decide to bring the project back)

cc @meteatamel, @JustinBeckwith, @chrisdunelm, @SurferJeffAtGoogle, @jsimonweb, @amanda-tarafa 

(Note: unless there are any objections, I plan to implement this on Friday November 8th.)

**Comment by SurferJeffAtGoogle** [comment]
The proposal SGTM.

**Comment by jskeet** [comment]
This has now been done.
