### ISSUE TITLE
Firestore reference data type can't work in .net core (c#)

### ISSUE THREAD

**Issue by li-rongcheng** [googleapis/google-cloud-dotnet#3684]
#### Environment details

  - **OS:** Windows 10
  - **.NET version:** .net core 3.0
  - **NuGet package name and version:**
    Google.Cloud.Firestore, 1.0.0

#### Steps to reproduce

1. Create document with a referece type field `tagRef` by:
    ``` c#
    await _db.Document("tags/tag_id_1234").SetAsync(new
    {
        someData = "some test data"
    });

    await _db.Document("devices/dev_id_abcd").SetAsync(new {
        tagRef = _db.Document("tags/tag_id_1234")
    });
    ```
   (no any problem here, works greatly)

2. Do:
    ``` c#
   var dev = await _db.Document("devices/dev_id_abcd").GetSnapshotAsync();
   var tagRefDoc = dev.GetValue<DocumentReference>("tagRef");
   var tagRefSnapshot = await tagRefDoc.GetSnapshotAsync();
    ```
3. Then:

    - `tagRefSnapshot.Exists` will always be false, which should be true
    - `tagRefSnapshot.ToDictionary()` will always be null (so that tagRef.GetValue<>() method will never work), which should be non-null

   Do `WhereEqualTo()` query for the embedded reference type `tagRef` can't work either:

    ``` c#
    var the_correct_tagRef = _db.Document("tags/tag_id_1234");
    var devs = await _db.Collection("devices").WhereEqualTo("tagRef", the_correct_tagRef).GetSnapshotAsync();
    ```
   then the `devs.Documents.Count` will always be 0, which should be non-zero

Need to mention that the following attributes work correctly for the above case:
  - tagRefDoc.Path
  - tagRefDoc.Parent
  - tagRefSnapshot.Id

**Comment by jskeet** [comment]
I don't see why you'd expect document `"tags/tag_id_1234"` to exist - you don't create it anywhere in the code above. You create a `DocumentReference`, but the document itself doesn't exist.

**Comment by li-rongcheng** [comment]
@jskeet  Sorry, it's my mistake, but to make it clearer, I still updated the issue description according to your comment.

What happened was that when I was creating the tag document, there was a trailing space in the tag ID, e.g. the tag id was actually "tag_id_1234 " but not the "tag_id_1234" I was expecting.Therefore, the problem in this issue doesn't exist. 

However, I still think allowing a trailing space in a document ID is a bug. When I did this, Firestore  should automatically trim the trailing or leading spaces, or an exception should be thrown out indicating the document ID format was wrong.

Do I need to raise a new different bug report? Thanks.

**Comment by li-rongcheng** [comment]
And I think operations to some special data types, like reference and geographical point, should be included in [document](https://firebase.google.com/docs/firestore/query-data/get-data) and [example code](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/firestore/api) as well.

**Comment by jskeet** [comment]
Firstly, I'm glad you've found and fixed the problem.

> However, I still think allowing a trailing space in a document ID is a bug. When I did this, Firestore should automatically trim the trailing or leading spaces, or an exception should be thrown out indicating the document ID format was wrong.

No, I believe it's a valid ID with a space. Have you seen a rule somewhere saying that the document ID *can't* include spaces or a trailing space? Personally I can't find documentation for what document IDs *are* valid - I do believe it would be good to add that, but I don't think you should *assume* that trailing spaces are invalid.

Note that at this time, rejecting or trimming IDs would break any applications which already *have* such documents, whether deliberately or not. I wouldn't want us to do that.

> And I think operations to some special data types, like reference and geographical point, should be included in document and example code as well.

Could you give details as to what you'd want to see in those examples? It looks like you've already understood `DocumentReference` clearly enough to use it correctly - without the ID issue, your code would have worked. Likewise the `GeoPoint` struct feels very simple - any example I'd give would be pretty trivial. I'm very happy to add more examples, but I want them to be genuinely useful ones.

I'll close this issue now, but if you add another comment with details of what you'd like to see in samples, I'll see what I can do. (I don't maintain the documentation on firebase.google.com, but I can ask for more documentation there too.)
