### ISSUE TITLE
FirestoreProperty: allow ignoring null values

### ISSUE THREAD

**Issue by kinex** [googleapis/google-cloud-dotnet#3705]
I would like to prevent serializing null values when using `DocumentReference.SetAsync` to keep documents cleaner and to save storage space. Something like this would be useful:
```c#
[FirestoreProperty(nullValueHandling: NullValueHandling.Ignore)]
public string Name { get; set; }
```
Is there any way to do this currently?

**Comment by amanda-tarafa** [comment]
Hi @kinex, you can create your own custom converter to handle this.
Take a look at the docs on [Costum Converters](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/datamodel.html#custom-converters).

**Comment by kinex** [comment]
Hi @amanda-tarafa, thanks for the idea. I noticed documentation says "conversion methods never receive null references". Anyway, I tried this since ignoring also empty string would be possibly ok in my case:

```c#
public class IgnoreNullConverter : IFirestoreConverter<string>
{
    public object ToFirestore(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return FieldValue.Delete;
        }
        return value;
    }

    public string FromFirestore(object value)
    {
        return value as string;
    }
}
```
But this throws exception `System.ArgumentException: 'Delete cannot appear in document data when overwriting Arg_ParamName_Name'`. I guess the exception refers to the name parameter which I am providing to FirestoreProperty. I cannot remove that parameter so it seems this approach does not work.

**Comment by amanda-tarafa** [comment]
I'm writing a sample now. But basically you need to write a [Costum Document Converter](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/datamodel.html#document-converters) (sorry I thought I had been explicit about that but I see I wasn't). As you well point out other Custom Converters don't support null values.

**Comment by amanda-tarafa** [comment]
@kinex Take a look at #3707 which should be of help. I understand though that if you want to ignore null values for all string properties in all your models, you might need to end up writing several document converters and that might be cumbersome.

**Comment by kinex** [comment]
@amanda-tarafa Thanks for the code sample! That is useful at least for simple projects. In my case there are around 20 data classes where I would like to ignore null values for specific fields which may be strings or references to some other classes.

I actually started implementing a generic version of a converter based on your code sample, but it started to look too complex risking both performance and stability. So I decided to give up and keep the null values for now. 

It would be nice if you could implement some simpler solution for this issue in some future update. The solution I presented in this issue description is similar to what e.g. Json.NET has.

**Comment by jskeet** [comment]
We can ask the Firestore team for their opinion, but I *suspect* we'll want to see more evidence of other users wanting this before implementing it.

It's worth bearing in mind that Json.NET is a library *dedicated* to serialization/deserialization. That's its only job... so it's not surprising that it has more advanced serialization capabilities that the Firestore library, which is primarily about communicating with Firestore, with serialization just being part of that. The .NET Firestore library is already more advanced than the libraries in other languages, in terms of serialization customization - I doubt that we'll want to increase that gap without more users requesting it.

**Comment by kinex** [comment]
Ok, that sounds like a good plan. The reason why I am not very used to seeing those null values in Firestore is that my initial experience with Firestore was a Flutter app where excluding null values is simple as the Flutter's JSON serializer supports it easily. So it has become my practice not to write null values to Firestore. Now my other app based on .NET Firestore accesses the same database and it writes null values..... At least I can now easily detect which app has written a document. But it is possible that this is only an issue in my head, so it is good to listen what other users say. Thanks!

**Comment by jskeet** [comment]
Right, I've talked to the Firestore team, and they agree that we'd want to hear from more users before implementing this. In particular, they note that one of the problems users sometimes observe is failing to find documents because they omitted a field. Writing a field with a value of null and not writing the field at all are not equivalent, and it's almost always a better idea to write the null value if you know this is a field which is logically part of a document.

I'm going to close this issue now, but again, thank you for the suggestion, and we'll keep an eye out for similar ideas.

**Comment by kinex** [comment]
OK. For possible comments from other developers I will present here one real-world sample use case where I have found it useful not to write null values. See this data model (simplified):
```c#
public enum EventType { Refuel, Expense, Service, Trip };

class Refuel { } // refuel event details
class Expense { } // expense event details
class Service { } // service event details
class Trip { } // trip details

// common data for all event types and container for event type specific details
class Event
{
    public string Id { get; set; }
    public DateTimeOffset DateTime { get; set; }
    public string Notes { get; set; }

    public EventType EventType { get; set; }

    public Refuel Refuel { get; set; }
    public Expense Expense { get; set; }
    public Service Service { get; set; }
    public Trip Trip { get; set; }
}
```
For a comparison here is the same class defined in Flutter/Dart where I can omit the null values easily as I want:
```dart
@JsonSerializable()
class Event
{
  String id;
  DateTime dateTime;
  String notes;

  EventType eventType;

  @JsonKey(includeIfNull: false)
  Refuel refuel;

  @JsonKey(includeIfNull: false)
  Expense expense;

  @JsonKey(includeIfNull: false)
  Service service;

  @JsonKey(includeIfNull: false)
  Trip trip;
}
```

`Event` contains common data to all events. Depending on `Event.EventType` only one of the `Refuel`/`Expense`/`Service`/`Trip` contains event specific data (others must be null). 

So when I am looking at those documents for example in Firebase console while debugging my app, I wouldn't like to even see those null values, because they just make reading the documents harder. Also, I don't know how much those null values take space, but if and when my app has millions of users those unnecessary null values may start to cost me.

Someone could say I should move `Refuel`/`Expense`/`Service` and `Trip` to a different collection and only link them with an id field. I did consider that also but I like this current schema. it is easy to use and also cost effective.

**Comment by MilosGrgov90** [comment]
Any news on this topic ? It's quite complicated using custom converter, from code maintenance perspective this adds many lines of code if documents are complicated and consists of many properties. If there is a list inside document, this adds extra complexity... Would be good to have some functionality like its mentioned, and not storing values we don't need for the document.

**Comment by jskeet** [comment]
@MilosGrgov90: I haven't heard anything from the Firestore team about this in the last 2 1/2 years, no. I'll ping them to see if there has been any activity around this in other languages.

**Comment by ZackOfAllTrades** [comment]
bump

**Comment by jskeet** [comment]
@ZackOfAllTrades: Nothing has changed here as far as I'm aware, and we've been putting less of our resources on "vertical integrations" recently so I wouldn't expect it to change any time soon. I suspect that back in 2019 we didn't have as much flexibility in user-defined conversions though - you should be able to write your own serializer for whatever behavior you want without *too* much effort. https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Firestore/latest/datamodel#custom-converters is the best documentation for that at the moment (and the source code, of course).

**Comment by rjgotten** [comment]
> you should be able to write your own serializer for whatever behavior you want without too much effort.

Except if you have to write a converter that has to do something like special-case behavior for unknown/unparsable enum values and revert them to `null`. Then you're just boned.

Colleague of mine just ran into that one head-first, and had no way of resolving it other than coding a triplet of three properties:
a public get/set auto-property; a private get-only property marked as `[FirestoreProperty]` to serialize the value; and a private set-only property marked as `[FirestoreProperty]` with the same name, to provide the specific parsing logic. Basically implementing the converter as a one-off inside the setter.

For each individual property that you run across.

I don't know who decided to special case null values and explicitly segregate them from being touched by `IFirestoreConverter`, but I do know with fair certainty that that, in hindsight, was a very, **very** poor decision.
