### ISSUE TITLE
Trace, question: do not trace certain routes

### ISSUE THREAD

**Issue by nover** [googleapis/google-cloud-dotnet#3717]
Pardon me if this is already covered somewhere in documentation but I couldn't find it...

Is it possible to configure / call something to avoid a certain call/route being traced?
We have a `/monitoring/shallow-health-check` route that is being polled by Kubernetes, and I honestly do not care for traces on this route.

Thanks in advance.

**Comment by amanda-tarafa** [comment]
Hi @nover,
On `Google.Cloud.Diagnostics.AspNetCore.TraceServiceOptions` you can set `TraceFallbackPredicate` that will help determine if an `HttpRequest` should be traced. One thing to note though is that if the request already has a trace header, the predicate won't be evaluated and the request will be traced anyway.
Another note, the `ignoreHealthChecks` parameter when creating the predicate refers to GAE healthchecks, so you can't rely on it to skip your own health check route.
Let me know if this solves your question.

**Comment by nover** [comment]
@amanda-tarafa Yes that was just what I was looking for, thanks.
