### ISSUE TITLE
Access DialogFlow sessions with gRPC API

### ISSUE THREAD

**Issue by DJ4ddi** [googleapis/google-cloud-dotnet#3727]
#### Environment details

  - OS: Windows 10 via Azure Function Runtime 2.0.12858.0
  - .NET version: Core 2.1
  - Package name and version: Google.Cloud.Dialogflow.V2 v1.2.0-beta01

#### Goal

I want to modify the contexts of a session initiated in DialogFlow from my webhook running on Azure Functions. I therefore can not use the Node.js library within DialogFlow that would allow me to do this in a fairly simple manner. My idea to get around this was to use the C# client library instead.

#### Issue

While I managed to get the library connected and authorized (tested by accessing the agent and its intents, which all show up fine), I am unable to access any DialogFlow sessions. Calls to `ContextsClient.ListContexts` always return an empty collection, `CreateContext` and `DeleteContext` have no effect on the conversation.

#### Reproduction

This is the code I use to create the client. The embedded JSON file contains an authorized service account with DialogFlow API administrator permissions.
```csharp
// Create authorized client
var credentials = GoogleCredential.FromStream(Assembly.GetExecutingAssembly()
  .GetManifestResourceStream("Namespace.Of.GoogleApiCredentials.json"))
  .CreateScoped(ContextsClient.DefaultScopes);
var channel = new Channel(ContextsClient.DefaultEndpoint.ToString(), credentials.ToChannelCredentials());
var client = ContextsClient.Create(channel);
```

With this, I attempt to modify context information of a `WebhookRequest` parsed with Protobuf.
```csharp
WebhookRequest request; // Received from DialogFlow, parsed with Protobuf
client.ListContexts(request.Session); // Expected: All contexts of the session; Actual: Empty collection

var context = client.CreateContext(request.Session, new Context {
  ContextName = new ContextName(request.QueryResult.OutputContexts.First().ContextName.ProjectId,
    request.QueryResult.OutputContexts.First().ContextName.SessionId,
    "new-context"),
  LifespanCount = 4
}); // Expected: Context added to existing session; Actual: Context added to new session with the same ID
client.ListContexts(request.Session); // Expected: Context added to session; Actual: 1 Context
client.DeleteAllContexts(request.Session); // Expected: All contexts removed from session; Actual: Only previously added context is cleared
```

#### Conclusion

I thought this would be the primary use case of the API. Is it even supposed to be possible? If so, did I make a mistake with the session identifier (directly taken from the request object)?

**Comment by jskeet** [comment]
I suspect this is really a matter for the Dialogflow API team. The maintainers of this repository aren't experts in the individual APIs - we make sure that client libraries are available to talk to the API, but we don't know the details.

In this case it sounds like the session isn't being recognized for some reason, but I don't know the details of that.

One thing I can help you with is making the client creation simpler. Once you've created the credentials, you can use:

```csharp
var client = new ContextsClientBuilder { TokenAccessMethod = credentials.GetAccessTokenForRequestAsync }.Build();
```

Or load the JSON resource once, and then use:

```csharp
var client = new ContextsClientBuilder { JsonCredentials = json }.Build();
```

These won't help with the problem you're seeing though. For that, I'd suggest using one of the resources from the [Dialogflow support page](https://cloud.google.com/dialogflow/docs/getting-support).

**Comment by DJ4ddi** [comment]
> I suspect this is really a matter for the Dialogflow API team. The maintainers of this repository aren't experts in the individual APIs - we make sure that client libraries are available to talk to the API, but we don't know the details.

Truth be told, I figured that would be the most likely answer. I now posted the same issue [here](https://issuetracker.google.com/u/1/issues/144301451).

Thanks for the link and recommendation, I'll look into that.

**Comment by jskeet** [comment]
Righto. I'll close this issue now, but if it does turn out to be anything in the client library, please add another comment and I'll reopen it straight away. Best of luck!
