### ISSUE TITLE
[Firestore] Support for "in" queries

### ISSUE THREAD

**Issue by lluismontero** [googleapis/google-cloud-dotnet#3783]
Earlier this month Firestore announced support for **"in"** queries (https://firebase.googleblog.com/2019/11/cloud-firestore-now-supports-in-queries.html). 

In many of the client libraries the option is already available, but not in the .NET SDK (https://cloud.google.com/firestore/docs/query-data/queries#in_and_array-contains-any). Is there any ETA when the "in" operator will be available?

**Comment by jskeet** [comment]
Hi @lluismontero, thanks for the heads-up. I haven't talked with the Firestore team about this, but I'd imagine we'd want to support it as soon as we can. Just to set expectations, it definitely won't be before Q1 2020... but I'll see if we can do it then :)

**Comment by lluismontero** [comment]
Hi @jskeet, thanks for your response. Is there any workarround to run that kind of queries?

**Comment by jskeet** [comment]
@lluismontero: Not without digging lower down than I suspect you want to go. (I mean, we do provide the underlying `V1.FirestoreClient` so you could make the query call yourself, but it'll be pretty painful, I'm afraid. It's a big cliff between the abstraction layers.)

**Comment by lluismontero** [comment]
Thanks anyway, I'll keep an eye on the SDK updates

**Comment by jskeet** [comment]
We've now released Google.Cloud.Firestore version 1.1.0 which contains this functionality. So I was wrong on the "definitely not before Q1 2020"...
