### ISSUE TITLE
Google.Cloud.Speech.V1 support on Xamarin

### ISSUE THREAD

**Issue by philipag** [googleapis/google-cloud-dotnet#3896]
**Is your feature request related to a problem? Please describe.**

There have been a few requests for Xamarin support but they are all old and closed so given that it's almost 2020 I would like to open a new one.

1. I am successfully using Google.Cloud.Speech.V1 with a Xamarin.Forms Android project so even though this is not officially supported it appears that the GRPC implementation exists for Android and is functional.  Since it is functional it's probably worth adding some tests for this target and officially supporting it?

2. However, when adding Google.Cloud.Speech.V1 to a Xamarin.Forms iOS project it compiles with the error "Error while loading assemblies: /../bin/iPhone/Debug/grpc_csharp_ext.x64.dll" so it seems a compatible GRPC implementation is not included. 

 **Describe the solution you'd like**
It seems to be quite important for a .net library to support Xamarin these days.  Only targeting .net desktop makes little sense and cripples the library.  Is it possible to add Xamarin iOS GRPC support and make these libraries functional under Xamarin iOS and officially support Xamarin Android & iOS?  

 **Describe alternatives you've considered**
Competing speech platforms with better platform support.

 **Additional context**
Seems like this GRPC project support OSX which means it would be fairly simple to add iOS support: https://github.com/grpc/grpc/tree/master/src/csharp

**Comment by jskeet** [comment]
I'd love to be able to say yes to this, but I'm afraid our small team just doesn't have the bandwidth to support Xamarin at the moment. The ongoing effort required to maintain integration tests for all the various platforms and the resources to be able to diagnose problems that developers might run up against, is just more than we have space for at the moment. Additionally, the libraries are really designed for server-side use, in terms of auth and also connectivity. A significant investment would be required to give a decent experience for mobile customers.

I really do hope it's feasible at some point, but I'd be surprised if we have the bandwidth to do this in 2020.
