### ISSUE TITLE
Webhook call failed. Error: DEADLINE_EXCEEDED

### ISSUE THREAD

**Issue by HilalRather** [googleapis/google-cloud-dotnet#3903]
I am getting the the issue <b> code": 4, "message": "Webhook call failed. Error: DEADLINE_EXCEEDED</b> while working with <b> Google.Cloud.Dialogflow.V2</b> <i>C# library</i>.
Although the webhook call gets executed successfully and returns the expected result.

Any help would be appreciated.

Thanks.

**Comment by jskeet** [comment]
(I've transferred this to google-cloud-dotnet repository as that's where the Google.Cloud.Dialogflow.V2 package lives.)

When you say "the webhook call gets executed successfully and returns the result" could you clarify what you mean by that? Are you certain that it's returning successfully *when called by Dialogflow*? Do you have logs of how long it takes to return the response? In what context are you seeing the error - does it work in the simulator for example, but fail with actual devices? The more information you can provide, the more likely we are to be able to help.

**Comment by HilalRather** [comment]
Hello Jon,


I am using the (Google.Cloud.Dialogflow.V2) to implement STT and TTS features in my project. When I run the existing dialogflow project using the simulator and the Google Assistant, the results are perfect. However, when trying to call from StreamingDetectIntent API using my codebase, it fails to return the expected results and the status displayed is: Webhook call failed. Error: DEADLINE_EXCEEDED.



The response of StreamingDetectIntent API should normally contain the webhook values for Fulfillment Text and Fulfillment Message (These are the properties of StreamingDetectIntent response). On the contrary, in my case, they return the default values defined in the dialolgflow.


Thanks,

Hilal Rather

________________________________

**Comment by jskeet** [comment]
So just to clarify, are *you* providing the webhook, or is this a separate webhook?

Please could you show your call to StreamingDetectIntent? If you're expecting it to call back to your webhook, do you have logs to indicate whether that happened or not?

I suspect this *may* be an issue that we need to refer to the Dialogflow team - the maintainers of this repository aren't very familiar with all the different APIs; we just maintain the client libraries that make sure requests and responses flow appropriately. We can keep investigating a bit here in case it *is* a client library problem, but I suspect it may be something deeper about either how the API is expected to work, or how you're using it.

**Comment by HilalRather** [comment]
No, I am not providing the webhook and this is not a separate webhook. I am calling my existing dialogflow project where I already mention the webhook URL and I have verified (by debugging the code) that the webhook project is getting the call from Dialogflow and found it (codebase) returning the expected result. But, the response of <i>StreamingDetectIntent</i> API should normally contain the webhook values for Fulfillment Text and Fulfillment Message (These are the properties of StreamingDetectIntent response). On the contrary, in my case, they return the default values defined in the dialolgflow.

The following is the StreamingDetactIntect call:

string token = GoogleAuthentication.GetToken();
         GoogleCredential googleCredential = GoogleCredential.FromAccessToken(token);
         Channel channel = new Channel(
         SessionsClient.DefaultEndpoint.Host, SessionsClient.DefaultEndpoint.Port, googleCredential.ToChannelCredentials());

         
         SessionsClient client = SessionsClient.Create(channel);
         SessionsClient.StreamingDetectIntentStream duplexStream = client.StreamingDetectIntent();
         SessionName sessionName = new SessionName("MyDialogFlowProjectID", "audioTest");

         Task responseHandlerTask = Task.Run(async () =>
         {
            IAsyncEnumerator<StreamingDetectIntentResponse> responseStream = duplexStream.ResponseStream;

            while (await responseStream.MoveNext())
            {
               StreamingDetectIntentResponse response = responseStream.Current;

               if (response != null)
               {
                  
                  Console.WriteLine($"Received response: {(response)}");
                  Console.WriteLine($"Received response: {response?.QueryResult?.FulfillmentText}");

                  if (!string.IsNullOrEmpty(response?.QueryResult?.FulfillmentText))
                  {
                     if (!response.OutputAudio.IsEmpty)
                     {
                        NAudio.Wave.WaveOutEvent waveOut = new NAudio.Wave.WaveOutEvent
                        {
                           DeviceNumber = -1,
                           NumberOfBuffers = 3,
                           DesiredLatency = 300,
                           Volume = 0.5f
                        };                      
                        WaveFileReader provider = new WaveFileReader(new MemoryStream(response.OutputAudio.ToByteArray()));
                        waveOut.Init(provider);
                        waveOut.Play();
                     }
                 }
               }


               //Console.WriteLine($"Received response: {response}");

            }
               
            
           
         });
         bool done = false;
         while (!done)
         {
            InputAudioConfig inputAudioConfig = new InputAudioConfig()
            {
               AudioEncoding = AudioEncoding.Linear16,
               LanguageCode = "en",
               SampleRateHertz = 16000,
               SingleUtterance = true,
             
            };
            OutputAudioConfig outputAudioConfig = new OutputAudioConfig()
            {
               AudioEncoding = OutputAudioEncoding.Linear16,
               SampleRateHertz = 16000,             

            };

            QueryInput queryInput = new QueryInput()
            {
               AudioConfig = inputAudioConfig
            };

            //RequestJson["originalDetectIntentRequest"]["payload"]["user"]["accessToken"].ToString();
            var accessToken = "";
            QueryParameters queryParameters = new QueryParameters
            {
               Payload = new Struct
               {
                  Fields = {

                              { "user" ,Value.ForStruct
                                    (new Struct{
                                       Fields =
                                       {
                                          {
                                             "accessToken",Value.ForString(accessToken)
                                          }
                                       }
                                    })
                              }

               }
               }
            };

            StreamingDetectIntentRequest req = new StreamingDetectIntentRequest()
            {
               QueryInput = queryInput,
               Session = sessionName.ToString(),
               QueryParams = queryParameters,
               OutputAudioConfig=outputAudioConfig
               
               


            };
            // Send first request informing we are going to send audio to be recognized.
            await duplexStream.WriteAsync(req);
            object writeLock = new object();
            bool writeMore = true;
            NAudio.Wave.WaveInEvent waveIn = new NAudio.Wave.WaveInEvent
            {
               DeviceNumber = 0,
               WaveFormat = new NAudio.Wave.WaveFormat(16000, 1)
            };
            waveIn.DataAvailable +=
                   (object sender, NAudio.Wave.WaveInEventArgs waveInEventArgs) =>
                   {
                      lock (writeLock)
                      {
                         if (!writeMore)
                         {
                            return;
                         }

                         StreamingDetectIntentRequest request = new StreamingDetectIntentRequest
                         {
                            InputAudio = ByteString.CopyFrom(waveInEventArgs.Buffer, 0, waveInEventArgs.BytesRecorded)
                         };

                         duplexStream.WriteAsync(request);

                         int value = Math.Abs(BitConverter.ToInt16(waveInEventArgs.Buffer, (waveInEventArgs.BytesRecorded - 2)));
                         // Console.WriteLine("value:"+ value);
                         if (value < 3)// For now hardcoded
                         {
                            Console.WriteLine("listing stopped");
                            waveIn.StopRecording();
                            // waveIn.Dispose();
                         }
                         done = true;                       
                      }
                   };
            waveIn.StartRecording();
            Console.WriteLine("Speak now.");
            await Task.Delay(TimeSpan.FromSeconds(10));
            // Stop recording and shut down.
            waveIn.StopRecording();
            lock (writeLock)
            {
               writeMore = false;
            }
           
         }

            await duplexStream.WriteCompleteAsync();
            await responseHandlerTask;
         
         Console.WriteLine("Response Finished");
         Console.ReadLine();
 return 0;

**Comment by jskeet** [comment]
I'm afraid at this point I really don't understand enough about what you're trying to achieve to help - it does sound like you need a Dialogflow expert. You may well want to look at [the Dialogflow support page](https://cloud.google.com/dialogflow/docs/getting-support) for that.

One possible issue though: you're currently looping round, and sending another "first request" with the audio config. I don't believe you're meant to do that - I believe you should send *one* initial request with the audio config and then *all* subsequent requests in the duplex stream should be audio data, basically. Although it's not clear to me how often you're actually looping, as it seems to be based on "value" that isn't clearly described.

**Comment by HilalRather** [comment]
@jskeet, <span>&#128521;</span>   hahaha, don't be afraid I am not implementing any rocket science here.
Let me clear the air about the <b>value</b>.
<b><i>
 int value = Math.Abs(BitConverter.ToInt16(waveInEventArgs.Buffer, (waveInEventArgs.BytesRecorded - 2)));
                     // Console.WriteLine("value:"+ value);
                     if (value < 3)// For now hardcoded
                     {
                        Console.WriteLine("listing stopped");
                        waveIn.StopRecording();
                        // waveIn.Dispose();
                     }
</b>
The above code snippet is basically trying to detect noise and the hardcoded value i.e, <b>3</b> 
is the threshold value and it is temporary for now.</i>

Thanks for taking the time to reflect on these.
@jskeet It would help immensely if you can refer me someone at Dialogflow support

**Comment by jskeet** [comment]
I can't refer you to anyone specific - just the options on the [support page](https://cloud.google.com/dialogflow/docs/getting-support) as mentioned before. I suggest you use the [Google Group](https://groups.google.com/forum/#!forum/dialogflow-enterprise-edition-users) for this - but take some time to explain really clearly what you're trying to do, and what you're seeing, as that's still unclear to me. For example, you talk about receiving an error, but also receiving a response with default values - are these in the same response? If not, when do you receive which?

I'd definitely suggest adding some more logging into your code so you can easily describe exactly how many requests you've made, and what those requests contain - along with what responses you've received.

I'll close this issue now as I don't believe there's anything more to be done within this repository, but please add a comment if you work out more information suggesting it *is* a library issue, and we can reopen.

**Comment by HilalRather** [comment]
@jskeet You could not close the issue without any genuine reason or solution to it, I need help.
I am not the only one who is facing this issue.
https://github.com/googleapis/nodejs-dialogflow/issues/341

**Comment by jskeet** [comment]
I close issues when it's not appropriate to keep in this repository. If others are facing the same issue *in other languages* then it strikes me as unlikely to be a bug in the client library, which is what this repository is for. Instead, it's likely to be more of an issue that the Dialogflow API team should be aware of - which is why I specifically directed you to the group about Dialogflow.
