### ISSUE TITLE
Google.Cloud.Bigtable.V2 and Google.Cloud.Bigtable.Admin.V2 issue during upgrade to 1.1.0

### ISSUE THREAD

**Issue by pblachut** [googleapis/google-cloud-dotnet#3911]
I have an issue during upgrade Google.Cloud.Bigtable.V2 and Google.Cloud.Bigtable.Admin.V2 packages from version 1.0.0 to version 1.1.0. I observed increase of write and read times. 

In my scenario write and read times went up from 3 to 4 times.

Tried to find what has been changed between these versions but release notes are empty.

https://github.com/googleapis/google-cloud-dotnet/releases/tag/Google.Cloud.Bigtable.V2-1.1.0
https://github.com/googleapis/google-cloud-dotnet/releases/tag/Google.Cloud.Bigtable.Admin.V2-1.1.0

Can you provide me with more detailed release notes? 

#### Environment details

  - OS: 
mcr.microsoft.com/dotnet/core/aspnet:3.0.0
  - .NET version: 
.net core 3.0
  - Package name and version:
Google.Cloud.Bigtable.V2 1.1.0
Google.Cloud.Bigtable.Admin.V2 1.1.0

**Comment by jskeet** [comment]
The version histories are here, in terms of API changes

- https://googleapis.dev/dotnet/Google.Cloud.Bigtable.V2/latest/history.html
- https://googleapis.dev/dotnet/Google.Cloud.Bigtable.Admin.V2/latest/history.html

... but I would be very surprised to see any changes in performance.

Do you have a sample we could use to reproduce the problem? I would expect the admin API to be irrelevant here, if this is reads and writes for a regular table.

**Comment by pblachut** [comment]
Thank you for information. Currently I don't have enough time to prepare repro, will just stay with the version 1.0.0. 

When I prepare a repro and the issue will be still present then I will reopen this ticket.
