### ISSUE TITLE
Storage : ListObjectsOptions does not have "fields" Parameter

### ISSUE THREAD

**Issue by mitulpanch** [googleapis/google-cloud-dotnet#4019]
https://cloud.google.com/storage/docs/json_api/v1/objects/list

fields parameter missing from C# client library

Please provide link if i am missing something

**Comment by jskeet** [comment]
No, we don't currently support the `fields` parameter. We can definitely do so, but if you could provide a little more information about your use case, that would help us in terms of designing the API surface.

**Comment by mitulpanch** [comment]
Actually, We want to Search files in Directory / SubDirectories.

I think we can do this using ListObjects API only.
to do this we just want names, ContentType of all files so further we can filter it with name contains-filter, wildcard search and mime-type filter.
(this is not a good solution but immediately we can do this for the client)

there may be thousands of files in subfolder structure. 

https://cloud.google.com/storage/docs/json_api/v1/how-tos/performance
This says that performance can be improved if we use fields. 

if anything is there which can search in folders with prefix and wildcard types of filters, then this is not required.

**Comment by jskeet** [comment]
Thanks very much for the context. I'll prototype this, and then see what difference it makes on a bucket with lots of objects in. If it makes the difference we hope it will, I'll be more than happy to merge the change. If it doesn't, we may want to look at other options.

**Comment by jskeet** [comment]
Right, I've prototyped this, and it increased the rate (on my laptop) from ~2500 objects per second to ~4500 objects per second, using a fields parameter of "items(name,contentType),nextPageToken".

There are two approaches we could make to the API here:

- Just accept a string, and link to the standard fields documentation
- Accept an array or `IEnumerable<string>` and perform the comma-joining ourselves

We'll either need to add `nextPageToken` ourselves, or document that it should be included if you want to be able to use more than a single page of data.

I'm tempted to go the route of "this is a reasonably rare use case: add it as a string and document requirements" - the less library code that gets in the way, the more flexibility users will have. Any thoughts on this? (The person who will review the PR is back on Monday, so there's no *desperate* urgency here.)

**Comment by mitulpanch** [comment]
thank you,

My thought is -
Original JSON API accept fields as comma-separated string. that same setting will be good.
JSON API ignores nextpagetoken if it is not passed in fields parameter.

**Comment by jskeet** [comment]
Right - so it sounds like #4023 would be okay with you. That's good to know - thanks!

**Comment by jskeet** [comment]
This is now released in Google.Cloud.Storage.V1 version 2.5.0.

**Comment by mitulpanch** [comment]
Got it. Thanks a lot.
