### ISSUE TITLE
Timestamp values are incorrectly rounded when retrieved from BigQuery

### ISSUE THREAD

**Issue by 47th** [googleapis/google-cloud-dotnet#4031]
#### Environment details

  - OS: Windows
  - .NET version: .NET Core 2.2
  - Package name and version: Google.Cloud.BigQuery.V2 1.4.0

#### Steps to reproduce

  1. Store value 2004-07-26 15:25:28.173333 in a timestamp column in BigQuery
  2. Retrieve this value using BigQueryClient.ExecuteQueryAsync

The obtained value is 2004-07-26 15:25:28.173332

The issue is most likely in BigQueryRow.TimestampConverter. For the value above BigQuery returns 1090855528.1733329 as the number of seconds, which is 1090855528173332.9 microseconds. The decimal 9 is then truncated upon converting to long.

**Comment by jskeet** [comment]
I'll look at this on Monday, but personally I think it's reasonable to truncate 1090855528.1733329 to 1090855528.173332; timestamps tend to be converted rather than rounded up. However, if this only ever happens due to floating point representations, it *may* be reasonable to round. I'll have to look in detail.

**Comment by 47th** [comment]
The same value is displayed as 2004-07-26 15:25:28.173333 in BigQuery UI. Also UNIX_MICROS returns 1090855528173333 for it. Everything looks like BigQuery UI rounds this value.

**Comment by jskeet** [comment]
Thanks for the info. Will dive into the code on Monday.

**Comment by jskeet** [comment]
Fortunately it looks like no rounding is required - just parsing as decimal. The server returns a string with the value "1.090855528173333E9" - it's parsing that string as a double that's losing precision.

**Comment by jskeet** [comment]
The fix is now merged, but we have a few other BigQuery changes to implement before we do another release. Shouldn't be very long though.
