### ISSUE TITLE
Dialogflow - Sentiment analysis - SentimentAnalysisResult obj is null sometimes

### ISSUE THREAD

**Issue by ganesh-gawande** [googleapis/google-cloud-dotnet#4032]
I am trying to do sentiment analysis from the c# code. I have enabled the sentiment analysis to true.

`DetectIntentRequest detectIntentRequest = new DetectIntentRequest();
detectIntentRequest.QueryInput = queryInput;
detectIntentRequest.SessionAsSessionName = _sessionName;
detectIntentRequest.QueryParams = new QueryParameters();
detectIntentRequest.QueryParams.SentimentAnalysisRequestConfig = new SentimentAnalysisRequestConfig();
                detectIntentRequest.QueryParams.SentimentAnalysisRequestConfig.AnalyzeQueryTextSentiment = true;`

For few sentences, I get the SentimentAnalysisResult in present response. But for few sentences the SentimentAnalysisResult is null in response. 

For example: When i send following as query string to detectIntent. 
 Show me possibilities not in Maharashtra - **This gives valid result.** 
 Show me possibilities in Maharashtra but not in pune - **This gives SentimentAnalysisResult as null**

**Comment by jskeet** [comment]
I think it's unlikely that this is a client library issue - the maintainers of this repository don't tend to know details about the specific APIs; our job is to make sure that you can make requests to the APIs accurately and easily. I suggest you follow one of the support routes on the [Dialogflow support page](https://cloud.google.com/dialogflow/docs/getting-support) where you'll be able to find people who know more about the details of the API itself.

One thing I *can* say, however, is that you can use object initializers to make your code simpler. The code you posted would be more simply written as:

```csharp
DetectIntentRequest detectIntentRequest = new DetectIntentRequest 
{
    SessionAsSessionName = _sessionName,
    QueryParams = new QueryParameters
    {
        SentimentAnalysisRequestConfig = new SentimentAnalysisRequestConfig { AnalyzeQueryTextSentiment = true }
    }
};
```

I'm going to close this issue as I don't believe there's any change required within the client library, and unfortunately we can't help you with the API-specific aspects. Hopefully you'll be able to find help on one of the Dialogflow support routes though.
