### ISSUE TITLE
ListObjectsAsync - `IAsyncEnumerable`, but not `GetAsyncEnumerator()`

### ISSUE THREAD

**Issue by kierenj** [googleapis/google-cloud-dotnet#4110]
I see that `ListObjectsAsync` returns a `PagedAsyncEnumerable`. Forgive me if I'm missing a subtlety of async (it would not be the first time). But it seems to not play very nicely with C# 8.0?

I think if the `GetEnumerator` method was instead called `GetAsyncEnumerator`, I could use `await foreach`? It'd be a good advantage since I think all the syntactic sugar means I can `.Select()` on that to abstract the underlying `Data.Object` for consumers of my API.

Edit: also, I tried to make a wrapper class to handle this. But so long as `Google.Cloud.Storage.V1` was referenced, the `System.Interactive.Async` package conflicted: the `IAsyncEnumerator` type was defined both in that and the `System.Runtime` package. Is `System.Interactive.Async` no longer needed perhaps?

Ah, in fact, even if I refer to `IAsyncEnumerator` anywhere in my code, I get that conflict.

**Comment by jskeet** [comment]
The `IAsyncEnumerable<T>` used in all of the released packages is the one from `System.Interactive.Async` 3.2. We are actively working on migrating this as part of a major version bump, tracked in #3519. It's a massive job though, partly as at the same time we're changing the code generator used for API-specific generation... which in turn involves changing how each API is configured.

We're making steady progress, and hoping for betas in late January / early February, hopefully with a GA in late February / early March. For more details, see the [major version plan document](https://googleapis.github.io/google-cloud-dotnet/docs/major-version.html)

If you're massively eager to try this, the code in the [next-major-version branch](https://github.com/googleapis/google-cloud-dotnet/tree/next-major-version) uses the new version of GAX (which is in the GAX master branch but not released on nuget.org yet). If you run `./build.sh Google.Cloud.Storage.V1` from the root of the next-major-version branch, you'll that will fetch GAX and build it locally, and you'll end up with a `Google.Cloud.Storage.V1` build which *will* work with `await foreach`. But you may just want to wait for the releases :)

I'll close this issue now as it's already being tracked effectively in #3519.

**Comment by kierenj** [comment]
Ah thats great thanks. I apologise I didnt find the existing issue.

**Comment by jskeet** [comment]
Not a problem at all - it's not exactly obvious that the gRPC upgrade is related to async sequences (although that's actually why gRPC took a major version bump too).
