### ISSUE TITLE
[BigQuery] Discussion about when to throw in insert operations (revisit query operations as well)

### ISSUE THREAD

**Issue by amanda-tarafa** [googleapis/google-cloud-dotnet#4199]
#4200 Makes insert methods return the response object (or a wrapper) with information about rows that failed to insert. These methods were previously void, so the only way to obtain information about failed rows was through a GoogleApiException that was thrown. The SuppressInsertErrors option controlled when the exception was thrown or not, false by default, if set to true the exception wouldn't be thrown. This made more sense when used in conjunction with the SkipInvalidRows options set to true, which meant that the caller was OK with a partial insert (and not knowing about failed rows).
Now that the insert methods are not void should we keep the SuppressInsertErrors option? Main worry is about side effects for code that never set this option and thus has been expecting an exception in all cases except when an insert is completely successful, i.e. all rows are inserted. Code like this will still build, but might not function properly.

**Comment by amanda-tarafa** [comment]
Options are, I think (all of these are about insert failures because of incorrect rows, all other failures, like network, access, etc. will be thrown regardless).

1. Leave as is in #4200: for all but complete success throw, unless SuppressInsertErrors is true.
**Pros**: Code that has never set SuppressInsertErrors won't be affectedm they'll get the same exceptions as always. This is the least breaking.
**Cons**: To me, now SkipInvalidRows and SuppressInsertErrors seem redundant. If I already set SkipInvalidRows I'm saying that I'm OK with a partial insert, so I don't expect to get an exception when that happens, or to have to set another option so that I don't get the exception.
2. Remove SuppressInsertErrors and never throw, the response object contains enough information so as to know whether the failure was complete or partial and also has some helper ThrowOnAnyError() methods.
**Pros**: We always get the best info possible, which is contained in the response object and not the exception.
**Cons**: It's not idiomatic to not throw when the insert failed completely.
This will break all clients that were relying on an exception on any insert errors.
3. Remove SuppressInsertErrors and only throw when no rows were inserted because either SkipInvalidRows is false and some rows were invalid or all rows were invalid (that is SkipInvalidRows means we are OK with a partial insert not with a full failure).
**Pros**: To me this seems the more idiomatic solution.
**Cons**: The exception contains less information than the response, and when the exception is thrown there is no way to access the response (maybe include the response in the exception, but where).
This will break all clients that were relying on exceptions on partial failures.

Personally I would favour 3 except for the fact that we don't include all the info in the exception. If we don't find a good way to include the response on the exception then I'd favour 2.
Although I agree that even when major version bumping we should try to break clients as little as possible, this change will be included in a major version bump, and developers with production code should take care on reading the docs about breaking changes. I'm unsure about to what lengths we should go to protect developers that might not read major version bump docs, if we should carry over some design decissions that were made in a different set of circumstances. I believe 1 made sense when methods were void, but not anymore.

**Comment by jskeet** [comment]
For option 1, if you mean that setting `SuppressInsertErrors` is redundant if `SkipInvalidRows` is set to true, then I see what you mean - but I think it's easier to reason about them as independent concepts.

I'd definitely like to rule out option 2 - that seems far too breaking to me.

I'm not sure about option 3. If I'm inserting 10000 rows, should there really be that much difference between 0 rows being inserted and 1 row being inserted? I'd be surprised if they were handled differently, I think.

I *think* I prefer option 1, but I'll keep thinking about it more - and in particular, I'll think about it while reviewing #4200.

**Comment by amanda-tarafa** [comment]
> For option 1, if you mean that setting `SuppressInsertErrors` is redundant if `SkipInvalidRows` is set to true, then I see what you mean - but I think it's easier to reason about them as independent concepts.

Yes, I though about that too. `SkipInvalidRows` is telling the server "insert all you can" and `SupressInsertErrors` is just setting the failure (binary) threshold. I'm fine with that.

> I'd definitely like to rule out option 2 - that seems far too breaking to me.

OK. This is the one that is more or less equivalent to what `BigQueryResult` does right not. If we rule this one out, should we consider always making the first call when querying, so that if the query is not well formed etc., we fail fast and not on the first iteration? That would be breaking, but consistent?

> I'm not sure about option 3. If I'm inserting 10000 rows, should there really be that much difference between 0 rows being inserted and 1 row being inserted? I'd be surprised if they were handled differently, I think.

Ah, but the same argument can probably be made the other way around :). If I'm inserting 10000 rows, should there really be that much difference between 9999 rows being inserted and 10000 rows being inserted? We are talking now about introducing a percentage based failur threshold, we can consider that as a fourth option, a little bit too much in my opinion, but I'd be totally fine with it.

> I'd be surprised if they were handled differently, I think.

Maybe it wouldn't be so surprising, because for 0 vs. 1 inserted to be treated differently `SkipInvalidRows` needed to be set to `true` (the only way not to throw on less than perfect). I think the poor quality of the data might be surprising but not so much the fact that the partial insertion was considered successful, in a way, that's what was asked for when setting `SkipInvalidRows` to `true`.

**Comment by jskeet** [comment]
Okay, reading this over again - I'm still keen on option 1. While I would *love* to think all responsible developers will read the release notes, I suspect that just won't happen. Option 1 still benefits responsible developers who don't want exceptions, as it's now easy for them to get the right information... but it doesn't hurt anyone else.

**Comment by amanda-tarafa** [comment]
Yes, I do see that point about (not) reading documentation. Option one is what is currently implemented in #4200 so no changes required.

We can close this issue unless we want to revisit queries as well, which are failing on the first iteration and not on BigQueryResult object creation. But the same though applies there as here, it's a semantic breaking change so could only be signaled through documentation.

**Comment by jskeet** [comment]
Yes, I think we're probably best keeping that behavior, even though the inconsistency is annoying. Closing now.
