### ISSUE TITLE
[Storage] LOH Allocation Uploading and Downloading

### ISSUE THREAD

**Issue by beefo** [googleapis/google-cloud-dotnet#4212]
**Is your feature request related to a problem? Please describe.**

Doing some scalabilty testing on our application, prefview reported high allocation to Large Object Heap stemming from `UploadObjectAsync` and `DownloadObjectAsync` APIs. Tracing this back to [ResumableUpload.cs](https://github.com/googleapis/google-api-dotnet-client/blob/master/Src/Support/Google.Apis/Upload/ResumableUpload.cs#L715) and [MediaDownloader.cs](https://github.com/googleapis/google-api-dotnet-client/blob/master/Src/Support/Google.Apis/Download/MediaDownloader.cs#L187) .This seems due, in part,  to default chunk size of 10 MB. A 10 MB byte array is allocated and used to chunk the stream.

I am able to lower the chunk size (and thus byte array size) for downloads low enough that allocations stay off the Large Object Heap. However, due to the limitation in minimum upload chunk size of 1024 * 256 bytes, I am unable to keep upload byte arrays off the LOH.

 **Describe the solution you'd like**

It would be ideal to find a way to buffer the streams without excess memory allocations.

Perhaps it's possible to reduce the allocations in .Net core environment by using [ArrayPool<T>](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.arraypool-1?view=netcore-3.1) feature. This may require multi targeting.

 **Describe alternatives you've considered**
None

 **Additional context**
Testing done on:
  - OS: Windows Server 2016
  - .NET version: netcoreapp3.1
  - Package name and version: Google.Cloud.Storage.V1

Can provide prefview screen shots if desired.

**Comment by jskeet** [comment]
I will look into this on Monday - although due to the nature of the way the library is layered, it may not be feasible with reasonable changes.

**Comment by jskeet** [comment]
I'm pretty sure we won't want to use ArrayPool for this. Bear in mind that the [repository containing this code](https://github.com/googleapis/google-api-dotnet-client) is in maintenance mode. We can add new features where the value/cost balance is okay, but adding significant new features that depend on specific targets is unlikely to meet that bar.

It's more likely that we could reduce the minimum chunk size to 64K, while keeping a *default* chunk size of 256K - we'll need to investigate the impact of that.

One thing that's worth being aware of is that while the chunk would indeed be allocated on the LOH, I'd only expect one or two chunks to be allocated that way, per concurrent upload. Further allocations should be able to reuse that portion of the LOH - after all, it will be allocating exactly the same length each time, so it's ideal for reuse. I'd be interested to hear more about what the "high allocation" was here, and what was happening in that scenario.

**Comment by beefo** [comment]
Fair enough, I thought it could be a stretch to multi-target. Lowering the minimum chunk size for uploads would be great if possible.

Just to clarify, the _default_ chunk size is _10MB_ for both [UL](https://github.com/googleapis/google-api-dotnet-client/blob/master/Src/Support/Google.Apis/Upload/ResumableUpload.cs#L58) and [DL](https://github.com/googleapis/google-api-dotnet-client/blob/master/Src/Support/Google.Apis/Download/MediaDownloader.cs#L52). The _minimum_ chunk size for UL is 256K.

In our test scenario of many concurrent UL or DL of a 414KB file, the default chunk sizes were showing the high allocation. Uploads at the minimum chunk size were _not_ excessive but on the LOH non the less which we would like to avoid if possible.

UL default chunk size
![Hgh1cP.png](https://iili.io/Hgh1cP.png)

UL minimum chunk size
![Hgh0KB.png](https://iili.io/Hgh0KB.png)

**Comment by jskeet** [comment]
Okay - I'll investigate where that current minimum chunk size comes from, and see whether we can lower it to 64K. It's likely that I won't have any news on that until later in the week, but I'll post here when I have something.

**Comment by jskeet** [comment]
Just as an update to this - it looks like this *may* be a service limitation... but we could potentially *transparently* change this to use 64K buffers internally. That's going to be harder than changing a constant, but will probably be of benefit to everyone with no changes required to their code.

**Comment by jskeet** [comment]
I've now validated that there *is* a server-side constraint here. Uploading 64K chunks gives this error:

> Invalid request.  The number of bytes uploaded is required to be equal or greater than 262144, except for the final request (it's recommended to be the exact multiple of 262144).  The received request contained 65536 bytes, which does not meet this requirement.

I'll look into an implementation change where we still send 256K chunks, but we do that via multiple smaller arrays.

**Comment by jskeet** [comment]
Just to say, I'm afraid this is currently relatively low priority compared with the other things we've got going on at the moment. I haven't forgotten about this, but I'm unlikely to get to it for a little while.

**Comment by jskeet** [comment]
I've had another look at this today - it's going to be pretty painful due to the complexity of the MediaUploader code. Doable, but painful. The upload and download code will have to be managed entirely separately though.

**Comment by jskeet** [comment]
Right, this is now fixed in google-api-dotnet-client - but it won't be available until we've done a new release of Google.Apis etc. We've got a new feature going in there soon, at which point we can release 1.45 of Google.Apis, and I can target that in a new beta of the storage library.

Sorry it's taken so long to get to this, but I'm very pleased with the result - not only does it avoid allocating any large objects, but it also massively reduces the amount of allocation in general, when you're uploading a seekable stream.

**Comment by beefo** [comment]
Thanks so much @jskeet! Really appreciate all your help with this. I'll keep my eyes peeled for the new version.

**Comment by jskeet** [comment]
This is now released in Google.Apis version 1.45.0, and we depend on that in Google.Cloud.Storage.V1 version 3.0.0-beta03. So if you're using the 3.0 beta already, just update - if you're using the 2.x GA, add a dependency on Google.Apis version 1.45.0 and it should all work fine.
