### ISSUE TITLE
[Storage] Error when attempting to upload file smaller than 256k

### ISSUE THREAD

**Issue by surgicalcoder** [googleapis/google-cloud-dotnet#4215]
#### Environment details

  - OS: Container running mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
  - .NET version: ASP .NET Core 3.1
  - Package name and version: Google.Cloud.Storage.V1 2.5.0

#### Steps to reproduce

1. Generate / Find a JPG that is less than 256k
2. Attempt to upload using code below:

Code:
```

 using (var client = StorageClient.Create(GoogleCredential.FromFile("gcloud.json")))
    {
        await using (var f = System.IO.File.OpenRead(filePath))
        {
            await client.UploadObjectAsync(Configuration["GoogleBucket"], $"img/{fileName}", "image/jpeg", f);
        }
    }
```

Error message:

> The service storage has thrown an exception: Google.GoogleApiException: Invalid request.  The number of bytes uploaded is required to be equal or greater than 262144, except for the final request (it's recommended to be the exact multiple of 262144).  The received request contained 41622 bytes, which does not meet this requirement.,
>    at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.CheckFinalProgress(),
>    at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.ExecuteAsync(CancellationToken cancellationToken)

**Comment by jskeet** [comment]
That's very odd - we do thinks like this all the time. I'll try to reproduce this on Monday.

**Comment by jskeet** [comment]
Hmm. Just tried this in a .NET Core 3.1 console app, and it was absolutely fine. I'll try it from an actual ASP.NET Core 3.1 app later on.

**Comment by surgicalcoder** [comment]
I too haven't been able to replicate this since. 

Am happy for this to be closed if you are unable to replicate it @jskeet .

**Comment by jskeet** [comment]
@surgicalcoder: Just to check what you mean, are you saying the same code that failed before is now working?

Is it possible that when it failed, the file size changed while you were uploading? That could potentially explain it.

**Comment by surgicalcoder** [comment]
@jskeet  It's part of a service that takes images, resizes them and uploads them to GCP storage - the code hasn't changed, and from about 4,500 images that have been uploaded since yesterday, I've only seen that error once.

**Comment by jskeet** [comment]
Okay, that's good to know, thanks. I'll close this for now, but please do add another comment if you see it happen again and we'll see if we can get to the bottom of it.
