### ISSUE TITLE
Sending back Text & Card in WebhookResponse FulfillmentMessage

### ISSUE THREAD

**Issue by thinkcodellc** [googleapis/google-cloud-dotnet#4240]
I am trying to use the API to send back a webhook response message across multiple channels.
While it works for ActionOnGoogle, I am having a bit of hard time to use the syntax to set for type Text with message - "Cannot implicitly convert type 'string' to 'Google.Cloud.Dialogflow.V2.Intent.Types.Message.Types.Text'"

Please help in suggesting the right way to set a Text value to a normal string.

     return new WebhookResponse
    {
	FulfillmentText = responseText,
	FulfillmentMessages =
	{
	    //Add for Telegram
	    new Message
	    {
		Platform = Message.Types.Platform.Telegram,   
		//Error here - Cannot implicitly convert type 'string' to 'Google.Cloud.Dialogflow.V2.Intent.Types.Message.Types.Text'                 
		Text =  "I would like to order a T-shirt",
		BasicCard = new BasicCard
		{
		    Image = cardImage,
		    FormattedText = responseText,
		    Subtitle = subtitle,
		    Title = "Title Text"
		}
	    }
	}

Also I was hoping to send the message as card similar to the response in JSON below, but setting it as above doesnt seem to work for Telegram, but works if sent as JSON below, any thoughts?

    "fulfillmentMessages": [
    {
      "card": {
        "imageUri": "imgagePath",
        "subtitle": "subtitle",
        "title": "Title"
      },
      "platform": "TELEGRAM"
    },
    {
      "platform": "TELEGRAM",
      "text": {
        "text": [
         "ResponseText"
        ]
      }
    }]

  

  - OS: Win10
  - .NET version: .NET Core 2.2
  - Package name and version: Google.Cloud.Dialogflow.V2

#### Steps to reproduce

  1. Set the response to above code snippet and invoke

Thanks in advance for any directions!

**Comment by jskeet** [comment]
I can't check the exact type at the moment as I'm on mobile, but if you just type 'Text = new ' then I suspect VS will suggest the right type for you - then use an object initialiser to set the properties within it.

**Comment by thinkcodellc** [comment]
@jskeet Thanks for responding. However all properties within Text object seem to be readonly with only gets.  Is there a parser from string that is required?


    public sealed class Text : IMessage<Text>, IMessage, IEquatable<Text>, IDeepCloneable<Text>
                    {
                        public const int Text_FieldNumber = 1;

                        [DebuggerNonUserCode]
                        public Text();
                        [DebuggerNonUserCode]
                        public Text(Text other);

                        [DebuggerNonUserCode]
                        public static MessageParser<Text> Parser { get; }
                        [DebuggerNonUserCode]
                        public static MessageDescriptor Descriptor { get; }
                        //
                        // Summary:
                        //     Optional. The collection of the agent's responses.
                        [DebuggerNonUserCode]
                        public RepeatedField<string> Text_ { get; }
                       ....
                    }

I tried the new and object initializer, but didnt see any set. Pardon my ignorance on this.

     new Message
                    {
                        Platform = Message.Types.Platform.Telegram,         
                        //Errors - since Text_ is also readonly
                        Text =  new Text() { Text_ = new Google.Protobuf.Collections.RepeatedField<string>().Add(responseText) },
                        BasicCard = new BasicCard
                        {
                            Image = cardImage,
                            FormattedText = responseText,
                            Subtitle = subtitle,
                            Title = "Title"
                        }
                    },

**Comment by jskeet** [comment]
Right, those read-only properties are for repeated fields. You populate those US Ng collection initializes. See https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-modify-repeated-fields-and-maps-in-protobuf-messages for an example. Hope this helps - if not, I'll give you a full example tomorrow or Monday

**Comment by thinkcodellc** [comment]
Thanks @jskeet ! That link helped. You da best! I followed your suggestion with the explanation from the article to define the RepeatedField so

    Text fulfillmentText = new Text();
            fulfillmentText.Text_.Add(responseText);

            return new WebhookResponse
            {
                FulfillmentText = responseText,
                FulfillmentMessages =
                {
                    //Add for Telegram
                    new Message
                    {
                        Platform = Message.Types.Platform.Telegram,
                        //Setting the card didnt display the card, neither does Basic Card work in Telegram
                        Card = new Card
                        {
                         ImageUri = cardImage.ImageUri,
                         Title = "Title of the card"
                        },
                        Text = fulfillmentText,
                    }]

So setting the Text made the text appear, but setting it along with the Card or using the BasicCard doesnt work the same way as it does in ActionsOnGoogle. I guess there is some issue with the way Telegram handles it?

Thanks for your pointers on the Dialogflow API though.

**Comment by jskeet** [comment]
I'm afraid I can't help on that front - that's more Dialogflow-specific knowledge which I don't have. (I'm just responsible for making sure the libraries accurately represent the APIs - I don't know all the details of all those APIs.)

I suggest at this stage you explore the options on the [Dialogflow support page](https://cloud.google.com/dialogflow/docs/getting-support). I'll close this issue now as I don't think any change is required in this repo, and the maintainers of this repo won't be able to help you any further, but best of luck on the next step.
