### ISSUE TITLE
Unable to proxy PubSub calls programmatically without setting Environment Variables

### ISSUE THREAD

**Issue by NicholasAzar** [googleapis/google-cloud-dotnet#4446]
#### Environment details

  - OS: macOs
  - .NET version: 3.1.102
  - Package name and version: Google.Cloud.PubSub.V1 - Version: 1.1.0

#### Steps to reproduce

  1. Attempt to proxy pubsub requests programmatically without setting environment variables.
  2. When setting the proxy as follows, only the oauth token request is proxied:
```
 ServiceAccountCredential credential = new ServiceAccountCredential(
               new ServiceAccountCredential.Initializer(serviceAccountEmail)
               {
                   Scopes = PublisherServiceApiClient.DefaultScopes,
                   HttpClientFactory = new ProxySupportedHttpClientFactory()
               }.FromPrivateKey(private_key));
```
  3. Even when using `System.Net.WebRequest.DefaultWebProxy = new WebProxy("http://localhost:8888", false)` it seems like it's ignored.

It seems like the only option available to proxy the grpc request to pubsub is through environment variables? 

Is there any api available in the library that would allow us to define an http proxy (with authentication) through code rather than rely on grpc to pick them up from the environment?

Thanks!

**Comment by jskeet** [comment]
No, I don't believe Grpc.Core supports programmatically specifying a proxy, no. ([This issue](https://github.com/grpc/grpc/issues/12815) and [this one](https://github.com/grpc/grpc/issues/13323) didn't mention any alternatives, for example.)

Until Grpc.Core supports this, we can't support it in client libraries. With the next major version (targeting GAX v3.x) it should be possible to use Grpc.Net.Client which probably *does* support proxies - although I know the PubSub client specifies some gRPC channel options which may not be supported by Grpc.Net.Client.

I'd recommend filing an [issue on the gRPC repo](https://github.com/grpc/grpc/issues) and referring to this one for context. (I'll then subscribe to that issue so I can take advantage of any suggestions or changes.)

**Comment by NicholasAzar** [comment]
Thanks a ton for the quick response @jskeet . I've went ahead with your suggestion and will wait to hear back from that team.

**Comment by jskeet** [comment]
I'm going to close this issue for now as at least *right now* there's nothing else to do here; I've subscribed to the issue you've raised though, and we can add support in the libraries if it becomes available in gRPC.

**Comment by NicholasAzar** [comment]
Sounds fine to me - thanks for your help on this @jskeet!
