### ISSUE TITLE
Firestore WhereIn operator failing

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#4543]
See https://stackoverflow.com/questions/60641354/cloud-firestore-wherein-method-not-working-in-net

**Comment by jskeet** [comment]
I can't reproduce this at the moment. Here's a sample which works for me:

```csharp
using Google.Cloud.Firestore;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

class Program
{
    static async Task Main(string[] args)
    {
        string projectId = args[0];
        var db = FirestoreDb.Create(projectId);

        var coll = db.Collection(Guid.NewGuid().ToString());
        await coll.AddAsync(new { Id = 1, Text = "foo" });
        await coll.AddAsync(new { Id = 2, Text = "bar" });
        await coll.AddAsync(new { Id = 3, Text = "baz" });

        var words = new List<string> { "bar", "other" };
        var snapshot = await coll.WhereIn("Text", words).GetSnapshotAsync();
        Console.WriteLine($"Snapshot count: {snapshot.Count}");
        foreach (var doc in snapshot.Documents)
        {
            Console.WriteLine($"Id: {doc.GetValue<int>("Id")}");
        }
    }
}
```

That's tested against Google.Cloud.Firestore versions 1.1.0 and 2.0.0-beta01.

**Comment by a-molaei** [comment]
I used your code with some changes in the connection configuration and I have the same error on the same line:

> Grpc.Core.RpcException: 'Status(StatusCode=InvalidArgument, Detail="Unknown FieldFilter operator.")'

My test is against **Google.Cloud.Firestore versions 1.1.0** and **firestore-emulator-docker**

```
using Google.Cloud.Firestore;
using Google.Cloud.Firestore.V1;
using Grpc.Core;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

class Program
{
    static async Task Main(string[] args)
    {
        Channel channel = new Channel("127.0.0.1", 8080, ChannelCredentials.Insecure);
        FirestoreClient client = FirestoreClient.Create(channel);
        var db = FirestoreDb.Create("sonat", client);

        var coll = db.Collection(Guid.NewGuid().ToString());
        await coll.AddAsync(new { Id = 1, Text = "foo" });
        await coll.AddAsync(new { Id = 2, Text = "bar" });
        await coll.AddAsync(new { Id = 3, Text = "baz" });

        var words = new List<string> { "bar", "other" };
        var snapshot = await coll.WhereIn("Text", words).GetSnapshotAsync();
        Console.WriteLine($"Snapshot count: {snapshot.Count}");
        foreach (var doc in snapshot.Documents)
        {
            Console.WriteLine($"Id: {doc.GetValue<int>("Id")}");
        }
    }
}
```

**Comment by jskeet** [comment]
I've just tried this with the emulator started by `gcloud beta emulators firestore start` and (after adapting it to use the IPv6 address) it worked.

Do you know what version of the emulator you're using? I wonder whether it's just an older emulator that doesn't support this. (In future, it's always best to mention that you're using an emulator right from the start, by the way.)

**Comment by a-molaei** [comment]
My apologies for forgetting to mention that I'm using firestore emulator. 
I am using this image:

> gerritforge/docker-firestore-emulator:latest


Actually I don't know how to get the version on my system. Please guide me if I can provide more info. 
Thanks

**Comment by jskeet** [comment]
Okay - it looks like that was last updated 10 months ago, which I suspect is the problem. It's entirely possible that building a new docker image with the same Dockerfile would actually get the later emulator anyway. I would give that a try - and if that doesn't help, possibly contact the [Firestore support team](https://firebase.google.com/support). I don't believe this is an issue in the client library itself, and I don't think I'd be able to give any further help, as the maintainers of this repo really only know about the client libraries, rather than details of the individual APIs. I'll close this issue now, but if you have reason to think the problem *is* in the client library, please add another comment and I can reopen it.

**Comment by a-molaei** [comment]
Yes, The problem is gone after updating the emulator. Thanks.
