### ISSUE TITLE
Inconsistency of parameter ordering between GetOrCreateTable and GetOrCreateDataset

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#4551]
In BigQueryClient, we have the following methods (amongst many other overloads):

```csharp
public virtual BigQueryDataset GetOrCreateDataset(DatasetReference datasetReference, GetDatasetOptions getOptions = null, Dataset resource = null, CreateDatasetOptions createOptions = null)
public virtual BigQueryTable GetOrCreateTable(TableReference tableReference, Table resource, GetTableOptions getOptions = null, CreateTableOptions createOptions = null)
public virtual BigQueryTable GetOrCreateTable(TableReference tableReference, TableSchema schema, GetTableOptions getOptions = null, CreateTableOptions createOptions = null)
```

For GetOrCreateDataset, the resource comes after the GetDatasetOptions; for both GetOrCreateTable overloads shown here, the resource comes before the options. I think we should make these consistent.

(We need to do this before next GA.)

**Comment by amanda-tarafa** [comment]
Yep, nice catch, I will do this now. I will have to put the resource before the options in all cases, because for tables the resource is not optional.
