### ISSUE TITLE
Lots of "Could not resolve base documentation" errors

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#4556]
This is probably an issue with inheritdoc in docfx, but we should look into it further.

**Comment by stan-osipov** [comment]
I just started with docfx, and I have the same. Pretty sure it's docfx issue, but please let me know if you find a way how to fix that.

**Comment by jskeet** [comment]
@stan-osipov: Oh yes, I'm pretty sure it's a problem with docfx. I don't know whether it's fixable or not yet. It may be something we can't fix, but can work around...

**Comment by iJungleboy** [comment]
Also getting ca. 20 wher previously I didn't have them. Previously used 2.48.1.

It seems that 2.48.1 also didn't perform the lookup correctly (the resulting docs were missing the inherited docs), but didn't throw an error. 

Downgrading removed the errors - but didn't add more docs - so the link to the underlying inheritdoc apparently was broken before and still is, but 2.48.1 didn't report it as an error.

**Comment by jskeet** [comment]
Yup, I'm going to try to work out a workaround at some point, but it's low down my priority list.

**Comment by iJungleboy** [comment]
no problem. Thanks for this awesome product!

**Comment by jskeet** [comment]
We only get the warnings due to `inheritdoc`. So let's not use that... this is generally for generated code anyway, so let's generate the docs.
Filed https://github.com/googleapis/gapic-generator-csharp/issues/248 and will start on it now.

**Comment by jskeet** [comment]
This has been fixed (or at least worked around) in the generator now.

**Comment by simonziegler** [comment]
Hi - I have the same issue in an ASP.NET Core repo. Do you know if there is some proper fix in DocFX? Thanks

**Comment by jskeet** [comment]
@simonz130: No, I don't know of a good fix unfortunately :(

**Comment by simonziegler** [comment]
Thanks @jskeet. Interestingly I can make this work in Visual Studio 16.4+ by using a cref tag, e.g. `/// <inheritdoc cref="ComponentBase.OnInitialized()"/>`, referenced from https://github.com/dotnet/docfx/issues/3699. However DocFX doesn't seem to support the cref tag.
