### ISSUE TITLE
Add Google.Cloud.Diagnostics.AspNet 4.0 support

### ISSUE THREAD

**Issue by keltex** [googleapis/google-cloud-dotnet#4658]
It would be really nice to continue to support asp.net. ASP.NET is supposed to be a supported framework and if Google.Cloud.Diagnostics.AspNet isn't upgraded like the .net core version, then we can't use GAX 3.0. Which means we can't use the updated versions of any of the other libraries.

**Comment by jskeet** [comment]
Hi Brett,

While I agree that we'd do this in an ideal world, it's not clear that there's enough demand for this to be worth the maintenance burden. The 3.0.0 release of the NuGet package has only had 120 downloads in over three months, for example. Supporting ASP.NET involves significantly more maintenance burden in terms of integration tests etc, compared with ASP.NET Core.

We could *potentially* revive it for just long enough to produce a 4.0 that depends on GAX 3.0.0, but then deem that "end of line" for anything other than patching significant issues.

Adding Amanda to the conversation now, for her perspective.

**Comment by keltex** [comment]
Thanks @jskeet. I understand the reasoning. But just wanted to point out that this library does claim to support ".NET Framework 4.5+". And while maybe not a lot of people use it, certainly some do. It's definitely nice to have stackdriver error logging built into our asp.net applications that we've moved over to google cloud.

GAX 3.0 support alone would be sufficient for our needs.

**Comment by jskeet** [comment]
Ah, we need to update our list of supported platforms - from GAX 3.0 onwards, it's .NET 4.6.1+, not 4.5.

I'll talk it through with Amanda tomorrow - I think we could probably do a "just this one release" but then drop ASP.NET again - basically to just support the existing feature set with GAX 3.0, but no further development.

(There will always be things that "not a lot of people use, but some do" - that in itself doesn't justify us spending time on something, where that time could be spent on something that would benefit *more* users. We need to balance our use of resources carefully.)

**Comment by keltex** [comment]
That alone would be good enough for me! Thanks Jon.

**Comment by jskeet** [comment]
I've released 4.0.0-beta01 now. @amanda-tarafa is going to do some local testing on it next week and then we can do a GA.

**Comment by amanda-tarafa** [comment]
This has now been released: https://www.nuget.org/packages/Google.Cloud.Diagnostics.AspNet/

**Comment by keltex** [comment]
Thanks @jskeet and @amanda-tarafa for doing this. Works perfectly!
