### ISSUE TITLE
are there a plan to support asp.net core 3.0?

### ISSUE THREAD

**Issue by shengxue** [googleapis/google-cloud-dotnet#4750]
are there a plan to support asp.net core 3.0?

**Comment by jskeet** [comment]
Do you mean in terms of Google.Cloud.Diagnostics.AspNetCore? I *believe* that should already work.

If that's not what you mean, please be more specific. If that *is* what you mean, have you tried the existing libraries? What happened?

**Comment by shengxue** [comment]
Yes, I tried  ```Google.Cloud.Diagnostics.AspNetCore.dll```,  and that caused some problems in our program after we upgraded our program to asp.net core 3.1.  The problems are related with HttpClientFactory .

```Google.Cloud.Diagnostics.AspNetCore.dll v``` depends on ``Microsoft.AspNetCore.Http v2.1````, ``Microsoft.AspNetCore.Http.Abstraction v2.1```` and other asp.netcore assemblies V2.    But V3 of these assemblies are not backward compatible with V2, and actually there is big differences between these two versions.

**Comment by jskeet** [comment]
Okay, we'll look at that. I suspect we'll create a different package.

**Comment by shengxue** [comment]
Thanks!  Possibly I can also make some contribution. :)

**Comment by shengxue** [comment]
When will be this package available approximately?

**Comment by jskeet** [comment]
Given that we currently have no source code for it, it's impossible to predict that. It *may* be relatively simple to copy the existing ASP.NET Core 2 source code, change the dependencies, rebuild and fix a few problems. Or it may be that there are broader architectural changes required that take weeks of work - weeks of work that haven't been scheduled yet. (It's not like the team is just sitting around waiting for feature requests to come in that they can jump on.)

I'm sure Amanda will ping this issue when there's progress. In the meantime, please be patient.

**Comment by amanda-tarafa** [comment]
I will try and build against ASP.NET Core 3 and from there I'll get a better idea of what needs changing. I will get back here when I have more info.

**Comment by slim1305** [comment]
Hi folks,

Do you have ETA to release Google.Cloud.PubSub.V1 2.X (based on GAX 3)?

**Comment by jskeet** [comment]
@slim1305: Please don't add unrelated comments to issues. That question isn't about ASP.NET Diagnostics. Issue threads get really confusing if there are unrelated questions involved.
However, the answer is that there's already 2.0.0-beta02 which targets GAX 3.0.0. We're hoping to look at #4397 this week, along with another change which *might* be breaking, and see whether we can release a GA either next week or the week after.

**Comment by da3dsoul** [comment]
Out of curiosity and frustration, why would this be compatible with and supported for aspnetcore2 when it's now long past the EOL? I could be talking out of my ass here, but I've had a lot of trouble getting this to work with stackdriver (now Google Cloud Logging), and this vague issue of incompatibility is my only lead.

**Comment by amanda-tarafa** [comment]
@da3dsoul I'm almost there with a Google.Cloud.Diagnostics.AspNetCore3 package that will support ASP.NET Core 3.1. I'll be able to release a beta version possibly next week.

ASP.NET Core 2.1 is still very much supported and in any case we don't necessarily stop supporting our libraries when some of our dependencies reach EOL.
For supporting ASP.NET Core 2.1 we did have to make some minor changes (#2661).

If you create issues describing the troubles you have with the library we might be able to help. Or if the issues are related to specifically supporting ASP.NET Core 3 then hopefully they'll be solved once the new package is released.

**Comment by da3dsoul** [comment]
I honestly have no idea what the root of my issues are. No errors or anything logged. It just doesn't work. It's entirely possible that errors are happening, but it's really hard to tell when it's the logger not working. I can wait and see if this new version magically fixes all of my problems, as I've not even tried to backport the application I'm working on to an older framework. It seems like a terrible idea to propose to your boss in seriousness.

I guess it's not a problem to support older versions, but I'm used to seeing teams *only* supporting older or newer versions because they don't have the manpower to both support their current codebase and work on a new one.

Thanks much for the reply.

**Comment by amanda-tarafa** [comment]
@da3dsoul Do create a new issue. If you can include a full minimum application that reproduces the problem that'd be best. Else clearly describe your environment (targeting frameworks, library versions etc.), include code showing how you are configuring the library and how you are using it.

**Comment by amanda-tarafa** [comment]
As an update, a couple other things have come up that stopped me from finishing this work when I had plan. I'm not aiming to have a release this week.

**Comment by amanda-tarafa** [comment]
This has been released https://www.nuget.org/packages/Google.Cloud.Diagnostics.AspNetCore3/4.0.0-beta01.
