### ISSUE TITLE
Datastore Grpc.Core.RpcException Unauthenticated

### ISSUE THREAD

**Issue by Mistic92** [googleapis/google-cloud-dotnet#4778]
#### Environment details

  - OS: Docker mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
  - .NET version:
  - Package name and version: Include="Google.Cloud.Datastore.V1" Version="3.0.0"

I'm trying to run dotnet app on GKE using Istio 1.5.1 with Workload identity enabled. 
I have created service accounts etc and this part is working. 

Issue is with Datastore library as I see that there is [no easy way](https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis) to use default credentials for grpc.

Following multiple issues there and on stackoverflow I found that this code is at least compiling but when deployed to cluster it's not working. 

```
            Google.Apis.Auth.OAuth2.GoogleCredential credential = Google.Apis.Auth.OAuth2.GoogleCredential.GetApplicationDefault();
            Grpc.Core.ChannelCredentials channelCredentials = credential.ToChannelCredentials();
            Channel channel = new Channel(DatastoreClient.DefaultEndpoint, channelCredentials);
            DatastoreClientBuilder builder = new Google.Cloud.Datastore.V1.DatastoreClientBuilder();
            builder.ChannelCredentials = channelCredentials;
            builder.Endpoint = DatastoreClient.DefaultEndpoint;
            DatastoreClient client = builder.Build();
            _db = DatastoreDb.Create(_appCfg.GcpProjectId, tenantCode, client: client);
```
(I know that this is not best code but dotnet is not my main language and I'm trying to have working code first ;) )

Error
```
Grpc.Core.RpcException: Status(StatusCode=Unauthenticated, Detail="Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.")
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
  at Google.Cloud.Datastore.V1.DatastoreDbImpl.CommitAsync[T](IEnumerable`1 values, Func`2 conversion, Action`2 keyPropagation, String parameterName, CallSettings callSettings)
```

**Comment by jskeet** [comment]
> Issue is with Datastore library as I see that there is no easy way to use default credentials for grpc.

No, that's not true. Datastore *does* use the default credentials for gRPC by default. Just using `DatastoreDb.Create(_appCfg.GcpProjectId, tenantCode)` will use the default credentials. What happens when you try that? I *suspect* you'll get the same exception - which means that the problem isn't with specifying credentials, it's that the default credentials aren't being accepted by Datastore.

Does your default service account definitely have access to Datastore? In your cluster's node pool details, in the Security section, what does it show for "Access scopes"?

**Comment by Mistic92** [comment]
I have google service account created _conversation@yxxxxxx.iam.gserviceaccount.com_ which have binding to kubernetes service account.
It have even datastore owner permission as I thought that user is not enough
```
Cloud SQL Client
Cloud Trace Agent
Cloud Datastore Owner
Cloud Datastore User
Errors Writer
Logs Writer
Monitoring Metric Writer
Stackdriver Resource Metadata Writer
```
```
Updated IAM policy for serviceAccount [conversation@yxxxxxxxx.iam.gserviceaccount.com].
bindings:
- members:
  - serviceAccount:xxxxxxxxx.svc.id.goog[convsersation/convsersation-sa]
  role: roles/iam.workloadIdentityUser
etag: BwWiTjsQqak=
version: 1
```

(yes, there is a typo in namespace and object name)

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: conversation@xxxxxxx.iam.gserviceaccount.com
  labels:
  name: convsersation-sa
  namespace: convsersation

secrets:
- name: convsersation-sa-token-48q68
```

When running without all this grpc setup I'm getting the same error which is weird for me
```
Grpc.Core.RpcException: Status(StatusCode=Unauthenticated, Detail="Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.") at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
```



I just found that it's coming from this method. 
await _db.InsertAsync(entity);

**Comment by Mistic92** [comment]
Oh, and it was working before enabling workload identity when using GCE credentials.

**Comment by jskeet** [comment]
> When running without all this grpc setup I'm getting the same error which is weird for me

It's not weird at all - your code *explicitly* fetches and uses the default application credentials - that just happens automatically if you don't set anything. It would be weird if you got a *different* result.

> Oh, and it was working before enabling workload identity when using GCE credentials.

Okay, that sounds like it's not really a problem the client libraries can handle then - we're just fetching the default credentials and using them in the same way as ever. If enabling workload identity makes those credentials fail, that's something I'd expect to fail with client libraries for all languages. Of course, we still want to help you - but we may very well run into the limits of our knowledge pretty quickly.

When you went through the setup procedure, did [step 9 here](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#enable_on_a_new_cluster) work? So `gcloud auth list` showed the Google service account?

**Comment by Mistic92** [comment]
Ok I think I found issue. 
Deployment was using default service account istead of new one. GKE documentation could be a little better and mention that there is no need to change code but deployment need to be updated
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_kubernetes_service_accounts

Now I have issue with Dialogflow in other service but when I confirm that this is the same I'll close issue.

**Comment by Mistic92** [comment]
Yes, point 9 was an issue as I had to update all deployments to not use default account. Sorry for taking your time but maybe someone else will find this thread helpful.
