### ISSUE TITLE
Webhook Response for Integration with Dialogflow Messenger

### ISSUE THREAD

**Issue by thinkcodellc** [googleapis/google-cloud-dotnet#4785]
I was interested to use the Google.Cloud.Dialogflow.V2 SDK (2.0.0) for use with the newly featured Dialogflow Messenger (https://cloud.google.com/dialogflow/docs/integrations/dialogflow-messenger). I enabled in the Integrations tab of Dialogflow, however even with the fulfillment response coming through, it doesnt make it to Dialogflow Messenger. 

I would appreciate some details on how to structure the webhook response so that Dialogflow messenger can pick up the fulfillmenttext.

Below is the Webhook Response setup I have

          //Create Webhook Response
            return new WebhookResponse
                {
                    FulfillmentText = responseText,
                    FulfillmentMessages =
                     {
                        simpleMessage,
                        basicCard,
                        telegramMessage,
                        suggestionChip()
                     }
                };

#### Environment details

  - OS: Win 10
  - .NET version:  .NET Core 2.2
  - Package name and version: Google.Cloud.Dialogflow.V2

#### Steps to reproduce

  1. Set up Fulfillment with Google.Cloud.Dialogflow.V2 SDK
  2. Invoke through Dialogflow Messenger - No response, however 

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jskeet** [comment]
Did you try following the steps on https://googleapis.dev/dotnet/Google.Cloud.Dialogflow.V2/2.0.0/index.html for implementing a web hook? In particular, you mustn't try to use the built-in JSON parsing and serialization - you have to use the Protobuf JSON serialization. Details are on that page.

**Comment by thinkcodellc** [comment]
Hi Jon, thanks for the quick response. I do create the WebHookResponse using the protobuf json serialization  with the construct
     WebhookResponse webhookResponse = new WebhookResponse
        {
            // ...
        };

and the response also makes it across different channels including Google Assistant AoG, Dialogflow WebDemo, Telegram etc. However, the newly introduced Dialogflow messenger doesnt catch the FulfillmentText from the WebhookResponse. I wanted to check if the Webhook Response structure needs to be different. Below is the response JSON from Dialogflow logs

    {
  "queryText": "US",
  "parameters": {
    "state": "US"
  },
  "fulfillmentText": "Response",
  "fulfillmentMessages": [
    {
      "platform": "ACTIONS_ON_GOOGLE",
      "simpleResponses": {
        "simpleResponses": [
          {
            "textToSpeech": "Response here",
            "displayText": "response display"
          }
        ]
      }
    },
    {
      "platform": "ACTIONS_ON_GOOGLE",
      "basicCard": {
        "title": "Title",
        "subtitle": "US",
        "formattedText": "Fulfillment",
        "image": {
          "imageUri": "url"
        }
      }
    },
    {
      "card": {
        "title": "Title",
        "subtitle": "Response ",
        "imageUri": "URI"
      },
      "platform": "TELEGRAM"
    },
    {
      "platform": "ACTIONS_ON_GOOGLE",
      "suggestions": {
        "suggestions": [
          {
            "title": "US"
          },
          {
            "title": "State"
          },
          {
            "title": "Quit"
          }
        ]
      }
    }
  ]

**Comment by jskeet** [comment]
>  I do create the WebHookResponse using the protobuf json serialization with the construct

That's just creating a protobuf object - if you're returning that directly from your web API, that will be *serialized* to JSON using the default ASP.NET Core serializer. You need to convert it to a string directly, e.g.

```csharp
string responseJson = response.ToString();
return Content(responseJson, "application/json");
```

Now it may be that you're already doing that - but you haven't shown us any code like that.

Unfortunately the maintainers of this repository don't have any specific Dialogflow experience - we make sure that the client libraries behave correctly, but that's all we can do. (There are far too many APIs for us to be experts in all of them.)

I suggest you use one of the [Dialogflow support channels](https://cloud.google.com/dialogflow/docs/support/getting-support), posting your JSON there - because I'm afraid I don't think anyone within this repository will be able to help you. (I hadn't even heard of Dialogflow Messenger before this issue!) Sorry not to be able to be more helpful.

**Comment by thinkcodellc** [comment]
Yes, I do convert it to JSON as you mentioned

    return Content(responseJson, "application/json; charset=utf-8");
As per your suggestions will try to reach out to Dialogflow support for guidance..  Since Dialogflow Messenger seems to be a new addition, was wondering if it required response in a different section under WebhookResponse construct.

Thanks for the assistance and and your awesome team in adding stuff and maintaining this repo!

**Comment by jskeet** [comment]
Righto. If the response from Dialogflow support suggests there's anything we need to change in the client library, then obviously please do come back and we can reopen this issue - I'll close it for now.

Just as a heads-up, I've just merged a breaking change with resource names, so next week I'll be releasing version 3.0.0-beta01 (and *maybe* taking it to GA next week). If 2.0.0 is working for you, you don't need to update particularly - just be aware that when you need new features, you'll need to update and it's *possible* the changes may be breaking for you. (I suspect not, with the way Dialogflow is typically used.)

**Comment by jskeet** [comment]
Version 3.0.0-beta01 has now been released.

**Comment by thinkcodellc** [comment]
Thanks Jon!
