### ISSUE TITLE
Unseal classes to allow extension

### ISSUE THREAD

**Issue by AshleyMedway** [googleapis/google-cloud-dotnet#4814]
The following classes are sealed which means we cannot extend them in the same way that we do  in Angular.

- FirestoreDb.cs
- CollectionReference.cs
- DocumentReference.cs

In Angular we extend the Firestore classes to allow us to handle some common data we set on all objects in our databases. We have tried to do the same in C# but at the moment this relies on extension methods. This is not fool proof, if we could extend the classes we could achieve this.

**Comment by jskeet** [comment]
No, we will not be doing this. These classes are not designed for inheritance, and we follow the guideline of "design for inheritance or prohibit it". For example, various places in the code assume that `CollectionReference` and `DocumentReference` are immutable. If they're not sealed, there's absolutely no guarantee that that's the case. My experience is that controlling inheritance carefully leads to more reliable code.

If you could give more details on what you're trying to achieve, I may be able to advise an alternative design strategy, but it won't involve deriving from those types.

**Comment by AshleyMedway** [comment]
Completely understand the design decision. I would say the most pressing issue is we set default data on all update, set, add.

Additionally, we do use `IEnlistmentNotification` to handle both firestore and sql transactions which would be nice to add to an inherited class.

**Comment by jskeet** [comment]
I would suggest either wrapping the existing classes, or just using extension methods, possibly with a Roslyn code analysis rule to ensure that your code never uses the "regular" methods. It sounds like you've probably got it in hand though in terms of design strategies, so I'll close this issue now. If there are ways that we can help you that don't involve undermining the existing design, I'm happy to listen to suggestions.
