### ISSUE TITLE
BigQueryRow throws exception when fetching value from a TIMESTAMP field

### ISSUE THREAD

**Issue by yaxv** [googleapis/google-cloud-dotnet#4821]
When using version 2.0.0-beta03 of the Google.Cloud.BigQuery.V2 library I get an FormatException-exception when trying to fetch the value of a TIMESTAMP field. I've downgraded to version 1.4.0 which does not exhibit this behavior.

#### Environment details

  - OS: Windows 10
  - .NET version: 3.1
  - Package name and version: Google.Cloud.BigQuery.V2, version 2.0.0-beta03

#### Steps to reproduce

Using 2.0.0-beta03:

  1. Fetch value of BigQueryRow["CreateTs"] where CreateTs is a TIMESTAMP field:

`var value = row["CreateTs"]; // row is an object of type BigQueryRow and CreateTs is a TIMESTAMP field. The value is shown as '1899-12-31 23:00:00 UTC' in the BigQuery UI.`

  2. The result is an exception:

> 'row["CreateTs"]' threw an exception of type 'System.FormatException'
> Data: {System.Collections.ListDictionaryInternal}
> HResult: -2146233033
> HelpLink: null
> InnerException: null
> Message: "Input string was not in a correct format."
> Source: "System.Private.CoreLib"
> StackTrace: 
>   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)\r\n
>   at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)\r\n
>   at System.Decimal.Parse(String s, NumberStyles style, IFormatProvider provider)\r\n
>   at Google.Cloud.BigQuery.V2.BigQueryRow.<>c.<.cctor>b__29_3(String v)\r\n
>   at Google.Cloud.BigQuery.V2.BigQueryRow.ConvertSingleValue(Object rawValue, TableFieldSchema field)\r\n
>   at Google.Cloud.BigQuery.V2.BigQueryRow.get_Item(Int32 index)\r\n
>   at Google.Cloud.BigQuery.V2.BigQueryRow.get_Item(String name)
>   TargetSite: {Void ThrowOverflowOrFormatException(ParsingStatus, System.TypeCode)}

Thanks.

**Comment by amanda-tarafa** [comment]
Thanks for reporting, I'll try to reproduce and get back to you as soon as I know something.

**Comment by amanda-tarafa** [comment]
This seems to be related to #4031

**Comment by amanda-tarafa** [comment]
The fix for this has now been released: https://www.nuget.org/packages/Google.Cloud.BigQuery.V2/2.0.0-beta04

**Comment by yaxv** [comment]
> 
> 
> The fix for this has now been released: https://www.nuget.org/packages/Google.Cloud.BigQuery.V2/2.0.0-beta04

Thank you for your quick response. The fix works as intended. :)
