### ISSUE TITLE
.net standard 2.1 availability

### ISSUE THREAD

**Issue by madmannrw** [googleapis/google-cloud-dotnet#4850]
#4815 
Right now version google.cloud.speech.v1 version 2.0 is available for use by .net standard 2.0. Is there a time frame for a .net standard 2.1 version of google.cloud.speech.v1 for use by .net core 3 apps?

**Comment by jskeet** [comment]
There's no need for that - you can use netstandard2.0 libraries in .NET Core 3.x.

**Comment by madmannrw** [comment]
Unable to resolve service for type 'Google.Cloud.Speech.V1.SpeechClient' while attempting to activate -- not sure why it's throwing this fit. Everything build fine, but it's during runtime that it throws this in the Program.cs > CreateHostBuilder(args).Build().Run();
