### ISSUE TITLE
Shutdown has already been called

### ISSUE THREAD

**Issue by PercentageCorporation** [googleapis/google-cloud-dotnet#4856]
- OS: Windows 10 - latest
  - .NET version: 4.7.2
  - Package name and version: Google.Cloud.Firestore 2.0.0-beta02

Whenever the"GetSnapshotAsync" method is called I get a "Shutdown has already been called" exception. This code is directly from the samples at:
https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/

#### Steps to reproduce

            CollectionReference collection = db.Collection("users");
            DocumentReference document = await collection.AddAsync(new { Name = new { First = "Barney", Last = "Rubble" }, Born = -5000 });
            DocumentSnapshot snapshot = await document.GetSnapshotAsync();

**Comment by jskeet** [comment]
Please provide a complete example. I suspect you've shut down the channel somewhere, but we can't tell just from that snippet.

Note that the snippets run as tests every day in continuous integration - so they aren't inherently broken.

**Comment by PercentageCorporation** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

using Google.Cloud.Firestore;

namespace FBTest
{
    class FBTest
    {
        static void Main(string[] args)
        {
            string appPath = System.Reflection.Assembly.GetExecutingAssembly().Location;
            appPath = appPath.Remove(appPath.LastIndexOf('\\'));
            string configFile = appPath + @"\tjobs-6a549-firebase-adminsdk-le4m0-8f8e7949f5.json";
            System.Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", configFile);

            Read();
        }

        private static async void Read()
        {
            FirestoreDb db = FirestoreDb.Create("tjobs-6a549");
            CollectionReference collection = db.Collection("users");
            QuerySnapshot allUsers = await collection.GetSnapshotAsync();

        }
    }
}

**Comment by jskeet** [comment]
Okay, the problem is you're calling an async method, but then not waiting for it to finish - so the process has started shutting down.

Change your `Read` method to:

```csharp
private static async Task Read()
{
    FirestoreDb db = FirestoreDb.Create("tjobs-6a549");
    CollectionReference collection = db.Collection("users");
    QuerySnapshot allUsers = await collection.GetSnapshotAsync();
}
```

Then from your `Main` method you need to wait for `Read` to complete - either make it an `async` method and await the result, or call `Read().GetAwaiter().GetResult()`.

**Comment by PercentageCorporation** [comment]
Thanks.
