### ISSUE TITLE
dotnet-pubsub: add support for retry policy

### ISSUE THREAD

**Issue by d-torres** [googleapis/google-cloud-dotnet#4886]
Add an additional field for subscriptions that allows configuring a [RetryPolicy](https://github.com/googleapis/googleapis/blob/42ee97c1b93a0e3759bbba3013da309f670a90ab/google/pubsub/v1/pubsub.proto#L704). RetryPolicy allows configuration of how long a message can be delayed before delivery is retried. The default policy is the current behavior, in that messages are redelivered as soon as possible after a NACK or message expiration.

Reference implementation in Go will be tracked under https://github.com/googleapis/google-cloud-go/issues/1942

**Comment by jskeet** [comment]
This is already present in Google.Cloud.PubSub.V1 version 2.0.0: https://googleapis.dev/dotnet/Google.Cloud.PubSub.V1/latest/api/Google.Cloud.PubSub.V1.Subscription.html#Google_Cloud_PubSub_V1_Subscription_RetryPolicy

I don't believe any manual code is required here, as this affects the *server* behavior rather than client, correct? (Will leave open while checking that.)

**Comment by jskeet** [comment]
@chrisdunelm: Do you know anything more about this?
@d-torres: Are you able to check?

**Comment by hongalex** [comment]
> I don't believe any manual code is required here, as this affects the server behavior rather than client, correct? (Will leave open while checking that.)

RetryPolicy does indeed only affect server behavior.

Yeah, I think C# is one of the languages that passes through simple features like this automatically. However, for a few other languages, we also add integration tests to test pass-through features even if there's no requirement for manual code.
Simple tests could be setting the minimum and maximum backoff values and seeing if it works. Is adding these kind of tests something that makes sense in the C# client?

**Comment by jskeet** [comment]
> Is adding these kind of tests something that makes sense in the C# client?

I'm generally not in favour of adding tests in this repository that aren't actually testing code in this repository beyond "to protobufs and gRPC work". Sometimes it's useful to write integration tests to make sure we understand the behavior where there *is* manual code (even if the results don't directly change the manual code), but in this case I don't think it would actually provide any benefit. Instead, it's more code to write, and will increase test run lengths. We can do it if necessary, but I'd *prefer* not to unless there's a concrete expectation of how it can add value.

**Comment by hongalex** [comment]
Yeah that makes sense. I'll circle this with some other Pub/Sub client lib folks and update this issue once I have more info. Thanks!

**Comment by hongalex** [comment]
We came to the conclusion that this wasn't necessary for any GAPIC only generated. Feel free to close!
