### ISSUE TITLE
Reevaluate ASP.NET Core analyzer value

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#4891]
The analyzer complicates project generation - we should check that it still adds value. (It may well be that as the installation approach has changed, many of the things it guards against are irrelevant.)

Even if we keep it, we could potentially not generate the project file - or just generate certain parts of it (e.g. version and copyright), making the rest manual.

**Comment by jskeet** [comment]
The only analyzer in the package checks that a call to `UseGoogleTrace` doesn't come after a call to `UseMvc`. This is only relevant when trace is being configured separately anyway (as opposed to just `UseGoogleDiagnostics` in Startup) - I suspect it's a vanishingly rare issue, and not worth having the analyzer project around.

Proposal:

- Remove all references in other projects
- Delete the code
- Leave the existing package where it is
- Check build scripts for places that treat this package differently to others

**Comment by amanda-tarafa** [comment]
LGTM.
It's actually [documented](https://googleapis.dev/dotnet/Google.Cloud.Diagnostics.AspNetCore/4.0.0/index.html#initializing-tracing) on the Snippets that `UseGoogleTrace` should come before anything else.

**Comment by jskeet** [comment]
Yup. I think we've got it covered. Will get on the plan this afternoon.
