### ISSUE TITLE
What version of Firestore should I use?

### ISSUE THREAD

**Issue by DenisNP** [googleapis/google-cloud-dotnet#4906]
Hello there.

What is the difference between
* Google.Cloud.Firestore.Admin.V1
* Google.Cloud.Firestore.V1
* Google.Cloud.Firestore

?

I haven't noticed any explanation in docs. Thank you in advance.

**Comment by jskeet** [comment]
Sorry, we need to fix the description in the README for this. 

- Google.Cloud.Firestore.Admin.V1 is the admin SDK, for things like creating indexes
- Google.Cloud.Firestore is a high(ish) level library for working with Firestore, with serialization to/from regular .NET types etc
- Google.Cloud.Firestore.V1 is a low level library that's wrapped by Google.Cloud.Firestore

You probably want Google.Cloud.Firestore. The docs are [here](https://googleapis.dev/dotnet/Google.Cloud.Firestore/2.0.0-beta02/index.html), including a user guide and data model description.

**Comment by DenisNP** [comment]
Thank you for superfast reply on both my questions!
