### ISSUE TITLE
Firestore's CollectionGroup queries

### ISSUE THREAD

**Issue by DenisNP** [googleapis/google-cloud-dotnet#4907]
**Is your feature request related to a problem? Please describe.**
There is a cool feature in Firestore: [collection group queries](https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query). 
This option is available in almost all supported languages, except several, including C#. Why? It is a killer feature to get away from SQL databases to Firestore.

 **Describe the solution you'd like**
`CollectionGroup` object in .NET Firestore client with all necessary methods and properties.

 **Describe alternatives you've considered**
Many sequential standard queries. Much more slower and harder to write.

**Comment by jskeet** [comment]
Collection group queries do exist in C#. Use [`FirestoreDb.CollectionGroup`](https://googleapis.dev/dotnet/Google.Cloud.Firestore/2.0.0-beta02/api/Google.Cloud.Firestore.FirestoreDb.html#Google_Cloud_Firestore_FirestoreDb_CollectionGroup_System_String_).

I'll file an internal issue about the lack of snippets for C# for this feature on Monday.

**Comment by jskeet** [comment]
(Closing now because I don't think there's anything more to do in this repo. If it doesn't work for you, we can reopen.)
