### ISSUE TITLE
No Row option in Payload

### ISSUE THREAD

**Issue by eduardobellotto** [googleapis/google-cloud-dotnet#4933]
Hi.

I'm trying to get a prediction from the Tables regression model I've deployed in Google Cloud using Google.Cloud.AutoML.V1 v2.0.0 Nuget in a  .NET Framework 4.7.2 project using Visual Studio 2019 in Windows 10.

From the [documentation](https://cloud.google.com/automl/docs/reference/rest/v1beta1/projects.locations.models/predict#ExamplePayload), the PredictionRequest object needs a Payload object with a Run object.

But there is no Run option in Payload:

![image](https://user-images.githubusercontent.com/38707465/81068374-a2846880-8eb6-11ea-9e77-0e82b5111ee1.png)

Could you help me with this task?

Thanks in advance.

**Comment by amanda-tarafa** [comment]
You are looking at the wrong documentation. The one you linked to is for the REST service V1Beta1.
The Google.Cloud.* packages are usually client libraries for the gRPC services (there are a few exceptions), as is the case for Google.Cloud.AutoML.V1, so you should be looking at this [documentation](https://cloud.google.com/automl/docs/reference/rpc/google.cloud.automl.v1#google.cloud.automl.v1.ExamplePayload) instead. Sorry if it's not any clearer.
Let me know if you still have issues after you have taken a look at the right docs.

**Comment by eduardobellotto** [comment]
Hi Amanda.

Thank you for the fast answer!

In this new link there is no Row option for Payload.

Do you know how can I use the Predict method with a list of values for my regression model?

Thanks.

**Comment by jskeet** [comment]
> Do you know how can I use the Predict method with a list of values for my regression model?

Unfortunately the maintainers of this repository don't know details of most of the APIs we produce libraries for. We make sure that the APIs are accurately represented by the client libraries, but we usually don't have expertise in those individual APIs. I suggest you follow one of the routes on the [AutoML support page](https://cloud.google.com/natural-language/automl/docs/getting-support) for that question.

I'll close this issue now, as I believe the client libraries are okay. Good luck with your task.

**Comment by eduardobellotto** [comment]
OK. Thanks anyway.
