### ISSUE TITLE
Missing Method FirestoreDb.Create

### ISSUE THREAD

**Issue by bbuzzi** [googleapis/google-cloud-dotnet#4949]
#### Environment details

  - OS: Windows 10 Pro 1903
  - .NET version: .NET Framework 4.7.2
  - Package name and version: 
![image](https://user-images.githubusercontent.com/2326017/81221836-bcf33a80-8fb9-11ea-9d9f-e6e426810656.png)

#### Steps to reproduce

I've upgraded the packages of my project and now I can't debug it.
This is the error I'm getting:

![image](https://user-images.githubusercontent.com/2326017/81221984-faf05e80-8fb9-11ea-9729-7a6e87fdee77.png)

Any help would be greatly appreciated.
Thanks,
Bruno.

**Comment by jskeet** [comment]
The versions of Google.Cloud.Firestore and Google.Cloud.Firestore.V1 that you're using aren't compatible with Google.Api.Gax.Grpc 3.0.0.
If you update to Google.Cloud.Firestore 2.0.0-beta02, that should solve the problem.

Don't worry about it being beta - it's stable in terms of the code quality; we haven't released it as 2.0.0 in case we needed to make any API surface changes for some upcoming retry changes, but that's all I know of coming up.

(Alternatively, you *could* downgrade the versions of Google.Api.Gax.Grpc and Grpc.Core, but I think you're best off upgrading the Firestore packages.)

**Comment by jskeet** [comment]
(If you could add a comment here when you've validated that my suggestion works, that would be much appreciated.)

**Comment by jskeet** [comment]
Closing as I believe this has been addressed.
(I'm about to release Firestore 2.0.0 as well.)
