### ISSUE TITLE
Support for custom serializers/deserializers in Firestore

### ISSUE THREAD

**Issue by tchantchoj** [googleapis/google-cloud-dotnet#4960]
Hello,

I'm currently trying to migrate my C#/.NET application from Firebase Realtime Database to Firestore.

I use the following package: Google.Cloud.Firestore version 1.1.0 .Net Framework 4.7.1

I came across an issue when trying to add an object, let's call it documentToInsert, of type JObject (from the library Newtonsoft.Json) as document in Firestore.

documentToInsert string representation looks like the following:

{
  "field1": "ufgfhbifhfihfh",
  "array1": [
    "uyfhufguhfioido",
    "pzoeipeiojrfjprfi"
  ],
  "array2": [
    {
      "field1": 1,
      "field2": "hifhfiofpjfofp",
      "field3": 2,
      "field4": 3
    },
   {
      "field1": 10,
      "field2": "uyhurhurhrfhnjfbf",
      "field3": 11,
      "field4": 12
    }
  ],
  "array3": [
    1,
    2,
    3
  ]
}

When I do:
await FIRESTORE_DATABASE.Collection("items")
                        .AddAsync(documentToInsert);

I get the following exception:
System.ArgumentException: 'Unable to create converter for type Newtonsoft.Json.Linq.JValue'

Is there a way I can tell the Firestore library which serializers/deserializers to use?

Thanks,

JC

**Comment by jskeet** [comment]
We have support for custom serializers as described here: https://googleapis.dev/dotnet/Google.Cloud.Firestore/2.0.0/datamodel.html#custom-converters

However, writing a custom converter for `JObject` will be at least somewhat challenging - we don't provide any Json.NET converters at the moment.

Do you have a .NET type representing your document, or could you create one? If you could, that would make it much easier to either write a converter for that specific document type, or you may very well be able to just add `[FirestoreData]` and `[FirestoreProperty]` annotations to the types as described in https://googleapis.dev/dotnet/Google.Cloud.Firestore/2.0.0/datamodel.html#mapping-with-attributed-classes.

**Comment by tchantchoj** [comment]
Hello Jon,

Thanks for the quick reply.

For the sake of simplicity, I was actually trying to avoid having to create .NET types to represent my documents.

I guess, I will follow your recommendation then.

Thanks,

JC
