### ISSUE TITLE
Dotnet based google cloud speech to text phrases not working

### ISSUE THREAD

**Issue by linuxqtcppexamples** [googleapis/google-cloud-dotnet#4963]
#### Environment details

  - OS: Windows 10
  - .NET version: VS 2017 
  - Package name and version: Google cloud speech to text : v1

#### Steps to reproduce

  1. Add phrase words to SpeechContext
  2. No difference observed between with adding phrase words and without adding phrase words

Making sure to follow these steps will guarantee the quickest resolution possible.

**Please find snippet code below:**

```csharp
SpeechContext speechContext = new SpeechContext();
speechContext.Phrases.Add("$TIME");
speechContext.Phrases.Add("$YEAR");
speechContext.Phrases.Add("$DAY");
speechContext.Phrases.Add("$MONTH");
speechContext.Phrases.Add("$MONEY");

string[] phraseWords= {  "blew" , "gro", "Safe" };
speechContext.Phrases.Add(phraseWords);

SpeechClient.StreamingRecognizeStream streamingCall = speech.StreamingRecognize();

RecognitionConfig RecConfig = new RecognitionConfig
{
    Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
    SampleRateHertz = int.Parse(hertz),
    LanguageCode = language
};

RecConfig.SpeechContexts.Add(speechContext);

await streamingCall.WriteAsync(new StreamingRecognizeRequest
{
    StreamingConfig = new StreamingRecognitionConfig
    {
        Config = RecConfig,
        InterimResults = false
    }
});
```

Thanks!

**Comment by jskeet** [comment]
I *suspect* this isn't a client library issue - it's more something for the Speech-to-Text team to look at. But if you could provide a sample input file, that would make it much easier for us to reproduce. Could you attach one here please?
Also, it's likely to be simpler to diagnose this with a non-streaming call - have you tried that and seen the same issue?

**Comment by jskeet** [comment]
Any more information about this? Without more information I'm afraid we won't be able to proceed any further - I'll close the issue if we haven't heard anything by the end of the week.

**Comment by jskeet** [comment]
Closed due to lack of further information. We can reopen if we get more information.
