### ISSUE TITLE
BigQuery - InsertRow - Not supporting UInt64

### ISSUE THREAD

**Issue by guypld** [googleapis/google-cloud-dotnet#4971]
Hi,

Big Query Numeric column type max value should be larger than UInt64 (ulong) max value, but unfortunatly it is not being supported in the code:
https://github.com/googleapis/google-cloud-dotnet/blob/12bdab84277957b5581388ab0e8d0de92cdd9413/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryInsertRow.cs#L80

and I get this error:

> Unable to use value of type System.UInt64 in BigQueryInsertRow

Is there any reason for that?
Thanks.

**Comment by jskeet** [comment]
Mapping all the other integer types to `BigQueryDbType.Int64`, but *just* `ulong` to `BigQueryNumeric` would be quite error-prone in my view.

It's very easy to do it *explicitly* though - just cast your value to `BigQueryNumeric`. That makes your intent clear, and the existing code will handle that.

**Comment by guypld** [comment]
Thanks for the reply, I'll use the explicit cast as mentioned.
