### ISSUE TITLE
BigQuery: Regex check in BigQueryInsertRow.Add causes excessive CPU load

### ISSUE THREAD

**Issue by 47th** [googleapis/google-cloud-dotnet#4975]
We are using streaming inserts to push data to BigQuery. Under high load this process starts consuming more CPU than expected. Profiler shows Regex.IsMatch in BigQueryInsertRow.Add high in the list of methods consuming CPU time.

#### Environment details

  - OS: Windows Server 2016 Datacenter
  - .NET version: 4.7.2
  - Package name and version: Google.Cloud.BigQuery.V2, version 1.4.0

#### Steps to reproduce

We use the following code for streaming inserts:
```c#
BigQueryClient client = ...;
BigQueryInsertDataRequest insertRequest = ...;

await client.InsertRowsAsync(
    client.ProjectId,
    insertRequest.DatasetName,
    insertRequest.TableName,
    insertRequest.ToInsertRows(), new InsertOptions(), t)
        .ConfigureAwait(false);

public class BigQueryInsertDataRequest
{
    public BigQueryInsertDataRequest(string datasetName, string tableName,
        IReadOnlyList<IDictionary<string, object>> rows)
    {
        DatasetName = datasetName;
        TableName = tableName;
        Rows = rows;
    }

    public string DatasetName { get; }
    public string TableName { get; }
    public IReadOnlyList<IDictionary<string, object>> Rows { get; }

    internal IEnumerable<BigQueryInsertRow> ToInsertRows()
    {
        return Rows.Select(r => ToInsertRow(r));
    }

    private BigQueryInsertRow ToInsertRow(IDictionary<string, object> data)
    {
        BigQueryInsertRow row = new BigQueryInsertRow();
        foreach (var pair in data)
        {
            if (pair.Value is decimal decimalValue)
            {
                row.Add(pair.Key, (BigQueryNumeric)decimalValue);
            }
            else if (pair.Value is IDictionary<string, object> dictionaryValue)
            {
                row.Add(pair.Key, ToInsertRow(dictionaryValue));
            }
            else if (pair.Value is IEnumerable<IDictionary<string, object>> listValue)
            {
                row.Add(pair.Key, new List<BigQueryInsertRow>(listValue.Select(v => ToInsertRow(v))));
            }
            else row.Add(pair.Key, pair.Value);
        }
        return row;
    }
}

```

**Comment by jskeet** [comment]
Notes:

`BigQueryInsertRow.Add` calls `TableSchemaBuilder.ValidateFieldName`, which is where the regex actually occurs. (We only do regex matching there and in `BigQueryNumeric`.)

Some options to consider:

- Pass `RegexOptions.Compiled` in the regex constructor
- Create a `BigQueryFieldName` class which validates the field name on construction - which means we could add an `Add(BigQueryFieldName name, object value)` overload that doesn't need to validate. (This would require your code to be changed, of course.)
- Create a cache of "known valid" names to use before checking the regex.

I'll benchmark `RegexOptions.Compiled` to see if that helps - if it does, that would be by far the least invasive fix.

**Comment by jskeet** [comment]
Okay, so using `RegexOptions.Compiled` doesn't help. Hand-writing the validation really, really does. PR coming when I've checked that we have tests.

**Comment by jskeet** [comment]
This should be *much* improved in the 2.0.0 release (or the next beta). That won't be *immediately*, but hopefully in the next few weeks.

**Comment by 47th** [comment]
Thank you very much!
