### ISSUE TITLE
Clear description on how thread-safe the Google Storage API calls are

### ISSUE THREAD

**Issue by Issam-Corissa** [googleapis/google-cloud-dotnet#4988]
**Is your feature request related to a problem? Please describe.**
I am currently using the Google Storage API on an ASP.NET Core app, I cannot seem to find documentation clearly stating that API calls are thread safe or not, forcing me to assume they are not for safety. 

 **Describe the solution you'd like**
The google cloud storage documentation should have a section about thread safety. (https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Storage.V1/docs/index.md)

 **Describe alternatives you've considered**
Unique StorageClient per thread, but again the documentation does not really state if that is safe or not.

 **Additional context**
When writing a service for using Google Storage, it's currently not clear if I can safely use the service as a singleton.

**Comment by jskeet** [comment]
Thanks for raising the issue. I can confirm that all our clients *are* thread-safe, and indeed using a single instance is the preferred approach. I'm not sure of the best place to document that, but we'll have a think about it and leave this issue open until we've found a good place to do so. (It's one of those aspects which is very important for production use, but not for getting started - we don't want to highlight it in the first five minutes, if you see what I mean.
