### ISSUE TITLE
Any plan for document ai api?

### ISSUE THREAD

**Issue by JandosHk** [googleapis/google-cloud-dotnet#4989]
I see there are java, nodejs, and python library for doc ai. Any plan for .net/.net core?

**Comment by jskeet** [comment]
Currently API is only in beta, and I believe the team only wants to use those languages for the beta. I'll ask internally though. I expect when the API becomes stable, we'll at least create a .NET library then.

**Comment by jskeet** [comment]
Just to keep you up to date - I'm still just getting final confirmation, but I think we probably *will* end up releasing the v1beta2 in C#. It shouldn't take too long to go from "yes we want it" to "release 1.0.0-beta01" - so if it happens, I'd expect that to be some time next week.

**Comment by JandosHk** [comment]
Great! I managed to call the API by calling node code from C#, but I'd much prefer C# directly.

**Comment by jskeet** [comment]
Further update: it's confirmed that we want to do this. I'm just getting a few configuration changes through source control, although I may be able to short-circuit that too...

**Comment by jskeet** [comment]
We've now released Google.Cloud.DocumentAI.V1Beta2 version 1.0.0-beta01: https://www.nuget.org/packages/Google.Cloud.DocumentAI.V1Beta2

It's unlikely that we'll have any samples any time soon, but it sounds like you're likely to be able to find your way around easily enough :)

**Comment by JandosHk** [comment]
Really appreciate that! It was so quick.

**Comment by meMuszr** [comment]
Glad I stumbled across this issue, was about to implement my own library for the API. Thanks!
