### ISSUE TITLE
Add support for the startOffset/endOffset parameters to the List Objects Cloud Storage method

### ISSUE THREAD

**Issue by stefanpavlov** [googleapis/google-cloud-dotnet#4993]
**Is your feature request related to a problem? Please describe.**
It is related to a minor performance issue. Not having access to these parameters means the output of the list method can't be constrained properly.

 **Describe the solution you'd like**
I would like Google.Apis.Storage.v1.ObjectsResource.ListRequest and/or Google.Cloud.Storage.V1.ListObjectsOptions to have StartOffset and EndOffset properties that are passed on during the [list request](https://cloud.google.com/storage/docs/json_api/v1/objects/list).

 **Describe alternatives you've considered**
As a workaround I'm using the prefix parameter as startOffset, looping over the results and breaking out of the cycle when the name is outside the range I need. This relies on the results being in lexicographical order [which seems to be true for now](https://cloud.google.com/storage/docs/listing-objects).

 **Additional context**
One of the problems I need to solve is listing all versions of a given blob. I couldn't figure out how to do this using the available parameters (Prefix, Delimiter and IncludeTrailingDelimiter) so I resorted to the workaround mentioned above.

**Comment by jskeet** [comment]
We should be able to add this - basically it's unfortunate that we have to manually add code when the API expands, but that's just how things are structured.
I suspect I should be able to get to this next week.
