### ISSUE TITLE
How to create traces in Console App

### ISSUE THREAD

**Issue by BTXAndy** [googleapis/google-cloud-dotnet#5018]
Hi,

Is there a sample somewhere that shows how to create traces outside of ASP.NET? If not, can you describe what would be required?

(We have containers that run background jobs and it would be good to trace these as well as our asp.net core services)

thanks

**Comment by jskeet** [comment]
I don't believe we have any samples for that, no. Assigning to Amanda, who can hopefully give you some pointers, but I wouldn't expect full code samples or anything like that - at least not for the moment.

**Comment by amanda-tarafa** [comment]
We don't have samples for that but it shouldn't be hard to accomplish.
Take a look at [SimpleManagedTracerTests](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.IntegrationTests/Trace/SimpleManagedTracerTest.cs) for how to create traces from other than ASP.NET.
Since you won't have a middleware to create the tracer for you, you'll have to do that yourself, but you can use the functions in [ManagedTracer](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/ManagedTracer.cs) to do that.

Let me know if this doesn't help (or if there's more demand for it) and I can add a couple of samples.

**Comment by amanda-tarafa** [comment]
@BTXAndy I will close this issue now since I belive I've answered your question. Please leave a comment if you believe otherwirse or a new issue if you encounter problems using the approach I suggested.

**Comment by tomislavpet** [comment]
@amanda-tarafa Can you please check out this example? Tracer gets injected into the service, but nothing gets sent to Google Cloud. Logging works fine and is visible on GC.

```
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;
using Google.Cloud.Diagnostics.Common;
using Google.Cloud.Diagnostics.AspNetCore;
using Microsoft.Extensions.Configuration;

namespace Example
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var services = new ServiceCollection();
            var serviceProvider = ConfigureServices(services);

            var app = serviceProvider.GetService<MyService>();

            for (int i = 0; i < 20; i++)
            {
                app.Doit();
            }

            Console.WriteLine("Waiting 10 sec");

            Task.Delay(10000).Wait();

            Console.WriteLine("Done");
        }

        public static IServiceProvider ConfigureServices(IServiceCollection serviceCollection)
        {
            var serviceProvider = serviceCollection.BuildServiceProvider();

            var provider = serviceProvider.GetService<ILoggerProvider>();

            IConfiguration config = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", true, true)
                .Build();

            serviceCollection
                .AddOptions()
                .Configure<StackdriverOptions>(config.GetSection("Stackdriver"))
                .AddLogging(opt => { opt.AddProvider(GoogleLoggerProvider.Create(null, config["Stackdriver:ProjectId"])).AddConsole().AddDebug(); })
                .AddGoogleTrace(options =>
                {
                    options.ProjectId = config["Stackdriver:ProjectId"];
                    options.Options = TraceOptions.Create(
                        retryOptions: RetryOptions.NoRetry(ExceptionHandling.Propagate),
                        bufferOptions: BufferOptions.NoBuffer(),
                        qpsSampleRate: double.MaxValue
                    );
                })
                .AddSingleton<MyService>();

            serviceProvider = serviceCollection.BuildServiceProvider();

            return serviceProvider;
        }
    }

    public class StackdriverOptions
    {
        public string ProjectId { get; set; }
        public string ServiceName { get; set; }
        public string Version { get; set; }
    }

    public class MyService
    {
        private ILogger m_Logger;
        private IManagedTracer m_Tracer;

        public MyService(ILogger<MyService> logger, IManagedTracer tracer)
        {
            m_Logger = logger;
            m_Tracer = tracer;
        }

        public void Doit()
        {
            using (m_Tracer.StartSpan("test trace"))
            {
                Console.WriteLine("MyService.Doit");

                m_Logger.LogInformation("Doing it!");
                m_Logger.LogWarning("Warning!");
                m_Logger.LogError("Here's an error!");

                Task.Delay(500).Wait();

                Console.WriteLine("MyService.Doit");
            }
        }
    }
}
```

**Comment by amanda-tarafa** [comment]
@tomislavpet please do create a new issue, (and maybe reference this one).
And to set some expectations I won't be able to get to this until next week at the very least. You can fork the repo and debug your code against our library code so you can see which bits you are missing.
