### ISSUE TITLE
Support ability to specify ServiceContext in GoogleLogger

### ISSUE THREAD

**Issue by shaneqld** [googleapis/google-cloud-dotnet#5028]
Hi,

I have recently added Google.Cloud.Diagnostics.AspNetCore logging into an existing application running in GKE (and it's working great).

My assumption is that I don't need to use the library's error reporting capabilities, as all errors that occur within my application are caught and logged with ILogger<T>.LogError(exception, message). These appear properly in cloud console.

Google Cloud Error Reporting automatically picks up these errors from the logs. However, in cloud console, all errors are reported as coming from "gke_instance", which does not help identify where the errors are coming from.  There is an [existing discussion](https://issuetracker.google.com/issues/62828996) about using resource labels from logs to better identify services, but 3 years on it is not supported yet.

I believe we can provide this information to error reporting by adding serviceContext to the JSON payload of log entries, however GoogleLogger does not expose any capabilities that permit configuring this.

I confess I have not used this library for long, and I might be missing something. But if not, could we potentially add support similar to ILogEntryLabelProvider, but for the JSON payload?

Cheers!

**Comment by jskeet** [comment]
How are you configuring the diagnostics package? If you're calling the `UseGoogleDiagnostics` extension method, there's a `serviceName` parameter you can specify at that point. Does that help you?

**Comment by shaneqld** [comment]
I am using the `ILoggerFactory.AddGoogle` extension method. I chose this as Istio is already pushing traces, and error reporting already supports logs I insert with `ILogger.LogError`.

With regards to `UseGoogleDiagnostics`, this method only passes the `serviceName` to error reporting.  `serviceName` does not make its way into `GoogleLogger`.

**Comment by jskeet** [comment]
Ah, right - whoops. I'll have a closer look when I get the chance.

**Comment by amanda-tarafa** [comment]
You can use Google Error Reporting on its own as shown [here](https://googleapis.dev/dotnet/Google.Cloud.Diagnostics.AspNetCore/4.0.0/index.html#registering-error-reporting). Although I realize that if you are logging other than errors, then you would need to register both the GoogleLogger and Googler Error Reporting. But if you are using the logger to only log errors, then this will solve your problem, without interfering with Istio tracing. ServiceName and Version will be included in the serviceContext field of the json payload.

Still, I see the use case for adding serviceContext for a general log entry, so I think we could add that. We probably wouldn't add anything as general as ILogEntryLabelProvider for the json payload, but we can definetely add ServiceName and Version to LoggerOptions, and include those on the serviceContext field when present.

Let me know if either or both will help, and we can go from there.

**Comment by shaneqld** [comment]
Hi @amanda-tarafa, thank you for the suggestion. In this case ILogger is being used for logging all log levels (including errors and warnings with accompanying exceptions); I am integrating Google.Cloud.Diagnostics.AspNetCore into several existing services like this.

The ability to specify ServiceName and Version in LoggerOptions is perfect for this use case and would solve the problem.

**Comment by amanda-tarafa** [comment]
> The ability to specify ServiceName and Version in LoggerOptions is perfect for this use case and would solve the problem.

Great. I will work on this, but probably late next week, maybe even early the week after.

**Comment by amanda-tarafa** [comment]
This has now been released in https://www.nuget.org/packages/Google.Cloud.Diagnostics.AspNetCore/4.1.0-beta01.
