### ISSUE TITLE
Using Task.Run in Google.Cloud.Spanner.Data causes remarkable delay 

### ISSUE THREAD

**Issue by walkure** [googleapis/google-cloud-dotnet#5114]
We are developing a server application using Google.Cloud.Spanner.Data with .NET Core 3.1.
The application server is built with ASP.NET Core MVC.

Remarkable delay in the part that uses `Task.Run` at `Google.Cloud.Spanner.Data`  has occurred when load testing sending a large number of requests.
At high load, it takes more than 10 seconds and the transaction times out.

Specifically, call `Task.Run()` in [GetOrdinal()](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDataReader.cs#L225) and in [PopulateMetadata()](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDataReader.cs#L353) calliing from `GetFieldValue()` via `GetSpannerFieldType()`.

So, when I cloned `google-cloud-dotnet` and implemented the async method of `GetOrdinal()` and `GetFieldValue()`,
The noticeable delay mentioned above has been resolved.

How about implementing the Async version for the two methods `GetOrdinal()` and `GetFieldValue()` ?

Now that I've signed the Corporate CLA, I can refine my implementation and contribute.

**Comment by jskeet** [comment]
We *could* implement extra methods for those, yes. They're not part of ADO.NET (which basically wasn't designed for asynchrony) which reduces the portability of the solution, unfortunately.

I do wonder where the delay is coming from - it sounds like your system probably has a huge number of tasks, and the thread-pool can't cope - my only concern is that this would be tackling one symptom, only to propagate the problem elsewhere.

Another option that might be more transparent is to populate the metadata more eagerly - at which point a lot of things might be simplified. I'll have to look into how feasible that would be.

**Comment by walkure** [comment]
Yes, Those async methods who I proposed is __NOT__ a part of ADO.NET.

But, Calling GetOrdinal() and GetFieldValue() is unavoidable because I need to get the data by specifying the column by name.

[ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1) recommends not to use Task.Run, so I want an idea that doesn't call Task.Run and is consistent with the ADO.NET interface.

How about implementing the async version of `GetFieldValue<T>(string columnName)` which does not inherited from `DbDataReader`.

**Comment by jskeet** [comment]
Well yes, it's nice not to use `Task.Run` if you can avoid it, but the fundamental problem is that Spanner communication is asynchronous and ADO.NET is synchronous. (And we need to use `Task.Run()` rather than blocking on the task as the same code could be used from WPF etc.) Unfortunately checklists like those "best practices" don't often take account the reality of synchronous code :(

I'll look at it when I get more time, ideally changing it to populate the metadata more eagerly (as I suspect its needed everywhere anyway). It won't be this week though I'm afraid.

**Comment by jskeet** [comment]
Fixed now - there's a new `GetOrdinalAsync` method to call if you want to use that before calling `Read` or `ReadAsync` - but after you've moved to the first row, it shouldn't call Task.Run anyway.

**Comment by jskeet** [comment]
(We're planning on doing a 3.1.0 release later this week, so the change will be in that.)

**Comment by walkure** [comment]
Thanks a lot !

However, it seems that this change does not concern about GetFieldValue(int ordinal), I think.

// GetFieldValue(int ordinal) calls GetSpannerFieldType(int i) which calls PopulateMetadata().

**Comment by jskeet** [comment]
That should be fine though - because `PopulateMetadata` does nothing if the metadata already exists, which it already will if you've called Read or ReadAsync... and if you *haven't* called Read or ReadAsync, then GetFieldValue will fail anyway.

**Comment by walkure** [comment]
We've tested brand-new libraries v3.1.0 with our server codes, and this issue was solved.

Thank you very much!
