### ISSUE TITLE
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")

### ISSUE THREAD

**Issue by fasetto** [googleapis/google-cloud-dotnet#5152]
When I access the database I get this error sometimes.
I am using *Google.Cloud.Firestore* nuget package.

#### Environment details

  - OS: Windows
  - .NET version: 3.1.201
  - Package name and version: Google.Cloud.Firestore latest

#### Steps to reproduce

  1. Start your client application to access firebase and wait some time (5mins)
  2. When you access the database (ex: get some data) you will get this issue

Here is stacktree: 
```cs
 ---> Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")
   at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
   at Google.Api.Gax.Grpc.AsyncResponseStream`1.MoveNextAsync(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.<ForEachAsync>g__Core|295_0[TSource](IAsyncEnumerable`1 source,
Action`1 action, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ForEach.cs:line 31
   at System.Linq.AsyncEnumerable.<ForEachAsync>g__Core|295_0[TSource](IAsyncEnumerable`1 source,
Action`1 action, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ForEach.cs:line 31
   at Google.Cloud.Firestore.Query.GetSnapshotAsync(ByteString transactionId, CancellationToken cancellationToken)
   at Charlie.Services.FirebaseService.FindRecipeAsync(String name) in C:\Users\serka\Source\Repos\charlie-bot\src\Charlie\Services\FirebaseService.cs:line 37
   at Charlie.Modules.BasicModule.FindRecipe(String name) in C:\Users\serka\Source\Repos\charlie-bot\src\Charlie\Modules\BasicModule.cs:line 38

```

**Comment by jskeet** [comment]
Please provide more details about the Google library you're using. (It sounds like it's Firestore, not Firebase, for a start.) It would also be useful to know how long "some time" is... 5 minutes? An hour? A day?

A short console app (with no other dependencies) to demonstrate the problem would be even better. (Is Charlie.Services your code, or another library?)

**Comment by jskeet** [comment]
(I've typically seen "Stream removed" with network problems. Your networking configuration could be very important here, including any firewall and proxy you're behind.)

**Comment by fasetto** [comment]
> (I've typically seen "Stream removed" with network problems. Your networking configuration could be very important here, including any firewall and proxy you're behind.)

Updated the issue. I am using *Google.Cloud.Firestore* nuget package. After 5 mins for example, it gives me this error.
I dont think its because of my network configuration.

Thanks for the reply.

**Comment by jskeet** [comment]
> After 5 mins for example, it gives me this error.

So if I write a console app that writes a value to the database, waits 5 minutes, then reads it, you'd expect to see the error? If so, I'll write an app for that tomorrow morning, but I really wouldn't *expect* that to fail, based on my previous experiences...

**Comment by fasetto** [comment]
> > After 5 mins for example, it gives me this error.
> 
> So if I write a console app that writes a value to the database, waits 5 minutes, then reads it, you'd expect to see the error? If so, I'll write an app for that tomorrow morning, but I really wouldn't _expect_ that to fail, based on my previous experiences...

Okay, I will do more tests and try to find what really causes this issue.

**Comment by fasetto** [comment]
```cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Google.Cloud.Firestore;

namespace GrpcExceptionRepro
{
    class Program
    {
        private static FirestoreDb database;

        static async Task Main(string[] args)
        {
            InitFirebase();
            
            database = FirestoreDb.Create("project-id-here");

            var user = await FindUser("fasetto");

            System.Console.WriteLine($"Found user: {user.Name}\tId: {user.Id}");

            await Task.Delay(TimeSpan.FromMinutes(4));
           
            await FindUser("fasetto");
        }

        static void InitFirebase()
        {
            var keyPath = "./firebase-service-account-key.json";

            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", keyPath);
        }

        static async Task<User> FindUser(string name)
        {
            var collection = database.Collection("users");
            var snapshot   = await collection.GetSnapshotAsync().ConfigureAwait(false);

            var user = snapshot.Documents
                .Select(x => x.ConvertTo<User>())
                .Where(x => x.Name.ToLower().Contains(name.ToLower()))
                .FirstOrDefault();

            return user;
        }
    }
}

```

@jskeet This is will cause that grpc error. I have no idea whats wrong. 
[GrpcExceptionRepro.zip](https://github.com/googleapis/google-cloud-dotnet/files/4908227/GrpcExceptionRepro.zip)

**Comment by jskeet** [comment]
Thanks very much - that'll be very useful indeed. I'll see whether it reproduces the problem for me tomorrow.

Just to clarify, are you running this from your development machine, or is it running in the Cloud somewhere?

**Comment by fasetto** [comment]
Running this on my development machine. Haven't tried on cloud server yet, but I think it will give me the same exception.

**Comment by jskeet** [comment]
User class from the zip file:

```csharp
using Google.Cloud.Firestore;

namespace GrpcExceptionRepro
{
    [FirestoreData]
    public class User
    {
        [FirestoreDocumentId]
        public string Id { get; set; }

        [FirestoreProperty]
        public string Name { get; set; }
    }
}
```

**Comment by jskeet** [comment]
I've run this several times this morning without issue. That makes me think it may well be something in your network setup, e.g. a proxy that severs connections after a few minutes. If you could try running the code in a different environment (e.g. on the Cloud, or via a different network) that would be really useful.

**Comment by fasetto** [comment]
> I've run this several times this morning without issue. That makes me think it may well be something in your network setup, e.g. a proxy that severs connections after a few minutes. If you could try running the code in a different environment (e.g. on the Cloud, or via a different network) that would be really useful.

Thank you. I will try this again on cloud.

**Comment by fasetto** [comment]
@jskeet It works on cloud without any issue like you said.
But I still wonder why it doesn't work on my development machine though.
Anyways, you can close this if you like.

**Comment by jskeet** [comment]
Okay, I'll close for now - but I'd suggest you look into your network setup for answers as to why it's not working for you. If you end up with more information that might help us avoid this for other users, do add another comment and we can reopen.
