### ISSUE TITLE
Request sample DialogFlow mega agent.

### ISSUE THREAD

**Issue by juliolitwin** [googleapis/google-cloud-dotnet#5156]
Yo,

Is there any possibility of adding an example using mega agents? I didn't find anything related to sub agents in QueryParams.

Thanks,
Cheers.

**Comment by jskeet** [comment]
Assigning to Amanda who owns the samples repo, but only so that she can route the request to the Dialogflow team.

**Comment by amanda-tarafa** [comment]
Closing in favor of GoogleCloudPlatform/dotnet-docs-samples/issues/1129
