### ISSUE TITLE
ReadMe link 404s

### ISSUE THREAD

**Issue by dh--** [googleapis/google-cloud-dotnet#5157]
The link to getting-started-dotnet in https://github.com/googleapis/google-cloud-dotnet#example-applications goes to https://github.com/googleapis/getting-started-dotnet/

That URL 404s.

I'm not sure where the best target for that link is.

**Comment by jskeet** [comment]
Whoops - thanks for that. I suspect the link wasn't updated when the repo moved.
The correct link is https://github.com/GoogleCloudPlatform/getting-started-dotnet/ - I'll send out a PR to fix that now.
