### ISSUE TITLE
Missing dotnet client library for identitytoolkit.googleapis.com service

### ISSUE THREAD

**Issue by Bartizan** [googleapis/google-cloud-dotnet#5179]
Hi. Trying to manage [Identity Toolkit API](https://cloud.google.com/identity-platform/docs/reference/rest/v2#service:-identitytoolkit.googleapis.com) for users and tenants required to create either a custom library or build a generated library based on the discovery documents.
Is there a reason why the dotnet client library missing?

I'd **expect** to have nugets, something like _Google.Cloud.IdentityToolkit.V1_ and _Google.Cloud.IdentityToolkit.V2_, in nuget.org repository and maintained by Google Team.

 **Additional context**
Some observations
- There are two nugets mentioned because of v1 is responsible for user management and v2 for tenants. Both APIs are officially referred and documented. 
- [Google APIs Discovery service](https://www.googleapis.com/discovery/v1/apis), that seems to be used for generating client libraries, does not define those two services but points to identitytoolkit v3 (_No identitytoolkit v3 nuget, even if it were, it is undocumented and at least does not cover tenants functionality_). Should identitytoolkit v1 and v2 be mentioned in discovery document either? 

Thanks

**Comment by amanda-tarafa** [comment]
Closing this one in favor of googleapis/google-api-dotnet-client#1605. The Identity API is REST and so should live in googleapis/google-api-dotnet if anything.
