### ISSUE TITLE
spanner: set the google-cloud-resource-prefix header in clients

### ISSUE THREAD

**Issue by skuruppu** [googleapis/google-cloud-dotnet#5181]
The `google-cloud-resource-prefix` header is expected to be set for the data and two admin clients of Cloud Spanner. I found that the header is set in [Firestore](https://github.com/googleapis/google-cloud-dotnet/blob/053434fa2a4d99da8a804d1645e2b634fe64be45/apis/Google.Cloud.Firestore.V1/Google.Cloud.Firestore.V1/FirestoreClientPartial.cs#L54) and [Datastore](https://github.com/googleapis/google-cloud-dotnet/blob/8eda274f0fe6e7fa4301da9d44b2662e25771646/apis/Google.Cloud.Datastore.V1/Google.Cloud.Datastore.V1/DatastoreClientPartial.cs#L22).

So I can follow that example to set it for the Spanner clients.

**Comment by jskeet** [comment]
Great, thank you. Let me know if anything is unclear. (It's somewhat annoying that we have to do this via manual code, admittedly.)

**Comment by jskeet** [comment]
@skuruppu: Can this issue now be closed? And would you like a new release, or do you want to wait until #5209 has been addressed?

**Comment by skuruppu** [comment]
@jskeet not quite :( It turns out I forgot to cover the StreamingRead API. I also haven't yet handled the admin APIs. I may take me a couple more weeks to complete these tasks. So we should hold out on a release until I do these.

These changes are not related to #5209 so releases can be done independently of that.

**Comment by skuruppu** [comment]
@jskeet it turns out we [don't have hand-written wrappers](https://github.com/googleapis/google-cloud-dotnet/search?q=StreamingRead&unscoped_q=StreamingRead) around the StreamingRead API, which I think means we can't do something like #5255. Instead, we have to ask users to set the header manually. Is my understanding correct?

**Comment by jskeet** [comment]
In vacation until Tuesday - will look then.

**Comment by jskeet** [comment]
Right, now I can get my head into this again... basically we don't support StreamingRead in any client-friendly way at the moment.

Two options to consider:

- Support it in PooledSession, which probably requires additional work to support PartialResultSet; at this point we could add the header ourselves
- Leave it in its current state of "I'd be astonished if you wanted to use the raw API for this"

I don't know the use cases for calling StreamingRead, so I don't know how important it is. I'd suggest going with option 2 for now, but including option 1 into future planning meetings as something to consider. Does that work for you?

**Comment by skuruppu** [comment]
Just looked at some stats and it seems to support "I'd be astonished if you wanted to use the raw API for this" as I don't see anyone using it.

So let's go with option 2.

I will send you PRs for supporting the admin APIs, just to close out this issue. Hoping to do this tomorrow but if not, it'll have to be next week.
