### ISSUE TITLE
ASPNET Core 3.1 OIDC validation

### ISSUE THREAD

**Issue by Talento90** [googleapis/google-cloud-dotnet#5194]
Hello, I am using cloud scheduler to create a CRON job that triggers an HTTP request using OIDC token as authorization mechanism. 

My problem is to find  authority url and configure according the following code:

```csharp
            services
                .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.Authority = "https://accounts.google.com/.well-known/openid-configuration";
                    options.IncludeErrorDetails = true;

                    options.TokenValidationParameters = new TokenValidationParameters()
                    {
                        RequireExpirationTime = true,
                        RequireSignedTokens = true,
                        ValidateActor = true,
                        ValidateAudience = false,
                        ValidateIssuer = true,
                        ValidateIssuerSigningKey = true,
                        ValidateLifetime = true,
                        ValidateTokenReplay = true,
                        ValidIssuer = options.Authority,
                    };
                });
```

Basically, I want to validate the token we get comes from the GCP and it contains the service account specified in the cron schedule.

**Comment by amanda-tarafa** [comment]
> configure according the following code

The code you have pasted uses Microsoft's [JwtBearerExtensions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.jwtbearerextensions.addjwtbearer?view=aspnetcore-3.0) and I'm afraid I'm not familiar with using those extensions. You should create an issue for Microsoft if you need help on using it.

> My problem is to find authority url

I'm not exactly sure what Authority URL refers to here, guessing, I would say it's either the issuer or the URL where the public key of the signing certificate lives. But what it's value should refer to is something you also need to confirm with Microsoft, taking a quick look at the reference docs, it's not clear to me.
In any case, whether it refers to the issuer, the URL of the public key or something else, the value you need to specify will depend entirely on how you are obtaining the OIDC token, and there's no info in your question about that.

I can give you some of Google's defaults if you want to try, but again, whether these work or not will depend on what Authority URL referest to and how you are obtaining the OIDC token:

  - For the URL where the signing public key lives:
    - For RS256 signed certificates, https://www.googleapis.com/oauth2/v3/certs will be used.
    - For ES256 signed certificates, https://www.gstatic.com/iap/verify/public_key-jwk will be used.
  - The issuers of some Google signed JWT are one of:
    - https://accounts.google.com
    - accounts.google.com

> and it contains the service account

Usually you can use the `sub` and `email` properties of the JWT payload for extracting the identity represented by the OIDC token. But again, I don't know where you are getting your OIDC token from.

And lastly, using the `Google.Apis.Auth` client library you can both obtain and verify OIDC tokens. Here are some IAP based examples that might help you even if your application CRON job is not calling an IAP protected app, just use the code bits that generate and verify the OIDC token. You can use these as an alternative to JwtBearerExtensions or simply to try token validation in a console app without having to set up services etc., until you get the right values.

  - [Obtain an OIDC token from a service account](https://cloud.google.com/iap/docs/authentication-howto#iap_make_request-csharp).
  - [Verify an OIDC token](https://cloud.google.com/iap/docs/signed-headers-howto#iap_validate_jwt-csharp)

**Comment by Talento90** [comment]
Thank you @amanda-tarafa! I am going to have a look at your useful resources 🙇  🥇 

I am closing this issue for now 👍
