### ISSUE TITLE
Google.Cloud.AutoML.V1 GcsSource.InputUri setter

### ISSUE THREAD

**Issue by dcao-godaddy** [googleapis/google-cloud-dotnet#5195]
InputUri is a required field for a GcsSource object when used as part of the InputConfig for importing data into a dataset, but there is no setter or builder associated with this field and it is readonly. Following documentation on other language apis
https://cloud.google.com/translate/automl/docs/datasets#training-data 
the InputUri field should not be readonly and should have a setter for directly setting the value to the correct gs url.

**Comment by jskeet** [comment]
`InputUris` is a repeated field - while the property is read-only, it returns a `RepeatedField<string>` which is mutable. (All C# protobuf objects are mutable.)
Please see https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-modify-repeated-fields-and-maps-in-protobuf-messages

In this case, you'd use something like:

```csharp
var source = new GcsSource { InputUris = { uri1, uri2 } };
```
