### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-dotnet#5196]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by jskeet** [comment]
Done. The "enforcing rules for admins" can be discussed internally, but I've enabled it for now. (At worst, it will slow me down a bit for cases where I really want to make the change...)
