### ISSUE TITLE
General dotnet client library for Firebase?

### ISSUE THREAD

**Issue by AndrewMorsillo** [googleapis/google-cloud-dotnet#5207]
Dotnet is coming to more client applications thanks to Blazor, Godot, and mono wasm. There exists a Firebase client SDK for dotnet via Unity but I don't see a client to use Firebase with a non-unity dotnet application. Is there a general purpose dotnet Firebase client library? Can the functionality be derived from the Unity Firebase SDK for non-unity apps? Thanks!

**Comment by jskeet** [comment]
I'm not aware of one at the moment, no.

It's possible that libraries generated from protobuf API definitions could happen in the future, but it's unlikely that a handwritten library would end up in *this* repository. I think it's more likely that the Firebase team would write their own non-Unity library that keeps the same look and feel where possible. I would suggest requesting this directly from the Firebase team at https://firebase.google.com/support/troubleshooter/report/features

I'll leave this open right now, but I suspect it will be best to close it as I'm not expecting this to happen any time soon. I'll make some inquiries internally as well though.

**Comment by jskeet** [comment]
I've heard back from the team, and for *admin* usage, there's the Admin SDK here: https://github.com/firebase/firebase-admin-dotnet (NuGet package [FirebaseAdmin](https://www.nuget.org/packages/FirebaseAdmin/).

For non-admin uses, there isn't a .NET package at the moment other than Unity, and there aren't plans for one right now. Sorry not to have better news for you, but the Firebase team are aware of the request so can include it in their deliberations later.

**Comment by tranb3r** [comment]
A few years later, has there been any update?

**Comment by jskeet** [comment]
@tranb3r: Not from the team managing this repo, no. There are various NuGet packages starting with "Google.Apis.Firebase", which are purely autogenerated from Discovery documents, but we don't provide a Firebase SDK as such. The Firestore library (Google.Cloud.Firestore) can be used for Firestore databases, of course.
