### ISSUE TITLE
[Diagnostics]: The trace rate limiter cannot be set to trace nothing or everything.

### ISSUE THREAD

**Issue by amanda-tarafa** [googleapis/google-cloud-dotnet#5213]
The trace rate limiter for sample tracing is set through QPS (queries per second to trace). Supposedly, for configuring Diagnostics tracing so that no sample tracing is performed (only traces forced through header are done), a small enough possitive double value should be provided for QPS. But even if the smallest possible value is set for QPS, the first call is always traced, and theoretically, if the application runs for really long periods of time, some other subsequent request will be traced as well.

1. This could be fixed by never tracing the first request, but that's semantically breaking.

The real cause of this issue is that really small positive double values, zero and really big positive double values are not allowed, because of the way the rate limiter is implemented, these values end up overflowing a TimeSpan value. So we never really can configure the rate limiter to trace nothing or trace everything in absolute terms (in practical terms we are close).

2. For fixing, allow these extreme values and interpret the TimeSpan overflows as:

 - Never trace when the overflow is in excess, as in, so much time needs to pass between traces that it actually means no tracing.
 - Always trace when the overflow is in defect, as in, so little time needs to pass between traces that it actually means always trace.

This approach has the advantage that is non-breaking.

3. An alternative approach can be considered where the rate limiter implementation does not rely (at least so heavily) on TimeSpan, but that would be at least semantically breaking and will requiere more time for redesign and implement.

@jskeet Thoughts welcome. I'm all for going with the second fix.

**Comment by jskeet** [comment]
Can we special-case 0.0 and `double.MaxValue`, detecting them and handling them slightly differently to the "regular QPS" case? (I haven't looked at the code recently.)

**Comment by amanda-tarafa** [comment]
Yes, we can do that as well. But then things like double.Epsilon won't work. I'll send a PR with both versions in.

**Comment by amanda-tarafa** [comment]
This has now been released in https://www.nuget.org/packages/Google.Cloud.Diagnostics.AspNetCore/4.1.0-beta01.
