### ISSUE TITLE
Pubsub retry config not generated

### ISSUE THREAD

**Issue by chrisdunelm** [googleapis/google-cloud-dotnet#5225]
This script: https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.PubSub.V1/midmicrogeneration.sh
Needs to also edit the retry config correctly to make the names match. At the moment it looks like there's a `v1` -> `v2` change, which is probably not correct.
Retry config file here: https://github.com/googleapis/googleapis/blob/4d52dfb72078000b13de923c1dadec19f3a64ad1/google/pubsub/v1/pubsub_grpc_service_config.json

**Comment by hongalex** [comment]
It seems like this might not have been correctly generated. [StreamingPull](https://github.com/googleapis/googleapis/blob/4d52dfb72078000b13de923c1dadec19f3a64ad1/google/pubsub/v1/pubsub_grpc_service_config.json#L102-L119) should have 5 retryable error codes, but it seems like [none were added](https://github.com/jskeet/google-cloud-dotnet/blob/1c4669e050a07c2ca25d3337aa0156fef8c13bc6/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberServiceApiClient.g.cs#L202). Am I missing something perhaps?

**Comment by jskeet** [comment]
I'll look into this tomorrow.

**Comment by jskeet** [comment]
Actually, this may be deliberate, because retry for streaming RPCs just doesn't work - at least not for gRPC, and I *think* not for any language. We've discussed prohibiting it from the service config in the past, but I suspect we just deliberately ignore it in the C# generator. Will check tomorrow.

**Comment by chrisdunelm** [comment]
Jon is correct, streaming RPCs cannot have retry automatically applied, so any config is ignored.
