### ISSUE TITLE
Google.Cloud.Firestore not writing data to firestore emulator

### ISSUE THREAD

**Issue by quirobin** [googleapis/google-cloud-dotnet#5234]
I'm trying to write data from my local environment (running on iis on my machine) to my Google Firestore emulator. The code runs, doesn't throw an error BUT the data doesn't seem to be being written to the Firestore emulator.

Using firebase CLI tools v8.6.0 Google.Cloud.Firestore v2.1.0

```
string project = ConfigurationManager.AppSettings["firestore_projectid"];
    Environment.SetEnvironmentVariable("FIRESTORE_EMULATOR_HOST", "localhost:8080");
    FirestoreDb db = new FirestoreDbBuilder
        {
            ProjectId = project,
            EmulatorDetection = Google.Api.Gax.EmulatorDetection.EmulatorOnly   
        }.Build();

    var dto = await GetLiveStreamDto();

    DocumentReference docRef = db
        .Collection("Events")
        .Document("123456789")
         
    await docRef.SetAsync(dto, SetOptions.MergeAll);
```

https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/#connecting-to-the-emulator

**Comment by jskeet** [comment]
Can you clarify what you mean by "the data doesn't seem to be being written to the Firestore emulator"? How are you testing that? (If you could provide a complete example so that I could try to reproduce it as closely to what you're doing, that would be ideal.)

**Comment by jskeet** [comment]
Closing this now as we haven't had any more information. @quirobin if you provide more information, ideally a complete example, I'll be happy to reopen it.
