### ISSUE TITLE
Customize the height of the chat widget of Dialogflow messenger integration

### ISSUE THREAD

**Issue by jawwadturabi** [googleapis/google-cloud-dotnet#5244]
I am using Dialogflow's new website integration "Dialogflow messenger". Everything is working fine but when I click on the chat widget the height of the chat window is exceeding the size of the browser window as you can see in the attached snapshot.
![Screenshot from 2020-08-13 16-15-12](https://user-images.githubusercontent.com/47825998/90147328-83da1b80-dd9b-11ea-8545-9a8bf4ece232.png)

I have read out the official [documentation](https://cloud.google.com/dialogflow/docs/integrations/dialogflow-messenger#css-customize) CSS customization of this chat widget but I couldn't found any useful method to handle this issue. I have tried with different browsers like firefox, chrome, safari, etc. But the issue remains the same. The documentation provides only the following CSS variables which don't help out too much.

![image](https://user-images.githubusercontent.com/47825998/90147400-98b6af00-dd9b-11ea-80fb-fba8674c59a1.png)

I will encourage if anyone can provide a solution to this. Thank you

**Comment by jskeet** [comment]
While we'd love to be able to help out, I'm afraid this is the repository for the .NET client libraries. The maintainers of this repository don't have in-depth knowledge of all the (many) products - and this definitely doesn't look like a question specifically about the .NET client library for Dialogflow.

Please see https://cloud.google.com/dialogflow/docs/support/getting-support for Dialogflow-specific support options.
