### ISSUE TITLE
Any Package for Cloud DNS?

### ISSUE THREAD

**Issue by mitulpanch** [googleapis/google-cloud-dotnet#5248]
Google.Apis.Dns.v1 this is avalilable as api

still any package for Cloud DNS with sample?

**Comment by jskeet** [comment]
No, I don't believe there's a gRPC interface for Cloud DNS yet - a quick search of https://github.com/googleapis/googleapis doesn't find anything. (That's where packages in this repo are generated from.)

I would suggest continuing to use Google.Api.Dns.v1 for now. As for samples, https://github.com/GoogleCloudPlatform/dotnet-docs-samples is the repo to check for those - and again, I don't believe we have any at the moment. Those are usually provided by the product teams, so you might want to request samples via one of the [Cloud DNS support paths](https://cloud.google.com/dns/docs/getting-support).

I'll close this issue now as there isn't anything to do in this repo at the moment - but I wouldn't be surprised if the Cloud DNS team were to publish a gRPC API in the future, at which point we'd generate a library for it.
