### ISSUE TITLE
Support the PubSub emulator in the same way as other APIs

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#5261]
Currently we have a few APIs (Datastore, Firestore and Spanner) that use EmulatorDetection to make it easy to connect to the emulator.

We should apply the same pattern to PubSub (which is *slightly* complex due to having a wrapper layer) and then update the documentation around this.

**Comment by umitkavala** [comment]
Hi @jskeet I'd like to take this task.

**Comment by jskeet** [comment]
@umitkavala: I'm happy for you to give it a try, but I should say that I've looked at this a couple of times hoping it would be simple, and it's really not... and that's despite me knowing the library infrastructure inside and out.

What I'm trying to say is that if you try but find it all too tricky/confusing, please don't feel any sense of inadequacy :) Of course, if you _can_ sort it out, that would be brilliant :)

**Comment by umitkavala** [comment]
Its better to warm up before. Let me choose less difficult task :) Do you have any recommendations?

**Comment by jskeet** [comment]
Not particularly, I'm afraid - where there are easy things to do, we tend to pick them off ourselves when we have little bits of time.

Having said that, https://github.com/googleapis/google-cloud-dotnet/issues/5578 would probably be a good starting place. I'd expect it to involve:

- Updating dependencies
- Creating an integration test
- Productionizing the "currently somewhat prototype" code - and particularly thinking about performance
- Writing more unit tests
- Writing documentation

I'm in no way suggesting that one person has to do all of that :) But it's relatively decoupled from the rest of the library work, which makes it simpler to start on. (It does mean you wouldn't learn as much about how the API libraries work though, so if that's one of your goals it's less appealing.) Let me know what you think :)

(I may now have another look at the PubSub one today, because it's irking me...)

**Comment by umitkavala** [comment]
I think its a good start. I'm happy to work with you (that a big bonus for me :) )
