### ISSUE TITLE
Question:  Passing along the client IP address in api requests

### ISSUE THREAD

**Issue by tiny-dancer** [googleapis/google-cloud-dotnet#5278]
Our organization has an app/api layer on top of data catalog and big query.  We're utilizing VPC Service Controls to restrict access within GCP to big query.  Instead of whitelisting our entire app/api, we’d like to pass along the client ip address through the dotnet sdk to the google api, so that the VPC Service Controls allow the _client_ access, not the _app/api_.  Is this possible?

Thanks!

**Comment by jskeet** [comment]
I'll look at this in more detail tomorrow (in the UK morning)

**Comment by jskeet** [comment]
Okay, now I'm working again... could you clarify what you mean by "pass along the client IP address"? I don't have any direct experience with VPC myself, so I'm not sure what that would involve. Are you effectively trying to add extra headers or similar? If so, we should be able to help you do that. (We probably won't include it as an "out of the box" option unless it looks like it would be fairly widely used though.) Additionally, which precise .NET libraries are you using? The steps would be slightly different for the main BigQuery library (which uses the REST API) vs other gRPC-based libraries.

**Comment by tiny-dancer** [comment]
> Are you effectively trying to add extra headers or similar?

That's an excellent question, this would essentially be the same as "spoofing" the ip to bypass VPC Service Controls so it may be interesting.  We attempted to utilize a few common ip header values to no luck, we are not sure internally how VPC Service Controls determines client ip.

> could you clarify what you mean by "pass along the client IP address"? 

Browser/Device (ipN) --> Custom Hosted API (ip2) --> VPC Service Controls (allow only ip1) --> Google Data Catalog & Big Query API

Ideally in this situation if i am at ip1 i am able to view data catalog and big query data through our custom hosted api or the cloud console.  The alternative option is to whitelist ip2 in the VPC Service Controls for the custom hosted api however then we need to implement another IP whitelist in front of the custom hosted api.  Acceptable, but not ideal.

**Comment by jskeet** [comment]
Okay, this sounds like something we'll need to talk to the VPC team about. I *suspect* that allow-listing ip2 really is the way forward - otherwise what's to stop something else at any other IP address from spoofing it in exactly the same way? It would make the IP address allow-list somewhat pointless if you could just spoof a different one. I'll see if I can find someone in the VPC team to talk to about this.

**Comment by mbpolan** [comment]
@jskeet Just an additional feedback note for discussions with relevant teams. Not necessarily specific to the .NET SDKs, but it seems the G Suite APIs have different responses for the situation where VPC rejects the request. This initially made troubleshooting what was going wrong more difficult, especially from the perspective of a developer who's just using the SDKs alone.

For example, the following BigQuery REST API returns an HTTP 403 and gives an informative message:

**Request**
GET https://bigquery.googleapis.com/bigquery/v2/projects/research-00/datasets

**Response**
```
{
  "error": {
    "code": 403,
    "message": "VPC Service Controls: Request is prohibited by organization's policy. vpcServiceControlsUniqueIdentifier: xxxxx.",
    "errors": [
      {
        "message": "VPC Service Controls: Request is prohibited by organization's policy. vpcServiceControlsUniqueIdentifier: xxxxx.",
        "domain": "global",
        "reason": "policyViolation"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
```

Whereas this Data Catalog endpoint simply returns an HTTP 200 and an empty JSON object.

**Request** (any valid request body)
POST https://datacatalog.googleapis.com/v1/catalog:search

**Response**
```
{}
```

At first, the latter mislead us into thinking something with our code was incorrect (query itself, client credential config, etc.) when in reality it was a VPC policy behind the scenes. It would be beneficial to at least standardize on some common response format so the SDKs can be coded to react accordingly.

**Comment by fieryorc** [comment]
So in essence you are asking for VPCSC trust boundary extended to your application, which is currently not supported. IP headers can't be set by callers. 

If you can describe your use case better, we can suggest an alternative.

**Comment by tiny-dancer** [comment]
Thank you, I believe the conversation has led to a feature request for VPCSC to have the ability to incorporate X-Forwarded-For in its evaluation.

The use case is pretty straightforward as we were looking to avoid duplicating firewall restrictions between app and VPCSC. We also enjoyed the thought of VPCSC being the source of truth data layer boundary, where we could allow the app to be more permissive for parts of its experience but the data availability in the app or elsewhere is always protected by the VPCSC configuration. 

This would be a want not a need scenario as all doable in the app layer with proper automation minimizing configuration and drift concerns.

**Comment by jskeet** [comment]
Thanks. It sounds like we can close this issue now, as there's no client library work required, at least for now.

**Comment by tiny-dancer** [comment]
Appreciate the quick turn around and responses.
