### ISSUE TITLE
prod:cloud-sharp/google-cloud-dotnet/gcp_windows/autorelease failing since August 25th

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/google-cloud-dotnet#5283]
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Acloud-sharp%2Fgoogle-cloud-dotnet%2Fgcp_windows%2Fautorelease

CC @bcoe

**Comment by jskeet** [comment]
The most recent failure (Sept 1st) was a timeout - the ones before are for a known issue in the autorelease reporting script which I believe has now been fixed. We should check when we next do a release, but I don't *believe* there's anything .NET-specific here.

**Comment by jskeet** [comment]
Still failing. The log halts for 5 minutes before getting to actual code, then fails with a timeout. Will investigate further this afternoon.

**Comment by amanda-tarafa** [comment]
Closing this one as we have an internal bug. @SurferJeffAtGoogle and @bcoe I'll cc you on the internal issue.
