### ISSUE TITLE
How do I save a custom data model without using [FirestoreData] and [FirestoreProperty] annotations

### ISSUE THREAD

**Issue by danmayor** [googleapis/google-cloud-dotnet#5312]
**Context**
I am looking to create a project that exposes an API and provides my users with a .NET Client library.  My thought is that I would like to create a shared library of data models that are used in both the API service and the Client Library. I do not want to ship or require the Google.Cloud.Firestore library in the Client.

**Question**
Is there some other way to configure the data models at **run time** to map such that I don't have to store them as dictionaries but also don't have to use the annotations?

Links to documentation would be great, happy to read and learn just can't seem to find anything myself.

**Comment by jskeet** [comment]
I can give more details on Monday when I'm back at work if you need more info, but what you want is a *custom converter* which you include in the converter registry for the `FirestoreDb`:
https://googleapis.dev/dotnet/Google.Cloud.Firestore/latest/datamodel.html#converter-registries

**Comment by jskeet** [comment]
@danmayor: Okay, now back and working - I'm not sure whether the documentation I pointed you at is sufficient. I would *expect* you to be able to do that; if you've got a lot of complex models, writing converters by hand could prove time-consuming, certainly. At the moment I'd prefer not to introduce any further complexity in the serialization code, so if you could see whether that will do what you want already, that would be great, thanks.

**Comment by danmayor** [comment]
@jskeet thanks, I think that will get me where I need to be.  I may need to do some reflection or expression over the models in the custom converter. Some early performance tests I did look like it'll be a perfectly acceptable solution.  Although, if there is a way to write directly to the serialization stream that could be even a bit more performant.  (Either way, 100k models of 26 random string fields was looking like 200ms or less, seems acceptable if reflecting to dictionary in the custom converter is the answer)

**Comment by jskeet** [comment]
If I remember correctly, if you create the protobuf values directly, they'll just be taken as they are rather than going via the dictionary - but the code for that would look significantly uglier. I'd stick to dictionaries or anonymous types as a first pass, at least.

Will close this for now, as it sounds like you're okay - but do add another comment if you run into problems, and we can reopen.
