### ISSUE TITLE
BigQuery: audit use of dense JSON encoding

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-dotnet#5330]
# Request
Review this library to ensure dense encoding (e.g. `prettyPrint=false`) is specified when possible when communicating with the BigQuery API methods.

# Additional Context
Pretty printed JSON responses from server can have significant response size inflation for complex objects.  BigQuery data APIs tend to exacerbate this.  Library can improve performance by using dense encoding, particular for underlying methods like jobs.getQueryResults and tabledata.list that may supply large, complex JSON responses.

Info about `prettyPrint` system API parameter:
https://cloud.google.com/apis/docs/system-parameters

# Internal (for Googlers)
See issue 168725137

**Comment by jskeet** [comment]
Will look at this next week.

**Comment by jskeet** [comment]
This is now released in version 2.1.0.
