### ISSUE TITLE
Failed to install Google.Cloud.Diagnostics.AspNetCore3

### ISSUE THREAD

**Issue by EatonZ** [googleapis/google-cloud-dotnet#5429]
My project runs on the latest .NET Core (3.1) so I wanted to swap the package to the newly released Google.Cloud.Diagnostics.AspNetCore3. I am getting an error when installing it on my web DLL:
`NU1202: Package Google.Cloud.Diagnostics.AspNetCore3 4.0.0-beta01 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package Google.Cloud.Diagnostics.AspNetCore3 4.0.0-beta01 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)`

My DLL is using the latest version, so I don't understand the issue.

![nothinghigher](https://user-images.githubusercontent.com/3020941/95808166-da9b9d00-0cd9-11eb-9ede-c2e6d1076690.png)

**Comment by amanda-tarafa** [comment]
Libraries to be used from ASP.NET Core 3 (and upwards) web applications, [under certain conditions](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#migrate-libraries-via-multi-targeting), need to target netcoreapp3.* and not netstandard2.1. The Google.Cloud.Diagnostics.AspNetCore3 library meets some of those conditions so it targets netcoreapp3.1 (the long-term support release of ASP.NET Core 3*).
I suppose your "web DLL" is a library that you use from your web application? In that case, it can target netcoreapp3.1 (your web app should already be targetting netcoreapp3*). If you had plans to use your "web DLL" in other application types,  it can target both netcoreapp3.1 and netstandard2.0 and use #ifdefs to provide alternative implementations for features that have dependencies on ASP.NET Core 3 specific APIs as recomended on the link above.

**Comment by EatonZ** [comment]
@amanda-tarafa I did not know you could change the class library target framework outside of values listed in the dropdown. Why wouldn't all possible values be listed? Regardless, went into the project file with a text editor and changed it. All good now.👍
