### ISSUE TITLE
Add more APIs

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#5452]
The following APIs have been identified for generation:

- [x] Access Approval API - needs C# namespace option
- [x] App Engine Admin API - if this is google/appengine/v1, needs C# namespace option (in progress)
- [x] Cloud Bigtable Admin API (been generated for ages)
- [x] Binary Authorization API (in google/cloud/binaryauthorization; needs C# namespace option)
- [x] Cloud Build API (in google/devtools/cloudbuild - needs C# namespace option, which we'd need to consider carefully)
- [x] Cloud IoT API (in google/cloud/iot)
- [ ] ~~Cloud Resource Manager API (in google/cloud/resourcemanager; has C# namespace option - but declares the common Folder resource, so we need to work out how to handle that; probably going to want to wait for v3)~~
- [x] IAM Service Account Credentials API (in google/iam/credentials; probably want C# namespace option)
- [ ] ~~Pub/Sub Lite API (don't think we want to generate this)~~
- [x] Web Security Scanner API
- [x] Area120 Tables API (released as alpha01 on 2020-09-22)
- [x] Data Labeling API (has C# namespace option; just needs comment on the service)
- [x] Media Translation API (in google/cloud/mediatranslation, has C# namespace option)
- [x] Policy Troubleshooter API (in beta since 2020-08-26; could go GA)
- [x] Recommendations AI
- [x] Service Control API
- [x] Service Management API (assuming this is google/api/servicemanagement/v1; has C# namespace option of Google.Cloud.ServiceManagement.V1)
- [x] Workflow Executions API (generated as of 2020-10-14)

We'll add a date and the kind of action as we go.

**Comment by amanda-tarafa** [comment]
Closed by accidentally clicking on the wrong place.

**Comment by jskeet** [comment]
Closing as we've now released everything we think we want to.

**Comment by mathieu-benoit** [comment]
Hi @jskeet, just curious, is there any plan to support `PubSub Lite` in there at some point? Thanks.

**Comment by jskeet** [comment]
@mathieu-benoit: We have no plans to release a C# PubSub Lite client at the moment, no.

**Comment by mathieu-benoit** [comment]
Thanks for the info @jskeet. 
I see there is this "old" PubSub Lite client library https://developers.google.com/api-client-library/dotnet/apis/pubsublite/v1 but I'm not seeing a way to `publish messages to a topic` nor `pull messages from a subscription`, is my understanding correct?

**Comment by jskeet** [comment]
@mathieu-benoit: That's just an autogenerated library from the API description. The PubSub Lite API really needs a hand-written wrapper around it in order to be usable; I would suggest not trying to use the generated library directly.
