### ISSUE TITLE
Create a PublisherServiceApiClient and SubscriberServiceApiClient using credentials passed in parameters

### ISSUE THREAD

**Issue by LIFEfreedom** [googleapis/google-cloud-dotnet#5507]
**Is your feature request related to a problem? Please describe.**
I want to create a PublisherServiceApiClient, but I don't want to store the authorization data in a file and use the `GOOGLE_APPLICATION_CREDENTIALS `variable. And without this variable, I get the error `"The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."`

 **Describe the solution you'd like**
It would be really cool if you could pass `GoogleCredential `as an argument to `PublisherServiceApiClient.Create()` and `PublisherServiceApiClient.CreateAsync()`.

 **Additional context**
The data for authorizing the **FireBase** service is stored in a single configuration file for my ASP.NET Core application and I would not like to produce various configuration files

**Comment by jskeet** [comment]
See https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis

For example:

```csharp
var publisher = new PublisherServiceApiClient { TokenAccessMethod = credential.GetAccessTokenForRequestAsync }.Build();
```

**Comment by jskeet** [comment]
(If you're creating the `GoogleCredential` from a string, you could use `JsonCredentials` property of the builder instead, btw.)

**Comment by LIFEfreedom** [comment]
Thanks. It works. Itself somehow did not think of it before
