### ISSUE TITLE
How to configuring a Proxy?

### ISSUE THREAD

**Issue by yang-xiaodong** [googleapis/google-cloud-dotnet#5530]
Hello there,

We are using GCP Pub/Sub and encountered the following error:
```
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="failed to connect to all addresses")
```

It looks like a problem with my network, since I am in China and we are using a proxy to access the GCP services.

In the google-cloud-java repository I found how to [configuring a proxy](https://github.com/googleapis/google-cloud-java#configuring-a-proxy) but it doesn’t seems to work for dotnet sdk. I didn't find the documentation on how to configuring a Proxy in dotnet sdk, so I'm looking for help.

Thanks.

**Comment by jskeet** [comment]
The Grpc.Core implementation is based on gRPC Core, so the [environment variables listed for gRPC Core](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md) are the relevant ones. So I'd *expect* this to be the relevant bit:

> grpc_proxy, https_proxy, http_proxy The URI of the proxy to use for HTTP CONNECT support. These variables are checked in order, and the first one that has a value is used.

Can you try setting `grpc_proxy` and giving it another try?

**Comment by yang-xiaodong** [comment]
> Can you try setting `grpc_proxy` and giving it another try?

It works, thanks very much
