### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [googleapis/google-cloud-dotnet#5569]
#### Environment details
N/A

#### Steps to reproduce
Click the links

"**Google.Cloud.Dataproc.V1**"
Status code [404:NotFound] - Link: https://googleapis.dev/dotnet/Google.Cloud.Dataproc.V1/3.0.0-beta00

"**Google.Cloud.DevTools.ContainerAnalysis.V1**"
Status code [404:NotFound] - Link: https://googleapis.dev/dotnet/Google.Cloud.DevTools.ContainerAnalysis.V1/2.1.0

"**Grafeas.V1**"
Status code [404:NotFound] - Link: https://googleapis.dev/dotnet/Grafeas.V1/2.1.0

--

Theses bad links were found by a tool I very recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback.

**Comment by jskeet** [comment]
The first link shouldn't be in there - I need to work out why it *is* there at all. (There shouldn't be any beta00 links.)

The other two links should be fine fairly soon - those packages were published less than an hour ago, and it takes a little while for the documentation publication process to catch up. (Another package that was published about 2 hours ago has valid documentation now.)

**Comment by jskeet** [comment]
Okay, the second and third links are now sorted.

We do actually have Dataproc set at 3.0.0-beta00 to avoid a breaking change - I'll release 3.0.0-beta01 (or maybe just 3.0.0) next week which will fix that.

Closing this issue now, as it's somewhat separate from the Dataproc issue really.
