### ISSUE TITLE
Increased latency after adding Google.Cloud.Diagnostics.AspNetCore3

### ISSUE THREAD

**Issue by Mistic92** [googleapis/google-cloud-dotnet#5632]
#### Environment details

  - OS: mcr.microsoft.com/dotnet/aspnet:3.1-buster-slim
  - .NET version: 3
  - Package name and version: Google.Cloud.Diagnostics.AspNetCore3

#### Steps to reproduce

We are running multiple services on Cloud Run. We were using opentelemetry but as it's on very early stage we had a lot of issue as traces were not connected and log's were not added. After Google have added support for dotnet core 3 we have changed to it. After week of monitoring we see that latency went up. 

What can we do/check to fix this issue?  

![image](https://user-images.githubusercontent.com/2607098/99941129-c7b2c880-2d6d-11eb-8d99-8dad989a7072.png)

![image](https://user-images.githubusercontent.com/2607098/99941216-edd86880-2d6d-11eb-973f-0c3f21d089ba.png)

**Comment by jskeet** [comment]
Assigning to Amanda as she owns the diagnostics parts.

Could you give more details about how you're configuring this, and what your application does? (For example, are you doing a lot of logging and a lot of tracing in every request?)

Is the logging and tracing _working_ for you, but just with awful latency, or is it also failing?

**Comment by jskeet** [comment]
(Labeled as a bug for the moment, as "question" sounds far too minor. But hopefully it's not a bug in the libraries and merely something we can help with configuring better, or something like that.)

**Comment by Mistic92** [comment]
Hi, our app is chat service. If you need I can open GCP support ticket to share more details as we have role based support. 
It's working fine but latency went up a lot as visible on previous screenshots. 

- I found that we have sample rate set to 1, might it be the reason for increased latency? On opentelemetry we probably had the same value set. What's the recommendation for this value? We'll also move this value to env.

- logging: I think we are not doing a lot of logging, currently we have set Information level and it's like 8-11 lines per request, depends on service

We have this in one file which is used in all services in project
```ASP.NET
using Google.Cloud.Diagnostics.AspNetCore3;
using Google.Cloud.Diagnostics.Common;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace YOSH.Messenger.Localization
{
    /// <summary>
    /// This should be move to CrossCuttingConcerns but for now Google.Cloud.Diagnostics.AspNetCore3 doesn't support .net standard
    /// </summary>
    public static class DiagnosticsInstaller
    {
        public static IServiceCollection AddCustomLogging(this IServiceCollection services, IConfiguration configuration, string serviceName, string serviceVersion)
        {
            var gcpProjectId = configuration.GetValue<string>(ConfigurationFields.GOOGLE_CLOUD_PROJECT_ID);

            var bufferOptions = BufferOptions.NoBuffer();
            var retryOptions = RetryOptions.NoRetry(ExceptionHandling.Propagate);

            #region Exceptions

            services.AddGoogleExceptionLogging(options =>
            {
                // Replace ProjectId with your Google Cloud Project ID.
                options.ProjectId = gcpProjectId;
                // Replace Service with a name or identifier for the service.
                options.ServiceName = serviceName;
                // Replace Version with a version for the service.
                options.Version = serviceVersion;

                options.Options = ErrorReportingOptions.Create(gcpProjectId, bufferOptions, retryOptions);
            });

            #endregion

            #region Logging

            services.AddLogging(config =>
            {
                // clear out default configuration
                config.ClearProviders();

                var loggerOptions = LoggerOptions.Create(logName: serviceName, bufferOptions: bufferOptions, retryOptions: retryOptions);

                // Replace projectId with your Google Cloud Project ID.
                services.AddSingleton<ILoggerProvider>(sp => GoogleLoggerProvider.Create(sp, gcpProjectId, loggerOptions));
            });

            #endregion

            return services;
        }

        public static IServiceCollection AddCustomTracing(this IServiceCollection services, IConfiguration configuration)
        {
            var gcpProjectId = configuration.GetValue<string>(ConfigurationFields.GOOGLE_CLOUD_PROJECT_ID);

            var bufferOptions = BufferOptions.NoBuffer();
            var retryOptions = RetryOptions.NoRetry(ExceptionHandling.Propagate);

            #region Tracing

            // The line below is needed for trace ids to be added to logs.
            services.AddHttpContextAccessor();

            // Replace ProjectId with your Google Cloud Project ID.
            services.AddGoogleTrace(options =>
            {
                options.ProjectId = gcpProjectId;
                options.Options = TraceOptions.Create(1, bufferOptions, retryOptions);
            });

            #endregion

            return services;
        }

        public static void UseCustomLogging(this IApplicationBuilder app, IConfiguration configuration)
        {
            //, ILoggerFactory loggerFactory
            //var gcpProjectId = configuration.GetValue<string>(ConfigurationFields.GOOGLE_CLOUD_PROJECT_ID);

            #region Exceptions

            app.UseGoogleExceptionLogging();

            #endregion

            #region Logging

            //loggerFactory.AddGoogle(app.ApplicationServices, gcpProjectId);

            #endregion
        }

        public static void UseCustomTracing(this IApplicationBuilder app)
        {
            #region Tracing

            app.UseGoogleTrace();

            #endregion
        }
    }

    public class ConfigurationFields
    {
        public const string GOOGLE_CLOUD_PROJECT_ID = "GOOGLE_CLOUD_PROJECT";
    }
}
```

**Comment by jskeet** [comment]
Thanks for the extra information. Hopefully that'll be enough to reproduce it without going via a GCP support ticket. It's been a while since I looked at trace, so I can't say for sure about the sample rate values. We'll get back to you with the results of our investigation.

**Comment by amanda-tarafa** [comment]
Thanks for the info. A couple of quick notes although I'll take a better look after.

You have no buffer configured for any of the Diagnostics components so there's an overhead added to each request, that, depending on how you had configured Opentelemtry, might be at least part of the explanation. What was your buffering strategy with Opentelemetry? Since you are running on Cloud Run, which limits CPU on downtime, you cannot use the timed buffer (see #5275 for a lengthy discussion around this), but you could use the sized buffer which would only impact some requests, and those, in general, wouldn't be impacted more than all requests are being impacted now if you fine tune the buffer size.

The sample rate for tracing set at 1 means there's, at max, one request traced per second, sample rate is qps (queries per second). There's not a blanket recommended value since it all depends on how much of your trafic you want to trace, the environment your application runs in, the amount of requests your application gets, etc. 

About the latency graph, although the overall latency has indeed increased, there are also these peeks at what look like regular intervals (24 hours) that weren't there before. I can't see how these would be related to Diagnostics. Diagnostics only periodic actions happen when the timed buffer is used, and your are not using it, and also, although it could be configured to flush every 24 hours, it'll probably be configured to flush sooner. Can you think of something else going on that would account for these peeks? It would be nice if we could get that out of the picture.

I'll set up some testing apps and get back here when I know more.

**Comment by amanda-tarafa** [comment]
I've got two similar apps running on Cloud Run, the only difference between them is that one configures and uses Diagnostics and the other one doesn't. I've written a small app that makes requests to these apps and I'll leave that running through the night and share results tomorrow.

**Comment by Mistic92** [comment]
Hi, we just pushed changes suggested by you to production and will monitor it. EOD I'll check traces and latencies but I think it looks good!

**Comment by amanda-tarafa** [comment]
I'm actually seeing some unexpected overhead on my own tests. I'm trying to pintpoint where that might be and will update here as soon as I can.

**Comment by amanda-tarafa** [comment]
OK, after sevaral tests that I've had running during the day, I'm pretty confident in saying that my initial suggestion of using `SizedBuffer` should get rid of the alarminglingly increased latency. Highlights here:

- I've deployed to a default Cloud Run service, using `mcr.microsoft.com/dotnet/aspnet:3.1-buster-slim` a web app that doesn't even have a dependency on the Google.Cloud.Diagnostics.AspNetCore3 app. It actually is just the code from a VisualStudio ASP.NET Core Web Application template. This is just for a baseline.

```
[HttpGet]
public IEnumerable<WeatherForecast> Get()
{
    var rng = new Random();
    return Enumerable.Range(1, 5).Select(index => new WeatherForecast
    {
        Date = DateTime.Now.AddDays(index),
        TemperatureC = rng.Next(-20, 55),
        Summary = Summaries[rng.Next(Summaries.Length)]
    })
    .ToArray();
}
```
  Baseline latency always looks as follows (a peak at startup, as expected and then very flat consistently under 100ms).
  
![image](https://user-images.githubusercontent.com/14878252/100122579-712eb280-2e71-11eb-8a18-9cb8308008ce.png)


- I've deployed, also to a default Cloud Run service with `mcr.microsoft.com/dotnet/aspnet:3.1-buster-slim` several versions of another template based app that uses Google.Cloud.Diagnostics.AspNetCore3 library to log and trace as follows (and it's also configured to do exception logging). The versions differ in how the Diagnostics library is configured, but the code in the controller is the same:

```
[HttpGet]
public IEnumerable<WeatherForecast> Get()
{
	_logger.LogInformation("Logging before span");
	WeatherForecast[] result;
	using (_tracer.StartSpan("get-span"))
	{
		var rng = new Random();

		_logger.LogInformation("Logging before calculations");
		result = Enumerable.Range(1, 5).Select(index => new WeatherForecast
		{
			Date = DateTime.Now.AddDays(index),
			TemperatureC = rng.Next(-20, 55),
			Summary = Summaries[rng.Next(Summaries.Length)]
		})
		.ToArray();
		_logger.LogInformation("Logging after calculations");
	}
	_logger.LogInformation("Logging after span");
	return result;
}
```
- I wrote a client app, that generates 10 to 20 requests per second to each of the apps so as to be able to compare.

- The first version of the Diagnostics web app I deployed was configured using the Startup code you provided. No buffering, no retrying and propagate exceptions. These gave pretty bad results, with peaks of over 30s.

![image](https://user-images.githubusercontent.com/14878252/100127920-827abd80-2e77-11eb-9cda-26fc6928afa0.png)

- I then tried any number of other versions, with differences, like ignoring exceptions, tracing more, not tracing, and not logging, all without buffers. Removing logging seemed to be the better of these, but still had a few peaks close to 500ms.

- With no buffers, logging is what generates the most gRPC calls, one each time you write a log. Tracing generates one gRPC call per sampled request and exception logging only generates one gRPC if there are exceptions. So, what is happening is that, whith how I'm logging, we get at least 4 (blocking) gRPC calls per request at least (so 40 to 80 a second). Some of those started timing out, which in turned, generated exception logging gRPCs, and when some of those started timing out then the instance crashed and a new one was spawn that needed to warmup, etc. Leading to those initial >30s peaks. Of course, the Cloud Run service can be configured to withstand some of this, but there's really no need if using buffers.

- With SizedBuffers (can't use timed buffers in Cloud Run), default size, this is what we get, peak at warmup, and then not flat, we are still making gRPCs as compared to the Baseline app, so some increase latency is expecting, but peaks are way under 200ms.

![image](https://user-images.githubusercontent.com/14878252/100129838-f3bb7000-2e79-11eb-851a-1da55bbde865.png)

You might want to try playing with different buffer sizes, you can have different buffer sizes for tracing, logging and exception logging as well. And also, at some point, if you are logging a lot so the buffer is quickly filled, you might want to tweak the Cloud Run service config to add more CPUs, etc. mainly if you get to a place where you can't avoid having several blocking gRPCs per request.

Let me know if this all helps.

**Comment by amanda-tarafa** [comment]
@Mistic92 This is in no way to rush you, just to make clear that if using SizedBuffer is not working for you in reducing latency as it dit for me, we can keep looking. Just let me know, because I would then need more info from you.

**Comment by Mistic92** [comment]
Hi, thank you for your support. Implementing buffers solved an issue and times went back to normal! 

![image](https://user-images.githubusercontent.com/2607098/100336490-896c1200-2fd6-11eb-86f7-0cb8541f5bfb.png)
