### ISSUE TITLE
[Diagnostics.AspNetCore3]: Documentation is missing snippet code.

### ISSUE THREAD

**Issue by amanda-tarafa** [googleapis/google-cloud-dotnet#5633]
See https://googleapis.dev/dotnet/Google.Cloud.Diagnostics.AspNetCore3/4.0.0-beta01/index.html
This is possibly because we are using the same Snippet project for both Diagnostics.AspNetCore* packages.

**Comment by jskeet** [comment]
I thought we'd separated out the snippets into a copy of the projects? The code that finds the snippets does expect it to be in a fixed location.

**Comment by jskeet** [comment]
I'll look into this today.

**Comment by jskeet** [comment]
Fixed in #5663 and #5665
