### ISSUE TITLE
[Google.Cloud.Logging.NLog] Nlog logging structure

### ISSUE THREAD

**Issue by orchowski** [googleapis/google-cloud-dotnet#5634]
Hi!
 **Problem description**
I have the following structure at stack driver
![image](https://user-images.githubusercontent.com/17548765/100084798-8264c880-2e4b-11eb-8574-97d357f6e47d.png)
using the following config:
![image](https://user-images.githubusercontent.com/17548765/100084979-c1931980-2e4b-11eb-9453-96dfbfeebf14.png)
and it's pretty understandable but I have to meet some standards where properties are in a flat structure.
Something like that is expected:
```
  "jsonPayload": {    
    "someProperty": "propertyValue",
    "message": "2020-11-24 11:50:32.192 | INFO | InfoTrace | traceId:  | Hawk Server-1.0.0: started ",
   ...
  },
```
where **someProperty** is near the message in structure. Isn't it better to require a full JSON layout from API clients to define **jsonPayload** exactly as they want?

 **Describe the solution you'd like**
I have two solutions actually:

1. **Accept JsonLayout as user desire:**
``` 
<layout xsi:type="JsonLayout" includeAllProperties="true">
                    <attribute name="message" layout="${defaultMessageFormat}" />
                    <attribute name="log_time" layout="${var:timeStampFormat}" />
                    <attribute name="team" layout="${var:team:default=dotnet}" />
                    <attribute name="service" layout="${var:serviceName:default=anonymous}" />
  </layout>
```
but it can be a breaking change, for that

2. By default all properties will be placed at properties object but with some prefixes like `.someProperty` properties are going to be at the root object

**Additional context**
It's something I really need now, but maybe there is a possibility to do that somehow?
I can implement that, but I think greenlight is needed before. Thanks in advance for your help and time.

**Comment by amanda-tarafa** [comment]
I'll take a look as soon as I can, but just to set expectations, it might not be this week.

**Comment by orchowski** [comment]
@amanda-tarafa ok! Thanks <3

**Comment by jskeet** [comment]
Actually, I believe we already have the necessary flexibility available.

You can specify the `JsonConverterTypeName` and `JsonConverterMethodName` options to make the specify your own converter. They should identify a method (either an instance method in a type that can be instantiated using `Activator.CreateInstance` or a static method) that accepts `object` and returns `Google.Protobuf.WellKnownTypes.Value` (which is effectively a JSON value).

That method will be used to provide the JSON payload. Please could you try that and get back to us if you have any problems?

**Comment by orchowski** [comment]
@jskeet I'll try to do that in this way

**Comment by orchowski** [comment]
@jskeet 
JsonConverter is used here to convert each parameter: https://github.com/googleapis/google-cloud-dotnet/blob/5c91cb16066fbf450379171dd574893011ea576d/apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget.cs#L522

And then these values are assing to propertiesStruct object. How it should work?
https://github.com/googleapis/google-cloud-dotnet/blob/5c91cb16066fbf450379171dd574893011ea576d/apis/Google.Cloud.Logging.NLog/Google.Cloud.Logging.NLog/GoogleStackdriverTarget.cs#L530

I'll try, but I'm not sure if it makes sense

**Comment by jskeet** [comment]
@orchowski: Ah, yes, you're right about this being just for the properties. We could *potentially* have a user-defined JsonLayout, following NLog's own JsonLayout type. That would be quite inefficient, as we'd need to ask the layout to format the log entry as a string, then we'd have to parse it into a protobuf `Struct` value (which is a JSON object) so that we could include it in the log entry that we send to Google Cloud Logging. But it should at least be feasible.

Are you happy to look into implementing this yourself? I doubt that we'll get to this as a feature request imminently.

**Comment by orchowski** [comment]
@jskeet okay then the situation is clear now. Thanks! 
I can take care of it then

**Comment by orchowski** [comment]
@jskeet I have some questions.

-  I have to discover what type of layout is provided in the configuration file and I need advice on which version Is the best.

It's problematic because information about that is nested inside TargetWithContextLayout and that's a private class from NLog.
 1. We can detect it through the value - after rendering we can validate it as a valid JSON object. But value like "hello there" is also valid so it can be a source of some problems.
 2. We can detect it through ToString() method - it's overloaded in the way where string is started from layout name. So, `if(Layout.ToString().StartsWith("JsonLayout") ....`
3. We can also add a flag like **IsCustomJsonLayout** or something. And It's probably the cleanest way to handle it but clumsy from an API perspective. If you are for this option please add some suggestions for flag name.

- I think this change should be documented and I'm a bit lost about where to place information about it.
- There is something to do before PR?

Thanks

**Comment by jskeet** [comment]
Hmm... do you mean that even without any code changes, if you specify a `JsonLayout` that will be activated by NLog, possibly in the "rendering" part of the code? (I'm afraid I don't use NLog myself normally, so this is all a bit new to me.)

If that is what you mean, option 3 is probably the cleanest in my view - it's the most predictable, even if it feels a little clunky. In terms of a name, I think I'll need to see what the code (and a test!) looks like first, as that will make me more aware of which NLog features it's using. But yes, we can definitely discuss options about that.

In terms of documentation, I totally agree that we'll want to document it, but you can probably leave that with me. Currently we have a bit of documentation in the README.md, but that should probably be moved into a docs/index.md file which I'm happy to do... and document this at the same time. At that point it would end up at https://googleapis.dev/dotnet/Google.Cloud.Logging.NLog/latest/index.html - or perhaps a separate "just configuration options" page linked from there and hosted in the same place.

**Comment by orchowski** [comment]
Okay then. I'll create PR tommorow with proposition.

And yes. NLog have dedicated renderers for layouts and all we need to do is to define layout at config file. For that it was a little strange for me that library impacts on layout format. But I'm not an expert of NLog too, I only try to manage with sprint task that anyone else don't want to do 😂

**Comment by jskeet** [comment]
This has now been released in Google.Cloud.Logging.NLog version 3.2.0
