### ISSUE TITLE
Custom Firestore Converters with F#

### ISSUE THREAD

**Issue by oantawilliam** [googleapis/google-cloud-dotnet#5636]
I was trying to implement in F# Custom Converters as described [here](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/datamodel.html#custom-converters), but I got into the problem of F#'s files ordering.

First, the type that will be converted requires an attribute, which needs to reference the ConverterClass - the actual class that does the conversion:
```
[<FirestoreDataAttribute(ConverterType=typeof<ConverterClass>)>]
type TypeClass = 
```

At the same time the ConverterClass needs to implement the following interface based on the Firestore implementation:

```
type IFirestoreConverter<'T> =
        abstract member ToFirestore: 'T -> Object
        abstract member FromFirestore: Object -> 'T
```

Also in the implementation of the interface, we need to use the TypeClass when we implement the two methods to replace the Generic T.

The main problem is that one of the two classes (ConverterClass or TypeClass) will be defined before the other, so then the latter cannot access the former, hence the code does not run.

Do you have any ideas on how to solve this?

Thank you!

**Comment by jskeet** [comment]
Does F# really not allow to types to refer to each other even via generics and attributes? That feels like a surprising limitation. I'm afraid I don't know enough F# to suggest a solution to that.

An alternative would be to register the type converter when constructing the `FirestoreDb` as described [here](https://googleapis.dev/dotnet/Google.Cloud.Firestore/latest/datamodel.html#converter-registries) - that way your class doesn't need to know about the converter.

**Comment by jskeet** [comment]
Any more information about this? Have you been able to try via registering the type converter?

**Comment by jskeet** [comment]
Closing as we can't do anything without more information - and hopefully registering the type converter works anyway. We can reopen if more information is provided.
