### ISSUE TITLE
Google Cloud Diagnostics Tracing - Service Name

### ISSUE THREAD

**Issue by Talento90** [googleapis/google-cloud-dotnet#5667]
I am using the following package in order to provide tracing metrics to stackdriver (http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNetCore/index.html).

I can see all traces in Stackdriver but I cannot filter by service name. Is there any way to set the service name when configuring the trace middleware?

```
services.AddGoogleTrace(options =>
{
    options.TraceFallbackPredicate = TraceDecisionPredicate.Create(IgnoreSwaggerAndHealth, true);
    options.ProjectId = settings.ProjectId;
    options.ServiceName = "MyService" // THIS does not exist
});
```

**Comment by jskeet** [comment]
(I'll look at this in detail tomorrow.)

**Comment by amanda-tarafa** [comment]
Google.Cloud.Diagnostics.AspNetCore and Google.Cloud.Diagnostics.AspNetCore3 rely on the [Google Trace API](https://cloud.google.com/trace/docs/reference/v2/rpc/google.devtools.cloudtrace.v1#google.devtools.cloudtrace.v1.PatchTracesRequest) which doesn't support specifying Service and Service Version at the trace or Span level.
And if you take a look at the [documentation](https://cloud.google.com/trace/docs/finding-traces#adding_a_filter) of the Trace Filter functionality in Google Cloud Console, Service and Version filtering are only enabled for apps running in App Engine (App Engine will create a top level span with the appropriate service information).

You can set labels on your spans though, and use those to filter.

**Comment by amanda-tarafa** [comment]
@Talento90 I'll be closing this issue because I believe there's nothing we can do on this repo. But please do leave a comment if you believe otherwise.
