### ISSUE TITLE
Emulator-based builders should use CopyCommonSettings

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#5671]
Currently with any of the APIs that support EmulatorDetection, if you configure the builder to use the emulator *and* you set a custom GrpcAdapter, the adapter property is ignored. Ditto for UserAgent, QuotaProject etc. Usually for an emulator most of these aren't important, but we should honour them anyway.

We'd want to copy the common settings, then set the emulator detection to None (and probably some other settings) to avoid infinite recursion.

**Comment by jskeet** [comment]
Actually it probably makes more sense for there to be a new GAX method specifically for this use case. There are specific properties that *shouldn't* be set here, around credentials etc. So the steps will be to create the new GAX method, then when we next release GAX (which isn't particularly urgent; I don't think it's worth doing a release just for this issue) we can update all the emulator-supporting libraries.

@amanda-tarafa does that sound reasonable to you?

**Comment by amanda-tarafa** [comment]
When you say a new method, you mean something like `BuildForEmulator`? I'd be fine with that as long as client code can keep calling `Build` only and we internally detect whether the emulator is set or not and call the new `BuildForEmulator`. Else client code has the duplicity of setting the emulation detection property and knowing when to call one or the other method. Or did I understood wrong?

For properties like `QuotaProject`, that are set through the credential (the `GoogleCredential`), it might be hard to set them for emulation given that, if I remember correctly, we use insecure (gRPC) `ChannelCredentials`. Admittedly we could create a `CallCredentials` from an interceptor that sets the `QuotaProject`.

**Comment by jskeet** [comment]
It would be something like `CopySettingsForEmulator` - definitely nothing new for *user* to call. This is just an internal tidy-up. We should do a proper audit of which properties make sense to copy and which don't when we create the method.

**Comment by amanda-tarafa** [comment]
Yep, totally onboard.

**Comment by jskeet** [comment]
This is now ready to be implemented next time we do a GAX release - which may well be for self-signed JWTs.
