### ISSUE TITLE
Firebase DateTime instances must be UTC

### ISSUE THREAD

**Issue by christophergunn** [googleapis/google-cloud-dotnet#5682]
Hello,

**Is your feature request related to a problem? Please describe.**
I am attempting to store an object containing a non-UTC DateTime in Firestore.

 **Describe the solution you'd like**
I would like non-UTC DateTime values to be able to be persisted.

 **Describe alternatives you've considered**
Writing a custom value converter seems over the top, but I have considered this.

 **Additional context**
The time local to the user is important for my use case. It also drives contractual events. The UTC time is not as important to us as the local time, so we generally store events against the users local time.

We are moving a large volume of data away from CosmosDB, which had no issues storing non-UTC DateTime objects.

Thanks,

Chris G

**Comment by jskeet** [comment]
Firestore simply doesn't have a type for representing this data. It has a timestamp type, but that's defined in terms of UTC. You might want to consider storing the data as a string instead.

**Comment by jskeet** [comment]
To expand a bit now I'm not on a mobile - if you really want to store the values as `Timestamp` entries in the documents, you could use `DateTime.SpecifyKind` to convert to a value with a `Kind` of `Utc` without changing the local value - but I'd think very carefully before doing that, as these aren't really timestamps in the sense of "an instant of time".

**Comment by jskeet** [comment]
Please add more information to this issue if you still think it needs further work, otherwise I'll close it at the end of the week.

**Comment by jskeet** [comment]
Closing.
