### ISSUE TITLE
Google.Cloud.Diagnostics.AspNetCore5

### ISSUE THREAD

**Issue by EatonZ** [googleapis/google-cloud-dotnet#5689]
A version of Google.Cloud.Diagnostics.AspNetCore, named Google.Cloud.Diagnostics.AspNetCore3, was made for .NET Core 3.
Can we expect another "special" version optimized for .NET 5?

**Comment by amanda-tarafa** [comment]
It's not about optimization, it's about the breaking changes from ASP.NET Core 2 to ASP.NET Core 3 and that we depended on some of the affected components. That does not seem to be the case for ASP.NET Core 3 to APS.NET Core 5 in which [breaking changes](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio)  seem to be around Blazor and around model binding when using Razor none of which we depend on.
I'd expect the Diagnostics.AspNetCore3 package to work exactly the same in ASP.NET Core 3 and 5.

**Comment by amanda-tarafa** [comment]
@EatonZ are you seeing any specific problems when attempting to use Google.Cloud.Diagnostics.AspNetCore3 in ASP.NET Core 5? Or did my answer addressed your question?
Of course if you encounter problems please let us know and we'll look at them.

**Comment by EatonZ** [comment]
@amanda-tarafa You answered it - thank you!
