### ISSUE TITLE
When using WhereIn in a field alongside with a range operator on another field, it throws an exception

### ISSUE THREAD

**Issue by mancku** [googleapis/google-cloud-dotnet#5719]
Hi,

After reading the documentation on [query limitations](https://cloud.google.com/firestore/docs/query-data/queries#query_limitations) I understood that the current behavior is a bug, but as I'm not 100% sure, I'm rather opening the issue as a Support request.

I'm trying to filter a collection by some document ids (less than 10) and by a property of the document, to know which users logged in to my application exactly 30 days ago, with both range operators filtering on the same field.

So, my understanding is that I'm not going against any limitation, as there's nothing in the documentation that says I can't query an "in" in a field and a range in another field.

Here's an example of what I'm trying to do:
``` C#
var minValue = DateTime.UtcNow.Date.AddDays(-30);
var maxValue = minValue.AddDays(1);
var ids = new List<string> { "437f6e3b47144e948453f83f6477ed53", "548170046e1749b2896f16de971a34df" };

var collection = this.db.Collection("users");
var query = collection.WhereIn(FieldPath.DocumentId.ToString(), ids);
query = query.WhereGreaterThanOrEqualTo("lastConnection", minValue);
query = query.WhereLessThan("lastConnection", maxValue);

var querySnapshot = await query.GetSnapshotAsync();
```
Executing this code in a **.NET Core 3.1** project, with **Google.Cloud.Firestore 2.3.0** referenced, I get the following exception:
>Grpc.Core.RpcException: Status(StatusCode="InvalidArgument", Detail="Cannot have inequality filters on multiple properties: [__key__, lastInteraction]", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1608741029.523000000","description":"Error received from peer ipv4:{AN IP HERE}","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc","file_line":1062,"grpc_message":"Cannot have inequality filters on multiple properties: [__key__, lastInteraction]","grpc_status":3}")
   at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
   at Google.Api.Gax.Grpc.AsyncResponseStream`1.MoveNextAsync(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.<ForEachAsync>g__Core|295_0[TSource](IAsyncEnumerable`1 source, Action`1 action, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ForEach.cs:line 31
   at System.Linq.AsyncEnumerable.<ForEachAsync>g__Core|295_0[TSource](IAsyncEnumerable`1 source, Action`1 action, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ForEach.cs:line 31
   at Google.Cloud.Firestore.Query.GetSnapshotAsync(ByteString transactionId, CancellationToken cancellationToken)

Am I doing something wrong or is this a bug?
Thank you very much

**Comment by jskeet** [comment]
Firstly, I'm on vacation at the moment (as is the rest of the .NET client library team) so please forgive any delays in response. But I suspect this is more of an issue with the documentation of Firestore queries rather than a bug in the .NET library - I expect this is a server-side query limitation.

I'll check your query when I'm back at work (January 5th) but until then you might want to try performing the same query with another language (or in the Firestore console if that supports custom queries - I can't remember or check right now). I suspect you'll get the same error.

**Comment by mancku** [comment]
@jskeet thank you for getting back to me, especially while being on vacation.
You were absolutely right, I tried with Node.js and got the same error.

Here's my Node.js code
```javascript
const { Firestore } = require('@google-cloud/firestore');
const firestore = new Firestore({ projectId, keyFilename })

async function quickstart() {
    const listOfReferences = ['5f87094d1face4007522c7a6', '5fa2928e9ca37c007671f268'];
    const collection = firestore.collection('PrivateInfluencersInfo');
    const minDate = new Date(2020, 11, 3, 23, 0, 0, 0);
    console.log('minDate', minDate);
    const maxDate = new Date(2020, 12, 4, 23, 0, 0, 0);
    console.log('maxDate', maxDate);
    const query = collection
    .where('__name__', "in", listOfReferences)
    .where('lastInteraction', '>=', minDate)
    .where('lastInteraction', '<', maxDate)
    ;
    let cont = 0;
    await query.get()
        .then(function (querySnapshot) {
            querySnapshot.forEach(function (doc) {
                // doc.data() is never undefined for query doc snapshots
                console.log(doc.id, " => ", doc.data());
                cont++;
            });
            console.log('total', cont);
        })
        .catch(function (error) {
            console.log("Error getting documents: ", error);
        });
}
quickstart();
```
And here's the error
>Error getting documents:  Error: 3 INVALID_ARGUMENT: Cannot have inequality filters on multiple properties: [__key__, lastInteraction]
    at Object.callErrorFromStatus (C:\Dev\node-firestore\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (C:\Dev\node-firestore\node_modules\@grpc\grpc-js\build\src\client.js:327:49)
    at Object.onReceiveStatus (C:\Dev\node-firestore\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:305:181)

Then, I don't know how to proceed, if I should close this issue and take it somewhere else, or if I should let you handle it internally. 
I will fix my .NET code to workaround that error. 
Enjoy your vacation. There's no rush for you to get back to me :)

**Comment by jskeet** [comment]
Thanks for testing that. I'll close this issue, but when I'm back at work I'll raise this with the Firestore team to clarify the documentation.
Thanks for raising it so clearly.
