### ISSUE TITLE
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses")

### ISSUE THREAD

**Issue by Snyder9195** [googleapis/google-cloud-dotnet#5722]
Unable to pull message from Google Pub/Sub 

Please reference issue #3112 as similar.

#### Environment details

  - OS: Windows 10 Pro version 2004
  - .NET version: .Net Core 3.1
  - Package name and version: Grpc.Core v2.34.0
  
![image](https://user-images.githubusercontent.com/7947336/103374902-b2d0ff80-4aa6-11eb-8d06-21d17510f52c.png)

#### Steps to reproduce

  1. Pass in project id, subscription id, and true for bool to sync method.
  2. Error occurs on the PullResponse.

Does this happen all the time, or just intermittently? All the time
If you use other Google Cloud APIs, have you seen the same problem with those? Have not had issues with Google bucket uploads
Are you able to test the same code on a different network? Yes, my home pc, which is Windows 10 Pro version 2004 works.

Code Run:

![image](https://user-images.githubusercontent.com/7947336/103374360-689b4e80-4aa5-11eb-9b3c-02ecf511f9cf.png)

Error message: 
Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1609353689.569000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1609353689.176000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\ext\filters\client_channel\lb_policy\pick_first\pick_first.cc","file_line":398,"grpc_status":14}]}")

**Comment by jskeet** [comment]
I'll look at this next Tuesday when I'm back from vacation.

But my guess is that you're behind a proxy that doesn't handle http/2 properly.

Note that the Google Cloud Storage library doesn't use gRPC, so that working is consistent with this being a gRPC connectivity issue.

**Comment by jskeet** [comment]
Okay, taking another look at the code and description, this really does sound like it's a network configuration issue. One way to test that would be to try using a different gRPC-based API. 

Here's a reasonably minimal example.

Program.cs:

```csharp
using Google.Cloud.Translate.V3;
using System;

class Program
{
    static void Main(string[] args)
    {
        var client = TranslationServiceClient.Create();
        var request = new TranslateTextRequest
        {
            Contents = { "It is raining" },
            Parent = "projects/your-project-id-here",
            SourceLanguageCode = "en-US",
            TargetLanguageCode = "fr-FR"
        };
        var response = client.TranslateText(request);
        Console.WriteLine(response);
    }
}
```

And the project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Translate.V3" Version="2.1.0" />
  </ItemGroup>

</Project>
```

Could you try that (editing it to use your project ID) and see whether it works? I suspect you don't even need to enable the Translation API, as if you get as far as the service rejecting your request on those grounds, then it will have connected appropriately.

**Comment by Snyder9195** [comment]
Performing the test above I still get the same error as before with the Translate package installed.  I'm assuming by getting the same error as before using a different library that we are not handling http2 correctly.  Would you say that is correct based on this additional test?

![image](https://user-images.githubusercontent.com/7947336/103651350-74689400-4f2f-11eb-8cfa-884a214db68e.png)


Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1609852827.224000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1609852827.224000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\ext\filters\client_channel\lb_policy\pick_first\pick_first.cc","file_line":398,"grpc_status":14}]}")****

**Comment by jskeet** [comment]
Right, so that definitely sounds like a network issue. I'd talk to your network administrator to find out more about your network topology and see if they can help you. If you need to specify a proxy, the GRPC_PROXY, HTTP_PROXY or HTTPS_PROXY environment variables are the ones to set.

**Comment by Snyder9195** [comment]
Working with my network administrator we were able to successfully make a good connection.  I will close the issue as resolved, thank you for the assistance.

**Comment by jskeet** [comment]
Wonderful - I'm so glad to hear it all worked out. Thanks for getting back to us.

**Comment by neil-gokhale** [comment]
I'm also having the same issue.  Can someone provide the list of URLs that this library hits?

**Comment by jskeet** [comment]
@neil-gokhale: Which exact library are you using?
