### ISSUE TITLE
Compute API

### ISSUE THREAD

**Issue by davidobrien1985** [googleapis/google-cloud-dotnet#5818]
Hi,

We were trying to use the dotnet SDK (our app is written in dotnet standard) to interact with some Compute resources (VPCs, Firewalls, Instances etc) but had to realise that the dotnet SDK doesn't support any compute APIs.

When is this planned for?
It seems like the node SDK has a much broader support: https://github.com/googleapis/google-cloud-node

@jskeet any timeline here for this?

Thanks.

**Comment by jskeet** [comment]
I believe you're looking for the [Google.Apis.Compute.v1](https://www.nuget.org/packages/Google.Apis.Compute.v1/) library.

There are two "styles" of .NET client libraries for Google APIs - the libraries in this repository target APIs that support gRPC, but the Compute API doesn't do that yet, so you need to use the older "REST-style" libraries. The repo for those libraries if you need to raise an issue etc is https://github.com/googleapis/google-api-dotnet-client

I'll close this issue now as I believe that answers your question, but let me know if I'm missing something.

**Comment by davidobrien1985** [comment]
@jskeet thanks. That SDK did not come up when following the documentation for dotnet sdks.
Might be worth updating the docs, even if that SDK is in maintenance mode.

**Comment by jskeet** [comment]
@davidobrien1985: Could you tell me exactly which page you were on? We have a lot of different documentation describing what's available, and it would be useful to know which part was confusing. (Some parts of it is easier to update than others.)

**Comment by davidobrien1985** [comment]
@jskeet yep, this one here: https://cloud.google.com/dotnet/
It only links to https://github.com/googleapis/google-cloud-dotnet

**Comment by jskeet** [comment]
@davidobrien1985: Great, thanks. There are tricky aspects in terms of exactly how to emphasize which libraries, but I'll definitely bring it up internally.
