### ISSUE TITLE
Not able to invoke POST request to google cloud function

### ISSUE THREAD

**Issue by TiagoBrenck** [googleapis/google-cloud-dotnet#5826]
#### Environment details

  - OS: Win64
  - .NET version: Core 3.1
  - Package name and version:  Google.Cloud.Functions.V1

#### Steps to reproduce

  1. Use the [Google Docs cloud function sample](https://cloud.google.com/functions/docs/writing/http#parsing_http_requests) that expects a `POST` request with data in the body.
  2. Create a .NET console app, that leverages `Google.Cloud.Functions.V1` nuget package.
  3. Use the code snippet to call your cloud function, but setting `Data` attribute with a json object
     ```c#
            CloudFunctionsServiceClient cloudFunctionsServiceClient = CloudFunctionsServiceClient.Create();
            object data = new { name = "my name is POST" };
            
            CallFunctionRequest request = new CallFunctionRequest
            {
                CloudFunctionName = CloudFunctionName.FromProjectLocationFunction("<your-proj>", "<region>", "<your-func-name>"),
                Data = JsonConvert.SerializeObject(data)
            };

            try
            {
               
                CallFunctionResponse response = await cloudFunctionsServiceClient.CallFunctionAsync(request);
                return response.Result;
            }
            catch (Exception ex)
            {

                throw ex;
            }
     ```
 4. Open Fiddler, execute your .NET application, and you will notice that the request is a GET, and `Data` attribute is anywhere in the request.
 5. (Extra) How would I invoke `DELETE`, `PUT`, `PATCH` using the library?

**Comment by jskeet** [comment]
I'll have a look at this tomorrow.

**Comment by jskeet** [comment]
(I'd note that this library uses gRPC though - I wouldn't expect to see any regular HTTP/1.1 request from this code, other than to obtain credentials.)

**Comment by TiagoBrenck** [comment]
I see. Well, either way, the sample function didnt receive the `name` attribute. It should have returned the message "Hello world, my name is post", but name is null.

**Comment by jskeet** [comment]
Hmm... just tried this with a test function that dumps the HTTP request, and it came through with the expected body.

Can I ask how you're checking what was returned? I can't see how you're getting the HTTP response from the function in your code. (The `CallFunctionAsync` method just starts it executing; it doesn't contain any response.)

I've just tried the [C# version of the Cloud Functions sample](https://cloud.google.com/functions/docs/writing/http#writing_http_content-csharp) with one modification to log the response that it's written, and it worked fine, logging "Hello my name is POST!" as the output. So everything seems to be working as far as I can see.

**Comment by TiagoBrenck** [comment]
@jskeet I deleted my Cloud Function and created again copying/pasting the C# version as is, and it works. Before I was posting a more complex object in the body, so I might have messed up something there.

Thanks,

**Comment by jskeet** [comment]
@TiagoBrenck: Okay - feel free to open another issue if you end up with things broken again and don't know why.
