### ISSUE TITLE
DocumentSnapshot ConvertTo<> set null to property values

### ISSUE THREAD

**Issue by TomasWeg** [googleapis/google-cloud-dotnet#5832]
Its simple. When I run the following code: 
`List<CustomerDetails> customerDetails = snapshot.Documents.Select(x => x.ConvertTo<CustomerDetails>()).ToList();`

The only property that is parsed correctly is the document id. I will show the CustomerDetails.cs class.

```csharp
[FirestoreData]
    public class CustomerDetails : IEntity
    {

        [FirestoreDocumentId]
        public string Id { get; set; }

        [FirestoreProperty]
        public string Email { get; set; }

        [FirestoreProperty]
        public string BusinessName { get; set; }
        
        [FirestoreProperty]
        public string Cuit { get; set; }

        [FirestoreProperty]
        public string FirstName { get; set; }

        [FirestoreProperty]
        public string LastName { get; set; }

        [FirestoreProperty]
        public List<Address> Addresses { get; set; }

        [FirestoreProperty]
        public string PasswordHash { get; set; }

        [FirestoreProperty]
        public string Scope { get; set; }

        [FirestoreProperty]
        public int? PasswordTryCount { get; set; }

        [FirestoreProperty]
        public List<string> NormalizedQuery { get; set; }

        [FirestoreProperty]
        public List<string> NotificationTokens { get; set; }

        [FirestoreProperty]
        public bool IsNew { get; set; }

        public CustomerDetails() { }
    }
```

It does not throw any exception, only all the properties are null except the Id.

**Comment by jskeet** [comment]
So what does the document look like, and what created it? Can you provide a complete example that creates the document, stores it, then loads it?
Note that if the document has fields of `email`, `businessName` etc, that would explain it - you'd need to use `[FirestoreProperty("email")]` etc.

**Comment by TomasWeg** [comment]
@jskeet  The document is created with that c# class, and the field names are Pascal Case, just like the C# class. Its strange because it stopped working today!
Here is an example of a Document.

![2021-01-12 10_50_07-Window](https://user-images.githubusercontent.com/31850785/104322662-f7579480-54c3-11eb-9402-10773b78ba9d.png)

**Comment by jskeet** [comment]
> Its strange because it stopped working today!

So the exact same code was working before? That's very strange. If you examine the snapshot (or convert each document to a `Dictionary<string, object>`), does it have all the right data? I'm wondering whether the query is selecting only some fields.

If you could provide a complete repro (e.g. a console app that creates a document, stores it, then reloads it) that would help to reproduce the problem. Currently I *doubt* that it's a library issue, but we don't really have enough information about the snapshot for me to reproduce it myself.

**Comment by TomasWeg** [comment]
I tried to convert to a dictionary and contains the right data. And yes,
the exact same code was working yesterday, I will test it out with a
console app

**Comment by TomasWeg** [comment]
@jskeet hey look at this. I tried creating a new document from CustomerDetails.cs and 
![2021-01-12 17_30_02-Window](https://user-images.githubusercontent.com/31850785/104369195-d4e16d80-54fb-11eb-8c50-ae160a553dcc.png)

"This document does not contains any data"

**Comment by jskeet** [comment]
Again, please provide a complete example, so I can run it and see it for myself. It now sounds like there are two different problems: one serializing and one deserializing. But without a complete example that I can reproduce the problem, I won't be able to help I'm afraid.

**Comment by TomasWeg** [comment]
I'm so sorry, I have created an internal class FirestorePropertyAttribute which extends Attribute with keyboard shortcuts. I found it and deleted and now it's working. So sorry.

**Comment by jskeet** [comment]
Ah, that would definitely explain it. Glad we got to the bottom of it.
