### ISSUE TITLE
[Spanner] feat: add `SpannerDate` struct

### ISSUE THREAD

**Issue by olavloite** [googleapis/google-cloud-dotnet#5839]
The Spanner client library currently uses `datetime` as the default type for both `TIMESTAMP` and `DATE` columns. That produces some challenges:
1. Setting a `datetime` value on a `SpannerParameter` without explicitly also setting the `DbType` or `SpannerDbType`, will always create a `SpannerParameter` with type `TIMESTAMP`. This makes it difficult to make a good default mapping for generic frameworks that only set a value and not a specific type for a parameter (e.g. Entity Framework).
2. `datetime` values always contain a time component and a kind (local, UTC, unspecified). This indicates that the `datetime` represents a specific moment in time, while a `DATE` value in Cloud Spanner [explicitly does not do so](https://cloud.google.com/spanner/docs/data-types#date_type).

Having a `SpannerDate` struct similar to the `SpannerNumeric` struct would mitigate the above problems. We should consider adding that to the client library and use that as the default type for `DATE` columns.

**Comment by jskeet** [comment]
This sounds like something that would be hard to do comprehensively without it being a breaking change - perhaps we should wait until we next want to do a new major version?

**Comment by jskeet** [comment]
It's worth noting that in .NET 6 there's a `DateOnly` type which represents a date. I wonder whether we might be able to use that rather than creating a new struct - obviously we could only do that on .NET 6, which is awkward.

**Comment by jskeet** [comment]
(We may want to introduce our own SpannerDate struct, but have conversions to and from DateOnly when running on .NET 6, and potentially have a configuration option to go straight to DateOnly, in the same way as we configure decimal conversions when we resolve #5837.)

**Comment by Rishabh-V** [comment]
This is now complete via #8367 #8534  #8656
