### ISSUE TITLE
PubSub: Server-side flow control

### ISSUE THREAD

**Issue by nathan-c** [googleapis/google-cloud-dotnet#5840]
Following #5119, we have been waiting for server-side flow control to be enabled on the server. In the [release notes](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.PubSub.V1/history.html) for v2.2.0 (2020-12-02) it is mentioned that `Server side flow control is on track to be enabled by the 2nd week of December 2020.`

I cant see any mention of server-side flow control being enabled on https://cloud.google.com/pubsub/docs/release-notes

Is there an ETA on its release? 

I realise this (client repo) isn't the right place for server-side issues, however as the client release notes mention it, I thought it worth asking. If there is a better place to ask this please do let me know!

**Comment by jskeet** [comment]
I'll ask the PubSub team today and update this issue when I hear something.

**Comment by jskeet** [comment]
I've now heard back:

> This was fully rolled out to production by December 9th. Since this is not really a public feature (the same way subscription filtering or ordering are) and rather an enhancement at the server side, it was not part of the product release notes.

So it should already be live. Please let me know if you have any issues with this; I'll close the issue now, but we can reopen it if necessary.

**Comment by nathan-c** [comment]
This is great news, thanks!
