### ISSUE TITLE
[Spanner] `WITH` clause is not recognized as query command type

### ISSUE THREAD

**Issue by olavloite** [googleapis/google-cloud-dotnet#5857]
The Cloud Spanner SQL dialect allows queries to start with either `SELECT` or `WITH`. The latter is currently not recognized as a keyword indicating the start of a `SELECT` command in the client library.

See https://cloud.google.com/spanner/docs/query-syntax for full query syntax reference.

Example query that is a valid Cloud Spanner query, but that is not recognized:

```sql
WITH AlbumsView AS (SELECT * FROM Albums)
select Title
from AlbumsView
```

> I suspect this is what needs changing: https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommandTextBuilder.cs

**Comment by jskeet** [comment]
I suspect this is what needs changing: https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommandTextBuilder.cs

**Comment by olavloite** [comment]
> I suspect this is what needs changing: https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommandTextBuilder.cs

Yes, I already have a fix, I'm just adding a number of test cases for other types of commands as well.

On the same note: The current implementation also does not work if the user has specified statement hints and/or comments. That seems to me like a lot less of a problem, but still not 100% correct in this case.

**Comment by jskeet** [comment]
Right. Happy to see any degree of fix, whether it's a really complete one or a stop-gap.
