### ISSUE TITLE
PubSub: PublisherClient.CreateAsync and ShutdownAsync

### ISSUE THREAD

**Issue by dustinmoris** [googleapis/google-cloud-dotnet#5893]
I have a quick question and some minor feedback on the PubSub library.

[According to the documentation](https://googleapis.dev/dotnet/Google.Cloud.PubSub.V1/2.3.0/index.html) a `PublisherClient` must be created via the `PublisherClient.CreateAsync` method and later shut down via `publisher.ShutdownAsync`.

My quarrel or misunderstanding with these methods is that they feel very unidiomatic and difficult to use in .NET. [In issue #3447](https://github.com/googleapis/google-cloud-dotnet/issues/3447) @chrisdunelm suggests that the `PublisherClient` should be re-used as much as possible:

> Reuse the publisher and subscribers as much as possible

This suggests to me to initialise a `PublisherClient` in the constructor of a singleton service, however due to the async nature of the factory it feels wrong and pushes me (and probably many other users) to believe that it should be a short lived transient dependency initialised at the time of publishing a message.

Which one should it be?

My even bigger confusion is around the `ShutdownAsync` method:

```csharp
// PublisherClient instance should be shutdown after use.
// The TimeSpan specifies for how long to attempt to publish locally queued messages.
await publisher.ShutdownAsync(TimeSpan.FromSeconds(15));
```

What is this method doing and what does it mean to pass in a 15 second timespan? Shall I await this method and will it then block me for 15 seconds or shall I fire and forget it without an await?

Assuming I have a singleton instance of `PublisherClient` does the `ShutdownAsync` method cause an issue if I don't invoke it until the application ends? Or perhaps the `ShutdownAsync` method is a bit like a flush with loggers and should get invoked more frequently? If it should get called more frequently then how frequent? At the end of a series of published messages or can it also get invoked at the end of every message published? Remember that most people will probably wrap the logic to publish a single message in some sort of service, and therefore such class design could cause the `ShutdownAsync` method to be invoked way too often, which is why I want to really understand what it's supposed to do.

The documentation is extremely thin on the proper usage and the meaning of those methods. This is very unidiomatic .NET code making it very hard even for very experienced developers to defer the meaning/purpose of the methods by looking at their signature. Furthermore the `ShutdownAsync` method converts the `TimeSpan` into a `CancellationToken` which is even weirder, but doesn't let me to pass in a cancellation token myself.

If `ShutdownAsync` is supposed to do some clean up work at the end of its lifecycle then would it have made more sense to implement the `IDisposable` or `IDisposableAsync` interface to steer .NET developers to do the correct thing?

Overall I'm really not clear how to manage a `PublisherClient` in order to avoid unnecessary long work, blocking code and to be safe. What is the best practice for this class?

**Comment by dustinmoris** [comment]
Also the linked documentation is wrong on the `PublisherServiceApiClient`:

```
// Publish a message to the topic.
PubsubMessage message = new PubsubMessage
{
    // The data is any arbitrary ByteString. Here, we're using text.
    Data = ByteString.CopyFromUtf8("Hello, Pubsub"),
    // The attributes provide metadata in a string-to-string dictionary.
    Attributes =
    {
        { "description", "Simple text message" }
    }
};
publisher.Publish(topicName, new[] { message });
```

The Publish method doesn't take a `PubsubMessage` as an argument. It demands a `PublishRequest` and there is no documentation on how to turn a `PubsubMessage` into a `PublishRequest`. There is also no factory method or constructor which tells me how to create a `PublishRequest`.

Is this library still maintained or is there a V2 version of PubSub with more up to date documentation somewhere?

**Comment by jskeet** [comment]
Yes, the library is still definitely maintained, and that code compiles - it's compiled as part of publishing the documentation.

The `Publish` method of `PublisherServiceApiClient` has the following overloads:

- `PublishResponse Publish(PublishRequest request, CallSettings callSettings = null)`
- `PublishResponse Publish(string topic, IEnumerable<PubsubMessage> messages, CallSettings callSettings = null)`
- `PublishResponse Publish(TopicName topic, IEnumerable<PubsubMessage> messages, CallSettings callSettings = null)`

I'm not quite sure why you don't see the second and third overloads - could you let me know why you think `Publish` "demands" a `PublishRequest`? (All the request types are protobuf messages by the way - you can just call the parameterless constructor and populate properties...)

**Comment by dustinmoris** [comment]
Ah thanks, my bad! I quickly opened my project in VS Code and there the Intellisense didn't show me more than one overload, but Rider shows me everything 😃

**Comment by chrisdunelm** [comment]
To answer your specific questions:

If you are regularly publishing messages to the same topic then you should create a singleton `PublisherClient` and always use this same instance to publish messages for the lifetime of your application.
You are correct that it's not entirely clear how to do this best in a DI context, although blocking on the `Task<PublisherClient>` returned from `CreateAsync(...)` may be reasonable. We will consider adding a synchronous `Create(...)` call to make this more obvious.

Shutdown is asynchronous because messages published with `PublishAsync(...)` may be internally buffered before being sent to the server. The timeout specified in `ShutdownAsync(...)` is the maximum time to wait to allow these internally buffered messages to be pushed to the server. If you ignore the returned `Task` and the program exits, then some buffered messages may not be published.
The timeout given here is a maximum; in most cases the returned task will complete considerably quicker - e.g. if there are currently zero buffered messages then the returned task will complete immediately.
This shutdown method is *not* a `Flush(...)` equivalent - it shuts down the publisher, and no further messages can be published with this `PublisherClient` instance.
There is a `ShutdownAsync(CancellationToken)` overload, so you may directly pass a `CancellationToken` if you wish.

The `IAsyncDisposable` interface did not exist when this code was written, and it does not accept a timeout, so is not used.

To use most effectively:
* Ideally create just one instance of `PublisherClient` per topic for the duration of execution. Instance creation of this class is expensive as multiple gRPC channels are brought up.
* It's OK to `await` or block (`.Result`) on `CreateAsync(...)`
* Do not block on calls to `PublishAsync(...)`
* The task returned by calls to `PublishAsync(...)` may be ignored if you don't need to know whether messages were successfully published. The task completes successfully when the task has been published to the server; or faults if there was an error publishing.
* Do `await` (or block) on shutdown

**Comment by dustinmoris** [comment]
Thank you for answering all my questions and confirming some of my thoughts! This is very helpful information which I think would be nice to add to the documentation :)

**Comment by jskeet** [comment]
Just to clarify one of Chris's points - *most* of the time it's okay to block on CreateAsync, but if it uses default credentials and needs to contact the Compute Engine metadata server, it will be genuinely async.

Chris's PR manages to make it properly synchronous.

**Comment by dustinmoris** [comment]
I just wanted to say that my question has been sufficiently answered, so from my point of view this issue can be closed, but if you want too keep this issue open as a reminder to update the current documentation then I appreciate it and I'd be happy to help with a PR if you accept them.

**Comment by jskeet** [comment]
@dustinmoris: I don't know whether @chrisdunelm has already started on a docs PR for this. If not, I'm sure he'd welcome a contribution.

**Comment by chrisdunelm** [comment]
Not yet started, but expect to get it done later this week. Yes, sounds sensible to leave this issue open until the docs are updated.

**Comment by jskeet** [comment]
The Create methods are now available in 2.4.0, btw.

**Comment by dustinmoris** [comment]
Thanks!

**Comment by hundreder** [comment]
Sorry for jumping in into closed issue, but this is closest I've found to what I am interested in.
I see that two relatively similar types (at least by names) exist for publishing messages and both are public via lib api, PublisherServiceApiClient and PublisherClient. They both have PublishAsync method. I am using PublisherClient, constructed as singleton the way you've discussed here, and PublisherClient is the one used in documentation. What I don't see is, a way to cancel message publishing via CancellationToken. If http request is being canceled by the client, message publishing wont be canceled if its executed at the moment of canceling.
On the other hand PublisherServiceApiClient accepts CancelationToken, but not sure if it's the way to go.

Am I missing something here @chrisdunelm  @jskeet ?

**Comment by jskeet** [comment]
@hundreder: Please create a new issue rather than piggy-backing on a mostly unrelated one, and I'll have a look. (@chrisdunelm no longer works on the project.)

**Comment by jstafford5380** [comment]
> To answer your specific questions:
> 
> If you are regularly publishing messages to the same topic then you should create a singleton `PublisherClient` and always use this same instance to publish messages for the lifetime of your application. Y
> ...
> * Ideally create just one instance of `PublisherClient` per topic for the duration of execution. Instance creation of this class is expensive as multiple gRPC channels are brought up.
> ...

Sorry for the necromancing, but I'm still unclear if this answered part of the question regarding the shut down; I think you acknowledged that it's not clear how to use with DI, then explained what shutdown is and how to create the client, but didn't actually finish clarifying on how to use with DI regarding shutdown. If I register PublisherClient with DI, how can I ensure it's calling ShutdownAsync at the end of its lifetime? Or is this something I don't need to worrk about? I can't tell if it's implementing IDisposable or IAsyncDisposable by looking at the source code (it appears to just implement the abstract base via code generation, but the base class doesn't implement disposables). Maybe I'm just not seeing it.

**Comment by jskeet** [comment]
@jstafford5380: It doesn't implement `IAsyncDisposable` or `IDisposable`, no - for reasons Chris laid out earlier on.

I'd need to check, but I believe it *could* be a problem as you could have unpublished messages which are still buffered. Given that this is only part of what's discussed in this issue, I'll create a new issue, cc you, and assign it to the current owner of the PubSub library. We'll need to work out how to best design this - it's still not 100% obvious to me what the right solution is, to be honest. (Our libraries are now *generally* more DI-friendly, but I don't think we've added simple ways of initializing PublisherClient/SubscriberClient...)

**Comment by jstafford5380** [comment]
> @jstafford5380: It doesn't implement `IAsyncDisposable` or `IDisposable`, no - for reasons Chris laid out earlier on.
> 
> I'd need to check, but I believe it _could_ be a problem as you could have unpublished messages which are still buffered. Given that this is only part of what's discussed in this issue, I'll create a new issue, cc you, and assign it to the current owner of the PubSub library. We'll need to work out how to best design this - it's still not 100% obvious to me what the right solution is, to be honest. (Our libraries are now _generally_ more DI-friendly, but I don't think we've added simple ways of initializing PublisherClient/SubscriberClient...)

Thanks Jon
