### ISSUE TITLE
Google.Cloud.Diagnostics.AspNetCore version 4.2.0 doesn't work in .net 5.0 

### ISSUE THREAD

**Issue by sergiutugulschi** [googleapis/google-cloud-dotnet#5925]
I started to get the same error  as mentioned here https://github.com/GoogleCloudPlatform/google-cloud-dotnet-powerpack/issues/22  in a docker images that uses mcr.microsoft.com/dotnet/sdk:5.0

As a fix mentioned in the linked issue I have installed separately Grpc.Core package of version 2.35.0 and now I'm getting this exception

---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)

at Google.Api.Gax.GkePlatformDetails.TryLoad(String metadataJson, KubernetesData kubernetesData)
at Google.Api.Gax.Platform.LoadInstanceAsync()
at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task1.get_Result()
at Google.Api.Gax.Platform.Instance()
at Google.Api.Gax.Grpc.MonitoredResourceBuilder.FromPlatform()
at Google.Cloud.Diagnostics.Common.EventTarget.ForLogging(LogTarget logTarget, String logName, LoggingServiceV2Client loggingClient, MonitoredResource monitoredResource)
at Google.Cloud.Diagnostics.Common.EventTarget.ForLogging(String projectId, String logName, LoggingServiceV2Client loggingClient, MonitoredResource monitoredResource)
at Google.Cloud.Diagnostics.Common.ErrorReportingOptions.Create(String projectId, BufferOptions bufferOptions, RetryOptions retryOptions)
at Google.Cloud.Diagnostics.Common.ErrorReportingContextExceptionLogger.Create(String projectId, String serviceName, String version, ErrorReportingOptions options)
at Google.Cloud.Diagnostics.Common.ContextExceptionLogger.Create(String projectId, String serviceName, String version, ErrorReportingOptions options)
at Google.Cloud.Diagnostics.AspNetCore.ErrorReportingExceptionLoggerExtension.AddGoogleExceptionLogging(IServiceCollection services, Action`1 setupAction)

**Comment by jskeet** [comment]
When you say "doesn't work in .NET 5.0" I suspect there's a significant degree of context here.

Please tell us *exactly* what context you're running in. A minimal example (code, project file, Dockerfile if relevant) would make it a lot easier to help.

**Comment by sergiutugulschi** [comment]
We are deploying a .net 5.0 Asp.NET 5.0 api to Cloud Run by creating a docker container image based on mcr.microsoft.com/dotnet/sdk:5.0

**Comment by jskeet** [comment]
Okay, and does your project have any other dependencies? Again, a minimal example would be really helpful - the simpler it is for us to reproduce the issue, the quicker we're likely to be able to resolve it.

**Comment by sergiutugulschi** [comment]
![Packages1](https://user-images.githubusercontent.com/67583483/107350774-84e1d080-6ad2-11eb-9458-21cb2e4e4b4d.PNG)
![Packages2](https://user-images.githubusercontent.com/67583483/107350788-8a3f1b00-6ad2-11eb-9eb3-6e50cd27bcc3.PNG)
Those are the mainly packages that we are using

**Comment by amanda-tarafa** [comment]
For ASP.NET Core 3 and over you should be using [`Google.Cloud.Diagnostics.AspNetCore3`](https://www.nuget.org/packages/Google.Cloud.Diagnostics.AspNetCore3/) and **not** [`Google.Cloud.Diagnostics.AspNetCore`](https://www.nuget.org/packages/Google.Cloud.Diagnostics.AspNetCore/). Try changing your dependency and let us know.

**Comment by sergiutugulschi** [comment]
@amanda-tarafa I"m using ASP.NET Core 5 I have already tried that still didn't work the same exception

**Comment by jskeet** [comment]
Okay, that's a *lot* of other packages. I wouldn't be at all surprised if it's a mismatch in versions somewhere. Although "Those are the mainly packages that we are using" doesn't really give me confidence that it's an exhaustive list - again, if you could provide a minimal but *complete* example, we'd be able to help you quicker.

You should *definitely* be using Google.Cloud.Diagnostics.AspNetCore3 rather than Google.Cloud.Diagnostics.AspNetCore though.

Does the app work locally when you're not deploying it with docker?

**Comment by jskeet** [comment]
(While we only have incomplete information, I'm reluctant to spend too much time trying to reproduce this myself. It would be entirely possible for me to try the packages you've listed, not reproduce the problem, and then you find that there's another package you haven't mentioned so far. Without complete information, trying to reproduce this will be very inefficient.)

**Comment by amanda-tarafa** [comment]
I would also advise you to go through Microsoft [guides](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#update-package-references) for migrating to ASP.NET Core 5. It seems that you should update some dependencies, and also the [recommended docker image](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#update-package-references)  there is not the one you are using.

Again you should really be using Google.Cloud.Diagnostics.AspNetCore**3**.

**Comment by sergiutugulschi** [comment]
Thanks for your help, I have removed all the packages and created just a basic project and it works now, so apparently some referenced packages is causing it. 
Thanks for the support.
