### ISSUE TITLE
datastore end cursor to ByteString.FromBase64 (System.FormatException)

### ISSUE THREAD

**Issue by himadrinath** [googleapis/google-cloud-dotnet#5944]
datastore query sending end cursor value  converting with ByteString.FromBase64 getting error

`System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
`
#### Environment details

  - OS: windows 10
  - .NET core version: 3.1
  - Package name and version: Google.Cloud.Datastore.V1 (3.1.0)

#### Steps to reproduce

  1.  end cursor value : Cl0KFQoIRGF0ZVRpbWUSCQjA0oD27+TbAhJAahJqfmRldm9wcy1zb3V0aGFzaWFyIwsSCE1lc3NhZ2VzIhVKeHR0OUN1fllDY0VHU35QdkZuaGIMogEEQ2hhdBgAIAE=
  2. ByteString.FromBase64(value)

**Comment by jskeet** [comment]
That exact string should be fine, assuming there's no whitespace before or after. Your steps to reproduce don't reproduce the issue for me:

Program.cs:

```csharp
using System;
using Google.Protobuf;

namespace Base64Issue
{
    class Program
    {
        static void Main(string[] args)
        {
            string text = "Cl0KFQoIRGF0ZVRpbWUSCQjA0oD27+TbAhJAahJqfmRldm9wcy1zb3V0aGFzaWFyIwsSCE1lc3NhZ2VzIhVKeHR0OUN1fllDY0VHU35QdkZuaGIMogEEQ2hhdBgAIAE=";
            ByteString bytes = ByteString.FromBase64(text);
            Console.WriteLine(bytes.Length);
        }
    }
}
```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.14.0" />
  </ItemGroup>

</Project>
```

Output: 95

Please could you provide a similar program that shows the error?

**Comment by himadrinath** [comment]
you r right i didn't see the binding parameter in controller 

my bad. thanks for help
