### ISSUE TITLE
Recreating Pubsub topics and subscriptions with the same name in Pubsub Emulator sometimes gives Topic not found exception

### ISSUE THREAD

**Issue by sergiutugulschi** [googleapis/google-cloud-dotnet#5958]
We have some integration tests in Asp.NET Core 5 which are publishing messages to pubsub emulator. The pubsub emulator is started in docker container. In order to clear messages in pubsub emulator I'm deleting and recreating the topics and the subscriptions before each test run. 

```csharp
// Delete topic
TopicName topic = new TopicName(EnvironmentVariables.ProjectId, topicName);
publisherService.DeleteTopic(topic);

// Delete subscription
SubscriptionName subscription = new SubscriptionName(EnvironmentVariables.ProjectId, subscriptionName);
subscriberService.DeleteSubscription(subscription);

// Create topic
TopicName topic = new TopicName(EnvironmentVariables.ProjectId, topicName);
publisherService.CreateTopic(topic);

// Create subscription
SubscriptionName subscription = new SubscriptionName(EnvironmentVariables.ProjectId, subscriptionName);
TopicName topic = new TopicName(EnvironmentVariables.ProjectId, topicName);

subscriberService.CreateSubscription(subscription, topic, pushConfig: null, ackDeadlineSeconds: 60);
```

From 37 tests, 35 are passing and two are failing with exception message:

```text
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. Unhandled exception. **Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="NotFound", Detail="Topic not found",** DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1613729362.707964780","description":"Error received from peer ipv4:127.0.0.1:8085","file":"/var/local/git/grpc/src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Topic not found","grpc_status":5}")
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Google.Cloud.PubSub.V1.Tasks.ForwardingAwaiter`1.GetResult()
   at Google.Cloud.PubSub.V1.Tasks.Extensions.<>c__DisplayClass5_0`1.<<ConfigureAwaitHideErrors>g__Inner|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Google.Cloud.PubSub.V1.Tasks.ForwardingAwaiter`1.GetResult()
   at Google.Cloud.PubSub.V1.PublisherClientImpl.PublishAsync(PubsubMessage message)
   at Google.Cloud.PubSub.V1.Tasks.ForwardingAwaiter`1.GetResult()
   at Google.Cloud.PubSub.V1.PublisherClientImpl.PublishAsync(PubsubMessage message)
```

It is strange that the testes are failing when running on github server, locally there is no such exception. 

**The exception appears in the code that is trying to Create the subscription this code is run after CreateTopic code so I expect the topic to be created.**

**Comment by jskeet** [comment]
I strongly suspect that this is a PubSub emulator issue rather than a .NET client library issue, which means I'm unlikely to be able to do more than give a few suggestions, or redirect you to the [PubSub support page](https://cloud.google.com/pubsub/docs/getting-support).

Just to be clear, am I right in saying that the `CreateSubscription` code *does* succeed? (I'd expect that to fail if the emulator doesn't know about the topic yet.)

Could you try - if only for the purposes of testing - adding a brief sleep after creating the topic?

**Comment by jskeet** [comment]
Hang on a sec - you say:

> The exception appears in the code that is trying to Create the subscription this code is run after CreateTopic code so I expect the topic to be created.

But that doesn't fit with the stack trace you've shown, which shows an exception in `PublishAsync`. If it's actually `CreateSubscription` that's failing, then it's relatively simple to add a workaround which tries to create the subscription, and then retries after a short delay if it fails. (You could even make that retry automatic with a suitable `CallSettings` value.)

But we really need to know which piece of code is failing first.

**Comment by sergiutugulschi** [comment]
Yes, sorry for the confusion, yes it is actually appearing at PublishAsync after recreating the topic and the subscription

**Comment by jskeet** [comment]
Okay - so `CreateSubscription` always succeeds? It's possible that there's more caching involved for Publish than for CreateSubscription.

One other thing to try, as well as the delay I mentioned before: instead of deleting and recreating the same topic multiple times, could you try using a unique topic name for each test? I wouldn't be *entirely* surprised if "create X, publish to X, delete X, create X, publish to X" fails, but "create X, publish to X, delete X, create Y, publish to Y" succeeds.

**Comment by sergiutugulschi** [comment]
Yes `CreateSubscription` always succeeds, we tried with setting a delay like ` await Task.Delay(200)`; will try to increase it to 1 second. Yes will try also the second solution, thank you for your sugestions.

**Comment by sergiutugulschi** [comment]
The delay didn't help, so will go with the second suggestion to create unique topics and subscriptions for each test.

**Comment by jskeet** [comment]
@sergiutugulschi: Any updates on how this went?

**Comment by alexandru-miaun** [comment]
We added diferent topics and subscription name for each tests and this fixed it. However if we tried deleting this topics and subscriptiond in a dispose method we were still getting this issue so we just leave the topics Like that and have them killed at container destruction.

**Comment by jskeet** [comment]
Okay. I'll close this now as it sounds like you have a solution, and it's not like this is anything we could fix on our side anyway :) (It would have to be in the emulator.)
