### ISSUE TITLE
PubSub PublisherClient is trying to get default credentials with EmulatorDetection.EmulatorOnly

### ISSUE THREAD

**Issue by dmytro-fedorchuk** [googleapis/google-cloud-dotnet#5973]
PubSub PublisherClient is trying to get default credentials with EmulatorDetection.EmulatorOnly.
Related changes: https://github.com/googleapis/google-cloud-dotnet/pull/5673/files

<PackageReference Include="Google.Cloud.PubSub.V1" Version="2.3.0" />

Example:
```
var clientcreationSettings = new PublisherClient.ClientCreationSettings()
   .WithEmulatorDetection(Google.Api.Gax.EmulatorDetection.EmulatorOnly);
await PublisherClient.CreateAsync(topicName, clientcreationSettings);
```
Exception:
> System.InvalidOperationException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. ...

https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/PublisherClient.cs#L258

I guess it should be implemented in the same way as for SubscriberClient. According to specified PR - credentials section was removed from SubscriberClient.CreateAsync.

**Comment by dmytro-fedorchuk** [comment]
When trying to call PublisherClient.CreateAsync with ChannelCredentials.Insecure  it fails with:
> System.InvalidOperationException: ChannelCredentials is set, contrary to use of EmulatorDetection.EmulatorOnly
>    at Google.Api.Gax.GaxPreconditions.CheckState[T1,T2,T3](Boolean condition, String format, T1 arg0, T2 arg1, T3 arg2)
>    at Google.Api.Gax.Grpc.ClientBuilderBase`1.GetEmulatorEnvironment(IEnumerable`1 requiredEmulatorEnvironmentVariables, IEnumerable`1 allEmulatorEnvironmentVariables, Func`2 environmentVariableProvider)
>    at Google.Cloud.PubSub.V1.PublisherServiceApiClientBuilder.MaybeCreateEmulatorClientBuilder()

Looks like removing environment variable PUBSUB_EMULATOR_HOST is the only option to use emulator. With manually specified credentials and endpoint settings.

**Comment by jskeet** [comment]
Thanks, will look into it.

**Comment by jskeet** [comment]
Please update to 2.4.0 - it should be fine there. Thanks for filing the issue!

**Comment by dmytro-fedorchuk** [comment]
@jskeet Thank you for the quick fix!
