### ISSUE TITLE
Connecting to Firestore emulator

### ISSUE THREAD

**Issue by jchannon** [googleapis/google-cloud-dotnet#5979]
I have downloaded a docker image with the Firestore emulator in it and I'm trying to connect to it from .NET. 

I have set environment variables I believe the Firestore library looks for but it still tried to connect to the Firestore inside GCP. 

Could you point me in the right direction please?

**Comment by jskeet** [comment]
Did you set the code to explicitly look for the environment variables, as described at https://googleapis.dev/dotnet/Google.Cloud.Firestore/latest/index.html#connecting-to-the-emulator ? If not, that's probably it.

**Comment by jchannon** [comment]
Thanks
