### ISSUE TITLE
pubsub: schema support

### ISSUE THREAD

**Issue by hongalex** [googleapis/google-cloud-dotnet#6004]
Schemas is a new feature of Pub/Sub that just went public preview. I saw the [autosynth PR](https://github.com/googleapis/google-cloud-dotnet/pull/5712/files) was merged in a while ago. Just wanted to check on if there's anything that needs to be done in the manual layer for C#.

**Comment by jskeet** [comment]
@hongalex: I haven't looked at it, but the Spanner team has generally been driving the features here.

**Comment by jskeet** [comment]
(Ignore my talk about Spanner - I'm not thinking straight.)

Users will already be able to use this with the `SchemaServiceClient`. Unless there are *specific* requests for additional manual support from the PubSub team, I don't think there's anything we need to do.

**Comment by jskeet** [comment]
It looks like there's a [task to add samples](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/1279) - so if any extra work is required, I imagine it will come out of that.

@hongalex: Do you want to leave this open, or are you happy for us to close it as "no known work, and we'll find out if there's any need for anything else via the samples"?

**Comment by hongalex** [comment]
Yeah, I'll close it now. Yeah as far as I know, this feature shouldn't require much manual work since it's just an additional service + some fields to export, but just wanted to double check. Thanks!
