### ISSUE TITLE
Program has exited with code 0

### ISSUE THREAD

**Issue by danielissac** [googleapis/google-cloud-dotnet#6018]
When trying to publish messages using PublisherClient.PublishAsync the execution getting stopped. I can see "The program '[16216] Pub.exe' has exited with code 0 (0x0)." in debug console and the messages are not published to the topic.
I'm able to publish messages to the topic using python library google-cloud-pubsub. But I need to do this using c#. Why the program has exited... Am I doing anything wrong?
I'm following this [https://cloud.google.com/pubsub/docs/quickstart-client-libraries](url)

**Comment by jskeet** [comment]
We'll need more detail than that, I'm afraid. Could you provide details about your operating system, .NET version, library versions and ideally a complete example that reproduces the problem?

**Comment by danielissac** [comment]
@jskeet 
OS ---> Windows 10
.NET ---> 4.8
Google.Cloud.PubSub.V1 ---> version 2.4.0

      `TopicName topicName = TopicName.FromProjectTopic(projectId, topicId);
      PublisherClient publisher = await PublisherClient.CreateAsync(topicName);

      PubsubMessage pubsubMessage = new PubsubMessage()
      {
	      Data = ByteString.CopyFromUtf8("this is message")
      };
      string id = await publisher.PublishAsync(pubsubMessage);`

**Comment by jskeet** [comment]
That's a small part of a program... that part looks okay, but we don't know how that's being called. If you could provide a complete example that we could run ourselves, that would be much more helpful. (For example, if this is an async method that you call from synchronous code and then ignore the returned task, that would certainly explain the program just terminating without publishing anything.)

**Comment by danielissac** [comment]
Publisher.cs
--------------------------------------------------------------------------------------------------
using Google.Cloud.PubSub.V1;
using Google.Protobuf;
using System;

namespace Pub
{
    public static class Publisher
    {
        public static async void PublishMessagesAsync(string projectId, string topicId)
        {
            try
            {
                TopicName topicName = TopicName.FromProjectTopic(projectId, topicId);
                PublisherClient publisher = await PublisherClient.CreateAsync(topicName);

                PubsubMessage pubsubMessage = new PubsubMessage()
                {
                    Data = ByteString.CopyFromUtf8("this is message")
                };
               
                string id = await publisher.PublishAsync(pubsubMessage);
                Console.WriteLine("published");

            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
    }
}


Program.cs
--------------------------------------------------------------------------------
using Google.Apis.Auth.OAuth2;
using Google.Cloud.Iam.V1;
using Google.Cloud.PubSub.V1;
using Google.Cloud.Storage.V1;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Pub
{
    class Program
    {
        private static string projectID = "pubsub-1615322837184";
        private static string topicID = "ccs_evpf_topic";
        //private static string subID = "ccs_evpf_topic-sub";
        static void Pub()
        {
             Publisher.PublishMessagesAsync(projectID, topicID);
        }
        static void Main(string[] args)
        {
             Pub();
        }
    }
}

**Comment by jskeet** [comment]
Right - so that's exactly as I described. You're calling an async method, but not actually waiting for it to complete. So as soon as it hits the first place where it needs to schedule a continuation, the `PublishMessagesAsync` method is returning, your `Pub` method is returning, your `Main` method is returning, and the process is exiting. You want to wait for the `PublishMessagesAsync` to actually *complete*.

It's easy to fix:

- Change the return type of `PublishMessagesAsync` to `Task`
- Remove `Program.Pub` entirely - you don't need it
- Change your `Main` method to:

```csharp
static async Task Main(string[] args)
{
    await Publisher.PublishMessagesAsync(projectID, topicID);
}
```

**Comment by danielissac** [comment]
@jskeet  Thank you so much for your help.
