### ISSUE TITLE
Crash application during FirestoreDb instance initialization

### ISSUE THREAD

**Issue by AlexDevFx** [googleapis/google-cloud-dotnet#6141]
Application interrupted  during firestoredb instanstance initialization.
The code of initializator;
```
string projectId = configuration["Integration:Firebase:ProjectId"];
var firestoreDbBuilder = new FirestoreDbBuilder
{
    ProjectId = projectId,
    ConverterRegistry = new ConverterRegistry
    {
	    new UserConverter(),
	    new WorkoutConverter(),
	    new ExerciseConverter(),
	    new EquipmentConverter(),
	    new RestrictionConverter(),
	    new RoundConverter(),
	    new ExerciseMetadataConverter()
    }
};

FirestoreDb firestoreDb = firestoreDbBuilder.Build();
```
 or simple initialization:

```
string projectId = configuration["Integration:Firebase:ProjectId"];
FirestoreDb firestoreDb = FirestoreDb.Create(projectId);
```

#### Environment details

  - OS: KUbuntu Linux, Kernel: 5.4.0-67-generic
  - .NET version: 5.0.201
  - Package name and version: google.cloud.firestore 2.3.0

#### Steps to reproduce

  1. Init FirestoreDbBuilder 
  2. Call Build() method of firestore builder
  
  Or
 1. Call FirestoreDb.Create(projectId);

I don't have any logs, since application are crashed. But I'd tried debug and found that error is occured in the method LoadUnmanagedLibrary of class NativeExtension.

**Comment by jskeet** [comment]
I suspect this is due to https://github.com/grpc/grpc/issues/24153

Please try adding a direct dependency on Grpc.Core version 2.36.1 in your project file and see if that fixes the problem. (We haven't updated our dependency yet as earlier fixes caused other problems. It's possible that 2.36.1 is now "good to go" generally but we'll need to do some more testing first.)

**Comment by AlexDevFx** [comment]
@jskeet Thank you. I have added package Grpc.Core version 2.36.1 in the project and it had fixed the problem.
