### ISSUE TITLE
Failed to connect to all addresses

### ISSUE THREAD

**Issue by neil-gok** [googleapis/google-cloud-dotnet#6151]
Unable to query records in Google Firestore

Environment details
OS: Windows 10 Pro
.NET version: .Net Core 3.1
Package name and version: Google.Cloud.Firestore 2.3.0

Steps to reproduce
 Query query = fireStoreDb.Collection(collectionName);
 QuerySnapshot querySnapshot = query.GetSnapshotAsync().GetAwaiter().GetResult();

GetSnapshotAsync() triggers the error. 

Does this happen all the time, or just intermittently? All the time
If you use other Google Cloud APIs, have you seen the same problem with those? I have not used any other Cloud APIs.  
Are you able to test the same code on a different network? Works on home network, not on corporate network.  I did add the proxy environment variables, but still does not work.  Is there any documentation that lists the URLs the library requires access to? 

Error message:
Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1616069718.456000000","description":"Failed to pick subchannel","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\client_channel.cc","file_line":4090,"referenced_errors":[{"created":"@1616069718.456000000","description":"failed to connect to all addresses","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy\pick_first\pick_first.cc","file_line":394,"grpc_status":14}]}")

**Comment by jskeet** [comment]
The Firestore API has an endpoint of `firestore.googleapis.com`. The auth library will (potentially) also need to connect to `accounts.google.com`, but that will be over HTTP/1.1.

**Comment by neil-gokhale** [comment]
Hi Jon, thanks for the quick response!  One more bit of information is that I can connect to firestore.googleapis.com when using Postman, and I know we have that bypasses as a proxy rule.  I have HTTP_PROXY, HTTPS_PROXY, and NO_PROXY defined as environment variables.  I thought this library might be hitting additional URLs, beyond the standard googleapis, which might be causing the proxy to block it.

**Comment by jskeet** [comment]
No, I suspect the problem is that the proxy doesn't support HTTP/2.0. Please contact your system administrator to find out more details of the proxy involved.

**Comment by neil-gokhale** [comment]
It looks like our proxy servers do support http2.

**Comment by jskeet** [comment]
In that case, I can't see any reason why it wouldn't work. I would suggest setting the `grpc_proxy` environment to be absolutely sure, then use monitoring on your proxy to check for connections from a test machine.

(I'd expect it to fail for *any* RPC by the way.)

**Comment by jskeet** [comment]
You might also want to try a different API, just for completeness of diagnostics. Here's a simple test I often use with the Translate v3 API:

```csharp
using Google.Api.Gax.ResourceNames;
using Google.Cloud.Translate.V3;
using System;

class Program
{
    static void Main(string[] args)
    {
        if (args.Length != 1)
        {
            Console.WriteLine("Expected argument: GCP Project ID");
            return;
        }
        string projectId = args[0];

        var client = TranslationServiceClient.Create();
        var response = client.TranslateText(
            parent: LocationName.FromProjectLocation(projectId, "global"),
            targetLanguageCode: "fr-FR",
            contents: new[] { "It's raining" });
        Console.WriteLine(response);
    }
}
```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Cloud.Translate.V3" Version="2.1.0" />
  </ItemGroup>
</Project>
```

Expected output:

```text
{ "translations": [ { "translatedText": "Il pleut", "detectedLanguageCode": "en" } ] }
```

(This assumes the application default credentials are available and the Translate API has been enabled.)

**Comment by neil-gok** [comment]
Same error with the translate api.  I know our proxy servers allow all outgoing traffic over http/1 and http/2.  All of the googleapis.com endpoints have already been added to our transparent proxy, which which bypasses standard proxy altogether.  Is there a possibility that an additional URL is needed for gRPC?

**Comment by jskeet** [comment]
Is there a DMZ in your network where you could test it without the proxy being in the way? It really does sound like it's the proxy blocking it - whether that's through a configuration issue or possibly a fault in the proxy's support for HTTP/2.0 (which is obviously rather newer).

Does the proxy log show anything? Ultimately there's relative little I can do as a client library maintainer - the problem is with the gRPC connection rather than anything within our library itself.

**Comment by jskeet** [comment]
After starting the emulator, set the `FIRESTORE_EMULATOR_HOST` environment variable. Then to build a `FirestoreDb`, use:

```csharp
FirestoreDb db = new FirestoreDbBuilder
{
    ProjectId = projectId,
    EmulatorDetection = EmulatorOnly
}.Build();
```

(Or other values of [`EmulatorDetection`](https://github.com/googleapis/gax-dotnet/blob/master/Google.Api.Gax/EmulatorDetection.cs))

**Comment by neil-gok** [comment]
I agree that this is not an issue with your library, but you still continued to assist.  That is must appreciated.  Closing this issue.

**Comment by neil-gok** [comment]
For the GCloud SDK, I had to specify my Company's CA Cert with the config custom_ca_certs_file.  Is there a way to do this with the Google.Cloud.Firestore library as well?

**Comment by jskeet** [comment]
The complete set of environment variables for gRPC is [here](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md) - I believe you want `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` (assuming this is a PEM file).

**Comment by neil-gok** [comment]
That was the missing step.  I'm now able to get past my corporate proxy.  Thank you.
