### ISSUE TITLE
Firestore Update - Duplicate Record

### ISSUE THREAD

**Issue by neil-gok** [googleapis/google-cloud-dotnet#6302]
#### Environment details

  - OS: Windows 10
  - .NET version: .net Core 3.1
  - Package name and version: Google.Cloud.Firestore 2.3.0

#### Steps to reproduce

  1. Update an existing document creates a new record in the collection

Models

    public class FireStoreBase
    {
        [FirestoreProperty]
        public string Id { get; set; }
    }

    [FirestoreData]
    public class Location : FireStoreBase
    {
   
        [FirestoreProperty]
        public string Building { get; set; }
        [FirestoreProperty]
        public string Name { get; set; }

    }

Repo Methods

        public async Task<List<T>> QueryRecords<T>(Query query) where T : FireStoreBase
        {
            QuerySnapshot querySnapshot = await query.GetSnapshotAsync();
            List<T> list = new List<T>();
            foreach (DocumentSnapshot documentSnapshot in querySnapshot.Documents)
            {
                if (documentSnapshot.Exists)
                {
                    Dictionary<string, object> record = documentSnapshot.ToDictionary();
                    //string json = JsonConvert.SerializeObject(record);
                    //T newItem = JsonConvert.DeserializeObject<T>(json);
                    //newItem.Id = documentSnapshot.Id;
                    list.Add(documentSnapshot.ConvertTo<T>());
                }
            }
            return list;
        }

       public async Task<bool> Update<T>(T record) where T : FireStoreBase
        {
            DocumentReference recordRef = fireStoreDb.Collection(collectionName).Document(record.Id);
            await recordRef.SetAsync(record, SetOptions.MergeAll);
            return true;
        }

      public async Task<Location> GetById(string locationId)
        {
            
            Query query = repo.fireStoreDb.Collection(collectionName).WhereEqualTo(nameof(Location.Id), locationId);

            var location =  await repo.QueryRecords<Location>(query);

            return location.FirstOrDefault();
        }

Unit Test

        [TestMethod]
        public void UpdateRecord()
        {
            var repo = new LocationRepo();

            var record = repo.GetById("28e81c6c-eef5-40fd-938e-f2dcdfcd814f").GetAwaiter().GetResult();

            record.Building = "Test";

            repo.Update(record).GetAwaiter().GetResult();

        }

My unit test attempts to update an existing document, that was created with the Id property set as a Guid.  When I attempt to update the document, a new document with an auto generated ID is created.

**Comment by jskeet** [comment]
I'll have a look at this tomorrow

**Comment by jskeet** [comment]
Your `GetById` method doesn't use the document ID - it uses the `FireStoreBase.Id` property. You haven't shown how anything is being set up, but I strongly suspect that the problem is that the document that contains an `Id` field with value "28e81c6c-eef5-40fd-938e-f2dcdfcd814f" doesn't actually have a *document* ID of "28e81c6c-eef5-40fd-938e-f2dcdfcd814f". So your `Update` method is creating a new document with a document ID of "28e81c6c-eef5-40fd-938e-f2dcdfcd814f".

I would suggest you move away from this "two IDs" approach... I strongly suspect that you'll end up with a lot of confusion.
