### ISSUE TITLE
FirestoreDb.Create() throws exception: Value cannot be null. (Parameter 'path1') when PublishSingleFile=true

### ISSUE THREAD

**Issue by jjdelorme** [googleapis/google-cloud-dotnet#6309]
#### Environment details

  - Base Container Image: mcr.microsoft.com/dotnet/runtime-deps:5.0
  - .NET version: 5.0.200
  - Package name and version:  Google.Cloud.Firestore

#### Steps to reproduce

  1. dotnet new cli
  2. dotnet add package Google.Cloud.Firestore --version 2.3.0
  3. Build an app that calls FirestoreDb.Create(...)
  4. dotnet publish --self-contained true \
        -r linux-x64 \
        -p:PublishTrimmed=True -p:TrimMode=Link \
        /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true
  5. Launch container

This works perfectly fine if not building a .NET self-contained executable.  However, this results in an exception "Value cannot be null. (Parameter 'path1')" for self contained.  It looks like this stems from Grpc.Core as pointed out here:https://github.com/grpc/grpc/issues/24153 and here https://github.com/dotnet/command-line-api/issues/1031

To fix this, I cloned https://github.com/googleapis/google-cloud-dotnet and rebuilt just Google.Cloud.Firestore after updating to the latest version of Grpc.Core 2.36.4 and it worked:

```csharp
Google.Cloud.Firestore.csproj
    <PackageReference Include="Grpc.Core" Version="[2.36.4, 3.0.0)" PrivateAssets="None" />
```

Can the API team bump the underlying Grpc.Core version across these libraries to resolve more broadly?

Thank you!

**Comment by jskeet** [comment]
We're looking at bumping the version of Grpc.Core, but 2.36.4 has some problems when running under .NET 4.6.1 on Windows, at least in test environments. As soon as there's a version of Grpc.Core that we're happy is stable everywhere, we'll release a new version of GAX that relies on that - but it's unlikely that we'd then release *all* the libraries in one go, just to solve a problem that's trivial to work around with a direct dependency. Instead, we'll allow the change to happen organically as we release the libraries to add new features.

**Comment by jskeet** [comment]
Just to be clear, having reread the bottom of the issue - you definitely don't need to rebuild Google.Cloud.Firestore yourself.

You can add a direct dependency on Grpc.Core version 2.36.4 within your C# project (the one that also depends on Google.Cloud.Firestore) and that should be fine. If the only workaround was really to rebuild Google.Cloud.Firestore, that would be a significantly bigger problem.

**Comment by jjdelorme** [comment]
Thanks for clarifying! I see that the PackageReference defines a range ```Version="[2.31.0, 3.0.0)"```, hence if I reference 2.36.4 in my project it will just use that.  Thank you! This should resolve my issue.
