### ISSUE TITLE
remove linq.async from google firestore code

### ISSUE THREAD

**Issue by nafberger** [googleapis/google-cloud-dotnet#6315]
the linq.async package makes it almost imposibble to use the google firestore in a project that uses linq and ef core, this is  a huge impediment. i tried to modify the google code it seems that google async is used in only 3-4 places, can that be done as a side package

**Comment by jskeet** [comment]
I'm extremely reluctant to remove the dependency. I would rather understand what problems it causes, and try to help you work around them.

Even if we use it in relatively few places now, I don't want to tie our hands around not using it more later on, and it's unreasonable to effectively reimplement a lot of it ourselves... and presumably asking the same of any other package you might depend on later on. It would be far better to work out how to use EF Core and System.Linq.Async in the same dependency tree.

Please provide more details about the problems it's causing you, ideally with a complete example.

**Comment by nafberger** [comment]
we have an enterprise application with a lot of queries, thing is as soon we import the google firestore package, which includes linq.async, then all of our queries which use the where linq extension methods stop working because of the ambiguous reference.

I am not sure about the detail but its documented here 

so its not a trivial thing, this problem means that net 5 users cannot use google firestore. a huge painful loss.

https://www.loom.com/share/533ce306ce9a4cfa896fd845da75c8f8

![Screenshot_3](https://user-images.githubusercontent.com/26122027/113948673-6c90e800-97db-11eb-9579-d4a2e01a12b2.png)

**Comment by jskeet** [comment]
I believe there's a simple fix for this.

Instead of:

```csharp
using System.Linq;
```

you just need:

```csharp
using static System.Linq.Queryable;
using static System.Linq.Enumerable; // You only need this if you're using LINQ to Objects
```

I believe that will resolve the problem. (I'd also suggest that "this problem means that net 5 users cannot use Google Firestore" is rather an overstatement. Let's stick to technical statements.)

**Comment by nafberger** [comment]
man, huge thanks, it seems to work. sorry for my emotional outburst, it was after 2 days of struggling to get things right.

**Comment by jskeet** [comment]
Hooray! I completely understand how frustration feels - I'm so glad we've ended up at a good outcome. Will close now.

**Comment by dorathoto** [comment]
This solution is a contour workaround.

Doing this in a big project is absurd, when I include more than 900 errors in my project, there's no way to put using static System.Linq.Queryable; everywhere.

I think it's a package partnership to force migration from .net 6

**Comment by kironiitdu** [comment]
@jskeet  I was having the issue because of using following references together

```
using Microsoft.EntityFrameworkCore;
using System.Data.Entity;
```
I have removed `using System.Data.Entity;` and the error gone. 
![ErrorEntityAmbiguous](https://user-images.githubusercontent.com/35517293/198920379-c533bb83-0dd9-449f-a55b-dc89841eedb7.png)

**Comment by kyledprogrammer** [comment]
> @jskeet I was having the issue because of using following references together
> 
> ```
> using Microsoft.EntityFrameworkCore;
> using System.Data.Entity;
> ```
> 
> I have removed `using System.Data.Entity;` and the error gone. However, your suggestion help me to ponder over.
> 
> ![ErrorEntityAmbiguous](https://user-images.githubusercontent.com/35517293/198920379-c533bb83-0dd9-449f-a55b-dc89841eedb7.png)

This solved my issue
