### ISSUE TITLE
Credentials Missing Method Exception

### ISSUE THREAD

**Issue by dennemark** [googleapis/google-cloud-dotnet#6325]
#### Environment details

  - OS: Windows
  - .NET version: 4.61 & 4.7 (tried both)
  - Package name and version: 
       - Google.Cloud.Storage.V1 (3.4.0)
       - Google.Cloud.Firestore (2.3.1)
       - Newtonsoft.Json (12.0.3 & 13.0.1 tried both)

#### Steps to reproduce

  1. Using latest Google.Cloud.Firestore and Google.Cloud.Storage.V1 versions I run into an issue when using credentials.
  2. If I use `StorageClient storage = new StorageClientBuilder { CredentialsPath = credentials }.Build();` I get this error:
  ```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: "Google.Apis.Auth.OAuth2.GoogleCredential Google.Apis.Auth.OAuth2.GoogleCredential.CreateWithQuotaProject(System.String)".
  Source=Google.Api.Gax.Rest
  StackTrace:
   at Google.Api.Gax.Rest.ClientBuilderBase`1.GetHttpClientInitializer()
   at Google.Cloud.Storage.V1.StorageClientBuilder.Build()
```
Same for FirestoreDbBuilder.

3. If I use GOOGLE_APPLICATION_CREDENTIALS and just use `StorageClient.Create()` or `FirestoreDb.Create(projectid)` I get a different error: 
``` 
'Error reading credential file from location ... : Error deserializing JSON credential data.
Please check the value of the Environment Variable GOOGLE_APPLICATION_CREDENTIALS'
```
(yes the sytem variable is set)
```
MissingMethodException: Method not found: "Void Newtonsoft.Json.JsonSerializerSettings.set_MetadataPropertyHandling(Newtonsoft.Json.MetadataPropertyHandling)".
```

Yesterday I had the same issue and I uninstalled all NuGet Packages. Then I reinstalled Google.Cloud.Firestore. After the issue appeared again, I updated the Newtonsoft.Json and it somehow worked afterwards. But after installing Google.Cloud.Storage.V1 I am facing the same issue again.

I hope someone has a clue?

**Comment by jskeet** [comment]
It sounds very much like the dependencies are out of sync, possibly due to assembly redirects getting broken.

Are you able to use an SDK-style project? I tend to find that sorts out this sort of thing.

If you could provide a complete example project demonstrating the problem, that would be really helpful. (These packages definitely *do* work on .NET 4.6.1 and 4.7... we run integration tests every night, so I'm sure we can get it working.)

**Comment by dennemark** [comment]
thanks for the fast reply! I will try the SDK-style and hope to get back to you tomorrow!

**Comment by dennemark** [comment]
Hi,
I am a bit of a newbie with Visual Studio, so the NuGet journey was already not very successful and a bit disappointing in comparision to my experiences with npm/yarn in JS/TS..  Now I understood the SDK approach as installing Google Cloud SDK and referencing the correct .dll`s from its installation folder. However I am struggling to find the right files. Am I on the right path with my approach? I could not find any description on integrating the SDK into VS yet. Only NuGet approaches...

(I did not install the Cloud Tools for VS since as far as I understand they are used to develop programs that run on the cloud. I currently just try to write a program that runs on my local machine and communicates with my server.)

**Comment by jskeet** [comment]
Ah, no - an SDK-style project is a type of .NET msbuild project (csproj file) which is significantly improved over the old style. Sorry, I'd have been more specific if I'd been aware you're new to .NET.

To check which style of project you're using at the moment, have a look at the Project element in your csproj file:

SDK-style projects:

```xml
<Project Sdk="Microsoft.NET.Sdk">
```

Old-style projects:

```xml
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```

I typically create a project targeting .NET Core (which will always use the SDK-style project) and then set the target framework to "net461" (or whatever) if I want to actually target the .NET Framework.

Can I ask what kind of project you're trying to write? Hopefully we can come up with a simple project file for you which will avoid all the problems.

**Comment by dennemark** [comment]
It is a bit specific for one program to develop visual coding components and it proposes to set up a VS project via this tutorial: https://developer.rhino3d.com/guides/grasshopper/installing-tools-windows/
https://developer.rhino3d.com/guides/grasshopper/your-first-component-windows/

I will see what I can do with your remarks.

**Comment by jskeet** [comment]
Okay, if it's very specific to a particular environment, I'm afraid you'll almost certainly need to ask for guidance in the Rhino support channels as to how Rhino handles assembly binding redirects. (For future reference, it's always worth mentioning unusual aspects of your environment right from the start when raising an issue.)

**Comment by dennemark** [comment]
Thanks! I will!

Concerning the SDK-style after switching project style you would still use NuGet packages correct?

**Comment by jskeet** [comment]
> Concerning the SDK-style after switching project style you would still use NuGet packages correct?

Yes - and the experience is much simpler as the NuGet package reference is directly in the csproj file - no separate packages.config required.

For example, here's a console app csproj file targeting .NET 4.6.1, with the dependencies you listed (but nothing explicit for Newtonsoft.Json as that's implicit via a transitive dependency):

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="2.3.1" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="3.4.0" />
  </ItemGroup>

</Project>
```

That's the *complete* project file, with nothing else required. I suspect if you compare that with your current project file, you'll find this is a lot simpler. However, I've no idea whether that approach is compatible with Grasshopper.

**Comment by dennemark** [comment]
Thanks a lot for your help! I managed to use the sdk style now! Even found a description for using NuGet for my software: https://developer.rhino3d.com/guides/rhinocommon/using-nuget/

Now Visual Studio seems to show me the main reason for my issues: conflicing Newtonsoft.Json versions. I guessed it could be this issue, but thought it was inbetween Google Apis.

Thanks a lot! I will close the issue. Hope it assists some others running into similar problems.

**Comment by dennemark** [comment]
Sorry...I was a bit impatient. Actually I can connect to FirestoreDb via `FirestoreDb db = FirestoreDb.Create(projectId)` using default credentials. However next line is `StorageClient storage = StorageClient.Create()` and it throws this erros: `System.MissingMethodException: 'Methode nicht gefunden: "Initializer Google.Api.Gax.Rest.ClientBuilderBase`1.CreateServiceInitializer()".'` 

Do you have any ideas what this could mean? I tried Google.Cloud.Storage.V1 (3.3.0 and 3.4.0)

**Comment by jskeet** [comment]
That sounds like you still have an incorrect version somewhere - this time of Google.Api.Gax.Rest. I can't see how though, given that `CreateServiceInitializer` has been part of `ClientBuilderBase<T>` since the [very first commit of that type](https://github.com/googleapis/gax-dotnet/commit/266e1a2453a0c68cdbb9501df31797249fa6d03c#diff-aa49a7613a2497eb0ef6be61c596dc06246329c0bf4bcf122095a711751e93f8).

Could you find the copy of `Google.Api.Gax.Rest.dll` that is being used at execution time, and let us the version? (In Windows Explorer if you right-click and select Properties, then go to the Details tab, it should be reported as File Version - at least, those are the English names; I'd expect them to be recognizable in the German version of Windows.) It *should* be using 3.2.0.0.

**Comment by dennemark** [comment]
It states 3.2.0.0.0. 

Now I tried version 3.0.0.0 of `Google.Api.Gax.Rest.dll` and v3.2.0.0 of ``Google.Cloud.Storage.V1`. This throws a different error. Maybe it is helpful in resolving the issue:

`System.ArrayTypeMismatchException`

StackTrace
```
at System.Collections.Generic.List`1.Add(T item)
at Google.Apis.Services.BaseClientService.CreateHttpClient(Initializer initializer, String versionHeader)
at Google.Apis.Storage.v1.StorageService..ctor(Initializer initializer)
at Google.Cloud.Storage.V1.StorageClientBuilder.Build()
```

**Comment by jskeet** [comment]
Okay, 3.2.0.0 is correct. How certain are you that that's the version that's *actually* being used?

More and more, this is sounding like something that's going to be very specific to the unusual execution environment you're in with the plugin - I do think you're more likely to be able to get detailed help in the Grasshopper support, I'm afraid.

**Comment by dennemark** [comment]
Thanks for your help! You are probably right and it is an issue with the software I am using. I will try it through the Grasshopper support. It is a bit unfortunate that I am not able to get more information about the error.
