### ISSUE TITLE
Memory Usage In Queries Under Load in Azure

### ISSUE THREAD

**Issue by quackemi-inmar** [googleapis/google-cloud-dotnet#6326]
I am running a query with the BigQuery client in a queue triggered Azure function.  If I keep the load very small, there are no issues with memory.  However, if I increase the load, the memory will grow over time and will not return to baseline.

#### Environment details

  - OS:  Microsoft Azure Function, running in debug on Windows 10.0.19041 in Visual Studio 2019 v16.9.3
  - .NET version: Core 3.1
  - Package name and version: Google.Cloud.BigQuery.V2 - v2.1.0

#### Steps to reproduce
Below is the code that was being triggered by the queue messages (with our actual table names and such removed for privacy):

```
public async Task GetThing(string source, int clientId)
{
    var beginningWeek = 202046;
    var endWeek = 202105;

    var query = @"
        SELECT
            DISTINCT
            loyalty_id,
            columnB,
            columnC
        FROM
        (
            SELECT 
                loyalty_id,
                COUNT(columnE) AS num_E,
                SUM(columnF) AS sumF
            FROM 
                `mytable` AS mytable
            WHERE 
                year_week >= @startWeek AND year_week <= @endWeek AND
                source = @source AND client_id = @clientId AND 
                columnG IN UNNEST(@listOfThings)
            GROUP BY
                loyalty_id
        ) AS firstTable
        JOIN
            anotherTable ON
            anotherTable.source = @source AND
            anotherTable.client_id = @clientId AND
            firstTable.loyalty_id = anotherTable.loyalty_id AND
            firstTable.num_E > firstTable.sumF 
        ";

   var parameters = new BigQueryParameter[]
    {
        new BigQueryParameter("startWeek", BigQueryDbType.Int64, beginningWeek),
        new BigQueryParameter("endWeek", BigQueryDbType.Int64, endWeek),
        new BigQueryParameter("source", BigQueryDbType.String, source),
        new BigQueryParameter("clientId", BigQueryDbType.Int64, clientId),
        new BigQueryParameter("listOfThings", BigQueryDbType.Array, listOfThings)
    };

    var pageSize = 100000;  //(have also tried 10,000 with the same results)
    var result = await this._bigQueryClient.ExecuteQueryAsync(query, parameters, null,
        resultsOptions: new GetQueryResultsOptions { PageSize = pageSize, StartIndex = 0 });

    string nextPageToken = null;

    do
    {
        var pageResult = await this._bigQueryClient.GetQueryResultsAsync(result.JobReference, new GetQueryResultsOptions { PageToken = nextPageToken });
        var page = await pageResult.ReadPageAsync(pageSize);
        nextPageToken = page.NextPageToken;

    } while (!String.IsNullOrWhiteSpace(nextPageToken));
}
```

The results from this query were relatively small - only about 1.2 MB of total text.  ~22K rows.  

I started out by dropping queue messages from a LinqPad script at a fairly slow rate.  Given that the message takes only a couple of seconds to process, this rate made certain that it could easily keep up.  This script ran for about 19 minutes:
```
while(true)
{
  int sleepInterval = rnd.Next(30000, 60000);
  int numMessages = rnd.Next(1, 5);
  
  for(var i = 0; i < numMessages; i++)
  {
	  SendMessageAsync();
  }
  Thread.Sleep(sleepInterval);
}
```

After 19 minutes the LinqPad script was shut down.  As you can see from this image, the memory stayed small, and recovered to a normal baseline:
![small_load_run](https://user-images.githubusercontent.com/49037240/114076569-cc879d00-9874-11eb-81e1-8a837eb3a527.jpg)

I then changed the LinqPad script so that within the first 1 minute and 11 seconds it dumped 74 messages on to the queue - and then I stopped the script.  The memory jumped to over 3GB (which it won't be able to do once deployed since there is a 1.5 GB limit on Azure).  It finished processing the queue messages within the first 2 minutes.  No further messages were added for the rest of the almost 15 minute run (the other events shown were just Application Insights telemetry checks).  The memory never recovered below 1.8GB.  The memory profile is shown below:
![higher_load_run](https://user-images.githubusercontent.com/49037240/114077926-52581800-9876-11eb-8efe-b4d477067444.jpg)

I have also seen this sort of behavior with the synchronous versions of the client query calls.  This code is not yet ready for deployment, so I have not been able to test it outside of the debugger.  I have noticed occasionally that if you leave the function running for a really long time - say for another half an hour or 45 minutes - the memory will sometimes go back down in to the normal range.  I have also seen it sit for many hours at the higher level and not go down.

**Comment by jskeet** [comment]
It's not quite clear to me what the relationship between the queue is and the BigQuery query you're executing. When you add one message to the queue, does it perform the complete query, or only query for new items?

It feels like we should be able to reproduce the problem without an actual queue being involved, just with a console app that executes the query... after all, it's only the querying app that's running out of memory, right?

I'd be very interested in more information about this aspect:

> The results from this query were relatively small - only about 1.2 MB of total text. ~22K rows.

Where are you getting the "total text" from? Is that the response size, or the total of "if you were to concatenate all the result values"? BigQuery HTTP responses can be quite verbose - I wouldn't be surprised if you found that you were receiving much larger responses. (Having said that, if you've only got three columns per row, there won't be as much overhead as a large number of small columns.)

I suspect memory isn't getting freed up due to objects being allocated on the [Large Object Heap](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap), which isn't compacted.

It would be great if we could reproduce this in a simple console app, taking out the Azure Functions part as well as the triggering queue. I suspect that the join within the query isn't relevant either - if you could provide us a simple schema with sample values (obviously non-sensitive ones - but values which are roughly a representative size) that would be really useful.

**Comment by quackemi-inmar** [comment]
I have done a bunch more digging today.  A console app wasn't really going to re-create the same conditions since Azure functions are inherently multithreaded and console apps are single threaded (unless you write threading code yourself) and therefore creating the same sort of load was going to be a bit of work.  So, rather than going down that path first, I instead looked more at the first suggestion from Amanda.  I had gone down the path of paging because our first experiments with something like this:

```
	var results = await client.ExecuteQueryAsync(query, null);

	await foreach (var row in results.GetRowsAsync())
	{
		// do anything
	}
```
did not seem to lazy load the results (as in the memory did not climb as the loop for results.GetRowsAsync() executed).  I tried again today, but with a MUCH larger result set - and realized that the default page set must be considerably larger than what we were using to test.  It does in fact lazy load it, when I'm returning 1.6 million rows.  

When one does not attempt the paging oneself - the memory is not an issue.  I will therefore chalk this one up to my own error, and will close the issue.
