### ISSUE TITLE
Why there is no way to create `ImageAnnotatorClient` with manually provided credentials?

### ISSUE THREAD

**Issue by TanvirArjel** [googleapis/google-cloud-dotnet#6346]
I am trying to use `ImageAnnotatorClient` for reading text from an image as follows:

```C#
ImageAnnotatorClient client = ImageAnnotatorClient.Create();
IReadOnlyList<EntityAnnotation> response = client.DetectText(image);
```

But what I have figured out that `ImageAnnotatorClient.Create()` method is trying to get the `GOOGLE_APPLICATION_CREDENTIALS` from the environment variable, That's fine but why there is no option to pass it manually by loading from the configuration file as follows:

```C#
GoogleCredential googleCredential = GoogleCredential.FromFile(configuration.GetValue<string>("GoogleCloudCredentialFile.json"));
StorageClient  storageClient = StorageClient.Create(googleCredential);
```

**Comment by jskeet** [comment]
(The reason to not have that directly as a `Create` parameter is that using the builder pattern provides *much* more flexibility for lots of options. Note that the builder pattern is also available for `StorageClient` so you can be consistent between them. The `StorageClient.Create` overload accepting a credential is maintained for backward compatibility.)

**Comment by TanvirArjel** [comment]
Look at the `ImageAnnotatrClient` spelling in your code is correct?

**Comment by jskeet** [comment]
Yes, that was a typo - I hope it was pretty obvious what was meant though.

**Comment by TanvirArjel** [comment]
However, Look at your code again. It should be `ImageAnnotatorClientBuilder` instead of `ImageAnnotatorClient.Builder`, isn't it?

**Comment by jskeet** [comment]
Aha, yes. Thanks for that. (I thought you'd prefer a quick reply that clearly unblocked you, over one that involved creating a project, adding a dependency etc to get it building and prevent typos.)

**Comment by TanvirArjel** [comment]
@jskeet Thank you so much for your prompt responses to the issue.
