### ISSUE TITLE
Service Account Role

### ISSUE THREAD

**Issue by neil-gok** [googleapis/google-cloud-dotnet#6360]
Environment details
OS: Windows 10 Pro
.NET version: .Net Core 3.1
Package name and version: Google.Cloud.Firestore 2.3.0

This just a general question about roles that must be assigned to the service account used by this library.  What is the least privileged role that I can get away with using, while still being able to read/write to Firestore with this library?

**Comment by jskeet** [comment]
This isn't specific to the library at all - we just propagate the credentials to the API. To find out what roles are required for any given API, you'd need to look at the documentation for that API.

I'm afraid I haven't found any documentation explicitly for Firestore in Native Mode roles. The [Firebase IAM page](https://firebase.google.com/docs/projects/iam/permissions) refers to the [Datastore permissions page](https://cloud.google.com/datastore/docs/access/iam#permissions) - I don't know whether that applies to *both* Firestore modes, but it's probably worth trying.

Beyond that, I'm afraid you'll need to go down one of the [Firebase support routes](https://firebase.google.com/support) - the maintainers of this repository don't have detailed knowledge of every supported API.

**Comment by neil-gok** [comment]
Thanks!
