### ISSUE TITLE
Google.Analytics.Data.V1Beta  Web client credentials, desktop credentials

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/google-cloud-dotnet#6397]
I am trying to test the new Google.Analytics.Data.V1Beta api with desktop and web credentials.  The only information i can find on authorization with this library uses a service account.  

Works fine if i have GOOGLE_APPLICATION_CREDENTIALS set to a service account credential file only.

            var client = await BetaAnalyticsDataClient.CreateAsync(CancellationToken.None);

Error from Desktop app credentials. 

>System.InvalidOperationException: Error reading credential file from location C:\dev\credentials.json: Error creating credential from JSON. Unrecognized credential type .
Please check the value of the Environment Variable GOOGLE_APPLICATION_CREDENTIALS
 ---> System.InvalidOperationException: Error creating credential from JSON. Unrecognized credential type .

The cred file 

>{"installed":{"client_id":"REDACTED","project_id":"testapikey-305109","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"REDACTED","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}

I am working on helping some developers who have existing applications which use the reporting api to implement the new GA4 in to their applications.  This needs user permission in order to access the data (OAuth2), it can not be done with service accounts which would only be used by an application which the developer themselves owns.   

Do you have any examples for this library using the other authorization forms?  I was unable to find them everything seems to point to service account authorization method.

I did a bit of digging to ensure that this isn't an API limitation, its possible in NodeJS. [Node Js sample](https://github.com/googleapis/nodejs-analytics-data/blob/master/samples/quickstart_oauth2.js)

**Comment by jskeet** [comment]
You should be able to use any `ICredential` using a builder:

```csharp
ICredential credential = ...;
var client = new BetaAnalyticsDataClientBuilder
{
    TokenAccessMethod = credential.GetAccessTokenForRequestAsync
}.Build();
```

(Note that `credential.GetAccessTokenForRequestAsync` is a method group - the lack of `()` at the end is very deliberate, as we're not trying to call the method here!)

See the [FAQ entry](https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis) for more details

**Comment by LindaLawton** [comment]
@jskeet  you are once again my hero.


Sample for anyone who has this issue in the future.  


```
static async Task SampleRunReport(string propertyId = "YOUR-GA4-PROPERTY-ID")
        {
        
            BetaAnalyticsDataClient client ;
            await using (var stream = new FileStream(PathToCreds, FileMode.Open, FileAccess.Read))
            {
                // Requesting Authentication or loading previously stored authentication for userName
                var credential = GoogleWebAuthorizationBroker.AuthorizeAsync(GoogleClientSecrets.Load(stream).Secrets,
                    new[] { "https://www.googleapis.com/auth/analytics.readonly"},
                    "userName",
                    CancellationToken.None,
                    new FileDataStore("tokenStorage", true)).Result;
                
                client = await new BetaAnalyticsDataClientBuilder
                {
                    TokenAccessMethod = credential.GetAccessTokenForRequestAsync
                }.BuildAsync();
            }

            var request = new RunReportRequest
            {
                Property = "properties/" + PropertyId,
                Dimensions = {new Dimension {Name = "date"},},
                Metrics = {new Metric {Name = "totalUsers"}, new Metric {Name = "newUsers"}},
                DateRanges = {new DateRange {StartDate = "2021-04-01", EndDate = "today"},},
            };

            var response = await client.RunReportAsync(request);


            Console.WriteLine("Report result:");

            foreach (var row in response.Rows)
            {
                Console.WriteLine(
                    $"{row.DimensionValues[0].Value}, {row.MetricValues[0].Value}, {row.MetricValues[1].Value}");
            }
        }
```
