### ISSUE TITLE
Wrong configuration example on the home page of Google.Cloud.Logging.Log4Net

### ISSUE THREAD

**Issue by mrzinger** [googleapis/google-cloud-dotnet#6419]
Steps to reproduce:
1. Open https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Logging.Log4Net/index.html#aspnet
2. Locate  <appender name="CloudLogger" type="Google.Logging.Log4Net.GoogleStackdriverAppender,Google.Cloud.Logging.Log4Net"> in the web.config example.

The type attribute must be Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender but instead is Google.Logging.Log4Net.GoogleStackdriverAppender. Which leads to runtime error in case if you use the proposed configuration.

**Comment by jskeet** [comment]
Will fix this on Tuesday. (Monday is a public holiday in the UK.) Thanks for letting us know.
