### ISSUE TITLE
Google Protobuf

### ISSUE THREAD

**Issue by neil-gok** [googleapis/google-cloud-dotnet#6420]
Not sure if this is the right avenue for this, but any advice would be appreciated.  

There is a critical vulnerability with the Google.Protobuf package being used (v 3.13.0).  This is preventing us from deploying an app that is leveraging Google.Cloud.Firestore into our Production environment, since there is a dependency to the Google.Protobuf package.  Google.Protobuf version 3.14.0 remediates this vulnerability.  When will Google.Cloud.Firestore will be updated to pick up the new version of Google.Api.Gax.Grpc.GrpcCore which has Google.Protobuf as a dependancy?  

We use JFrog Artifactory to scan dependencies, and the vulnerability report shows the following "Protocol buffers (protobuf) contains an unspecified flaw in the parser that is triggered when operating with codedinputstream. this may allow an attacker to have an unspecified impact. no further details have been provided by the vendor."

**Comment by jskeet** [comment]
I wasn't aware of that vulnerability before, but as it happens we're releasing a bunch of updates anyway at the moment.

You don't have to wait though - it's fine for you to take an explicit dependency on Google.Protobuf 3.15.8 (the latest stable version) within your application, and that will be used by the application (including being used by all the libraries that were built against 3.13.0).

**Comment by jskeet** [comment]
Please could you comment on whether this advice is sufficient for you? If it is, I'll close the issue and let the Firestore release happen at an appropriate time (which may well be within the next two weeks anyway). If it doesn't solve your problem, I'll prioritize a Firestore release.

**Comment by neil-gok** [comment]
This solved me issue.  Thank you for the reply!
