### ISSUE TITLE
Spanner: Retry Transaction Outcome Unknown errors

### ISSUE THREAD

**Issue by olavloite** [googleapis/google-cloud-dotnet#6421]
Cloud Spanner can return the error `Transaction Outcome Unknown` if a transaction fails with an unknown transient reason. It is safe to retry the entire transaction when this error is returned, even though the error message indicates that the outcome is inconclusive. The specific error should therefore be added to the conditions for retrying a transaction. Currently, only `Aborted` errors cause an entire transaction to be retried.

cc @skuruppu

**Comment by amanda-tarafa** [comment]
I've changed this to a feature request, the original spec we got only included `Aborted` as a retryable error.

**Comment by olavloite** [comment]
After an internal discussion, the decision has been made not to automatically retry these errors.
