### ISSUE TITLE
API Connection status test extension

### ISSUE THREAD

**Issue by damikun** [googleapis/google-cloud-dotnet#6441]
It can be helpful if API provides an out-of-box kind of connection test function..

 **Can be:**
- Health check
- Ping
- Dummy Open/Close

Usually, some API require to have this test function to validate if the client can connect with current setup.. I use this for example with ElasticSearch or Fileserver like S3 to verify I'm able to open the connection... These services provide this as an API function builded-in...

I think this can be exposed from the underlying GRPC client... But there is nothing I can use just call it with some dummy image but that is not really the way I wanna do..

What do you think?

**Comment by jskeet** [comment]
Could you clarify what you mean by "I think this can be exposed from the underlying GRPC client"?

**Comment by damikun** [comment]
Hi.. I mean I can see that object of GRPC_Client is part of `client` and the idea was to extend it by a new API client function to Test connection... I cannot see the details of client implementation since it comes from a different API (link to  gax..)  But I believe this API provides a mechanism for opening the channel and sending the data... It can just open a channel or send a dummy greeting message.. But that is more for implementation of backend if this kind of health/greeting messages exists there...

**Comment by jskeet** [comment]
There isn't always a channel involved - we end up with a `CallInvoker` when constructing the client, but we don't even have that afterwards. Basically the layers of abstraction really don't encourage this - I'm not even sure what we'd do if we had a full `Grpc.Core.Channel`. I *suspect* this is basically infeasible, I'm afraid... I can have a poke around, but I'm dubious I'm afraid.

**Comment by jskeet** [comment]
I'm afraid I believe this to be infeasible - I'll close the issue now. Thanks for the suggestion though, and I'll keep it in mind in case I see an opportunity in the future. (I agree it would be useful.)

**Comment by greg-signi** [comment]
I'm working on a new healthcheck to check if we have a valid connection to SecretManager, I was probing an saw this closed issue, I'm guessing creating a out-of-the-box healthcheck is still not feasible.

Just wondering if you have any suggestions for how to make it on our side... Do you think a ping to the default endpoint would suffice ? 

`public static string DefaultEndpoint { get; } = "secretmanager.googleapis.com:443";`

**Comment by jskeet** [comment]
@greg-signi: If you want to know whether or not you can make an RPC, that's what you should try. It's entirely possible that you could successfully ping, but not make an RPC, or vice versa.

If you know a suitable project, potentially based on the credentials, you could use `SecretManagerServiceClient.ListSecrets`. Make sure you iterate over the result though, as list operations are evaluated lazily.

If you *don't* know a suitable project name, you could potentially use one that you know to be "bad", and expect to get a particular "no such resource" or "forbidden" exception (as opposed to anything indicating a connection issue).

**Comment by greg-signi** [comment]
Alright! I will do both cases. Thank you for your advice.
