### ISSUE TITLE
Firestore - Incorrect Record Count

### ISSUE THREAD

**Issue by neil-gok** [googleapis/google-cloud-dotnet#6473]
#### Environment details

  - OS: Windows 10 Pro
  - .NET version: .net 5.0
  - Package name and version: Google.Cloud.Firestore 2.3.1

#### Steps to reproduce

When I query all records in a collection of >24K records, only approx 6k of those records are returning using the Firestore library.  We do not have any filtering in place.  

Please see code below

 public async Task<List<T>> GetAll<T>() where T : FireStoreBase
        {
         

            Query query = fireStoreDb.Collection(collectionName);

            QuerySnapshot querySnapshot =  await query.GetSnapshotAsync();
            List<T> list = new List<T>();
            foreach (DocumentSnapshot documentSnapshot in querySnapshot.Documents)
            {
                if (documentSnapshot.Exists)
                {
                    Dictionary<string, object> record = documentSnapshot.ToDictionary();                    
                    T newItem = documentSnapshot.ConvertTo<T>();
                    newItem.Id = documentSnapshot.Id;
                    list.Add(newItem);
                }
            }
            return list;
        }

       [TestMethod]
        public void GetAll()
        {
            var locationRepo = new LocationRepo();
            var locations = locationRepo.GetAll().GetAwaiter().GetResult();
            
        }

Is there a configuration setting that limits the number of records that the library will return, or am I doing something wrong when querying the data?  

Thanks!

**Comment by jskeet** [comment]
I'm not aware of any limit. I'll attempt to reproduce this locally (it'll be tomorrow, UK time).

**Comment by jskeet** [comment]
Okay, I can't reproduce this. Here's some code which either generates or queries as many documents as you want - I've just tried it with 25,000 documents, and it was fine.

```csharp
using Google.Cloud.Firestore;
using System;
using System.Diagnostics;
using System.Threading.Tasks;

namespace Issue6473
{
    class Program
    {
        static async Task Main(string[] args)
        {
            if (args.Length != 3)
            {
                Console.WriteLine("Expected arguments: project-id collection-id count");
                return;
            }
            string projectId = args[0];
            string collectionId = args[1];
            int count = int.Parse(args[2]);
            var db = FirestoreDb.Create(projectId);
            var collection = db.Collection(collectionId);
            // Optionally comment out one of these to only take one action
            await GenerateDocuments(collection, count);
            await QueryDocuments(collection);
        }

        static async Task GenerateDocuments(CollectionReference collection, int count)
        {
            for (int batchNumber = 0; count > 0; batchNumber++)
            {
                int batchSize = Math.Min(count, 100);
                var batch = collection.Database.StartBatch();
                for (int i = 0; i < batchSize; i++)
                {
                    batch.Create(collection.Document(), new { batch = batchNumber, item = i });
                }
                await batch.CommitAsync();
                Console.WriteLine($"Committed batch {batchNumber}");
                count -= batchSize;
            }
        }

        static async Task QueryDocuments(CollectionReference collection)
        {
            var stopwatch = Stopwatch.StartNew();
            var snapshot = await collection.GetSnapshotAsync();
            Console.WriteLine($"Query returned {snapshot.Documents.Count} documents in {(int)stopwatch.ElapsedMilliseconds}ms");
        }
    }
}
```

Please could you try this code yourself? If that works for you, could you try using it to query one of your existing collections?

**Comment by neil-gok** [comment]
I think this might be our proxy server.  Thanks for the response.
