### ISSUE TITLE
Firestore - Project Id

### ISSUE THREAD

**Issue by neil-gok** [googleapis/google-cloud-dotnet#6576]
This is just a general question about the Firestore Library (Google.Cloud.Firestore 2.3.1).  When creating a new FirestoreDb object, I keep receiving an error stating that "ProjectId cannot be null".  However, I'm wondering why a Project Id is required when the project Id is also included in the service account key file.  Is there a way to tell the library to use the value in the key file, instead of passing it in to the Create method?  

FirestoreDb.Create()

**Comment by jskeet** [comment]
The credential used to connect isn't always a service account.

When running on GCP, the project ID is auto-detected from the metadata server, but there's no equivalent when the deployment isn't on GCP.

If you know that your code *will* always have a service account key, you could get that credential yourself using `GoogleCredential.GetApplicationDefault()`, use the `UnderlyingCredential` property and cast it to `ServiceAccountCredential`, then extract the project ID from that, but we don't do that in the library at the moment.

**Comment by neil-gok** [comment]
Thank you.
