### ISSUE TITLE
move to grpc-dotnet

### ISSUE THREAD

**Issue by xanscale** [googleapis/google-cloud-dotnet#6578]
[grpc Csharp Future](https://grpc.io/blog/grpc-csharp-future/)

grpc-dotnet (the Grpc.Net.Client and Grpc.AspNetCore.Server nuget packages) is now the recommended gRPC implementation for .NET/C#. The original gRPC C# implementation (the Grpc.Core nuget package) will enter maintenance mode and won’t be getting any new features and will only receive important bug fixes and security fixes going forward. The ultimate plan is to phase out Grpc.Core completely at some point in the future. This announcement describes the reasons why we have decided to do so and lays out the plan in more detail.

**Comment by jskeet** [comment]
Yes, we're aware of this (and helped write that blog post). We're expecting to move to the Grpc.Net.Client as the default dependency in the next major version of GAX, then migrating all the client libraries to that version too. I don't have an ETA for that, but it's on our radar so I'll close this issue now.

**Comment by xanscale** [comment]
i think we can use SDK also in UWP app if it moved to grpc-dotnet

**Comment by jskeet** [comment]
@xanscale: While that may be technically possible, I doubt that we'd want to make UWP a fully supported environment without spending significant resources in testing it.

**Comment by Ducki** [comment]
Is there any temporary workaround for this? Because a compiled app for linux-arm seems to fail to run because of this (using the Speech API).
See https://github.com/grpc/grpc/issues/23566#issuecomment-662479880

**Comment by jskeet** [comment]
You can add a dependency on `Google.Api.Gax.Grpc.GrpcNetClient`, and then when you build a client, use the client builder and specify the `GrpcAdapter` property to be a `GrpcNetClientAdapter`.
I don't know for sure whether that will avoid Grpc.Core being initialized (and thus failing), but it *may* do...

**Comment by xanscale** [comment]
@jskeet unfortunately `Google.Api.Gax.Grpc.GrpcNetClient` requires .NET Standard 2.1 but UWP support up to 2.0

so there isn't any workaround for UWP ?

**Comment by jskeet** [comment]
@xanscale: Not for the APIs in this repo, no. To reiterate: **UWP is not a supported platform for these libraries**. You could potentially use the `Google.Apis.*` NuGet packages, which don't use gRPC, but again, UWP isn't a supported platform for those either.

**Comment by trebor678** [comment]
Just in case anyone was wondering, the above works for Linux arm.

```
var builder = new Google.Cloud.Firestore.V1.FirestoreClientBuilder();
builder.GrpcAdapter = Google.Api.Gax.Grpc.GrpcNetClient.GrpcNetClientAdapter.Default;

db = FirestoreDb.Create("XXX", builder.Build());
```

**Comment by noseratio** [comment]
Apologies for reviving this thread. Are there still plans in place to migrate `Google Cloud Libraries for .NET` to `Grpc.Net.Client`, away from `Grpc.Core.Api` ?

The current version of the package, [`1.0.0-beta48`](https://www.nuget.org/packages/Google.Cloud.AIPlatform.V1Beta1/1.0.0-beta48) at the time of writing, still depends on the latter:

<img width="2239" height="787" alt="Image" src="https://github.com/user-attachments/assets/a88f74d2-adb9-405b-b1e4-3f1fac25e331" />

**Comment by jskeet** [comment]
@noseratio: There's never been a plan to migrate away from `Grpc.Core.Api`. The `Grpc.Net.Client` package itself depends on `Grpc.Core.Api` indirectly (via `Grpc.Net.Common`). The point of the migration was to stop requiring `Grpc.Core`, which is entirely different.

**Comment by noseratio** [comment]
@jskeet, oh, good point, thank you. I should've dug deeper, and I've made an effort now. To sum up:

- Targeting net462 -> we transitively pull `Grpc.Core` ([the legacy one](https://www.nuget.org/packages/grpc.core/)).

- Targeting netstandard2.0 ->  we use `Grpc.Net.Client`/`Grpc.Core.Api` instead, no `Grpc.Core`.  

Is this correct? Thanks again!

**Comment by jskeet** [comment]
Yes, that's right. See https://cloud.google.com/dotnet/docs/reference/help/transports for some more details.
