### ISSUE TITLE
Question about Compute Engine API Instance resource Disks, Labels, and NetworkInterfaces fields 

### ISSUE THREAD

**Issue by alexchao1995** [googleapis/google-cloud-dotnet#6582]
I'm working on a feature for my team where we want to have a service be able to create a VM instance in Compute Engine through the GCP API. While adding a call to InstancesClient InsertAsync [method](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Compute.V1/api/Google.Cloud.Compute.V1.InstancesClient.html#Google_Cloud_Compute_V1_InstancesClient_InsertAsync_System_String_System_String_Google_Cloud_Compute_V1_Instance_Google_Api_Gax_Grpc_CallSettings_), I noticed in the Instance class the [Disk](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Compute.V1/api/Google.Cloud.Compute.V1.Instance.html#Google_Cloud_Compute_V1_Instance_Disks), [Label](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Compute.V1/api/Google.Cloud.Compute.V1.Instance.html#Google_Cloud_Compute_V1_Instance_Labels), and [NetworkInterfaces](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Compute.V1/api/Google.Cloud.Compute.V1.Instance.html#Google_Cloud_Compute_V1_Instance_NetworkInterfaces) fields are all read only and I'm unable to initialize them when creating an Instance object. This poses a problem for me since when my service creates a VM instance we want to be able to allow custom images from a users account to be used to create an instance, a user to define specific labels for an instance, etc. So I want to understand why are these fields read only? Is there a plan to make those fields support set operation? 

For what its worth, I previously had used the Google.Apis.Compute.v1 SDK and the [Disks](https://googleapis.dev/dotnet/Google.Apis.Compute.v1/latest/api/Google.Apis.Compute.v1.Data.Instance.html#Google_Apis_Compute_v1_Data_Instance_Disks), Label, and NetworkInterfaces fields all supported set operations and thus I was able to create Instances with custom Images, Networks, and Labels.

**Comment by jskeet** [comment]
Although the properties are read-only, the collections returned by them are mutable. You can *absolutely* populate them with custom images etc.

See [this FAQ entry](https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-modify-repeated-fields-and-maps-in-protobuf-messages) for more details.

**Comment by alexchao1995** [comment]
I overlooked that, thanks for the help!
