### ISSUE TITLE
Google.Cloud.TextToSpeech.V1 2.2.0 dependency chain broken

### ISSUE THREAD

**Issue by mysticfakir** [googleapis/google-cloud-dotnet#6583]
#### Environment details

  - OS: Windows 10
  - .NET version: 4.0
  - Package name and version: Google.Cloud.TextToSpeech.V1 2.2.0

#### Steps to reproduce

  1. Install package (and dependencies)

Issue is that the dependency chain is broken. 
Dependency Google.Api.Gax.Grpc.3.3.0 has strong reference to Google.Apis.Auth 1.48.0.0
Dependency Grpc.Auth has strong reference to Google.Apis.Auth 1.46.0.0

Due to this the dependency requirements can never be met and Assembly can not be loaded.

**Comment by jskeet** [comment]
We don't support .NET 4.0 (and neither does Microsoft). I'm not sure what you mean by "strong reference" but I've just tried  Google.Cloud.TextToSpeech.V1 2.2.0 in both a .NET 4.6.1 (the oldest version of the .NET Framework we support) and .NET Core 3.1, and it worked fine in both places.

For the .NET 4.6.1 project, an assembly binding redirect was generated automatically:

```xml
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.48.0.0" newVersion="1.48.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

... that resolves absolutely fine.

I don't think there's any problem here.

**Comment by mysticfakir** [comment]
By strong reference, i mean that it is requiring the exact versions listed in my OP. Not sure why this is. I have looked up the dependencies on NuGet and they say for Grpc.Auth, >=1.46 and Google.Api.Gax.Grpc >=1.48. 
Not sure why my NuGet is not resolving these dependency requirements but it doesn't seem to be an issue with the package.
