### ISSUE TITLE
Request UWP App Support

### ISSUE THREAD

**Issue by xanscale** [googleapis/google-cloud-dotnet#6587]
Using this SDK for UWP App compiled **only for x86 and x64** works perfectly on developer PC but when we send to the store we receivce this error.

i think can be fixed just replacing grpc native with grpc-dotnet.

we has completed development of 3 App (Android, iOS and UWP) and now we are stuck and don't know what to do.

-------------------------------------------------------------
Supported APIs
Error Found: The supported APIs test detected the following errors:

- API WSACleanup in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API WSAGetLastError in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API WSASetLastError in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API WSAStartup in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API bind in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API closesocket in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API connect in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API getpeername in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API getsockname in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API htonl in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API htons in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API listen in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API ntohl in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API ntohs in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API setsockopt in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API socket in wsock32.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API SymFromAddr in dbghelp.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API SymInitialize in dbghelp.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.
- API SymSetOptions in dbghelp.dll is not supported for this application type. grpc_csharp_ext.x86.dll calls this API.

Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements.
How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Microsoft Store apps. Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these environments may pull in unsupported APIs. Retest your app in a release configuration, and with .NET Native enabled if applicable.

**Comment by jskeet** [comment]
We don't currently support UWP, and even if using grpc-dotnet makes it technical work, it's unlikely that we will prioritize UWP support over other work. So when we *have* moved over to grpc-dotnet by default, you may be in a situation where you can try to use the libraries and quite possibly be successful, but we would still not support it.

Obviously we'd *like* to support the libraries in as many environments as possible, but we have limited resources and need to prioritize this alongside a lot of other work. I'm sorry this obviously isn't the answer you'd like to get, but I'm afraid it's the way of the world :(

**Comment by jskeet** [comment]
Closing after discussion with colleagues.

You *may* find that the REST-based libraries for whichever APIs you're using (packages starting "Google.Apis") work, but again those aren't actually *supported* on UWP.
