### ISSUE TITLE
Get more than 1 results on image web matches

### ISSUE THREAD

**Issue by ChoOo7** [googleapis/google-cloud-dotnet#6610]
Hello

From
https://github.com/googleapis/google-cloud-dotnet/blob/41094ed98f5e00e8741cb04ca7a5067059a1ff96/apis/Google.Cloud.Vision.V1/Google.Cloud.Vision.V1.Snippets/ImageA
nnotatorClientSnippets.cs#L351

How can i get more than 10 results ?
Is possible according to the documentation of the REST API
https://cloud.google.com/vision/docs/detecting-web#vision_web_detection_gcs-drest

Thanks

**Comment by jskeet** [comment]
You can create an `AnnotateImageRequest` with more information. I'm not on a suitable machine right now, but it would be something like:

```csharp
var request = new AnnotateImageRequest
{
    Image = image, // However you'd create this before
    Features = { new Feature { MaxResults = 1000, Type = Feature.Types.Type.WebDetection } }
}
var response = client.Annotate(request);
var webResults = response.WebDetection;
```

**Comment by jskeet** [comment]
Closing as I believe this is resolved. Please add a comment if this has not resolved your issue.

**Comment by ChoOo7** [comment]
Sorry for the delay
Thanks for your help, it's fine

Have a good day
