### ISSUE TITLE
Firestore SetAsync requires to have en existing document

### ISSUE THREAD

**Issue by pblachut** [googleapis/google-cloud-dotnet#6611]
According to the [documentation and language sample,](https://cloud.google.com/firestore/docs/manage-data/add-data#c), `SetAsync` should create a document if it doesn't exist or update it in a selected way (depending on which option is selected).

After quick tests, it looks that a document must exist before using `SetAsync`.

Not sure if am right but, looks like an incorrect precondition is used here?
https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/WriteBatch.cs#L212

Instead of `Precondition.None`, null is passed.

Example that triggers problem:
```csharp
var reference = firestore
       .Collection(CountriesCollection)
       .Document(id)
                                       
await reference.SetAsync(
         new SomeDocument
         {
               SomeId= evt.Id
         }, cancellationToken: token);

```

**Comment by jskeet** [comment]
I can't reproduce the problem. Here's a complete console app which successfully creates a document:

```csharp
using Google.Cloud.Firestore;
using System;
using System.Threading.Tasks;

namespace Issue6611
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string projectId = args[0];
            var db = FirestoreDb.Create(projectId);
            var reference = db
                .Collection("Issue6611")
                .Document(Guid.NewGuid().ToString());

            await reference.SetAsync(new { TestValue = "test" });
        }
    }
}
```

Without knowing what error you're seeing, or what `evt` is or the declaration of `SomeDocument`, it's hard to tell what's wrong - but I don't see any sign the `SetAsync` has any problems.

**Comment by pblachut** [comment]
Ok, never mind, it was a problem on my side. Sorry for bothering you.
