### ISSUE TITLE
Error `symbol not found` when using `-p:PublishSingleFile=true`

### ISSUE THREAD

**Issue by mathieu-benoit** [googleapis/google-cloud-dotnet#6654]
We can't use `-p:PublishSingleFile=true` to optimize the size of the app because we got at runtime those errors:
```
Error relocating /usr/lib/libgssapi_krb5.so.2: explicit_bzero: symbol not found
Error relocating /usr/lib/libgssapi_krb5.so.2: secure_getenv: symbol not found
Error relocating /usr/lib/libkrb5.so.3: explicit_bzero: symbol not found
Error relocating /usr/lib/libkrb5.so.3: secure_getenv: symbol not found
Error relocating /usr/lib/libk5crypto.so.3: explicit_bzero: symbol not found
Error relocating /lib/libcom_err.so.2: secure_getenv: symbol not found
Error relocating /usr/lib/libkrb5support.so.0: explicit_bzero: symbol not found
```

The command below in my `Dockerfile` is working fine: 
```
dotnet publish myproject.csproj \
-r linux-musl-x64 \
--self-contained true \
-c release
```
But as soon as I add  `-p:PublishSingleFile=true` I got the issue at runtime described above.

FYI: I use the following container base image with which I run my app into `FROM mcr.microsoft.com/dotnet/runtime-deps:5.0.7-alpine3.13-amd64`.

Here is how looks like `myproject.csproj`:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Cloud.PubSub.V1" Version="2.5.0" />
  </ItemGroup>
</Project>
```

I found this former issue #6309 talking about `PublishSingleFile` but the resolution is not working in my case, JFYI.

**Comment by jskeet** [comment]
I *suspect* this is another gRPC issue rather than an issue in the code in this repo.

Could you try the minimal repro in https://github.com/grpc/grpc/issues/25208 and see if that displays the same problem? If you could try with Grpc.Core versions 2.38.0 and 2.38.1, that would be great.

**Comment by mathieu-benoit** [comment]
Gotcha thanks @jskeet for the guidance and pointer, I just filed this new issue there https://github.com/grpc/grpc/issues/26538 because based on the code you shared, I was able to to my own minimal setup to reproduce the issue with `Grpc.Core`.

Closing that current issue as the issue is in the https://github.com/grpc repo, thanks again!
