### ISSUE TITLE
In InstancesClient how does SetMetadataAsync work to notify the VM instance to run a newly added startup script?

### ISSUE THREAD

**Issue by alexchao1995** [googleapis/google-cloud-dotnet#6665]
I'm writing a function in a service that creates a VM instance in GCP Compute Engine. Afterwards the function does a few more computations before it makes a call to SetMetadataAsync to add a startup script under the windows-startup-script-ps1 key. My code roughly looks like the below:

```
// There's code above here that creates an Instance object
await machineClient.InsertAsync(ProjectId, Zone, instance, cancellationToken);

... // There's more code here I didn't include that does more computations.

instance = await machineClient.GetAsync(ProjectId, Zone, instance.Name, cancellationToken);
var metadata = new Metadata
{
    Fingerprint = instance.Metadata.Fingerprint,
    Items = 
    {
        new Items
        {
            Key = "windows-startup-script-ps1",
            Value = string.Join('\n', script) //script is a list of strings
        }
    }
};

await machineClient.SetMetadataAsync(PProjectId, Zone, instance.Name, metadata, cancellationToken);
```

My code works and the startup script is executed and installs the needed software. As stated in the title, I'm wondering what is the process that occurs in between a new startup script being added to a VM's metadata and the VM instance running the script. 

I've looked through the [docs](https://cloud.google.com/compute/docs/instances/startup-scripts/windows#passing-directly) on adding startup scripts to Windows VMs and the code bases ([compute-image-windows](https://github.com/GoogleCloudPlatform/compute-image-windows) [guest-agent](https://github.com/GoogleCloudPlatform/guest-agent)) for running the Windows agent and scripts, but can't seem to get any insight.

**Comment by jskeet** [comment]
@alexchao1995: I'm afraid the maintainers of this repository can't really be of much help on this front. We know how the libraries work, and can deal with any issues around *how* to make requests, but we don't have expertise in the details of how each individual API works. I would strongly advise following one of the [Compute-specific support routes](https://cloud.google.com/compute/docs/support) to ask for more details as to how all of this behaves.

**Comment by alexchao1995** [comment]
@jskeet I see, thanks for the response.
