### ISSUE TITLE
`grpc-dotnet` versus `Grpc.Core`

### ISSUE THREAD

**Issue by mathieu-benoit** [googleapis/google-cloud-dotnet#6671]
What's the position of this repo regarding the recent announcement [The future of gRPC in C# belongs to grpc-dotnet](https://grpc.io/blog/grpc-csharp-future/).

> TL;DR grpc-dotnet (the `Grpc.Net.Client` and `Grpc.AspNetCore.Server` nuget packages) is now the recommended gRPC implementation for .NET/C#. The original gRPC C# implementation (the `Grpc.Core` nuget package) will enter maintenance mode and won’t be getting any new features and will only receive important bug fixes and security fixes going forward.

**Comment by jskeet** [comment]
We expect to move to Grpc.Net.Client with the next major version of Google.Api.Gax.Grpc - we're likely to plan that in Q3 and start work in Q4, expecting to actually execute the migration in 2022.

Note that you can already use Grpc.Net.Client with the packages in this repo using the GrpcAdapter property of the client builder - but we haven't exactly advertised it widely...

**Comment by jskeet** [comment]
(Closing in the expectation that this is all the information required.)

**Comment by mathieu-benoit** [comment]
Thanks for the info @jskeet!
