### ISSUE TITLE
CloudTraceExtensions.TryAddGoogleTraceContextProvider is missing

### ISSUE THREAD

**Issue by EatonZ** [googleapis/google-cloud-dotnet#6672]
Hi,

I upgraded to Google.Cloud.Diagnostics.AspNetCore3 4.3.0-beta01 and have had to make a few changes to my code to accommodate various obsoletions and changes.

I have this code in my `ConfigureServices` method:
`services.AddSingleton<ITraceContext>(new GoogleTraceProvider());`

In the beta this no longer compiles. It tells me to: "Use CloudTraceExtensions.TryAddGoogleTraceContextProvider instead."

That method does not seem to exist.

**Comment by jskeet** [comment]
Thanks for the report - I'll have a look on Monday. It's possible that the message should just be changed to "Use CloudTraceExtensions.AddGoogleTrace instead" - that method definitely *does* exist.

**Comment by amanda-tarafa** [comment]
It's here https://github.com/googleapis/google-cloud-dotnet/blob/ceb62cbb84ff22b9d1c1f94c0b298d2dbc32c3ee/apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Trace/CloudTraceExtension.cs#L157

**Comment by EatonZ** [comment]
@amanda-tarafa Is it not in this beta? There is only 1 `CloudTraceExtensions` class showing up and it looks like this:

![ggl](https://user-images.githubusercontent.com/3020941/123518127-7e638800-d672-11eb-85f6-92ec3c5f144c.PNG)

**Comment by jskeet** [comment]
@EatonZ: That's a different class - the one Amanda pointed to before is in Google.Cloud.Diagnostics.AspNetCore

**Comment by EatonZ** [comment]
@jskeet I figured it out now.
The obsoletion suggested this: `CloudTraceExtensions.TryAddGoogleTraceContextProvider`
When it should be this: `CloudTraceExtension.TryAddGoogleTraceContextProvider`

There is a CloudTraceExtension**s** and a CloudTraceExtension class.
IntelliSense didn't pick up the non-s version immediately.

**Comment by amanda-tarafa** [comment]
Ah yes, sorry for the confusion. I'll update the Obsolete suggestion to include the full namespace and remove the s.

The class in Common is new so I named it with the usual naming convention, with the s. The one in AspNetCore* it's older and changing the name now to include the s would be breaking.
