### ISSUE TITLE
FireStore: Nested class array converter issue/question

### ISSUE THREAD

**Issue by AudriusZemys** [googleapis/google-cloud-dotnet#6751]
Hi,

I've been trying to put documents to Firestore using my .NET Core app. Everything works fine using Dictionary, but I've been receiving exceptions when I try to Set a value of my own custom object: 

> System.ArgumentException: Unable to create converter for type App.Models.Firestore.Foo

The model looks like this:
```

    [FirestoreData]
    public class Document
    {
        [FirestoreProperty]
        public string Id { get; set; }

        [FirestoreProperty]
        public string Prop0 { get; set; }

        [FirestoreProperty]
        public string Prop1 { get; set; }

        [FirestoreProperty]
        public string Prop2 { get; set; }

        [FirestoreProperty]
        public string Prop3 { get; set; }

        [FirestoreProperty]
        public List<Foo> Prop4 { get; set; } // this property is responsible for the exception

        [FirestoreProperty]
        public string[] Prop5{ get; set; }

        [FirestoreProperty]
        public string[] Prop6 { get; set; }

        [FirestoreProperty]
        public int Prop7 { get; set; }

        [FirestoreProperty]
        public string[] Prop8 { get; set; }
    }

    public class Foo
    {
        [FirestoreProperty]
        public string Prop9 { get; set; }

        [FirestoreProperty]
        public string Prop10 { get; set; }

        [FirestoreProperty]
        public string[] Prop11 { get; set; } // This object is in a List, it contains array elements.

        [FirestoreProperty]
        public DateTime StartDate { get; set; }

        [FirestoreProperty]
        public DateTime? EndDate { get; set; }
    }
```
What I have read on docs (https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/datamodel.html) that:

> Array elements cannot themselves be arrays

I then created a custom converter:
```
    public class CustomConverter<T> : IFirestoreConverter<T>
        where T : new()
    {
        public T FromFirestore(object value)
        {
            throw new NotImplementedException();
        }

        public object ToFirestore(T value)
        {
            Dictionary<object, object> result = new Dictionary<object, object>();
            foreach (var property in typeof(T).GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                if (property.PropertyType.IsArray)
                {
                    var arrProp = (Array)property.GetValue(value);
                    for (int i = 0; i < arrProp.Length; i++)
                    {
                        result.Add(i, arrProp.GetValue(i));
                    }
                    return result;
                }
            }

            return typeof(T)
                        .GetProperties(BindingFlags.Public | BindingFlags.Instance)
                        .ToDictionary(propertyInfo => propertyInfo.Name, propertyInfo => propertyInfo.GetValue(value));
        }
```

I've registered it at `FireStoreDbBuilder`, tried playing with applying it to both inner array attributes and the outter array attributes - I still get the same exception. This might be a stupid question, apologies in advance, but I cannot reach my converter while debugging. Still a little bit confused with how these converters work...

The code I use to set a document in FireStore is simple:
```
    public class FirestoreService : IFirestoreService
    {
        FirestoreDb _firestore;

        public FirestoreService()
        {
            _firestore = new FirestoreDbBuilder
            {
                ProjectId = "my-project",
                ConverterRegistry = new ConverterRegistry { new CustomConverter<Foo>() }
            }.Build();
        }

        public async Task AddDocumentAsync(Document document)
        {
            var document = _firestore.Collection("docs").Document(document.Id);
            await document.SetAsync(document);
        }
    }
```

I'd greatly appreciate any kind of support, directing me the right way. I'm still thinking of a workaround at the moment, might try out Dictionaries here as before.

Thank you in advance!

**Comment by jskeet** [comment]
Could you clarify why you've created a custom converter for `Foo` at all? I haven't looked at the detail of what you're doing in there, but I would expect it to be simpler to just decorate `Foo` with the `[FirestoreData]` attribute just as you have with `Document`, at which point it should just be fine.

(Your custom converter seems to return half way through if it find an array though, which seems unlikely to be desirable...)

**Comment by AudriusZemys** [comment]
I created it because of the reference in the docs that
> Array elements cannot themselves be arrays

I've read through other issues and understood that serializing is pretty limited. It was difficult to understand what exactly the issue is only by the exception message.

Anyway, adding `[FirestoreData]` attribute was the dumb mistake on my side. Works perfectly well and the converter is not needed at all.

I'll try to deep dive into converter usage just out of curiosity. So far I love how simple and elegant things are on Google Cloud, very exciting stuff for me :)

Thank you Jon, have a nice day!

P.S. Love your book!
