### ISSUE TITLE
Support Cloud Load Balancing API

### ISSUE THREAD

**Issue by asleire** [googleapis/google-cloud-dotnet#6787]
I'd like to manage Google Cloud Load Balancers using C#. Are there any plans to support the [Cloud Load Balancing API](https://cloud.google.com/load-balancing/docs/apis)?

**Comment by jskeet** [comment]
That's part of the Compute API.

There's an alpha version of our "modern" generated libraries, [Google.Cloud.Compute.V1](https://www.nuget.org/packages/Google.Cloud.Compute.V1).
Alternatively, there's the more mature [Google.Apis.Compute.v1](https://www.nuget.org/packages/Google.Apis.Compute.v1/) library produced by the older generator.

**Comment by asleire** [comment]
Thanks! I kept searching for some load balancer entity, but now realize there is no such thing.
For future people like me: [At the API level, there is no Load Balancer, only the components that make it up](https://stackoverflow.com/a/50958698)
