### ISSUE TITLE
Manual dependency updates required

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#6833]
Things Renovate found that need manual fixes:

- [x] Bigtable client generator has a very outdated gRPC dependency
- [ ] PubSub test uses old Google.Api.Gax.Testing
- [ ] Update Google.Apis to 1.53.0
- [ ] Firestore integation benchmarks: storage
- [x] Breaking change detector: microsoft.build.tasks.core (to 16.10) - or remove this code?
- [x] Breaking change detector: microsoft.build.engine (to 16.10) - or remove this code?
- [x] Breaking change detector: microsoft.build (to 16.10) - or remove this code?
- [ ] Dialog flow ASP.NET Core snippets (currently 1.x!)
- [x] Breaking change detector, analyzers and analyzers testing: microsoft.codeanalysis.csharp.workspaces 3.10.0
- [ ] xunit combinatorial
- [ ] ValueTuple for Spanner and PubSub tests

**Comment by jskeet** [comment]
- [ ] Firestore integation benchmarks: storage
- [ ] Breaking change detector: microsoft.build.tasks.core (to 16.10) - or remove this code?
- [ ] Breaking change detector: microsoft.build.engine (to 16.10) - or remove this code?
- [ ] Breaking change detector: microsoft.build (to 16.10) - or remove this code?
- [ ] Dialog flow ASP.NET Core snippets (currently 1.x!)
- [ ] Breaking change detector, analyzers and analyzers testing: microsoft.codeanalysis.csharp.workspaces 3.10.0

**Comment by jskeet** [comment]
- [ ] xunit combinatorial

**Comment by jskeet** [comment]
- [ ] ValueTuple for Spanner and PubSub tests

**Comment by jskeet** [comment]
- [ ] Update the analyzer to netstandard2.0

**Comment by amanda-tarafa** [comment]
- [ ] System.Collections.Immutable in Google.Cloud.Tools.VersionCompat

**Comment by amanda-tarafa** [comment]
- [ ] Maybe add a .NET 5 framework target for Diagnostis.AspNetCore3 unit and integration tests. But ASP.NET dependencies need to be the ones from ASP.NET Core 3.
