### ISSUE TITLE
System.Text.Json dependency replacing Newtonsoft.Json on newer targets

### ISSUE THREAD

**Issue by NinoFloris** [googleapis/google-cloud-dotnet#6874]
Now that System.Text.Json has matured a bit (5.0 is ok and 6.0 will be fairly nice even) I'm wondering if the SDK would consider switching from Newtonsoft.Json to STJ on these newer targets. For us Google.Api.Gax is the last place Newtonsoft.Json is referenced. I'm willing to do the work, after a quick search it looks manageable.

I would completely understand if you think it would be too much of a maintenance burden!

**Comment by jskeet** [comment]
No, we can't really do that. In Google.Apis there are public API surface bits exposing Json.NET, so you'd end up having the dependency anyway. We would eventually like to separate GAX from Google.Apis.Auth, but that definitely won't be any time soon.

**Comment by NinoFloris** [comment]
Ah I hadn't found those in my cursory look, that's a blocker indeed...

**Comment by jskeet** [comment]
Closing (with regret) as infeasible. Sorry about that. (Maybe eventually we'll be able to separate them entirely...)
