### ISSUE TITLE
Support for cancellation token in PublisherClient.PublishAsync

### ISSUE THREAD

**Issue by hundreder** [googleapis/google-cloud-dotnet#6889]
I see that two relatively similar types (at least by names) exist for publishing messages and both are public via lib api, PublisherServiceApiClient and PublisherClient. They both have PublishAsync method. I am using PublisherClient, constructed as singleton, and PublisherClient is the one used in documentation. What I don't see is, a way to cancel message publishing via CancellationToken. If http request is being canceled by the client, message publishing wont be canceled if its executed at the moment of canceling.
On the other hand PublisherServiceApiClient accepts CancelationToken, but not sure if it's the way to go.

So, it looks ok to me to add overload for PublisherClient.PublishAsync that accepts CancelationToken.

Google.Cloud.PubSub.V1

**Comment by jskeet** [comment]
The `PublisherServiceApiClient` is the "low-level" API - and the cancellation token would be used to cancel a single RPC.

`PublisherClient` is a higher level API which batches messages to be published, amongst other things. Using a cancellation token for a single message within a batch would be very confusing in terms of semantics. Instead, `PublisherClient` expects to just publish batches appropriately, with a `Shutdown` method to shut the client down entirely.

It's hard to give a recommendation without knowing more about your context, but if you want to have fine-grained control over the publishing, including cancelling individual messages, you may well be better off with `PublisherServiceApiClient`.

But adding an overload to `PublisherClient.PublishAsync` accepting a `CancellationToken` wouldn't fit in with the general model, in my view. (I should note that this is an area of our client libraries that I know *relatively* little about, admittedly.)

**Comment by jskeet** [comment]
Note: without more information, we have nothing more to do here. I'll close the issue if there's no more interaction by the end of the week. We can always reopen it later.

**Comment by hundreder** [comment]
Thank you John. I wasn't using PublisherClient as a batch publisher, but with default settings for sending a message one by one. I'll have in mind what you've wrote, and use PublisherServiceApiClient for scenarios where I need cancelation.

Thanks.
