### ISSUE TITLE
Using API without use of the libraries.

### ISSUE THREAD

**Issue by bobsort** [googleapis/google-cloud-dotnet#7033]
It seems all developers forgot how they could just download a library and add it to their library folder and it would stay there for rest of their application life and would compile without issue even 20 years after it was written without fear of jCenter, codeplex, google code, .... shutdown.

1- I have disabled nuget in my system, since I'm working from a barn and have limited access to internet which charges me price of one Quarter Pounder per 100Mb. However I have access to internet when I'm in town once a month. I find it annoying that when people develop a source code they forget to mention its dependencies in their documentation so I can download them before hand. Imagine you go back to your barn and find out you will need to download 5 packages. you look at their size, ok it is 200kb I'll download it, then realize those packages have dependency to other packages and before you know it, you have downloaded over 1Gb data and next day have to go back to city to purchase another data pack for your phone.

2- I am writing API consumers for past 20 years and I can do it in just 20 line of code. I can't figure out why would I need a minimum 500 lines of code to be able to do that. I compiled the code and it is about 65Mb for just calling a single 

3- I deleted .git, *.sh, *.md, *.py since I don't want to publish back to this repo and I don't have bash or python on my widows system. now I cannot even open the projects since references in projects were given from ".gitignore" file and root of the repo instead of relative paths!

4- Projects are defined as .NET 4.6 compatible but I am not even able compile projects on .NET 4.6 (only .NET standrard and core works)

**Comment by jskeet** [comment]
I'm sorry you're dissatisfied with the libraries we're providing. The largest dependency is gRPC, and that has reduced in size very significantly over time. In the next major release we're planning on moving to the Grpc.Net.Client implementation, which should reduce this further. However, it's never going to be tiny.

Out of all your points, point 4 is the only one I think we can really address. (I don't know what point 3 was trying to say at all, I'm afraid.) We run integration tests against .NET 4.6 every day, so everything really should be fine. If you could provide a concrete example of the problems you're having with .NET 4.6, we can try to help with that.

**Comment by bobsort** [comment]
Hello Mr. Skeet,

I meant no offense, specially to such a reputable person like you who saved my back many times directly and indirectly (SO)
I Apologise for my tone in message.

I had one single map API access which was miraculously working over past 6 years even though I received a million messages from google that they will terminate it/close it/shut it down/will not be available. Yesterday I received a company project dropped by 2 other teams as not feasible by defined constrains. It is a text to speech and I decided to give it a go with google text to speech. From experience with google map API (only 4 lines of code) I thought, how hard that could be. 

to access it I had to migrate my account to cloud so clicked the button. Loosing access to old map API was not the only problem. 
 When I reach here I was already frustrated with the process of activating and creating project in cloud console. most cloud documents doesn't make sense. Things that need to be explained in detail is just summarized in one single line, how to links go to pages that doesn't exists. Even to find link to these github accounts I had to look in documents for an hour.

I tried these libraries for another 3 hours, I got it to work in my own PC but due to  server security policies I cannot just install whatever I want and change settings. I gave up at 1:30 AM and decided to try PHP libraries. 

--- Item 3, 
Most people who work with .NET are still working on windows OS and windows doesn't run bash (I know I can install it) so sh files are just ... same goes for python. I am working on Visual Studio Pro (licensed to company). It is company PC and obviously I won't be able to install what I like, and since bash support is not part of windows it doesn't exist and I can't use bash scripts to compile libraries.

Some of projects have settings that trying to locate .gitignore file or root of the repository to locate other required projects deleting .git or even moving part of project out of git folder will cause it to go haywire and doesn't even open.
for example: 

```
    <AssemblyOriginatorKeyFile>$(RepoRoot)/apis/GoogleApis.snk</AssemblyOriginatorKeyFile>
    <RepoRoot>$([System.IO.Path]::GetDirectoryName($([MSBuild]::GetPathOfFileAbove('.gitignore', '$(MSBuildThisFileDirectory)'))))</RepoRoot>

Copy the project out of the local git folder and it won't open anymore.

```

--- Item 4
Build a VM image of your PC with visual studio installed and .NET core (uninstalled). disconnect internet access. I'm sure you know how to copy nuget packages to project without running nuget.

from line ```<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>``` in project file remove ```netstandard2.0``` since it won't open otherwise. try opening the project, it will probably open or not (I had to remove code analyzers too) after opening try to compile it. I believe it will not even though you still have the .NET4.6 in your system.

now in that same system create a .NET 4.6 library project and add project files to it, add reference libraries too, it will compile this time. now Compare project file (csproj) that you have just created with one in this repo (I'm sure differences are obvious)


-- conclusion
6 years ago what I needed to do was to create a key for google API. it was a base64 string which I didn't even care what is in it. put it in ether header of http request or body of request and send it to server to receive your result, and that was it, in some cases I would receive a secondary token which was valid for one session and then I had to request a new token. 

For Java I can easily find dependency tree and it doesn't look pretty. for .NET since you have written most of the code yourself, you know their dependency and it doesn't look pretty either and same goes for PHP. I'm sure you can't fit C++ version in an STM32 micro-controller either. When I say it is complex, I mean, using them is not straight forward, just as it used to be.
