### ISSUE TITLE
ListLogEntries() with pageSize higher than number of logs for filter takes "forever"

### ISSUE THREAD

**Issue by chrisbbe** [googleapis/google-cloud-dotnet#7162]
Hi,

Using [Google.Cloud.Logging.V2](https://www.nuget.org/packages/Google.Cloud.Logging.V2) to list log entries feels buggy in the context of performance;

By specifying the `pageSize` parameter higher than the number of known log entries meeting the criteria for the `filter` param in Google Cloud Logging, the method uses "forever" to return. In opposition to invoking `ListLogEntries()` with a value for `pageSize` that is equal to or lower the number of known log entries that fulfills the filter. This can easily be tested by adjusting the `pageSize` param in the snippet below between different executions.

In my case, I know there are in total 6 log entries fulfilling the `filter` param, execution of the snippet with `pageSize = 6 or 5` causes `ListLogEntries(...)` to return within a few seconds. By adjusting the `pageSize`  to 7 causes the method to return after around 40 ish seconds. 

My first thought was; this might be reasonable, the Google Logging machinery behind the API will quite rapidly find all the 6 entries fulfilling the filter, and thereafter continue crawling all log entries to see if it finds matching entries to "fill the page". But from an RDMS query point of view, this doesn't make sense as both field `logName` and `label.*` is indexed according to the documentation, on the other side I don't think there is any RDMS behind Google Logging, leaving me with no dealing with how Google Cloud Logging lays out the query execution plan.

The execution time diff bothers me, and I find it hard to accept that Google Cloud Logging queries can be so slow, so I decided to try the same query in Python using the official Google Cloud Logging library, and to my delight, the execution time of retrieving log entries is not affected by the page size parameter. This leads me to believe that there are one or more bugs in the Google Cloud Logging .NET library inner workings.

Note: I'm testing this on my local computer, and have not gotten the opportunity to deploy and test the performance while deployed in GCP.

```
var client = LoggingServiceV2Client.Create();
LogName logName = new LogName(s_projectId, logId);
ProjectName projectName = new ProjectName(s_projectId);

var stopWatch = new Stopwatch();
stopWatch.Start();

var results = client.ListLogEntries(
    Enumerable.Repeat(projectName, 1),
    "logName={logName} AND labels.Name=Foo",
    "timestamp desc",
    pageSize: 7
).ToList();

stopWatch.Stop();

```

**Comment by jskeet** [comment]
That sounds very unusual - please could you post the Python you're using as well, so we can try to reproduce this in as close a manner as possible?

I think it's very unlikely that this is a bug in the library; all of this code is autogenerated and pretty much just passes the request through to an RPC.

Just to check another thing - your string `"logName={logName} AND labels.Name=Foo"` isn't an interpolated string literal, so it will include the braces and "logName" rather than the actual log name... did you intend that, or did you intend `$"logName={logName} AND labels.Name=Foo"`?

**Comment by chrisbbe** [comment]
That's correct, the filter string is interpolated in my code, so the filter looks right. Here is the Python script doing the same as the .NET snippet:

```
from google.cloud import logging

def list_entries(project, logger_name):
    """Lists the most recent entries for a given logger."""
    logging_client = logging.Client(project=project)
    logger = logging_client.logger(logger_name)

    print("Listing entries for logger {}:".format(logger.name))

    _filter = "labels.Name=Foo"

    for entry in logger.list_entries(filter_=_filter, order_by="timestamp desc", page_size=1000):
        timestamp = entry.timestamp.isoformat()
        print("* {}: {}".format(timestamp, entry.payload))

if __name__ == '__main__':
    list_entries("GCP_PROJECT_ID", "<your-logger-name>")
```

**Comment by jskeet** [comment]
> That's correct, the filter string is interpolated in my code, so the filter looks right.

So that means the code you gave us isn't the code you're actually using? It would really help if we could get a minimal example (just a console) app that we can run *exactly* as-is, so we can reproduce the problem. It looks like the Python code is already that, so just the equivalent that you're using in .NET would be helpful.

**Comment by chrisbbe** [comment]
The Python version appends the `logName=...` internally in the `list_entries() def`, more precisely on line 280 in `logger.py`.

Here is a minimal .NET example:

```
using System;
using System.Diagnostics;
using System.Linq;
using Google.Api.Gax.ResourceNames;
using Google.Cloud.Logging.V2;

namespace GcpLoggingCmd
{
    internal static class Program
    {
        private static void Main(string[] args)
        {
            ListEntries("GCP_PROJECT_ID", "<your-logger-name>");
        }

        private static void ListEntries(string projectId, string logId)
        {
            var client = LoggingServiceV2Client.Create();
            LogName logName = new LogName(projectId, logId);
            ProjectName projectName = new ProjectName(projectId);

            var stopWatch = new Stopwatch();
            stopWatch.Start();

            var results = client.ListLogEntries(
                Enumerable.Repeat(projectName, 1),
                $"logName={logName} AND labels.CompanyCode=18218",
                "timestamp desc",
                pageSize: 5
            ).ToList();
            stopWatch.Stop();

            foreach (var row in results)
            {
                Console.WriteLine($"{row}");
            }

            Console.WriteLine("Elapsed Time is {0} seconds", stopWatch.ElapsedMilliseconds / 1000);
        }
    }
}
```

.csproj

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Logging.V2" Version="3.4.0" />
  </ItemGroup>

</Project>

```

**Comment by jskeet** [comment]
Great, thanks for the repro - we'll see what we can find out.

**Comment by amanda-tarafa** [comment]
OK, I've been running some crude trials and I can't reproduce what you are seeing, I'm actually seeing exactly the opposite i.e. request with page sizes bigger than result set are faster, which is actually expected.

Here's the code I ran, which is almost the same as yours, except for the layer that makes repeated calls with varying page sizes:

``` csharp
        private static void Main(string[] args)
        {
            //SaveEntries(ProjectId, LogId);
            ListEntriesStatistics(5);
            ListEntriesStatistics(6);
            ListEntriesStatistics(7);
            ListEntriesStatistics(500);
        }

        private static void SaveEntries(string projectId, string logId)
        {
            var client = LoggingServiceV2Client.Create();
            LogName logName = new LogName(projectId, logId);

            WriteLogEntriesRequest request = new WriteLogEntriesRequest
            {
                LogNameAsLogName = logName,
                Labels = { { "Name", "Foo" } },
                Resource = new MonitoredResource { Type = "project", Labels = { { "project_id", projectId } } },
                Entries =
                {
                    new LogEntry {TextPayload = "Entry 1"},
                    new LogEntry {TextPayload = "Entry 2"},
                    new LogEntry {TextPayload = "Entry 3"},
                    new LogEntry {TextPayload = "Entry 4"},
                    new LogEntry {TextPayload = "Entry 5"},
                    new LogEntry {TextPayload = "Entry 6"},
                }
            };

            client.WriteLogEntries(request);
        }

        private static void ListEntriesStatistics(int pageSize)
        {
            long max = 0;
            long min = long.MaxValue;
            long total = 0;
            int executions = 10;
            int expectedEntries = 6;

            for (int i = 0; i < executions; i++)
            {
                var (millisElapsed, entriesFound) = ListEntries(ProjectId, LogId, pageSize);

                total += millisElapsed;

                if (millisElapsed > max)
                {
                    max = millisElapsed;
                }
                if (millisElapsed < min)
                {
                    min = millisElapsed;
                }
                if (entriesFound != expectedEntries)
                {
                    Console.WriteLine($"Expected entries {expectedEntries}, entries found {entriesFound}");
                }
            }

            Console.WriteLine($"Ran {executions} times for pageSize {pageSize}:");
            Console.WriteLine($"Min: {min / 1000}. Max: {max / 1000}. Avg: {total / executions / 1000}");
        }

        private static (long millisElapsed, int entriesFound) ListEntries(string projectId, string logId, int pageSize)
        {
            var client = LoggingServiceV2Client.Create();
            LogName logName = new LogName(projectId, logId);
            ProjectName projectName = new ProjectName(projectId);

            var stopWatch = new Stopwatch();
            stopWatch.Start();

            var results = client.ListLogEntries(
                Enumerable.Repeat(projectName, 1),
                $"logName={logName} AND labels.Name=Foo",
                "timestamp desc",
                pageSize: pageSize
            ).ToList();

            stopWatch.Stop();

            return (stopWatch.ElapsedMilliseconds, results.Count);
        }
```

And here's the result I get (times in seconds):
```
Ran 10 times for pageSize 5:
Min: 18. Max: 38. Avg: 29
Ran 10 times for pageSize 6:
Min: 14. Max: 24. Avg: 18
Ran 10 times for pageSize 7:
Min: 11. Max: 17. Avg: 13
Ran 10 times for pageSize 500:
Min: 12. Max: 16. Avg: 13
```

I created 6 very simple entries running (just once) the `SaveEntries` method that I've shared. And the I ran the statistics for the different page sizes. The resulsts are very consistent and expected, here's why:

- When you call `ListLogEntries` no service calls are made inmediately, instead you get a sequence as a result.
- As you iterate over the sequence (by calling `ToList` in this case), it will lazily make service calls, each time requesting the next page of results, with the given page size.
- The sequence knows not to make any more service calls  when the page returned is smaller than the requested page size.
- Given that we have 6 entries:
  - When page size is 5, we need 2 service calls, both responses contain results. That's why this one takes the longest.
  - When page size is 6, we still need 2 service calls, but the second response finds and returns no entries. That's why this one takes slightly less than the first one.
  - When page size is bigger than 6 (no matter if it's 7 or 500) we only need 1 service call, which returns 6 entries. That's why runtimes for these two page sizes are consistent and the shortest.

Could you run my code and report back?

Note: There's probably some caching involved server side, as in my first few runs of this code all times were slightly higher, but the relationship between them was still roughly the same, and that's what we care about here.

**Comment by chrisbbe** [comment]
Thanks for the detailed feedback. Executing your code basically never finish, been waiting for a while and only the first results appears;

```
Expected entries 6, entries found 0
Ran 10 times for pageSize 5:
Min: 21. Max: 263. Avg: 86
```

Simultaneously as your code executed, I ran the Python version with the same filter as in your code, returning withing seconds (2, 3 seconds). I still suspect there's something going on in the .NET library, slowing down the communication with the API.

Do you have any explanation for why the Python version is noticeable faster?

**Comment by chrisbbe** [comment]
Your code translated to Python yields the following results:

```
Ran 10 times for pageSize 5
Min: 1.4629275798797607. Max: 2.0473074913024902. Avg: 1.8228280305862428
Ran 10 times for pageSize 6
Min: 1.5058989524841309. Max: 2.1481986045837402. Avg: 1.714873480796814
Ran 10 times for pageSize 7
Min: 1.6548881530761719. Max: 1.9952278137207031. Avg: 1.820720911026001
Ran 10 times for pageSize 500
Min: 1.5909919738769531. Max: 2.142904281616211. Avg: 1.7820335388183595
```

**Comment by amanda-tarafa** [comment]
Can you please confirm that you are executing the C# and Python code in the same machine, same network config, etc.

It's not just weird that the C# code hangs, but also the huge difference between the min and max execution of the only result shown.

**Comment by jskeet** [comment]
I was thinking about the network config too - particularly in terms of proxies, which may be configured for one language but not the other.
Are you able to test the same code on multiple machines, ideally on different networks?

One other *possible* factor - it looks like the Python library can use gRPC or HTTP/1.1. The .NET library will *always* use gRPC. Is it possible that Python isn't using gRPC in your test setup, and that the transport difference explains things?

The reason Amanda and I aren't looking through the library code is that there's so little of it involved here - basically it makes the RPC, and that's all. One next step might be to rewrite the repro using the "raw" gRPC with even less library code involved, removing GAX from the picture entirely. I'd be very surprised if that made a difference, but then the results are already very surprising.

**Comment by chrisbbe** [comment]
I can confirm that the C# and Python code was executed on the same computer, and therefor the same network.

Executing on another Windows computer on my home network yields the following results;

```
Ran 10 times for pageSize 5:
Min: 18. Max: 64. Avg: 30
Ran 10 times for pageSize 6:
Min: 18. Max: 25. Avg: 20
Ran 10 times for pageSize 7:
Min: 16. Max: 18. Avg: 17
Ran 10 times for pageSize 500:
Min: 16. Max: 20. Avg: 17

```
Even tried on Ubuntu, without any significant difference.

Reworked the Python version, who now runs with both gRPC disabled and enabled:

```
Results; use_grpc=True
------------------------
Ran 10 times for pageSize 5
Min: 1.74. Max: 3.14. Avg: 2.10
Ran 10 times for pageSize 6
Min: 1.70. Max: 2.21. Avg: 1.88
Ran 10 times for pageSize 7
Min: 1.70. Max: 2.89. Avg: 1.91
Ran 10 times for pageSize 500
Min: 1.69. Max: 2.14. Avg: 1.86

Results; use_grpc=False
------------------------
Ran 10 times for pageSize 5
Min: 0.00. Max: 0.00. Avg: 0.00
Ran 10 times for pageSize 6
Min: 0.00. Max: 0.00. Avg: 0.00
Ran 10 times for pageSize 7
Min: 0.00. Max: 0.00. Avg: 0.00
Ran 10 times for pageSize 500
Min: 0.00. Max: 0.00. Avg: 0.00
```

Python code:

```python
import sys
import time

from google.cloud import logging


def list_entries(page_size, project_id, logger_id, use_grpc):
    """Lists the most recent entries for a given logger."""
    logging_client = logging.Client(project=project_id, _use_grpc=use_grpc)
    logger = logging_client.logger(logger_id)

    _filter = "labels.Name=Foo"

    start = time.time()
    entries = logger.list_entries(filter_=_filter, order_by="timestamp desc", page_size=page_size)
    end = time.time()

    return end - start, len(list(entries))


def list_entries_statistics(page_size, project_id, log_id, use_grpc):
    max_millis = 0
    min_millis = sys.maxsize
    total = 0
    executions = 10
    expected_entries = 6

    i = 0
    while i < executions:
        millis_elapsed, entries_found = list_entries(page_size, project_id, log_id, use_grpc)
        total += millis_elapsed

        if millis_elapsed > max_millis:
            max_millis = millis_elapsed

        if millis_elapsed < min_millis:
            min_millis = millis_elapsed

        if entries_found != expected_entries:
            print("Expected entries {}, entries found {}".format(expected_entries, entries_found))

        i += 1

    print("Ran {} times for pageSize {}".format(executions, page_size))
    print("Min: {:.2f}. Max: {:.2f}. Avg: {:.2f}".format(min_millis, max_millis, (total / executions)))


if __name__ == '__main__':
    project_id = "<your-gcp-project-id>"
    log_id = "<your-log-id>"

    print("Results; use_grpc=True")
    print("------------------------\n")
    list_entries_statistics(5, project_id, log_id, True)
    list_entries_statistics(6, project_id, log_id, True)
    list_entries_statistics(7, project_id, log_id, True)
    list_entries_statistics(500, project_id, log_id, True)

    print("\nResults; use_grpc=False")
    print("------------------------\n")
    list_entries_statistics(5, project_id, log_id, False)
    list_entries_statistics(6, project_id, log_id, False)
    list_entries_statistics(7, project_id, log_id, False)
    list_entries_statistics(500, project_id, log_id, False)

```

**Comment by amanda-tarafa** [comment]
I think there's a problem with your latest Python code (althoug I'm not 100% certain as I'm not very familiar with that library). But, it should work very similar to the C# one in that it will only make lazy service calls. Basically, you should call `len` inside the stopwatch as that is what will trigger the service calls.
Can you please do that on both machines and report back? Thanks.

**Comment by chrisbbe** [comment]
Ahh, I see. Here is the updated code:

```python
def list_entries(page_size, project_id, logger_id, use_grpc):
    """Lists the most recent entries for a given logger."""
    logging_client = logging.Client(project=project_id, _use_grpc=use_grpc)
    logger = logging_client.logger(logger_id)

    _filter = "labels.Name=Foo"

    start = time.time()
    entries = logger.list_entries(filter_=_filter, order_by="timestamp desc", page_size=page_size)
    entries_length = len(list(entries))
    end = time.time()
    return end - start, entries_length
```

New execution results, executed on work and home computer, on different networks:

Computer 1
```
Results; use_grpc=True
------------------------
Ran 10 times for pageSize 5
Min: 3.03. Max: 4.64. Avg: 3.64
Ran 10 times for pageSize 6
Min: 3.05. Max: 3.62. Avg: 3.34
Ran 10 times for pageSize 7
Min: 1.71. Max: 2.32. Avg: 1.82
Ran 10 times for pageSize 500
Min: 1.61. Max: 2.31. Avg: 1.88

Results; use_grpc=False
------------------------
Ran 10 times for pageSize 5
Min: 3.12. Max: 3.72. Avg: 3.35
Ran 10 times for pageSize 6
Min: 3.11. Max: 4.03. Avg: 3.33
Ran 10 times for pageSize 7
Min: 1.72. Max: 2.18. Avg: 1.90
Ran 10 times for pageSize 500
Min: 1.77. Max: 1.98. Avg: 1.89
```

Computer 2
```
Results; use_grpc=True
------------------------
Ran 10 times for pageSize 5
Min: 2.90. Max: 3.57. Avg: 3.13
Ran 10 times for pageSize 6
Min: 2.80. Max: 3.89. Avg: 3.14
Ran 10 times for pageSize 7
Min: 1.64. Max: 1.94. Avg: 1.81
Ran 10 times for pageSize 500
Min: 1.65. Max: 2.21. Avg: 1.78

Results; use_grpc=False
------------------------
Ran 10 times for pageSize 5
Min: 3.03. Max: 3.92. Avg: 3.26
Ran 10 times for pageSize 6
Min: 2.69. Max: 3.62. Avg: 3.21
Ran 10 times for pageSize 7
Min: 1.78. Max: 2.21. Avg: 1.88
Ran 10 times for pageSize 500
Min: 1.73. Max: 1.96. Avg: 1.81
```

**Comment by amanda-tarafa** [comment]
OK, we found something else that affects consistency of results between Python and C#. The Python library [adds a default "last 24 hours" filter](https://github.com/googleapis/python-logging/blob/28d141d0e8ed4560d2e33f8de0d43b0825a7f33f/google/cloud/logging_v2/_helpers.py#L144) whereas the C# library adds nothing.

So, ideally:
- Add a `timestamp >= "2021-09-15"` filter to the C# query and run on both machines. You should get results similar to the latest reported with Python.
- Add a timestamp > "2000-09-01" (basically a date that includes the whole lifetime of your project) to the Python query and run on both machines. Machine 1 should hang or be very slow (sames as C# is without the timestamp filter) and machine 2 should have similar times to the ones your reported there for C#.

Thanks again!

**Comment by chrisbbe** [comment]
Yes, that's it! Making sure both the Python and C# client sends the same filter request over the wire makes both libraries act the same in the manner of response time. Thank you for leading pointing me in the right direction!
