### ISSUE TITLE
Canonical link function returning 500s

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-dotnet#7233]
https://us-central1-jonskeet-integration-tests.cloudfunctions.net/canonicalize-link?package=Google.Apis.Auth.AspNetCore&page=api%2FMicrosoft.Extensions.DependencyInjection.GoogleOpenIdConnectExtensions.html: status: 500 Internal Server Error

https://us-central1-jonskeet-integration-tests.cloudfunctions.net/canonicalize-link?package=Google.Apis.Logging.v2&page=api%2FGoogle.Apis.CloudResourceManager.v2.CloudResourceManagerBaseServiceRequest-1.AltEnum.html: status: 500 Internal Server Error

P1 because we need to update canonical links right away.

**Comment by jskeet** [comment]
Will have a look tomorrow.

The first of those is interesting given that it's not a Google class though...

**Comment by jskeet** [comment]
Ah, I'm wrong about the first one - it *is* a Google class, due to the slightly odd conventions for this area.

Will try to solve both now...

**Comment by jskeet** [comment]
Okay, I've got a fix - but I'm surprised that we're asking for the second one at all, as the given page isn't documented in that package. It might be worth investigating why we're trying that - it may be there's a bug somewhere else.
