### ISSUE TITLE
Add support for turbo replication

### ISSUE THREAD

**Issue by ddelgrosso1** [googleapis/google-cloud-dotnet#7266]
We need to add support for a new metadata field `rpo`. Full details are available in [this doc](https://docs.google.com/document/d/1ee3LzRfyArNIR4rLEeY60Eio7DBwLy5TkmvcMPxSork/edit?usp=sharing&resourcekey=0-4CYSH1Gc0ekxa1oUntE9yg).

Please wait for approval from myself before merging or releasing this change so we can coordinate around release dates.

**Comment by jskeet** [comment]
@ddelgrosso1: It's not clear that anything actually needs to be done for the C# library. We rely on the generated REST library, which [already contains the `Rpo` property](https://github.com/googleapis/google-api-dotnet-client/blob/cb5130649c6776aef3d132e380d9f29b97120e61/Src/Generated/Google.Apis.Storage.v1/Google.Apis.Storage.v1.cs#L7669).

Users of Google.Cloud.Storage.V1 will have access to the `Rpo` property via the generated `Bucket` class - I doubt that anything else is required here.

**Comment by ddelgrosso1** [comment]
Thanks @jskeet. I spoke with @shivgautam and @amanda-tarafa the request was that I open 2 issues, 1 for samples 1 for the library. If this requires no work, I will go ahead and close it.
