### ISSUE TITLE
Fastest way to fetch table's data to local cache

### ISSUE THREAD

**Issue by shiran1992s** [googleapis/google-cloud-dotnet#7281]
Hi,
I have a table sized approximately 6 GB, I am trying to fetch all the table's data and load it to a local cache.
The code I use is (in basic format):
```
var query = "SELECT  *  FROM ..."
var customerProfiles = bqClient.ExecuteQuery(query, null);
```
Is there any difference between returning the results as IEnumerable<> and later split them to batches and process each batch and insert the results to local cache.

Or is it preferable to return a List<> of all the results and process them and insert the results to local cache.

I am trying to understand is there any difference when I iterate the result in a foreach between a List<> and IEnumerable<> (we are using an extension using yield)  according to your implementation?

Best Regards,
Shiran.

**Comment by jskeet** [comment]
That will depend on how you return the results as an `IEnumerable<>`, and what you then do with it.

When you iterate over a `BigQueryResult`, it will fetch a page of results at a time. If you iterate over it multiple times, you'll end up fetching results multiple times, which you obviously want to avoid.

If you're definitely going to want all the data in memory, then just calling `ToList()` would be the *simplest* way of fetching it all. However:

- It sounds like you could quite possibly insert the results into the local cache piecemeal, avoiding pulling all the data in one go
- Depending on how you structure your code, you may be able to achieve more concurrency by inserting some data into your cache while fetching the next page of data
- You should think about the "partial results before failure" scenario: do you only want to put *anything* in the local cache if you're able to fetch *everything* from the database? If that's the case, it's hard to avoid fetching everything first. If, however, you want to put as much into the local cache as possible, even if there's a failure when fetching the very last row, then "process as you go" is clearly better.

**Comment by jskeet** [comment]
Please could you let us know if there's anything else you need here?

**Comment by shiran1992s** [comment]
Hi, Thank you for your fast and thorough answer.
We decided to split the info to batches sized 100K and ToList().

Best Regards,
Shiran.
