### ISSUE TITLE
Firestore - Limit not returning correct number of records

### ISSUE THREAD

**Issue by neil-gok** [googleapis/google-cloud-dotnet#7299]
Library: Google.Cloud.Firestore 2.3.1

When attempting to query a range of dates, I am unable to return the correct number of records when including a limit in the query.  In the example below, without the limit selected, it returns over 5k records.  When I apply a limit of 5k, it only returns 2256 records.  

```csharp
        public async Task<List<T>> QueryRecords<T>(Query query) where T : FireStoreBase
        {
            QuerySnapshot querySnapshot = null;
            querySnapshot = await query.GetSnapshotAsync();            
            List<T> list = new List<T>();
            var count = querySnapshot.Documents.Count;
            foreach (DocumentSnapshot documentSnapshot in querySnapshot.Documents)
            {
                if (documentSnapshot.Exists)
                {                    
                    Dictionary<string, object> record = documentSnapshot.ToDictionary();                    
                    T newItem = documentSnapshot.ConvertTo<T>();
                    newItem.Id = documentSnapshot.Id;
                    list.Add(newItem);
                }
            }
            return list;
        }

        public async Task<List<SomeData>> GetSchedulesFilterByDate(DateTime startDate, DateTime endDate, int recordsLimit = 0)
        {
            if (recordsLimit == 0) recordsLimit = _recordsLimit;

            Query query = repo.fireStoreDb.Collection(collectionName).OrderBy("SomeDate")
                                            .WhereGreaterThanOrEqualTo("SomeDate", startDate)
                                            .WhereLessThanOrEqualTo("SomeDate", endDate).Limit(5000);

            return await repo.QueryRecords<SomeData>(query);
        }
```

**Comment by jskeet** [comment]
I'll look at this on Monday.

**Comment by jskeet** [comment]
@neil-gok: I can try, but this is why I'm asking you for a complete example to reproduce the problem. Me trying random things from a position of *not* being able to reproduce the problem isn't as useful as you cutting down your existing situation where you *can* reproduce the problem, until you've got something you can share.

I'll try adding nested collections and documents, but I'm basically *guessing* whereas you know the exact structure that does reproduce the problem.

**Comment by neil-gok** [comment]
@jskeet 

Thanks for your assistance with this.  After trying a number of things on my side, I have determined that this is a proxy issue, and not an issue with the Library or the Firestore API itself.
