### ISSUE TITLE
Add a custom label to automatically generated traces

### ISSUE THREAD

**Issue by Gregordy** [googleapis/google-cloud-dotnet#7430]
I am using Google.Cloud.Diagnostics.AspNetCore v4.3.0.

I use `AddOutgoingGoogleTraceHandler` to trace every outgoing HTTP request of a given HTTP client and I want to add a label to every trace created by this method.

From what I understood, it is more precisely the underlying span of a trace that carries a label.
And we can use the [AnnotateSpan](https://googleapis.dev/dotnet/Google.Cloud.Diagnostics.Common/latest/api/Google.Cloud.Diagnostics.Common.ISpan.html#Google_Cloud_Diagnostics_Common_ISpan_AnnotateSpan_System_Collections_Generic_Dictionary_System_String_System_String__) method to add a label, but only when we manually create a trace span.

I read the [latest documentation](https://googleapis.dev/dotnet/Google.Cloud.Diagnostics.AspNetCore/4.3.0/index.html#using-tracing-with-other-than-googles-own-trace-header) but still didn't figure out how to do label annotation for automatically created traces.

Am I missing something?

**Comment by amanda-tarafa** [comment]
Unfurtunatelly you are not missing anything, custom labels on outgoing traces (and yes, it's the spans that carry the labels) are not supported.
I've marked this as a feature request and I'll try to get it in before the month is out.
Would it work for you a definition of

```csharp
public interface IOutgoingTraceLabelsProvider
{
    IDictionary<string, string> GetLabelsForOutgoingRequest(HttpRequestMessage outgoingRequest);
}
```

Then you would inject as many of these as you'd like and we would use them to annotate the outgoing span.

Let me know if this sounds like a good solution for you.

**Comment by Gregordy** [comment]
Thank you for the quick reply Amanda!

Yes, this solution looks totally fine to me.

**Comment by amanda-tarafa** [comment]
@Gregordy I've submitted #7676 for review that should add support for custom labels in outgoing traces. I implemented it slightly different to how we talked about in https://github.com/googleapis/google-cloud-dotnet/issues/7430#issuecomment-961749050.

Basically I've added an overload to `AddOutgoingGoogleTraceHandler` that takes a `Func<IServiceProvider, IDictionary<string, string>>`. I believe this approach is more inline with how a configuration should work for IHttpClientFactory and it's also more flexible, as it will allow you to configure different HTTP clients that set different labels.

Let me know if you think there's some use case that this won't cover.

**Comment by amanda-tarafa** [comment]
@Gregordy I've merged #7676, but I won't release until you've confirmed that the resulting API surface covers your use case. Please see https://github.com/googleapis/google-cloud-dotnet/issues/7430#issuecomment-1010074440 above.

**Comment by amanda-tarafa** [comment]
@Gregordy any thoughts on the implemented solution?

**Comment by Gregordy** [comment]
@amanda, your implementation is indeed more flexible than what we discussed initially. Everything looks good to me, I think this will cover all my needs.

**Comment by amanda-tarafa** [comment]
Thanks! I'll release on Monday then.

**Comment by Gregordy** [comment]
Thanks to you Amanda.
