### ISSUE TITLE
Error Reporting: No way to manually set credentials 

### ISSUE THREAD

**Issue by cypressious** [googleapis/google-cloud-dotnet#7448]
#### Environment details

  - OS: Windows
  - .NET version: 6
  - Package name and version: Google.Cloud.Diagnostics.AspNetCore 4.3.0

#### Steps to reproduce

Calling `services.AddGoogleErrorReportingForAspNetCore()` offers no way to set the Google Credential manually.

In version 4.2.0 I was able to do

```cs
services.AddGoogleExceptionLogging(
    options =>
    {
        options.ProjectId = projectId;
        options.ServiceName = name;
        options.Version = version;
        options.Options = ErrorReportingOptions.Create(
            EventTarget.ForLogging(
                projectId,
                loggingClient: new LoggingServiceV2ClientBuilder { ChannelCredentials = googleCredential.ToChannelCredentials() }.Build()));
    });
```

After upgrading to 4.3.0, my application failed to start with an Error from Google Error Reporting (ironic) as it wasn't finding any credentials to use. I noticed that `AddGoogleExceptionLogging` was now deprecated, so I tried to do

```cs
services.AddGoogleErrorReportingForAspNetCore(new ErrorReportingServiceOptions
{
    ProjectId = projectId,
    ServiceName = name,
    Version = version,
    Client = new LoggingServiceV2ClientBuilder { ChannelCredentials = googleCredential.ToChannelCredentials() }.Build(),
});
```

but still didn't have success.

The `Client` property seems to be ignored after the update. This can be confirmed be looking in https://github.com/googleapis/google-cloud-dotnet/blob/09fe22baac6fe7a34b9691a1ef1257751dc659b6/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/ErrorReporting/ErrorReportingExtensions.cs where `options.Client` is never accessed.

I was able to come up with the following ugly workaround but I would appreciate if there was a more straight-forward way:

```cs
ErrorReportingServiceOptions options = new ErrorReportingServiceOptions
{
    ProjectId = projectId,
    ServiceName = name,
    Version = version,
    Client = new LoggingServiceV2ClientBuilder { ChannelCredentials = googleCredential.ToChannelCredentials() }.Build(),
};

services.AddGoogleErrorReportingForAspNetCore(options);
services.Replace(ServiceDescriptor.Singleton(provider => ContextExceptionLogger.Create(options, provider)));
```

**Comment by cypressious** [comment]
Note that this is a breaking change, in fact my application failed to start up after upgrading because Error Reporting wasn't finding any credentials.

**Comment by amanda-tarafa** [comment]
This is a bug and I'm working on a fix right now.  The intention is that you continue to use the client property on the ErrorReportingServiceOptions.

**Comment by amanda-tarafa** [comment]
Fyi, the fix for this has just been released in Google.Cloud.Diagnostics.* 4.3.1.
Thanks for reporting and sorry for the inconvenience.

**Comment by cypressious** [comment]
Thx for the quick fix and for letting me know.
