### ISSUE TITLE
Seekable streams over GCS

### ISSUE THREAD

**Issue by CatalinAdlerDF** [googleapis/google-cloud-dotnet#7471]
Hi folks,

It's common to store files of significant size on GCS; some formats are seekable, like zips, ISO, avro, etc.
The current .NET api for accessing content on GCS is a DownloadObjectAsync that download the full file content to a stream.

It would be far more practical to have a OpenFile that returns a seekable stream over a file stored in GCS.
GCS supports range headers so stream seek operations can be implemented.

I've found ootb implementations in java for eg and other people manually implementing the idea https://medium.com/circuitpeople/random-access-seekable-streams-for-amazon-s3-in-c-bd2414255dcd

Thanks!

**Comment by jskeet** [comment]
It doesn't have to download the full content - you can specify the range in [DownloadObjectOptions.Range](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Storage.V1/latest/Google.Cloud.Storage.V1.DownloadObjectOptions#Google_Cloud_Storage_V1_DownloadObjectOptions_Range). Creating a full seekable stream over the top of the underlying library would be a very significant amount of implementation work for relatively little benefit over just downloading the range you're interested in via the options.

**Comment by jskeet** [comment]
(You could potentially implement the functionality yourself on top of Google.Cloud.Storage.V1 if you really wish to do so, but I don't expect this to be something which would ever reach the top of our team's priority list.)

**Comment by CatalinAdlerDF** [comment]
Well, i do not want to explicitly seek to a range, but I'd like to pass the seekable stream to classes which do that, like a ziparchive.
You know that the pattern in .net is to get a stream, pass it around, and depending on its capabilities seek, rewind, etc as needed.

With the current design in the gcp libs i am forced to create a stream, fully download the object to it and then pass it around, which is quite inefficient for seekable formats.

In my use case, I have .zip files in gcs; i do not know where the table of content is, but zip libraries do; and most take in a stream as input arg on the ctor.

**Comment by jskeet** [comment]
Right, I can appreciate the use case, but:

- Seeking on a remote stream like that as if it's a simple operation is likely to be very inefficient. I suspect many libraries expect to be able to seek anywhere in a reasonably efficient way, whereas you'd have to start fetching data with new requests all over the place
- As I said before, you should be able to implement the functionality yourself on top of Google.Cloud.Storage.V1 should you wish (using `DownloadObjectOptions.Range`) but I don't expect this to be a feature we implement ourselves.

**Comment by CatalinAdlerDF** [comment]
Thanks for the response.

Will definitely have to implement myself or find other libs that might be using the s3 apis.

Inefficient as it might be, it is miles better than downloading tons of useless bytes.

But I must be missing smth from the whole picture; at low level all file io are about operations on byte ranges; even at storage level we talk ab sectors (hdd and ssd); this should map very well with the http range operation. I understand that latencies are vastly different, but that becomes a perf problem, not a mismatch problem.
wrt to multiple requests, i hope that one day object store allows us to use the new http capabilities which should help in this regard.

**Comment by jskeet** [comment]
Yes, it's just a performance problem - it's absolutely feasible to implement this. The mismatch is in terms of expectations of performance and the relative cost of seeking.

When implementing this, you'll need to work out how much data you're happy to cache: if the zip library keeps doing a "seek to part of the header, read some data, seek to the start of the next file, read it, then seek back to the header" etc, do you cache the previously-read data for the header? Does that mean reading more than you're "asked" to in the first place? (If the library tries to read a single byte, do you make an HTTP request for that single byte, or do you read some minimum amount and cache it? At what point do you evict cache entries?)

Again, all perfectly doable - but there are non-trivial decisions that could make a huge difference in terms of performance.

**Comment by CatalinAdlerDF** [comment]
I guess I'll see.

Thanks!

**Comment by jskeet** [comment]
Please feel free to reach out with questions when you're implementing - happy to help in that regard.

I'll close this issue now as I don't expect to make any change within this repo, but good luck with it!
