### ISSUE TITLE
Support the use of `PUBSUB_EMULATOR_HOST` with the P/S Emulator

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/google-cloud-dotnet#7510]
When using the P/S C# client lib with the P/S emulator, one is required to patch their code as describe [here](https://cloud.google.com/pubsub/docs/emulator#accessing_environment_variables). 

Ideally, the library should look for the environment variable `PUBSUB_EMULATOR_HOST` to determine whether to use emulated or real service.

Go/Node.js/PHP/Python/Ruby already support the use of an environment variable, which is a much more desirable experience when testing out P/S locally.

See internal b/206034017.

**Comment by jskeet** [comment]
No, that isn't required. You *do* need to opt into *possibly* using the emulator explicitly, but it's far simpler than described in that sample.
See https://cloud.google.com/dotnet/docs/reference/help/emulators for a description of how to do this - noting that the sample at the end is an example of what you have to do if the library you use *doesn't* support the EmulatorDetection property. I'll add a sample of how to do it for clients that do, but it's as simple as:

```csharp
var client = new SubscriberClientBuilder
{
    EmulatorDetection = EmulatoryDetection.EmulatorOrProduction
}.Build();
```

With that in place, the subscriber client will connect to either the emulator or production based on the environment variable. The FAQ entry describes other values, as well as why this is explicitly opt-in in the .NET client libraries.

**Comment by jskeet** [comment]
Closing this now as I don't believe any further changes are required:

- The library does make it easy to use the emulator; you just need to opt into it
- I've improved the [emulator support docs](https://cloud.google.com/dotnet/docs/reference/help/emulators) and released the new version of that document; it will take a little while to roll out though
- I've improved the [PubSub overview page](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.PubSub.V1/latest), but that won't be rolled out until the next release.

It would make sense to improve the product docs, but that wouldn't be a change in this repo anyway - we can track it in the internal bug.
