### ISSUE TITLE
Add support for Net6 

### ISSUE THREAD

**Issue by samuel-mr** [googleapis/google-cloud-dotnet#7552]
Net6 is now official and has long-term support. Run on Windows, linux and macOS. Many projects are migrating, It would be great to be able to use it

note: Currently [you support from net461]( https://cloud.google.com/dotnet/docs/reference/help/platforms):
... but net461 support will end[ Apr 26, 2022 ](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework)

**Comment by jskeet** [comment]
You already *can* use it. .NET 6 supports netstandard2.0, which we target.

If you've tried to use .NET 6 and had problems, please provide a lot more detail. (We don't currently even know which package you're interested in - there are about 150 hosted in this repo...)

**Comment by samuel-mr** [comment]
really [netstandard 2.0 is to share code between .NET Framework ](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/#what-you-should-target)... not for net5 or net6
this is the package
```
  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="2.4.0" />
  </ItemGroup>
```
**I have created 2 projects, the client (only to consume) and the library** 
1. console app (netcore 2.0) -> library (netstandard 2.0)   OK
2. console app (net 5, net6) -> library (netstandard 2.0 , netstandard 2.1) ERROR

this is the error:
```
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="DeadlineExceeded", Detail="Deadline Exceeded", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1637245331.806000000","description":"Deadline Exceeded","file":"..\..\..\src\core\ext\filters\deadline\deadline_filter.cc","file_line":81,"grpc_status":4}")
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Google.Cloud.Firestore.WriteBatch.CommitAsync(ByteString transactionId, CancellationToken cancellationToken)
   at Google.Cloud.Firestore.DocumentReference.SetAsync(Object documentData, SetOptions options, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in W:\Learn\Android\Firebases\CRUD_firestore\Program.cs:line 27
   at Program.<Main>(String[] args)

```

the problem occurs on this line  **await docRef.SetAsync(user)**
the code in the lib project:
   ```
      const string FIRESTORE_PROJECT_ID = "MYID";
      const string CONFIGURATION_FILE = @"....path\config.json";

      System.Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", CONFIGURATION_FILE);
      FirestoreDb db = FirestoreDb.Create(FIRESTORE_PROJECT_ID);

      DocumentReference docRef = db.Collection("users").Document("alovelace");
      Dictionary<string, object> user = new Dictionary<string, object>
      {
          { "First", "Ada" },
          { "Last", "Lovelace" },
          { "Born", 1815 }
      };
      await docRef.SetAsync(user);

      Console.WriteLine("Saved.");
```
let me know if you need more details

**Comment by jskeet** [comment]
> really netstandard 2.0 is to share code between .NET Framework ... not for net5 or net6

That doesn't mean it isn't supported by .NET 6. It is. I don't believe the problem you're having is due to .NET 6. From the article you referenced:

> The only reason to retarget from .NET Standard to .NET 5 is to gain access to more runtime features, language features, or APIs.

We don't need to do that, so we've left the .NET Standard target. We'll probably make it .NET Standard 2.1 in the next major version, to still support .NET Core 3.1 but get some of the newer features that 2.1 supports.

Did you try the same code on .NET Core 3.1 or .NET Framework before assuming it was a .NET 6 problem?

I've just tried your code in .NET 6 and it was fine - no problem at all. (I literally just created a new .NET 6 console app, added the NuGet reference and a `using` directive, then your code.) If you still think this is a .NET version issue, I suggest you try with a different framework - but I suspect you'll get the same problem.
My strong suspicion is that actually this is a networking problem somewhere - we've seen some proxies that don't handle gRPC properly.

**Comment by samuel-mr** [comment]
can u share me your repo with your code in .NET 6? (maybe there is something different in my project)

**Comment by jskeet** [comment]
Nope, I really can't reproduce the problem at all.

I'm attaching a zip file with a complete console app calling the library app, with the TFMs exactly as you described. It works in both .NET 5 and .NET 6.

Run it with:

```sh
dotnet run -f net6.0 --project ConsoleApp -- your-project-id
```

(After setting the GOOGLE_APPLICATION_CREDENTIALS environment variable in your shell.)

[FirestoreDotNet6.zip](https://github.com/googleapis/google-cloud-dotnet/files/7565013/FirestoreDotNet6.zip)

**Comment by samuel-mr** [comment]
I try it and works ok, the problem was my firewall, sorry and thanks.
