### ISSUE TITLE
Whence Grpc.Net.Client

### ISSUE THREAD

**Issue by samskivert** [googleapis/google-cloud-dotnet#7574]
Any plans to switch away from Grpc.Core to Grpc.Net.Client?

The future of gRPC on .NET is Grpc.Net.Client, or so I have heard from little birdies: https://grpc.io/blog/grpc-csharp-future/

We're trying to use Firebase on Apple Silicon Macs and I'm running into the pickle of the C gRPC libraries not supporting ASi, and the "recommended solution" (for cross-platform loving C# developers like ourselves, per the blog post above) being, stop using the C gRPC libraries. But we don't depend on Grpc.Core, Google.Cloud.Firestore does. So we're stuck. Of course we can run our entire project under x86 emulation for the time being, but ideally we can get back to living in CPU architecture blind utopia promised by C# and the CLR.

**Comment by jskeet** [comment]
Yes, we're planning on doing this in 2022 Q1 (although it's possible it will slip to Q2). It's slightly more complicated than just moving from one library to another, as Grpc.Net.Client won't work on all our target platforms. It's also a breaking change, prompting a new major version, with all the planning and execution timing that involves.

See https://github.com/googleapis/gax-dotnet/pull/508 and https://github.com/googleapis/gax-dotnet/pull/510 for what GAX might look like in the future. It should simplify things significantly, and reduce the transitive dependency size for non-Framework applications too.

For the moment, you can change the GrpcAdapter that the Google.Cloud.Firestore library used - see https://github.com/googleapis/google-cloud-dotnet/issues/7560 for instructions on how to do that.

I'll close this issue now as it's already being planned etc.

**Comment by samskivert** [comment]
Thanks for the quick reply, the roadmap and the workaround! And in advance for the hard work of moving everything over to Grpc.Net.Client. Cheers!

**Comment by samskivert** [comment]
Let me also apologize for what turns out to be a repeat question. I searched the issues for info on Grpc.Net.Client but now I realized that I only searched _open_ issues, not _closed_. I should have broadened my search.

**Comment by jskeet** [comment]
@samskivert: Not a problem at all. It's very easily done, and I appreciate the effort in the first place :)
