### ISSUE TITLE
Mac M1 support?

### ISSUE THREAD

**Issue by tonygomez** [googleapis/google-cloud-dotnet#7630]
ERROR on mac m1 libgrpc_csharp_ext.x64.dylib is not found arm64e.

Is support for mac m1 process planned?

**Comment by jskeet** [comment]
There's a workaround for now by explicitly using the Google.Api.Gax.Grpc.GrpcNetClient package, and in the next few months we're planning a new major version which will use Grpc.Net.Client by default. See https://github.com/googleapis/google-cloud-dotnet/issues/7560 for more details.

**Comment by tonygomez** [comment]
@jskeet  thank you!
