### ISSUE TITLE
SubscriberClient creation error

### ISSUE THREAD

**Issue by milosgrgov** [googleapis/google-cloud-dotnet#7631]
On creating a subscriber client I'm not able to check if the subscriber client is created properly. The same situation is when you try to start it as well. We are not able to get the status. Even if you use the wrong projetId or pull-subscription name. This client will be created but we won't have any messages since this project or pull-subscription does not exist.

**Comment by jskeet** [comment]
The client itself doesn't check, no - but as soon as you try to *start* it, the returned task will fail. Sample code:

```csharp
using Google.Cloud.PubSub.V1;

var subscriptionName = new SubscriptionName("badproject", "badsubscription");
var subscriber = SubscriberClient.Create(subscriptionName);
await subscriber.StartAsync(async (message, cancellationToken) =>
{
    Console.WriteLine(message.MessageId);
    await Task.Yield();
    return SubscriberClient.Reply.Ack;
});
```

Exception:

```text
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="NotFound", Detail="Resource not found (resource=badsubscription).", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1640008778.847000000","description":"Error received from peer ipv4:142.250.180.10:443","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1067,"grpc_message":"Resource not found (resource=badsubscription).","grpc_status":5}")
```

**Comment by jskeet** [comment]
Closing given the reaction to the previous comment.
