### ISSUE TITLE
The call is ambiguous between the following methods

### ISSUE THREAD

**Issue by lukepuplett** [googleapis/google-cloud-dotnet#7633]
#### Environment details

  - OS: macOS 12
  - .NET version: 6.0
  - Package name and version: Google.Cloud.Diagnostics.AspNetCore 4.3.1

#### Steps to reproduce

  1. Create a basic dotnet 6 ASP.NET app
  2. Follow [this Google documentation] (https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Diagnostics.AspNetCore3/latest#configuration-1) up to and including Getting Started.
  3. Assume that your code will run on GCP Cloud Run and omit `ProjectId`, `Service` and `Version` as documented.
  4. Observe that your code will not compile.

`services.AddGoogleDiagnosticsForAspNetCore();`

`The call is ambiguous between the following methods or properties: 'AspNetCoreGoogleDiagnosticsExtensions.AddGoogleDiagnosticsForAspNetCore(IServiceCollection, AspNetCoreTraceOptions, LoggingServiceOptions, ErrorReportingServiceOptions)' and 'AspNetCoreGoogleDiagnosticsExtensions.AddGoogleDiagnosticsForAspNetCore(IServiceCollection, string, string, string, TraceOptions, LoggingOptions, ErrorReportingOptions)' [Evoq.Timesheets.Web.Application]csharp(CS0121)`

I think it's an API bug to have two overloaded signatures that cannot be resolved in this way. I'm not entirely sure there's a solution without breaking it or introducing a second method or third overload with a unique signature, I've not given it much thought, but perhaps the documentation needs changing.

**Comment by amanda-tarafa** [comment]
I'll take a look as soon as I can but that might unfortunately be early January.

The workaround is to pass three null strings for project ID, service and version. They will be obtained from GCP if running there.

**Comment by lukepuplett** [comment]
No rush. Enjoy Christmas. There's a workaround so it's hardly P1, but it's just bad code/API design.
