### ISSUE TITLE
Firestore "Stream Removed" Error After 3 Minutes Doing Nothing

### ISSUE THREAD

**Issue by ertugrulsngr** [googleapis/google-cloud-dotnet#7635]
- OS: Windows 10
  - .NET version: 4.7.2
  - Package name and version: Google.Cloud.Firestore 2.4.0

#### Steps to reproduce

  1. I've .NET Winforms Apps project get information from user and write it to firestore and read documents if needed.
  2. Everything working greatly but if my app do not use any read/write function more than 3 minutes i'm getting this error:
 `Grpc.Core.RpcException: 'Status(StatusCode="Unknown", Detail="Stream removed", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@***","description":"Error received from peer ipv4:****","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1068,"grpc_message":"Stream removed","grpc_status":2}")'
`
Do i made a mistake somewhere or it's about Package?
And should i use a thread that calls read/write functions every 1 minute to prevent getting this error ?

**Comment by ertugrulsngr** [comment]
If i recreate Database instance after catching the error like this;
`catch (Exception ex)
            {
                DataBase = FirestoreDb.Create(ClientID");
            }` solves error but throwing `Stream Removed` error is long proccess. So it takes time.

**Comment by jskeet** [comment]
Are you able to reproduce this in a simple console application? I'd expect it to be something along the lines of:

- Create `FirestoreDb` instance
- Write a document
- In a loop:
  - Read the document
  - Sleep for 5 minutes

If you can reproduce the problem with that, I can try it from here. Although I should mention that I'm really on vacation until January, so won't be able to spend more than a few minutes on it before then.

**Comment by ertugrulsngr** [comment]
Thanks for your answering this quick. I've tried you said. I created an console app with .NET 6.0 and result is still same. 

![error1](https://user-images.githubusercontent.com/82088208/147106377-f5cc850b-69f6-4930-8bb0-ed70c4740d6a.png)

**Comment by ertugrulsngr** [comment]
Thanks for your answering this quick. I've tried you said. I created a console app with .NET 6.0 and result is still same.
![error1](https://user-images.githubusercontent.com/82088208/147107917-04a9e117-e08f-497d-8cb4-0a2d77daef94.png)

**Comment by jskeet** [comment]
Right... So please provide the code for the simple console app so I can try to reproduce the issue.

**Comment by ertugrulsngr** [comment]
Here is my code. Thanks again spend time for this...

```
using Google.Cloud.Firestore;


string Path = AppDomain.CurrentDomain.BaseDirectory + @"pathtoSDK json file";
Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", Path);
FirestoreDb DataBase = FirestoreDb.Create(DataBaseId);
Query QRef = DataBase.Collection(CollectinId).WhereEqualTo();
QuerySnapshot snap = await QRef.GetSnapshotAsync();
Console.WriteLine("Waiting for 5 minutes..");
Task.Delay(300000).Wait();
Console.WriteLine("Waited for 5 minutes");
snap = await QRef.GetSnapshotAsync();
Console.WriteLine("Done without any error.");
```

**Comment by jskeet** [comment]
That code won't *quite* compile (as you haven't provided any arguments to `WhereEqualTo`) but having modified it very slightly, it was fine for me. Code is below - I already have the suitable environment variable set.

```csharp
using Google.Cloud.Firestore;

string projectId = "...";
string collectionId = "issue7635";

FirestoreDb DataBase = FirestoreDb.Create(projectId);
Query query = DataBase.Collection(collectionId).WhereEqualTo("x", "y");
var snapshot1 = await query.GetSnapshotAsync();
Console.WriteLine($"Snapshot 1 size: {snapshot1.Count}");
Console.WriteLine("Waiting for 5 minutes..");
Task.Delay(300000).Wait();
Console.WriteLine("Waited for 5 minutes");

var snapshot2 = await query.GetSnapshotAsync();
Console.WriteLine($"Snapshot 2 size: {snapshot2.Count}");
Console.WriteLine("Done without any error.");
```

(My collection has two documents in it; both have "x" fields - one with a value of "y" and one with a value of "z".)

Output:

```text
Snapshot 1 size: 1
Waiting for 5 minutes..
Waited for 5 minutes
Snapshot 2 size: 1
Done without any error.
```

My guess is that this is something within your network path, closing TCP connections early. Previously we've seen similar issues with misbehaving proxies.

**Comment by ertugrulsngr** [comment]
Is there anyting i can do for fixing this issue? I can read documents every 1-2 minutes to keep connection alive but is it right way?

**Comment by jskeet** [comment]
Well a better solution would be to find out what's closing the stream prematurely, really. We're already configuring Grpc.Core to send a keepalive packet once a minute, here: https://github.com/googleapis/gax-dotnet/blob/main/Google.Api.Gax.Grpc/ClientBuilderBase.cs#L26

I suggest you try the code on a few different networks if you can (but keeping everything else the same) to see if you can identify what's closing the connection.

**Comment by ertugrulsngr** [comment]
As you said, i changed my network and it worked. It's not a general problem but i don't know why i can't keep my connection alive.  I'll try to figure it out. Thanks a lot.

**Comment by jskeet** [comment]
Closing this issue now as a network-based problem.
