### ISSUE TITLE
Obsolete class recommends to use an incompatible type

### ISSUE THREAD

**Issue by lukepuplett** [googleapis/google-cloud-dotnet#7636]
#### Environment details

  - OS: macOS 12
  - .NET version: 6
  - Package name and version: Google.Cloud.Diagnostics.AspNetCore3 v4.3.1

#### Steps to reproduce

  1. Make a new dotnet ASP.NET (Core) 6.0 app from template
  2. Add NuGet package as above
  3. Configure IoC services container with

    services.AddGoogleDiagnosticsForAspNetCore(new AspNetCoreTraceOptions() { ServiceOptions = new ... })

The problem comes when trying to provide a value for `ServiceOptions`. The type of the property is obsolete but the type recommended to be used, `AspNetCoreTraceOptions` is not compatible.

![image](https://user-images.githubusercontent.com/5802524/147140630-a4d449f5-bcb2-4f93-a7da-8e1ae2bba5a5.png)

On the whole, the design is very peculiar to this C# developer for a few reasons.

- It's unintuitive as to what the correct code should be; i.e. the API design doesn't lead the developer to success, instead I have to decompile the classes and look how they work.
- There do not seem to be any good defaults setup.
- Tracing options and logging options use inconsistent patterns; one uses constructors the other a static `Create` method.
- There are two `TraceServiceOptions` classes with the same name between the two Google namespace that require importing/using to write this code which inevitably leads to a conflict and one of the using statements needs backing out and fully-qualified type names have to be used, which is annoying at best, and just poor coding to repeat type names.
- I am adding this code because on ephemeral environment compute, elastic scale Cloud Run, diags are buffered by default and so logging is never flushed. This is acknowledged, thank you, in the documentation but it seems obvious to me that the environment should be determinable by an environment variable set by GCP which is then used in your code to configure the correct buffering and thus Just Works for developers.

The UX of this library and its API, considering my other reported issue, is far below my expectations for a Google product. These are very basic issues.

            services.AddGoogleDiagnosticsForAspNetCore(
                new AspNetCoreTraceOptions()
                {
                    ServiceOptions = new TraceServiceOptions() // <=== what do I put here? 
                },
                new Google.Cloud.Diagnostics.Common.LoggingServiceOptions()
                {
                    Options = Google.Cloud.Diagnostics.Common.LoggingOptions.Create(bufferOptions: BufferOptions.NoBuffer)
                },
                null);

I want to reiterate that a better solution is no extra code needed. Your diags library should detect the ephemeral nature of its environment and configure itself properly. This would also lead to a reduction in time wasted by many developers wondering why their logged lines are not ending up in Cloud Run logging.

Thanks.

**Comment by jskeet** [comment]
As with the other issue, we'll look in January.

**Comment by amanda-tarafa** [comment]
Can you share the exact message you are getting. Neither [AspNetCoreTraceOptions](https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Trace/AspNetCoreTraceOptions.cs) or it's properties, nor [Common.TraceServiceOptions](https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/TraceServiceOptions.cs) which is the type of the property you are referring to, are deprecated.
As for initialization, Common.TraceServiceOptions has all settable properties so that's how you initialize it, by setting values in its properties.
I really don't see where you are getting the deprecated message from.

I'll reply to some of your other observations when we are back. But, the current status of the library, with some "duplicated" and deprecated classes across packages, is precisely to address the inconsistency issues that you mentioned. Of course, some inconsistencies may have zipped through either inadvertently or because standardizing was more complex than it was worth. On our next major version, early 2022, we'll remove all deprecated types and properties. And before that we'll be happy to fix any of the inconsistencies that may have inadvertently zipped through, but the main issue reported here does not seem to be one of those, again please share the deprecation message you are seeing and we can go from there.

**Comment by lukepuplett** [comment]
Hi Amanda, **this isn't important**, I have my app working and I don't need tracing, so don't rush to respond.

The confusion is because `Google.Cloud.Diagnostics.AspNetCore3.AspNetCoreTraceOptions` is obsolete and says to use `Google.Cloud.Diagnostics.AspNetCore3.AspNetCoreTraceOptions`, i.e. itself.

This is so bizarre that I thought it must be `Google.Cloud.Diagnostics.Common.TraceServiceOptions` that was deprecated but indeed it is fine. So the problem is now that weird self-referencing thing. 

This is from my decompiler:

![image](https://user-images.githubusercontent.com/5802524/147259105-22f4f98c-10c8-4769-a4d6-a7b6ccef1f64.png)

Cheers!

**Comment by lukepuplett** [comment]
Another note on the setting properties thing, it's best to initialize a class with good defaults and provide guidance in the constructor.

See

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/property

and

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/constructor

from this book:

https://www.amazon.co.uk/Framework-Design-Guidelines-Conventions-Development/dp/0321545613

Thanks

**Comment by amanda-tarafa** [comment]
I still can't see the problem deprecation wise. You say there's a self reference from a deprecated type recommending to use itself, but there's none. Certainly not in the code you pasted, but also none that I could find in our codebase. By the way, you don't need to disassemble the code as it is all public in this very same repo.

In the code you pasted, the deprecated type is `Google.Cloud.Diagnostics.AspNetCore3.TraceServiceOptions` recommending to use `Google.Cloud.Diagnostics.AspNetCore3.AspNetCoreTraceOptions`, those are two different types.
`Google.Cloud.Diagnostics.AspNetCore3.AspNetCoreTraceOptions` does have a dependency on `Google.Cloud.Diagnostics.Common.TraceServiceOptions`, which is a third type, same class name as the deprecated one but in a different namespace, and it is not deprecated.
I understand this might lead to some human confusion, but it won't cause a build error or make some aspects of the library unusable. There's really nothing wrong or bizarre about it and the potential for confusion will go away on the next major version.

As for the links on design guidelines, these are all very good general purpose guidelines, but guidelines nonetheless. There's much to be said about design decisions, I'm certain, and I'm sorry ours don't match your expectations, but they have all been actively and carefully made. Some of the rationale in the case of these option classes:
- All properties have sensible enough default values, that do not lead to failure or security holes. As for the timed buffer being the default, that was a decision made some time ago before serverless environments where so common place and changing that now would mean, possibly, silently breaking existing users. We prefer to ask serverless users to actively change the buffers.
- We don't define constructors very consciously, for several reasons, but mainly to avoid having to introduce breaking changes if new properties are needed. Or, in terms of the guidelines above, there's not a subset of the properties in these classes that are the "main ones", all are on equal footing and none need to be set for things to work in the general case.

There are still a couple other observations you made that I'll look into when I'm back, and I'll also try to add a couple more samples showing some config scenarios.

But I still need more info to find the issue you are reporting about the deprecated type recommending an incompatible type.

**Comment by lukepuplett** [comment]
Hey Amanda, happy new year.

You know I read your message weeks ago and couldn't sleep for the embarrassment. I'm so sorry to confuse you; I can't tell if I'm accidentally trolling you or the API is trolling me!

So finally I'm back at my desk today. I've already got a headache :)

Okay so I think the confusion is all because there's are two classes called `TraceServiceOptions` in two namespaces that are both likely to be automatically imported by the code editor (using) when configuring Google diags.

So, because the API is designed not to use constructors or static builders to assist in generating the right code, I instead have to float my mouse over the `ServiceOptions` property to see what type it needs. That reveals `TraceServiceOptions` so I enter the code as below.

![Code showing type mismatch error and obsolete warning](https://user-images.githubusercontent.com/5802524/148218267-04141969-5acd-4f6c-b991-4505c7b4998f.png)

Note that the class is not fully-qualified and as such the compiler picks `Google.Cloud.Diagnostics.AspNetCore3.TraceServiceOptions` which is obsolete and it recommends to use `Google.Cloud.Diagnostics.AspNetCore3.AspNetCoreTraceOptions` instead, so I alter my code.

![Code showing type mismatch](https://user-images.githubusercontent.com/5802524/148218957-d1affc2f-9b46-4de5-95f1-c4c81e5aa165.png)

Again, it's not fully-qualified so the compiler picks `Google.Cloud.Diagnostics.AspNetCore3.AspNetCoreTraceOptions` which is the type that was recommended. However, this type is no compatible.

So I guess what's happening is that the duplicate class name is causing terrible confusion since, unless I enter the fully-qualified class name, the compiler picks the wrong one and sends me into a strange spiral.

This works.
```
ServiceOptions = new Google.Cloud.Diagnostics.Common.TraceServiceOptions()
```

But the issue is that people don't code like that, because they don't expect duplicate class names within such _cohesive_ namespaces, so they look at the class names and type them in and accept any automatic imports (usings) that the editor assists with.

I hope this makes sense now :)

**Comment by lukepuplett** [comment]
By the way, this is now resolved and you may as well close the issue since there's nothing you can do that you may not already be working on.

The lessons are a) don't repeat class names in cohesive APIs b) consider a design that better guides the user so they fall into the pit of success.

I'll let you close it if you're cool.

**Comment by amanda-tarafa** [comment]
Yes, we know this may lead to confusion, but as I mentioned earlier, it is just a temporary state, necessary for making some requiered changes without breaking existing users. We are planning a new major version for the first half of 2022, and deprecated types will disappear then, and these clashes will go with that.

Just one comment on your feature request:

> but it seems obvious to me that the environment should be determinable by an environment variable set by GCP which is then used in your code to configure the correct buffering and thus Just Works for developers.
 
We don't have a reliable way to determine whether an environment is CPU limiting or not, and note that this is not just a characteristic of GCP environments, but of other cloud providers as well, and you may very well use our libraries there. Even if we could determine the environment, there's not a lot we could do to configure the code so that it "Just Works". For instance, using no buffer may greatly impact performance depending on the volume of entries an application is generating at any given time, as well as using sized buffers, which will affect latency of requests that make the buffer go over the limit. We really want users to be conscious of their configuration in these cases. I've added some extra documentation around buffering in #7645 that hopefully will help make things clearer.

**Comment by lukepuplett** [comment]
Thanks Amanda.

I take your point about these libs being used outside of GCP, though that sounds rare. I imagine you would be able to talk to the GCP platform teams and get them to set an environment variable so libs/customer code knows what GCP product they're running within. I mean, it's what environment variables are for.

There's currently some kind of default set by someone somewhere. The current default is not optimal for ASP.NET 6.0 on Cloud Run and I've had to change it to 1 second.

Again, a good API can guide the developer here such that specifying a value is made explicit and mandatory when configuring the lib.

Otherwise, maybe it's possible to hook into the sleep events in the OS and have diagnostic buffers rapidly purged, though that depends on whether the Cloud Run hypervizer sleeps the OS via ACPI, or uses other method.

https://cloud.google.com/compute/docs/instances/suspend-resume-instance

Just ideas. Cheers!
