### ISSUE TITLE
Streaming upload sample for Google.Cloud.Storage.V1

### ISSUE THREAD

**Issue by khuyennguyen7007** [googleapis/google-cloud-dotnet#7638]
With NodeJS, I could find an example for streaming upload at here: https://cloud.google.com/storage/docs/streaming#storage-stream-upload-object-nodejs and here: https://github.com/googleapis/nodejs-storage/blob/main/samples/streamFileUpload.js. But I don't see any examples of streaming upload with Google.Cloud.Storage.V1. So you who have experience with this, please show me an example or tell me how to find one.

Thank you very much.

**Comment by jskeet** [comment]
I'm afraid we don't support this in the .NET library. We only support uploading from a *readable* stream. You could try to write a custom stream-pair implementation where one stream reads (and blocks until more data is available) and another stream writes to make the new data available, but we don't have such a thing in the library at the moment, I'm afraid.

**Comment by khuyennguyen7007** [comment]
Thanks @jskeet for the answer. I'm using Google Cloud Speech-to-Text to transcribe audio from streaming input (a microphone) via gRPC. Everytime the server received an audio, it combined with the latest stream and wrote to a audio file. When you stop the stream, it will upload it to Google Cloud Storage. But if the audio file is too large, it takes a long time to upload. The smart way that I can do is stream it to Google Cloud Storage. But as you said, we don't have such a thing in the library at the moment.
Could you please show me the alternative way to achieve this? I have tried the GCS composing objects, but it doesn't work with audio file.

**Comment by jskeet** [comment]
> I have tried the GCS composing objects, but it doesn't work with audio file.

Could you clarify what you mean by "it doesn't work"? What exactly happens? That sounds like a perfectly reasonable approach.

(Please note that I'm on vacation until January 4th - I can add little comments occasionally, but I don't have time to try to work up any code examples etc until I'm back at work.)

**Comment by khuyennguyen7007** [comment]
Oh my mistake @jskeet , I tried with the wave file type so it doesn't work, I tried again with the mp3 file type and it's working perfectly. Thanks for your time, enjoy your vacation and have a good time. I will start my holiday tomorrow and I can enjoy it without worrying anymore.

**Comment by jskeet** [comment]
Hooray - I'm really glad it's sorted now. I'll close this issue now - enjoy your holiday!
