### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by lukepuplett** [googleapis/google-cloud-dotnet#7879]
Hello, me again.

Is there a way to see if my credentials are actually being sent over GRPC?

I have had this error for a day now and I am getting nowhere. My service account now has the unsafe **Cloud Datastore Owner** role. The service account JSON file is downloaded and presumably being read when creating my FirestoreDbBuilder. It doesn't work.

Something critical in the docs is missing.

#### Error message

`    Grpc.Core.RpcException: Status(StatusCode="PermissionDenied", Detail="Permission denied on resource project my-amazing-project.")`

#### Code

```csharp
builder.CredentialsPath = "/Users/lukepuplett/Documents/Git/MyProject/secrets/gcp-service-account.json";
builder.ProjectId = "my-amazing-project";
builder.EmulatorDetection = EmulatorDetection.EmulatorOrProduction;

if (OperatingSystem.IsMacOS())
{
    this.log.LogWarning("macOS detected. Assuming Apple Silicon and loading workaround GRPC adapter.");
    //
    // https://github.com/googleapis/google-cloud-dotnet/issues/7560#issuecomment-975414370

    builder.GrpcAdapter = GrpcNetClientAdapter.Default;
}
```
#### Context

The code is running locally as part of some automated tests that check my repository classes. I am not using the Firestore emulator since it needs Java JRE installing, so I figured I'd connect to a real instance, hence I'm having to workaround the ADC magic.

**Note** - This problem is also posted on SO with no responses.

https://stackoverflow.com/questions/70790257/wait-time-for-google-cloud-service-account-role-change-to-propagate

**Note** - I do not have support because I still have not yet been successful with Google's product offering yet.

Thanks.

**Comment by jskeet** [comment]
Hmm. That code looks okay. One aspect of using Grpc.Net.Client that I haven't looked into is the logging - I suspect the steps [listed for gRPC troubleshooting](https://cloud.google.com/dotnet/docs/reference/help/troubleshooting#how-can-i-trace-grpc-issues) may only work for Grpc.Core, which you aren't using in this case.

Are you able to test the same code with the same credentials on a Windows or Linux box? That way:

- We could get extra information about whether it's potentially an issue with how we're using Grpc.Net.Client
- We could see trace information that would include authentication

Another possibility is that it's a problem with the use of self-signed JWTs, which was introduced *relatively* recently.

Could you try downgrading to Google.Cloud.Firestore 2.4.0 and Google.Api.Gax.Grpc.GrpcNetClient 3.3.0 or 3.4.0? I don't *expect* this to make a difference (it hasn't caused any problems anywhere else) but it would be good to know.

**Comment by lukepuplett** [comment]
Thanks for such a prompt response. I'll take a look after the school run. I have a Windows machine, too.

In the meantime, is there any way to inspect the traffic? Or any logs on GCP that might shed light? And is there anything else that needs doing on the GCP/FS side other than assign the role to the service account? There's no sort of higher-level master access that needs configuring?

Thank you.

**Comment by jskeet** [comment]
I doubt that you'd be able to inspect traffic that ends up with PermissionDenied - at least, I don't know of any way to do so.
Nothing else should need configuring.

Note that we can't actually see what you're trying to do with the builder once it's configured. I'll put together a small console app that you can test with, so that we both know all the code that's being used. (I'll assume you're using .NET 6, so we can just use top-level statements etc...)

**Comment by jskeet** [comment]
Okay, here's a complete program that just lists the root collections:

```csharp
using Google.Api.Gax.Grpc;
using Google.Api.Gax.Grpc.GrpcCore;
using Google.Api.Gax.Grpc.GrpcNetClient;
using Google.Cloud.Firestore;

if (args.Length != 3)
{
    Console.WriteLine("Arguments: <project-id> <auth-file> <use-grpc-net-client>");
    Console.WriteLine("use-grpc-net-client should be true or false");
    return;
}

var adapter = bool.Parse(args[2])
    ? GrpcNetClientAdapter.Default
    : (GrpcAdapter) GrpcCoreAdapter.Instance;

var client = new FirestoreDbBuilder
{
    ProjectId = args[0],
    CredentialsPath = args[1],
    GrpcAdapter = adapter
}.Build();

var collections = await client.ListRootCollectionsAsync().ToListAsync();
Console.WriteLine($"{collections.Count} root collections:");
foreach (var collection in collections)
{
    Console.WriteLine(collection.Id);
}
```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Api.Gax.Grpc.GrpcNetClient" Version="3.6.0" />
    <PackageReference Include="Google.Cloud.Firestore" Version="2.5.0" />
  </ItemGroup>
</Project>
```

Just pass the project ID, path to the auth file, and then either "true" or "false" (for "use Grpc.Net.Client" or "use Grpc.Core") as arguments.

I've just tried this on Windows with both adapters, and they both worked fine.

**Comment by lukepuplett** [comment]
Hey, thanks for preparing this.

I'm on my Windows machine and you'll be relieved to hear that this doesn't work either, using `true` or `false`. So I'm going to delete and recreate my Firestore instance and the key for the service account and re-download and try again, in case GCP dropped an event or something and my role change never got propagated.

Interestingly, the Usage Logs tab for the service account is empty. That might be normal, but arguably this is a failed usage and I should be able to see attempts to access resources.

**Comment by lukepuplett** [comment]
Okay, it's my fault. Well, it's the Google console design team's fault. It turns out that the project name at the top of the screen is not the actual project name. It's an alias that serves no purpose.

Thanks for your help. Sorry for wasting everyone's time. If you're ever on a call with the Console UX team, please point them to this thread.

**Comment by lukepuplett** [comment]
The error message `PermissionDenied` is also wrong. That implies it found the target but permission was denied. I think `ResourceNotFound` would be a vast improvement. If I was Developer Aladdin, I'd wish for accurate error messages with lengthy explanations and hints at common mistakes and things to try.

**Comment by jskeet** [comment]
Error messages where a top-level resource can't be found are deliberately vague, as per [AIP-211](https://google.aip.dev/211). That avoids leaking information about the existence of the resource in question. It would be better if (as per the AIP) the message included "(or it might not exist)" - but the choice of PermissionDenied is a deliberate one.

**Comment by lukepuplett** [comment]
Yeah I thought you might say that :) The error should say _Either the resource could not be found or the request was not authorized. Check the address of the service you're trying to connect to and your credentials, and verify you have the correct server-side access rights._ and, as you say, remain consistent between failed attempts.
