### ISSUE TITLE
Grpc.core to be depreciated

### ISSUE THREAD

**Issue by jamesstanden** [googleapis/google-cloud-dotnet#7918]
**Is your feature request related to a problem? Please describe.**
I was considering using  Google.Analytics.Data.V1Beta (and possibly others) but note that it uses GRPC.core and this is, from what I understand, to be depreciated and no longer supported in May 2022.

 **Describe the solution you'd like**
I'm interested to understand if Google intends to continue using this depreciated assembly, take on its mainenance, use a different solution etc. for the .net framework.

 **Describe alternatives you've considered**
I have decided to code my own client objects directly to the REST api at this point for Google Analytics 4

**Comment by amanda-tarafa** [comment]
Please see #7574. Short story, although, at least for the time being, we'll continue to support Grpc.Core in one manner or another, we'll move the libraries to use Grpc.Net.Client by default. That should happen this quarter.

You can start using Grpc.Net.Client already if you wish to do so, see #7560 on how to do that.

**Comment by jskeet** [comment]
(Closing as it's covered in #7574.)
