### ISSUE TITLE
Google.Cloud.Firestore Xamarin Form Doc Support

### ISSUE THREAD

**Issue by MarkAM7** [googleapis/google-cloud-dotnet#7925]
Not sure if this is the proper place to post this but it would be great to have Documentation for Xamarin Forms and Maui configurations.

**Comment by jskeet** [comment]
@MarkAM7: I'm afraid neither of those are supported platforms. (We've heard of successful uses of Maui, but not Xamarin Forms.)

Once our current work to use Grpc.Net.Client by default comes to fruition (hopefully in the first half of this year) it's likely that Maui at least would be *easier* to support (in terms of the gRPC transport) - but authentication is still likely to be the stumbling block.

Unfortunately the .NET client libraries team doesn't have the resources to support every platform we'd like to - and that's as much about test infrastructure as anything else. We'd definitely like to expand the range of supported platforms over time, but I wouldn't expect it any time soon I'm afraid.

I'll close this issue now as we're not expecting to make any changes on the basis of it, but please do feel free to add more comments if you feel they're relevant.
