### ISSUE TITLE
Overwrite BigQuery tables

### ISSUE THREAD

**Issue by BasirBaidya** [googleapis/google-cloud-dotnet#7959]
Hi Team,

I am not able to overwrite tables while insert/update rows. Is there any option where I can mention to overwrite while inserting into tables? Here I am using this method:
````
response = await table.InsertRowsAsync(bqRows);
public Task<BigQueryInsertResults> InsertRowsAsync(IEnumerable<BigQueryInsertRow> rows, InsertOptions options = null, CancellationToken cancellationToken = default)
````

I can see `InsertOptions` provides me following configuration, but could not find for overwrite table:
```
public bool? AllowUnknownFields { get; set; }
public bool? SkipInvalidRows { get; set; }
public bool SuppressInsertErrors { get; set; }
public string TemplateSuffix { get; set; }
public bool AllowEmptyInsertIds { get; set; }
```
Could you please look into this and provide any update on this thread.

Thanks!

**Comment by jskeet** [comment]
As far as I'm aware, you can only update data using DML - see [the documentation for updating with DML](https://cloud.google.com/bigquery/docs/updating-data) for details. This isn't a limitation of the .NET client library - it's inherent in the nature of BigQuery. (Bear in mind that when defining BigQuery tables there's no primary key, so it would be difficult for an operation such as `InsertRows` to perform an update anyway.)

**Comment by jskeet** [comment]
That's assuming you want to selectively update rows, of course. If you want to simply truncate the existing data in the table and then insert the new data, that's certainly feasible with a load job (using a `WriteDisposition` of `Truncate`) - I don't know the simplest way of doing it with `InsertRows` though.

**Comment by BasirBaidya** [comment]
![screenshot-console cloud google com-2022 02 11-20_12_10](https://user-images.githubusercontent.com/52160978/153612781-d741fa64-7326-4a6a-832e-b42c51b81a6f.png)

When we open [GBQ ](https://console.cloud.google.com/bigquery)and from UI choosing 

> More Settings > Query Settings option on query editor top bar 

I am talking about above functionality, can we achieved through this library?
Thanks!

**Comment by jskeet** [comment]
Okay, so you're not wanting to call the InsertRows API after all - you're performing a query and wanting to truncate any existing table. Yes, that's entirely doable. If you don't need the results within your code, you can do this with `BigQueryClient.CreateQueryJob`, specifying QueryOptions like this:

```csharp
var queryOptions = new QueryOptions
{
    DestinationTable = client.GetTableReference(datasetId, tableId),
    WriteDisposition = WriteDisposition.WriteTruncate
};
var job = client.CreateQueryJob(sql, parameters, queryOptions)
    .PollUntilCompleted()
    .ThrowOnAnyError();
```

**Comment by BasirBaidya** [comment]
Here we can only pass one query inside `CreateQueryJob` function, Is there any way to pass `DataTable` or records in forms to overwrite the table

**Comment by jskeet** [comment]
I would suggest inserting into a temporary table, then to use `CreateCopyJob` to truncate the existing table.

I don't know whether that's atomic, mind you. That sort of detailed API-specific question is best put straight to the BigQuery team, and isn't really about the .NET client library - I suggest you follow one of the [BigQuery support options](https://cloud.google.com/bigquery/docs/getting-support) for that.

**Comment by iqb-dawn** [comment]
@jskeet I am facing the same issue at https://github.com/googleapis/google-cloud-dotnet/issues/8146 (thanks for the tip of @amanda-tarafa)

Since the data is eventual consistent, so the new table might be not available at the time performing truncate which means the issue remains the same. 

Just thinking loudly what is recommended way to recreate table every time as it is very common request.

**Comment by jskeet** [comment]
@iqb-dawn: It's not clear that this *is* exactly the same issue (or that it's a "very common request"). I'm watching the other issue - there's no need to draw attention in other places.

**Comment by jskeet** [comment]
Closing this issue now as I don't believe there's any change needed (or feasible) in the client libraries.
