### ISSUE TITLE
Sample request: setting endpoint on storage client

### ISSUE THREAD

**Issue by Breathtender** [googleapis/google-cloud-dotnet#7966]
We need samples added that describe how to set the endpoint for our storage clients.
Such as setting for localhost/emulator, or private/vpc, or for the soon to be added locational endpoints feature.

Sample tracker & Request:

https://docs.google.com/document/d/1aeL7jgs789s7xg9khTxGzGWkb4k-t6LUk-uqhhs1Vuw/edit#

**Comment by jskeet** [comment]
Please could refile this in https://github.com/GoogleCloudPlatform/dotnet-docs-samples? I'd transfer this issue, but that repo is in a different org.

**Comment by Breathtender** [comment]
Oh yes, thank you for pointing me.
