### ISSUE TITLE
BigQueryTable.InsertRows throws Table xx not found intermittingly

### ISSUE THREAD

**Issue by iqb-dawn** [googleapis/google-cloud-dotnet#8146]
#### Environment details

  - OS: Azure Function
  - .NET version: .NET Core 3.1
  - Package name and version: google.cloud.bigquery.v2, 2.1.0

#### Steps to reproduce

We are simply deleting table, creating table and then inserting data using,

            BigQueryTable table;
            try
            {
                table = dataset.GetTable(tableName);
                table.Delete();
            }
            catch
            {
            }
            finally
            {
                table = dataset.CreateTable(tableName, schemaBuilder.Build());
            }

            table.InsertRows(rows);

It works but sometimes it throws,

    Exception while executing function: BigQueryExport Google.Apis.Requests.RequestError
    Table xxxx not found. [404]
    Errors [
    	Message[Table xxxx not found.] Location[ - ] Reason[notFound] Domain[global]
    ]

    exception Google.GoogleApiException handled at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw:
       at Google.Apis.Requests.ClientServiceRequest`1+<ParseResponse>d__31.MoveNext (Google.Apis, Version=1.49.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
       at Google.Apis.Requests.ClientServiceRequest`1.Execute (Google.Apis, Version=1.49.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab)
       at Google.Cloud.BigQuery.V2.BigQueryClientImpl.InsertRows (Google.Cloud.BigQuery.V2, Version=2.1.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0)

We are using `google.cloud.bigquery.v2` version `2.1.0`.

**Comment by amanda-tarafa** [comment]
There are a couple of things you can check, since you are executing in a Azure Function:

- Is this code being called at the same time from several places, with the same table name? If that's the case, then two or more calls may be overlapping and one of them is attempting to delete the table that the other call already deleted.
- Is it possible that on a previous run the table creation failed (you didn't even get to insert data) so, when attempting to delete it, it is not there?

If none of the above checks are relevant, it is still very unlikely that this is a problem with the library itself, but most likely with eventual consistency. If that's the case it'll be best if you follow the [BigQuery support paths](https://cloud.google.com/bigquery/docs/getting-support) as the maintainers of this repo, we are not experts on each of the individual APIs.

**Comment by amanda-tarafa** [comment]
Ah, I see the error is in insert rows so my second check sugestion is not a valid one. The first one is still very relevant though.

**Comment by iqb-dawn** [comment]
Found in Google docs,

```
Table Creation/Deletion. Streaming to a nonexistent table returns a variation of a notFound response. A table created in response might not immediately be recognized by subsequent streaming inserts. Similarly, deleting or recreating a table can create a period of time where streaming inserts are effectively delivered to the old table. The streaming inserts might not be present in the new table.
```
https://cloud.google.com/bigquery/docs/error-messages#metadata-errors-for-streaming-inserts

The question is that how we can recreate table(delete/create/insert) using this librart?

**Comment by amanda-tarafa** [comment]
As with most eventual consistency issues you can either:

- Reconsider your design, as it is not "in line" with the API's own design, as stated on the documentation (sorry, I know this is probably something you don't want to hear):

  > Because BigQuery's streaming API is designed for high insertion rates, modifications to the underlying table metadata exhibit are eventually consistent when interacting with the streaming system. Most of the time, metadata changes are propagated within minutes, but during this period API responses might reflect the inconsistent state of the table.

  As an alternative design consider this proposal on a similar question: https://github.com/googleapis/google-cloud-dotnet/issues/7959#issuecomment-1036318021

- Or you can retry NotFound errors (with backoff).
  - You can either write your own retry logic on a catch statement when inserting. (Probably the easiest alternative)
  - Or you can use the `BigQueryClientBuilder` to specify a `Google.Apis.Http.HttpClientFromMessageHandlerFactory` that can be used in conjunction with `System.Net.Http.IHttpClientFactory` and DI. You can see how to set up the `IHttpClientFactory` on this [sample](https://github.com/googleapis/google-api-dotnet-client/blob/bfc9090dc2fae5b06a654328c4da7bc6b05b66f1/Src/Support/IntegrationTests/HttpClientFromMessageHandlerFactoryTests.cs#L38) and also take a look at these issues for more information:
    - https://github.com/googleapis/google-api-dotnet-client/issues/1756#issuecomment-775360014
    - https://github.com/googleapis/google-api-dotnet-client/issues/1775

    Then you configure your HTTP message handler to perform retries on specific error codes, you can see Microsoft Documentation on how to do that [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly).

Note that the library doesn't and won't attempt to mimick eventual consistency out of the box, as our goal is to have the library mimick the API's desing, behaviour and intentions.
