### ISSUE TITLE
Invalid log name in GetGcpConsoleLogsUrl 

### ISSUE THREAD

**Issue by CommitedSajmon** [googleapis/google-cloud-dotnet#8176]
`LoggerDiagnosticsOutput` produces wrong url for logs in Google Console in regards to `logName`.
In the below snippet logName parameter is set to `"abc"`.

```
builder.AddGoogle(new LoggingServiceOptions
                {
                    ProjectId = loggingOptions.ProjectId,
                    Version = loggingOptions.Version,
                    ServiceName = loggingOptions.ServiceName,
                    LoggerDiagnosticsOutput = Console.Out,
                    Options = Google.Cloud.Diagnostics.Common.LoggingOptions.Create(
                        logName: "abc",
                        logLevel: LogLevel.Debug
                });

```
It produces following url :
"GoogleLogger will write logs to: https://console.cloud.google.com/logs/viewer?resource=global&minLogLevel=100&logName=projects/*/logs/abc&project=*"

When I enter the link, following query parameters are there (logName is missing):
```
resource.type="global"
severity>=DEBUG
```

When I change the url manually to :
"GoogleLogger will write logs to: https://console.cloud.google.com/logs/viewer?resource=global&minLogLevel=100&logName=abc&project=*"

then it gives following output (correct logs are displayed)
```
resource.type="global"
logName="projects/*/logs/abc"
severity>=DEBUG
```

In generated url the prefix for logName shouldn't be included:
Instead of : `logName=projects/*/logs/abc` it should be just `abc`

Changing parameter from `_fullLogName ` to `_logName` below  should do the job
https://github.com/googleapis/google-cloud-dotnet/blob/2cac34761c11e939b6150fb70fd4409f40c7edb8/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Logging/GoogleLogger.cs#L223

**Comment by amanda-tarafa** [comment]
Thanks for reporting.

The URL we are currently generating is for [Legacy Logs Viewer which will soon be turned down](https://cloud.google.com/logging/docs/view/log-viewer-shutdown). It does work if you are using Legacy Logs Viewer mode.

The new URL you are proposing is for Logs Explorer, which is currently the default log viewer UI on the GCP console.

I've drafted #8178 which adds support for the Logs Explorer URL format. But before merging I'm going to get confirmation from the Logging UI team.

- First, it feels like Legacy Logs Viewer URLs should be redirected to Logs Explorer automatically.
- Second, I want to get confirmation on the proposed Logs Explorer URL format. It's currently working, but we need to make sure it will do so after Legacy Logs Viewer is turned down.

I'll update here when I know more.

**Comment by amanda-tarafa** [comment]
The Logs Explorer team has confirmed that Legacy Logs Viewer URLs will be supported indifenitely and should redirect correctly to Logs Explorer. The URL that we are printing is in the recommended format, the fact that it does not work is a bug server side that they are working on.
So, we won't make any changes on the library. I'm following the internal bug and as soon as it's fixed I'll comment here, but I'll close this issue now as there's really nothing we can do library side.

As a workaround, and for the time being, just use the modified URL that works. Sorry for the inconvinience.
