### ISSUE TITLE
Consider dropping internal Spanner logging and using normal MS logging

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#8201]
When the Spanner libraries first came out, the Microsoft.Extensions.Logging libraries were relatively new, and it wasn't clear how well adopted they'd be. It's likely that we'll depend on them in the next major version of GAX though.

I think it would be reasonable to drop the internal logging library from Spanner now.

I'll look into this in terms of feasibility.

**Comment by amanda-tarafa** [comment]
+1 to this.

**Comment by jskeet** [comment]
We've decided not to take the breaking change in the end, for the next major version - as the change didn't feel clean enough. We didn't have a good story on how to inject suitable loggers etc, and we didn't want to block the next version on it.

Instead, we'll write an implementation of the Spanner internal logger that delegates to an `ILogger`, and include that in the next major version as a way of at least allowing logging from Spanner. We'll then look at removing the internal logger in the future.

**Comment by jskeet** [comment]
The delegating code was in #8448. We should add some documentation for this when we're doing a documentation overhaul for the new major version.
