### ISSUE TITLE
Hi, i'm getting this error while deploying my dotnet Razor pages app to Google Cloud

### ISSUE THREAD

**Issue by DeveloperIrkhan** [googleapis/google-cloud-dotnet#8203]
Build started 25/02/2022 10:20:54 am.
Project "E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\BrainXero.Medgic.Web.csproj" on node 1 (Publish target(s)).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreGenerateAssemblyInfo:
Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
_DiscoverMvcApplicationParts:
Skipping target "_DiscoverMvcApplicationParts" because all output files are up-to-date with respect to the input files.
_CoreGenerateRazorAssemblyInfo:
Skipping target "_CoreGenerateRazorAssemblyInfo" because all output files are up-to-date with respect to the input files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
_CreateAppHost:
Skipping target "_CreateAppHost" because all output files are up-to-date with respect to the input files.
GenerateStaticWebAssetsManifest:
Skipping target "GenerateStaticWebAssetsManifest" because all output files are up-to-date with respect to the input files.
_GenerateScopedCssFiles:
Skipping target "_GenerateScopedCssFiles" because it has no outputs.
ResolveTagHelperRazorGenerateInputs:
Skipping target "ResolveTagHelperRazorGenerateInputs" because all output files are up-to-date with respect to the input files.
RazorCoreGenerate:
Skipping target "RazorCoreGenerate" because all output files are up-to-date with respect to the input files.
CoreGenerateRazorTargetAssemblyInfo:
Skipping target "CoreGenerateRazorTargetAssemblyInfo" because all output files are up-to-date with respect to the input files.
RazorCoreCompile:
Skipping target "RazorCoreCompile" because all output files are up-to-date with respect to the input files.
_CopyFilesMarkedCopyLocal:
  Touching "E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\obj\Release\net5.0\BrainXero.Medgic.Web.csproj.CopyComplete".
GetTypeScriptCopyToOutputDirectoryItems:
  Adding items with BuildAction=TypeScriptCompile to the same collections that will be populated (with items of other BuildActions) by the GetCopyToOutputDirectoryItems target
_CopyOutOfDateSourceItemsToOutputDirectory:
Skipping target "_CopyOutOfDateSourceItemsToOutputDirectory" because all output files are up-to-date with respect to the input files.
GenerateBuildDependencyFile:
Skipping target "GenerateBuildDependencyFile" because all output files are up-to-date with respect to the input files.
GenerateBuildRuntimeConfigurationFiles:
Skipping target "GenerateBuildRuntimeConfigurationFiles" because all output files are up-to-date with respect to the input files.
CopyFilesToOutputDirectory:
  BrainXero.Medgic.Web -> E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\bin\Release\net5.0\BrainXero.Medgic.Web.dll
_RazorCopyFilesToOutputDirectory:
  BrainXero.Medgic.Web -> E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\bin\Release\net5.0\BrainXero.Medgic.Web.Views.dll
  Touching "E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\obj\Release\net5.0\BrainXero.Medgic.Web.csproj.CopyComplete".
_CopyResolvedFilesToPublishPreserveNewest:
Skipping target "_CopyResolvedFilesToPublishPreserveNewest" because all output files are up-to-date with respect to the input files.
Publish:
  BrainXero.Medgic.Web -> E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\bin\Release\net5.0\publish\
_TransformWebConfig:
  Updating web.config at 'E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\bin\Release\net5.0\publish\web.config'
_PrepareForMsDeployPublish:
  Deleting file "E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\obj\Release\net5.0\PubTmp\BrainXero.Medgic.Web.SourceManifest.xml".
  Deleting file "E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\obj\Release\net5.0\PubTmp\BrainXero.Medgic.Web.Parameters.xml".
  Creating "E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\obj\Release\net5.0\PubTmp\BrainXero.Medgic.Web.SourceManifest.xml" because "AlwaysCreate" was specified.
  Creating "E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\obj\Release\net5.0\PubTmp\BrainXero.Medgic.Web.Parameters.xml" because "AlwaysCreate" was specified.
MSDeployPublish:
  Starting Web deployment task from source: manifest(E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\obj\Release\net5.0\PubTmp\BrainXero.Medgic.Web.SourceManifest.xml) to Destination: auto().
C:\Program Files\dotnet\sdk\5.0.201\Sdks\Microsoft.NET.Sdk.Publish\targets\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(140,5): error : Web deployment task failed. (Connected to the remote computer ("35.190.230.184") using the Web Management Service, but could not authorize. Make sure that you are using the correct user name and password, that the site you are connecting to exists, and that the credentials represent a user who has permissions to access the site.  Learn more at: https://go.microsoft.com/fwlink/?LinkId=221672#ERROR_USER_UNAUTHORIZED.) [E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\BrainXero.Medgic.Web.csproj]
C:\Program Files\dotnet\sdk\5.0.201\Sdks\Microsoft.NET.Sdk.Publish\targets\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(140,5): error : Make sure the site name, user name, and password are correct. If the issue is not resolved, please contact your local or server administrator. [E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\BrainXero.Medgic.Web.csproj]
C:\Program Files\dotnet\sdk\5.0.201\Sdks\Microsoft.NET.Sdk.Publish\targets\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(140,5): error : Error details: [E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\BrainXero.Medgic.Web.csproj]
C:\Program Files\dotnet\sdk\5.0.201\Sdks\Microsoft.NET.Sdk.Publish\targets\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(140,5): error : Connected to the remote computer ("35.190.230.184") using the Web Management Service, but could not authorize. Make sure that you are using the correct user name and password, that the site you are connecting to exists, and that the credentials represent a user who has permissions to access the site.  Learn more at: https://go.microsoft.com/fwlink/?LinkId=221672#ERROR_USER_UNAUTHORIZED. [E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\BrainXero.Medgic.Web.csproj]
C:\Program Files\dotnet\sdk\5.0.201\Sdks\Microsoft.NET.Sdk.Publish\targets\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(140,5): error : The remote server returned an error: (401) Unauthorized. [E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\BrainXero.Medgic.Web.csproj]
  Publish failed to deploy.
Done Building Project "E:\brainXero\Medgic app\BrainXero.Medgic\BrainXero.Medgic.Web\BrainXero.Medgic.Web.csproj" (Publish target(s)) -- FAILED.

Build FAILED.

**Comment by jskeet** [comment]
I'm afraid we'll need a lot more context information. We know that you're deploying to Google Cloud, but we don't know anything more than that - is this a VM? Is it Windows or Linux? How are you attempting to authenticate? Has this ever worked, or is this the first time you've tried to deploy?

Please give us more information, and we'll see if we can help you.

**Comment by jskeet** [comment]
Closing due to lack of information. We can reopen if we receive more information.
