### ISSUE TITLE
BigQuery.V2 Does Not Report Insert Errors

### ISSUE THREAD

**Issue by TMGMike** [googleapis/google-cloud-dotnet#8206]
**Is your feature request related to a problem? Please describe.**
I'm currently working on a GCP Cloud function as a "middle-man" between a desktop app (WPF) and BigQuery, written in .NET Core 3.1. I'm facing errors inserting a row into BQ, but the error is very vague. Looking at the Result object of client.InsertRow (following this sample: [TableInsertRows.cs](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/e04699dcbc54a026f9be8a8d93a3f605cb38059e/bigquery/api/Snippets/TableInsertRows.cs)), I see an enumerable Errors, which only points to the row it failed on, there's no mention of *why* it failed.

 **Describe the solution you'd like**
Data which describes *why* the insert failed, similar to the Java API approach in [TableInsertRows.java](https://github.com/googleapis/java-bigquery/blob/db37f8bf4684b27e800833ac5914eabd9271870a/samples/snippets/src/main/java/com/example/bigquery/TableInsertRows.java)

 **Additional context**
The code I'm using to insert data is as below (basic snippet as there's a lot more irrelevant checks etc.):

```csharp
public void InsertData(BigQueryInsertRow dataRow, string table = null)
{
    var client = BigQueryClient.Create(ProjectId);
    client.InsertRow(DatasetId, table ?? TableId, dataRow);
}

public async Task HandleAsync(HttpContext context)
{
    InsertData(new BigQueryInsertRow(eventData.EventId)
    {
        { "event_id", eventData.EventId },
        { "country", eventData.Country },
        { "app_version", eventData.ApplicationVersion },
        { "country_code", eventData.CountryCode },
        { "created_at", eventData.CreatedAt.ToUniversalTime() },
        { "component", component },
        { "event_data", JsonSerializer.Serialize(dataObject) } // Serialized as string because we don't know the fields that are passed into BQ schema
    }, 
        table: $"{component.ToString().ToLower()}_events");
}
```

The exact error I'm facing during insert:
```csharp
The service bigquery has thrown an exception: Google.GoogleApiException: Error inserting data. Status: NoRowsInserted
   at Google.Cloud.BigQuery.V2.BigQueryInsertResults.ThrowOnAnyError()
   at Google.Cloud.BigQuery.V2.BigQueryInsertResults.ThrowIfNotSuppressing(Nullable`1 suppressInsertErrors)
   at Google.Cloud.BigQuery.V2.BigQueryClientImpl.InsertRows(TableReference tableReference, IEnumerable`1 rows, InsertOptions options)
   at Google.Cloud.BigQuery.V2.BigQueryClient.InsertRow(TableReference tableReference, BigQueryInsertRow row, InsertOptions options)
   at Google.Cloud.BigQuery.V2.BigQueryClient.InsertRow(String datasetId, String tableId, BigQueryInsertRow row, InsertOptions options)
   at SimpleHttpFunction.Function.InsertData(BigQueryInsertRow dataRow, String table) in /workspace/Function.cs:line 34
```

**Comment by amanda-tarafa** [comment]
BigQueryClient.InserRow return [BigQueryInsertResult](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.BigQuery.V2/latest/Google.Cloud.BigQuery.V2.BigQueryInsertResults) which contains error information. I don't see your code processing the InserRow result.

**Comment by TMGMike** [comment]
> BigQueryClient.InserRow return [BigQueryInsertResult](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.BigQuery.V2/latest/Google.Cloud.BigQuery.V2.BigQueryInsertResults) which contains error information. I don't see your code processing the InserRow result.

Unfortunately, from what I can tell, this Error information only contains a record of which row it failed on, not why. Since I'm only inserting one row, it doesn't give me any useful information. Unless it's this `GetEnumerator()` object that I should be using?

**Comment by jskeet** [comment]
I'll try to reproduce and debug into this today.

**Comment by jskeet** [comment]
> So the error fails on creating the client? 

You wouldn't get that exception from creating the client.

Note that `InsertRow` (as opposed to `InsertRows`) automatically throws an exception if no rows were inserted. So in this case you need to dive into the `GoogleApiException` for more details. Here's a minimal example which does that:

```csharp
using Google;
using Google.Apis.Requests;
using Google.Cloud.BigQuery.V2;

if (args.Length != 3)
{
    Console.WriteLine("Arguments: <project-id> <dataset-id> <table-id>");
    return;
}

string projectId = args[0];
string datasetId = args[1];
string tableId = args[2];

var client = BigQueryClient.Create(projectId);

var row = new BigQueryInsertRow
{
    { "timestamp", DateTimeOffset.UtcNow },
    { "text", "Text value" }
};

try
{
    var result = client.InsertRow(datasetId, tableId, row);
    Console.WriteLine(result.Status);
}
catch (GoogleApiException ex)
{
    Console.WriteLine($"Message: {ex.Message}");

    Console.WriteLine("Individual errors:");
    foreach (var error in ex.Error?.Errors ?? Enumerable.Empty<SingleError>())
    {
        Console.WriteLine(error.Message);
        Console.WriteLine(error.Location);
        Console.WriteLine();
    }
}
```

And here are some error cases I've provoked (replacing my project name with my-project; issue8206 is the dataset ID):

## Table doesn't exist

```text
Message: Google.Apis.Requests.RequestError
Not found: Table my-project:issue8206.no-such-table [404]
Errors [
        Message[Not found: Table my-project:issue8206.no-such-table] Location[ - ] Reason[notFound] Domain[global]
]

Individual errors:
Not found: Table my-project:issue8206.no-such-table
```

## Table contains a required field not present in the row

```text
Message: Error inserting data. Status: NoRowsInserted
Individual errors:
Error in row 0. Missing required field: Msg_0_CLOUD_QUERY_TABLE.id.
```

## Table's "text" field is of type integer

```text
Message: Error inserting data. Status: NoRowsInserted
Individual errors:
Error in row 0. Cannot convert value to integer (bad value): Text value
text
```

## Table has no "timestamp" field

```text
Message: Error inserting data. Status: NoRowsInserted
Individual errors:
Error in row 0. no such field: timestamp.
timestamp
```

So I would expect all the errors really to be in the exception - you just need to iterate over them. Unfortunately we don't want to do that within the simple `Message` property of the exception (as it can get really huge), but I wonder whether we should add a method to `GoogleApiException` to provide all the data in one go (potentially as JSON...). @amanda-tarafa any thoughts on that?

**Comment by TMGMike** [comment]
Thanks for the detailed reply, this was very helpful. 

> You wouldn't get that exception from creating the client.

Ah, I didn't think so. Maybe GCF is doing something to the file to cause the incorrect line number. 
I tried with the code you suggested to iterate over the GoogleApiException, and found that the insert is failing on "created_at" with a `Invalid datetime string "2022-01-30T01:53:14.222123Z" Reason: invalid` - I just discovered the `AsBigQueryDate()` extension method, which resolved this particular error... although it loses the time, so that datetime string becomes `2022-01-30T00:00:00` in BQ... maybe this won't be a big deal though.

> I wonder whether we should add a method to GoogleApiException to provide all the data in one go (potentially as JSON...)
I think this could work, it didn't seem very clear when the `BigQueryInsertResult` object doesn't contain the errors, but makes sense if it throws for single rows. Perhaps the client library documentation that I was following could be updated to highlight error handling: https://cloud.google.com/bigquery/docs/samples/bigquery-table-insert-rows#bigquery_table_insert_rows-csharp - the current sample doesn't do anything for failures, I think it could be useful to show here for InsertRow and InsertRows.

**Comment by jskeet** [comment]
> Ah, I didn't think so. Maybe GCF is doing something to the file to cause the incorrect line number.

I've seen off-by-one errors in stack traces in all kinds of situations, to be honest. Never quite got to the bottom of it.

Thanks for the feedback on the documentation. It's slightly tricky as the pages are designed to have similar code in all languages, but we might be able to show error handling in all languages.

With regards to your data conversion issue, what's the BigQuery type of the field? If it's `datetime`, I suspect the problem is the `Z` at the end, which is valid for `timestamp` but not for `datetime`. (Are you able to change the field type to `timestamp`? That's probably more suitable for a `created_at` value anyway, I'd say.) Unfortunately we need to convert the value into a string of *some* format, and we don't know the BigQuery type at that point. Looking at [this code](https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2/BigQueryInsertRow.cs#L209), if you have an "unspecified" kind of value, that will be converted without the `Z` on the end. So if you want to stick to DateTime but use a UTC value, you could change your code to:

```csharp
{ "created_at", DateTime.SpecifyKind(eventData.CreatedAt.ToUniversalTime(), DateTimeKind.Unspecified) },
```

... which looks decidedly odd, but I *suspect* would work.

**Comment by TMGMike** [comment]
> Thanks for the feedback on the documentation. It's slightly tricky as the pages are designed to have similar code in all languages, but we might be able to show error handling in all languages.

No problem - yeah it might be difficult to document in a uniform way across languages, but would be a great addition if possible. I believe I saw some pages for Inserting in Java that had error handling.

>Are you able to change the field type to timestamp? That's probably more suitable for a created_at value anyway, I'd say.

Thanks, this worked perfectly - the schema was simple and the dataset only contains one entry from testing this function, so it was a simple task to remove and re-create with the new field type. I'm not sure why I didn't just go with `timestamp` to begin with, honestly 😆

**Comment by amanda-tarafa** [comment]
As an FYI I've sent googleapis/google-api-dotnet-client#2067 for review which should include the HTTP status code on the `GoogleApiException.Message`.
Also note that `GoogleApiException.Error.ErrorResponseContent` contains the raw content as we received it in the response. If it's a JSON the know fields should already be parsed in `RequestError`. But basically, there's no need for an extension method as it would just return the value of that property.

Note some of the changes are breaking, but only if code was dependant on the exact error message, which was not very useful to start with.
