### ISSUE TITLE
System.ArgumentException: 'Value BIGNUMERIC is undefined in BigQueryDbType Parameter name: name'

### ISSUE THREAD

**Issue by djzzmail** [googleapis/google-cloud-dotnet#8212]
- Search the issues already opened: https://stackoverflow.com/questions/71301009/system-argumentexception-value-bignumeric-is-undefined-in-bigquerydbtype/71301089#71301089

#### Steps to reproduce

  1. in GCP bigQuery declare id as type BIGNUMERIC 
  2. 
            foreach (BigQueryRow row in client.GetQueryResults(job.Reference))
            {
                //  MessageBox.Show(row.ToString);
                // var id = row["id"];
                //Console.WriteLine(row);
                richTextBox1.Text += row["id"] + " | " + row["storeno"] + " | " + row["data"] +"\n";
            }
received error 
System.ArgumentException: 'Value BIGNUMERIC is undefined in BigQueryDbType Parameter name: name'

Thanks!

**Comment by jskeet** [comment]
As noted in my answer, I'd expect this to be addressed in 2.4.0-beta01.

Which version are you seeing this in?

**Comment by djzzmail** [comment]
the issue is in v2.3.0
ok solved in Google.Cloud.BigQuery.V2 -Version 2.4.0-beta01
from nuget console type " Install-Package Google.Cloud.BigQuery.V2 -Version 2.4.0-beta01"
thanks.

**Comment by djzzmail** [comment]
the issue is in v2.3.0
ok solved in Google.Cloud.BigQuery.V2 -Version 2.4.0-beta01
from nuget console type " Install-Package Google.Cloud.BigQuery.V2 -Version 2.4.0-beta01"
thanks.
