### ISSUE TITLE
Detail="Permission 'documentai.processors.processOnline' denied on resource 

### ISSUE THREAD

**Issue by akmichael** [googleapis/google-cloud-dotnet#8237]
Hi,

I am getting permission denied on resource, with correct projectId, and processid. Problem could be in my code. 

    RpcException: Status(StatusCode="PermissionDenied", 
    Detail="Permission 'documentai.processors.processOnline' denied on resource 
    '//documentai.googleapis.com/projects/80xxxxxxxx87/locations/us/processors/axxxxxxx01f' (or it may not exist).", 
    DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1647240729.026000000","description":
    "Error received from peer ipv4:xxxxxxx.xxxx.xxxx","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1070,"grpc_message":
    "Permission 'documentai.processors.processOnline' denied on resource 
    '//documentai.googleapis.com/projects/80xxxxxxx87/locations/us/processors/axxxxxx1f'
     (or it may not exist).","grpc_status":7}")

**Prediction endpoint (shown in console)**
https://us-documentai.googleapis.com/v1/projects/80xxxxxxxxx87/locations/us/processors/a4xxxxxxxxxx01f:process

        `public async Task<ScanResultDataSet> DoScan()
        {
            string pdfFilePath = "D:\\invoice.pdf";
            var bytes = File.ReadAllBytes(pdfFilePath);
            ByteString content = ByteString.CopyFrom(bytes);

            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", @"D:\\poised-aleph-3xxx07-6axxxxxxxa03.json");

            DocumentProcessorServiceClient documentProcessorServiceClient = new DocumentProcessorServiceClientBuilder()
            .Build();

            ProcessRequest request = new ProcessRequest
            {
                ProcessorName = ProcessorName.FromProjectLocationProcessor("80xxxxxxx987", "us", "a4xxxxxxxxxx01f"),
                SkipHumanReview = false,
                RawDocument = new RawDocument
                {
                    MimeType = "application/pdf",
                    Content = content
                }
            };
            request.RawDocument.MimeType = "application/pdf";
            request.RawDocument.Content = content;

            ProcessResponse response = await documentProcessorServiceClient.ProcessDocumentAsync(request);
            Document docResponse = response.Document;
            Console.WriteLine(docResponse.Text);
            return null;
        }`

**Comment by akmichael** [comment]
@jskeet ,

as you mentioned, moved CredentialsPath , endpoint into DocumentProcessorServiceClientBuilder.


![image](https://user-images.githubusercontent.com/8349884/158157360-0171d305-3f42-4feb-9543-68a0c5234b56.png)

and added documentai api role for the projects. still getting Permission 'documentapi.processors.processonline' error.

**Comment by jskeet** [comment]
The user you've shown there isn't the service account though - the service account would have an icon like this: 
<img width="20" alt="image" src="https://user-images.githubusercontent.com/17011/158158177-df0f49a8-c71c-4e10-a72d-d10175e6bd7d.png">

That service account is the one you're using to try to authenticate, so that's the one that needs to have the right permission.

If the service account isn't shown in the list of principals, you can add it with the "Add" button at the top - use the email address that's in the service account JSON file (I'd expect it to be of the form *something*@*project-id*..iam.gserviceaccount.com) and add the Document AI API User role to the service account that way.

**Comment by akmichael** [comment]
@jskeet ,

it works with email id specified in json. super thanks.
