### ISSUE TITLE
How to get Entity list, KeyValue pair list, Tables using Document AI client librarary 

### ISSUE THREAD

**Issue by akmichael** [googleapis/google-cloud-dotnet#8248]
Hi,

I could not find documentation or any methods or library in document ai client library. Does client lib has any methods/properties to get list of keyvalue pairs, Tables objects idenfied in the scanning?

for example I am looking for List of <KeyFields> objects like Invoice No (key) and its value, Invoice Date (key) and it is value,etc. and table objects with fields with columnindex, rowindex, etc..  Similar to Microsoft Azure Form recognizer library result.

**Comment by jskeet** [comment]
> I could not find documentation or any methods or library in document ai client library.

Please see https://cloud.google.com/dotnet/docs/reference/Google.Cloud.DocumentAI.V1/latest/Google.Cloud.DocumentAI.V1 for the full reference documentation.

I'm afraid beyond that, the maintainers of this repository aren't going to be able to help you much - we know the details of the generated code, but we don't have expertise in all of the individual APIs. There's a [table example](https://cloud.google.com/document-ai/docs/process-tables) that might help you though, and the [`Page.Tables`](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.DocumentAI.V1/latest/Google.Cloud.DocumentAI.V1.Document.Types.Page#Google_Cloud_DocumentAI_V1_Document_Types_Page_Tables) property would no doubt be relevant too...

I'm going to close this issue now as we're not the right team to provide API-specific support - please see the [DocumentAI support page](https://cloud.google.com/document-ai/docs/getting-support) for more options of people who would be able to help you more.
