### ISSUE TITLE
Setting proxy for Google Analytics Data API (GA4)

### ISSUE THREAD

**Issue by pipe-chaiprapun** [googleapis/google-cloud-dotnet#8265]
I need to config proxy credential for GA4 Client library to pass it from http proxy server, unfortunately there isn't any rich documentation for this purpose on the web (or maybe I couldn't find them)

[Google Analytics Data API(GA4)](https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart-client-libraries#.net)

```
using Google.Analytics.Data.V1Beta;
using System.Net;

// Config Proxy Credential
WebProxy proxy = new WebProxy([proxy_url], [bypass]);
proxy.Credentials = new NetworkCredential([username], [password]);


// Google Analytics configuration
BetaAnalyticsDataClient client = BetaAnalyticsDataClient.Create();
RunReportRequest request = new RunReportRequest
{
  Property = "properties/" + propertyId,
  Dimensions = { new Dimension{ Name="city"}, },
  Metrics = { new Metric{ Name="activeUsers"}, },
  DateRanges = { new DateRange{ StartDate="2020-03-31", EndDate="today"}, },
};

// Make the request
var response = client.RunReport(request);
```

I have tried to assign object proxy to BetaAnalyticsDataClient or RunReportRequest object but I can't find it and I don't know how to use proxy configuration for GA4 library.

**Comment by jskeet** [comment]
Hmm... for a proxy *without* credentials, you'd just set the `grpc_proxy` environment variable. I'm not sure whether Grpc.Core supports proxies that require credentials. I'll ask internally. (It's possible that Grpc.Core doesn't support it, but that you could do so with Grpc.Net.Client. I'll investigate further.)

**Comment by jskeet** [comment]
Just as a workaround until I hear back - you could use the [Google.Apis.AnalyticsData.v1beta](https://www.nuget.org/packages/Google.Apis.AnalyticsData.v1beta/) library, which is our older REST-like client library. It's not as clean to use as the gRPC-based library, but it should be easier to support in terms of proxies. You should just be able to set `HttpClient.DefaultWebProxy` to use it for all requests.

You can *try* using the gRPC library with that as well, via Grpc.Net.Client:

- Add a reference to the Google.Api.Gax.Grpc.GrpcNetClient package
- Set the global `HttpClient` proxy (`HttpClient.DefaultWebProxy = proxy;`)
- Create your client specifying the gRPC adapter as shown below:

```csharp
BetaAnalyticsDataClient client = new BetaAnalyticsDataClientBuilder
{
    GrpcAdapter = GrpcNetClientAdapter.Default
};
```

I would *expect* that to use the default HttpClient proxy for everything... (Note that in our next major version of client libraries, hopefully in the next few months, Grpc.Net.Client will be used by default.)

**Comment by pipe-chaiprapun** [comment]
> Just as a workaround until I hear back - you could use the [Google.Apis.AnalyticsData.v1beta](https://www.nuget.org/packages/Google.Apis.AnalyticsData.v1beta/) library, which is our older REST-like client library. It's not as clean to use as the gRPC-based library, but it should be easier to support in terms of proxies. You should just be able to set `HttpClient.DefaultWebProxy` to use it for all requests.
> 
> You can _try_ using the gRPC library with that as well, via Grpc.Net.Client:
> 
> * Add a reference to the Google.Api.Gax.Grpc.GrpcNetClient package
> * Set the global `HttpClient` proxy (`HttpClient.DefaultWebProxy = proxy;`)
> * Create your client specifying the gRPC adapter as shown below:
> 
> ```cs
> BetaAnalyticsDataClient client = new BetaAnalyticsDataClientBuilder
> {
>     GrpcAdapter = GrpcNetClientAdapter.Default
> };
> ```
> 
> I would _expect_ that to use the default HttpClient proxy for everything... (Note that in our next major version of client libraries, hopefully in the next few months, Grpc.Net.Client will be used by default.)

Thank you for your help, but I have tried to install Google.Api.Gax.Grpc.GrpcNetClient and get notice
"Could not install package 'Google.Api.Gax.Grpc.GrpcNetClient 3.7.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

I'm not sure is it about my .net standard or other dependencies, where do I can find .net standard 2.1?

**Comment by jskeet** [comment]
Ah, okay - if you're using .NET 4.6.1 then you won't be able to use Google.Api.Gax.Grpc.GrpcNetClient unfortunately. (Support for Grpc.Net.Client on .NET Framework is complex even before we get to GAX.)

If you're able to use .NET Core 3.1 or .NET 6 instead of .NET Framework, that would solve that problem (as well as generally being a good idea for getting off legacy software - note that .NET 4.6.1 will be [unsupported by Microsoft as of the end of April](https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/)).

If you can't change which framework you're targeting, we're back to either finding out how to support proxies requiring authentication in Grpc.Core, or using [Google.Apis.AnalyticsData.v1beta](https://www.nuget.org/packages/Google.Apis.AnalyticsData.v1beta/).

**Comment by pipe-chaiprapun** [comment]
> Ah, okay - if you're using .NET 4.6.1 then you won't be able to use Google.Api.Gax.Grpc.GrpcNetClient unfortunately. (Support for Grpc.Net.Client on .NET Framework is complex even before we get to GAX.)
> 
> If you're able to use .NET Core 3.1 or .NET 6 instead of .NET Framework, that would solve that problem (as well as generally being a good idea for getting off legacy software - note that .NET 4.6.1 will be [unsupported by Microsoft as of the end of April](https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/)).
> 
> If you can't change which framework you're targeting, we're back to either finding out how to support proxies requiring authentication in Grpc.Core, or using [Google.Apis.AnalyticsData.v1beta](https://www.nuget.org/packages/Google.Apis.AnalyticsData.v1beta/).

Thank you for your help, for now I'll ask my PM that is it able to use .NET Core or not?

**Comment by jskeet** [comment]
> Thank you for your help, for now I'll ask my PM that is it able to use .NET Core or not?

Sorry, I don't quite understand that comment. Are you asking me a question, or just saying that you'll ask your PM about changing target?

**Comment by pipe-chaiprapun** [comment]
> just saying that you'll ask your PM

just saying that I'll ask my PM.

**Comment by jtattermusch** [comment]
FTR, for `grpc_proxy` setting in Grpc.Core see https://github.com/grpc/grpc/blob/master/doc/environment_variables.md
From the source code it looks that we might support proxy URLs that contain embedded user credentials (e.g see docs for `http_proxy` and `https_proxy`):
https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/src/core/ext/filters/client_channel/http_proxy.cc#L53
https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/src/core/ext/filters/client_channel/http_proxy.cc#L97

The user creds from the URL get translated into the "Proxy-Authorization" header.

**Comment by jskeet** [comment]
Thanks @jtattermusch. One thing to note @pipe-chaiprapun: depending on your credentials, you might *also* want to set the default `HttpClient` proxy; some credentials require fetching OAuth tokens, so you'd want that to go through the proxy too.

**Comment by pipe-chaiprapun** [comment]
> FTR, for `grpc_proxy` setting in Grpc.Core see https://github.com/grpc/grpc/blob/master/doc/environment_variables.md
> 
> From the source code it looks that we support proxy URLs that contain embedded user credentials (e.g see docs for `http_proxy` and `https_proxy`): https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/src/core/ext/filters/client_channel/http_proxy.cc#L53 https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/src/core/ext/filters/client_channel/http_proxy.cc#L97
> 
> The user creds from the URL get translated into the "Proxy-Authorization" header.

Thank you very much @jtattermusch, could you please guide me the example source code to use Grpc.Core to config proxy_url with username & password or configuration of grpc_proxy environment that contain embedded user credentials?

**Comment by jskeet** [comment]
@pipe-chaiprapun: Judging by the code, it's a matter of:

- Base64-encoding `user:password` as per RFC 7617
- Setting the environment variable to `auth@uri` (where auth is the base64-encoded credentials, and uri is the proxy URI.)

**Comment by pipe-chaiprapun** [comment]
> * RFC 7617

```
// Http Proxy Configuration
var authByte = Encoding.UTF8.Getbytes("username:password");
var base64 = Convert.ToBase64String(authByte);
Environment.SetEnvironmentVariable("http_proxy",  base64 + "@" + proxy_url);

// Google Analytics configuration
BetaAnalyticsDataClient client = BetaAnalyticsDataClient.Create();
RunReportRequest request = new RunReportRequest
{
  Property = "properties/" + propertyId,
  Dimensions = { new Dimension{ Name="city"}, },
  Metrics = { new Metric{ Name="activeUsers"}, },
  DateRanges = { new DateRange{ StartDate="2020-03-31", EndDate="today"}, },
};

// Make the request
var response = client.RunReport(request);
```

Did I do anything wrong? It's still not work

**Comment by jskeet** [comment]
Just to check: you put the *actual* username and password in the first line, right? Obviously I'm not expecting you to show us that, I'm just checking it's really not just "username:password" verbatim.

Other than that, it looks okay to me. Could you clarify "It's still not work" a bit - what *exactly* do you see? If there's an exception, please give the full stack trace.

**Comment by pipe-chaiprapun** [comment]
> Just to check: you put the _actual_ username and password in the first line, right? Obviously I'm not expecting you to show us that, I'm just checking it's really not just "username:password" verbatim.
> 
> Other than that, it looks okay to me. Could you clarify "It's still not work" a bit - what _exactly_ do you see? If there's an exception, please give the full stack trace.

Yes, I put the actual username & password and I got these exception error

- **Status** => Unavailable

- **Message** => Status(StatusCode="Unavailable", Detail="DNS resolution failed for service: analyticsdata.googleapis.com:443", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1648111378.302000000","description":"Resolver transient failure","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":1356,"referenced_errors":[{"created":"@1648111378.302000000","description":"DNS resolution failed for service: analyticsdata.googleapis.com:443","file":"..\..\..\src\core\ext\filters\client_channel\resolver\dns\c_ares\dns_resolver_ares.cc","file_line":360,"grpc_status":14,"referenced_errors":[{"created":"@1648111378.302000000","description":"C-ares status is not ARES_SUCCESS qtype=A name=analyticsdata.googleapis.com is_balancer=0: Could not contact DNS servers","file":"..\..\..\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_wrapper.cc","file_line":722,"referenced_errors":[{"created":"@1648111378.302000000","description":"C-ares status is not ARES_SUCCESS qtype=AAAA name=analyticsdata.googleapis.com is_balancer=0: Could not contact DNS servers","file":"..\..\..\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_wrapper.cc","file_line":722}]}]}]}")

- **Stack trace** =>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Analytics.Data.V1Beta.BetaAnalyticsData.BetaAnalyticsDataClient.RunReport(RunReportRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass10_0.<WithCallSettingsOverlay>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Analytics.Data.V1Beta.BetaAnalyticsDataClientImpl.RunReport(RunReportRequest request, CallSettings callSettings)
   at Profita.Program.SampleRunReport(String propertyId) in E:\Profita\Profita\Profita\Program.cs:line 61
   at Profita.Program.Main(String[] args) in E:\Profita\Profita\Profita\Program.cs:line 25

-

**Comment by jskeet** [comment]
Okay, so that looks like it's a DNS error rather than a problem creating the connection. If you try to ping analyticsdata.googleapis.com, what happens?

**Comment by jskeet** [comment]
Another thing to try - set the GRPC_DNS_RESOLVER environment variable to "native" so that it uses the OS DNS resolution rather than the ares library.

**Comment by pipe-chaiprapun** [comment]
> 

It say "Ping request could not find host analyticsdata.googleapis.com. Please check the name and try again."
but I test ping with my  laptop and it work.

**Comment by pipe-chaiprapun** [comment]
> Another thing to try - set the GRPC_DNS_RESOLVER environment variable to "native" so that it uses the OS DNS resolution rather than the ares library.

I tried, and still get error

Status(StatusCode="Unavailable", Detail="DNS resolution failed for service: analyticsdata.googleapis.com:443", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1648113029.415000000","description":"Resolver transient failure","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":1356,"referenced_errors":[{"created":"@1648113029.415000000","description":"DNS resolution failed for service: analyticsdata.googleapis.com:443","file":"..\..\..\src\core\ext\filters\client_channel\resolver\dns\native\dns_resolver.cc","file_line":202,"grpc_status":14,"referenced_errors":[{"created":"@1648113029.415000000","description":"OS Error","file":"..\..\..\src\core\lib\iomgr\resolve_address_windows.cc","file_line":93,"os_error":"No such host is known.\r\n","syscall":"getaddrinfo","wsa_error":11001}]}]}")

**Comment by pipe-chaiprapun** [comment]
> > Another thing to try - set the GRPC_DNS_RESOLVER environment variable to "native" so that it uses the OS DNS resolution rather than the ares library.
> 
> I tried, and still get error
> 
> Status(StatusCode="Unavailable", Detail="DNS resolution failed for service: analyticsdata.googleapis.com:443", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1648113029.415000000","description":"Resolver transient failure","file":"......\src\core\ext\filters\client_channel\client_channel.cc","file_line":1356,"referenced_errors":[{"created":"@1648113029.415000000","description":"DNS resolution failed for service: analyticsdata.googleapis.com:443","file":"......\src\core\ext\filters\client_channel\resolver\dns\native\dns_resolver.cc","file_line":202,"grpc_status":14,"referenced_errors":[{"created":"@1648113029.415000000","description":"OS Error","file":"......\src\core\lib\iomgr\resolve_address_windows.cc","file_line":93,"os_error":"No such host is known.\r\n","syscall":"getaddrinfo","wsa_error":11001}]}]}")

And this is the stack trace

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Analytics.Data.V1Beta.BetaAnalyticsData.BetaAnalyticsDataClient.RunReport(RunReportRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass10_0.<WithCallSettingsOverlay>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Analytics.Data.V1Beta.BetaAnalyticsDataClientImpl.RunReport(RunReportRequest request, CallSettings callSettings)
   at Profita.Program.SampleRunReport(String propertyId) in E:\Profita\Profita\Profita\Program.cs:line 62
   at Profita.Program.Main(String[] args) in E:\Profita\Profita\Profita\Program.cs:line 26

**Comment by pipe-chaiprapun** [comment]
> Okay, it really sounds like you need to talk to your network admin then. If nothing can resolve the server that hosts the API, that's a dead end.

Got it, Thank you so much.

**Comment by jskeet** [comment]
I'll close this issue now as I don't *believe* there's anything that should be needed from our side, but if you feel there's a problem with the client libraries, or the DNS works but then the proxy doesn't, please add a comment and I can reopen it.

**Comment by jtattermusch** [comment]
Just to double check: 
Did the logs indicate that gRPC has actually recognized the the setting done by `Environment.SetEnvironmentVariable("http_proxy",  base64 + "@" + proxy_url);`? On some platforms, when you set the env variable by `Environment.SetEnvironmentVariable()` the change won't be visible to the gRPC native layer.
E.g. see https://github.com/grpc/grpc/issues/19706
