### ISSUE TITLE
storage: Add Support for Dual Region Buckets

### ISSUE THREAD

**Issue by danielbankhead** [googleapis/google-cloud-dotnet#8272]
**FR:** Support dual region buckets.

The method for creating a bucket should accept a string with 2 regions concatenated with a '+' (e.g. `US-EAST1+US-WEST1`).

**System tests:**
- Verify a dual region bucket with specified regions can be created
- Verify a dual region bucket's `location` metadata is the specified dual region provided
- Verify a dual region bucket's `locationType` metadata is `dual-region`

[Internal] For details and coordination: [go/gcs-dpe-dual-region-milestones](http://go/gcs-dpe-dual-region-milestones)

**Comment by jskeet** [comment]
I'm not sure whether anything actually needs to be changed here for the library. If the user wants to specify anything other than the bucket name, they have to create a `Bucket` object in memory, and that already allows the dual region to be created. Sample code:

```csharp
using Google.Apis.Storage.v1.Data;
using Google.Cloud.Storage.V1;

var client = StorageClient.Create();
var bucket = new Bucket
{
    Name = "...",
    Location = "US-EAST1+US-WEST1"
};
var result = client.CreateBucket("...", bucket);
Console.WriteLine(result.Location);
Console.WriteLine(result.LocationType);
```

Output:

```csharp
US-EAST1+US-WEST1
dual-region
```

And in the Storage console:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/17011/159648321-6ea9308c-ef69-4461-aedf-eaeb4b5af713.png">

If that looks okay, I think we can just close this FR.
