### ISSUE TITLE
storage: Add Sample for Dual-Region Bucket Creation

### ISSUE THREAD

**Issue by danielbankhead** [googleapis/google-cloud-dotnet#8295]
**FR:** Add sample for dual-region bucket creation.

The sample for creating a bucket should accept a bucket name and 2 regions (e.g. `my-bucket`, `US-EAST1`, `US-WEST1`).

**Region tag:** `storage_create_bucket_dual_region`

**System tests:**
- Verify a dual region bucket with specified regions can be created
- Verify a dual region bucket's `location` metadata is the specified dual region provided
- Verify a dual region bucket's `locationType` metadata is `dual-region`

[Internal]
- For canonical samples: [go/dual-region-canonical-sample](http://go/dual-region-canonical-sample)
- For details and coordination: [go/gcs-dpe-dual-region-milestones](http://go/gcs-dpe-dual-region-milestones)

**Comment by jskeet** [comment]
@danielbankhead: Please could you refile this in https://github.com/GoogleCloudPlatform/dotnet-docs-samples? That's where the sample will actually live, and it makes things simpler if the FR is in the same repo as the change, so that merging the PR can close the issue.

**Comment by danielbankhead** [comment]
Absolutely. Created: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/1673
