### ISSUE TITLE
storage: support AbortIncompleteMultipartUpload LifecycleAction

### ISSUE THREAD

**Issue by BrennaEpp** [googleapis/google-cloud-dotnet#8316]
This feature adds the following capabilities to the existing GCS Lifecycle APIs:
- A new type of LifecycleAction -  `AbortIncompleteMultipartUpload` will be added. 

**If there are code changes other than documentation to implement this feature, please add the following system tests:**

- Validate that “AbortIncompleteMultipartUpload” lifecycle action can be set via Bucket Create, Patch and Update operations.
- Bucket Get and List operations should return the correct state of the lifecycle configuration on the bucket which includes the rules with the new action if present.

**If no code changes are required, verify that there are tests proving strings are properly propagated.**

Internal: see [go/gcs-dpe-olm-mpu](http://go/gcs-dpe-olm-mpu) for more info.

Please wait for approval from myself before merging or releasing this change so we can coordinate around release dates.

**Comment by amanda-tarafa** [comment]
As discussed internally we are in agreement that, since no code change is needed here, we won't write specific system tests. Closing...

**Comment by BrennaEpp** [comment]
Hi Amanda, are code changes needed to update these docs: https://developers.google.com/resources/api-libraries/documentation/storage/v1/csharp/latest/classGoogle_1_1Apis_1_1Storage_1_1v1_1_1Data_1_1Bucket_1_1LifecycleData_1_1RuleData_1_1ActionData.html#:~:text=Type%20%5Bget%2C%20set%5D-,Type%20of%20the%20action.%20Currently%2C%20only%20Delete%20and%20SetStorageClass%20are%20supported,-.%20More...

`Type of the action. Currently, only Delete and SetStorageClass are supported` - this should include this new action as well.

**Comment by jskeet** [comment]
That documentation is massively out of date - I don't know when it was last generated. (It looks like it may have been 2020, but I'm not sure what generated it.)

The current documentation is at https://googleapis.dev/dotnet/Google.Apis.Storage.v1/latest/api/Google.Apis.Storage.v1.Data.Bucket.LifecycleData.RuleData.ActionData.html

It is automatically generated from the Discovery doc, and published when the new package is published. No manual intervention is required, beyond making sure that the Discovery doc is up-to-date (and that's not a .NET-specific task).
