### ISSUE TITLE
Would be very useful to have a option to insert BigQuery table rows without streaming

### ISSUE THREAD

**Issue by MarekMalczewskiWavemaker** [googleapis/google-cloud-dotnet#8350]
Class Google.Cloud.BigQuery.V2.BigQueryTable has method InsertRow and couple of overloads. Unfortunately all overloads use insertAll API method which uses streaming buffer. In some cases would be useful to load data directly with no streaming.

**Comment by jskeet** [comment]
If there's an API method you think we should support, we'd be happy to do so. But BigQuery is designed as a Data Warehousing solution - if you're looking for something more like an OLTP database, it may not be the best fit.

Is there a specific BigQuery API that you want to want to see exposed?

**Comment by MarekMalczewskiWavemaker** [comment]
You are right. My suggestion does not make sense at all. I do not know why I thaught there is an API method to insert data without streaming.

Thank you.

**Comment by jskeet** [comment]
No problem - I'll close this now.
