### ISSUE TITLE
How add FilterExpression in the FilterExpressionList

### ISSUE THREAD

**Issue by dbemfica** [googleapis/google-cloud-dotnet#8416]
### About
[Google.Analytics.Data.V1Beta](https://googleapis.dev/dotnet/Google.Analytics.Data.V1Beta/latest/api/Google.Analytics.Data.V1Beta.html)

## Support request
I searched on https://googleapis.dev/dotnet/Google.Analytics.Data.V1Beta/latest/api/Google.Analytics.Data.V1Beta.FilterExpressionList.html to know how add Expressions in the Filter Expression List but not finded

Somebody know how do it?

**Comment by jskeet** [comment]
You just call `Add` on the list returned by the `Expressions` property - or you can do it with a collection initializer, e.g.

```csharp
var list = new FilterExpressionList
{
    Expressions = { filterExpression }
}
```

**Comment by dbemfica** [comment]
Thanks, worked
