### ISSUE TITLE
AppEngine Service response object doesn't contain labels 

### ISSUE THREAD

**Issue by shaybenh7** [googleapis/google-cloud-dotnet#8419]
Hi,
When I'm using the RestApi for AppEngine service here: 
https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services/get
I get my service labels like in the documentation.
https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services#resource:-service

BUT, when using the SDK the return object doesnt contain the property of Labels.
I was wondering how can I get my service labels using the SDK?
You can see here the property doesn't exist:
https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Google.Cloud.AppEngine.V1/Google.Cloud.AppEngine.V1/Service.g.cs#L96

I'm using Google.Cloud.AppEngine.V1 version 1.2.0

Thanks!

**Comment by jskeet** [comment]
The Google.Cloud.AppEngine.V1 API isn't based on the REST API, it's based on the gRPC API, which you can find [here](https://github.com/googleapis/googleapis/tree/master/google/appengine/v1). If you look at the [service proto](https://github.com/googleapis/googleapis/blob/master/google/appengine/v1/service.proto) you'll see that doesn't contain labels. Interestingly, the [RPC API for Service](https://cloud.google.com/appengine/docs/admin-api/reference/rpc/google.appengine.v1#google.appengine.v1.Service) *does* show labels - I need to investigate that discrepancy.

For now, I'd suggest using the Google.Apis.Appengine.v1 package which is a .NET library for the REST API. I'll ask internally about whether labels are likely to be exposed via the gRPC API, and why they're being shown in the API documentation but not in the protos.

**Comment by shaybenh7** [comment]
Will wait for your update then :)
I appreciate the response.

**Comment by jskeet** [comment]
Hi @shaybenh7, apologies for the delay. The protos have now been updated, the code has been regenerated, and I've just done a release. So if you update to version 1.4.0, you should fine the Labels property as you'd expect.

**Comment by shaybenh7** [comment]
Hi @jskeet 
This is great! thanks for the quick response :)
