### ISSUE TITLE
Using Access Token with Notebooks

### ISSUE THREAD

**Issue by joonvena** [googleapis/google-cloud-dotnet#8451]
Hi,
I'm trying to use the GoogleCredential to authorize calls using OAUTH2. I can get valid credentials by providing token eg.

```
var credential = GoogleCredential.FromAccessToken("xxx");
```

I can use this fine with Cloud Storage just by passing the GoogleCredential object directly to Create method.

```
var client = StorageClient.Create(credential);
```

This kind of functionality is not available in the Notebooks Create method. Is it possible to use this token based auth with the Notebook service?

**Comment by jskeet** [comment]
Once you have created a `GoogleCredential`, you can create a client builder and specify the `TokenAccessMethod` to use the credential. (We're making this all a bit simpler in the next major version).

So you'd use:

```csharp
var credential = GoogleCredential.FromAccessToken("xxx");
var client = new NotebookServiceClientBuilder
{
    TokenAccessMethod = credential.GetAccessTokenForRequestAsync
}.Build();
```

**Comment by joonvena** [comment]
Thanks for the reply! I tried with your example but i get error:

```
GoogleCredential' does not contain a definition for 'GetAccessTokenForRequestAsync' and no accessible extension method 'GetAccessTokenForRequestAsync
```

credential is type of GoogleCredential which doesn't directly have access to the GetAccessTokenForRequestAsync method.

**Comment by jskeet** [comment]
Whoops, my bad - that's due to explicit interface implementation. Your variable needs to be declared as type `ICredential`:

```csharp
ICredential credential = GoogleCredential.FromAccessToken("xxx");
var client = new NotebookServiceClientBuilder
{
    TokenAccessMethod = credential.GetAccessTokenForRequestAsync
}.Build();
```

(Or `ITokenAccess` would be fine.)

**Comment by jskeet** [comment]
@joonvena: Any updates on whether this works for you?

**Comment by joonvena** [comment]
@jskeet Sorry for the late reply. This indeed solved my issue :) Thanks!
