### ISSUE TITLE
Spanner Table are not roll backed when a transaction is aborted 

### ISSUE THREAD

**Issue by plemanach** [googleapis/google-cloud-dotnet#8456]
Hello,

I am getting this behavior when I wrap the creation of a table and insertion inside a transaction.

The spanner transaction is aborted  but the the table  is not removed only the row inserted is removed.

#### Environment details

  - OS: Windows 7
  - .NET version: .Net 6.0
  - Package name and version:  Google.Cloud.Spanner.Data Version=3.15.1

#### Steps to reproduce

Run this code:

`

                            using (var trans = connection.BeginTransaction())
 				{
					string createTableStatement =

					@"CREATE TABLE Venues (
                                            VenueId INT64 NOT NULL,
                                            VenueName STRING(100),
					) PRIMARY KEY (VenueId)";

					var cmd = connection.CreateDdlCommand(createTableStatement);

					cmd.Transaction = trans;

					cmd.ExecuteNonQuery();

					var dmlCommand = connection.CreateDmlCommand("INSERT INTO Venues(VenueId, VenueName) values(1, 'Test')");
					dmlCommand.Transaction = trans;
					dmlCommand.ExecuteNonQuery();

					throw new Exception("Something bad happened");

					trans.Commit();
				}`

**Comment by amanda-tarafa** [comment]
[Spanner transactions do not cover DDL operations](https://cloud.google.com/spanner/docs/transactions), so the behaviour you observed is expected.

`Google.Cloud.Spanner.Data` let's you use `SpannerCommand` for DDL operations as a convenience, but we understand this gives the false impression of transactions being applicable to DDL commands. I'll send a PR shortly to document this behaviour clearly.

**Comment by plemanach** [comment]
Thank you @amanda-tarafa for the clarification.
