### ISSUE TITLE
Control the grouping in exceptions in error reporting

### ISSUE THREAD

**Issue by SebastianStehle** [googleapis/google-cloud-dotnet#8544]
**Is your feature request related to a problem? Please describe.**
I use error reporting and like this feature, but the way errors are grouped is not transparent.

I have read the documentation about error reporting:

https://cloud.google.com/error-reporting/docs/grouping-errors

But the question is? Which exceptions are grouped. If I introduce a custom generic exception, you cannot configure grouping by yourself.

 **Describe the solution you'd like**
Provide a setting to decide in the client code, which exceptions should be grouped.

**Comment by amanda-tarafa** [comment]
This is a feature request for the product/API teams, as there's nothing in the API for us (client library) to configure how errors are groupped.
You can use the [Error Reporting Support routes](https://cloud.google.com/error-reporting/docs/support) for making this request.

In any case, there is some information in the [docs you linked](https://cloud.google.com/error-reporting/docs/grouping-errors#grouping) that apply to exceptions, including custom exceptions.

> - Exceptions are grouped together if they have the same exception type and similar stacks.
> - The stack trace is ignored for exceptions that are typically unrelated to the source location where they occur.
> - Errors without an exception stack are grouped together if they were created by the same log statement, approximated by the source location it was reported from (reportLocation).

I'll close this issue now as there's nothing we can do library side.
