### ISSUE TITLE
Example code for Blazor Server-Side?

### ISSUE THREAD

**Issue by crmckinnon** [googleapis/google-cloud-dotnet#8548]
Hi,

I'm curious if there is any example code for setting up Cloud Trace for Blazor Server-Side?

I've been trying to get it working using the following code example:
https://github.com/googleapis/google-cloud-dotnet/issues/6367#issuecomment-903852079

And the common Razor component used by this library:
https://github.com/IvanJosipovic/BlazorApplicationInsights/
https://github.com/IvanJosipovic/BlazorApplicationInsights/blob/master/src/BlazorApplicationInsights/ApplicationInsightsComponent.razor.cs

I currently seem to always get  a NullManagedTracer at this point.

**Comment by amanda-tarafa** [comment]
I'm sorry but we don't explicitly support Blazor so there's no guarantee that it will work out of the box.

The sample code you referenced should serve as the basis for specific implementations but maybe you are missing what would be the Middleware equivalent in Blazor? That's what should capture the incoming trace and initialize the tracer with it. I'm sorry I'm not familiar enough with Blazor to help you there.

I'll be closing this issue now as there's not much more we can do here, but do feel free to create new issues if you have trouble with the Diagnostics library independent from Blazor.
