### ISSUE TITLE
storage: Add Support for Updated Dual-Region Bucket API

### ISSUE THREAD

**Issue by danielbankhead** [googleapis/google-cloud-dotnet#8549]
[Internal]
- For details and coordination: [go/gcs-dpe-dual-region-milestones-api-refactor](http://go/gcs-dpe-dual-region-milestones-api-refactor)
- Implementation Example: https://github.com/googleapis/nodejs-storage/pull/1977

**Comment by jskeet** [comment]
Assigning to Anshul to check, but I wouldn't *expect* there to be anything to do here within the library, beyond potentially updating to the latest underlying Google.Apis.Storage.v1 library.

**Comment by jskeet** [comment]
Changing to p2 as we don't expect there to be anything to do here - we're just going to create the samples to *validate* that there's nothing to do before closing this.

**Comment by jskeet** [comment]
Closing as there's nothing to do in this repo, although https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/1746 still needs addressing in terms of samples.
