### ISSUE TITLE
Incorrect link for documentation about GAX4

### ISSUE THREAD

**Issue by manigandham** [googleapis/google-cloud-dotnet#8769]
All of the release notes link to https://cloud.google.com/dotnet/docs/reference/help/breaking-gax4 for GAX4 breaking changes, however this URL is a 404 page.

**Comment by jskeet** [comment]
Yes, we're aware - if really hoped that a push on Friday had fixed it, but apparently not. It's top of my priority list today..

**Comment by manigandham** [comment]
looks like this is page offers some info in the meantime: https://github.com/googleapis/google-cloud-dotnet/blob/main/docs/devsite-help/breaking-gax4.md

**Comment by jskeet** [comment]
Yes, that's the source of the document that *will* be at the link when it's working...

**Comment by manigandham** [comment]
This is live now, thanks

https://cloud.google.com/dotnet/docs/reference/help/breaking-gax4
