### ISSUE TITLE
Regional Endpoint cannot be set in SpeechClientBuilder in Google.Cloud.Speech.V1 version 3.0.0

### ISSUE THREAD

**Issue by Thomas2792** [googleapis/google-cloud-dotnet#8798]
I would like to use the European endpoint **eu-speech.googleapis.com** for the Google Cloud speech recognition C# API. An example is given for Python at https://cloud.google.com/speech-to-text/docs/endpoints#speech-sync-recognize-python.
Further documentation is available at https://github.com/googleapis/google-cloud-dotnet/blob/e04d0561688dec66080c8b7a96bb3ba021a035cb/docs/devsite-help/breaking-gax2.md#endpoints

#### Steps to reproduce

My credentials (type = service_acount) are stored in a json file. When setting up the SpeechClient as follows and calling Recognize(...) afterwards, an _invalid authentication_ exception is thrown:

```
using Google.Apis.Auth.OAuth2;
using Google.Cloud.Speech.V1;
...
SpeechClientBuilder scb = new SpeechClientBuilder
{
    Credential = GoogleCredential.FromFile("mycredentials.json")
};
scb.Endpoint = "eu-speech.googleapis.com"; // Without this line everything works.
SpeechClient speechClient = scb.Build();
speechClient.Recognize(...);
```

Exception:
```
Status(StatusCode="Unauthenticated", 
Detail="Request had invalid authentication credentials. 
Expected OAuth 2 access token, login cookie or other valid authentication credential. 
See [developers.google.com/identity/sign-in/web/devconsole-project]
(https://developers.google.com/identity/sign-in/web/devconsole-project).", 
DebugException="Grpc.Core.Internal.CoreErrorDetailException: 
{"created":"@1655809348.867000000","description":"Error received from peer ipv6:
[...]:443","file":"..\..\..\src\core\lib\surface\call.cc","file_line":953,"grpc_message"...
```

#### Environment details

  - OS: Windows 10 Pro
  - .NET version: 4.7.2
  - Package name and version:
Google.Cloud.Speech.V1 3.0.0
Google.Apis.Auth 1.56.0.0

**Comment by amanda-tarafa** [comment]
This is probably because the Speech API does not support self signed JWTs authentication with regional endpoints. I need to check this internally.

But to confirm, and as a workaround, can you try adding this to the builder initialization:

```csharp
SpeechClientBuilder scb = new SpeechClientBuilder
{
    Credential = GoogleCredential.FromFile("mycredentials.json"),
    UseJwtAccessWithScopes = false // Add this line of code to force access token fetching when using a regional endpoint.
};
scb.Endpoint = "eu-speech.googleapis.com"; // Without this line everything works.
SpeechClient speechClient = scb.Build();
...
```

**Comment by Thomas2792** [comment]
Awesome! Thanks a lot for the fast support! I can confirm that both approaches work, i.e. using either GoogleCredential or CredentialsPath.
From my side, the issue can be closed.
Thanks, Thomas

**Comment by jskeet** [comment]
Thanks - we'll keep working out what's happening internally, but I'm glad to hear it's working.

**Comment by LindaLawton** [comment]
For future reference:

This issue was cross posed from [How to use a regional endpoint in Google Speech-to-Text C# API?](https://stackoverflow.com/q/72699460/1841839)
