### ISSUE TITLE
Equivalent to Java's StorageBatch for C#

### ISSUE THREAD

**Issue by joshi-aparna** [googleapis/google-cloud-dotnet#8800]
Is there an equivalent to Java library's [StorageBatch](https://googleapis.dev/java/google-cloud-storage/latest/com/google/cloud/storage/StorageBatch.html) in the dotnet library? 

I am looking to delete more than one object from Google Cloud Storage at once. While I understand that there is no API to do so, batching requests might speed up the operation a bit and is a good workaround. However, I was not able to find an equivalent class for dotnet to achieve this.

**Comment by amanda-tarafa** [comment]
Google.Cloud.Storage.V1 is a handwritten library on top of Google.Apis.Storage.v1, the former aiming to improve usage over the latter. Although we don't have handwritten code to work with batch requests in Google.Cloud.Storage.V1, you can still use the feature directly from Google.Apis.Storage.v1. Here's a full working example, I've used insert bucket requests only for convenience, but that's not a requirement, you can mix different request types on a single batch request, you just probably want different callbacks.

```csharp
using Google.Apis.Requests;
using Google.Apis.Storage.v1.Data;
using Google.Cloud.Storage.V1;

namespace StorageBatch
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            string projectId = "CHANGE-ME";

            StorageClient storageClient = StorageClient.Create();

            BatchRequest batchRequest = new BatchRequest(storageClient.Service);

            var insertRequest = storageClient.Service.Buckets.Insert(new Bucket { Name = "my-first-bucket" }, projectId);
            var anotherInsertRequest = storageClient.Service.Buckets.Insert(new Bucket { Name = "my-second-bucket" }, projectId);

            batchRequest.Queue<Bucket>(insertRequest, InsertBucketCallback);
            batchRequest.Queue<Bucket>(anotherInsertRequest, InsertBucketCallback);

            await batchRequest.ExecuteAsync();
        }

        static void InsertBucketCallback(Bucket bucket, RequestError error, int index, HttpResponseMessage httpMessage)
        {
            if (error is null)
            {
                Console.WriteLine($"Bucket {bucket.Name} created succesfully");
            }
            else
            {
                Console.WriteLine(error.Message);
            }
        }
    }
}
```

**Comment by amanda-tarafa** [comment]
Closing, assuming everything has worked because of the heart emoji. Please feel free to leave a comment if you encounter any issues.
