### ISSUE TITLE
Is there any C# documentation so I could understand how to use the  google-cloud-dotnet? Thank you

### ISSUE THREAD

**Issue by prince272** [googleapis/google-cloud-dotnet#8807]

**Comment by shivgautam** [comment]
https://cloud.google.com/dotnet

Hope this helps in getting you started.

**Comment by amanda-tarafa** [comment]
And if you are particularly interested in how to use the client libraries in this repo, take a look at https://cloud.google.com/dotnet/docs/reference/help/getting-started and all the other topics that appear on the left hand side index under `Client Library Help`. Although samples there might be written for specific libraries the concepts explained apply to most libraries on this repo.
