### ISSUE TITLE
PubSub - PublisherClient/SubscriberClient.CreateAsync - Add a way to pass TokenAccessMethod

### ISSUE THREAD

**Issue by AlonShitrit** [googleapis/google-cloud-dotnet#8814]
**Problem**  - 
According to the [DOCS](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.PubSub.V1/latest/index) the recommended way to create high-performant PublisherClient/SubscriberClient  is to create them via the corresponding PublisherClient.CreateAsync/SubscriberClient.CreateAsync. The above-mentioned methods use the default implementation for retrieving the credential.
In my specific scenario, we cannot store the path to a credential file as an environment variable and hence cannot use these methods to create clients. 

**Solution** -
If possible I'd like to extend the CreateClientAsync method to also receive either an optional  Action<SubscriberServiceApiClientBuilder>/Action<PublisherServiceApiClientBuilder> to allow  further cofiguration of the clients.

 **Alternatives I've considered**
1. I've considered either using SubscriberServiceApiClient.PullAsync/PublisherServiceApiClient.PublishAsync but according to the docs it's not the recommended way for performance.
2. Use PublisherClientImpl/SubscriberClientImpl .ctors directly and create clients and shutdown method beforehand.

Solution 1 doesn't seem to really cut it as performance is an issue. Solution 2 does work but is a bit weird as it requires calling the Impl .ctors and pretty much copying the source code from CreateAsync.

**Comment by jskeet** [comment]
I'll look at this tomorrow.

**Comment by AlonShitrit** [comment]
Thanks on the prompt response :)

**Comment by jskeet** [comment]
There's already a class for customizing client creation: [`PublisherClient.ClientCreationSettings`](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.PubSub.V1/latest/Google.Cloud.PubSub.V1.PublisherClient.ClientCreationSettings) and the equivalent for `SubscriberClient`.

They both have a `Credentials` property of type `ChannelCredentials`. Once you've loaded a credential (e.g. via `GoogleCredential.FromJson`), and scoped it appropriately, you can call the `ToChannelCredentials` extension method to get a `ChannelCredentials` - you'll need a `using` directive for `Grpc.Auth`.

I wouldn't want to overload `CreateClient`/`CreateClientAsync` as a completely separate method of customizing client creation - but I do recognize that the above is pretty longwinded, especially as the "normal" way using a builder is significantly simpler these days. I suspect that adding to `PublisherClient.ClientCreationSettings` to either accept an `Action<PublisherApiClientBuilder>` or similar would be the way forward here - but until then, hopefully the above is helpful. Let me know if you need some more help implementing it.

**Comment by jskeet** [comment]
I'll close this now, as it sounds like the workaround has worked. We'll discuss adding the alternative ClientCreationSettings constructor within a team meeting, but I don't think it's urgent.
