### ISSUE TITLE
Release tooling: ignore non-conventional-commit lines at the end of a message

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#8828]
A commit message like this:

```text
feat: X
docs: Y

This does something
```

... should ignore the bit after the blank line. It's probably easiest to just skip everything after the first blank line, as a first approximation.

**Comment by amanda-tarafa** [comment]
I think that for breaking changes the footer is used to give more explanation?

**Comment by jskeet** [comment]
That's true. I'll see if I can find examples and work out exactly what to keep.
