### ISSUE TITLE
videointelligence: Generate apiv1beta3 client with support for streaming video #6109

### ISSUE THREAD

**Issue by tyronegroves** [googleapis/google-cloud-dotnet#8829]
Go, Python, and CPP clients have streaming video clients. I am not able to generate a client that will work with C#.

**Comment by jskeet** [comment]
Just to clarify, I assume you mean the v1p3beta1 API surface? You're right that we don't currently generate that for .NET.

I will ask the product team for their input as to whether they'd like a .NET library to be published for it. (I can give you steps to generate the library yourself if you really want to, but you wouldn't be able to publish it to NuGet etc, so it may prove tricky to use.)

**Comment by tyronegroves** [comment]
That is correct v1p3beta1.

**Comment by jskeet** [comment]
I've been in touch with the product team. They're trying to not encourage any new usage of the Streaming API at the moment while they evaluate improvements, so we won't be generating the v1p3beta1 client, I'm afraid.

I'll close this issue now as we're not expecting to take any further action. I do completely understand that this is frustrating, but we need to balance multiple factors when deciding whether or not to generate a particular version, and in this case the steer from the product team is clear. I know that's not what you wanted to hear :(

**Comment by tyronegroves** [comment]
@jskeet Can you give me the steps to generate the client?

**Comment by jskeet** [comment]
@tyronegroves: The process we normally go through is in https://github.com/googleapis/google-cloud-dotnet/blob/main/NEWAPI.md. You'd want to add `Google.Cloud.VideoIntelligence.V1P3Beta`. But I want to be completely clear that this really is an unsupported process - if it works, that's great, but if it doesn't I'm afraid I won't be able to spend time helping you on it.
