### ISSUE TITLE
what is System Environment Variable name for auth/disable_ssl_validation?

### ISSUE THREAD

**Issue by longtth** [googleapis/google-cloud-dotnet#8877]
I'm using Google Cloud in my .NET app inside a company with behind a proxy, "The network here has a MITM root certificate by design so all SSL traffic can be snooped" like [this question ](https://stackoverflow.com/questions/49310591/adding-a-custom-ca-root-certificate-to-gcloud-utility-or-python-generally-on-w) on Stackoverflow 

I've tried with google cloud CLI client and my function work well after set 

```
gcloud config set proxy/address {proxy-host} 
gcloud config set proxy/port 8080
gcloud config set proxy/type http
gcloud config set auth/disable_ssl_validation  True
```

but I can not find how to the ` auth/disable_ssl_validation True` to my .NET app, 
what is the system envirionment variable for `auth/disable_ssl_validation` name?

**Comment by amanda-tarafa** [comment]
You can disable SSL validaiton globally in a .NET application by setting [`ServicePointManager.ServerCertificateValidationCallback`](ServicePointManager.ServerCertificateValidationCallback) to a delegate that always returns `true`:

```csharp
ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;
```

As an alternative, you can also disable SSL validation on a per HTTP Client basis by setting [`HttpClientHandler.ServerCertificateCustomValidationCallback`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.servercertificatecustomvalidationcallback?view=netstandard-2.1) and then configuring the `HttpClient` to be used by Google .NET client libraries service clients. I can show you how to do that if you prefer, but I'd need to know exactly which client libraries you are using including version, the .NET targets of your application and how you are performing Auth. That is, you need to share a minimal but complete console app that shows how you are using Google .NET client libraries so I can build an example from there.

**Comment by amanda-tarafa** [comment]
I'm closing this issue now as I believe I've answered your question. Feel free to leave a comment if you fell otherwise or if you need more help with bypassing SSL validation for a specific Google .NET Client Library service client.
