### ISSUE TITLE
Offline Data Persistence Support for Firestore

### ISSUE THREAD

**Issue by AathifMahir** [googleapis/google-cloud-dotnet#8986]
**Is your feature request related to a problem? Please describe.**

Offline data persistence feature that caches a copy of the Cloud Firestore data that dotnet app is actively using, so app can access the data when the device is offline. Enables App to write, read, listen to, and query the cached data. When the device comes back online, Cloud Firestore synchronizes any local changes made by the app to the Cloud Firestore backend.

 **Describe the solution you'd like**

Using Sqflite or Any Other Local Database that suitable for Firestore to Persistent the Data Offline with the listener and adapter to make changes when's the connection is back online, exactly like the way firestore for Android, iOS, Flutter works

**Comment by amanda-tarafa** [comment]
I'll bring this feature request to the attention of the Firestore product team.

**Comment by amanda-tarafa** [comment]
I've heard back from the Firestore product team.

> The .NET Client library for Firestore is considered a server side client library and we don't intend to support offline usage.

I'll be closing this issue now as we won't act on this feature request. I appreaciate this is not the reply you wanted and I'm sorry about that.
