### ISSUE TITLE
Google.Cloud.Firestore 3.0.0 Grpc.Core.RpcException

### ISSUE THREAD

**Issue by achavezz94** [googleapis/google-cloud-dotnet#8991]
We recently upgraded Google.Cloud.Firestore from 2.3.1 to 3.0.0 and we started receiving the Exception below. If the amount of records are less than 25, it runs fine. If the count is greater than 25 the exception get thrown. Latest version that works without issue is 2.5.0.

#### Environment details

  - OS: Windows 10 Pro
  - .NET version: .NET 6.0
  - Package name and version: Google.Cloud.Firestore 3.0.0

#### Steps to reproduce

  1. Install Google.Cloud.Firestore 3.0.0 using Visual Studio Package manager
  2. Setup API call to GetAll() from a repo in Firestore
  3. Execute GetAll()
  4. Get exception thrown
  Exception:
Grpc.Core.RpcException
  HResult=0x80131500
  Message=Status(StatusCode="Internal", Detail="Error reading next message. InvalidDataException: Unexpected end of content while reading the message content.", DebugException="System.IO.InvalidDataException: Unexpected end of content while reading the message content.
   at Grpc.Net.Client.StreamExtensions.ReadMessageContentAsync(Stream responseStream, Memory`1 messageData, Int32 length, CancellationToken cancellationToken)
   at Grpc.Net.Client.StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.MoveNextCore(CancellationToken cancellationToken)")

**Comment by jskeet** [comment]
For diagnostic purposes, could you:

- Add a package reference to Grpc.Core
- Set the `GRPC_DEFAULT_ADAPTER_OVERRIDE` environment variable to `Grpc.Core`
- Try the existing code again?

If that works, then it's an incompatibility between Grpc.Core and Grpc.Net.Client.

When you say `GetAll`, please could you clarify which method you mean? (There's a FirestoreDb.GetAllSnapshotsAsync method, but it's not clear whether that's the one you mean.) If I can reproduce the issue, it'll definitely make it easier to make progress on it.

**Comment by achavezz94** [comment]
I followed the steps you suggested and I was able to successfully use "QuerySnapshot querySnapshot = await query.GetSnapshotAsync();" (GetAll method). Are the steps you outline the way to fix the incompatibility, or will there be an update? Thank you for your quick response.

**Comment by jskeet** [comment]
Well that's shown that it's something to do with Grpc.Net.Client, but I'd still really like to be able to reproduce this myself - I've just tried this code, for example:

```csharp
using Google.Cloud.Firestore;

string projectId = "...";

var db = FirestoreDb.Create(projectId);
var collection = db.Collection("...");

var snapshot = await collection.GetSnapshotAsync();
Console.WriteLine(snapshot.Count);
```

... and that returned me the 10,000 documents in the collection with no problems. If you could provide a similar complete example (with whatever steps are required to set up the data) that would be appreciated. Until I can reproduce the problem, it's going to be hard to diagnose it further.

**Comment by achavezz94** [comment]
`using Google.Cloud.Firestore;
using Newtonsoft.Json;
using System.Net;

HttpClient.DefaultProxy = new WebProxy();
var json = File.ReadAllText(Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS"));
Environment.SetEnvironmentVariable("GRPC_DEFAULT_ADAPTER_OVERRIDE", "Grpc.Core");

var cr = (Newtonsoft.Json.Linq.JObject)JsonConvert.DeserializeObject(json);

var projectId = (string)cr.GetValue("project_id");

FirestoreDb fireStoreDb = FirestoreDb.Create(projectId);

string collectionName = "Users";
Query query = fireStoreDb.Collection(collectionName);
QuerySnapshot querySnapshot = await query.GetSnapshotAsync();

var count = querySnapshot.Documents.Count;

Console.WriteLine(count);  `

This is the code we use for most of our calls prior to the changes you suggested. The collection has about 5000 records but the count varies from time to time. Sometimes I get about 400 and other times I get closer to 5000.

**Comment by jskeet** [comment]
> The collection has about 5000 records but the count varies from time to time. Sometimes I get about 400 and other times I get closer to 5000.

Even though you're querying the same collection? That's distinctly odd. I'd expect it to be absolutely consistent, if nothing's modifying the collection.

How much data is in each of your documents? (The collection I was using has fairly small test documents.)

**Comment by achavezz94** [comment]
That could be related to a proxy I'm using, but figured I would mention it in case it was related to the GRPC. The documents are  pretty large. Some of documents have nested fields with multiple fields as well.

**Comment by jskeet** [comment]
> That could be related to a proxy I'm using

If the proxy is doing odd things, it's entirely possible that that's the cause of the Grpc.Net.Client problem as well.

Are you able to test the code in an unproxied environment, by any chance? That would really help to narrow things down.

**Comment by achavezz94** [comment]
Unfortunately, I cannot test unproxied. Your suggestion did get rid of the error though. The record count is something we've seen before, prior to getting the Grpc.core.RpcException. 

Thank you for your help.

**Comment by jskeet** [comment]
> Unfortunately, I cannot test unproxied.

Could you clarify why that's infeasible? I'm imagining a process of:

- Create a new Cloud project (so that it can't interfere with anything else)
- Create a Firestore collection with 10,000 documents of "medium" size with test data
- Grant read access to a user who can test this outside your environment as well as inside it

Fundamentally, it looks like my code is equivalent to yours, and it works fine. The only way to find out whether this *is* a problem with the proxy is for someone to run the same code against the same collection with and without the proxy. The most straightforward way I can think of for doing that is shown above. Alternatively, you could deploy code to Cloud Run to access your Firestore collection without a proxy.

The variable record count aspect really does suggest it's probably a proxy issue - and while that may *currently* only show itself in only seeing partial results, it could have even more significant impacts in other cases, so I'd really think it would be in your best interests to diagnose that.
