### ISSUE TITLE
gRPC errors when updating to a new package version (2.4 and newer)

### ISSUE THREAD

**Issue by tmentz** [googleapis/google-cloud-dotnet#9009]
#### Environment details

  - OS:
  - .NET Standard:  2.1
  - Google.Cloud.Firestore: 3.0.0 
  - Xamarin.Forms: 5.0.0.2515

#### Steps to reproduce
1. When we follow the guidelines to set up Firestore Database (https://firebase.google.com/docs/firestore/quickstart) everything works fine with **old versions of the package** (Package 2.3.1 is the last working version).

2. When chaning to a newer package version **Google.Cloud.Firestore.DocumentReference.SetAsync**() will produce gRPC errors:

The Error message is:  {Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="**Bad gRPC response. Response protocol downgraded to HTTP/1.1.**")   at Google.Api.Gax.Grpc.ApiCallRetryExtensions+<>c__DisplayClass0_0`2[TRequest,TResponse].<WithRetry>b__0 (TRequest request, Google.Ap…}
 
3. Changing back to an version that is 2.3.1 or older will resolve the issue again. This is happening on Android and IOS. 

Is there a work around for this?

Thanks a lot and BR

**Comment by jskeet** [comment]
> This is happening on Android and IOS.

I'm afraid those aren't [supported platforms](https://cloud.google.com/dotnet/docs/reference/help/transports) to start with for this library, so I'm not entirely surprised to see that there are issues.

Fundamentally, it sounds like Grpc.Core works for you, but Grpc.Net.Client doesn't (that's the big change in GAX v4) - which means one option is to switch back to using the Grpc.Core implementation. See https://cloud.google.com/dotnet/docs/reference/help/transports for details on how to do this, but fundamentally it would be a matter of:

- Adding a reference to the Grpc.Core package
- Either setting the `GRPC_DEFAULT_ADAPTER_OVERRIDE` environment variable to `Grpc.Core`, or using the `FirestoreDbBuilder` and setting `GrpcAdapter = GrpcCoreAdapter.Instance`

It's possible that you can find other ways of getting Grpc.Net.Client to work on Android and iOS, and that would be better for the long term (as that's the long term direction of gRPC support) but I'm not in a position to investigate that myself, I'm afraid.

**Comment by tmentz** [comment]
Hi,

thanks for your fast reply. This seems to have solved our issue, but we will also try to find a way to make GrpC.Net.Client work in another way.
