### ISSUE TITLE
Support `HttpClient` span tracing without using `AddOutgoingGoogleTraceHandler`

### ISSUE THREAD

**Issue by kriswuollett** [googleapis/google-cloud-dotnet#9013]
I'm evaluating the usage of either, or both of, OpenTelemetry and Google.Cloud.Diagnostics. I cannot find the equivalent of [`OpenTelemetry.Tracing.TracerProviderBuilderExtensions::AddHttpClientInstrumentation`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/968dc52eb35b3a5c78b51f68de2e135746df5b3e/src/OpenTelemetry.Instrumentation.Http/TracerProviderBuilderExtensions.cs#L38) which adds child spans for HTTP requests without also adding span propagation. This is something that is possible as seen in OpenTelemetry's console export for a debugging API call of mine named `greeting` which makes an HTTP request to itself on `localhost` for `currentDateTimeOffset` and returns something like `{"message":"Hello, Kris. Today is 8/23/2022. The time is 4:31 PM"}`:

```
Activity.TraceId:          67a9020e3c07ac5849b3771e8094e93c
Activity.SpanId:           5556dd9133f22cc2
Activity.TraceFlags:           Recorded
Activity.ActivitySourceName: OpenTelemetry.Instrumentation.AspNetCore
Activity.DisplayName: /debugging/greeting
Activity.Kind:        Server
Activity.StartTime:   2022-08-23T21:06:04.4546850Z
Activity.Duration:    00:00:00.2880370
Activity.Tags:
    http.host: localhost:5000
    http.method: GET
    http.target: /debugging/greeting
    http.url: http://localhost:5000/debugging/greeting?name=Kris
    http.user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
    http.status_code: 200
   StatusCode : UNSET
Resource associated with Activity:
    service.name: my-api
    service.version: 1.0-local
    service.instance.id: b2e0b56b-f3d7-4ea7-a2aa-7b81f3266a14

Activity.TraceId:          67a9020e3c07ac5849b3771e8094e93c
Activity.SpanId:           8860279665d43dd5
Activity.TraceFlags:           Recorded
Activity.ParentSpanId:    5556dd9133f22cc2
Activity.ActivitySourceName: OpenTelemetry.Instrumentation.Http
Activity.DisplayName: HTTP GET
Activity.Kind:        Client
Activity.StartTime:   2022-08-23T21:06:04.4638920Z
Activity.Duration:    00:00:00.1671190
Activity.Tags:
    http.method: GET
    http.host: localhost:5000
    http.url: http://localhost:5000/debugging/currentDateTimeOffset
    http.status_code: 200
   StatusCode : UNSET
Resource associated with Activity:
    service.name: my-api
    service.version: 1.0-local
    service.instance.id: b2e0b56b-f3d7-4ea7-a2aa-7b81f3266a14
```

If I only use [`AddGoogleTraceForAspNetCore`](https://github.com/googleapis/google-cloud-dotnet/blob/be4557d649f36dcc0ea7c41aee4d82ff60bd2ade/apis/Google.Cloud.Diagnostics.AspNetCore3/Google.Cloud.Diagnostics.AspNetCore3/Trace/AspNetCoreTraceExtensions.cs#L32), then the two requests show up as separate server-side spans:

![CleanShot 2022-08-23 at 16 48 58@2x](https://user-images.githubusercontent.com/1834192/186273100-40f8fefd-5f05-4120-b4dc-fc9f6452c0e4.png)

But if I use something like `services.AddHttpClient("google").AddOutgoingGoogleTraceHandler()` and use the injected `IHttpClientFactory` to create a "`google`" `HttpClient` then I can see the parent child relationship like this as I'd like to see:

![CleanShot 2022-08-23 at 16 56 01@2x](https://user-images.githubusercontent.com/1834192/186273608-f1658bbb-6dc6-4ed7-b84e-f4c7678f3b46.png)

** Feature Request **

There are two parts to this feature request:

First, ideally, I'd like to have a configuration option to have child spans published to Google Trace from `HttpClient`s without the use of the `IHttpClientFactory` -- as shown above it is possible in the OpenTelemetry library. In addition to usually not needing to inject an `IHttpClientFactory` for my own code, tracing the duration of HTTP requests made by third-party libraries should work out of the box.

Second, being able to configure just having `HttpClient` spans without propagation using the `IHttpClientFactory` method should also be available.

If what I'm looking for is already possible, then please repurpose this issue as a documentation and example request, as it wasn't readily clear whether this was possible or not. The closest issue I could find regarding this issue was #800.

**Comment by jskeet** [comment]
Thanks for creating this issue. I've assigned it to Amanda, who is back from vacation tomorrow.

**Comment by amanda-tarafa** [comment]
I'll take a look at this next week and reply when I know more.

**Comment by kriswuollett** [comment]
Great, thanks! I am moving to use `IHttpClientFactory` in my own code by creating a span in a `DelegatingHandler` and making it easy to add through an extension on `IHttpClientBuilder`. Perhaps if any refactoring is done for supporting plain `HttpClient` usage, similar code could be exposed for end-users.

**Comment by amanda-tarafa** [comment]
Having looked into this in more detail it's not certain that would want to implement either of your feature requests.
- [Using IHttpClientFactory is MS's recommended approach](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests). Ideally all (modern) (third party) libraries have a way to integrate with `IHttpClientFactory`.
- There's no .NET public API that allows to intercept all HTTP incoming and outgoing requests (other than `IHttpClientFactory`). The OpenTelemetry implementation is relying heavily on reflection (of private members in most cases) and that's an approach we are not happy with.
- We could consider allowing configuration of non injected HTTP clients, but still the whole Google.Cloud.Diagnostics library depends on DI and you'd need to provide a `ServiceProvider` at some point, so not sure where the gain would be there?
- With the current implementation, you can create a child span for each outgoing HTTP request (performed with an `HttpClient` configured by calling `AddOutgoingGoogleTraceHandler`) without propagating the tracing context. See the documentation for [Custom Trace Context for outgoing HTTP requests](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Diagnostics.Common/latest#trace-outgoing-http-requests) and simply specify a propagation function that does nothing, i.e., that does not modify the request.

**Comment by amanda-tarafa** [comment]
@kriswuollett Any extra comments you want to add? 

As per my previous comment I'm tempted to close this request. I believe we are supporting current MS recommendations on `HttpClient` usage and interception, and adding new code to support other ways seems like a step backwards.

I understand that some third party libraries may not be up to date in recommendations, but that seems to be more of a request for them to modernize than for us to support alternatives?

**Comment by kriswuollett** [comment]
@amanda-tarafa I'd agree, from what it sounds like there wasn't an easy integration point that did not use reflection. I wouldn't expect the effort to go into building for clients that don't follow the best practices (`IHttpClientFactory`) which seems to be to just adding [`AddGoogleOutgoingTraceHandler`](https://github.com/googleapis/google-cloud-dotnet/blob/4e1b746e5843fca20f3859f1f65b9f5898659cdb/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common.Snippets/TraceSnippets.cs#L94).

**Comment by amanda-tarafa** [comment]
Perfect, thanks for replying back! I'll close these issue now, but of course create new ones if you encounter any other problems.
