### ISSUE TITLE
storage: add support for Autoclass 

### ISSUE THREAD

**Issue by cojenco** [googleapis/google-cloud-dotnet#9057]
Autoclass feature at the bucket level, allows for the automatic selection of the best storage class based on object metadata and access patterns. Currently, Autoclass supports  **new buckets** only - a bucket can be enabled for Autoclass only at creation, once disabled it cannot be enabled again

**System tests are only required in languages with code changes other than documentation:**
- Autoclass can be enabled via Bucket `Create`
- Autoclass can be disabled via Bucket `Patch` and `Update` operations
- Bucket `Get` operations should return the correct state of Autoclass on the bucket which includes the enabled boolean field and toggleTime timestamp field

request (internal): [go/sat-client-library-request](https://goto.google.com/sat-client-library-request)
details and coordination (internal): [go/gcs-dpe-autoclass](http://go/gcs-dpe-autoclass)
python-storage example: https://github.com/googleapis/python-storage/pull/791

Please wait for approval from myself before merging/releasing so we can coordinate around release dates.

**Comment by jskeet** [comment]
@anshuldavid13: This shouldn't need any changes in Google.Cloud.Storage.V1, other than a dependency update on Google.Apis.Storage.v1 when the changes are published there.

**Comment by jskeet** [comment]
It looks like Autoclass has existed for quite a while, actually - and is already in our dependencies. Closing this issue as I'm pretty sure we don't need to do anything else.
