### ISSUE TITLE
Pub/Sub client life-cycles should be more DI-friendly

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#9238]
This is effectively about addressing the latest comment in #5893.

If a singleton `PublisherClient` is registered in DI, I *suspect* it's entirely possible to lose published messages during shutdown due to buffering. We should work out what's required, and document it really clearly.

**Comment by Rishabh-V** [comment]
Thanks Jon. I am on vacation for the entire next week. I will start work on it after I am back. Thanks.

**Comment by Rishabh-V** [comment]
Will close it after docs are updated.
