### ISSUE TITLE
Workload identity federation support

### ISSUE THREAD

**Issue by neotrow** [googleapis/google-cloud-dotnet#9245]
I was wondering if there is a plan to add Workload identity federation support to the .net client libraries?

According to the [documentation](https://cloud.google.com/iam/docs/using-workload-identity-federation#generate-automatic) it is not supported yet and I also tried to point the `GOOGLE_APPLICATION_CREDENTIALS` to a credential configuration file but then it throws an error 
```
 Error creating credential from JSON or JSON parameters. Unrecognized credential type external_account.
```

**Comment by jskeet** [comment]
It's supported in the recently-released beta of Google.Apis.Auth. See [this issue](https://github.com/googleapis/google-api-dotnet-client/issues/2033) for more details and links to the PRs involved. (Note that for auth queries, that's the right repo to raise issues on, as that's where the code for Google.Apis.Auth lives.)
