### ISSUE TITLE
Simple away of finding intent for given text input using dialog flow API

### ISSUE THREAD

**Issue by kondareddy** [googleapis/google-cloud-dotnet#9254]
I have googled a lot, and found below sample code for my use case, but struck with an issue.

I have json for service account, want to use that as this approach works all users

**Error Details**
'The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.'

**Sample Code**
var query = new QueryInput
            {
                Text = new TextInput
                {
                    Text = text,
                    LanguageCode = "en-us"
                }
            };

            var sessionId = Guid.NewGuid().ToString();
            var agent = "JioRoom";
            var creds = GoogleCredential.FromFile(@"xx-73469c172245.json");
            var channel = new Grpc.Core.Channel(SessionsClient.DefaultEndpoint,
                          creds.ToChannelCredentials());

            var client = SessionsClient.Create();

            var dialogFlow = client.DetectIntent(
                new SessionName(agent, sessionId),
                query
            );

            var intent = dialogFlow.QueryResult.Intent;
            channel.ShutdownAsync();

**Comment by kondareddy** [comment]
Thanks for quick response.

I am not getting any exception now, execution struck with no response.

string json = File.ReadAllText(@"73469c172245.json");
            var client = new SessionsClientBuilder
            {
                JsonCredentials = json
            }.Build();

            **var dialogFlow = client.DetectIntent(**
                new SessionName(agent, sessionId),
                query
            );

Please help on this to move forward.

**Comment by jskeet** [comment]
That's an entirely different issue, and would be better raised *as* a different issue.

I suspect it's isn't a client library issue - I would encourage you to experiment on the "Try this method" page of [the REST method documentation](https://cloud.google.com/dialogflow/es/docs/reference/rest/v2/projects.agent.sessions/detectIntent). If the same request works there but fails when issued in the client library, please raise a new issue with all the relevant details, including precisely which library you're using, where the code is running (locally, on GCP, or somewhere else), what version of .NET you're using etc.

**Comment by kondareddy** [comment]
Ok, I will explore and update here

**Comment by jskeet** [comment]
@kondareddy: No, please don't update this issue. File a *new* issue if you believe there's a client library problem, or there's no need to add anything if you work out what was going on. If it's not a problem with the client library but with the Dialogflow API itself, please follow one of the general Dialogflow support routes - the maintainers of this repository don't have specialist knowledge of all the APIs.

**Comment by jskeet** [comment]
Apologies for writing `SessionsClient.Builder` earlier - it should indeed be `SessionsClientBuilder`.

Again, please file a *new issue* as this looks unrelated to the original auth issue.

Please make sure you include details of when you get the deadline exceeded vs when you get "failed to connect to all addresses" - the latter is usually due to a proxy or other network issue. Also include details of the target framework you're using - ideally provide a minimal console app and associated project file so that I can run it (using my credentials, of course).

**Comment by kondareddy** [comment]
@jskeet ,

I just tested on personnel laptop, sample worked. On domain/office laptop I will get google api whitelisted.
Thanks for support.
We can close this ticket now.

**Comment by jskeet** [comment]
(This issue was already closed, because you were reusing the one that was originally about auth. I'll just leave it closed.)
