### ISSUE TITLE
Firestore creation using application default credential

### ISSUE THREAD

**Issue by SamrawitMM** [googleapis/google-cloud-dotnet#9272]
#### Environment details

  - OS: Ubuntu 20.04
  - .NET version: 6.0.202
  - Package name and version: Google.Cloud.Firestore, V. 3.0.0

#### Steps to reproduce

   var firestoreDbBuilder = new FirestoreDbBuilder {
            ProjectId = CloudManager.ProjectId, 
            ChannelCredentials = GoogleCredential.FromFile("application_default_credentials.json").ToChannelCredentials()
            };
            var firestoreDb = firestoreDbBuilder.Build();

I configured application default credential and used it to create the firestore database, but the above code does not create the firestore database. 
Thanks!

**Comment by jskeet** [comment]
I suspect you should be scoping the credentials - but it would be simpler just to use the `CredentialsPath` property, as per [these docs](https://cloud.google.com/dotnet/docs/reference/help/client-configuration#credentialspath-jsoncredentials-or-googlecredential)

```csharp
var firestoreDbBuilder = new FirestoreDbBuilder
{
    ProjectId = CloudManager.ProjectId,
    CredentialsPath = "application_default_credentials.json"
};
var firestoreDb = firestoreDbBuilder.Build();
```

If that doesn't work, please give more information than "does not create the firestore database". What precise error do you get, and when?

**Comment by SamrawitMM** [comment]
Okay, I used Google.Cloud.Firestore, V. 3.0.0. And I have added the FirebaseManagementService scope to the credential. I am getting no errors in my console, that is why I am so confused.

` GoogleCredential credential = GoogleCredential.GetApplicationDefault();
            if (CloudManager.Credential.IsCreateScopedRequired)
            {
                credential = CloudManager.Credential.CreateScoped(FirebaseManagementService.Scope.CloudPlatform
                );
            }
            _firebaseManagementService = new FirebaseManagementService(
               new BaseClientService.Initializer()
               {
                  
                   HttpClientInitializer = credential,
                   ApplicationName = CloudManager.ApplicationName

               });`

**Comment by jskeet** [comment]
FirebaseManagementService is an entirely different API - I don't know what you're trying to do with it, or how that relates to the issue you reported.

Do you understand that creating a `FirestoreDb` doesn't actually do *anything* server-side? It's just creating a client object. You normally don't have to "create a database" explicitly - you can just start writing to the default one.

**Comment by SamrawitMM** [comment]
The logic I wanted to implement was, when users register on an app, I wanted to automatically create a custom databse( firestoredb) for each admin users by the server, this will reduce the manual work. So I used Google.Apis.CloudResourceManager to create the cloud project automatically, and then I used Google.Apis.FirebaseManagement  to create the firebase project automatically, and lastly I wanted to add the firestoredb inside the firebase project. And is there a way to do this on the server side? That makes sense if the firestoredb is done on the client-side.

**Comment by jskeet** [comment]
As far as I'm aware, there's no such step as "add the firestoredb inside the firebase project". (Firestore non-default databases are a thing, but it doesn't sound like that's what you're trying to do.)

To be honest, it doesn't sound like there's actually a client libraries question here - more Firebase/Firestore admin API questions, and the maintainers of this repository aren't API specialists. (We maintain libraries for hundreds of APIs.) For support on how to use the Firebase/Firestore APIs (the steps you need to go through), please follow one of the paths in the [Firebase support page](https://firebase.google.com/support).

Once you know the API calls you need to make, if you have problems *making* those calls with the .NET client libraries, please file a new issue - but I'll close this for now as it sounds like it was based on a misunderstanding of what the `FirebaseDb` class represents.
