### ISSUE TITLE
Missing RPC google.cloud.documentai.v1beta3 methods and classes in .Net Google.Cloud.DocumentAI.V1Beta3 namespace

### ISSUE THREAD

**Issue by InusBotha** [googleapis/google-cloud-dotnet#9332]
I can see that the RPC Reference for certain calls, such as to train a processor version using TrainProcessorVersionRequest, is available in the google.cloud.documentai.v1beta3 package, however, I don't see this being available for the .NET client library (Namespace Google.Cloud.DocumentAI.V1Beta3 (2.0.0-beta02)).

Any indication when this might be available for the .NET client library?

**Comment by jskeet** [comment]
2.0.0-beta03 has now been released. Do shout if you run into any problems.
