### ISSUE TITLE
Skip hash validation when it's unsafe when downloading Storage objects

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#9507]
In #1641 I proposed a `HashValidationMode` of `WhenAvailable` or similar - but we couldn't implement it at the time.

With the new `x-goog-stored-content-encoding` header, we may be able to implement this - see the [Node PR](https://github.com/googleapis/nodejs-storage/pull/2023/files) for an example.

Ideally, we'd want to make this the default - but that should only happen at the next major version of Google.Cloud.Storage.V1.

**Comment by amanda-tarafa** [comment]
FYI: There was some recent movement in internal issues around this. One of the issues with hash validations was that for files doubly compressed, Storage was removing the outer compression layer on serve, see #7154 as well.
@frankyn should know more about the state of things in general. There was also go/decompression-hash-validation and the newly added header seems to work towards the option of providing a strong signal regarding the hash matching the content.

**Comment by frankyn** [comment]
Hey folks, skipping validation can now be done through new headers `x-goog-stored-content-encoding` and `x-goog-stored-content-length`; It's not exactly what we are looking for as a boolean that would tell clients that decompression occurred (it can happen outside of GCS' control in GFE); so this is the next best thing. Go and [Python](https://github.com/googleapis/google-resumable-media-python/pull/346) have this support for download.

**Comment by amanda-tarafa** [comment]
Assigning to @jskeet as per internal discussion with the wider team.
