### ISSUE TITLE
Establish a trace context in a non-http context

### ISSUE THREAD

**Issue by christopheblin** [googleapis/google-cloud-dotnet#9856]
I've seen #5897 and #9157 and #9476 and https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Diagnostics.AspNetCore3/latest#custom-trace-context-example

However, after multiple tries, I'm not able to wrap my head around ITraceContext when I want both the "default" context (i.e for HTTP context) and my own context for non-http context, so I'm asking for help here...

Basically, I have a cloud run with an HTTP API where the default "integration" is OK (i.e when I do _logger.LogInformation("xxx"), i can see this log statement when I do "Show logs for the trace" from logs explorer)

Now, this cloud run also connects to ActiveMq, and I do not manage to create a new trace for each message received

Here is where I am stuck :  

```
    private readonly IServiceProvider _sp;    

    //omitted details to establish connection to ActiveMq, jsut showing the method to handle one message

    private void Consume(IMessage message)
    {
        using var scope = _sp.CreateScope();
        //TODO: correctly configure GCP tracing & logging
        var logger = scope.ServiceProvider.GetRequiredService<ILogger<ActiveMQConsumer>>();
        var txtMessage = message as ITextMessage ?? throw new IllegalStateException("not an ITextMessage, impossible !!!");
        logger.LogInformation("received ActiveMQ message {}", txtMessage.Text);        
    }
```

I can provide details about what I've tried if necessary

**Comment by amanda-tarafa** [comment]
I'll try to reply tomorrow at some point, else on Friday.

**Comment by amanda-tarafa** [comment]
Ok, if I understand your question correctly you need to look at docs on [Establishing traces on non HTTP requests ](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Diagnostics.Common/latest#one-trace-per-requestevent) when you want to trace your ActiveMq activity (know that I'm not at all familiar with ActiveMq). So, integrating the code example from that link into your code, ir could look something like this:

``` csharp
private void Consume(IMessage message)
{
    using var scope = _sp.CreateScope();
    EstablishTrace(scope, message);
    var logger = scope.ServiceProvider.GetRequiredService<ILogger<ActiveMQConsumer>>();
    var txtMessage = message as ITextMessage ?? throw new IllegalStateException("not an ITextMessage, impossible !!!");
    logger.LogInformation("received ActiveMQ message {}", txtMessage.Text);        
}

private void EstablishTrace(IServiceScope scope, IMessage message)
{
    ITraceContext traceContext = GetTraceContextFromIncomingMessage(message);
    var tracerFactory = scope.GetRequiredService<Func<ITraceContext, IManagedTracer>>();
    IManagedTracer tracer = tracerFactory(traceContext);
    ContextTracerManager.SetCurrentTracer(tracer);
}

private ITraceContext GetTraceContextFromIncomingMessage(IMessage message)
{
    // You need to extract the trace context from the incoming message and create
    // an instance of ITraceContext (you can use Google.Cloud.Diagnostics.Common.SimpleTraceContext).
    // If the incoming message does not contain a trace context, you can create a new one by creating a new
   // trace ID.
}
```

Let me know if this helps.

**Comment by christopheblin** [comment]
HI @amanda-tarafa 

I tried the solution and now I do not see logs anymore on GCP 😒 

However, I did fallback to Console.WriteLine and I do not see that either, meaning the server is simply not pulling messsages anymore so I really have another problem somewhere 😱 

I've yet to find some time to understand what is going on before bothering you, but be assured that I will report back here as soon as possible 😄 

Anyway, the code I added is the following :  
```
    private void Consume(IMessage message)
    {       
        using var scope = _sp.CreateScope();
        EstablishTrace(scope, message);
        var logger = scope.ServiceProvider.GetRequiredService<ILogger<ActiveMQConsumer>>();
        var txtMessage = message as ITextMessage ?? throw new IllegalStateException("cannot deconstruct message (should not happen)");
        Console.WriteLine("Received from console {}", txtMessage.Text);
        logger.LogInformation("Received from logger {}", txtMessage.Text);
    }

    private void EstablishTrace(IServiceScope scope, IMessage message)
    {
        //see https://github.com/googleapis/google-cloud-dotnet/issues/9856#issuecomment-1425617476
        var tracerFactory = scope.ServiceProvider.GetService<Func<ITraceContext, IManagedTracer>>();
        if (tracerFactory == null) //GCP tracing not available
            return;
        Console.WriteLine("Enabling GCP tracing");
        var traceContext = new SimpleTraceContext(Guid.NewGuid().ToString().Replace("-", ""), null, true);
        var tracer = tracerFactory(traceContext);
        ContextTracerManager.SetCurrentTracer(tracer);
    }
```

**Comment by amanda-tarafa** [comment]
@christopheblin I'll be closing this one until you are ready to provide more information, and that now seems to depend on #9948 . Happy to reopen as soon as you are ready.
