### ISSUE TITLE
URLs to whitelist

### ISSUE THREAD

**Issue by ksangita** [googleapis/google-cloud-dotnet#9876]
Hi Google API team, 
Can you please share the URLs that the client library 
https://www.nuget.org/packages/Google.Cloud.Iam.Credentials.V1 
https://github.com/googleapis/google-cloud-dotnet 

access to connect to google API to generate JWT token using SA Json Credentials file. I am unable to locate the URLs that are supposed to be whitelisted except https://*.googleapis.com/. 

Right now when I run the project on my local machine it works fine, But when I run the same on the server where external URLs are blocked, it doesn't work and gives an error 

`Status(StatusCode="Unavailable", Detail=" failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1649326888.179000000","description":"Failed to pick subchannel","file":"......\src\core\ext\filters\client_channel\client_channel.cc","file_line":3009,"referenced_errors":[{"created":"@1649326888.179000000","description":"failed to connect to all addresses","file":"......\src\core\ext\filters\client_channel\lb_policy\pick_first\pick_first.cc","file_line":398,"grpc_status":14}]}") `

Currently, I have identified the below URLs which are already whitelisted by my infra team but still getting the above error message. 

Whitelisted URLs - https://*.googleapis.com/ 

Kindly help me whitelist the respective URLs used by this library to connect Google IAM API.  Please share the list of URLs that I should whitelist on the hosting server machine if I missed any.

**Comment by jskeet** [comment]
Presumably you're behind a proxy - Google.Cloud.Iam.Credentials.V1 is a gRPC-based library, so the problem may well be in your proxy configuration.

The library itself connects to iamcredentials.googleapis.com, but it does so using gRPC, not just HTTP/1.1 requests. It's hard to say whether that's the problem.

We've got some initial diagnostic steps listed at https://cloud.google.com/dotnet/docs/reference/help/troubleshooting#how-can-i-diagnose-proxy-issues - I suggest you look through those to start with.

**Comment by jskeet** [comment]
@ksangita: Are you unblocked now? I'd like to close this issue if so - and if not, please let us know what more information you need.

**Comment by jskeet** [comment]
Closing due to lack of further information. We can reopen later if necessary.
