### ISSUE TITLE
Is this obsolete by mistake?

### ISSUE THREAD

**Issue by dungeym-dojo** [googleapis/google-cloud-dotnet#9890]
#### Environment details

  - OS: Mac
  - .NET version: 2.1
  - Package name and version: Google.Cloud.Spanner.Data v4.3.0

#### Steps to reproduce

  1. Use the call `spannerConnection.GetSessionPoolDatabaseStatistics()`
  2. Build the code
  3. See the Obsolete warning, and attempt to find the method the warning says you should use

I'm sure I've missed something but I have looked, and the warning suggests using `GetSessionPoolStatistics` but I can't find this method anywhere.

**Comment by jskeet** [comment]
Thanks for filing this - the method went through a couple of name changes over time, and we missed the message when we renamed.

The non-deprecated method is GetSessionPoolSegmentStatistics.

**Comment by jskeet** [comment]
(I'll fix the message for the next release.)
