### ISSUE TITLE
Automatically trace outgoing requests for traced request

### ISSUE THREAD

**Issue by Zopitirik** [googleapis/google-cloud-dotnet#9941]
Hi,

If request to serviceA is being traced, I would expect the request from serviceA to serviceB should be also tracked without any other configuration.
when I tried and also read both docs and codes, there should be named httpClient to configure AddOutgoingGoogleTraceHandler [docs](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Diagnostics.Common/latest#configuration-3)
Was it done on purpose or is there something I missed?
Should we configure all httpClients one by one or do you have any other solution to work service wide and not need httpClient configurations?

I asked this because we have 4 project and each project has 40 services. :)

I thought to write a httpClient wrapper to send all HTTP requests on it. So I can detect that the request is traced add traceContext to header and move on. ref : https://github.com/googleapis/google-cloud-dotnet/issues/9856#issuecomment-1425617476

**Comment by Zopitirik** [comment]
Hi Amanda,

You understand right, sory for my writing skill :)
I understand your point. Let me explain without projects :) If I fail then ill create minimal projects.

app1 sends req1 -> serviceA sends req2 -> serviceB
    
app1 has services.AddGoogleDiagnosticsForAspNetCore() on startup.cs
serviceA has services.AddGoogleDiagnosticsForAspNetCore() on startupc.s
serviceB has  services.AddGoogleDiagnosticsForAspNetCore() on startup.cs

When I click a button on app1 and send to req1 to ServiceA, [trace list](https://console.cloud.google.com/traces/list) only shows req1 (app1 -> serviceA). Waterfall graph not shows chained request like req2.

So all project have Google.Cloud.Diagnostics.* and configured with "AddGoogleDiagnosticsForAspNetCore".

If you tell me "req2 must be listed on waterfall graph without any other configuration", means that I will create example project :)
**OR**

If I add a line to serviceA startup `services.AddHttpClient("myHttpClient").AddOutgoingGoogleTraceHandler();`
and use "myHttpClient" to send request to ServiceB, waterfall lists req2 too. This is what I wanted to see.
The question is here "should I only use myHttpClient to send request to ServiceB to see req2 on waterfall graph?"

This means; we must always configure named httpClient with **AddOutgoingGoogleTraceHandler** and use this to send requests at each service.

**Comment by amanda-tarafa** [comment]
> If I add a line to serviceA startup services.AddHttpClient("myHttpClient").AddOutgoingGoogleTraceHandler();
> and use "myHttpClient" to send request to ServiceB, waterfall lists req2 too. This is what I wanted to see.
> The question is here "should I only use myHttpClient to send request to ServiceB to see req2 on waterfall graph?"
> 
> This means; we must always configure named httpClient with AddOutgoingGoogleTraceHandler and use this to send requests at each service.


Yes, if you want your trace to propagate (so that all requests on the chain are included on the same trace and shown on the waterfall graph) you need to confgured the each relevant HttpClient with AddOutgoingGoogleTraceHandler.  What happens when you don't do that is that the trace from app1 is not propagated to serviceA, so when the request reaches serviceA a new trace is created, which is also not propagated to serviceB which itself creates a new trace. You can find this 3 traces if you use HttpClients that have not been configured with `AddOutgoingGoogleTraceHandler`.

Note that Google.Cloud.Diagnostics.* does not require you to use named HTTP clients. [The example](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Diagnostics.Common/latest#trace-outgoing-http-requests) shows named HTTP clients for clarity, but from Google.Cloud.Diagnostics.* side of things, you can just use the [basic HTTP client](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0#basic-usage) for all your requests.

**Comment by Zopitirik** [comment]
Ok, I understand the way you go and clear for me. 
Last question for basic HTTP client. 
I want to apply AddOutgoingGoogleTraceHandler to all httpClient in serviceA. This method needs `IHttpClientBuilder`.

AddHttpClient() returns IServiceCollection -> ref : [link](https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L23)

AddHttpClient("") returns IHttpClientBuilder  -> ref: [link](https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L78)

Do you have a suggestion to apply this to all httpClients within the service?

Docs: [link](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientfactoryservicecollectionextensions.addhttpclient?view=dotnet-plat-ext-7.0&viewFallbackFrom=net-7.0#microsoft-extensions-dependencyinjection-httpclientfactoryservicecollectionextensions-addhttpclient(microsoft-extensions-dependencyinjection-iservicecollection))

**Comment by amanda-tarafa** [comment]
You can configure the default client by [adding and configuring a named client with the default name](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientfactoryservicecollectionextensions.addhttpclient?view=dotnet-plat-ext-7.0#microsoft-extensions-dependencyinjection-httpclientfactoryservicecollectionextensions-addhttpclient(microsoft-extensions-dependencyinjection-iservicecollection-system-string)) (see the Remarks section).

That means that your configuration code looks like:

```csharp
services.AddHttpClient(Options.DefaultName).AddOutgoingGoogleTraceHandler();
```

but the code where you use the HTTP client doesn't need to request any specifically named clients.

**Comment by Zopitirik** [comment]
ty, we will go on this way
